Repository OffchainLabs/prysm, pull requests merged in 2018-11, with the labels that each got.

#680 Removed Demo Debug Flags
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/state_transition.go
  beacon-chain/casper/state_transition_test.go
  beacon-chain/casper/validator_test.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/simulator/service.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/types/active_state.go
  beacon-chain/types/active_state_test.go
  beacon-chain/types/block.go
  beacon-chain/types/block_test.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/crystallized_state_test.go
  beacon-chain/utils/flags.go
  genesis.json
Labels: Enhancement, Ready For Review

#681 Dynamic Chain Test Language Package With YAML Parser
  WORKSPACE
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/casper/sharding.go
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/validator_test.go
  beacon-chain/chaintest/BUILD.bazel
  beacon-chain/chaintest/README.md
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/setup_db.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/chaintest/backend/test_format.go
  beacon-chain/chaintest/main.go
  beacon-chain/chaintest/sampletests/basic_fork_choice.yaml
  beacon-chain/chaintest/yaml_test.go
  beacon-chain/db/db.go
  beacon-chain/db/db_test.go
  beacon-chain/internal/BUILD.bazel
  beacon-chain/internal/db_test_util.go
  beacon-chain/params/config.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service_test.go
  beacon-chain/testutil/BUILD.bazel
Labels: Priority: High, Ready For Review

#734 Integers to Bytes Helper Methods
  beacon-chain/casper/BUILD.bazel
  beacon-chain/casper/state_transition_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/schema.go
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/active_state.go
  beacon-chain/types/crystallized_state_test.go
  shared/bytes/BUILD.bazel
  shared/bytes/bytes.go
  shared/bytes/bytes_test.go
Labels: Enhancement, Ready For Review

#719 Synchronize Beacon Node with Spec
  beacon-chain/blockchain/service_test.go
  beacon-chain/casper/sharding.go
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/validator.go
  beacon-chain/casper/validator_test.go
  beacon-chain/params/config.go
  beacon-chain/types/attestation.go
  beacon-chain/types/block.go
  beacon-chain/types/block_test.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/utils/shuffle.go
  proto/beacon/p2p/v1/messages.proto
Labels: Enhancement, Ready For Review

#735 Add basic bootnode
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
Labels: Priority: Medium, Ready For Review

#744 Fixed GetShardAndCommitteesForSlot index out of range
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/validator.go
  beacon-chain/casper/validator_test.go
Labels: Bug, Priority: Critical, Ready For Review

#784 Fixed broken reference link to eth2.0 spec
  beacon-chain/types/active_state_test.go
  docs/DEMO_INFORMATION.md
  shared/hashutil/hash.go
Labels: Bug

#790 Cleanup of Miscellaneous Items Around the Repo
  beacon-chain/attestation/service.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/node.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/types/block.go
  beacon-chain/utils/shuffle.go
Labels: Enhancement, Priority: Low

#796 Standartize params for BeaconChain and Validator projects
  beacon-chain/casper/BUILD.bazel
  beacon-chain/casper/incentives.go
  beacon-chain/casper/incentives_test.go
  beacon-chain/casper/sharding.go
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/state_transition.go
  beacon-chain/casper/state_transition_test.go
  beacon-chain/casper/validator.go
  beacon-chain/casper/validator_test.go
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/params/BUILD.bazel
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/active_state.go
  beacon-chain/types/active_state_test.go
  beacon-chain/types/attestation.go
  beacon-chain/types/block.go
  beacon-chain/types/block_test.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/crystallized_state_test.go
  beacon-chain/utils/BUILD.bazel
  beacon-chain/utils/genesis_json_test.go
  beacon-chain/utils/shuffle.go
  beacon-chain/utils/shuffle_test.go
  shared/params/BUILD.bazel
  shared/params/config.go
  shared/params/config_test.go
  validator/beacon/BUILD.bazel
  validator/beacon/service.go
  validator/params/config.go
  validator/params/config_test.go
  validator/types/BUILD.bazel
  validator/types/collation.go
Labels: Priority: High, Ready For Review

#787 Allow Sync Service to Query State Of Network
  beacon-chain/chaintest/backend/setup_db.go
  beacon-chain/chaintest/main.go
  beacon-chain/db/db.go
  beacon-chain/db/db_test.go
  beacon-chain/internal/db_test_util.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/node/p2p_config.go
  beacon-chain/simulator/service.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/sync/sync-querier/BUILD.bazel
  beacon-chain/sync/sync-querier/service.go
  beacon-chain/sync/sync-querier/service_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  shared/testutil/log.go
Labels: Priority: High, Ready For Review

#815 Implement YAML Based Shuffle Test
  beacon-chain/chaintest/BUILD.bazel
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/chain_test_format.go
  beacon-chain/chaintest/backend/shuffle_test_format.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/chaintest/main.go
  beacon-chain/chaintest/tests/chain-tests/basic_fork_choice.yaml
  beacon-chain/chaintest/tests/shuffle-tests/shuffle.yaml
  beacon-chain/chaintest/yaml_test.go
Labels: Ready For Review

#825 Add relay node tool
  tools/relaynode/BUILD.bazel
  tools/relaynode/relaynode.go
Labels: Ready For Review

#842 Add Bootnode Docker Target
  tools/bootnode/BUILD.bazel
Labels: Ready For Review

#848 Fixed Duplicated Flag and PubKey Empty Issues
  validator/main.go
  validator/node/node.go
Labels: Bug

#863 Define BeaconState Core Type and Protobuf Definition
  beacon-chain/casper/state_transition.go
  beacon-chain/casper/state_transition_test.go
  beacon-chain/core/types/BUILD.bazel
  beacon-chain/core/types/state.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/crystallized_state_test.go
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
Labels: Priority: High, Refactor

#875 Refactor Casper Validators Into Core/Validators Stateless Package
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service_test.go
  beacon-chain/casper/BUILD.bazel
  beacon-chain/casper/sharding.go
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/state_transition.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/active_state.go
  beacon-chain/types/block.go
  beacon-chain/types/crystallized_state.go
Labels: Refactor

#843 Use --batch for gazelle to help with timeouts on buildkite
  scripts/check_gazelle.sh
  scripts/check_visibility.sh
Labels: Ready For Review

#669 Allow Initial Sync to Work with Simulator
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/db.go
  beacon-chain/db/schema.go
  beacon-chain/db/simulator.go
  beacon-chain/db/simulator_test.go
  beacon-chain/db/state.go
  beacon-chain/node/p2p_config.go
  beacon-chain/simulator/service.go
  beacon-chain/simulator/service_test.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/sync/sync-querier/service.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  shared/bytes/bytes.go
  shared/bytes/bytes_test.go
  shared/p2p/service.go
  shared/params/config.go
  shared/slotticker/BUILD.bazel
  shared/slotticker/simulatorticker.go
  shared/slotticker/simulatorticker_test.go
Labels: Priority: High, Ready For Review

#914 Validator Fix
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/active_state.go
Labels: Bug, Priority: Critical

#925 Fixed Validator's Pubkey in Genesis.json
  genesis.json
Labels: Bug

#890 Refactor More Casper Functions Into Beacon-Chain/Core
  beacon-chain/casper/BUILD.bazel
  beacon-chain/casper/state_transition.go
  beacon-chain/core/incentives/incentives.go
  beacon-chain/core/incentives/incentives_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/processing.go
  beacon-chain/core/state/processing_test.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/committees.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/crystallized_state_test.go
Labels: Refactor

#954 Fix service registry breakage
  beacon-chain/sync/sync-querier/service.go
  shared/service_registry.go
Labels: Bug

#953 Merge Active/Crystallized State
  beacon-chain/core/incentives/BUILD.bazel
  beacon-chain/core/incentives/incentives.go
  beacon-chain/core/incentives/incentives_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/processing.go
  beacon-chain/core/state/processing_test.go
  beacon-chain/core/state/state_transition.go
  beacon-chain/core/state/state_transition_test.go
  beacon-chain/core/types/BUILD.bazel
  beacon-chain/core/types/block.go
  beacon-chain/core/types/state.go
  beacon-chain/core/validators/committees.go
  beacon-chain/types/crystallized_state.go
Labels: Refactor

#965 Remove Function to Add SpecialRecord to ActiveState
  beacon-chain/types/active_state.go
  beacon-chain/types/active_state_test.go
Labels: Ready For Review

#827 Add support for connecting via relay nodes
  beacon-chain/main.go
  beacon-chain/node/p2p_config.go
  shared/cmd/flags.go
  shared/p2p/BUILD.bazel
  shared/p2p/addr_factory.go
  shared/p2p/addr_factory_test.go
  shared/p2p/dial_relay_node.go
  shared/p2p/dial_relay_node_test.go
  shared/p2p/feed_example_test.go
  shared/p2p/feed_test.go
  shared/p2p/monitoring.go
  shared/p2p/options.go
  shared/p2p/register_topic_example_test.go
  shared/p2p/service.go
  shared/p2p/service_norace_test.go
  shared/p2p/service_test.go
  validator/node/p2p_config.go
Labels: Priority: Medium, Ready For Review

#968 Added flag for p2p port
  beacon-chain/main.go
  beacon-chain/node/p2p_config.go
  shared/cmd/flags.go
  shared/p2p/BUILD.bazel
  shared/p2p/options.go
  shared/p2p/options_test.go
  shared/p2p/service.go
  validator/node/p2p_config.go
Labels: Ready For Review

#969 Bootnode query tool
  shared/p2p/dial_relay_node.go
  shared/p2p/dial_relay_node_test.go
  tools/bootnode-query/BUILD.bazel
  tools/bootnode-query/main.go
Labels: Ready For Review

#973 Bootstrap the DHT service
  shared/p2p/BUILD.bazel
  shared/p2p/dial_relay_node.go
  shared/p2p/dial_relay_node_test.go
  shared/p2p/discovery.go
  shared/p2p/service.go
Labels: Ready For Review

#980 Added kubernetes config map update for deployvrc
  WORKSPACE
  contracts/validator-registration-contract/deployVRC/BUILD.bazel
  contracts/validator-registration-contract/deployVRC/deployVRC.go
Labels: Ready For Review

#972 Auto Clean Block Vote Cache
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block_vote_cache.go
  beacon-chain/db/block_vote_cache_test.go
  beacon-chain/db/cleanup_history.go
  beacon-chain/db/cleanup_history_test.go
  beacon-chain/db/db.go
  beacon-chain/db/schema.go
  beacon-chain/dbcleanup/BUILD.bazel
  beacon-chain/dbcleanup/service.go
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/main.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/utils/flags.go
Labels: Ready For Review

#989 Align Constant Variables With Latest Spec Changes
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  shared/params/config.go
Labels: Ready For Review

#991 Kubernetes 4 of ?? - rotate secrets
  WORKSPACE
  k8s/BUILD.bazel
  k8s/geth/BUILD.bazel
  k8s/geth/bootnode.encrypted_secret.yaml
  k8s/geth/bootnode.secret.yaml
  k8s/geth/ethstats.encrypted_secret.yaml
  k8s/geth/ethstats.secret.yaml
  k8s/geth/faucet.deploy.yaml
  k8s/geth/faucet.encrypted_secret.yaml
  k8s/geth/faucet.secret.yaml
  k8s/geth/genesis.config.yaml
  k8s/geth/genesis.secret.yaml
  k8s/geth/miners.deploy.yaml
  k8s/geth/nodes.deploy.yaml
  k8s/monitoring/grafana.encrypted_secret.yaml
  k8s/monitoring/manifests-all.yaml
  k8s/nginx/BUILD.bazel
  k8s/nginx/default-server-secret-encrypted.yaml
  k8s/nginx/default-server-secret.yaml
  tools/BUILD.bazel
  tools/kubesec.bzl
Labels: Ready For Review

#1007 Return Unused Error in State_transition
  beacon-chain/core/state/state_transition.go
Labels: Bug
