Repository OffchainLabs/prysm, pull requests merged in 2018-10, with the labels that each got.

#588 Fixed Sync With Simulator
  beacon-chain/attestation/service.go
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/core.go
  beacon-chain/blockchain/core_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/validator.go
  beacon-chain/casper/validator_test.go
  beacon-chain/rpc/service.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  beacon-chain/simulator/service_test.go
  beacon-chain/types/active_state.go
  beacon-chain/types/attestation.go
  beacon-chain/types/block.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/interfaces.go
  validator/beacon/service.go
  validator/beacon/service_test.go
  validator/params/config.go
Labels: Bug

#602 Fixed Simulator Can't get ParentSlot
  beacon-chain/blockchain/core.go
  beacon-chain/blockchain/core_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/rpc/service.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  beacon-chain/simulator/service_test.go
  beacon-chain/sync/service.go
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/block.go
  beacon-chain/types/interfaces.go
  beacon-chain/utils/clock.go
  validator/beacon/BUILD.bazel
  validator/beacon/service.go
  validator/beacon/service_test.go
  validator/params/config.go
Labels: Bug

#606 Beacon Node Determines Slot From Genesis Block if ChainState Detected
  beacon-chain/blockchain/service.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/types/block.go
  beacon-chain/types/block_test.go
Labels: Beacon Chain

#607 Fixed Simulator Slot Alignment
  beacon-chain/params/config.go
  beacon-chain/simulator/service.go
  beacon-chain/simulator/service_test.go
  beacon-chain/types/interfaces.go
Labels: Bug

#609 Fix Validator Assignment
  beacon-chain/params/config.go
  beacon-chain/simulator/service.go
  beacon-chain/types/crystallized_state.go
Labels: Bug

#599 Update Documentation to Reflect Latest Changes, Demo Instructions
  README.md
  docs/DEMO_INFORMATION.md
  docs/MAINCHAIN.md
  docs/VALIDATOR_REGISTRATION.md
Labels: In Progress

#611 Fix Shuffling Algorithm
  beacon-chain/utils/shuffle.go
Labels: Bug, Enhancement

#596 Update Rewards to Align with Spec
  beacon-chain/casper/incentives.go
  beacon-chain/casper/incentives_test.go
  beacon-chain/types/crystallized_state_test.go
  shared/BUILD.bazel
  shared/math_helper.go
  shared/math_helper_test.go
Labels: Ready For Review

#582 Refactor to Create DB Package
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/core.go
  beacon-chain/attestation/core_test.go
  beacon-chain/attestation/service.go
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/core.go
  beacon-chain/blockchain/core_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/attestation.go
  beacon-chain/db/attestation_test.go
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
  beacon-chain/db/db.go
  beacon-chain/db/db_test.go
  beacon-chain/db/schema.go
  beacon-chain/db/schema_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  beacon-chain/simulator/service_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/types/attestation.go
  beacon-chain/types/attestation_test.go
  beacon-chain/types/block.go
  beacon-chain/types/block_test.go
  beacon-chain/utils/BUILD.bazel
  beacon-chain/utils/slot_interval.go
Labels: Ready For Review

#624 Add SpecialRecord Type and Updated Config
  beacon-chain/casper/BUILD.bazel
  beacon-chain/casper/incentives.go
  beacon-chain/casper/incentives_test.go
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/validator.go
  beacon-chain/params/BUILD.bazel
  beacon-chain/params/config.go
  beacon-chain/params/config_test.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/crystallized_state_test.go
  beacon-chain/utils/shuffle.go
  beacon-chain/utils/shuffle_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: Beacon Chain, Ready For Review

#628 Align Block and State Field Names with Spec
  beacon-chain/blockchain/service_test.go
  beacon-chain/casper/BUILD.bazel
  beacon-chain/casper/incentives.go
  beacon-chain/casper/incentives_test.go
  beacon-chain/casper/sharding.go
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/validator.go
  beacon-chain/casper/validator_test.go
  beacon-chain/db/attestation_test.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state_test.go
  beacon-chain/params/config.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/simulator/service.go
  beacon-chain/simulator/service_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/active_state.go
  beacon-chain/types/active_state_test.go
  beacon-chain/types/attestation.go
  beacon-chain/types/attestation_test.go
  beacon-chain/types/block.go
  beacon-chain/types/block_test.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/crystallized_state_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  validator/attester/service.go
  validator/attester/service_test.go
  validator/proposer/service.go
  validator/proposer/service_test.go
Labels: Ready For Review

#640 Clean Up Todos and Add in Issue Checker
  beacon-chain/blockchain/service.go
  beacon-chain/db/schema.go
  beacon-chain/types/crystallized_state.go
  scripts/check-todo.sh
  shared/p2p/service.go
  validator/proposer/service.go
Labels: Enhancement

#647 [WIP] Partial fix for the validator code
  beacon-chain/casper/validator.go
  beacon-chain/rpc/service.go
  genesis.json
Labels: In Progress

#645 Implement Validator Rotation during State Recalculation
  beacon-chain/casper/validator.go
  beacon-chain/casper/validator_test.go
  beacon-chain/params/config.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/crystallized_state_test.go
Labels: Priority: High, Ready For Review

#641 Refactor Crystallized State
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/casper/BUILD.bazel
  beacon-chain/casper/sharding.go
  beacon-chain/casper/sharding_test.go
  beacon-chain/casper/state_transition.go
  beacon-chain/casper/state_transition_test.go
  beacon-chain/casper/validator.go
  beacon-chain/casper/validator_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/db.go
  beacon-chain/db/db_test.go
  beacon-chain/db/state_test.go
  beacon-chain/rpc/service_test.go
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/active_state.go
  beacon-chain/types/active_state_test.go
  beacon-chain/types/block_test.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/crystallized_state_test.go
  beacon-chain/utils/BUILD.bazel
  beacon-chain/utils/genesis_json.go
  beacon-chain/utils/genesis_json_test.go
  beacon-chain/utils/vote_cache.go
Labels: Priority: Medium, Ready For Review, Refactor

#651 Implement RANDAO From Spec
  beacon-chain/blockchain/service_test.go
  beacon-chain/casper/BUILD.bazel
  beacon-chain/casper/validator.go
  beacon-chain/params/config.go
  beacon-chain/rpc/service.go
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/active_state.go
  beacon-chain/types/block.go
  beacon-chain/types/block_test.go
  beacon-chain/types/crystallized_state.go
  beacon-chain/types/crystallized_state_test.go
Labels: Priority: High, Ready For Review

#667 Implement Validator Exiting Logic
  beacon-chain/casper/state_transition.go
  beacon-chain/casper/state_transition_test.go
  beacon-chain/casper/validator.go
  beacon-chain/casper/validator_test.go
  beacon-chain/params/config.go
  beacon-chain/types/crystallized_state.go
Labels: Priority: Medium, Ready For Review

#660 Implemented Update Ancestor Hashes Function
  beacon-chain/types/block.go
  beacon-chain/types/block_test.go
Labels: Priority: Medium

#676 BLS Public API
  shared/bls/BUILD.bazel
  shared/bls/bls.go
  shared/bls/bls_test.go
Labels: Priority: High

#678 Remove Unnecessary Interfaces, Clean Up Some Naming
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  beacon-chain/types/BUILD.bazel
  beacon-chain/types/interfaces.go
  validator/main.go
  validator/node/node.go
  validator/node/node_test.go
  validator/types/BUILD.bazel
  validator/types/interfaces.go
Labels: Enhancement

#679 Discard Block With Slot Lower Than LastFinalizedSlot
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
Labels: Enhancement

#690 Fix LibP2P Global Proto Bug on Travis
  WORKSPACE
  shared/p2p/BUILD.bazel
  shared/p2p/service_test.go
Labels: Bug

#696 Integrate Herumi's C Pairing Library for BLS12-381
  .travis.yml
  WORKSPACE
  shared/bls/BUILD.bazel
  shared/bls/mcl.go
  shared/bls/mcl_test.go
Labels: Priority: High

#713 Disable Codecov Patch As It Is Unreliable
  .codecov.yml
  beacon-chain/db/attestation.go
  beacon-chain/db/block.go
  beacon-chain/db/db.go
  beacon-chain/node/node_test.go
Labels: CI, Enhancement

#708 Align Error String Consistency
  beacon-chain/blockchain/service_test.go
  beacon-chain/casper/validator.go
  beacon-chain/db/block.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/service.go
  beacon-chain/types/active_state.go
  beacon-chain/types/block.go
  validator/beacon/service.go
  validator/types/shard.go
  validator/types/shard_test.go
Labels: Enhancement, Ready For Review
