Repository OffchainLabs/prysm, pull requests merged in 2018-06, with the labels that each got.

#146 Sharding/node: Address Logging To Hex
  sharding/node/utils.go
Labels: Bug

#147 Serialization Perf
  sharding/collation.go
  sharding/collation_test.go
  sharding/utils/marshal.go
  sharding/utils/marshal_test.go
Labels: Enhancement

#149 Refactor Sharding Node According to New Design
  cmd/geth/shardingcmd.go
  sharding/collation.go
  sharding/database/database.go
  sharding/database/inmemory.go
  sharding/interfaces.go
  sharding/mainchain/smc_client.go
  sharding/mainchain/smc_client_test.go
  sharding/mainchain/utils.go
  sharding/node/backend.go
  sharding/node/backend_test.go
  sharding/node/node.go
  sharding/notary/notary.go
  sharding/notary/service.go
  sharding/notary/service_test.go
  sharding/observer/service.go
  sharding/observer/service_test.go
  sharding/p2p/service.go
  sharding/p2p/service_test.go
  sharding/params/chainConfig.go
  sharding/proposer/service.go
  sharding/proposer/service_test.go
  sharding/shard.go
  sharding/shard_test.go
  sharding/txpool/service.go
  sharding/txpool/service_test.go
  sharding/utils/marshal.go
Labels: Intermediate, Phase 1

#167 Implement ShardChainDB Into the ShardEthereum Instance
  sharding/database/database.go
  sharding/database/database_test.go
  sharding/database/inmemory.go
  sharding/database/inmemory_test.go
  sharding/node/backend.go
  sharding/notary/service.go
  sharding/observer/service.go
  sharding/proposer/service.go
  sharding/shard.go
  sharding/shard_test.go
Labels: Needs Review

#111 Implement Proposers Submitting Collations onto SMC
  sharding/collation.go
  sharding/mainchain/smc_client.go
  sharding/notary/notary.go
  sharding/notary/service_test.go
  sharding/proposer/proposer.go
  sharding/proposer/service.go
  sharding/proposer/service_test.go
Labels: Needs Review

#168 Constant variable in SMC for notary's challenge period
  sharding/contracts/sharding_manager.go
  sharding/contracts/sharding_manager.sol
Labels: Needs Review

#169 Pass ShardID from CLI to Actor Service
  README.md
  cmd/geth/main.go
  cmd/geth/shardingcmd.go
  cmd/utils/flags.go
  sharding/node/backend.go
  sharding/observer/service.go
  sharding/proposer/service.go
Labels: Needs Review

#170 Graceful Shutdown on SIGINT and Non-Blocking Services
  sharding/interfaces.go
  sharding/node/backend.go
  sharding/notary/service.go
  sharding/observer/service.go
  sharding/p2p/service.go
  sharding/proposer/service.go
  sharding/txpool/service.go
Labels: Enhancement

#173 Use shardConfig Across Code
  cmd/utils/flags.go
  sharding/config.go
  sharding/config_test.go
  sharding/contracts/sharding_manager.go
  sharding/contracts/sharding_manager.sol
  sharding/contracts/sharding_manager_test.go
  sharding/mainchain/smc_client.go
  sharding/mainchain/utils.go
  sharding/node/backend.go
  sharding/notary/notary.go
  sharding/notary/service.go
  sharding/notary/service_test.go
  sharding/params/chainConfig.go
  sharding/params/config.go
  sharding/params/config_test.go
  sharding/proposer/proposer.go
  sharding/proposer/service.go
  sharding/proposer/service_test.go
Labels: Needs Review

#184 Simplify Interfaces Into Smaller, Useful Ones
  sharding/mainchain/interfaces.go
  sharding/mainchain/smc_client.go
  sharding/mainchain/smc_client_test.go
  sharding/notary/notary.go
  sharding/notary/service.go
  sharding/notary/service_test.go
  sharding/proposer/proposer.go
  sharding/proposer/service.go
  sharding/proposer/service_test.go
Labels: Enhancement

#171 Random transaction generator
  sharding/proposer/service.go
  sharding/proposer/service_test.go
  sharding/txpool/service.go
Labels: In Progress, Phase 1

#186 Separating out Transaction Receipt functionality
  sharding/mainchain/smc_client.go
  sharding/mainchain/smc_client_test.go
  sharding/notary/service_test.go
  sharding/proposer/service_test.go
Labels: Enhancement, Needs Review

#131 Implementation for the Notary to Vote on Collations
  sharding/contracts/sharding_manager.go
  sharding/contracts/sharding_manager.sol
  sharding/contracts/types.go
  sharding/mainchain/interfaces.go
  sharding/notary/notary.go
  sharding/notary/service.go
  sharding/notary/service_test.go
  sharding/proposer/service_test.go
  sharding/shard.go
  sharding/shard_test.go
Labels: Needs Review, Phase 1

#172 Handle and Simulate Collation Body Requests/Responses
  sharding/collation.go
  sharding/interfaces.go
  sharding/internal/README.md
  sharding/mainchain/interfaces.go
  sharding/mainchain/smc_client.go
  sharding/node/backend.go
  sharding/observer/service.go
  sharding/p2p/feed.go
  sharding/p2p/feed_example_test.go
  sharding/p2p/feed_test.go
  sharding/p2p/messages/messages.go
  sharding/proposer/proposer.go
  sharding/proposer/service.go
  sharding/proposer/service_test.go
  sharding/simulator/service.go
  sharding/simulator/service_test.go
  sharding/syncer/handlers.go
  sharding/syncer/handlers_test.go
  sharding/syncer/service.go
  sharding/syncer/service_test.go
Labels: Intermediate, Phase 1

#196 Include Proposer Signature in Collation Record in SMC
  sharding/contracts/sharding_manager.go
  sharding/contracts/sharding_manager.sol
  sharding/contracts/sharding_manager_test.go
  sharding/mainchain/interfaces.go
  sharding/proposer/proposer.go
  sharding/simulator/service_test.go
  sharding/syncer/handlers_test.go
Labels: Bug, Needs Review

#211 Use Internal Mock Client for Proposer Tests
  sharding/proposer/service_test.go
Labels: Needs Review

#212 Use Internal Mock Client for Notary Tests
  sharding/internal/client_helper.go
  sharding/notary/service_test.go
Labels: Needs Review

#207 Use Small Interfaces to Fix Nil Pointer Errors in Simulator/Syncer Tests
  sharding/node/backend.go
  sharding/simulator/service.go
  sharding/simulator/service_test.go
  sharding/syncer/service.go
  sharding/syncer/service_test.go
Labels: Needs Review

#218 Add debug flags to shardingcmd
  cmd/geth/shardingcmd.go
Labels: Enhancement, Needs Review

#216 Simplify Goroutines for Better Testing
  sharding/database/database.go
  sharding/database/database_test.go
  sharding/database/inmemory.go
  sharding/node/backend.go
  sharding/p2p/service.go
  sharding/simulator/service.go
  sharding/simulator/service_test.go
  sharding/syncer/service.go
  sharding/syncer/service_test.go
  sharding/utils/service.go
  sharding/utils/service_test.go
Labels: Enhancement

#217 Simplify Service Registry, Pass in References as Dependencies to Prevent Nil Pointer Errors
  sharding/interfaces.go
  sharding/node/backend.go
  sharding/notary/service.go
  sharding/observer/service.go
  sharding/observer/service_test.go
  sharding/proposer/service.go
  sharding/simulator/service.go
  sharding/simulator/service_test.go
  sharding/syncer/service.go
Labels: Intermediate

#220 Check AddHeader Transaction Gets Mined
  sharding/proposer/proposer.go
  sharding/proposer/service.go
  sharding/proposer/service_test.go
  sharding/syncer/handlers_test.go
Labels: Needs Review
