Repository OffchainLabs/prysm, pull requests merged in 2018-12, with the labels that each got.

#1030 Update ValidatorRecord Proto
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/incentives/incentives.go
  beacon-chain/core/state/processing_test.go
  beacon-chain/core/state/validity_conditions.go
  beacon-chain/core/state/validity_conditions_test.go
  beacon-chain/core/types/state.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Refactor

#1044 Updated Genesis JSON and Fixed Test
  BUILD.bazel
  beacon-chain/utils/BUILD.bazel
  beacon-chain/utils/genesis_json.go
  beacon-chain/utils/genesis_json_test.go
  genesis.json
Labels: Ready For Review

#1054 Change to Golang Crypto Library
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/db/block.go
  beacon-chain/dbcleanup/service.go
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/node/node.go
  shared/hashutil/BUILD.bazel
  shared/hashutil/hash.go
  shared/hashutil/hash_test.go
Labels: Ready For Review

#1055 Update Shuffle Function
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/core/state/state_transition_test.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/simulator/service_test.go
  beacon-chain/utils/shuffle.go
  beacon-chain/utils/shuffle_test.go
  shared/params/config.go
Labels: Ready For Review

#1039 Preliminary Implementation of SSZ
  shared/ssz/BUILD.bazel
  shared/ssz/decode.go
  shared/ssz/decode_test.go
  shared/ssz/encode.go
  shared/ssz/encode_test.go
  shared/ssz/encoder_decoder_lib.go
Labels: Priority: High, Ready For Review

#1075 Add new ShardAndCommitteesAtSlot from spec
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review

#1082 Use Validator Status in Proto
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/incentives/incentives_test.go
  beacon-chain/core/state/processing_test.go
  beacon-chain/core/state/state_transition_test.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/utils/genesis_json_test.go
  genesis.json
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
  shared/params/config_test.go
Labels: Ready For Review

#1076 Implement Proposer Slashing Block Operations
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/validators/validator.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review

#1084 Update Wrapper for Beacon State
  beacon-chain/core/types/BUILD.bazel
  beacon-chain/core/types/state.go
Labels: Ready For Review

#1087 Helper Functions to Retrieve Total Validator Balances
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/state/state_transition.go
  beacon-chain/core/state/state_transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  shared/params/config.go
Labels: Ready For Review

#1086 Implement Casper Slashing Block Operations
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
  shared/slices/BUILD.bazel
  shared/slices/slice.go
  shared/slices/slice_test.go
Labels: Ready For Review

#1079 SSZ: Support More Types
  shared/ssz/BUILD.bazel
  shared/ssz/decode.go
  shared/ssz/decode_test.go
  shared/ssz/doc.go
  shared/ssz/encode.go
  shared/ssz/encode_test.go
  shared/ssz/example_and_test.go
Labels: Ready For Review

#1088 Implement Attestation Processing Block Operations
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/processing.go
  beacon-chain/core/state/processing_test.go
  beacon-chain/core/state/state_transition_test.go
  beacon-chain/core/types/state.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review

#1103 Get Epoch (&Boundary) Attestations Helper Functions
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
Labels: Ready For Review

#1097 Implement Process Exits Block Operation
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  shared/params/config.go
Labels: Ready For Review

#1105 Implement Process Block Receipt Root Records
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
Labels: Priority: High, Ready For Review

#1111 Implement Attestation Participants Helper Function
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/committees.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/db/db.go
  shared/mathutil/math_helper.go
  shared/mathutil/math_helper_test.go
  shared/p2p/service.go
Labels: Ready For Review

#1110 1.use 0.5.1 compiler, 2.bug fixing, and 3.align spec2.0
  contracts/validator-registration-contract/validator_registration.go
  contracts/validator-registration-contract/validator_registration.sol
  contracts/validator-registration-contract/validator_registration_test.go
Labels: Ready For Review

#1115 Boundary Attestation and Balances Helper functions
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  shared/slices/slice.go
  shared/slices/slice_test.go
Labels: Ready For Review

#1083 Partial Implementation of the Slot Processing Routine
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/randao/BUILD.bazel
  beacon-chain/core/randao/randao.go
  beacon-chain/core/randao/randao_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/processing.go
  beacon-chain/core/state/state_transition.go
  beacon-chain/core/state/validity_conditions.go
  beacon-chain/core/state/validity_conditions_test.go
  beacon-chain/core/types/state.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Priority: High, Ready For Review

#1136 Update kubesec to use canonical repo
  WORKSPACE
Labels: Ready For Review

#1138 Remove Deprecated Spec Logic
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/blocks/validity_conditions_test.go
  beacon-chain/core/incentives/BUILD.bazel
  beacon-chain/core/incentives/incentives.go
  beacon-chain/core/incentives/incentives_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/processing.go
  beacon-chain/core/state/processing_test.go
  beacon-chain/core/state/state_transition.go
  beacon-chain/core/state/state_transition_test.go
  beacon-chain/core/state/validity_conditions.go
  beacon-chain/core/state/validity_conditions_test.go
  beacon-chain/core/types/state.go
  beacon-chain/core/types/state_test.go
Labels: Priority: High, Ready For Review

#1114 SSZ: Support Pointer and Array
  shared/ssz/README.md
  shared/ssz/decode.go
  shared/ssz/decode_test.go
  shared/ssz/encode.go
  shared/ssz/encode_test.go
  shared/ssz/encoder_decoder_lib.go
  shared/ssz/example_and_test.go
Labels: Ready For Review

#1137 Replace Types of Block Primitives With Proto Generated Types
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/blocks/validity_conditions_test.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state_transition.go
  beacon-chain/core/types/BUILD.bazel
  beacon-chain/core/types/block.go
  beacon-chain/core/types/state.go
  beacon-chain/core/types/state_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/dbcleanup/BUILD.bazel
  beacon-chain/dbcleanup/service.go
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/querier.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
Labels: Priority: Medium, Ready For Review

#1145 Implemented Rest of Epoch Helpers
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  shared/bytes/bytes.go
Labels: Ready For Review

#1164 Deprecate types.BeaconState with pb.BeaconState Generated Proto
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/blocks/validity_conditions_test.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/incentives/incentives_test.go
  beacon-chain/core/randao/BUILD.bazel
  beacon-chain/core/randao/randao.go
  beacon-chain/core/randao/randao_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/types/BUILD.bazel
  beacon-chain/core/types/state.go
  beacon-chain/core/types/state_test.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/dbcleanup/BUILD.bazel
  beacon-chain/dbcleanup/service.go
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  beacon-chain/simulator/service_test.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync.go
  shared/p2p/service_test.go
  shared/ssz/encode.go
  validator/internal/beacon_service_mock.go
Labels: Priority: High, Ready For Review, Refactor

#1158 Epoch Processing: Receipt Root, Justification and Finalization
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/state.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review

#1167 Implement Crosslink Processing
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  proto/beacon/p2p/v1/messages.pb.go
Labels: Ready For Review

#1172 Updating Genesis Block to Spec
  beacon-chain/blockchain/service.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/simulator/service.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  shared/params/config.go
Labels: Priority: Medium, Ready For Review

#1119 Add Batch Syncing for Initial Sync
  beacon-chain/node/p2p_config.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  beacon-chain/simulator/service_test.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: Priority: Medium, Ready For Review

#1173 Rewards/Penalties for Justification and Finalization Case 1
  beacon-chain/core/balances/BUILD.bazel
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  shared/slices/slice.go
  shared/slices/slice_test.go
Labels: Ready For Review

#1135 Integrate Block Operations Into State Transition
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/sync/initial-sync/service.go
Labels: Priority: High, Ready For Review

#1175 Rewards/Penalties for Justification and Finalization Case 2
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/balances/rewards_penalties_test.go
Labels: Ready For Review

#1179 Implement Validator Registry Delta Chain Tip Helper for Validator Rotation
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review

#1176 Update State Transitions to Process Block Roots
  beacon-chain/blockchain/service.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/state/transition.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/hashutil/BUILD.bazel
  shared/hashutil/merkleRoot.go
  shared/hashutil/merkleRoot_test.go
  shared/params/config.go
Labels: Ready For Review

#1104 Verify Block Proposer RANDAO
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/randao/BUILD.bazel
  beacon-chain/core/randao/randao.go
  beacon-chain/core/randao/randao_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/hashutil/hash.go
Labels: Priority: High, Ready For Review

#1181 Helpers for Updating Validator Status
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review

#1199 Implement Verify Merkle Branch
  shared/trie/BUILD.bazel
  shared/trie/merkle.go
  shared/trie/merkle_test.go
Labels: Ready For Review

#1200 Implement Process Deposit Validator Helper Function
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review

#1198 Fix Merkle Root Helper
  shared/hashutil/merkleRoot.go
  shared/hashutil/merkleRoot_test.go
Labels: Ready For Review

#1183 Health check endpoints for services
  beacon-chain/attestation/service.go
  beacon-chain/blockchain/service.go
  beacon-chain/dbcleanup/service.go
  beacon-chain/node/node.go
  beacon-chain/powchain/service.go
  beacon-chain/rpc/service.go
  beacon-chain/simulator/service.go
  beacon-chain/sync/service.go
  shared/p2p/adapter/metric/metric_test.go
  shared/p2p/monitoring.go
  shared/p2p/service.go
  shared/p2p/service_test.go
  shared/prometheus/BUILD.bazel
  shared/prometheus/logrus_collector_test.go
  shared/prometheus/service.go
  shared/prometheus/service_test.go
  shared/service_registry.go
  shared/service_registry_test.go
  validator/attester/service.go
  validator/beacon/service.go
  validator/proposer/service.go
  validator/rpcclient/service.go
  validator/txpool/service.go
Labels: Ready For Review

#1215 Disable race detection on go docker images
  beacon-chain/BUILD.bazel
  contracts/validator-registration-contract/deployVRC/BUILD.bazel
  tools/bootnode/BUILD.bazel
  tools/relaynode/BUILD.bazel
  validator/BUILD.bazel
Labels: Ready For Review

#1208 Implement Get Initial Genesis State
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/validators/validator.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review
