Repository OffchainLabs/prysm, pull requests merged in 2019-07, with the labels that each got.

#2876 Update Configs for Freeze
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice_reorg_test.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/cache/seed_test.go
  beacon-chain/cache/total_balance_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/spectest/crosslinks_test.yaml.go
  beacon-chain/core/epoch/spectest/registry_updates.yaml.go
  beacon-chain/core/helpers/block.go
  beacon-chain/core/helpers/block_test.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/spectest/sanity_slots_test.yaml.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/state_metrics.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server_test.go
  contracts/deposit-contract/deployContract/deployContract.go
  proto/testing/ssz_minimal.yaml.go
  shared/params/config.go
  shared/testutil/helpers.go
  validator/client/validator_metrics.go
Labels: Ready For Review

#2867 Update State Transition Function
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
Labels: Ready For Review, spec-v0.8

#2888 Change Base Reward Factor
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/block.go
  beacon-chain/core/helpers/randao_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  shared/params/config.go
Labels: Ready For Review, spec-v0.8

#2893 Update Freeze Spec Simplification Section - part 1
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  shared/sliceutil/slice.go
  shared/sliceutil/slice_test.go
Labels: Ready For Review, spec-v0.8

#2895 Update Helper Function's Pseudocode Definitions
  beacon-chain/attestation/service.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/helpers/block.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/utils/shuffle.go
  shared/bls/bls.go
Labels: Ready For Review, spec-v0.8

#2898 Make Constants Explicit and Minor Cleanups
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/validator_server_test.go
  shared/params/config.go
  shared/sliceutil/slice.go
Labels: Ready For Review, spec-v0.8

#2900 Move Block Operation Length Checks to ProcessOperations
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
Labels: Ready For Review, spec-v0.8

#2902 Proto Fields Reordering
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review, spec-v0.8

#2889 Slashing Penalty Calculation Change
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/bytesutil/bytes.go
  shared/mathutil/math_helper.go
  shared/mathutil/math_helper_test.go
  shared/params/config.go
Labels: Ready For Review, spec-v0.8

#2916 Update BLS Domain
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  shared/bls/bls.go
  shared/bytesutil/bytes.go
  shared/bytesutil/bytes_test.go
  shared/keystore/BUILD.bazel
  shared/keystore/deposit_input.go
  shared/keystore/deposit_input_test.go
  shared/params/BUILD.bazel
  shared/params/config.go
Labels: Ready For Review, spec-v0.8

#2907 Fix Spec tests
  WORKSPACE
  beacon-chain/core/blocks/spectest/block_processing_test.go
  beacon-chain/core/blocks/spectest/blocks_mainnet.yaml.go
  beacon-chain/core/blocks/spectest/blocks_minimal.yaml.go
  beacon-chain/core/epoch/spectest/BUILD.bazel
  beacon-chain/core/epoch/spectest/crosslinks_test.yaml.go
  beacon-chain/core/epoch/spectest/epoch_processing_crosslink_test.go
  beacon-chain/core/epoch/spectest/epoch_processing_registry_test.go
  beacon-chain/core/epoch/spectest/registry_updates.yaml.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/state/spectest/BUILD.bazel
  beacon-chain/core/state/spectest/sanity_slots_test.yaml.go
  beacon-chain/core/state/spectest/slot_processing_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/utils/spectest/BUILD.bazel
  beacon-chain/utils/spectest/shuffle_yaml_test.go
  beacon-chain/utils/spectest/shuffling_full.yaml
  beacon-chain/utils/spectest/shuffling_minimal.yaml
Labels: Ready For Review, spec-v0.8

#2890 Freeze Spec Bug Fixes
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/state.go
Labels: Ready For Review, spec-v0.8

#2908 Add Max Size Tag for Protobuf Fields
  WORKSPACE
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  third_party/BUILD.bazel
  third_party/com_github_gogo_protobuf-equal.patch
Labels: Ready For Review, spec-v0.8

#2926 Update Proto Fields
  WORKSPACE
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review, spec-v0.8

#2906 Update Validator Workflow
  beacon-chain/core/helpers/committee.go
  beacon-chain/rpc/validator_server.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  validator/client/BUILD.bazel
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
Labels: Ready For Review, spec-v0.8

#2924 Fix SSZ Compatibility Test
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  proto/testing/BUILD.bazel
  proto/testing/ssz_compatibility_test.go
  proto/testing/ssz_protobuf.yaml.go
  proto/testing/tags_test.go
  shared/testutil/BUILD.bazel
  shared/testutil/is_empty.go
Labels: Blocked, spec-v0.8

#2930 Epoch Process Slashings Spec Tests
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/spectest/BUILD.bazel
  beacon-chain/core/epoch/spectest/crosslink_test.go
  beacon-chain/core/epoch/spectest/registry_test.go
  beacon-chain/core/epoch/spectest/slashings_test.go
Labels: Ready For Review, spectest

#2931 Add ssz compatibility tests for signing root
  beacon-chain/core/blocks/spectest/deposit_test.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/powchain/service.go
  proto/testing/ssz_compatibility_test.go
  shared/cmd/flags.go
Labels: spectest

#2901 Final updates spec tests
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/spectest/BUILD.bazel
  beacon-chain/core/epoch/spectest/final_updates_test.go
  proto/beacon/p2p/v1/types.pb.go
Labels: spectest

#2945 Remove Block Signing Root
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_reorg_test.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/transition.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/initial-sync/sync_blocks.go
  beacon-chain/sync/receive_block.go
  beacon-chain/sync/receive_block_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  shared/blockutil/BUILD.bazel
  shared/blockutil/beacon_block.go
Labels: Bug, Priority: High, Ready For Review, spec-v0.8

#2952 Add Tests for Genesis Deposits Caching
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/deposit.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
  shared/params/config.go
Labels: Ready For Review, spec-v0.8

#2961 Minor runtime fixes
  beacon-chain/core/state/transition.go
  beacon-chain/rpc/validator_server.go
  contracts/deposit-contract/drainContracts/drainContracts.go
  shared/params/config.go
Labels: spec-v0.8

#2978 Align prysm to spec v0.8.1
  WORKSPACE
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/node/node.go
  beacon-chain/operations/service.go
  beacon-chain/powchain/service.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/sharding/p2p/v1/messages.pb.go
Labels: Ready For Review

#2983 Update pubkey logging of validators
  validator/client/validator_attest.go
  validator/client/validator_propose.go
Labels: Ready For Review

#2984 Fix proposer assignment
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/node/node.go
  beacon-chain/powchain/log_processing.go
  validator/client/validator_attest.go
  validator/client/validator_propose.go
Labels: Ready For Review

#2986 More Runtime Fixes
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
Labels: Ready For Review, spec-v0.8

#2999 Fix Querier to handle Deposit Logs Race
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
  beacon-chain/sync/querier.go
  beacon-chain/sync/querier_test.go
Labels: Ready For Review, spec-v0.8

#2998 Update Protobufs to Match Ethereum APIs
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/BUILD.bazel
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/attestation.proto
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_block.proto
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/node.proto
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.proto
  proto/sharding/p2p/v1/messages.pb.go
Labels: Ready For Review

#2973 Implement Proposer Signature
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
Labels: Ready For Review

#3004 Schema of BeaconBlockHeader has an extra column
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.proto
  proto/eth/v1alpha1/beacon_chain.pb.go
Labels: Ready For Review

#3044 Resolve Proto Lint Issues
  .travis.yml
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/eth/v1alpha1/BUILD.bazel
  proto/eth/v1alpha1/_compatibility/BUILD.bazel
  proto/eth/v1alpha1/_compatibility/compatability_test.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/testing/test.pb.go
  shared/testutil/json_to_pb_converter_test.go
Labels: Ready For Review

#3049 Implement Node gRPC Server
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/deposit_contract.go
  beacon-chain/db/deposit_contract_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/node_server.go
  beacon-chain/rpc/node_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
Labels: Ready For Review

#3050 Implement ListValidatorBalances gRPC server
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
Labels: Ready For Review

#3046 Standardize Flags at Top Level and Remove Deprecated Utils
  beacon-chain/BUILD.bazel
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/shuffle.go
  beacon-chain/core/helpers/shuffle_test.go
  beacon-chain/core/helpers/spectest/BUILD.bazel
  beacon-chain/core/helpers/spectest/shuffle_test_format.go
  beacon-chain/core/helpers/spectest/shuffle_yaml_test.go
  beacon-chain/flags/BUILD.bazel
  beacon-chain/flags/flags.go
  beacon-chain/main.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/node/p2p_config.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/usage.go
  beacon-chain/utils/BUILD.bazel
  beacon-chain/utils/clock.go
  beacon-chain/utils/clock_test.go
  validator/BUILD.bazel
  validator/flags/BUILD.bazel
  validator/flags/flags.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/usage.go
Labels: Ready For Review

#3052 Remove optional verify signatures argument when verifying deposits
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice_reorg_test.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/spectest/deposit_test.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state_test.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service_test.go
  shared/testutil/helpers.go
Labels: Ready For Review

#3056 Optimize Sparse Merkle Trie
  beacon-chain/blockchain/service_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/rpc/validator_server_test.go
  shared/trieutil/BUILD.bazel
  shared/trieutil/sparse_merkle.go
  shared/trieutil/sparse_merkle_test.go
  shared/trieutil/zerohashes.go
Labels: Enhancement, Ready For Review

#3058 Include Stubs for All Beacon Chain Server RPC Methods
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/service.go
Labels: Ready For Review

#3059 Sync with latest eth api definitions
  WORKSPACE
  beacon-chain/internal/beacon_service_mock.go
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/rpc/beacon_chain_server.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/_compatibility/compatability_test.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review

#3054 Implement GetValidators gRPC server
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  shared/params/config.go
Labels: Ready For Review

#3012 Fix Batched Block Response
  beacon-chain/blockchain/block_processing.go
  beacon-chain/core/state/transition.go
  beacon-chain/db/state.go
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/initial-sync/sync_blocks.go
  beacon-chain/sync/initial-sync/sync_state.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Bug, Priority: Critical, Ready For Review

#3062 Template based protobuf parameters for ssz configurations
  beacon-chain/core/blocks/spectest/BUILD.bazel
  beacon-chain/core/blocks/spectest/attestation_mainnet_test.go
  beacon-chain/core/blocks/spectest/attestation_minimal_test.go
  beacon-chain/core/blocks/spectest/attestation_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_mainnet_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_minimal_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_test.go
  beacon-chain/core/blocks/spectest/block_header_mainnet_test.go
  beacon-chain/core/blocks/spectest/block_header_minimal_test.go
  beacon-chain/core/blocks/spectest/block_header_test.go
  beacon-chain/core/blocks/spectest/block_processing_mainnet_test.go
  beacon-chain/core/blocks/spectest/block_processing_minimal_test.go
  beacon-chain/core/blocks/spectest/block_processing_test.go
  beacon-chain/core/blocks/spectest/deposit_mainnet_test.go
  beacon-chain/core/blocks/spectest/deposit_minimal_test.go
  beacon-chain/core/blocks/spectest/deposit_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_mainnet_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_minimal_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_test.go
  beacon-chain/core/blocks/spectest/transfer_mainnet_test.go
  beacon-chain/core/blocks/spectest/transfer_minimal_test.go
  beacon-chain/core/blocks/spectest/transfer_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_mainnet_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_minimal_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_test.go
  beacon-chain/core/epoch/spectest/BUILD.bazel
  beacon-chain/core/epoch/spectest/crosslink_mainnet_test.go
  beacon-chain/core/epoch/spectest/crosslink_minimal_test.go
  beacon-chain/core/epoch/spectest/crosslink_test.go
  beacon-chain/core/epoch/spectest/final_updates_mainnet_test.go
  beacon-chain/core/epoch/spectest/final_updates_minimal_test.go
  beacon-chain/core/epoch/spectest/final_updates_test.go
  beacon-chain/core/epoch/spectest/justification_and_finalization_mainnet_test.go
  beacon-chain/core/epoch/spectest/justification_and_finalization_minimal_test.go
  beacon-chain/core/epoch/spectest/justification_and_finalization_test.go
  beacon-chain/core/epoch/spectest/registry_mainnet_test.go
  beacon-chain/core/epoch/spectest/registry_minimal_test.go
  beacon-chain/core/epoch/spectest/registry_test.go
  beacon-chain/core/epoch/spectest/slashings_mainnet_test.go
  beacon-chain/core/epoch/spectest/slashings_minimal_test.go
  beacon-chain/core/epoch/spectest/slashings_test.go
  beacon-chain/core/state/spectest/BUILD.bazel
  beacon-chain/core/state/spectest/genesis_initialization_minimal_test.go
  beacon-chain/core/state/spectest/genesis_validity_minimal_test.go
  beacon-chain/core/state/spectest/slot_processing_mainnet_test.go
  beacon-chain/core/state/spectest/slot_processing_minimal_test.go
  beacon-chain/core/state/spectest/slot_processing_test.go
  proto/BUILD.bazel
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/types.proto
  proto/eth/v1alpha1/BUILD.bazel
  proto/ssz_proto_library.bzl
  proto/testing/BUILD.bazel
  proto/testing/ssz_mainnet_compatibility_test.go
  proto/testing/ssz_minimal_compatibility_test.go
Labels: Ready For Review

#3074 Fix Key in Eth1Data Cache
  beacon-chain/cache/eth1_data.go
  beacon-chain/cache/eth1_data_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/sync/regular_sync.go
Labels: Ready For Review

#3067 Implement ListValidatorAssignments RPC function
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/beacon_server_test.go
  shared/pagination/BUILD.bazel
  shared/pagination/pagination.go
  shared/pagination/pagination_test.go
Labels: Ready For Review

#3076 Update SSZ Dependency With Tree Hash Cache Enabled
  WORKSPACE
  beacon-chain/core/helpers/eth1data.go
Labels: Ready For Review

#3061 Implement AttestationPool and ListAttestations RPC Functions
  WORKSPACE
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  shared/pagination/pagination.go
  shared/pagination/pagination_test.go
Labels: Ready For Review

#3048 Implement state transition no verify
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/spectest/block_processing_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/proposer_server.go
Labels: Ready For Review

#3080 Fix Signature Verification for Attestations
  beacon-chain/core/blocks/block_operations_test.go
  validator/client/validator_attest.go
Labels: Bug, Ready For Review

#3085 Fix State Root Verification in Sync
  beacon-chain/core/state/transition.go
Labels: Bug, Ready For Review

#3087 Fixed TestRetrieveAttestations_OK test
  beacon-chain/db/attestation_test.go
Labels: Ready For Review

#3102 Replace Deposit Hash with HashTreeRoot
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/state.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/deposit.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  shared/hashutil/BUILD.bazel
  shared/hashutil/deposit_hash.go
  shared/testutil/BUILD.bazel
  shared/testutil/helpers.go
  shared/trieutil/BUILD.bazel
  shared/trieutil/sparse_merkle_test.go
Labels: Ready For Review

#3112 Fix assignment to advance state up to requested slot
  beacon-chain/rpc/validator_server.go
Labels: Bug

#3105 Eth1Data VoteCount Fix
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
Labels: Bug, Ready For Review

#3113 Attestation Fixes
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/service_test.go
Labels: Bug, Ready For Review

#3117 Fix chain start assignment panic
  validator/client/validator.go
Labels: Bug
