Repository OffchainLabs/prysm, pull requests merged in 2019-01, with the labels that each got.

#1216 Code Clean Up Part 1 - Core Package
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/incentives/BUILD.bazel
  beacon-chain/core/incentives/incentives.go
  beacon-chain/core/incentives/incentives_test.go
  beacon-chain/core/randao/randao.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/committees.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/state.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync_test.go
Labels: Ready For Review

#1220 Cleanup Attestation Helper Function and Test
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
Labels: Ready For Review

#1223 Remove Special Records and Timestamp
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review

#1184 Process Validator Deposits
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/db/state.go
  beacon-chain/rpc/service_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Priority: High, Ready For Review

#1233 Replace Validator Status Code With Activation/Exit Slot
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/attestations/attestation.go
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/committees.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/service_test.go
  beacon-chain/utils/genesis_json_test.go
  genesis.json
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review

#1258 Fix Bug On Startup Using Genesis.json
  README.md
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/node/node.go
  beacon-chain/simulator/service_test.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/utils/BUILD.bazel
  beacon-chain/utils/genesis_json.go
  beacon-chain/utils/genesis_json_test.go
  docs/VALIDATOR_REGISTRATION.md
  genesis.json
Labels: Ready For Review

#1224 Modifying Block Proposals for Validator Clients
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/internal/proposer_service_mock.go
  validator/proposer/BUILD.bazel
  validator/proposer/service.go
  validator/proposer/service_test.go
Labels: Ready For Review

#1276 Advance Beacon State Transition Part 3: Simulate Validator Deposits
  beacon-chain/chaintest/README.md
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/state_test_format.go
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/core/state/transition.go
Labels: Ready For Review

#1297 Advance Beacon State Transition Part 4: Simulate Proposer Slashings
  beacon-chain/chaintest/README.md
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/state_test_format.go
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/core/state/state.go
  shared/params/config.go
Labels: Ready For Review

#1308 Delete unused clock util
  validator/utils/BUILD.bazel
  validator/utils/clock.go
  validator/utils/clock_test.go
Labels: Ready For Review

#1304 Actually test p2p service against the service definition
  shared/p2p/BUILD.bazel
  shared/p2p/service_test.go
Labels: Ready For Review

#1309 Ignore empty public keys in gRPC request
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
Labels: Bug, Ready For Review

#1305 Install prometheus service in the validator node
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
Labels: Ready For Review

#1279 Implement Validator Rotation Logic
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/service.go
  beacon-chain/simulator/service.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync.go
  shared/hashutil/hash_test.go
  shared/params/config.go
  shared/ssz/hash.go
Labels: Ready For Review

#1317 Encoding/Decoding Deposit Data Fix
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
Labels: Bug, Ready For Review

#1298 Advance Beacon State Transition Part 5: Simulate Casper Slashings
  beacon-chain/chaintest/README.md
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/state_test_format.go
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/validators/validator.go
Labels: Ready For Review

#1302 Advance Beacon State Transition Part 6: Simulate Validator Exits
  beacon-chain/chaintest/README.md
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/state_test_format.go
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/rpc/service_test.go
Labels: Ready For Review

#1291 Implement Process Penalties and Exit Logic
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/randao/randao.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/regular_sync.go
  shared/params/config.go
Labels: Ready For Review

#1289 Modify PowChain service
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/node.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  contracts/validator-registration-contract/BUILD.bazel
  contracts/validator-registration-contract/validator_registration.go
  contracts/validator-registration-contract/validator_registration.sol
  contracts/validator-registration-contract/validator_registration_test.go
Labels: Priority: Medium, Ready For Review

#1335 Implement Logic to Update Penalized Exit Balances
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
Labels: Ready For Review

#1327 Add in ChainStart Listener
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/node.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/utils/BUILD.bazel
  beacon-chain/utils/POWlogs.go
Labels: Ready For Review

#1127 add unit test for test broadcast
  CONTRIBUTING.md
  shared/p2p/BUILD.bazel
  shared/p2p/service_test.go
Labels: Ready For Review

#1310 Implement Basic LMD Ghost Fork Choice Skeleton + Helper Funcs
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/internal/db_test_util.go
  beacon-chain/utils/POWlogs.go
  shared/hashutil/beacon_block_test.go
Labels: Ready For Review

#1359 Add attestation p2p messages
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  scripts/update-go-pbs.sh
Labels: Ready For Review

#1360 Rm Shard Committees 2 - Get Crosslink Committees Helpers
  beacon-chain/core/validators/committees.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator_test.go
  shared/bytes/bytes.go
Labels: Ready For Review

#1362 Simplified validator workflow - first pass
  WORKSPACE
  validator/client/BUILD.bazel
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/service.go
  validator/client/service_test.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/p2p_config.go
Labels: Ready For Review

#1364 Remove Shard Committees 3 - Get RANDAO Mix Helper
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
Labels: Ready For Review

#1368 Remove Shard Committees 4 - Validator Registries Processing
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
Labels: Ready For Review

#1379 Remove Shard Committees 5 - Align Core Package
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/tests/fork-choice-tests/basic_fork_choice.yaml
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/randao/randao_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/committees.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
Labels: Ready For Review

#1392 Remove Simulator Service
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/db.go
  beacon-chain/db/schema.go
  beacon-chain/db/simulator.go
  beacon-chain/db/simulator_test.go
  beacon-chain/main.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/simulator/BUILD.bazel
  beacon-chain/simulator/service.go
  beacon-chain/simulator/service_test.go
  beacon-chain/utils/flags.go
Labels: Priority: Medium, Ready For Review

#1343 Replace Solidity Contract With Vyper
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/utils/BUILD.bazel
  beacon-chain/utils/POWlogs.go
  contracts/deposit-contract/BUILD.bazel
  contracts/deposit-contract/ETH1logs.go
  contracts/deposit-contract/README.md
  contracts/deposit-contract/abi.json
  contracts/deposit-contract/bytecode.bin
  contracts/deposit-contract/deployContract/BUILD.bazel
  contracts/deposit-contract/deployContract/README.md
  contracts/deposit-contract/deployContract/deployContract.go
  contracts/deposit-contract/depositContract.go
  contracts/deposit-contract/depositContract.v.py
  contracts/deposit-contract/depositContract_test.go
  contracts/validator-registration-contract/.soliumignore
  contracts/validator-registration-contract/SafeMath.sol
  contracts/validator-registration-contract/deployVRC/BUILD.bazel
  contracts/validator-registration-contract/validator_registration.go
  contracts/validator-registration-contract/validator_registration.sol
  shared/mathutil/math_helper.go
  shared/mathutil/math_helper_test.go
  shared/params/config.go
Labels: Ready For Review

#1347 Refactor ChainService for Synchronous Tests and ChainStart
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/service_test.go
  beacon-chain/sync/regular_sync_test.go
  validator/client/validator_test.go
Labels: Priority: High, Ready For Review

#1401 Spec Comments for ForkChoice Functions
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/core/blocks/block.go
Labels: Ready For Review

#1420 Add Beacon Block Operations to Messages.proto
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: Ready For Review

#1408 Eliminate Custody Logic for Phase 0
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/README.md
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/shuffle_test_format.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/state_test_format.go
  beacon-chain/chaintest/main.go
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/committees.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/schema.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/utils/block_vote_cache.go
  beacon-chain/utils/shuffle.go
  beacon-chain/utils/shuffle_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  shared/params/config.go
  shared/slices/slice.go
  shared/slices/slice_generic_test.go
  shared/slices/slice_test.go
Labels: Ready For Review

#1404 Inclusion Distance with Multiple Attestations
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
Labels: Ready For Review

#1444 Beacon Block Operation Pool to store Attestation
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service.go
  beacon-chain/attestation/service_test.go
  beacon-chain/core/attestations/attestation.go
  beacon-chain/core/attestations/attestation_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service.go
Labels: Ready For Review
