Repository OffchainLabs/prysm, pull requests merged in 2019-10, with the labels that each got.

#3676 Add process block with full attestations test
  beacon-chain/core/state/transition_test.go
Labels: Enhancement

#3671 Optimize Domain Data RPC Request
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/node/node.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  beacon-chain/sync/validate_voluntary_exit_test.go
  shared/testutil/helpers.go
  shared/testutil/helpers_test.go
Labels: Ready For Review

#3678 Add Error to Message validation
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  beacon-chain/sync/validate_voluntary_exit.go
  beacon-chain/sync/validate_voluntary_exit_test.go
Labels: Ready For Review

#3600 Improve Beacon Node Logging UX
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/forkchoice/log.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/gateway/handlers.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/node/clear_db.go
  beacon-chain/node/node.go
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/p2p/addr_factory.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  shared/prometheus/service.go
  shared/prometheus/service_test.go
Labels: Ready For Review

#3682 Tiny Logging Fix
  beacon-chain/sync/initial-sync/round_robin.go
Labels: Ready For Review

#3681 log buf.String() instead of map[reflect.Type]error
  shared/prometheus/service.go
Labels: Ready For Review

#3661 Validator logging improvements
  shared/bytesutil/bytes.go
  shared/bytesutil/bytes_test.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_metrics.go
  validator/client/validator_propose.go
Labels: Enhancement, Ready For Review

#3675 Ask for blocks from peers in parallel
  beacon-chain/p2p/sender.go
  beacon-chain/sync/initial-sync/round_robin.go
Labels: Ready For Review

#3698 Send Status For Already Connected Peers
  beacon-chain/sync/rpc_status.go
Labels: Ready For Review

#3703 Add message events to spans for pubsub
  WORKSPACE
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster.go
  beacon-chain/sync/subscriber.go
  shared/hashutil/BUILD.bazel
  shared/hashutil/hash.go
Labels: Ready For Review

#3705 Coverage for chain info
  beacon-chain/blockchain/chain_info_test.go
Labels: Ready For Review

#3706 Resubscribe Headers from ETH 1 Chain
  beacon-chain/powchain/service.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#3707 Support Provided Host Addresses
  beacon-chain/p2p/dial_relay_node.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/utils.go
Labels: Networking, Ready For Review

#3714 Moved /shared/ test code in different package
  shared/bytesutil/bytes_test.go
  shared/featureconfig/config_test.go
  shared/hashutil/merkleRoot_test.go
  shared/interop/generate_genesis_state_test.go
  shared/interop/generate_keys_test.go
  shared/iputils/external_ip_test.go
  shared/mathutil/math_helper_test.go
  shared/messagehandler/messagehandler_test.go
  shared/pagination/pagination_test.go
  shared/params/config_test.go
  shared/sliceutil/slice_test.go
  shared/trieutil/merkle_trie_test.go
Labels: Ready For Review

#3715 Clean up feature flag namings
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/cache/attestation_data.go
  beacon-chain/cache/eth1_data.go
  beacon-chain/cache/feature_flag_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/state/interop/write_block_to_disk.go
  beacon-chain/core/state/interop/write_state_to_disk.go
  beacon-chain/node/node.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  shared/bls/bls.go
  shared/featureconfig/config.go
  shared/featureconfig/config_test.go
  validator/main.go
  validator/node/node.go
Labels: Enhancement

#3735 Use New SSZ In Workspace
  WORKSPACE
Labels: Ready For Review

#3734 Tests for process att with overlapping bits
  beacon-chain/core/blocks/block_operations_test.go
Labels: Ready For Review

#3739 Ensure Blocks Are Not Duplicated When Saved to DB
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/kv.go
Labels: Ready For Review

#3737 Add context and tracing to attestation pool
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/operations/service.go
  beacon-chain/sync/validate_attester_slashing.go
  shared/testutil/block.go
  shared/testutil/spectest.go
Labels: Enhancement, Ready For Review

#3743 Continue Writing to The Stream Despite Failures
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
Labels: Ready For Review

#3751 Annotate errors / spans in block processing queue
  WORKSPACE
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/receive_block.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/pending_blocks_queue.go
Labels: Ready For Review

#3754 Some fixes for bazel v1
  WORKSPACE
  beacon-chain/BUILD.bazel
  proto/beacon/rpc/v1/BUILD.bazel
  proto/beacon/rpc/v1/services.proto
Labels: Ready For Review

#3775 Fix Round Robin Test
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: Ready For Review

#3789 Aggregation helper improvements
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_aggregation_bench_test.go
  beacon-chain/core/helpers/attestation_test.go
Labels: Ready For Review

#3783 Type for process epoch optimization
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/type.go
Labels: Ready For Review

#3788 Methods to precompute process_epoch records
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/epoch/precompute/new.go
  beacon-chain/core/epoch/precompute/new_test.go
  shared/params/config.go
Labels: Ready For Review

#3596 slasher server
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  slasher/BUILD.bazel
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/server_test.go
  slasher/service.go
Labels: Ready For Review

#3761 Better aggregated attestations pool
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/db/db.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/attestations_test.go
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/beacon_chain_server_test.go
  proto/beacon/db/BUILD.bazel
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/attestation_container.proto
  proto/beacon/db/attestation_container_helper.go
  proto/beacon/db/attestation_container_helper_test.go
Labels: Ready For Review

#3792 Process justification with precompute
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/justification_finalization.go
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
Labels: Ready For Review

#3793 Process rewards and penalties with precompute
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
Labels: Ready For Review

#3797 Process slashing with precompute
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/slashing.go
  beacon-chain/core/epoch/precompute/slashing_test.go
Labels: Ready For Review

#3798 Implement `ProcessEpochPrecompute`
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/epoch/precompute/new_test.go
  beacon-chain/core/epoch/precompute/slashing_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/spectest/BUILD.bazel
  beacon-chain/core/state/spectest/slot_processing_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#3804 Check attestations bitfield overlaps
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
Labels: Ready For Review

#3805 Use lowest included slot for precompute
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/epoch/precompute/new.go
  beacon-chain/core/epoch/precompute/new_test.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/epoch/precompute/type.go
Labels: Ready For Review

#3808 Refactor operation service.go into smaller files
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/attestation.go
  beacon-chain/operations/attestation_test.go
  beacon-chain/operations/block.go
  beacon-chain/operations/block_test.go
  beacon-chain/operations/exit.go
  beacon-chain/operations/exit_test.go
  beacon-chain/operations/log.go
  beacon-chain/operations/recent_att_multi_map.go
  beacon-chain/operations/recent_att_multi_map_test.go
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
Labels: Enhancement

#3800 Attestation is Decoupled From Proposal
  shared/slotutil/BUILD.bazel
  shared/slotutil/slottime.go
  validator/client/runner.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
Labels: Ready For Review

#3818 Gateway registers gRPC gateway handlers
  beacon-chain/gateway/BUILD.bazel
  beacon-chain/gateway/gateway.go
  proto/eth/v1alpha1/BUILD.bazel
Labels: Ready For Review

#3815 Blacklist Peer if they fail Handshake too many times
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/handshake.go
  beacon-chain/sync/peerstatus/BUILD.bazel
  beacon-chain/sync/peerstatus/peer_statuses.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
Labels: Networking, Ready For Review

#3820 Add State Batch Delete for DB
  beacon-chain/db/db.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
Labels: Ready For Review

#3821 Limit init sync to 15 peers
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: Bug, Networking, Ready For Review

#3829 Removed extra save genesis block root
  beacon-chain/blockchain/service.go
Labels: Ready For Review

#3828 Update TESTNET.md - add genesis.ssz file link
  TESTNET.md
Labels: Ready For Review

#3827 Add a tool to extract genesis.ssz from existing database
  beacon-chain/db/BUILD.bazel
  tools/interop/export-genesis/BUILD.bazel
  tools/interop/export-genesis/main.go
Labels: Ready For Review

#3832 Fix `What is Ethereum?` link
  docs/READINGS.md
Labels: Ready For Review

#3842 Guard against deleting genesis and finalized state in DB
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
  tools/interop/export-genesis/main.go
Labels: Ready For Review

#3843 Require state to exist when updating finalized checkpoint
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/checkpoint_test.go
  beacon-chain/db/kv/state_test.go
Labels: Ready For Review

#3785 Optimize Integer Square Root
  shared/mathutil/math_helper.go
  shared/mathutil/math_helper_test.go
Labels: Ready For Review

#3854 Use Compute Domain Instead of Get Domain
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/powchain/deposit.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/rpc/validator_server_test.go
  shared/bls/BUILD.bazel
  shared/bls/bls.go
  shared/bls/bls_test.go
  shared/featureconfig/flags.go
  shared/interop/generate_genesis_state.go
  shared/keystore/deposit_input.go
  shared/testutil/helpers.go
Labels: Ready For Review

#3847 Fix pruning finalized state
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
Labels: Bug

#3856 Prune states since last finalized
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/blockchain/forkchoice/service.go
Labels: Bug, Ready For Review

#3859 Add tracing and annotation for descendent error
  beacon-chain/blockchain/forkchoice/BUILD.bazel
  beacon-chain/blockchain/forkchoice/process_block.go
Labels: Ready For Review

#3850 Fix Failure Counter
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/peerstatus/BUILD.bazel
  beacon-chain/sync/peerstatus/peer_statuses.go
  beacon-chain/sync/peerstatus/peer_statuses_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
Labels: Ready For Review

#3855 Inclusion rewards are based off previous epoch
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
Labels: Ready For Review

#3878 Make No Genesis Delay the Default
  beacon-chain/powchain/log_processing.go
  shared/featureconfig/config.go
  shared/featureconfig/config_test.go
  shared/featureconfig/flags.go
Labels: Enhancement, Required for Testnet

#3873 Track finalized block root index and filter in blocks by range
  beacon-chain/db/db.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/checkpoint_test.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/finalized_block_roots_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  proto/beacon/db/BUILD.bazel
  proto/beacon/db/finalized_block_root_container.proto
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Priority: Critical, Ready For Review

#3881 Add flag deprecation
  shared/featureconfig/BUILD.bazel
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/featureconfig/flags_test.go
Labels: Enhancement

#3872 Update seed domains
  beacon-chain/archiver/BUILD.bazel
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/spectest/attestation_mainnet_test.go
  beacon-chain/core/blocks/spectest/attestation_minimal_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_mainnet_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_minimal_test.go
  beacon-chain/core/blocks/spectest/block_header_mainnet_test.go
  beacon-chain/core/blocks/spectest/block_header_minimal_test.go
  beacon-chain/core/blocks/spectest/block_processing_mainnet_test.go
  beacon-chain/core/blocks/spectest/block_processing_minimal_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_mainnet_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_minimal_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/epoch/spectest/crosslink_mainnet_test.go
  beacon-chain/core/epoch/spectest/final_updates_mainnet_test.go
  beacon-chain/core/epoch/spectest/final_updates_minimal_test.go
  beacon-chain/core/epoch/spectest/justification_and_finalization_mainnet_test.go
  beacon-chain/core/epoch/spectest/registry_mainnet_test.go
  beacon-chain/core/epoch/spectest/slashings_mainnet_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/minimal_config_consensus_test.go
  beacon-chain/core/state/spectest/slot_processing_mainnet_test.go
  beacon-chain/core/state/spectest/slot_processing_minimal_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/operations/attestation_test.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/sync/validate_attester_slashing_test.go
  shared/params/config.go
  shared/testutil/block.go
  validator/client/validator_attest.go
Labels: Ready For Review, spec-v0.9

#3869 Remove active index roots and compact committee roots
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/spectest/deposit_mainnet_test.go
  beacon-chain/core/blocks/spectest/deposit_minimal_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_mainnet_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_minimal_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/participation_test.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/epoch/spectest/crosslink_minimal_test.go
  beacon-chain/core/epoch/spectest/registry_minimal_test.go
  beacon-chain/core/epoch/spectest/slashings_minimal_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/testing/ssz_static_test.go
  shared/testutil/helpers_test.go
Labels: Ready For Review, spec-v0.9

#3886 Update Inclusion Reward
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
Labels: Ready For Review, spec-v0.9

#3903 Validator client side grpc metrics
  validator/client/BUILD.bazel
  validator/client/service.go
Labels: Ready For Review

#3888 Fix early committee bias
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/operations/attestation_test.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/validate_attester_slashing_test.go
  shared/testutil/block_test.go
Labels: Ready For Review, spec-v0.9

#3902 Set committee assignment deadline to 1 epoch
  beacon-chain/core/helpers/BUILD.bazel
  validator/client/BUILD.bazel
  validator/client/runner.go
  validator/client/validator.go
Labels: Ready For Review

#3892 Safer panic handler
  shared/traceutil/recovery_interceptor_option.go
Labels: Ready For Review

#3889 Simple tool to extract state from db
  beacon-chain/core/state/interop/BUILD.bazel
  beacon-chain/db/filters/BUILD.bazel
  tools/extractor/BUILD.bazel
  tools/extractor/main.go
Labels: Ready For Review

#3786 slasher grpc server
  slasher/BUILD.bazel
  slasher/README.md
  slasher/flags/BUILD.bazel
  slasher/flags/flags.go
  slasher/main.go
  slasher/rpc/server.go
  slasher/rpc/server_test.go
  slasher/server.go
  slasher/server_test.go
  slasher/service/BUILD.bazel
  slasher/service/service.go
  slasher/service/service_test.go
  slasher/usage.go
  slasher/usage_test.go
Labels: Ready For Review

#3897 Fix indexed attestations Slasher store
  slasher/db/indexed_attestations.go
  slasher/db/indexed_attestations_test.go
  slasher/db/schema.go
  tools/extractor/main.go
Labels: Ready For Review

#3879 Cache Skipped Slots
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/skip_slot_cache.go
  beacon-chain/core/state/skip_slot_cache_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/node/clear_db.go
  beacon-chain/node/node.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/testutil/block.go
  shared/testutil/block_test.go
  slasher/service/service_test.go
Labels: Ready For Review

#3907 Epoch spec tests v0.9
  WORKSPACE
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/epoch/spectest/final_updates_mainnet_test.go
  beacon-chain/core/epoch/spectest/final_updates_minimal_test.go
  beacon-chain/core/epoch/spectest/justification_and_finalization_mainnet_test.go
  beacon-chain/core/epoch/spectest/registry_mainnet_test.go
  beacon-chain/core/epoch/spectest/registry_minimal_test.go
  beacon-chain/core/epoch/spectest/slashings_mainnet_test.go
  beacon-chain/core/epoch/spectest/slashings_minimal_test.go
  beacon-chain/core/state/transition.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/attestation.proto
  proto/ssz_proto_library.bzl
  shared/params/config.go
Labels: Ready For Review, spec-v0.9

#3861 Add span and annotate errors for validating beacon attestations
  beacon-chain/sync/validate_beacon_attestation.go
  shared/traceutil/errors.go
Labels: Ready For Review
