Repository OffchainLabs/prysm, pull requests merged in 2019-06, with the labels that each got.

#2737 Cache Active Validator Indices, Count, and Balances
  beacon-chain/attestation/service.go
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/active_balance.go
  beacon-chain/cache/active_balance_test.go
  beacon-chain/cache/active_count.go
  beacon-chain/cache/active_count_test.go
  beacon-chain/cache/active_indices.go
  beacon-chain/cache/active_indices_test.go
  beacon-chain/cache/seed.go
  beacon-chain/cache/seed_test.go
  beacon-chain/cache/shuffled_indices.go
  beacon-chain/cache/shuffled_indices_test.go
  beacon-chain/cache/start_shard.go
  beacon-chain/cache/start_shard_test.go
  beacon-chain/cache/total_balance.go
  beacon-chain/cache/total_balance_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/helpers/cache.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/regular_sync_test.go
Labels: Ready For Review, spec-v0.6

#2753 Optimize Base Reward Calculation
  beacon-chain/cache/start_shard_test.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
Labels: Ready For Review, spec-v0.6

#2755 Remove Deprecated Beacon Chain Configs
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/validator_server.go
  shared/params/config.go
Labels: Ready For Review, spec-v0.6

#2759 Add graffiti and update generate seed
  beacon-chain/cache/eth1_data_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/rpc/proposer_server.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review, spec-v0.6

#2758 Benchmark Process Block with Attestations
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/transition_test.go
Labels: Ready For Review, spec-v0.6

#2762 Tidying up Godoc for Core Package
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/helpers/block.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/validators/validator.go
  beacon-chain/rpc/attester_server.go
Labels: Ready For Review, spec-v0.6

#2763 Clean up Old RPC Endpoints
  beacon-chain/internal/beacon_service_mock.go
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/sharding/p2p/v1/messages.pb.go
  scripts/update-mockgen.sh
  validator/client/validator_attest.go
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review, spec-v0.6

#2767 Update RPC end point for Proposer
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/client/BUILD.bazel
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
  validator/internal/proposer_service_mock.go
Labels: Ready For Review, spec-v0.6

#2785 Renovate Updates
  WORKSPACE
Labels: Ready For Review

#2773 Update Attester Server RPC Calls
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/cache/attestation_data.go
  beacon-chain/cache/attestation_data_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review, spec-v0.6

#2793 Add gRPC Gateway Folder
  beacon-chain/internal/beacon_service_mock.go
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/main.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/BUILD.bazel
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.gw.go
  proto/sharding/p2p/v1/messages.pb.go
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: CI

#2795 Minor Updates to 0.7
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/slot_epoch.go
Labels: Ready For Review, spec-v0.6

#2792 Update Phore Dependency to the latest version
  WORKSPACE
  beacon-chain/gateway/server/BUILD.bazel
  beacon-chain/gateway/server/main.go
  beacon-chain/sync/querier_test.go
  shared/bls/BUILD.bazel
  shared/bls/bls.go
  shared/debug/maxprocs_metric.go
  shared/p2p/service_norace_test.go
  validator/client/service_test.go
Labels: Ready For Review

#2768 Add BoltDB Internal Stats
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/db.go
  beacon-chain/db/db_metrics.go
Labels: Enhancement, Ready For Review

#2787 Optimize Committee Assignment RPC
  beacon-chain/internal/beacon_service_mock.go
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_test.go
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review, spec-v0.6

#2816 Update BlockRoot to BlockHash
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/blocks/validity_conditions_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/sync/initial-sync/sync_state.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/testutil/helpers.go
Labels: Ready For Review, spec-v0.6

#2825 Align Protobuf Type Names
  beacon-chain/attestation/service.go
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_reorg_test.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/cache/seed_test.go
  beacon-chain/cache/total_balance_test.go
  beacon-chain/chaintest/backend/fork_choice_test_format.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/blocks/validity_conditions_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/block.go
  beacon-chain/core/helpers/block_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/stateutils/validator_index_map.go
  beacon-chain/core/state/stateutils/validator_index_map_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_metrics.go
  beacon-chain/db/validator.go
  beacon-chain/db/validator_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/initial-sync/sync_state.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  shared/params/config.go
Labels: Ready For Review

#2832 Update Domain Related Functions
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/validator_server.go
  shared/bls/bls.go
Labels: Ready For Review

#2838 Add ConvertToPb to package testutil
  shared/testutil/BUILD.bazel
  shared/testutil/json_to_pb_converter.go
Labels: Ready For Review

#2836 Block Processing Bug Fixes
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/transition_test.go
Labels: Ready For Review, spec-v0.6

#2840 Update types PB with Size Tags
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  proto/testing/BUILD.bazel
  proto/testing/tags_test.go
  proto/testing/test.pb.go
  proto/testing/test.proto
  shared/testutil/json_to_pb_converter.go
Labels: Ready For Review

#2839 SSZ compatibility test for protobufs
  WORKSPACE
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  proto/testing/BUILD.bazel
  proto/testing/ssz_compatibility_test.go
  proto/testing/ssz_minimal.yaml.go
Labels: Ready For Review

#2733 eth1data rpc endpoint
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/core/epoch/spectest/BUILD.bazel
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/eth1data.go
  beacon-chain/core/helpers/eth1data_test.go
  beacon-chain/db/deposits.go
  beacon-chain/db/pending_deposits.go
  beacon-chain/db/pending_deposits_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server_test.go
  shared/bls/spectest/aggregate_pubkeys_test.go
  shared/bls/spectest/aggregate_sigs_test.go
  shared/bls/spectest/priv_to_pub_test.go
  shared/keystore/key_test.go
  shared/sliceutil/slice_generic_test.go
Labels: Ready For Review, spec-v0.6

#2863 Remove chaintest, simulated backend and state generator
  WORKSPACE
  beacon-chain/blockchain/stategenerator/BUILD.bazel
  beacon-chain/blockchain/stategenerator/state_generator.go
  beacon-chain/blockchain/stategenerator/state_generator_test.go
  beacon-chain/chaintest/BUILD.bazel
  beacon-chain/chaintest/README.md
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/fork_choice_test_format.go
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/chaintest/backend/state_test_format.go
  beacon-chain/chaintest/main.go
  beacon-chain/chaintest/yaml_test.go
Labels: Ready For Review
