Repository OffchainLabs/prysm, pull requests merged in 2019-11, with the labels that each got.

#3913 Set WriteToCache Bool Correctly
  beacon-chain/core/state/transition.go
  shared/version/version.go
Labels: Ready For Review

#3905 Block spec test v0.9
  beacon-chain/core/blocks/spectest/attestation_mainnet_test.go
  beacon-chain/core/blocks/spectest/attestation_minimal_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_mainnet_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_minimal_test.go
  beacon-chain/core/blocks/spectest/block_header_mainnet_test.go
  beacon-chain/core/blocks/spectest/block_header_minimal_test.go
  beacon-chain/core/blocks/spectest/block_processing_mainnet_test.go
  beacon-chain/core/blocks/spectest/deposit_mainnet_test.go
  beacon-chain/core/blocks/spectest/deposit_minimal_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_mainnet_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_minimal_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_mainnet_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_minimal_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_block.proto
  proto/testing/ssz_static_mainnet_test.go
  proto/testing/ssz_static_minimal_test.go
  proto/testing/ssz_static_test.go
Labels: Ready For Review, spec-v0.9

#3911 Use ETH1 Block To Determine Genesis State
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  proto/beacon/db/finalized_block_root_container.pb.go
Labels: Ready For Review, Required for Testnet

#3906 Update deposit contract
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  contracts/deposit-contract/BUILD.bazel
  contracts/deposit-contract/README.md
  contracts/deposit-contract/abi.json
  contracts/deposit-contract/bytecode.bin
  contracts/deposit-contract/deployContract/BUILD.bazel
  contracts/deposit-contract/deployContract/README.md
  contracts/deposit-contract/deployContract/deployContract.go
  contracts/deposit-contract/depositContract.go
  contracts/deposit-contract/depositContract.v.py
  contracts/deposit-contract/depositContract_test.go
  contracts/deposit-contract/deposit_tree_test.go
  contracts/deposit-contract/sendDepositTx/sendDeposits.go
  contracts/deposit-contract/testutils.go
  shared/keystore/deposit_input.go
  shared/keystore/deposit_input_test.go
  shared/testutil/helpers.go
  shared/trieutil/sparse_merkle_test.go
  tools/cluster-pk-manager/server/server.go
  validator/accounts/account.go
Labels: spec-v0.9

#3887 Remove --enable-finalized-block-root-index
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/finalized_block_roots_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#3914 Handle ETH1 Node Failure
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/proposer_server.go
  proto/beacon/db/finalized_block_root_container.pb.go
Labels: Ready For Review, Required for Testnet

#3846 Fix ListValidatorBalances RPC API
  WORKSPACE
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
Labels: Ready For Review

#3857 Set ejection balance to 3ETH
  shared/params/config.go
Labels: Blocked, Required for Testnet

#3876 Hardcode Domain Version For Compute Domain
  shared/bls/BUILD.bazel
  shared/bls/bls.go
Labels: Blocked, Required for Testnet

#3912 Slot processing spec test V0.9
  beacon-chain/core/state/spectest/slot_processing_mainnet_test.go
Labels: Ready For Review, spec-v0.9

#3916 Update Latest EthereumAPIs
  WORKSPACE
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.proto
Labels: Ready For Review

#3920 Unskip minimal spec test for finalization
  beacon-chain/core/epoch/spectest/justification_and_finalization_minimal_test.go
  beacon-chain/core/epoch/spectest/justification_and_finalization_test.go
Labels: Ready For Review, spec-v0.9

#3922 Remove outdated interop tests
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/minimal_config_consensus_test.go
  beacon-chain/core/state/testdata/minimal/artemis_crosslink/block.ssz
  beacon-chain/core/state/testdata/minimal/artemis_crosslink/post.ssz
  beacon-chain/core/state/testdata/minimal/artemis_crosslink/pre.ssz
  beacon-chain/core/state/testdata/minimal/crosslink_mismatch/block.ssz
  beacon-chain/core/state/testdata/minimal/crosslink_mismatch/post.ssz
  beacon-chain/core/state/testdata/minimal/crosslink_mismatch/pre.ssz
  beacon-chain/core/state/testdata/minimal/duplicate_rewards/block.ssz
  beacon-chain/core/state/testdata/minimal/duplicate_rewards/post.ssz
  beacon-chain/core/state/testdata/minimal/duplicate_rewards/pre.ssz
Labels: Ready For Review, spec-v0.9

#3880 Handle Missing Blocks
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/testing/BUILD.bazel
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/cache/feature_flag_test.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Priority: Critical, Ready For Review

#3915 Modify RPC Methods To Handle ETH1Failure
  beacon-chain/powchain/service.go
  beacon-chain/powchain/testing/faulty_mock.go
  beacon-chain/powchain/testing/mock.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
Labels: Ready For Review, Required for Testnet

#3924 Update Eth-API To The Latest Version
  WORKSPACE
Labels: Ready For Review

#3926 Testnet restart: bump fork version
  shared/params/config.go
Labels: Ready For Review

#3927 store validator public keys
  slasher/db/BUILD.bazel
  slasher/db/db.go
  slasher/db/schema.go
  slasher/db/validator_id_pubkey.go
  slasher/db/validator_id_pubkey_test.go
Labels: Ready For Review

#3919 Update validator to use proposer slot
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  validator/client/BUILD.bazel
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/validator.go
  validator/client/validator_attest_test.go
  validator/client/validator_test.go
Labels: Ready For Review, spec-v0.9

#3931 Fix Committee Assignment
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
Labels: Ready For Review, spec-v0.9

#3930 Replace shard with committeeIndex
  beacon-chain/cache/attestation_data.go
  beacon-chain/cache/attestation_data_test.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/validator_server.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_test.go
Labels: Ready For Review, spec-v0.9

#3933 Cosmetic clean up
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/validator_server.go
  proto/beacon/p2p/v1/types.proto
  proto/eth/v1alpha1/beacon_chain.proto
  shared/params/config.go
Labels: Ready For Review, spec-v0.9

#3936 Remove shard filter in db
  beacon-chain/db/filters/filter.go
  beacon-chain/db/filters/filter_test.go
Labels: Ready For Review, spec-v0.9

#3939 Remove lightouse compatibility test
  beacon-chain/p2p/encoder/BUILD.bazel
  beacon-chain/p2p/encoder/ssz_test.go
Labels: Ready For Review, spec-v0.9

#3942 Update Latest Master SSZ
  WORKSPACE
Labels: Ready For Review

#3941 Store Validators Min and Max Spans for Slashing
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/slasher.proto
  slasher/db/BUILD.bazel
  slasher/db/db.go
  slasher/db/min_max-span_test.go
  slasher/db/min_max_span.go
  slasher/db/schema.go
Labels: Ready For Review

#3946 Pass db to init sync
  beacon-chain/node/node.go
Labels: Bug, Ready For Review

#3948 Update Committee Cache for v0.9
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_test.go
  beacon-chain/cache/shuffled_indices.go
  beacon-chain/cache/shuffled_indices_test.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/cache.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/gateway/gateway.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  validator/client/validator_attest.go
Labels: Ready For Review, spec-v0.9

#3925 Dont Process Old Blocks And Attestations
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review, Required for Testnet

#3953 Block validator from getting assignment until beacon node is sync'ed
  beacon-chain/gateway/gateway.go
  beacon-chain/rpc/service.go
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/internal/BUILD.bazel
  validator/internal/attester_service_mock.go
  validator/internal/node_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review

#3950 Fix finalized block root index
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/finalized_block_roots_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
Labels: Ready For Review

#3955 Do Not Reject Attestations in Genesis Epoch
  beacon-chain/db/kv/finalized_block_roots_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  proto/eth/v1alpha1/slasher.pb.go
  slasher/db/min_max-span_test.go
  validator/internal/attester_service_mock.go
  validator/internal/node_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Bug, Ready For Review

#3958 Unskip TestProtoCompatability
  WORKSPACE
  proto/eth/v1alpha1/_compatibility/compatability_test.go
Labels: Ready For Review, spec-v0.9

#3954 Handle Runtime Error Type
  shared/traceutil/recovery_interceptor_option.go
Labels: Ready For Review

#3961 Simplify verifyAttSlotTime
  beacon-chain/blockchain/forkchoice/process_attestation.go
Labels: Ready For Review, spec-v0.9

#3966 Copy Block When Receiving it From Sync
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/receive_block.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
Labels: Bug, Ready For Review, Required for Testnet, Testnet

#3956 Change logging of Bitfield
  beacon-chain/operations/block.go
Labels: Ready For Review, spec-v0.9

#3968 RPC checks sync status
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
Labels: Enhancement, Ready For Review

#3962 Unskip Beacon Server Test
  WORKSPACE
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/db/kv/archive_test.go
  beacon-chain/operations/recent_att_multi_map_test.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/validator_server.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/archive.proto
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  proto/eth/v1alpha1/slasher.pb.go
  slasher/db/BUILD.bazel
  slasher/db/min_max_span_test.go
Labels: Bug, Ready For Review

#3984 Change to Random Vote
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/service.go
  proto/eth/v1alpha1/slasher.pb.go
Labels: Ready For Review, Required for Testnet

#3975 Restructure Beacon Chain RPC Servers Into Subpackages
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester/BUILD.bazel
  beacon-chain/rpc/attester/server.go
  beacon-chain/rpc/attester/server_test.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/node/BUILD.bazel
  beacon-chain/rpc/node/server.go
  beacon-chain/rpc/node/server_test.go
  beacon-chain/rpc/proposer/BUILD.bazel
  beacon-chain/rpc/proposer/server.go
  beacon-chain/rpc/proposer/server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/rpc/validator/status_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/eth/v1alpha1/slasher.pb.go
Labels: Ready For Review

#3976 Validator clean up part 1
  proto/eth/v1alpha1/validator.pb.go
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
Labels: Ready For Review

#3951 min max span update logic
  slasher/db/indexed_attestations.go
  slasher/db/min_max_span.go
  slasher/db/min_max_span_test.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/server_test.go
  slasher/rpc/update_min_max_span.go
  slasher/rpc/update_min_max_span_test.go
  slasher/service/service.go
Labels: Ready For Review

#3986 Remove custody
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/spectest/attestation_mainnet_test.go
  beacon-chain/core/blocks/spectest/attestation_minimal_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_mainnet_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_minimal_test.go
  beacon-chain/core/blocks/spectest/block_processing_mainnet_test.go
  beacon-chain/core/blocks/spectest/block_processing_minimal_test.go
  beacon-chain/core/helpers/attestation_aggregation_bench_test.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/db/kv/attestations_test.go
  beacon-chain/operations/attestation_test.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/sync/validate_attester_slashing_test.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/attestation_container_helper.go
  proto/beacon/db/attestation_container_helper_test.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/_compatibility/compatability_test.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/attestation.proto
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_block.proto
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  proto/testing/ssz_static_mainnet_test.go
  proto/testing/ssz_static_minimal_test.go
  proto/testing/ssz_static_test.go
  shared/testutil/block.go
  shared/testutil/block_test.go
  slasher/db/indexed_attestations.go
  slasher/db/indexed_attestations_test.go
  validator/client/BUILD.bazel
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
Labels: Ready For Review, spec-v0.9.1

#3987 Decoy flip flop check
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
Labels: Ready For Review, spec-v0.9.1

#3977 Implement ListBeaconCommittees RPC Method
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/db/kv/archive_test.go
  beacon-chain/node/node.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/service_test.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/archive.proto
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
Labels: Priority: High, Ready For Review

#3990 Add Context to Validator Participation Comment
  beacon-chain/core/epoch/participation.go
Labels: Ready For Review

#3992 Validate Deposit Transactions
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  tools/cluster-pk-manager/server/BUILD.bazel
  tools/cluster-pk-manager/server/server.go
Labels: Ready For Review, Testnet

#3998 Unskip mainnet spec tests
  WORKSPACE
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/spectest/attestation_mainnet_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_mainnet_test.go
  beacon-chain/core/blocks/spectest/block_processing_mainnet_test.go
  proto/testing/ssz_static_mainnet_test.go
Labels: Ready For Review, spec-v0.9.1

#3994 Productionize RPC Server Error Codes
  beacon-chain/rpc/attester/BUILD.bazel
  beacon-chain/rpc/attester/server.go
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/node/server.go
  beacon-chain/rpc/proposer/server.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status.go
Labels: Ready For Review

#3999 Unskip minimal spec tests
  WORKSPACE
  beacon-chain/core/blocks/spectest/attestation_minimal_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_minimal_test.go
  beacon-chain/core/blocks/spectest/block_processing_minimal_test.go
  proto/testing/ssz_static_minimal_test.go
Labels: Ready For Review, spec-v0.9.1

#4001 Unskip proto compatibility test
  WORKSPACE
  proto/eth/v1alpha1/_compatibility/compatability_test.go
Labels: Ready For Review, spec-v0.9.1

#3978 Update minimal seconds per slot to 6
  shared/params/config.go
Labels: Ready For Review

#3993 Bounce attack tests
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/core/helpers/slot_epoch_test.go
Labels: spec-v0.9.1

#3752 Change BLS Library to Herumi
  WORKSPACE
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/operations/attestation_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  beacon-chain/sync/validate_voluntary_exit_test.go
  shared/bls/BUILD.bazel
  shared/bls/bls.go
  shared/bls/bls_benchmark_test.go
  shared/bls/bls_test.go
  shared/bls/spectest/BUILD.bazel
  shared/bls/spectest/aggregate_pubkeys_test.go
  shared/bls/spectest/msg_hash_compressed_test.go
  shared/bls/spectest/msg_hash_uncompressed_test.go
  shared/bls/spectest/priv_to_pub_test.go
  shared/keystore/BUILD.bazel
  shared/keystore/key.go
  shared/keystore/key_test.go
  shared/mathutil/math_helper_test.go
  tools/cluster-pk-manager/client/BUILD.bazel
  validator/BUILD.bazel
Labels: Ready For Review

#4005 Nil Check in Active Set Changes RPC
  beacon-chain/rpc/beacon/validators.go
Labels: Bug, Ready For Review

#4007 Properly Archive Active Set Changes
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#4010 remove source epoch from indexed attestation indices
  slasher/db/indexed_attestations.go
  slasher/db/indexed_attestations_test.go
  slasher/db/schema.go
Labels: Ready For Review

#3932 End To End Tests for Demo and Minimal config
  WORKSPACE
  beacon-chain/BUILD.bazel
  beacon-chain/node/node.go
  endtoend/BUILD.bazel
  endtoend/beacon_node.go
  endtoend/demo_e2e_test.go
  endtoend/endtoend_test.go
  endtoend/epochTimer.go
  endtoend/eth1.go
  endtoend/evaluators/BUILD.bazel
  endtoend/evaluators/finality.go
  endtoend/evaluators/validator.go
  endtoend/minimal_e2e_test.go
  endtoend/validator.go
  shared/params/config.go
  validator/BUILD.bazel
Labels: Ready For Review

#4008 Check end slot for state pruning
  beacon-chain/blockchain/forkchoice/process_block.go
Labels: Bug, Ready For Review

#4015 Optimize Processing Of Past Logs
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  endtoend/endtoend_test.go
  endtoend/evaluators/finality.go
  endtoend/evaluators/validator.go
Labels: Priority: High, Ready For Review

#4014 Process attestation to use operation service's pool
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
  beacon-chain/blockchain/forkchoice/service.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/operations/attestation.go
  beacon-chain/operations/attestation_test.go
  beacon-chain/operations/service.go
  beacon-chain/operations/testing/mock.go
  beacon-chain/rpc/attester/server.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/attestation_container.proto
  proto/beacon/db/finalized_block_root_container.pb.go
Labels: Enhancement, Ready For Review

#4012 Handle Missing Logs
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
Labels: Ready For Review

#3967 Surround detection
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/slasher.proto
  slasher/db/min_max_span.go
  slasher/db/min_max_span_test.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/detect_update_min_max_span.go
  slasher/rpc/detect_update_min_max_span_bench_test.go
  slasher/rpc/detect_update_min_max_span_test.go
  slasher/rpc/update_min_max_span.go
  slasher/rpc/update_min_max_span_test.go
Labels: Ready For Review

#4033 RPC assignment Nil state check
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
Labels: Ready For Review

#4034 Fix deleted branch from ethereumapis
  WORKSPACE
Labels: Priority: Critical, Ready For Review

#4039 Return err for verifyAttestation
  beacon-chain/blockchain/forkchoice/process_attestation.go
Labels: Ready For Review

#4030 Return Empty Results Instead of Pagination Error in RPC + Prevent Future Epoch Requests
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#4032 Improve validator status method
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/rpc/validator/status_test.go
Labels: Ready For Review

#4042 Nil state fallback in Blockchain.HeadState()
  beacon-chain/archiver/service.go
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/attester/server.go
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/proposer/server.go
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_voluntary_exit.go
Labels: Ready For Review

#4053 Update ChainHead
  WORKSPACE
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/validators_test.go
  endtoend/evaluators/finality.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/cluster/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  tools/forkchecker/forkchecker.go
Labels: Ready For Review

#4059 Update Ethereum APIs and Match Schemas
  WORKSPACE
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  endtoend/evaluators/validator.go
  proto/eth/v1alpha1/_compatibility/compatability_test.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
Labels: Ready For Review

#4062 Implement aggregation helpers
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  shared/params/config.go
Labels: Ready For Review

#4049 Double vote detection
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/slasher.proto
  slasher/db/indexed_attestations.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/server_test.go
Labels: Ready For Review

#4054 Archive Data Even Through Skip Slots
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
Labels: Ready For Review

#4074 Fix UpdateCommitteeCache slot
  beacon-chain/core/helpers/committee.go
Labels: Ready For Review

#4065 Add surround check to endpoint
  proto/beacon/rpc/v1/services.proto
  slasher/rpc/detect_update_min_max_span.go
  slasher/rpc/server.go
  slasher/rpc/server_test.go
Labels: Ready For Review

#4066 Update Pending Queue
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
Labels: Bug, Ready For Review

#4061 Filter ListValidators by Active in RPC
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#4081 Refactor validator roles into an array
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review

#4085 gRPC Gateway: Emit JSON empty fields by default
  beacon-chain/gateway/gateway.go
Labels: OK to merge

#4079 Deprecate feature flag --scatter
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/interop/BUILD.bazel
  shared/interop/generate_deposits_test.go
  shared/interop/generate_genesis_state.go
  shared/interop/generate_keys.go
Labels: OK to merge, Ready For Review

#4051 Resolve Panic in ListValidatorBalances RPC
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Bug, OK to merge, Priority: Medium, Ready For Review

#4071 Aggregator selection from RPC to validator client
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/helpers/attestation.go
  beacon-chain/operations/attestation.go
  beacon-chain/operations/service.go
  beacon-chain/operations/testing/mock.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/aggregator/BUILD.bazel
  beacon-chain/rpc/aggregator/server.go
  beacon-chain/rpc/aggregator/server_test.go
  beacon-chain/rpc/service.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  scripts/update-mockgen.sh
  shared/params/config.go
  validator/client/BUILD.bazel
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_aggregate.go
  validator/client/validator_aggregate_test.go
  validator/client/validator_propose_test.go
  validator/client/validator_test.go
  validator/internal/BUILD.bazel
  validator/internal/aggregator_service_mock.go
  validator/internal/attester_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: OK to merge, Ready For Review

#4087 Buildkite: Disable failing BES
  .buildkite-bazelrc
Labels: OK to merge

#4086 Add Lock When Accessing Checkpoints
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/service.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
Labels: OK to merge, Ready For Review

#4080 Release --optimize-process-epoch to all
  beacon-chain/core/state/spectest/slot_processing_test.go
  beacon-chain/core/state/transition.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#4082 Release --prune-finalized-states to all
  beacon-chain/blockchain/forkchoice/BUILD.bazel
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#4089 Implement wait till two thirds
  validator/client/validator_aggregate.go
  validator/client/validator_aggregate_test.go
Labels: Ready For Review

#4090 Update attester to wait till one-third
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
Labels: OK to merge, Ready For Review

#4084 Move StateInitialized and ChainStarted to state feed
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/testing/BUILD.bazel
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/core/statefeed/events.go
  beacon-chain/node/node.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_test.go
Labels: OK to merge

#4093 Feedfixes
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/subscriber.go
Labels: OK to merge

#4094 Revert "Add Lock When Accessing Checkpoints"
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/service.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
Labels: OK to merge

#4091 Properly Return Finalized Epoch in GetValidatorParticipation Archival Endpoint
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge, Ready For Review

#4100 Reduce genesis validator ocunt
  shared/params/config.go
Labels: Ready For Review

#4102 Use Latest Vote Map
  beacon-chain/blockchain/forkchoice/benchmark_test.go
  beacon-chain/blockchain/forkchoice/lmd_ghost_yaml_test.go
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/blockchain/forkchoice/service.go
  beacon-chain/blockchain/forkchoice/service_test.go
  beacon-chain/db/db.go
  beacon-chain/db/kv/validators.go
  beacon-chain/db/kv/validators_test.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  validator/internal/aggregator_service_mock.go
  validator/internal/attester_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: OK to merge, Ready For Review

#4106 Enforce --p2p-max-peers
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/options.go
Labels: OK to merge

#4107 Fork choice beacon block checks
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
Labels: Ready For Review

#4104 Prevent Requesting Current Epoch for Validator Participation
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge, Ready For Review

#4109 Lower conn mgr grace period to 1s
  beacon-chain/p2p/options.go
Labels: OK to merge

#4108 Tool to dump graphviz data for block tree
  WORKSPACE
  tools/blocktree/BUILD.bazel
  tools/blocktree/main.go
Labels: Ready For Review

#4075 Speed Up Block Processing In Sync
  beacon-chain/blockchain/forkchoice/BUILD.bazel
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/service.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/flags/BUILD.bazel
  beacon-chain/flags/config.go
  beacon-chain/node/node.go
Labels: OK to merge

#4002 Refactor Eth1data
  beacon-chain/rpc/proposer/BUILD.bazel
  beacon-chain/rpc/proposer/eth1_data.go
  beacon-chain/rpc/proposer/eth1_data_test.go
  beacon-chain/rpc/proposer/server.go
  beacon-chain/rpc/proposer/server_test.go
Labels: OK to merge, Ready For Review

#4118 Do not save duplicated indices
  beacon-chain/db/kv/attestations_test.go
  beacon-chain/db/kv/utils.go
  beacon-chain/p2p/options.go
Labels: Bug, Ready For Review

#4095 Add signatures to logs
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/rpc/aggregator/server.go
  validator/client/validator_propose.go
Labels: Enhancement, OK to merge, Ready For Review

#4114 Save Deposit Contract Address
  beacon-chain/node/node.go
  beacon-chain/p2p/options.go
Labels: OK to merge, Ready For Review

#4127 Add votes to tree graph
  beacon-chain/core/helpers/BUILD.bazel
  tools/blocktree/BUILD.bazel
  tools/blocktree/main.go
Labels: OK to merge

#4121 Update aggregation proto
  WORKSPACE
  beacon-chain/core/helpers/attestation.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: OK to merge

#4125 DB Improvements: Snappy compression, remove some unnecessary batch / goroutines
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archive.go
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/attestations_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/encoding.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/migrate_snappy.go
  beacon-chain/db/kv/migrate_snappy_test.go
  beacon-chain/db/kv/operations.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/slashings.go
  beacon-chain/db/kv/state.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#4128 Check Best Peer Before Syncing
  beacon-chain/sync/initial-sync/round_robin.go
Labels: OK to merge, Ready For Review

#4129 Mirror run definitions in build
  .bazelrc
Labels: OK to merge

#4115 Avoid crash if peer goes missing
  beacon-chain/sync/initial-sync/round_robin.go
Labels: OK to merge

#4130 Account for Skipped Slots When Requesting for Blocks
  beacon-chain/sync/initial-sync/round_robin.go
  tools/blocktree/main.go
Labels: Ready For Review

#4135 Removed unused mocks
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service_test.go
  beacon-chain/operations/testing/BUILD.bazel
  beacon-chain/operations/testing/mock.go
Labels: Ready For Review

#4134 README for Third Party Directory
  third_party/README.md
Labels: API, OK to merge, Ready For Review

#4136 Fix log message from PR #4130
  beacon-chain/sync/initial-sync/round_robin.go
Labels: OK to merge

#4139 Prune boundary state
  beacon-chain/blockchain/forkchoice/BUILD.bazel
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/prune_states.go
  beacon-chain/db/kv/prune_states_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#4142 Update ethereumapis
  WORKSPACE
  beacon-chain/rpc/node/server.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
  validator/internal/node_mock.go
Labels: OK to merge, Ready For Review

#4146 Update README.md to reflect spec version
  README.md
Labels: OK to merge, Ready For Review

#4148 Check in archive.pb.go
  proto/beacon/p2p/v1/archive.pb.go
Labels: OK to merge

#4153 Remove pruned states check
  beacon-chain/db/kv/prune_states.go
Labels: OK to merge, Ready For Review

#4151 Implement ListPeers API call
  beacon-chain/node/node.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/info.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/mock_peersprovider.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/rpc/node/BUILD.bazel
  beacon-chain/rpc/node/server.go
  beacon-chain/rpc/node/server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/peerstatus/BUILD.bazel
Labels: OK to merge

#4147 Update forkchoice spec link to v0.9.0
  beacon-chain/blockchain/forkchoice/doc.go
Labels: OK to merge

#4152 Update lastUpdated on peerstatus.Set()
  beacon-chain/sync/peerstatus/BUILD.bazel
  beacon-chain/sync/peerstatus/peer_statuses.go
  beacon-chain/sync/peerstatus/peer_statuses_test.go
Labels: OK to merge
