Repository OffchainLabs/prysm, pull requests merged in 2019-09, with the labels that each got.

#3372 Bootnode: Print private key at debug
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
Labels: Ready For Review

#3373 Fix Discv5 in Runtime
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  tools/bootnode/bootnode.go
Labels: Bug, Ready For Review

#3270 Slasher db
  shared/params/config.go
  slasher/db/BUILD.bazel
  slasher/db/block_header.go
  slasher/db/block_header_test.go
  slasher/db/db.go
  slasher/db/db_test.go
  slasher/db/schema.go
Labels: Ready For Review

#3382 Mega renovate updates
  WORKSPACE
Labels: Ready For Review

#3358 Add Test for Aggregating Large Amount of Attestations
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  shared/params/config.go
  slasher/db/block_header.go
Labels: Ready For Review

#3386 Return status error while syncing
  beacon-chain/sync/initial-sync/service.go
Labels: Ready For Review

#3389 Clean up beacon chain config
  shared/params/config.go
Labels: Ready For Review

#3390 Temporarily ban peer if it fails to connect
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/service.go
Labels: Ready For Review

#3394 Fix Prysm Deposit Formatting
  shared/trieutil/sparse_merkle.go
  shared/trieutil/sparse_merkle_test.go
Labels: Ready For Review

#3388 Initial Sync: report healthy before chain started
  beacon-chain/sync/initial-sync/service.go
Labels: Ready For Review

#3399 Remove unnecessary lock when handling attestation
  beacon-chain/blockchain/forkchoice/process_attestation.go
Labels: Ready For Review

#3401 Log the slot of the block w/o parent
  beacon-chain/sync/subscriber_beacon_blocks.go
Labels: Enhancement

#3402 Rename / move logic about updating validator indices
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
Labels: Ready For Review

#3403 PubSub: Check messages received from self, do not double process
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  beacon-chain/sync/validate_voluntary_exit.go
  beacon-chain/sync/validate_voluntary_exit_test.go
Labels: Ready For Review

#3405 Genesis State Generator + Interop Docs
  INTEROP.md
  beacon-chain/core/state/BUILD.bazel
  shared/bls/bls.go
  tools/genesis-state-gen/BUILD.bazel
  tools/genesis-state-gen/main.go
  tools/genesis-state-gen/main_test.go
Labels: Ready For Review

#3408 Load ssz formatted genesis state
  beacon-chain/blockchain/service.go
  beacon-chain/flags/flags.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/usage.go
Labels: Enhancement

#3406 Align metrics to interop
  beacon-chain/blockchain/forkchoice/metrics.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/receive_block.go
  shared/bytesutil/bytes.go
Labels: Ready For Review

#3410 Add /heads page
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/info.go
  beacon-chain/node/node.go
Labels: Enhancement

#3413 Wrap Remaining Errors
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/beacon_server.go
  validator/client/validator.go
Labels: Enhancement

#3411 Clean up post `--next`
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/info.go
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/blocks/validity_conditions_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/eth1data.go
  beacon-chain/core/helpers/eth1data_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/node/node.go
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/powchain/block_reader.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/deposit.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/rpc/testing/BUILD.bazel
  beacon-chain/rpc/testing/beacon_service_mock.go
  beacon-chain/rpc/testing/validator_service_mock.go
  beacon-chain/rpc/validator_server_test.go
Labels: Enhancement

#3416 Update WORKSPACE With Latest SSZ
  WORKSPACE
  beacon-chain/blockchain/forkchoice/lmd_ghost_test.yaml
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/epoch/epoch_processing_test.go
  tools/genesis-state-gen/main.go
Labels: Ready For Review

#3421 Add outfile support for ENR calculation
  tools/enr-calculator/main.go
Labels: Ready For Review

#3407 [Interop] Improve RPC Codebase + Start Beacon Chain With Mock ETH1 Values
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/flags/flags.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/operations/service.go
  beacon-chain/operations/testing/BUILD.bazel
  beacon-chain/operations/testing/mock.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/powchain/testing/BUILD.bazel
  beacon-chain/powchain/testing/faulty_mock.go
  beacon-chain/powchain/testing/mock.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/service.go
  beacon-chain/sync/testing/BUILD.bazel
  beacon-chain/sync/testing/mock.go
  beacon-chain/usage.go
Labels: Ready For Review

#3437 Cold start for interop
  beacon-chain/BUILD.bazel
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/service.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/service.go
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/interop/BUILD.bazel
  beacon-chain/core/state/interop/log.go
  beacon-chain/core/state/interop/write_state_to_disk.go
  beacon-chain/core/state/transition.go
  beacon-chain/db/kv/kv.go
  beacon-chain/flags/BUILD.bazel
  beacon-chain/flags/flags.go
  beacon-chain/flags/interop.go
  beacon-chain/interop-cold-start/BUILD.bazel
  beacon-chain/interop-cold-start/log.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/main.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/service.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/sync/error.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/rpc_hello.go
  beacon-chain/sync/rpc_hello_test.go
  beacon-chain/sync/rpc_test.go
  beacon-chain/usage.go
  shared/bls/bls.go
  shared/interop/BUILD.bazel
  shared/interop/generate_genesis_state.go
  shared/interop/generate_genesis_state_test.go
  shared/interop/generate_keys.go
  shared/params/config.go
  tools/genesis-state-gen/BUILD.bazel
  tools/genesis-state-gen/main.go
  tools/unencrypted-keys-gen/BUILD.bazel
  tools/unencrypted-keys-gen/main.go
  tools/unencrypted-keys-gen/main_test.go
  validator/BUILD.bazel
  validator/flags/BUILD.bazel
  validator/flags/interop.go
  validator/interop.go
  validator/main.go
  validator/usage.go
  validator/usage_test.go
Labels: Ready For Review

#3443 Abstract Usage of Deposit Cache Into Interface
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/cache/depositcache/deposits_test.go
  beacon-chain/cache/depositcache/pending_deposits.go
  beacon-chain/cache/depositcache/pending_deposits_test.go
  beacon-chain/interop-cold-start/BUILD.bazel
  beacon-chain/interop-cold-start/service.go
  beacon-chain/node/node.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/testing/faulty_mock.go
  beacon-chain/powchain/testing/mock.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
Labels: Ready For Review

#3414 Allow Separate Ports for Different Transports
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service_test.go
  beacon-chain/usage.go
  shared/cmd/flags.go
  tools/enr-calculator/main.go
Labels: Ready For Review

#3447 Remove Default Value for Bootstrap Node
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/minimal_regression_test.go
  shared/cmd/flags.go
Labels: Ready For Review

#3463 Add Fork Choice Package Docs
  beacon-chain/blockchain/forkchoice/doc.go
Labels: Ready For Review

#3464 Add Consensus Regression Tests
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/minimal_config_consensus_test.go
  beacon-chain/core/state/minimal_regression_test.go
  beacon-chain/core/state/testdata/minimal/artemis_crosslink/block.ssz
  beacon-chain/core/state/testdata/minimal/artemis_crosslink/post.ssz
  beacon-chain/core/state/testdata/minimal/artemis_crosslink/pre.ssz
  beacon-chain/core/state/testdata/minimal/crosslink_mismatch/block.ssz
  beacon-chain/core/state/testdata/minimal/crosslink_mismatch/post.ssz
  beacon-chain/core/state/testdata/minimal/crosslink_mismatch/pre.ssz
  beacon-chain/core/state/testdata/minimal/duplicate_rewards/block.ssz
  beacon-chain/core/state/testdata/minimal/duplicate_rewards/post.ssz
  beacon-chain/core/state/testdata/minimal/duplicate_rewards/pre.ssz
  beacon-chain/core/state/transition.go
Labels: Ready For Review

#3467 Fix Deterministic Key Generator
  shared/interop/BUILD.bazel
  shared/interop/generate_keys.go
  shared/interop/generate_keys_test.go
  shared/interop/keygen_test_vector.yaml
Labels: Bug, Ready For Review

#3466 Clean up validator server
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review

#3469 Fixed attesting indices set
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
Labels: Ready For Review

#3468 Clean up operation service
  beacon-chain/node/node.go
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review

#3490 Implement Recent Blocks RPC Request
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/rpc_topic_mappings.go
  beacon-chain/p2p/sender.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_hello.go
  beacon-chain/sync/rpc_hello_test.go
  beacon-chain/sync/rpc_recent_beacon_blocks.go
  beacon-chain/sync/rpc_recent_beacon_blocks_test.go
  beacon-chain/sync/rpc_test.go
Labels: Networking, Ready For Review

#3465 Resolve Miscellaneous Prysm TODOs
  INTEROP.md
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/block.go
  beacon-chain/cache/block_test.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/node/node.go
  beacon-chain/p2p/encoder/BUILD.bazel
  beacon-chain/p2p/encoder/doc.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/node_server.go
  beacon-chain/rpc/node_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/rpc.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  tools/genesis-state-gen/main.go
Labels: Ready For Review

#3495 Specify Endianness in BLS Package Funcs
  shared/bls/bls.go
Labels: Ready For Review

#3488 Save Network Keys in Data Directory
  beacon-chain/node/node.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/utils.go
Labels: Ready For Review

#3487 Handle Attestations in a Separate Goroutine
  beacon-chain/rpc/attester_server.go
Labels: Ready For Review, Runtime

#3516 Test proccess on chainstart
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_test.go
  tools/bootnode/bootnode.go
Labels: Ready For Review

#3515 Remove beacon rpc service
  beacon-chain/gateway/BUILD.bazel
  beacon-chain/gateway/gateway.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/testing/BUILD.bazel
  beacon-chain/rpc/testing/beacon_service_mock.go
  beacon-chain/rpc/testing/validator_service_mock.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  scripts/update-mockgen.sh
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_propose_test.go
  validator/client/validator_test.go
  validator/internal/BUILD.bazel
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review

#3507 Archiver Service Definition
  beacon-chain/archiver/BUILD.bazel
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/flags/BUILD.bazel
  beacon-chain/flags/archive.go
  beacon-chain/flags/base.go
  beacon-chain/main.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/usage.go
Labels: Ready For Review

#3517 Fix Withdrawal Credentials
  shared/interop/generate_genesis_state.go
  shared/keystore/BUILD.bazel
  shared/keystore/deposit_input.go
Labels: Bug, Ready For Review

#3518 Update to Latest Version of Bazel Go-Ethereum
  WORKSPACE
Labels: Ready For Review

#3520 Batch Validator Performance Requests
  beacon-chain/rpc/testing/validator_service_mock.go
  beacon-chain/rpc/validator_server.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  validator/client/validator_metrics.go
  validator/internal/attester_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review, Runtime

#3510 Archived Data Definitions & DB API
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/db.go
  beacon-chain/db/db_test.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archive.go
  proto/eth/v1alpha1/BUILD.bazel
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/archive.proto
Labels: Ready For Review

#3506 Use Start Index Flag in Unencrypted Key Gen
  tools/unencrypted-keys-gen/main.go
  tools/unencrypted-keys-gen/main_test.go
Labels: Ready For Review

#3521 Implement Archival DB Methods
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archive.go
  beacon-chain/db/kv/archive_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
Labels: Ready For Review

#3523 Continue on bad attestation
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
Labels: Ready For Review

#3522 Clean hello tracker on peer disconnection
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/rpc_hello.go
  beacon-chain/sync/rpc_hello_test.go
  beacon-chain/sync/service.go
Labels: Ready For Review

#3452 Complete ListAttestations EthereumAPIs v1alpha
  WORKSPACE
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/db/filters/filter.go
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/attestations_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
Labels: Ready For Review

#3527 Fix Validator Client
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/rpc_hello_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
Labels: Bug, Ready For Review

#3524 Archive Validator Participation on End of Epoch Event
  beacon-chain/archiver/BUILD.bazel
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/participation.go
  beacon-chain/core/epoch/participation_test.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/beacon_chain_server.go
Labels: Ready For Review

#3530 Update validators votes from incoming block
  beacon-chain/blockchain/forkchoice/BUILD.bazel
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/blockchain/forkchoice/service.go
Labels: Ready For Review

#3519 Update Naming to Latest Networking Spec
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/rpc_topic_mappings.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_goodbye_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: Networking, Ready For Review

#3533 Remove Error Message Type
  beacon-chain/sync/error.go
  beacon-chain/sync/error_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: Ready For Review

#3531 Archive Remaining Data at Epoch End in Archiver Service
  beacon-chain/archiver/BUILD.bazel
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/db/kv/archive_test.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/archive.proto
Labels: Ready For Review

#3534 Fix justified check point mutation
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/service.go
Labels: Bug

#3514 Wait until fully synced to process pubsub messages
  beacon-chain/node/node.go
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/testing/BUILD.bazel
  beacon-chain/sync/initial-sync/testing/mock.go
  beacon-chain/sync/peerstatus/BUILD.bazel
  beacon-chain/sync/peerstatus/peer_statuses.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  beacon-chain/sync/validate_voluntary_exit.go
  beacon-chain/sync/validate_voluntary_exit_test.go
Labels: Ready For Review

#3539 Implement `AggregatedAttestation` helper
  beacon-chain/blockchain/forkchoice/BUILD.bazel
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/service.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/service.go
  beacon-chain/sync/service.go
Labels: Enhancement, Ready For Review

#3541 Save aggregated attestations in DB after processing
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
Labels: Ready For Review

#3544 Removed unused code in `HandleAttestation`
  beacon-chain/operations/service.go
Labels: Ready For Review

#3545 Fix DiscoveryV5
  WORKSPACE
Labels: Ready For Review

#3556 Expose Nodes
  WORKSPACE
  tools/bootnode/bootnode.go
Labels: Networking

#3543 Fixed 2 cosmetic errors
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/rpc/attester_server.go
Labels: Enhancement

#3526 Utilize Archived Data in GetValidatorParticipation RPC Server
  WORKSPACE
  beacon-chain/archiver/service_test.go
  beacon-chain/core/epoch/participation.go
  beacon-chain/core/epoch/participation_test.go
  beacon-chain/db/kv/archive_test.go
  beacon-chain/node/node.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/service.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/_compatibility/compatability_test.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.proto
  proto/sharding/p2p/v1/messages.pb.go
  tools/forkchecker/forkchecker.go
Labels: Ready For Review

#3542 Implement attestation pool in memory
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester_server.go
Labels: Ready For Review

#3536 Use Archive in Retrieving Validator Balances
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
Labels: Ready For Review

#3557 Add Back Kademlia DHT to Prysm
  beacon-chain/node/node.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/config.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
  shared/cmd/flags.go
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
  tools/bootnode/bootnode_test.go
Labels: Networking

#3560 Update beacon chain server `AttestationPool`
  beacon-chain/operations/service.go
  beacon-chain/operations/testing/mock.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
Labels: Enhancement, Ready For Review

#3562 Removed `verifyAttSlotTime` check for updating fork choice votes
  beacon-chain/blockchain/forkchoice/process_block.go
Labels: Bug

#3559 Allow for Fetching RPC Historical Assignments from Archived Data
  WORKSPACE
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/archive.proto
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
Labels: Ready For Review

#3565 Restore bootnode query tool for kaddht and fix bootstrapping
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/service.go
  tools/bootnode-query/BUILD.bazel
  tools/bootnode-query/README.md
  tools/bootnode-query/main.go
Labels: Ready For Review

#3563 Revamp GetValidators to Retrieve Historical Validators By Epoch
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
Labels: Ready For Review

#3567 Lock around validateBeaconBlockPubSub
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review

#3528 Chunked Responses
  beacon-chain/p2p/encoder/network_encoding.go
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/encoder/ssz_test.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/deadlines.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/rpc_chunked_response.go
  beacon-chain/sync/service.go
Labels: Networking, Ready For Review

#3570 Attestation Server Fix
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester_server.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Bug, Ready For Review

#3571 Merkle tree math helpers
  shared/trieutil/BUILD.bazel
  shared/trieutil/merkle_trie.go
  shared/trieutil/merkle_trie_test.go
Labels: Ready For Review

#3572 Merkle tree implementation
  shared/trieutil/BUILD.bazel
  shared/trieutil/merkle_trie.go
  shared/trieutil/merkle_trie_test.go
Labels: Ready For Review

#3577 Fix Validator Account Creation
  validator/accounts/BUILD.bazel
  validator/accounts/account.go
Labels: Ready For Review

#3575 General indices helpers
  shared/trieutil/merkle_trie.go
  shared/trieutil/merkle_trie_test.go
Labels: Ready For Review

#3573 Do Not Archive Active Indices
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/db/db.go
  beacon-chain/db/kv/archive.go
  beacon-chain/db/kv/archive_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
Labels: Ready For Review

#3579 Fixes our Attestation Aggregation Issues
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/operations/service.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester_server.go
Labels: Bug, Ready For Review

#3538 Initial Sync: Round robin
  WORKSPACE
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/deadlines.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/peerstatus/BUILD.bazel
  beacon-chain/sync/peerstatus/peer_statuses.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_chunked_response.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
Labels: Ready For Review

#3568 Implement Active Set Changes RPC Method
  WORKSPACE
  beacon-chain/archiver/BUILD.bazel
  beacon-chain/archiver/service.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/eth/v1alpha1/archive.pb.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.proto
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/sharding/p2p/v1/messages.pb.go
Labels: Ready For Review

#3584 Remove dead cache
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/active_balance.go
  beacon-chain/cache/active_balance_test.go
  beacon-chain/cache/feature_flag_test.go
  beacon-chain/cache/seed.go
  beacon-chain/cache/seed_test.go
  beacon-chain/cache/start_shard.go
  beacon-chain/cache/start_shard_test.go
  beacon-chain/cache/total_balance.go
  beacon-chain/cache/total_balance_test.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/cache.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  beacon-chain/core/state/transition.go
  shared/bls/bls.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#3586 Initial sync no verify block
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/service.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/state/transition.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#3587 Log warning with error instead of returning an error in fork choice attestation votes updates
  beacon-chain/blockchain/forkchoice/process_block.go
Labels: Ready For Review

#3271 Slasher grpc service
  .gitignore
  beacon-chain/core/helpers/BUILD.bazel
  proto/eth/v1alpha1/slasher.pb.go
  proto/eth/v1alpha1/slasher.proto
  slasher/BUILD.bazel
  slasher/db/BUILD.bazel
  slasher/db/block_header.go
  slasher/db/block_header_test.go
  slasher/db/db.go
  slasher/db/db_test.go
  slasher/db/setup_db.go
  slasher/db/setup_db_test.go
  slasher/service.go
  slasher/service_test.go
Labels: Ready For Review

#3594 Refactor Validator Start Routine
  beacon-chain/node/node.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/BUILD.bazel
  validator/accounts/BUILD.bazel
  validator/accounts/interop.go
  validator/accounts/keys.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/keyutils.go
  validator/node/node.go
  validator/node/node_test.go
Labels: Ready For Review

#3574 Implement GetValidatorQueue RPC
  beacon-chain/core/validators/validator.go
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
Labels: Ready For Review

#3602 Handle large ranges of skipped slots
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: Ready For Review, Required for Testnet

#3606 Move `SplitOffset` to Sliceutil
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/shuffle.go
  beacon-chain/core/helpers/shuffle_test.go
  shared/sliceutil/slice.go
  shared/sliceutil/slice_test.go
Labels: Enhancement, Ready For Review

#3605 Part 1 of caching improvement - ShuffledIndices function
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
Labels: Ready For Review

#3601 Grab read lock on seenPendingBlocks map
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review

#3599 update rules go to support go 1.13.1
  WORKSPACE
  tools/bootnode/BUILD.bazel
  tools/cluster-pk-manager/client/BUILD.bazel
  tools/contract-addr/BUILD.bazel
  tools/enr-calculator/BUILD.bazel
  tools/relaynode/BUILD.bazel
  validator/BUILD.bazel
Labels: Ready For Review

#3597 Tidy up logging in the validator
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_metrics.go
  validator/client/validator_propose.go
Labels: Ready For Review

#3607 Part 2 of caching improvement - A cache for shuffled indices
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_test.go
Labels: Ready For Review

#3611 Return All Pending Queue Validators in GetValidatorsQueue RPC
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
Labels: Ready For Review

#3617 Part 3 of caching improvement - Update cache
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
Labels: Ready For Review

#3496 Batch Deletions for Blocks and Attestations
  beacon-chain/db/db.go
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/attestations_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
Labels: Ready For Review

#3589 Reorganize State Transition Functions
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/proposer_server.go
Labels: Ready For Review

#3623 Report sync unhealthy in the case that the node is still syncing
  beacon-chain/sync/service.go
Labels: Ready For Review

#3621 Bootstrap from finalized checkpoint rather than head slot
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: Ready For Review

#3619 Feature flag for new caching scheme
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#3624 All deposits must be verified
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/state/transition.go
Labels: Ready For Review

#3627 Use demo config for accounts create
  validator/BUILD.bazel
  validator/main.go
Labels: Ready For Review, Required for Testnet

#3625 Part 4 of caching improvement - Use Cache
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/forkchoice/BUILD.bazel
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
Labels: Ready For Review

#3626 Accounts create: make the print the same number of characters
  validator/accounts/account.go
Labels: Ready For Review

#3629 Add active indices functionality to cache
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_test.go
  beacon-chain/core/helpers/validators.go
Labels: Ready For Review

#3660 Update WORKSPACE SSZ Dependency
  WORKSPACE
Labels: Ready For Review

#3622 Large Prysm Performance Improvements
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/db/db.go
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/attestations_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/validators.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_chain_server.go
  beacon-chain/rpc/beacon_chain_server_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
Labels: Enhancement, Ready For Review

#3672 Batch save attestations in state transition
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
  beacon-chain/blockchain/forkchoice/process_block.go
Labels: Enhancement, Ready For Review
