Repository OffchainLabs/prysm, pull requests merged in 2019-03, with the labels that each got.

#1762 Misc Fixes for Epoch Processing
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
Labels: Ready For Review

#1768 Fix Attestation Info at Slot to Match Justified Epoch Expectations
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/rpc/attester_server.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  shared/params/config.go
  validator/client/validator_attest.go
Labels: Bug, Ready For Review

#1759 Add Error Log for Attester
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
Labels: Bug, Ready For Review

#1786 Change Validator Log
  validator/client/runner.go
Labels: Ready For Review

#1801 Fix Randao Reveal Bug
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/state.go
Labels: Bug

#1785 Eth1 Data Fix
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/powchain/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service_test.go
Labels: Ready For Review

#1791 Remove Logging Exits in Block
  beacon-chain/core/state/transition.go
Labels: Enhancement

#1771 Refactor Crosslink Committees at Slot
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
Labels: Ready For Review

#1830 Fixing Sync
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/querier.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/simulated_sync_test.go
  shared/params/config.go
Labels: Ready For Review

#1798 Clean Up Validator RPC Server
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_test.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review

#1850 Clean Up Context
  beacon-chain/attestation/service.go
  beacon-chain/blockchain/service.go
  beacon-chain/node/node.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/querier.go
  validator/node/node.go
Labels: Ready For Review

#1875 Allow Node to Request State if it is Behind
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  shared/params/config.go
Labels: Ready For Review

#1858 Adding Prometheus Metrics and Tracing to Sync
  beacon-chain/powchain/service_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/metrics.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/metrics.go
  beacon-chain/sync/regular_sync.go
Labels: Ready For Review

#1894 Add Spans for Processing Block
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
Labels: Ready For Review

#1892 Request Block Parent If Not Found During Regular Sync
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
Labels: Priority: Critical, Ready For Review

#1896 Wait for Validator Activation Stream Server
  beacon-chain/internal/BUILD.bazel
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/internal/validator_service_mock.go
Labels: Priority: Critical, Ready For Review

#1898 Validator Client WaitForActivation Implementation
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Priority: Critical, Ready For Review

#1905 Discard Attestations Older Than Prev Epoch Start Slot
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
Labels: Bug

#1911 Proposer Service: Only return attestations within the last epoch
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/service_test.go
Labels: Ready For Review

#1913 Fix wait for activation
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  validator/client/service.go
Labels: Ready For Review

#1915 Fix WaitForActivation Race Condition
  beacon-chain/rpc/validator_server.go
Labels: Bug, Ready For Review

#1916 Fix attestations again
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/rpc/proposer_server.go
Labels: Ready For Review

#1917 Sync Drops Attestations < 1 Epoch Length
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
Labels: Bug

#1718 Add State Generator
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/stategenerator/BUILD.bazel
  beacon-chain/blockchain/stategenerator/state_generator.go
  beacon-chain/blockchain/stategenerator/state_generator_test.go
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
  beacon-chain/db/db.go
  beacon-chain/db/schema.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/node/node.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
Labels: Priority: High, Ready For Review

#1925 Fix Panic in Message Recovery
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
Labels: Bug, Ready For Review

#1922 PendingAttestations: allow for request to specify a slot
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  proto/beacon/rpc/v1/services.proto
  validator/client/validator_propose.go
Labels: Ready For Review

#1679 Faucet enhancements + cluster private key management system
  WORKSPACE
  contracts/deposit-contract/deployContract/deployContract.go
  k8s/BUILD.bazel
  k8s/beacon-chain/BUILD.bazel
  k8s/beacon-chain/beacon-chain.deploy.yaml
  k8s/beacon-chain/beacon-chain.service.yaml
  k8s/beacon-chain/beacon-config.config.yaml
  k8s/beacon-chain/bootnode.deploy.yaml
  k8s/beacon-chain/bootnode.encrypted_secret.yaml
  k8s/beacon-chain/bootnode.service.yaml
  k8s/beacon-chain/cluster-manager.encrypted_secret.yaml
  k8s/beacon-chain/cluster-manager.yaml
  k8s/beacon-chain/deploydepositcontract.job.yaml
  k8s/beacon-chain/deploydepositcontract.serviceaccount.yaml
  k8s/beacon-chain/relay.deploy.yaml
  k8s/beacon-chain/relay.encrypted_secret.yaml
  k8s/beacon-chain/relay.service.yaml
  k8s/beacon-chain/validator.deploy.yaml
  k8s/client/BUILD.bazel
  k8s/client/proposer.deploy.yaml
  k8s/geth/faucet.deploy.yaml
  k8s/monitoring/BUILD.bazel
  k8s/prylabs-wildcard-gateway.yaml
  proto/cluster/BUILD.bazel
  proto/cluster/services.pb.go
  proto/cluster/services.proto
  shared/prometheus/BUILD.bazel
  shared/prometheus/simple_server.go
  tools/bootnode-query/README.md
  tools/bootnode-query/main.go
  tools/cluster-pk-manager/README.md
  tools/cluster-pk-manager/client/BUILD.bazel
  tools/cluster-pk-manager/client/main.go
  tools/cluster-pk-manager/server/BUILD.bazel
  tools/cluster-pk-manager/server/db.go
  tools/cluster-pk-manager/server/logger.go
  tools/cluster-pk-manager/server/main.go
  tools/cluster-pk-manager/server/server.go
  tools/cluster-pk-manager/server/server_test.go
  tools/cluster-pk-manager/server/watchtower.go
  tools/faucet/BUILD.bazel
  tools/faucet/main.go
  tools/faucet/server.go
Labels: Ready For Review

#1923 Fix Current Block Children Implementation
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: Ready For Review

#1931 p2p fixes / improvements
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/simulated_sync_test.go
  k8s/beacon-chain/beacon-chain.deploy.yaml
  k8s/beacon-chain/beacon-config.config.yaml
  shared/p2p/BUILD.bazel
  shared/p2p/message.go
  shared/p2p/p2p.go
  shared/p2p/peer.go
  shared/p2p/service.go
  shared/p2p/service_test.go
Labels: Ready For Review

#1933 LMD GHOST fork choice implementation and tests
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block_test.go
Labels: Ready For Review

#1939 Handle Skipped Slots in Sync
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync.go
Labels: Bug, Ready For Review

#1928 Implement Updated Sparse Merkle Trie as a Utility for Deposit Processing
  shared/trieutil/BUILD.bazel
  shared/trieutil/sparse_merkle.go
  shared/trieutil/sparse_merkle_test.go
Labels: Priority: Critical, Ready For Review

#1949 Minor fixes to beaconchain service
  beacon-chain/blockchain/service.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  k8s/beacon-chain/beacon-chain.deploy.yaml
Labels: Ready For Review

#1942 Clean up Atts Older Than Epoch Length
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
Labels: Ready For Review

#1957 Misc updates for epoch processing
  beacon-chain/core/blocks/block.go
  beacon-chain/core/epoch/epoch_processing.go
Labels: Ready For Review

#1926 Handle Panics in Remaining Services
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/service.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync_test.go
  shared/messagehandler/BUILD.bazel
  shared/messagehandler/messagehandler.go
  shared/messagehandler/messagehandler_test.go
  validator/client/validator_propose_test.go
Labels: Ready For Review

#1956 Add grpc middleware to recover from panics
  WORKSPACE
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
Labels: Ready For Review

#1963 Fix off by 1 for attestation justified epoch checking
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
Labels: Priority: Critical

#1968 Typo: valud/valid
  beacon-chain/node/node.go
Labels: Ready For Review

#1934 Post ChainStart Validator Activation
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/db.go
  beacon-chain/db/deposits.go
  beacon-chain/db/pending_deposits.go
  beacon-chain/db/pending_deposits_test.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator_server_test.go
  proto/cluster/services.pb.go
  shared/params/config.go
  shared/trieutil/BUILD.bazel
  shared/trieutil/deposit_trie.go
  shared/trieutil/deposit_trie_test.go
  shared/trieutil/sparse_merkle.go
  shared/trieutil/sparse_merkle_test.go
  validator/client/validator.go
Labels: Priority: Critical, Ready For Review

#1950 Part 1 of X - LMD Ghost Benchmark Tests
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: Ready For Review

#1972 Do not propose a block when compute state root fails
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
Labels: Bug

#1955 Make State Requests only Request for Finalized State
  beacon-chain/blockchain/service.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/querier.go
  beacon-chain/sync/querier_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/simulated_sync_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: Ready For Review

#1985 Revert One off Attestation
  beacon-chain/core/blocks/block_operations.go
Labels: Bug, Ready For Review

#1982 Update FFG Check Points During Block Processing
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/stategenerator/state_generator_test.go
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
Labels: Ready For Review

#1991 Update FFG Check Points During Block Processing
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/stategenerator/state_generator_test.go
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
Labels: Ready For Review

#2004 Update Aggregate Attestation
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service.go
  beacon-chain/attestation/service_test.go
Labels: Ready For Review

#2023 State Transition Configuration Options
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/stategenerator/state_generator.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/proposer_server.go
Labels: Enhancement, Ready For Review

#1994 Prevent invalid pending attestations
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
Labels: Ready For Review

#2029 Log the DB path
  beacon-chain/node/node.go
Labels: Ready For Review

#2006 Update FFG Check Points During Block Processing
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/stategenerator/state_generator.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
Labels: In Progress

#2045 Refactor State Gen To Take Input Slot
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/stategenerator/BUILD.bazel
  beacon-chain/blockchain/stategenerator/state_generator.go
  beacon-chain/blockchain/stategenerator/state_generator_test.go
Labels: Ready For Review

#1780 State size metric
  beacon-chain/db/state.go
Labels: Ready For Review

#2049 Test on Skip Slot for FFG Check Point
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/stategenerator/state_generator.go
Labels: Ready For Review

#2051 Add Prometheus Counter for Reorg
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/fork_choice.go
Labels: Ready For Review

#2040 Validator: performing for multiple keys - update rpc proto
  .gitignore
  beacon-chain/internal/beacon_service_mock.go
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/sharding/p2p/v1/messages.pb.go
  scripts/update-mockgen.sh
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_test.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review

#2068 Mega Renovate Updates
  WORKSPACE
  k8s/beacon-chain/beacon-chain.deploy.yaml
  k8s/beacon-chain/beacon-config.config.yaml
  k8s/beacon-chain/validator.deploy.yaml
Labels: Ready For Review

#2050 Allow 8 Validator Multinode Cluster to Run Indefinitely
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service.go
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/stategenerator/BUILD.bazel
  beacon-chain/blockchain/stategenerator/state_generator.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/state/transition.go
  beacon-chain/db/block.go
  beacon-chain/node/node.go
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/querier.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service.go
  k8s/beacon-chain/beacon-chain.deploy.yaml
  k8s/beacon-chain/validator.deploy.yaml
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/p2p/service.go
  shared/params/config.go
  validator/client/BUILD.bazel
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
  validator/client/validator_test.go
Labels: Priority: Critical, Ready For Review

#2070 Reconnect to VIP peers
  shared/p2p/BUILD.bazel
  shared/p2p/monitoring.go
  shared/p2p/monitoring_test.go
  shared/p2p/service.go
Labels: Ready For Review

#2074 Treat Post & Pre-ChainStart Validators Equally in Assignments Fetching
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/validator.go
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/internal/validator_service_mock.go
Labels: Priority: High, Ready For Review

#2075 Disable Crosslinks for Testnet
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/BUILD.bazel
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/chaintest/yaml_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Priority: High, Ready For Review

#2082 Avoid increment reorg counter twice
  beacon-chain/blockchain/fork_choice.go
Labels: Ready For Review

#2085 Enhance Logging for Validator Registration
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
Labels: Ready For Review

#2091 Remove Outdated DB Method
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/cleanup_history.go
  beacon-chain/db/cleanup_history_test.go
  beacon-chain/db/schema.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/regular_sync.go
Labels: Ready For Review

#2092 Fix ActiveValidatorIndices use slot
  beacon-chain/core/balances/rewards_penalties.go
Labels: Ready For Review

#2090 Prune Outdated Deposits after Chainstart
  beacon-chain/db/pending_deposits.go
  beacon-chain/db/pending_deposits_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/querier.go
  beacon-chain/sync/querier_test.go
  beacon-chain/sync/service.go
Labels: Bug

#2089 Request Missing Parents Recursively via P2P
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/receive_block.go
  beacon-chain/sync/receive_block_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service_test.go
  beacon-chain/sync/simulated_sync_test.go
Labels: In Progress, Priority: High

#2097 Request Assignments From Canonical Slot Upon Activation
  beacon-chain/rpc/validator_server.go
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Priority: High, Ready For Review

#2103 Fix getting active validators for ValidatorPerformance
  beacon-chain/rpc/validator_server.go
Labels: Ready For Review

#2104 Use a mutex/lock on the validator store
  beacon-chain/blockchain/block_processing.go
  beacon-chain/blockchain/block_processing_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/validators/validator.go
Labels: Ready For Review

#2109 Prevent Reorg Infinite Loops in Initial Sync
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/querier.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/simulated_sync_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: Priority: Critical

#2054 keystore and account support for multi key
  shared/keystore/keystore.go
  shared/keystore/keystore_test.go
  validator/accounts/account.go
  validator/accounts/account_test.go
  validator/client/service.go
Labels: Priority: High, Ready For Review

#2115 Add Validator Stats
  beacon-chain/db/state_metrics.go
Labels: Ready For Review

#2116 take first validator key
  validator/client/service.go
Labels: Bug

#2114 Modify p2p Allowed Buffer Size & Batch Block Limit
  shared/p2p/service.go
  shared/params/config.go
Labels: Ready For Review
