Repository OffchainLabs/prysm, pull requests merged in 2019-02, with the labels that each got.

#1455 Aligning ETH2.0 spec - Remove Exit Count
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review

#1454 Aligning ETH2.0 spec - RANDAO helpers
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/committees.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review

#1433 Clean Up Simulated Backend
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
Labels: Ready For Review

#1474 Initialize State from ChainStart Deposits in POWChainService
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/dbcleanup/BUILD.bazel
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/regular_sync_test.go
  contracts/deposit-contract/depositContract_test.go
  validator/BUILD.bazel
Labels: Ready For Review

#1402 Implement Attestation Pool for Fork Choice
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service.go
  beacon-chain/attestation/service_test.go
  beacon-chain/chaintest/backend/simulated_backend.go
  shared/bytesutil/bytes.go
Labels: Ready For Review

#1470 Aligning ETH2.0 spec - Removed Balances from Validator Proto
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/db/state_test.go
  beacon-chain/dbcleanup/BUILD.bazel
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review

#1475 Pending deposits db
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/db.go
  beacon-chain/db/pending_deposits.go
  beacon-chain/db/pending_deposits_test.go
Labels: Ready For Review

#1460 Aligning ETH2.0 spec - Make Epoch First Citizen (Package: Validators)
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/balances/BUILD.bazel
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/committees.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
Labels: Ready For Review

#1462 Validator Proposer Rewrite
  beacon-chain/rpc/beacon_server.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  shared/p2p/BUILD.bazel
  shared/p2p/interfaces.go
  shared/p2p/mock/BUILD.bazel
  shared/p2p/mock/broadcaster_mock.go
  shared/p2p/service_test.go
  validator/client/BUILD.bazel
  validator/client/validator.go
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
  validator/client/validator_test.go
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
  validator/node/node.go
Labels: Ready For Review

#1491 Use a better message for notifying of a new deposit
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: Ready For Review

#1496 Override reasonable defaults for bazel test timeout
  .buildkite-bazelrc
Labels: Ready For Review

#1495 Insert pending deposits
  beacon-chain/db/pending_deposits.go
  beacon-chain/db/pending_deposits_test.go
  beacon-chain/node/node.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: Ready For Review

#1445 Allow Simulated Backend to Advance Chain
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition_test.go
  shared/params/config.go
Labels: Priority: High, Ready For Review

#1501 Aligning ETH2.0 spec - Update Fork and Domain Helpers
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/signature.go
  beacon-chain/core/helpers/signature_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review

#1507 Aligning ETH2.0 spec - Crosslink Records
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/committees.go
  beacon-chain/core/validators/committees_test.go
  beacon-chain/core/validators/validator.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review

#1509 Add metrics about the powchain service
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
Labels: Ready For Review

#1508 Pending Deposits RPC Server Implementation
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/service.go
Labels: Ready For Review

#1513 Aligning ETH2.0 spec - Update Validator Fields
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/stateutils/validator_index_map_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review

#1514 fix config across codebase
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition_test.go
Labels: Ready For Review

#1518 Aligning ETH2.0 spec - Update Initial Beacon State
  beacon-chain/core/state/state.go
Labels: Ready For Review

#1494 Update Deposit Contract
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/beacon_server_test.go
  contracts/deposit-contract/BUILD.bazel
  contracts/deposit-contract/ETH1logs.go
  contracts/deposit-contract/abi.json
  contracts/deposit-contract/bytecode.bin
  contracts/deposit-contract/depositContract.go
  contracts/deposit-contract/depositContract.v.py
  contracts/deposit-contract/depositContract_test.go
  shared/trieutil/BUILD.bazel
  shared/trieutil/deposit_trie.go
  shared/trieutil/deposit_trie_test.go
Labels: Priority: Medium, Ready For Review

#1527 Align Initial Beacon State to Latest Spec
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
Labels: Priority: High, Ready For Review

#1517 k8s goerli config
  k8s/BUILD.bazel
  k8s/README.md
  k8s/beacon-chain/namespace.yaml
  k8s/geth/BUILD.bazel
  k8s/geth/bootnode.deploy.yaml
  k8s/geth/ethstats.deploy.yaml
  k8s/geth/ethstats.encrypted_secret.yaml
  k8s/geth/ethstats.service.yaml
  k8s/geth/faucet.deploy.yaml
  k8s/geth/faucet.service.yaml
  k8s/geth/goerli.config.yaml
  k8s/geth/goerli_validator.encrypted_secret.yaml
  k8s/geth/ingress.yaml
  k8s/geth/miners.deploy.yaml
  k8s/geth/namespace.yaml
  k8s/geth/nodes.deploy.yaml
  k8s/geth/nodes.service.yaml
  k8s/geth/prober/BUILD.bazel
  k8s/geth/prober/main.go
  k8s/geth/public_nodes.deploy.yaml
  k8s/geth/public_nodes.service.yaml
  k8s/letsencrypt-issuer.yaml
  k8s/monitoring/grafana.encrypted_secret.yaml
  k8s/monitoring/grafana.service.yaml
  k8s/monitoring/ingress.yaml
  k8s/monitoring/manifests-all.yaml
  k8s/nginx/BUILD.bazel
  k8s/nginx/default-server-secret-encrypted.yaml
  k8s/nginx/deployment.yaml
  k8s/nginx/loadbalancer.yaml
  k8s/nginx/namespace.yaml
  k8s/nginx/nginx-config.yaml
  k8s/nginx/rbac.yaml
  k8s/nginx/service-account.yaml
Labels: Ready For Review

#1512 Align Block Operations to Spec
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/state_test_format.go
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/block_operations_test.go
  beacon-chain/operations/service_test.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Priority: High, Ready For Review

#1539 Update MaxDeposit Config Names
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/state_test.go
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/regular_sync_test.go
  shared/params/config.go
Labels: Ready For Review

#1530 Remove pending deposits after receiving a processed block
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: Ready For Review

#1523 Aligning ETH2.0 spec - Attestation and Epoch Processing - Part 2
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/validators/validator.go
Labels: Ready For Review

#1533 Update RANDAO to Match Spec
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/randao/BUILD.bazel
  beacon-chain/core/randao/randao.go
  beacon-chain/core/randao/randao_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Priority: High, Ready For Review

#1540 Final Updates During Epoch Processing
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
Labels: Ready For Review

#1547 Fixed a Prev Boundary Epoch Attestation Bug
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
Labels: Bug

#1546 Update to Use Crosslink in AttestationData
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
Labels: Ready For Review

#1505 Attester RPC Server Functions
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/internal/attester_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Priority: High, Ready For Review

#1367 Utilize Go-BLS in Prysm
  WORKSPACE
  shared/bls/BUILD.bazel
  shared/bls/bls.go
  shared/bls/bls_test.go
  shared/keystore/BUILD.bazel
  shared/keystore/key.go
  shared/keystore/key_test.go
  shared/keystore/keystore.go
  shared/keystore/keystore_test.go
  shared/keystore/utils.go
  validator/accounts/account.go
  validator/accounts/account_test.go
Labels: Ready For Review

#1553 Support Encode/Decode of Nil Pointer
  shared/ssz/decode.go
  shared/ssz/decode_test.go
  shared/ssz/encode.go
  shared/ssz/encode_test.go
Labels: Ready For Review

#1536 Update Contract to Use Little Endian And Encoding Across Entire Repo
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/db/schema.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/validator_server_test.go
  contracts/deposit-contract/README.md
  contracts/deposit-contract/abi.json
  contracts/deposit-contract/bytecode.bin
  contracts/deposit-contract/deployContract/deployContract.go
  contracts/deposit-contract/depositContract.go
  contracts/deposit-contract/depositContract.v.py
  contracts/deposit-contract/depositContract_test.go
  shared/bytesutil/bytes.go
  shared/bytesutil/bytes_test.go
  shared/trieutil/deposit_trie.go
  shared/trieutil/deposit_trie_test.go
Labels: Priority: High, Ready For Review

#1563 change to message hash
  beacon-chain/core/blocks/block_operations.go
Labels: Ready For Review

#1552 Implement get_next_epoch_committee_assignment helper function
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
Labels: Ready For Review

#1557 Use Public, Constant Genesis Timestamp in Deposit Contract Instead of ChainStart Bool
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  contracts/deposit-contract/abi.json
  contracts/deposit-contract/bytecode.bin
  contracts/deposit-contract/depositContract.go
  contracts/deposit-contract/depositContract.v.py
  contracts/deposit-contract/depositContract_test.go
Labels: Priority: High, Ready For Review

#1566 Track Previously Seen Merkle Index to Prevent Duplicate Log Spam
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  shared/keystore/keystore_test.go
Labels: Ready For Review

#1569 Standardize Slot Ticker with params.BeaconConfig().GenesisSlot
  shared/slotutil/BUILD.bazel
  shared/slotutil/simulatorticker.go
  shared/slotutil/simulatorticker_test.go
  shared/slotutil/slotticker.go
  shared/slotutil/slotticker_test.go
Labels: Ready For Review

#1579 Simplify Config
  shared/params/config.go
Labels: Ready For Review

#1561 Remove Justified Slot
  beacon-chain/core/attestations/BUILD.bazel
  beacon-chain/core/attestations/attestation.go
  beacon-chain/core/attestations/attestation_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: Ready For Review

#1583 Moved Rewards/Penalties Helpers to Helper Packages
  beacon-chain/core/balances/BUILD.bazel
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
Labels: Ready For Review

#1568 Wait to Send Genesis Time to Validators Until After Genesis State is Initialized
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
Labels: Ready For Review

#1571 Change BLS Public Key Length Check in Beacon RPC Server
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  shared/params/config.go
Labels: Ready For Review

#1574 Fetch Initial Assignments at Genesis Slot Post ChainStart
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review

#1576 Update References to Deposit Contract, Update Flags
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/utils/flags.go
  contracts/deposit-contract/deployContract/BUILD.bazel
  contracts/deposit-contract/deployContract/README.md
  contracts/deposit-contract/deployContract/deployContract.go
  docs/MAINCHAIN.md
  k8s/README.md
  k8s/beacon-chain/BUILD.bazel
  k8s/beacon-chain/beacon-chain.deploy.yaml
  k8s/beacon-chain/beacon-config.config.yaml
  k8s/beacon-chain/deploydepositcontract.job.yaml
  k8s/beacon-chain/deploydepositcontract.serviceaccount.yaml
Labels: Ready For Review

#1584 Move Validator Helper Functions to Helper Package
  beacon-chain/core/balances/BUILD.bazel
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/validator_server.go
Labels: Ready For Review

#1564 Update Fork Choice to Use Balance
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service.go
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  shared/params/config.go
Labels: Ready For Review

#1570 Provide Real Keystore to Validator Service for Public/Private Key Access at Runtime
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/db_test.go
  beacon-chain/internal/BUILD.bazel
  beacon-chain/internal/db_test_util.go
  beacon-chain/node/node_test.go
  shared/keystore/BUILD.bazel
  shared/keystore/key_test.go
  shared/keystore/keystore_test.go
  shared/keystore/utils.go
  shared/params/config.go
  shared/testutil/BUILD.bazel
  shared/testutil/tempdir.go
  validator/accounts/BUILD.bazel
  validator/accounts/account.go
  validator/accounts/account_test.go
  validator/client/BUILD.bazel
  validator/client/service.go
  validator/client/service_test.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
  validator/client/validator_test.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/node_test.go
Labels: Ready For Review

#1562 Implement Verify Bitfield
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator_test.go
  shared/params/config.go
Labels: Ready For Review

#1585 Remove Old References to Block Vote Cache
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/validity_conditions_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block_vote_cache.go
  beacon-chain/db/block_vote_cache_test.go
  beacon-chain/db/db.go
  beacon-chain/db/schema.go
  beacon-chain/dbcleanup/BUILD.bazel
  beacon-chain/dbcleanup/service.go
  beacon-chain/dbcleanup/service_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/utils/BUILD.bazel
  beacon-chain/utils/block_vote_cache.go
  beacon-chain/utils/block_vote_cache_test.go
Labels: Ready For Review

#1590 Support Typed Nil Pointer in Tree Hash
  shared/ssz/hash.go
  shared/ssz/hash_test.go
Labels: Ready For Review

#1591 Add ChainStart Delay Flag
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/utils/flags.go
Labels: Ready For Review

#1577 Use Tree Hashing Algorithm Everywhere for Block Roots and State Root
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block.go
  beacon-chain/db/block_operations.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  shared/hashutil/BUILD.bazel
  shared/hashutil/beacon_block.go
  shared/hashutil/beacon_block_test.go
  shared/ssz/decode.go
  shared/ssz/encode.go
  shared/ssz/hash.go
  validator/client/validator_propose.go
Labels: Priority: High, Ready For Review

#1597 Eliminate Repeated Expensive Operation in Client Tests
  validator/client/service_test.go
  validator/client/validator_propose_test.go
Labels: Enhancement, Ready For Review

#1602 Revive Our Demo Config for Local Testing
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/blocks/validity_conditions_test.go
  beacon-chain/rpc/validator_server_test.go
  shared/params/config.go
Labels: Enhancement, Ready For Review

#1604 Fixed Epoch Committee Count's Lower Bound to 1
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
Labels: Ready For Review

#1606 Retrieve Attestations from Operation Service
  beacon-chain/db/attestation.go
  beacon-chain/db/attestation_test.go
  beacon-chain/operations/BUILD.bazel
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
Labels: Ready For Review

#1617 Pending Attestations RPC Server/Client Implementation
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/client/validator.go
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
  validator/client/validator_test.go
  validator/internal/proposer_service_mock.go
Labels: Priority: High, Ready For Review

#1605 Adding batched logs
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/node.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  shared/params/config.go
Labels: Ready For Review

#1620 Fix Penalize Validator Precondition
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
Labels: Bug, Ready For Review

#1619 Fix Off By One Attestation Bug
  beacon-chain/core/blocks/block_operations.go
Labels: Bug, Ready For Review

#1622 Add a Note for Leap Sec in Block Validity Condition
  beacon-chain/core/blocks/validity_conditions.go
Labels: Ready For Review

#1623 Skips Attestation Older than Finalized Slot
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
Labels: Ready For Review

#1621 Name Changes to Align with V0.3
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/state_test_format.go
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/randao.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/block_operations.go
  beacon-chain/db/block_operations_test.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/db/state_test.go
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/utils/shuffle_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  shared/params/config.go
  shared/slotutil/slotticker_test.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_propose.go
  validator/client/validator_test.go
Labels: Ready For Review

#1628 Update CheckBit for Small Endian
  beacon-chain/attestation/service_test.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/validators/validator_test.go
  shared/bitutil/bit.go
  shared/bitutil/bit_test.go
Labels: Ready For Review

#1626 Remove Processed Block Operations from DB
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/attestations/BUILD.bazel
  beacon-chain/core/attestations/attestation.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/attestation.go
  beacon-chain/db/attestation_test.go
  beacon-chain/node/node.go
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
Labels: Ready For Review

#1596 Fetch the Correct Chain Head During AttestHead
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/client/validator.go
  validator/client/validator_attest.go
Labels: Priority: High, Ready For Review

#1625 Create Wrapper Around Pure Go BLS Project in Prysm
  WORKSPACE
  shared/bls/BUILD.bazel
  shared/bls/bls.go
  shared/bls/bls_test.go
  shared/bytesutil/bytes.go
  shared/keystore/BUILD.bazel
  shared/keystore/key.go
  shared/keystore/key_test.go
  shared/keystore/keystore.go
  shared/keystore/keystore_test.go
  shared/keystore/utils.go
  validator/accounts/account.go
  validator/client/validator.go
  validator/client/validator_attest.go
Labels: Priority: High, Ready For Review

#1624 First pass on pow faucet for testnet
  BUILD.bazel
  WORKSPACE
  k8s/beacon-chain/testnet-site.yaml
  k8s/geth/BUILD.bazel
  k8s/geth/faucet.deploy.yaml
  k8s/geth/faucet.encrypted_secret.yaml
  k8s/geth/faucet.service.yaml
  k8s/geth/goerli.config.yaml
  k8s/geth/nodes.deploy.yaml
  k8s/geth/public_nodes.service.yaml
  k8s/prylabs-wildcard-gateway.yaml
  proto/faucet/BUILD.bazel
  proto/faucet/faucet.pb.go
  tools/faucet/BUILD.bazel
  tools/faucet/main.go
  tools/faucet/server.go
Labels: Ready For Review

#1644 Move Deposit Encoding to Helpers Package
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/deposits.go
  beacon-chain/core/helpers/deposits_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/state_test.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/regular_sync_test.go
Labels: Priority: High, Ready For Review

#1648 Contract drain (for test/debug only!)
  beacon-chain/powchain/service_test.go
  contracts/deposit-contract/abi.json
  contracts/deposit-contract/bytecode.bin
  contracts/deposit-contract/deployContract/BUILD.bazel
  contracts/deposit-contract/deployContract/deployContract.go
  contracts/deposit-contract/depositContract.go
  contracts/deposit-contract/depositContract.v.py
  contracts/deposit-contract/depositContract_test.go
Labels: Ready For Review

#1641 Implement Next Epoch Committee Assignment for RPC Server
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  validator/internal/attester_service_mock.go
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review

#1633 Implement BLS Based RANDAO
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/chaintest/tests/state-tests/block-processing.yaml
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state_test.go
  beacon-chain/rpc/validator_server_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service_test.go
Labels: Priority: High, Ready For Review

#1654 Implement Attestation Req/Res for Sync Service
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: Ready For Review

#1618 Add Utility to Send Deposit Transactions
  WORKSPACE
  contracts/deposit-contract/sendDepositTx/BUILD.bazel
  contracts/deposit-contract/sendDepositTx/README.md
  contracts/deposit-contract/sendDepositTx/sendDeposits.go
Labels: Ready For Review

#1615 Implement Eth1Data RPC Server Functionality
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/service.go
Labels: Priority: High, Ready For Review

#1650 Implement Randao Reveal Signing in Proposer Client
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/beacon_server.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  shared/forkutils/BUILD.bazel
  shared/forkutils/signature.go
  shared/forkutils/signature_test.go
  validator/client/BUILD.bazel
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
  validator/internal/beacon_service_mock.go
Labels: Ready For Review

#1655 Remove Redundant Committee Assignment Getters in Validator RPC Service
  beacon-chain/internal/validator_service_mock.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  scripts/update-mockgen.sh
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_test.go
  validator/internal/beacon_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review

#1663 Implement Process Slot for Per-slot Processing
  beacon-chain/blockchain/service.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/transition.go
Labels: Ready For Review

#1665 Fatal if ChainStart Receiving Fails
  beacon-chain/node/node.go
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
  beacon-chain/rpc/service.go
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Bug, Priority: High, Ready For Review

#1666 Custom ChainStart Genesis Time Delay in Deposit Contract
  beacon-chain/powchain/service_test.go
  contracts/deposit-contract/abi.json
  contracts/deposit-contract/bytecode.bin
  contracts/deposit-contract/deployContract/deployContract.go
  contracts/deposit-contract/depositContract.go
  contracts/deposit-contract/depositContract.v.py
  contracts/deposit-contract/depositContract_test.go
Labels: Enhancement, Priority: High, Ready For Review

#1684 fix zero being power of two
  shared/mathutil/math_helper.go
  shared/mathutil/math_helper_test.go
Labels: Ready For Review

#1687 Add example encoding for godoc ssz
  shared/ssz/BUILD.bazel
  shared/ssz/example_encode_test.go
Labels: Ready For Review

#1675 DepositInput: Proof of possession, withdrawal credentials
  shared/keystore/BUILD.bazel
  shared/keystore/deposit_input.go
  shared/keystore/deposit_input_test.go
  shared/params/config.go
  validator/accounts/BUILD.bazel
  validator/accounts/account.go
Labels: Ready For Review

#1594 Test Syncing with Another Fully Synced Service
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/chaintest/backend/simulated_backend_test.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/blocks/validity_conditions_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block_test.go
  beacon-chain/db/setup_db.go
  beacon-chain/db/state.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/querier.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/sync/simulated_sync_test.go
  validator/accounts/account.go
  validator/accounts/account_test.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_propose.go
  validator/client/validator_test.go
  validator/main.go
Labels: Priority: High, Ready For Review

#1692 Add validator balance metric
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/metrics.go
  beacon-chain/core/state/metrics_test.go
  beacon-chain/core/state/transition.go
Labels: Ready For Review

#1674 Miscellaneous Runtime Fixes & Improvements - Raul
  beacon-chain/attestation/service.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/blocks/validity_conditions.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/metrics_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/node/node.go
  beacon-chain/operations/service.go
  beacon-chain/operations/service_test.go
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/rpc/proposer_server_test.go
  beacon-chain/rpc/service_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/regular_sync.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  shared/params/config.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
  validator/internal/proposer_service_mock.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/types/flags.go
Labels: Priority: Critical, Ready For Review

#1690 Save Validator Public Key -> Index in DB
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/db.go
  beacon-chain/db/schema.go
  beacon-chain/db/state.go
  beacon-chain/db/validator.go
  beacon-chain/db/validator_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
Labels: Ready For Review

#1703 Align Epoch Processing With Spec
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/balances/rewards_penalties_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/beacon_server.go
Labels: Bug

#1711 Revert Usage of ssz.TreeHash Across Repo
  beacon-chain/attestation/BUILD.bazel
  beacon-chain/attestation/service_test.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/fork_choice.go
  beacon-chain/blockchain/fork_choice_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/chaintest/backend/BUILD.bazel
  beacon-chain/chaintest/backend/helpers.go
  beacon-chain/chaintest/backend/simulated_backend.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_test.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_test.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/block.go
  beacon-chain/db/block_test.go
  beacon-chain/db/state.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/attester_server.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/rpc/proposer_server.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  shared/hashutil/BUILD.bazel
  shared/hashutil/beacon_block.go
  shared/hashutil/beacon_block_test.go
  validator/client/BUILD.bazel
  validator/client/validator_propose.go
Labels: Enhancement, Priority: High, Ready For Review

#1713 Registry Change Check Fix
  beacon-chain/core/helpers/validators.go
  beacon-chain/rpc/validator_server.go
Labels: Bug

#1694 Update Initial Sync
  beacon-chain/blockchain/service.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/querier.go
  beacon-chain/sync/querier_test.go
  beacon-chain/sync/regular_sync.go
  beacon-chain/sync/regular_sync_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/simulated_sync_test.go
  shared/params/config.go
Labels: Priority: High, Ready For Review

#1716 Reduce Sync Test Time
  shared/params/config.go
Labels: Ready For Review

#1715 Fix attestation inclusion
  beacon-chain/blockchain/service.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
Labels: Bug, Ready For Review

#1708 Move Node State Transition Logging to Block Chain Service
  beacon-chain/blockchain/service.go
  beacon-chain/core/state/transition.go
Labels: Ready For Review

#1722 Use RegistryChanged Flag in CrosslinkCommitteesAtSlot Everywhere
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/powchain/service.go
Labels: Bug

#1721 Fix Get Previous Epoch Logic
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/slot_epoch.go
Labels: Ready For Review

#1724 Complain if contract address changes
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/verify_contract.go
  beacon-chain/db/verify_contract_test.go
  beacon-chain/node/node.go
Labels: Ready For Review

#1720 Fix Invalid Timestamp From ChainStart Log Issue
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: Bug

#1723 Fix Validator Slashed Epoch Calculation
  beacon-chain/core/validators/validator.go
Labels: Bug

#1738 Update renovates
  WORKSPACE
Labels: Ready For Review

#1740 Fix committee assignment bugs
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
Labels: Bug

#1743 Rename Shard Block Root to Crosslink Data Root
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_operations.go
  beacon-chain/core/epoch/epoch_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/attester_server_test.go
  beacon-chain/sync/regular_sync_test.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
Labels: Ready For Review

#1746 Make Getting Epoch Assignment Generic
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/rpc/validator_server.go
  beacon-chain/rpc/validator_server_test.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  scripts/update-mockgen.sh
  validator/internal/beacon_service_mock.go
  validator/internal/proposer_service_mock.go
  validator/internal/validator_service_mock.go
Labels: Ready For Review

#1754 Add Address Check
  beacon-chain/node/node.go
Labels: Ready For Review

#1761 Remove Next Epoch Registry Change Checks
  beacon-chain/core/balances/rewards_penalties.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/validators.go
Labels: Ready For Review

#1757 Optimize ETH1 Data Vote
  beacon-chain/rpc/beacon_server.go
  beacon-chain/rpc/beacon_server_test.go
Labels: Ready For Review
