Repository OffchainLabs/prysm, pull requests merged in 2020-06, with the labels that each got.

#6062 Forkchoice start using proper root
  beacon-chain/blockchain/head.go
Labels: Ready For Review

#6066 Reset Streams Properly
  beacon-chain/p2p/handshake.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_status.go
Labels: Networking, Ready For Review

#6067 Fixes intersection functions (uint64, int64, []byte)
  shared/sliceutil/slice.go
  shared/sliceutil/slice_test.go
Labels: Ready For Review

#6054 Ensure Consistent ListValidators RPC Results
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge, Ready For Review

#6028 Add More Tests to CommitteeAssignments
  beacon-chain/core/helpers/committee_test.go
Labels: OK to merge, Ready For Review

#6069 Cache genesis block root
  beacon-chain/blockchain/service.go
Labels: OK to merge, Ready For Review

#6071 Fixes subsequence matching in deleteValueForIndices
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/utils.go
  beacon-chain/db/kv/utils_test.go
Labels: OK to merge, Ready For Review

#6046 Fix Status Messages During Genesis
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/service.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
Labels: OK to merge, Ready For Review, Testnet

#6073 Use `stateutil.BlockRoot` instead of `ssz` for fork choice
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_block_helpers.go
Labels: OK to merge

#5865 Update Geth Fork
  WORKSPACE
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  contracts/deposit-contract/depositContract.go
  deps.bzl
  go.mod
  go.sum
  nogo_config.json
  third_party/io_bazel_rules_go.patch
Labels: OK to merge, Ready For Review

#6075 use `stateutil.BlockRoot` instead of `ssz` for forkchoice
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_block_helpers.go
Labels: OK to merge, Ready For Review

#6061 New spanner db structure
  beacon-chain/db/kv/attestations.go
  slasher/db/iface/BUILD.bazel
  slasher/db/iface/interface.go
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/benchmark_test.go
  slasher/db/kv/epoch_store.go
  slasher/db/kv/epoch_store_test.go
  slasher/db/kv/kv.go
  slasher/db/kv/schema.go
  slasher/db/kv/spanner_new.go
  slasher/db/kv/spanner_new_test.go
Labels: Ready For Review

#6085 Add Sync Pool For Snappy
  beacon-chain/p2p/encoder/BUILD.bazel
  beacon-chain/p2p/encoder/snappy_test.go
  beacon-chain/p2p/encoder/ssz.go
Labels: Ready For Review

#6048 Split validator databases
  validator/accounts/account.go
  validator/accounts/account_test.go
  validator/db/BUILD.bazel
  validator/db/manage.go
  validator/db/manage_test.go
  validator/flags/flags.go
  validator/main.go
  validator/usage.go
Labels: OK to merge

#6084 Rollback libp2p kad dht dependency update
  beacon-chain/p2p/service.go
  deps.bzl
  go.mod
  go.sum
  tools/bootnode-query/main.go
  tools/bootnode/bootnode.go
Labels: OK to merge, Priority: High, Ready For Review

#6101 Fixes go fmt issues
  validator/db/manage_test.go
  validator/flags/flags.go
Labels: OK to merge, Ready For Review

#6090 Enable JSON-HTTP Gateway by Default on Port 3000
  beacon-chain/flags/base.go
  beacon-chain/gateway/gateway.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/usage.go
Labels: API, Enhancement, OK to merge, Ready For Review

#6105 Disable some static analysis checks for coverage builds
  .bazelrc
  BUILD.bazel
  beacon-chain/p2p/service.go
  beacon-chain/powchain/service.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  nogo_config.json
  slasher/beaconclient/service.go
Labels: OK to merge, Ready For Review

#6109 Save unaggregated att in `beacon_aggregate_and_proof` subscriber
  beacon-chain/sync/subscriber_beacon_aggregate_proof.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
Labels: OK to merge, Ready For Review

#6055 Remove Websockets for ETH1 From Prysm
  beacon-chain/blockchain/service_test.go
  beacon-chain/flags/base.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/usage.go
  endtoend/components/beacon_node.go
  shared/featureconfig/flags.go
Labels: Enhancement, OK to merge, Ready For Review

#6112 Assert gfind is available on OSX, for protobufs updates
  scripts/common.sh
  scripts/update-go-pbs.sh
  scripts/update-go-ssz.sh
Labels: OK to merge, Ready For Review

#6092 Add indice to certain validator logs
  validator/accounts/status.go
  validator/accounts/status_test.go
  validator/client/validator.go
  validator/client/validator_metrics.go
  validator/client/validator_test.go
Labels: Ready For Review

#6117 Fix broken v0.12 tests
  beacon-chain/core/state/benchmarks_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
Labels: v0.12

#6118 Add `NewBeaconBlock` to testutil
  shared/testutil/block.go
Labels: Ready For Review

#6108 Simplified validator flags
  validator/flags/flags.go
  validator/main.go
  validator/usage.go
Labels: OK to merge

#6113 Bind Service Endpoints to Localhost by Default
  beacon-chain/flags/base.go
  beacon-chain/gateway/server/main.go
  beacon-chain/node/node.go
  endtoend/components/eth1.go
  slasher/flags/flags.go
  tools/eth1exporter/main.go
Labels: Ready For Review

#6115 Add public keys to response for GetValidatorPerformance
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge

#6125 Re-enable previous fetching algorithm testing
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
Labels: OK to merge, Ready For Review

#6124 Disable Kademlia Discovery By Default
  beacon-chain/p2p/service.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#6122 Remove Balance Updates With Excessive Locking
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/helpers/rewards_penalties.go
Labels: Ready For Review, v0.12

#6119 Add AttestationDataRoot to stateutil
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/attestations.go
  beacon-chain/state/stateutil/attestations_test.go
Labels: Ready For Review

#6102 Add more fields for fast ssz marshal
  beacon-chain/blockchain/init_sync_process_block_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/encoding.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/exit_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status_test.go
  beacon-chain/state/stategen/hot_test.go
  beacon-chain/state/stategen/replay_test.go
  shared/testutil/block.go
Labels: Ready For Review, v0.12

#6126 Notify users' with warning about using default ETH 1.0 RPC
  beacon-chain/node/node.go
Labels: OK to merge, Ready For Review

#6099 Pretty pcli
  go.mod
  tools/pcli/BUILD.bazel
  tools/pcli/main.go
Labels: Ready For Review

#6087 Invert new state mgmt to default
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review, v0.12

#6137 Fix aggregator with unaggregated attestation
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/pool.go
  beacon-chain/rpc/validator/aggregator.go
  beacon-chain/rpc/validator/aggregator_test.go
Labels: OK to merge, Ready For Review

#6140 Remove unused bazel test target
  slasher/rpc/BUILD.bazel
Labels: OK to merge

#6136 Use stateutil AttestationDataRoot instead of go-ssz
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/attestations_test.go
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/validator/attester.go
Labels: OK to merge, Ready For Review

#6134 Fix inaccurate validator balance metrics
  beacon-chain/rpc/beacon/validators.go
  validator/client/validator_metrics.go
Labels: OK to merge, Ready For Review

#6143 Re-enables multi-failure test case in round robin
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: OK to merge, Ready For Review

#6138 Log commit hash on slasher startup
  slasher/node/BUILD.bazel
  slasher/node/node.go
  slasher/rpc/server.go
  slasher/rpc/service.go
  slasher/rpc/service_test.go
Labels: OK to merge, Ready For Review

#6135 Use FastSSZ Everywhere Applicable
  beacon-chain/core/blocks/spectest/attestation_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_test.go
  beacon-chain/core/blocks/spectest/block_header_test.go
  beacon-chain/core/blocks/spectest/block_processing_test.go
  beacon-chain/core/blocks/spectest/deposit_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_test.go
  beacon-chain/core/state/interop/BUILD.bazel
  beacon-chain/core/state/interop/write_block_to_disk.go
  beacon-chain/core/state/interop/write_state_to_disk.go
  beacon-chain/core/state/spectest/slot_processing_test.go
  beacon-chain/interop-cold-start/BUILD.bazel
  beacon-chain/interop-cold-start/service.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/encoder/BUILD.bazel
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/fork.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/rpc/debug/BUILD.bazel
  beacon-chain/rpc/debug/block.go
  beacon-chain/rpc/debug/block_test.go
  beacon-chain/rpc/debug/state.go
  beacon-chain/rpc/debug/state_test.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  deps.bzl
  fuzz/attestation_fuzz.go
  fuzz/block_fuzz.go
  fuzz/block_header_fuzz.go
  fuzz/common.go
  fuzz/deposit_fuzz.go
  go.mod
  go.sum
  proto/testing/ssz_regression_test.go
  shared/benchutil/BUILD.bazel
  shared/benchutil/pregen.go
  shared/hashutil/hash.go
  shared/testutil/spectest.go
  shared/trieutil/BUILD.bazel
  shared/trieutil/sparse_merkle_test.go
  third_party/com_github_prysmaticlabs_go_ssz.patch
  tools/benchmark-files-gen/BUILD.bazel
  tools/benchmark-files-gen/main.go
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
  tools/genesis-state-gen/BUILD.bazel
  tools/genesis-state-gen/main.go
  tools/interop/export-genesis/BUILD.bazel
  tools/interop/export-genesis/main.go
  tools/update-genesis-time/main.go
Labels: OK to merge, Ready For Review

#6147 Update RPC Responses For V0.12.1
  beacon-chain/sync/error.go
  beacon-chain/sync/error_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/generated.ssz.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  proto/beacon/rpc/v1_gateway/debug.pb.gw.go
  shared/params/network_config.go
Labels: Networking, Ready For Review

#6151 Only build with cgosymbolizer when explicitly requested
  .bazelrc
  shared/debug/cgo_symbolizer.go
Labels: Bug, OK to merge

#6149 Check attestation has pre state before retrieving it
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
Labels: Ready For Review

#6152 Fix Status Message Handling
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
Labels: Ready For Review

#6141 Fix Gossip Clock Disparity
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/utils_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
Labels: OK to merge, Ready For Review, Security

#6154 Update v0.12.1 badge
  README.md
Labels: Ready For Review

#6128 Clean Up Discovery Filtering of Peers
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/service.go
Labels: Networking, Ready For Review

#6159 Verify historical slots per archived point
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/check_historical_state.go
  beacon-chain/db/kv/check_historical_test_test.go
Labels: Enhancement, OK to merge, Ready For Review

#6168 Move dependencies to the deps.bzl file and out of the WORKSPACE
  DEPENDENCIES.md
  WORKSPACE
  deps.bzl
Labels: OK to merge, Ready For Review

#6160 Update Spec Tests
  WORKSPACE
Labels: Ready For Review

#6173 Rename white/blacklist to allow/deny list
  beacon-chain/db/kv/encoding.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/options_test.go
  beacon-chain/usage.go
  shared/cmd/flags.go
  shared/featureconfig/BUILD.bazel
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  tools/cluster-pk-manager/server/db.go
Labels: OK to merge, Ready For Review

#6165 Force manual validator account creation
  validator/keymanager/direct_keystore.go
  validator/node/node.go
Labels: Ready For Review

#6146 Init-sync queue assert order and uniqueness of blocks emitted
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
Labels: OK to merge, Ready For Review

#6166 Add debug endpoint for individual vote status
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  deps.bzl
  go.mod
  go.sum
  proto/beacon/rpc/v1/debug.pb.go
  proto/beacon/rpc/v1/debug.proto
  proto/beacon/rpc/v1_gateway/debug.pb.go
  proto/cluster/services.pb.go
  shared/mock/beacon_service_mock.go
Labels: Enhancement, Ready For Review

#6182 Fixes span naming in rpc/validator
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/status.go
Labels: OK to merge, Ready For Review

#6142 Remove Excess State Copies
  beacon-chain/blockchain/process_attestation_helpers.go
Labels: Ready For Review

#6185 Invert reduce attester state copies
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Enhancement, Ready For Review

#6186 Resolve Final Outstanding Comments for v0.12
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/subscriber.go
Labels: Ready For Review

#6188 Head eth1data tests
  beacon-chain/blockchain/chain_info_test.go
Labels: Ready For Review

#6187 Inverts enable-init-sync-wrr flag
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#6190 Ivan's v0.12 Feedback
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  shared/featureconfig/config.go
Labels: Ready For Review

#6181 Improves operations/attestations/kv test coverage
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/pool.go
Labels: OK to merge, Ready For Review

#6191 Make a simple json-rpc call to ensure we are connected to a real ETH1 node
  beacon-chain/powchain/service.go
Labels: OK to merge, Ready For Review

#6184 Use Updated Connection Manager
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/connmgr/BUILD.bazel
  beacon-chain/p2p/connmgr/connmgr.go
  beacon-chain/p2p/connmgr/connmgr_test.go
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/options.go
  go.mod
  go.sum
Labels: OK to merge

#6192 Update bootnode ENR for Onyx
  shared/cmd/flags.go
Labels: OK to merge, Ready For Review

#6193 Update RBE toolchain and image to have libgmp-dev with bazel 3.2.0
  .bazelversion
  third_party/herumi/bls_eth_go_binary.BUILD
  third_party/herumi/mcl.BUILD
  tools/cross-toolchain/Dockerfile
  tools/cross-toolchain/configs/.latest.bazelrc
  tools/cross-toolchain/configs/clang/bazel_3.2.0/cc/BUILD
  tools/cross-toolchain/configs/clang/bazel_3.2.0/cc/armeabi_cc_toolchain_config.bzl
  tools/cross-toolchain/configs/clang/bazel_3.2.0/cc/builtin_include_directory_paths
  tools/cross-toolchain/configs/clang/bazel_3.2.0/cc/cc_toolchain_config.bzl
  tools/cross-toolchain/configs/clang/bazel_3.2.0/cc/cc_wrapper.sh
  tools/cross-toolchain/configs/clang/bazel_3.2.0/config/BUILD
  tools/cross-toolchain/configs/clang/bazel_3.2.0/java/BUILD
  tools/cross-toolchain/configs/clang/bazel_3.2.0/prysm_toolchains/BUILD.bazel
  tools/cross-toolchain/configs/clang/bazel_3.2.0/prysm_toolchains/WORKSPACE
  tools/cross-toolchain/configs/clang/bazel_3.2.0/prysm_toolchains/cc_toolchain_config_linux_arm64.bzl
  tools/cross-toolchain/configs/clang/bazel_3.2.0/prysm_toolchains/cc_toolchain_config_osx.bzl
  tools/cross-toolchain/configs/clang/bazel_3.2.0/prysm_toolchains/cc_toolchain_config_windows.bzl
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/cc/BUILD
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/cc/armeabi_cc_toolchain_config.bzl
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/cc/builtin_include_directory_paths
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/cc/cc_toolchain_config.bzl
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/cc/cc_wrapper.sh
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/config/BUILD
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/java/BUILD
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/prysm_toolchains/BUILD.bazel
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/prysm_toolchains/WORKSPACE
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/prysm_toolchains/cc_toolchain_config_linux_arm64.bzl
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/prysm_toolchains/cc_toolchain_config_osx.bzl
  tools/cross-toolchain/configs/gcc/bazel_3.2.0/prysm_toolchains/cc_toolchain_config_windows.bzl
  tools/cross-toolchain/configs/versions.bzl
  tools/cross-toolchain/rbe_toolchains_config.bzl
Labels: OK to merge, Ready For Review

#6194 Add --random flag for unencrypted keygen
  tools/unencrypted-keys-gen/BUILD.bazel
  tools/unencrypted-keys-gen/main.go
Labels: OK to merge, Ready For Review

#6210 Add the latest git tag as part of the version string
  scripts/workspace_status.sh
  shared/version/BUILD.bazel
  shared/version/version.go
Labels: Ready For Review

#6208 Fix long running E2E deposits testing
  endtoend/components/beacon_node.go
  endtoend/components/slasher.go
  endtoend/components/validator.go
  endtoend/evaluators/operations.go
  endtoend/long_minimal_e2e_test.go
  endtoend/minimal_e2e_test.go
  endtoend/minimal_slashing_e2e_test.go
  endtoend/params/params.go
Labels: OK to merge, Ready For Review

#6211 Adds a User Agent for Libp2p
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/options.go
  shared/version/version.go
Labels: Ready For Review

#6214 Fix proposer calculation in sync
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review

#6217 Revert "Send blocks that fails validation to slasher"
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge

#6218 Resolve Nil Validator Panic
  beacon-chain/state/getters.go
  beacon-chain/state/getters_test.go
Labels: OK to merge, Ready For Review

#6150 Cleanup flat spans implementation
  slasher/db/iface/BUILD.bazel
  slasher/db/iface/interface.go
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/benchmark_test.go
  slasher/db/kv/epoch_store.go
  slasher/db/kv/epoch_store_test.go
  slasher/db/kv/schema.go
  slasher/db/kv/spanner.go
  slasher/db/kv/spanner_new.go
  slasher/db/kv/spanner_new_test.go
  slasher/detection/attestations/types/BUILD.bazel
  slasher/detection/attestations/types/epoch_store.go
  slasher/detection/attestations/types/epoch_store_test.go
  slasher/detection/attestations/types/types.go
Labels: Ready For Review

#6174 No sig slasher rpc
  proto/slashing/slashing.pb.go
  proto/slashing/slashing.proto
  slasher/detection/detect.go
  slasher/detection/detect_test.go
  slasher/detection/proposals/detector.go
  slasher/detection/proposals/iface/iface.go
  slasher/detection/testing/utils.go
  slasher/rpc/server.go
  slasher/rpc/server_test.go
  validator/slashing-protection/external_test.go
Labels: OK to merge, Ready For Review

#6212 Provide some feedback to user when creating an account
  validator/accounts/account.go
Labels: OK to merge, Ready For Review

#6213 Fix Proposer Bug in Prysm
  beacon-chain/rpc/validator/proposer.go
Labels: Bug, OK to merge, Priority: Critical, Ready For Review

#6221 Reduce JSON-RPC queries
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/service.go
Labels: OK to merge, Ready For Review

#6225 Do Not Wait Till Genesis
  beacon-chain/sync/service.go
Labels: Bug, OK to merge, Priority: Critical, Ready For Review, Testnet

#6226 Follow Up to #6225
  beacon-chain/sync/service.go
Labels: OK to merge

#6222 Sort Duplicate Blocks In Response
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/utils.go
  beacon-chain/sync/utils_test.go
Labels: OK to merge, Ready For Review

#6230 Add dockerhub image endpoints
  beacon-chain/BUILD.bazel
  slasher/BUILD.bazel
  validator/BUILD.bazel
Labels: OK to merge, Ready For Review

#6228 Skip proposer duty calculation for slot 0
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
Labels: Bug, Ready For Review

#6231 Countdown Until Genesis
  beacon-chain/blockchain/service.go
  beacon-chain/interop-cold-start/BUILD.bazel
  beacon-chain/interop-cold-start/service.go
  shared/params/config.go
  shared/slotutil/BUILD.bazel
  shared/slotutil/countdown.go
  shared/slotutil/countdown_test.go
Labels: OK to merge, Ready For Review

#6232 Do Not Ignore Max Gateway Size gRPC
  beacon-chain/gateway/gateway.go
Labels: API, OK to merge, Ready For Review

#6233 Add a Log for Newly Connected gRPC Clients in the Beacon Node
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  go.sum
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#6237 Don't regen parent state for genesis state
  beacon-chain/blockchain/service.go
Labels: Ready For Review

#6199 Add cache for flan spans
  slasher/cache/BUILD.bazel
  slasher/cache/doc.go
  slasher/cache/flat_span_cache.go
  slasher/cache/span_cache.go
  slasher/db/kv/kv.go
  slasher/db/kv/spanner_new.go
Labels: Ready For Review

#6240 Revert "Remove Excess State Copies"
  beacon-chain/blockchain/process_attestation_helpers.go
Labels: OK to merge

#6242 Fix ancestor to return most recent root in the case of skip slot
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: OK to merge, Ready For Review

#6243 Use Connection Gater to Manage Peer Connections
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/connection_gater.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/p2p.go
Labels: OK to merge, Ready For Review

#6246 Fix pubkey used in validator metrics
  validator/client/validator_metrics.go
Labels: OK to merge, Ready For Review

#6249 Fix Genesis Justified Checkpoints
  beacon-chain/blockchain/process_block_helpers.go
Labels: OK to merge, Ready For Review

#6250 Mark Peer As Bad After a Failed Validation
  beacon-chain/sync/rpc_status.go
Labels: Ready For Review

#6251 Filter Peers Properly With Connection Gater
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/connection_gater.go
  beacon-chain/p2p/connection_gater_test.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/options_test.go
  beacon-chain/p2p/service.go
Labels: OK to merge

#6254 `ActiveValidatorCount` to use cache
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
Labels: Enhancement, Ready For Review

#6261 Fix Discovery Panic
  deps.bzl
  go.mod
Labels: OK to merge

#6262 Updates go.sum
  go.sum
Labels: In Progress

#6264 Go mod tidy
  .github/actions/gomodtidy/Dockerfile
  .github/actions/gomodtidy/action.yml
  .github/actions/gomodtidy/entrypoint.sh
  .github/workflows/go.yml
Labels: OK to merge, Ready For Review

#6268 Default BeaconRPCProvider for Validator Should Match Beacon Node's Host
  validator/flags/flags.go
Labels: OK to merge, Ready For Review

#6267 Fix validator summary reporting
  beacon-chain/core/state/transition.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge, Ready For Review

#6271 Fix validator creation path issue on windows
  validator/accounts/account.go
  validator/main.go
Labels: Ready For Review

#6270 Fix windows DB path error and make errors more concise
  beacon-chain/db/kv/kv.go
  beacon-chain/node/node.go
Labels: OK to merge, Ready For Review

#6275 Fix underflow in SlotsSinceGenesis
  shared/slotutil/BUILD.bazel
  shared/slotutil/slottime.go
  shared/slotutil/slottime_test.go
Labels: OK to merge, Ready For Review

#6272 Use justified balances for fork choice
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
Labels: Ready For Review

#6283 Add --initial-sync-verify-all-signatures as a dev flag
  shared/featureconfig/flags.go
Labels: Ready For Review

#6277 Verify many block attestations at once
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/transition.go
  shared/bls/bls.go
Labels: Ready For Review

#6285 pre-allocate memory for AggregateVerify
  shared/bls/bls.go
Labels: OK to merge, Ready For Review

#6282 Fork choice avoids redundant call to get_ancestor
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  shared/attestationutil/attestation_utils.go
  shared/attestationutil/attestation_utils_test.go
Labels: Ready For Review

#6276 Clarify Insecure gRPC Connection Logs
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  validator/client/service.go
Labels: OK to merge, Ready For Review

#6248 Implement flat spans cache into DB
  slasher/db/iface/interface.go
  slasher/db/kv/benchmark_test.go
  slasher/db/kv/spanner_new.go
  slasher/db/kv/spanner_new_test.go
  slasher/db/types/types.go
  slasher/detection/attestations/types/BUILD.bazel
  slasher/detection/attestations/types/epoch_store.go
  slasher/detection/attestations/types/epoch_store_test.go
Labels: Ready For Review

#6269 Less restrictive block stream for slashing detection
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review

#6286 First part of block chain service cleanup
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: OK to merge, Ready For Review

#6293 Fix `GetValidatorPerformance` before/after balances
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#6295 Fix getting att pre state in sync
  beacon-chain/sync/validate_beacon_attestation.go
Labels: Bug, Ready For Review

#6292 Avoid active validator count cache for genesis
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
Labels: Ready For Review

#6296 Add @prysmaticlabs/core-team as codeowner for deps.bzl
  .github/CODEOWNERS
Labels: OK to merge

#6289 Update Node RPC Endpoints
  beacon-chain/node/node.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/fork.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/sender_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/mock_peersprovider.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/p2p/utils.go
  beacon-chain/rpc/node/BUILD.bazel
  beacon-chain/rpc/node/server.go
  beacon-chain/rpc/node/server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/rpc_goodbye_test.go
  beacon-chain/sync/rpc_metadata_test.go
  beacon-chain/sync/rpc_ping_test.go
  beacon-chain/sync/rpc_status_test.go
  deps.bzl
  go.mod
  go.sum
  shared/mock/beacon_chain_service_mock.go
  shared/mock/beacon_service_mock.go
  shared/mock/beacon_validator_client_mock.go
  shared/mock/beacon_validator_server_mock.go
  shared/mock/node_service_mock.go
Labels: OK to merge, Ready For Review

#6301 Update BLS
  third_party/herumi/herumi.bzl
Labels: Ready For Review

#5867 Stream Duties Client Implementation
  beacon-chain/state/stateutil/BUILD.bazel
  go.sum
  nogo_config.json
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/BUILD.bazel
  validator/client/metrics/BUILD.bazel
  validator/client/metrics/metrics.go
  validator/client/polling/BUILD.bazel
  validator/client/polling/fake_validator_test.go
  validator/client/polling/runner.go
  validator/client/polling/runner_test.go
  validator/client/polling/service.go
  validator/client/polling/service_test.go
  validator/client/polling/validator.go
  validator/client/polling/validator_aggregate.go
  validator/client/polling/validator_aggregate_test.go
  validator/client/polling/validator_attest.go
  validator/client/polling/validator_attest_test.go
  validator/client/polling/validator_log.go
  validator/client/polling/validator_metrics.go
  validator/client/polling/validator_propose.go
  validator/client/polling/validator_propose_test.go
  validator/client/polling/validator_test.go
  validator/client/streaming/BUILD.bazel
  validator/client/streaming/fake_validator_test.go
  validator/client/streaming/runner.go
  validator/client/streaming/runner_test.go
  validator/client/streaming/service.go
  validator/client/streaming/service_test.go
  validator/client/streaming/validator.go
  validator/client/streaming/validator_aggregate.go
  validator/client/streaming/validator_aggregate_test.go
  validator/client/streaming/validator_attest.go
  validator/client/streaming/validator_attest_test.go
  validator/client/streaming/validator_duties.go
  validator/client/streaming/validator_duties_test.go
  validator/client/streaming/validator_log.go
  validator/client/streaming/validator_metrics.go
  validator/client/streaming/validator_propose.go
  validator/client/streaming/validator_propose_test.go
  validator/client/streaming/validator_test.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
Labels: Ready For Review

#6307 Use STABLE_ prefix for git tag to force a relink of version
  scripts/workspace_status.sh
  shared/version/BUILD.bazel
Labels: OK to merge, Ready For Review

#6306 Add a debug log statement when enabling dev flags
  shared/featureconfig/config.go
Labels: OK to merge, Ready For Review

#6305 Implements max k-coverage greedy algorithm
  deps.bzl
  go.mod
  go.sum
  shared/aggregation/BUILD.bazel
  shared/aggregation/aggregation.go
  shared/aggregation/aggregation_test.go
  shared/aggregation/attestations.go
  shared/aggregation/attestations_test.go
  shared/aggregation/maxcover.go
  shared/aggregation/maxcover_test.go
Labels: OK to merge, Ready For Review

#6266 Fix Pagination Bug When Total Size % Page Size == 0
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks_test.go
  shared/pagination/pagination.go
  shared/pagination/pagination_test.go
Labels: Ready For Review

#6304 Add Debug Endpoints For Peers
  beacon-chain/rpc/debug/BUILD.bazel
  beacon-chain/rpc/debug/p2p.go
  beacon-chain/rpc/debug/p2p_test.go
  beacon-chain/rpc/debug/server.go
  beacon-chain/rpc/service.go
  proto/beacon/rpc/v1/BUILD.bazel
  proto/beacon/rpc/v1/debug.pb.go
  proto/beacon/rpc/v1/debug.proto
  proto/beacon/rpc/v1_gateway/debug.pb.go
  proto/beacon/rpc/v1_gateway/debug.pb.gw.go
Labels: Ready For Review

#6322 Fix race condition issues in beacon state
  beacon-chain/state/field_trie.go
  beacon-chain/state/setters.go
  beacon-chain/state/state_trie.go
  beacon-chain/state/types.go
Labels: OK to merge, Ready For Review

#6339 Reclaims leakybucket resources in sync service
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/service.go
Labels: OK to merge, Ready For Review

#6287 Add flat spans to slasher runtime
  slasher/beaconclient/submit.go
  slasher/db/kv/kv.go
  slasher/detection/attestations/BUILD.bazel
  slasher/detection/attestations/spanner.go
  slasher/detection/attestations/spanner_test.go
  slasher/detection/attestations/types/epoch_store.go
  slasher/detection/detect.go
Labels: Ready For Review

#6340 Release State Field Trie
  beacon-chain/state/state_trie.go
  beacon-chain/state/state_trie_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#6347 QSP8 - ActivationEligibilityEpoch nil case
  beacon-chain/state/getters.go
  beacon-chain/state/getters_test.go
Labels: Audit, Ready For Review

#6348 Renames receiver in sync service
  beacon-chain/sync/decode_pubsub.go
  beacon-chain/sync/error.go
  beacon-chain/sync/metrics.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_chunked_response.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof.go
  beacon-chain/sync/subscriber_beacon_attestation.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_handlers.go
  beacon-chain/sync/utils.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_voluntary_exit.go
Labels: OK to merge, Ready For Review

#6352 QSP58, QSP59 - Fix DB spans
  beacon-chain/db/kv/archive.go
  beacon-chain/db/kv/archived_point.go
Labels: Audit, OK to merge, Ready For Review

#6323 Remove All Instances of Kademlia from Prysm
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/config.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/service.go
  deps.bzl
  endtoend/components/beacon_node.go
  go.mod
  go.sum
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  tools/bootnode-query/main.go
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
  tools/bootnode/bootnode_test.go
Labels: OK to merge, Ready For Review

#6343 Adds aggregation/attestations package
  beacon-chain/state/BUILD.bazel
  shared/aggregation/BUILD.bazel
  shared/aggregation/attestations.go
  shared/aggregation/attestations/BUILD.bazel
  shared/aggregation/attestations/attestations.go
  shared/aggregation/attestations/attestations_test.go
  shared/aggregation/attestations/maxcover.go
  shared/aggregation/attestations/maxcover_test.go
  shared/aggregation/attestations/naive.go
  shared/aggregation/maxcover.go
  shared/aggregation/maxcover_test.go
  shared/aggregation/testing/BUILD.bazel
  shared/aggregation/testing/bitlistutils.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#6353 Minor Improvements
  beacon-chain/rpc/debug/p2p.go
  beacon-chain/sync/deadlines.go
Labels: OK to merge, Ready For Review

#6355 Fixes error message wording
  beacon-chain/blockchain/service.go
  beacon-chain/interop-cold-start/service.go
Labels: Audit, OK to merge, Ready For Review

#6356 Fixes receiver name in db/kv
  beacon-chain/db/kv/archive.go
  beacon-chain/db/kv/archived_point.go
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/backup.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/deposit_contract.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/operations.go
  beacon-chain/db/kv/powchain.go
  beacon-chain/db/kv/slashings.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_summary.go
Labels: Audit, OK to merge, Ready For Review

#6357 Resolves issues from the best practices in sync package
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_blocks_queue.go
Labels: Audit, OK to merge, Ready For Review

#6358 Resolves issues from the best practices in beacon-chain/db
  beacon-chain/db/filters/filter.go
  beacon-chain/db/kafka/export_wrapper.go
  beacon-chain/db/kv/archived_point.go
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/check_historical_state.go
  beacon-chain/db/kv/regen_historical_states.go
  beacon-chain/db/kv/utils.go
  beacon-chain/db/kv/utils_test.go
Labels: Audit, OK to merge, Ready For Review

#6359 SubscribeCommitteeSubnets fields length check
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/attester_test.go
Labels: OK to merge

#6361 Fix cold state replay to start at correct slot
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: OK to merge, Ready For Review

#6252 External slashing protection not requiring signature
  shared/blockutil/BUILD.bazel
  shared/blockutil/block_utils.go
  shared/blockutil/block_utils_test.go
  validator/client/polling/BUILD.bazel
  validator/client/polling/validator_attest.go
  validator/client/polling/validator_attest_test.go
  validator/client/polling/validator_propose.go
  validator/client/streaming/BUILD.bazel
  validator/client/streaming/validator_attest.go
  validator/client/streaming/validator_attest_test.go
  validator/client/streaming/validator_propose.go
  validator/slashing-protection/BUILD.bazel
  validator/slashing-protection/external.go
  validator/slashing-protection/external_test.go
  validator/slashing-protection/protector.go
  validator/testing/BUILD.bazel
  validator/testing/protector_mock.go
  validator/testing/slasher_mock.go
Labels: OK to merge, Ready For Review

#6344 Enables new aggregation implementation
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_aggregation_bench_test.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/aggregator_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/state/BUILD.bazel
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#6369 Refactor setupDB to return the state summary cache used by the database
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/init_sync_process_block_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service_norace_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/testing/setup_db.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/debug/BUILD.bazel
  beacon-chain/rpc/debug/block_test.go
  beacon-chain/rpc/debug/state_test.go
  beacon-chain/rpc/node/server_test.go
  beacon-chain/rpc/validator/aggregator_test.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/exit_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status_test.go
  beacon-chain/state/stategen/cold_test.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/hot_test.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/replay_test.go
  beacon-chain/state/stategen/service_test.go
  beacon-chain/state/stategen/setter_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/rpc_goodbye_test.go
  beacon-chain/sync/rpc_metadata_test.go
  beacon-chain/sync/rpc_ping_test.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/subscriber_beacon_attestation_test.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review

#6367 QSP-Docs All Documentation Improvements from Quantstamp Audit Report
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/justification_finalization.go
  beacon-chain/core/helpers/block.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/state/transition.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/encoder/ssz_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/utils.go
  beacon-chain/state/setters.go
  beacon-chain/state/state_trie.go
  beacon-chain/state/stateutil/state_root.go
  beacon-chain/state/types.go
  beacon-chain/sync/service.go
  shared/bytesutil/bytes.go
  shared/sliceutil/slice.go
  validator/flags/interop.go
  validator/node/node.go
Labels: Audit, OK to merge, Ready For Review

#6373 Remove new state mgmt within db package
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/check_historical_state.go
  beacon-chain/db/kv/checkpoint.go
Labels: OK to merge, Ready For Review

#6366 Add Mutex to Hot State Cache
  beacon-chain/cache/hot_state_cache.go
Labels: Audit, OK to merge, Ready For Review

#6371 QSP-61 Clarify Why Process Pending Attestations May Exit Early
  beacon-chain/sync/pending_attestations_queue.go
Labels: Audit, OK to merge, Ready For Review
