Repository OffchainLabs/prysm, pull requests merged in 2020-08, with the labels that each got.

#6819 Fix empty wallet check
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/wallet.go
  validator/accounts/v2/wallet_test.go
Labels: Bug, Ready For Review

#6821 `Load` config after `Configure` config
  beacon-chain/node/node.go
  validator/main.go
  validator/node/node.go
Labels: OK to merge, Ready For Review

#6807 Add Medalla bootnodes
  shared/params/testnet_medalla_config.go
Labels: Priority: High, Ready For Review

#6756 Adds block provider scorer
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/peers_test.go
  beacon-chain/p2p/peers/score_block_providers.go
  beacon-chain/p2p/peers/score_block_providers_test.go
  beacon-chain/p2p/peers/scorer_manager.go
  beacon-chain/p2p/peers/scorer_manager_test.go
  beacon-chain/p2p/peers/store.go
Labels: OK to merge, Ready For Review

#6827 Remove Custom Genesis Delay
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/usage.go
  shared/cmd/config.go
  shared/cmd/flags.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#6824 Change E2E config to test deposits in PR
  endtoend/BUILD.bazel
  endtoend/components/beacon_node.go
  endtoend/components/eth1.go
  endtoend/components/slasher.go
  endtoend/components/validator.go
  endtoend/endtoend_test.go
  endtoend/evaluators/metrics.go
  endtoend/evaluators/operations.go
  endtoend/helpers/helpers.go
  endtoend/long_minimal_e2e_test.go
  endtoend/minimal_e2e_test.go
  endtoend/params/params.go
  shared/params/testnet_e2e_config.go
Labels: Ready For Review

#6823 Refactor Direct Keymanager to One-Shot Decrypt
  go.mod
  shared/promptutil/prompt.go
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_create.go
  validator/accounts/v2/accounts_export.go
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/accounts_import_test.go
  validator/accounts/v2/accounts_list.go
  validator/accounts/v2/accounts_list_test.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/iface/wallet.go
  validator/accounts/v2/prompt.go
  validator/accounts/v2/testing/mock.go
  validator/accounts/v2/wallet.go
  validator/accounts/v2/wallet_create.go
  validator/accounts/v2/wallet_create_test.go
  validator/accounts/v2/wallet_edit.go
  validator/accounts/v2/wallet_test.go
  validator/keymanager/v2/direct/BUILD.bazel
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/direct_test.go
  validator/keymanager/v2/direct/import.go
  validator/keymanager/v2/direct/import_test.go
  validator/keymanager/v2/direct/migrate.go
  validator/keymanager/v2/direct/migrate_test.go
Labels: AccountsV2, Priority: Critical, Ready For Review

#6657 Add heap file to E2E artifacts and fix miscalculation for deposit processing
  endtoend/components/beacon_node.go
  endtoend/components/validator.go
  endtoend/endtoend_test.go
  endtoend/evaluators/metrics.go
  endtoend/evaluators/operations.go
  endtoend/helpers/helpers.go
  endtoend/minimal_slashing_e2e_test.go
  shared/params/testnet_e2e_config.go
Labels: OK to merge, Ready For Review

#6730 Fix CMD Config and modify --historical-slasher-node
  beacon-chain/flags/base.go
  beacon-chain/node/node.go
  shared/cmd/BUILD.bazel
  shared/cmd/config.go
  shared/cmd/config_test.go
  slasher/node/node.go
Labels: OK to merge, Ready For Review

#6836 Update medalla bootnodes
  shared/params/testnet_medalla_config.go
Labels: Networking, Ready For Review

#6849 Better Password Input Experience
  shared/promptutil/validate.go
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/import.go
Labels: AccountsV2, OK to merge, Ready For Review

#6853 Update `DepositContractFlag` default to Medalla
  beacon-chain/flags/base.go
Labels: Enhancement, OK to merge, Ready For Review

#6848 Use Less Intensive Search
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets.go
Labels: OK to merge, Ready For Review

#6852 `ForceCheckpoint` return early when zero hashes
  beacon-chain/state/stategen/setter.go
  beacon-chain/state/stategen/setter_test.go
Labels: Bug, OK to merge, Ready For Review

#6854 Fix Critical Account Keystores Bugs
  validator/accounts/v2/accounts_create.go
  validator/accounts/v2/accounts_list_test.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/wallet.go
  validator/keymanager/v2/direct/BUILD.bazel
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/direct_test.go
  validator/keymanager/v2/direct/import.go
  validator/keymanager/v2/direct/import_test.go
  validator/keymanager/v2/direct/migrate.go
Labels: AccountsV2, OK to merge, Priority: Critical, Ready For Review

#6856 Add Back Displaying Deposit Data + Misc Bugs
  validator/accounts/v2/accounts_list.go
  validator/accounts/v2/prompt.go
  validator/accounts/v2/wallet.go
  validator/keymanager/v2/derived/BUILD.bazel
  validator/keymanager/v2/derived/derived.go
  validator/keymanager/v2/direct/BUILD.bazel
  validator/keymanager/v2/direct/direct.go
Labels: AccountsV2, OK to merge, Priority: Critical, Ready For Review

#6861 Fix Justified and Finalized Retrieval in Genesis
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/checkpoint_test.go
Labels: Bug, OK to merge, Priority: Critical

#6874 Validate attestation: fix error log
  beacon-chain/core/helpers/attestation.go
Labels: Enhancement, OK to merge, Ready For Review

#6871 Slasher protection race condition fix
  beacon-chain/state/BUILD.bazel
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/server_test.go
Labels: OK to merge, Ready For Review

#6865 Change Sync Error Logs To Debug Logs
  beacon-chain/sync/error.go
  beacon-chain/sync/metrics.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_voluntary_exit.go
  endtoend/components/beacon_node.go
Labels: OK to merge, Ready For Review, Sync

#6875 Return an error when wallet is nil rather than panic
  validator/accounts/v2/wallet_create.go
Labels: Bug, Ready For Review

#6857 Fix Panic in Wallet HasDir()
  validator/accounts/v2/wallet.go
Labels: OK to merge, Ready For Review

#6877 Handle empty local slashing protection data
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/db/kv/attestation_history.go
Labels: OK to merge, Ready For Review

#6878 Return Err in Wallet.HasDir function
  validator/accounts/v2/wallet.go
Labels: OK to merge, Ready For Review

#6881 Remove Fuzzit badge
  README.md
Labels: Ready For Review

#6885 Warn users of upcoming breaking change to default value for eth1 provider flag
  beacon-chain/node/node.go
Labels: OK to merge, Ready For Review

#6879 Check roughtime more frequently when there is a large clock offset
  shared/roughtime/BUILD.bazel
  shared/roughtime/roughtime.go
Labels: Enhancement, OK to merge, Ready For Review

#6872 E2E: Add cpu profile and fix logs and sync time
  endtoend/components/beacon_node.go
  endtoend/components/validator.go
  endtoend/endtoend_test.go
  endtoend/evaluators/validator.go
  endtoend/helpers/helpers.go
  endtoend/minimal_e2e_test.go
  endtoend/params/params.go
  endtoend/types/types.go
Labels: Ready For Review

#6889 Slasher redial
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/receivers.go
  slasher/beaconclient/service.go
Labels: OK to merge, Ready For Review

#6894 Chain id and netork id flags
  beacon-chain/flags/base.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/usage.go
Labels: Enhancement, OK to merge, Ready For Review

#6899 Revert "Use Less Intensive Search"
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets.go
Labels: OK to merge

#6895 Add debug endpoint to get inclusion slot
  beacon-chain/rpc/debug/BUILD.bazel
  beacon-chain/rpc/debug/block.go
  beacon-chain/rpc/debug/block_test.go
  beacon-chain/rpc/service.go
  proto/beacon/rpc/v1/debug.pb.go
  proto/beacon/rpc/v1/debug.proto
  proto/beacon/rpc/v1_gateway/debug.pb.go
  proto/beacon/rpc/v1_gateway/debug.pb.gw.go
Labels: Enhancement, Ready For Review

#6900 Tool for Decrypting/Encrypting EIP-2335 Keystores
  tools/keystores/BUILD.bazel
  tools/keystores/main.go
  tools/keystores/main_test.go
  validator/keymanager/v2/BUILD.bazel
Labels: AccountsV2, Enhancement, Ready For Review

#6903 Add trace spans to GetBlock methods for a better understanding of block proposal delays
  beacon-chain/rpc/validator/proposer.go
Labels: OK to merge, Ready For Review

#6907 Log error if slasher is not up
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
Labels: Ready For Review, Slasher

#6911 RPC/proposer: remove duplicated delete pool attestations
  beacon-chain/rpc/validator/proposer.go
Labels: Enhancement, Ready For Review

#6913 Allow for Different Language Mnemonic Recovery
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/wallet_recover.go
Labels: AccountsV2, Enhancement, Ready For Review

#6912 Check before saving attestation to pool
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/prune_expired.go
Labels: Enhancement, OK to merge, Ready For Review

#6914 Fix Pubkey Not Specified Issues in External Keystore Imports
  tools/keystores/main.go
  validator/keymanager/v2/direct/import.go
Labels: AccountsV2, OK to merge, Ready For Review

#6915 Fail Immediately if Importing Accounts from Empty Directory
  validator/accounts/v2/accounts_import.go
Labels: AccountsV2, OK to merge, Ready For Review

#6917 Update `SignRequest` for key manager
  proto/validator/accounts/v2/BUILD.bazel
  proto/validator/accounts/v2/keymanager.pb.go
  proto/validator/accounts/v2/keymanager.proto
  validator/client/aggregate.go
  validator/client/attest.go
  validator/client/propose.go
  validator/client/service.go
Labels: AccountsV2, Ready For Review

#6918 Sort by Derivation Path in File Name When Importing
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/accounts_import_test.go
  validator/keymanager/v2/derived/derived.go
Labels: AccountsV2, Enhancement, Ready For Review

#6916 Accounts V2: Remove unused passwords-dir and deprecate flag
  validator/accounts/v2/accounts_import_test.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/cmd_wallet.go
  validator/accounts/v2/iface/wallet.go
  validator/accounts/v2/prompt.go
  validator/accounts/v2/testing/mock.go
  validator/accounts/v2/wallet.go
  validator/accounts/v2/wallet_recover_test.go
  validator/accounts/v2/wallet_test.go
  validator/flags/BUILD.bazel
  validator/flags/flags.go
  validator/keymanager/v2/direct/BUILD.bazel
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/migrate.go
  validator/keymanager/v2/direct/migrate_test.go
  validator/main.go
  validator/usage.go
Labels: OK to merge, Ready For Review

#6910 Add New Validator Map Handler
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/getters.go
  beacon-chain/state/setters.go
  beacon-chain/state/state_trie.go
  beacon-chain/state/types.go
  beacon-chain/state/validator_map_test.go
Labels: OK to merge, Ready For Review

#6923 Log Error Logs Less Frequently
  beacon-chain/powchain/service.go
Labels: Ready For Review

#6921 Update Prometheus Client
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#6932 go mod tidy
  go.sum
Labels: OK to merge

#6908 Subscriber: use target epoch for hasSeen cache
  beacon-chain/sync/subscriber_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation.go
Labels: Enhancement, OK to merge, Ready For Review

#6934 Standardize File Permissions in Accounts-V2
  go.mod
  go.sum
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/wallet.go
Labels: AccountsV2, OK to merge, Ready For Review

#6937 Unexport protoarray forkchoice types
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/info.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/helpers.go
  beacon-chain/forkchoice/protoarray/no_vote_test.go
  beacon-chain/forkchoice/protoarray/node.go
  beacon-chain/forkchoice/protoarray/nodes.go
  beacon-chain/forkchoice/protoarray/nodes_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/forkchoice/protoarray/vote_test.go
  beacon-chain/rpc/debug/forkchoice.go
  beacon-chain/rpc/debug/forkchoice_test.go
Labels: Cleanup, Ready For Review

#6919 Proposer: aggregated unaggregated attestations for block
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
Labels: Enhancement, Ready For Review

#6938 Applies assertion funcs to beacon-chain/db tests
  beacon-chain/db/filters/BUILD.bazel
  beacon-chain/db/filters/filter_test.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archived_point_test.go
  beacon-chain/db/kv/backup_test.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/check_historical_test_test.go
  beacon-chain/db/kv/checkpoint_test.go
  beacon-chain/db/kv/deposit_contract_test.go
  beacon-chain/db/kv/encoding_test.go
  beacon-chain/db/kv/finalized_block_roots_test.go
  beacon-chain/db/kv/kv_test.go
  beacon-chain/db/kv/migration_archived_index_test.go
  beacon-chain/db/kv/migration_block_slot_index_test.go
  beacon-chain/db/kv/operations_test.go
  beacon-chain/db/kv/slashings_test.go
  beacon-chain/db/kv/state_summary_test.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/db/kv/utils_test.go
Labels: OK to merge, Ready For Review, Test

#6939 Applies assertion funcs to beacon-chain/core/blocks tests
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/blocks/block_regression_test.go
  beacon-chain/core/blocks/deposit_test.go
  beacon-chain/core/blocks/eth1_data_test.go
  beacon-chain/core/blocks/exit_test.go
  beacon-chain/core/blocks/genesis_test.go
  beacon-chain/core/blocks/header_test.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/core/blocks/randao_test.go
  beacon-chain/core/blocks/spectest/BUILD.bazel
  beacon-chain/core/blocks/spectest/attestation_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_test.go
  beacon-chain/core/blocks/spectest/block_header_test.go
  beacon-chain/core/blocks/spectest/block_processing_test.go
  beacon-chain/core/blocks/spectest/deposit_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_test.go
Labels: OK to merge, Ready For Review, Test

#6944 Revert "Subscriber: use target epoch for hasSeen cache"
  beacon-chain/sync/subscriber_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation.go
Labels: OK to merge, Ready For Review

#6930 Make Initial Sync Failures Debug
  beacon-chain/sync/initial-sync/round_robin.go
Labels: OK to merge, Ready For Review

#6928 Peer scorer: weighted sorting, requests capping, stale peers handling.
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/score_block_providers.go
  beacon-chain/p2p/peers/score_block_providers_test.go
  beacon-chain/p2p/peers/scorer_manager_test.go
  beacon-chain/p2p/peers/store.go
Labels: OK to merge, Ready For Review

#6922 Invert State Locks Flag
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#6940 Applies assertion funcs to beacon-chain/core/* tests
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing_fuzz_test.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
  beacon-chain/core/epoch/precompute/new_test.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/epoch/precompute/slashing_test.go
  beacon-chain/core/epoch/precompute/spectest/BUILD.bazel
  beacon-chain/core/epoch/precompute/spectest/rewards_penalties_test.go
  beacon-chain/core/epoch/spectest/BUILD.bazel
  beacon-chain/core/epoch/spectest/final_updates_test.go
  beacon-chain/core/epoch/spectest/justification_and_finalization_test.go
  beacon-chain/core/epoch/spectest/registry_test.go
  beacon-chain/core/epoch/spectest/rewards_and_penalties_test.go
  beacon-chain/core/epoch/spectest/slashings_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/helpers/block_test.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  beacon-chain/core/helpers/shuffle_test.go
  beacon-chain/core/helpers/signing_root_test.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/core/helpers/spectest/BUILD.bazel
  beacon-chain/core/helpers/spectest/shuffle_yaml_test.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/benchmarks_test.go
  beacon-chain/core/state/skip_slot_cache_test.go
  beacon-chain/core/state/spectest/BUILD.bazel
  beacon-chain/core/state/spectest/slot_processing_test.go
  beacon-chain/core/state/state_test.go
  beacon-chain/core/state/stateutils/BUILD.bazel
  beacon-chain/core/state/stateutils/validator_index_map_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator_test.go
Labels: OK to merge, Ready For Review, Test

#6949 Simplify `make` call by omitting redundant arguments
  beacon-chain/core/helpers/shuffle.go
  beacon-chain/core/helpers/shuffle_test.go
  beacon-chain/core/helpers/spectest/shuffle_yaml_test.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/state/stateutil/arrays.go
  shared/htrutils/hashers.go
  shared/htrutils/merkleize.go
  shared/trieutil/sparse_merkle.go
  slasher/detection/attestations/mock_spanner.go
Labels: OK to merge

#6893 Wait for subnet peers before broadcasting onto attestation subnet topic
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/monitoring.go
  beacon-chain/p2p/pubsub.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/subscriber.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#6951 Fix multiple anti-patterns from DeepSource analysis
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/blocks/deposit.go
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/db/kv/backup.go
  beacon-chain/gateway/gateway.go
  beacon-chain/node/node.go
  beacon-chain/operations/attestations/prune_expired.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/state/stateutil/arrays.go
  beacon-chain/sync/error.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/fsm.go
  beacon-chain/sync/initial-sync/fsm_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/service.go
  shared/bls/herumi/public_key_test.go
  shared/bls/herumi/secret_key_test.go
  shared/bls/herumi/signature_test.go
  shared/bytesutil/bytes.go
  shared/cmd/helpers.go
  shared/cmd/wrap_flags.go
  shared/grpcutils/grpcutils.go
  shared/slotutil/slotticker_test.go
  shared/slotutil/testing/mock.go
  slasher/beaconclient/receivers.go
  slasher/main.go
  tools/forkchecker/forkchecker.go
  tools/pcli/main.go
  validator/client/metrics.go
  validator/client/service.go
  validator/db/kv/proposal_history.go
Labels: OK to merge, Ready For Review

#6920 Change Log Level of Genesis Time Info Log in RPC
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/validator_test.go
Labels: OK to merge, Ready For Review

#6952 Wallet file lock
  deps.bzl
  go.mod
  go.sum
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/wallet.go
  validator/accounts/v2/wallet_test.go
  validator/node/node.go
Labels: Ready For Review

#6953 Resolve Accounts-v2 Feedback
  validator/accounts/v2/accounts_create.go
  validator/accounts/v2/accounts_list.go
  validator/accounts/v2/wallet_create.go
Labels: AccountsV2, OK to merge, Ready For Review

#6933 Refactor Wallet Password Handling, Preventing Wallet Corruption
  shared/cmd/BUILD.bazel
  shared/cmd/customflags.go
  shared/cmd/defaults.go
  shared/fileutil/BUILD.bazel
  shared/fileutil/fileutil.go
  shared/fileutil/fileutil_test.go
  tools/keystores/BUILD.bazel
  tools/keystores/main.go
  validator/accounts/v1/BUILD.bazel
  validator/accounts/v1/account.go
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_create.go
  validator/accounts/v2/accounts_create_test.go
  validator/accounts/v2/accounts_export.go
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/accounts_import_test.go
  validator/accounts/v2/accounts_list.go
  validator/accounts/v2/accounts_list_test.go
  validator/accounts/v2/consts_test.go
  validator/accounts/v2/iface/wallet.go
  validator/accounts/v2/prompt.go
  validator/accounts/v2/testing/mock.go
  validator/accounts/v2/wallet.go
  validator/accounts/v2/wallet_create.go
  validator/accounts/v2/wallet_recover.go
  validator/accounts/v2/wallet_recover_test.go
  validator/accounts/v2/wallet_test.go
  validator/flags/BUILD.bazel
  validator/flags/flags.go
  validator/keymanager/v2/derived/BUILD.bazel
  validator/keymanager/v2/derived/derived.go
  validator/keymanager/v2/derived/derived_test.go
  validator/keymanager/v2/direct/BUILD.bazel
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/direct_test.go
  validator/keymanager/v2/direct/import_test.go
  validator/keymanager/v2/remote/BUILD.bazel
  validator/keymanager/v2/remote/remote.go
  validator/keymanager/v2/remote/remote_test.go
  validator/node/node.go
Labels: AccountsV2, OK to merge, Priority: Critical, Ready For Review

#6954 Proposer: log graffiti
  validator/client/propose.go
Labels: OK to merge, Ready For Review

#6955 Accounts V2: Log and UX cleanup
  shared/promptutil/prompt.go
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/wallet.go
  validator/keymanager/v2/direct/direct.go
Labels: AccountsV2, OK to merge, Ready For Review

#6956 Fix loading historical blocks to replay cold state
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: Bug, OK to merge, Ready For Review

#6941 Accounts-V2: Add command to delete accounts
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_delete.go
  validator/accounts/v2/accounts_export.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/prompt.go
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/direct_test.go
Labels: AccountsV2, OK to merge, Ready For Review

#6958 Support Domains For Discovery
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
Labels: Ready For Review

#6959 Remove Checked In Metadata File
  beacon-chain/p2p/metaData
Labels: OK to merge

#6961 Fix antipatterns
  beacon-chain/p2p/service.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  tools/forkchecker/forkchecker.go
Labels: OK to merge, Ready For Review

#6960 Move to opt-out attestation-aggregation-strategy flag
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#6962 Refactors blocks fetcher: repackage methods
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
Labels: OK to merge, Ready For Review

#6929 Allow Importing One-Off, Private Keys Into Accounts-v2
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/accounts_import_test.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/wallet_test.go
  validator/flags/flags.go
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/import.go
  validator/keymanager/v2/direct/import_test.go
Labels: AccountsV2, Enhancement, OK to merge, Ready For Review

#6966 Add and use genesis time in config
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/sync/initial-sync/service.go
  shared/params/config.go
  shared/params/testnet_medalla_config.go
Labels: Enhancement, Ready For Review

#6964 First attempt of account related web api protos
  proto/validator/accounts/v2/BUILD.bazel
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
Labels: OK to merge, Ready For Review

#6965 Health related web api protos
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
Labels: OK to merge, Ready For Review

#6936 Implement Accounts-V2 Backup for Direct Keymanager
  shared/promptutil/BUILD.bazel
  shared/promptutil/prompt.go
  shared/promptutil/validate.go
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_backup.go
  validator/accounts/v2/accounts_backup_test.go
  validator/accounts/v2/accounts_create.go
  validator/accounts/v2/accounts_delete.go
  validator/accounts/v2/accounts_export.go
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/accounts_import_test.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/prompt.go
  validator/accounts/v2/wallet.go
  validator/accounts/v2/wallet_create_test.go
  validator/accounts/v2/wallet_test.go
  validator/flags/flags.go
  validator/keymanager/v2/direct/BUILD.bazel
  validator/keymanager/v2/direct/backup.go
  validator/keymanager/v2/direct/backup_test.go
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/doc.go
  validator/keymanager/v2/remote/doc.go
Labels: AccountsV2, OK to merge, Ready For Review

#6967 Validator web RPC skeleton
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  validator/rpc/BUILD.bazel
  validator/rpc/server.go
Labels: OK to merge, Ready For Review

#6970 Go syntax-repr in test assertions
  shared/testutil/assert/assertions_test.go
  shared/testutil/assertions/assertions.go
  shared/testutil/require/requires_test.go
Labels: OK to merge, Ready For Review

#6974 DB: add block roots test
  beacon-chain/db/kv/blocks_test.go
Labels: Ready For Review

#6975 `ListBalances` for validator RPC
  proto/beacon/p2p/v1/types.pb.go
  proto/validator/accounts/v2/web_api.pb.go
  validator/client/BUILD.bazel
  validator/client/fake_validator_test.go
  validator/client/metrics.go
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/health.go
  validator/rpc/health_test.go
  validator/rpc/server.go
Labels: Ready For Review

#6979 Injects peer.ID into requested/queued/fetched batches in init-sync
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/fsm.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: OK to merge, Ready For Review

#6981 Peer scorer: fix weighted sorting
  beacon-chain/p2p/peers/score_block_providers.go
  beacon-chain/p2p/peers/score_block_providers_test.go
  beacon-chain/p2p/peers/scorer_manager_test.go
Labels: OK to merge, Ready For Review

#6984 Merges assert and require tests into a single suite
  shared/testutil/assert/BUILD.bazel
  shared/testutil/assertions/BUILD.bazel
  shared/testutil/assertions/assertions_test.go
  shared/testutil/require/BUILD.bazel
  shared/testutil/require/requires_test.go
Labels: OK to merge, Ready For Review

#6986 Fix Validator Exits
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/blocks/exit_test.go
Labels: OK to merge, Ready For Review

#6982 Accounts-V2: Add test for DeleteAccounts
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_delete.go
  validator/accounts/v2/accounts_delete_test.go
  validator/accounts/v2/wallet_test.go
  validator/keymanager/v2/direct/direct.go
Labels: OK to merge, Ready For Review

#6987 `ListStatuses` for validator RPC
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/rpc/BUILD.bazel
  validator/rpc/health.go
  validator/rpc/health_test.go
Labels: OK to merge, Ready For Review

#6985 Moves AssertLogsContains to assertions package
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/utils_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service_test.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/state/stategen/hot_test.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/setter_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  shared/messagehandler/BUILD.bazel
  shared/messagehandler/messagehandler_test.go
  shared/slotutil/BUILD.bazel
  shared/slotutil/countdown_test.go
  shared/testutil/BUILD.bazel
  shared/testutil/assert/BUILD.bazel
  shared/testutil/assert/assertions.go
  shared/testutil/assertions/BUILD.bazel
  shared/testutil/assertions/assertions.go
  shared/testutil/assertions/assertions_test.go
  shared/testutil/log.go
  shared/testutil/require/BUILD.bazel
  shared/testutil/require/requires.go
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/chain_data_test.go
  slasher/beaconclient/historical_data_retrieval_test.go
  slasher/beaconclient/submit_test.go
  slasher/beaconclient/validator_retrieval_test.go
  slasher/detection/BUILD.bazel
  slasher/detection/listeners_test.go
  slasher/node/BUILD.bazel
  slasher/node/node_test.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/service_test.go
  validator/accounts/v2/wallet_create_test.go
  validator/client/aggregate_test.go
  validator/client/attest_test.go
  validator/client/metrics_test.go
  validator/client/propose_test.go
  validator/client/runner_test.go
  validator/client/service_test.go
  validator/client/validator_test.go
  validator/keymanager/v2/derived/BUILD.bazel
  validator/keymanager/v2/derived/derived_test.go
  validator/keymanager/v2/direct/direct_test.go
Labels: OK to merge, Ready For Review

#6983 Add in Attestation Validity Check
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/signature.go
Labels: OK to merge, Priority: Critical, Ready For Review

#6709 Peer scoring: init sync
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/peers_test.go
  beacon-chain/p2p/peers/score_block_providers.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#6968 Add Authentication Functions to Validator RPC
  go.mod
  go.sum
  proto/beacon/p2p/v1/types.pb.go
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/db/kv/schema.go
  validator/db/kv/web_api.go
  validator/db/kv/web_api_test.go
  validator/rpc/BUILD.bazel
  validator/rpc/auth.go
  validator/rpc/auth_test.go
  validator/rpc/health_test.go
  validator/rpc/intercepter.go
  validator/rpc/intercepter_test.go
  validator/rpc/server.go
  validator/rpc/server_test.go
Labels: API, AccountsV2, OK to merge, Ready For Review

#6993 Add and utilize seen atts map
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/kv.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/pool.go
  beacon-chain/rpc/validator/proposer_test.go
Labels: Enhancement, Ready For Review

#6994 Integrate Validator RPC Server Into Runtime + Add Gateway
  endtoend/components/validator.go
  endtoend/params/params.go
  proto/beacon/p2p/v1/types.pb.go
  proto/validator/accounts/v2/BUILD.bazel
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2_gateway/BUILD.bazel
  proto/validator/accounts/v2_gateway/keymanager.pb.go
  proto/validator/accounts/v2_gateway/keymanager.pb.gw.go
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/client/BUILD.bazel
  validator/client/service.go
  validator/flags/flags.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/gateway/BUILD.bazel
  validator/rpc/gateway/gateway.go
  validator/rpc/health_test.go
  validator/rpc/intercepter.go
  validator/usage.go
Labels: API, Ready For Review

#6997 Uncomments tests in kv/unaggregated_test
  beacon-chain/operations/attestations/kv/unaggregated_test.go
Labels: OK to merge, Ready For Review

#6999 Register health APIs handler
  validator/rpc/gateway/gateway.go
  validator/rpc/server.go
Labels: OK to merge, Ready For Review

#7001 Fix Validator RPC JWT Response
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  validator/rpc/BUILD.bazel
  validator/rpc/auth.go
  validator/rpc/intercepter.go
Labels: API, OK to merge, Ready For Review

#6898 added flag to enable roughtime syncing, with it disabled by default
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/roughtime/BUILD.bazel
  shared/roughtime/roughtime.go
Labels: Ready For Review

#7004 Initialize Config Correctly
  shared/featureconfig/config.go
Labels: OK to merge, Priority: Critical, Ready For Review

#7006 Fix 2nd Stage of Sync
  beacon-chain/blockchain/receive_block.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: OK to merge, Priority: Critical, Ready For Review

#7007 Featureflag test: reset init
  shared/featureconfig/config_test.go
Labels: OK to merge, Ready For Review

#7008 Core: optimize `InitiateValidatorExit` and `ProcessAttesterSlashings`
  beacon-chain/core/blocks/attester_slashing.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/validators/validator.go
Labels: Enhancement, Ready For Review

#7010 Use LRU for checkpoint state cache
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/checkpoint_state.go
  beacon-chain/cache/checkpoint_state_test.go
Labels: Enhancement, Ready For Review

#7012 Use Stage 1 For Non Finalized Sync
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: OK to merge, Priority: Critical

#7016 Sync: Dont ban block roots for context.DeadlineExceeded
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/subscriber_beacon_blocks.go
Labels: OK to merge, Ready For Review

#7019 Sync: fix panic and check blocks + roots lengths
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/utils.go
  beacon-chain/sync/utils_test.go
Labels: Bug, Priority: Critical, Ready For Review

#7017 Revert "Sync: Dont ban block roots for context.DeadlineExceeded"
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/subscriber_beacon_blocks.go
Labels: OK to merge

#7020 Ignore subscription cancelled warning
  beacon-chain/sync/subscriber.go
Labels: OK to merge, Ready For Review

#7018 Update committee cache size to 32
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_test.go
Labels: Enhancement, OK to merge, Priority: Critical, Ready For Review

#7028 Do Not Retrieve From DB For Block Roots
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
Labels: OK to merge, Ready For Review

#7032 Wait interval, before finalized peers re-checked
  beacon-chain/sync/initial-sync/blocks_queue.go
Labels: OK to merge, Ready For Review

#7037 Only cache check point state if it hasn't existed in other cache
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/state/stategen/hot.go
Labels: Enhancement, Ready For Review

#7036 Pending queue to handle same slot blocks
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: OK to merge, Priority: Critical, Ready For Review

#7040 Don't ban blocks for context deadlines
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: OK to merge, Ready For Review

#7039 Updates resyncIfBehind() functionality
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/rpc_status.go
Labels: OK to merge, Ready For Review

#7041 Validator recheck slasher client status
  validator/client/validator.go
  validator/slashing-protection/slasher_client.go
Labels: OK to merge

#7044 Reject Duplicate Blocks From Being Saved
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/validate_beacon_attestation.go
Labels: Priority: High, Ready For Review

#7043 Slasher span cache size flag
  slasher/flags/flags.go
  slasher/main.go
  slasher/node/node.go
  slasher/usage.go
Labels: OK to merge, Ready For Review

#7045 Use map to reject seen pending block
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Enhancement, Ready For Review

#7052 Default To Mainnet Config When Parsing Chain Config
  shared/params/loader.go
  shared/params/loader_test.go
Labels: OK to merge, Ready For Review

#7038 Accounts-V2: Change ListDirs() to Exists(), fix bug for derived
  validator/accounts/v2/iface/wallet.go
  validator/accounts/v2/testing/mock.go
  validator/accounts/v2/wallet.go
  validator/keymanager/v2/derived/derived.go
  validator/keymanager/v2/direct/direct.go
Labels: AccountsV2, OK to merge, Ready For Review

#7053 Use correct context for IsFinalizedBlock call
  beacon-chain/sync/rpc_status.go
Labels: OK to merge, Ready For Review

#7055 Save finalized checkpoint before migrate to cold
  beacon-chain/blockchain/process_block_helpers.go
Labels: OK to merge, Ready For Review

#7059 Shift Sync Warn and Error Messages To Debug
  beacon-chain/p2p/service.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/rpc.go
Labels: Ready For Review

#7027 Batch Block Roots Requesting
  beacon-chain/p2p/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/utils.go
Labels: OK to merge, Ready For Review

#7061 Slasher improvements
  slasher/beaconclient/receivers.go
  slasher/db/kv/spanner_new.go
  slasher/flags/flags.go
  slasher/rpc/server.go
Labels: Ready For Review

#7060 Add replay block count metric
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/hot.go
Labels: Enhancement, Ready For Review

#7063 Use hot state cache for replay
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/hot_test.go
Labels: Enhancement, Ready For Review

#7046 Voluntary exit CLI command
  shared/promptutil/prompt.go
  tools/keystores/main.go
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_delete.go
  validator/accounts/v2/accounts_exit.go
  validator/accounts/v2/accounts_exit_test.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/prompt.go
  validator/accounts/v2/wallet_recover.go
  validator/accounts/v2/wallet_test.go
  validator/flags/flags.go
  validator/keymanager/v2/derived/mnemonic.go
Labels: Ready For Review

#7064 Add "slotInEpoch" to log
  beacon-chain/blockchain/log.go
Labels: Enhancement, Ready For Review

#7065 Account commands cleanup
  shared/promptutil/prompt.go
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_backup.go
  validator/accounts/v2/accounts_create.go
  validator/accounts/v2/accounts_delete.go
  validator/accounts/v2/accounts_delete_test.go
  validator/accounts/v2/accounts_exit.go
  validator/accounts/v2/accounts_helper.go
  validator/accounts/v2/wallet_test.go
  validator/flags/flags.go
Labels: OK to merge, Ready For Review

#6995 Tidying up a few core functions
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/blocks/exit_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/rpc/validator/exit.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_voluntary_exit.go
  fuzz/attestation_fuzz.go
  fuzz/voluntary_exit_fuzz.go
Labels: Cleanup, OK to merge, Ready For Review

#6829 Add prysm.sh1 for native Windows support via PowerShell
  prysm.ps1
Labels: OK to merge, Ready For Review

#7069 Fix identical expressions
  beacon-chain/core/epoch/precompute/spectest/rewards_penalties_test.go
  beacon-chain/state/stategen/replay_test.go
Labels: OK to merge, Ready For Review, Test

#7092 Adds DeepNotEqual assertion
  shared/testutil/assert/assertions.go
  shared/testutil/assertions/assertions.go
  shared/testutil/assertions/assertions_test.go
  shared/testutil/require/requires.go
Labels: OK to merge, Ready For Review, Test

#7087 Fixes errNoPeersWithFinalizedBlocks naming
  beacon-chain/sync/initial-sync/blocks_queue.go
Labels: OK to merge, Ready For Review, Sync

#7086 More conservative selection of non-finalized peers
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/rpc_status.go
Labels: OK to merge, Ready For Review, Sync

#7097 Handle Nil Signature in Pending Queue
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
Labels: Ready For Review

#7096 Optimizes error message parsing in testutils
  shared/testutil/assertions/assertions.go
Labels: OK to merge, Ready For Review, Test

#7080 Create Validator Accounts V2 Send Deposit
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_deposit.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/prompt.go
  validator/flags/flags.go
  validator/keymanager/v2/derived/BUILD.bazel
  validator/keymanager/v2/derived/deposit.go
  validator/keymanager/v2/derived/deposit_test.go
Labels: AccountsV2, Enhancement, OK to merge, Ready For Review

#7098 Use checkpoint info cache
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/testing/BUILD.bazel
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/cache/hot_state_cache.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Enhancement, Ready For Review

#7081 Add Shared Field Metrics
  beacon-chain/blockchain/metrics.go
  beacon-chain/state/state_trie.go
  beacon-chain/state/types.go
Labels: OK to merge, Ready For Review

#7103 Make Interop keys functional for accounts-v2
  shared/featureconfig/flags.go
  validator/keymanager/v2/direct/BUILD.bazel
  validator/keymanager/v2/direct/direct.go
  validator/node/BUILD.bazel
  validator/node/node.go
Labels: OK to merge

#7106 Fix Interop Mode
  beacon-chain/node/node.go
Labels: Ready For Review

#6666 First take of applying assertion funcs to shared tests
  beacon-chain/core/blocks/spectest/block_header_test.go
  shared/BUILD.bazel
  shared/bls/herumi/signature_test.go
  shared/bls/spectest/BUILD.bazel
  shared/bls/spectest/aggregate_test.go
  shared/bls/spectest/aggregate_verify_test.go
  shared/bls/spectest/fast_aggregate_verify_test.go
  shared/bls/spectest/sign_test.go
  shared/bls/spectest/verify_test.go
  shared/bytesutil/bytes_test.go
  shared/depositutil/deposit_test.go
  shared/event/BUILD.bazel
  shared/event/subscription_test.go
  shared/fileutil/fileutil_test.go
  shared/keystore/BUILD.bazel
  shared/keystore/key_test.go
  shared/keystore/keystore_test.go
  shared/mathutil/BUILD.bazel
  shared/mathutil/math_helper_test.go
  shared/mputil/BUILD.bazel
  shared/mputil/benchmark_test.go
  shared/mputil/scatter_test.go
  shared/pagination/BUILD.bazel
  shared/pagination/pagination_test.go
  shared/params/BUILD.bazel
  shared/params/loader_test.go
  shared/params/spectest/BUILD.bazel
  shared/params/spectest/config_test.go
  shared/prometheus/BUILD.bazel
  shared/prometheus/logrus_collector_test.go
  shared/prometheus/service_test.go
  shared/service_registry_test.go
  shared/testutil/BUILD.bazel
  shared/testutil/block_test.go
  shared/testutil/deposits_test.go
  shared/testutil/helpers_test.go
  shared/testutil/spectest.go
  shared/testutil/state_test.go
  shared/trieutil/BUILD.bazel
  shared/trieutil/sparse_merkle_test.go
Labels: OK to merge, Ready For Review

#7093 Unset From,Sequence Number and Signature For Pubsub Messages
  beacon-chain/p2p/service.go
Labels: OK to merge, Ready For Review

#6818 Modify majority vote rules
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#7107 Updates bazel-toolchains 3.1.1 -> 3.2.0
  WORKSPACE
Labels: OK to merge, Ready For Review

#7104 Accounts-V2: Fix wallet-v2 recover and wallet-v2 create for derived
  validator/accounts/v2/wallet_create.go
  validator/accounts/v2/wallet_recover.go
  validator/keymanager/v2/derived/derived.go
Labels: AccountsV2, OK to merge, Ready For Review
