Repository OffchainLabs/prysm, pull requests merged in 2020-04, with the labels that each got.

#5273 Avoid div by zero in extreme balance case
  WORKSPACE
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/rewards_penalties_test.go
Labels: Ready For Review, spec-v0.11

#5274 Verify block proposer index before gossip
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review, spec-v0.11

#5269 Add in Proposer Index to Custom HTR
  beacon-chain/state/stateutil/blocks.go
  beacon-chain/state/stateutil/blocks_test.go
Labels: Ready For Review

#5278 Enable slashing protection in validator by default
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/client/validator_propose.go
Labels: OK to merge, Ready For Review

#5285 Resolve Flakey P2P Tests
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
Labels: Ready For Review

#5280 Release Skip Slot Cache to All
  beacon-chain/cache/skip_slot_cache.go
  beacon-chain/cache/skip_slot_cache_test.go
  beacon-chain/core/blocks/spectest/block_processing_test.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/skip_slot_cache.go
  beacon-chain/core/state/skip_slot_cache_test.go
  beacon-chain/core/state/spectest/slot_processing_test.go
  beacon-chain/core/state/state_fuzz_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_fuzz_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/sync/initial-sync-old/BUILD.bazel
  beacon-chain/sync/initial-sync-old/round_robin.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/rpc_test.go
  endtoend/BUILD.bazel
  endtoend/endtoend_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#5287 Release Resources Correctly in P2P Tests
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets_test.go
Labels: Ready For Review

#5220 slasher retrieve and cache validator public key
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/service.go
  slasher/beaconclient/validator_retrieval.go
  slasher/beaconclient/validator_retrieval_test.go
  slasher/cache/BUILD.bazel
  slasher/cache/validators_cache.go
  slasher/node/BUILD.bazel
  slasher/node/node.go
Labels: Ready For Review

#5272 Enable NOISE Handshake by Default v0.11
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#5284 Init sync optimizations
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/fsm.go
  beacon-chain/sync/initial-sync/fsm_test.go
Labels: In Progress

#5289 Make `new-state-mgmt` canonical
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/check_historical_state.go
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/checkpoint_test.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/state/stategen/service.go
  beacon-chain/sync/initial-sync/fsm_test.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review, spec-v0.11

#5286 Init sync release queue
  beacon-chain/node/node.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#5293 Invert init-sync-batch-save-blocks flag for v0.11
  beacon-chain/blockchain/init_sync_process_block.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/sync/initial-sync-old/round_robin.go
  beacon-chain/sync/initial-sync-old/round_robin_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review, Testnet

#5294 Clear init sync blocks on the correct line
  beacon-chain/blockchain/init_sync_process_block.go
Labels: OK to merge, Ready For Review

#5139 Detect Proposer Slashing Implementation
  slasher/db/iface/interface.go
  slasher/db/kv/block_header.go
  slasher/db/kv/block_header_test.go
  slasher/detection/BUILD.bazel
  slasher/detection/detect.go
  slasher/detection/detect_test.go
  slasher/detection/listeners.go
  slasher/detection/listeners_test.go
  slasher/detection/proposals/BUILD.bazel
  slasher/detection/proposals/detector.go
  slasher/detection/proposals/detector_test.go
  slasher/detection/service.go
  slasher/detection/testing/BUILD.bazel
  slasher/detection/testing/utils.go
Labels: Ready For Review

#5295 Set a max limit for decoding ssz objects from p2p
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/encoder/ssz_test.go
Labels: Fuzz, OK to merge, Ready For Review

#5296 Add maligned struct static check
  BUILD.bazel
  beacon-chain/flags/config.go
  beacon-chain/p2p/config.go
  beacon-chain/powchain/service.go
  beacon-chain/sync/initial-sync/fsm_test.go
  contracts/deposit-contract/testutils.go
  nogo_config.json
  shared/featureconfig/config.go
  tools/analyzers/maligned/BUILD.bazel
  tools/analyzers/maligned/analyzer.go
  tools/analyzers/maligned/maligned.go
  validator/client/fake_validator_test.go
Labels: OK to merge, Ready For Review

#5271 Add Metadata And Ping RPC methods
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/rpc_topic_mappings.go
  beacon-chain/p2p/sender.go
  beacon-chain/p2p/sender_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/p2p/utils.go
  beacon-chain/state/stateutil/blocks_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync-old/round_robin.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_metadata_test.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_ping_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/usage.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  proto/beacon/p2p/v1/types.pb.go
  shared/cmd/flags.go
  shared/featureconfig/flags.go
Labels: Networking, Ready For Review, spec-v0.11

#5292 Update proposer protection to v0.11
  proto/slashing/slashing.pb.go
  proto/slashing/slashing.proto
  validator/client/validator_propose.go
  validator/client/validator_propose_test.go
  validator/db/BUILD.bazel
  validator/db/db.go
  validator/db/iface/BUILD.bazel
  validator/db/iface/interface.go
  validator/db/proposal_history.go
  validator/db/proposal_history_test.go
Labels: Ready For Review

#5301 Update @terencechain public key.
  .well-known/security.txt
Labels: OK to merge, Ready For Review

#5298 Init sync update highest slot
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
Labels: Ready For Review

#5299 Implement `SubscribeCommitteeSubnet` method
  WORKSPACE
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/committee_ids.go
  beacon-chain/cache/committee_ids_test.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
  validator/client/validator.go
  validator/client/validator_test.go
  validator/internal/beacon_node_validator_service_mock.go
Labels: Blocked, Testnet, spec-v0.11

#5309 Save cached blocks to db during phase 2 of initial sync
  beacon-chain/blockchain/process_block.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
Labels: Bug, Priority: Critical

#5313 fix broken links in readme
  README.md
Labels: OK to merge

#5304 Remove unused validator protos
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/server.go
  proto/beacon/rpc/v1/BUILD.bazel
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/BUILD.bazel
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/beacon/rpc/v1_gateway/slasher.pb.go
  validator/client/BUILD.bazel
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review

#5312 Validator subscribe subnet to next epoch
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review, spec-v0.11

#5302 Aggregate on demand for v0.11
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/aggregate.go
  beacon-chain/operations/attestations/aggregate_test.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/pool.go
  beacon-chain/operations/attestations/service.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/aggregator.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/attester_test.go
  endtoend/minimal_antiflake_e2e_1_test.go
  endtoend/minimal_antiflake_e2e_2_test.go
  validator/client/validator_attest.go
Labels: Ready For Review, spec-v0.11

#5318 Refactor Dynamic Subscriptions
  beacon-chain/sync/metrics.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation.go
Labels: Networking, Ready For Review, spec-v0.11

#5320 Interop batch save validator indices
  beacon-chain/interop-cold-start/service.go
Labels: Ready For Review

#5321 Fix listindexed attestations and detect historic attestations
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  slasher/detection/service.go
Labels: Ready For Review

#5325 Add buildbuddy BES
  .buildkite-bazelrc
Labels: OK to merge, Ready For Review

#5324 V0.11 run time fixes to use interop config
  beacon-chain/blockchain/service.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/node/node.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: OK to merge, Priority: High, Ready For Review

#5328 Use less goroutines in validator runner
  validator/client/runner.go
Labels: OK to merge, Ready For Review

#5329 Remove old cross compile starlark rules
  BUILD.bazel
  beacon-chain/BUILD.bazel
  tools/go_image.bzl
  validator/BUILD.bazel
Labels: OK to merge, Ready For Review

#5330 Create CODEOWNERS
  .github/CODEOWNERS
Labels: OK to merge, Ready For Review

#5331 Nil Checks in Process Attestation v0.11
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_helpers.go
Labels: Bug, Ready For Review

#5332 Validator batch subscribe subnets
  WORKSPACE
  beacon-chain/rpc/validator/attester.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
  validator/client/validator.go
  validator/client/validator_test.go
  validator/internal/beacon_node_validator_service_mock.go
Labels: Ready For Review, spec-v0.11

#5334 Validator smarter subscribe
  shared/bytesutil/bytes.go
  validator/client/validator.go
Labels: Ready For Review, spec-v0.11

#5336 Fix incorrect proposer index calculation
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review

#5319 Update P2P Service to Handle Local Metadata
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/mock_peersprovider.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync-old/BUILD.bazel
  beacon-chain/sync/initial-sync-old/round_robin_test.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_ping_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
Labels: Networking, Ready For Review

#5303 Wait for Genesis Event to Start P2P
  beacon-chain/node/node.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/config.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets_test.go
Labels: Ready For Review

#5342 Use param config `SlotsPerArchivedPoint`
  beacon-chain/state/stategen/service.go
Labels: Ready For Review

#5346 Avoid duplicated aggregation request
  validator/client/BUILD.bazel
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_aggregate.go
  validator/client/validator_propose_test.go
Labels: spec-v0.11

#5348 Fix Validate For Metadata
  beacon-chain/sync/rpc_ping.go
Labels: Ready For Review

#5344 Multiple Proposer Slots Allowed Per Epoch for Validators
  WORKSPACE
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/validator/assignments.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Priority: High, Ready For Review

#5300 Validator client improvements
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/rpc/validator/status_test.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#5349 Networking Fixes
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/sender.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation.go
Labels: Ready For Review

#5354 More efficient aggregation on demand
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/pool.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/rpc/validator/aggregator.go
Labels: Ready For Review, spec-v0.11

#5357 Release DiscoveryV5 for Testnet Restart
  beacon-chain/flags/base.go
  beacon-chain/flags/config.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/service.go
  beacon-chain/usage.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#5361 Fix Overflow in Status Check
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
Labels: Ready For Review

#5347 Add cache to Eth1 RPC functions
  beacon-chain/powchain/block_reader.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/rpc/validator/proposer.go
Labels: Ready For Review

#5363 Update bazel to 3.0.0
  .bazelversion
Labels: OK to merge

#5368 Update README
  README.md
Labels: Enhancement, Ready For Review

#5370 Add roughtime static code analysis and fix all violations
  BUILD.bazel
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/p2p/connmgr/BUILD.bazel
  beacon-chain/p2p/connmgr/connmgr.go
  beacon-chain/p2p/connmgr/connmgr_test.go
  beacon-chain/powchain/service.go
  beacon-chain/sync/initial-sync-old/round_robin.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/fsm.go
  nogo_config.json
  shared/keystore/BUILD.bazel
  shared/keystore/utils.go
  tools/analyzers/roughtime/BUILD.bazel
  tools/analyzers/roughtime/analyzer.go
Labels: OK to merge, Ready For Review

#5369 Fix incorrect proposer slashing domain calculation
  beacon-chain/core/blocks/block_operations.go
Labels: OK to merge, Ready For Review

#5367 Make Mainnet Config Default, No More Demo Config
  beacon-chain/blockchain/process_attestation_test.go
  endtoend/README.md
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/params/config.go
  tools/blocktree/BUILD.bazel
  tools/blocktree/main.go
  tools/cluster-pk-manager/server/BUILD.bazel
  tools/cluster-pk-manager/server/main.go
  tools/forkchecker/forkchecker.go
  tools/sendDepositTx/sendDeposits.go
  validator/flags/flags.go
  validator/main.go
  validator/usage.go
Labels: Ready For Review

#5351 Use FastSSZ Marshal/Unmarshal for DB Encodings in v0.11.1
  beacon-chain/archiver/BUILD.bazel
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/backup_test.go
  beacon-chain/db/kv/checkpoint_test.go
  beacon-chain/db/kv/encoding.go
  beacon-chain/db/kv/finalized_block_roots_test.go
  beacon-chain/db/kv/slashings_test.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status_test.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/replay_test.go
  beacon-chain/sync/initial-sync-old/BUILD.bazel
  beacon-chain/sync/initial-sync-old/round_robin_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
  shared/testutil/BUILD.bazel
  shared/testutil/block.go
  shared/testutil/state.go
  shared/testutil/state_test.go
Labels: Ready For Review

#5376 Reconnect slasher streams on beacon node shutdown
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/receivers.go
Labels: Ready For Review

#5364 Update state root cache to fuzz in parallel
  WORKSPACE
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/arrays.go
  beacon-chain/state/stateutil/state_root_cache_fuzz_test.go
Labels: Bug, Priority: Critical, Ready For Review

#5379 Update CODEOWNERS
  .github/CODEOWNERS
Labels: OK to merge, Ready For Review

#5382 Add probot no-response configuration
  .github/no-response.yml
Labels: OK to merge, Ready For Review

#5384 Remove next slot requirement for processing attestations
  beacon-chain/blockchain/process_attestation.go
Labels: OK to merge, Ready For Review

#5388 Revert "Validator client improvements"
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/rpc/validator/status_test.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Priority: Critical

#5387 Update Bootnode to v0.11
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
Labels: Ready For Review

#5383 Use state validator index map
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archive.go
  beacon-chain/db/kv/archived_point.go
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/validators.go
  beacon-chain/db/kv/validators_test.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/validator/aggregator.go
  beacon-chain/rpc/validator/aggregator_test.go
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/rpc/validator/status_test.go
  beacon-chain/state/setters.go
  shared/bytesutil/bytes.go
Labels: Ready For Review

#5392 Add log-file flag to bootnode
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
Labels: OK to merge

#5391 State service clean up - better migration
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/archived_point.go
  beacon-chain/db/kv/archived_point_test.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/migrate_test.go
Labels: Ready For Review

#5389 Validator client cleanup
  shared/testutil/block.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#5386 Unskip E2E for V0.11
  endtoend/BUILD.bazel
  endtoend/components/beacon_node.go
  endtoend/components/eth1.go
  endtoend/endtoend_test.go
  endtoend/evaluators/BUILD.bazel
  endtoend/evaluators/slashing.go
  endtoend/helpers/helpers.go
  endtoend/minimal_antiflake_e2e_1_test.go
  endtoend/minimal_antiflake_e2e_2_test.go
  endtoend/minimal_e2e_test.go
  endtoend/minimal_slashing_e2e_test.go
  endtoend/params/params.go
  tools/bootnode/BUILD.bazel
  validator/client/validator_aggregate.go
  validator/client/validator_propose.go
Labels: Ready For Review

#5398 Set ssz cache enabled by default
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5400 Fixed a bug in ActivatedValidatorIndices
  beacon-chain/archiver/service_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Bug, Ready For Review

#5393 State service clean up - better cold state getter
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: Enhancement, Ready For Review

#5407 Pass E2E Tests for v0.11 and Enable Attestation Subnets By Default
  beacon-chain/p2p/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
  endtoend/components/beacon_node.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Priority: High, Ready For Review

#5414 Resolve Misc v0.11 Items (Raul)
  beacon-chain/node/node.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/config.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/sync/subscriber_handlers.go
  third_party/herumi/bls_eth_go_binary_serialization_alloc_fix.patch
  tools/faucet/server.go
Labels: Ready For Review

#5416 Revert keymanager changes
  WORKSPACE
  shared/cmd/flags.go
  validator/BUILD.bazel
  validator/accounts/BUILD.bazel
  validator/accounts/account.go
  validator/accounts/account_test.go
  validator/client/BUILD.bazel
  validator/client/service_test.go
  validator/client/validator_aggregate_test.go
  validator/client/validator_attest_test.go
  validator/client/validator_propose_test.go
  validator/flags/flags.go
  validator/keymanager/BUILD.bazel
  validator/keymanager/direct_keystore.go
  validator/keymanager/remote.go
  validator/keymanager/remote_internal_test.go
  validator/keymanager/wallet.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/node_test.go
  validator/usage.go
Labels: Ready For Review

#5415 Update BLS and limit visibility
  WORKSPACE
  beacon-chain/core/blocks/block_operations_test.go
  shared/bls/bls.go
  third_party/herumi/bls_eth_go_binary.BUILD
  third_party/herumi/herumi.bzl
Labels: Ready For Review

#5431 Update deposit contract default value for topaz
  beacon-chain/flags/base.go
Labels: OK to merge, Priority: Critical, Ready For Review

#5435 Fix Network Encoder
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/encoder/network_encoding.go
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/encoder/ssz_test.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/decode_pubsub.go
  shared/cmd/flags.go
Labels: OK to merge, Priority: Critical, Ready For Review

#5420 nil check for `SignedAggregateAndProof`
  beacon-chain/rpc/validator/aggregator.go
Labels: Ready For Review

#5440 Fix bad log messages for duplicate deposits
  beacon-chain/powchain/log_processing.go
Labels: OK to merge

#5411 Modify `ListBeaconCommittees ` to use new state service
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
Labels: Ready For Review

#5409 Modify `GetValidatorParticipation` to use new state service
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#5442 Fix Panics in P2P Service
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/service.go
Labels: OK to merge, Ready For Review

#5444 Use debug for `Skipping deposit...` log
  beacon-chain/core/blocks/block_operations.go
Labels: OK to merge

#5408 Modify `GetValidatorActiveSetChanges` to use new state service
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge, Ready For Review

#5365 Modify `ListValidatorAssignments` to use new state service
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/service.go
Labels: OK to merge, Ready For Review

#5445 Deprecate archival service
  beacon-chain/archiver/BUILD.bazel
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/flags/BUILD.bazel
  beacon-chain/flags/archive.go
  beacon-chain/flags/config.go
  beacon-chain/main.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/usage.go
Labels: OK to merge, Ready For Review

#5447 updates UpdateRandaoMixesAtIndex signature
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/state/field_trie_test.go
  beacon-chain/state/references_test.go
  beacon-chain/state/setters.go
  beacon-chain/state/types_test.go
Labels: OK to merge, Ready For Review

#5426 Add healthz check to E2E
  endtoend/components/beacon_node.go
  endtoend/evaluators/BUILD.bazel
  endtoend/evaluators/node.go
  endtoend/minimal_antiflake_e2e_1_test.go
  endtoend/minimal_antiflake_e2e_2_test.go
  endtoend/minimal_e2e_test.go
  endtoend/minimal_slashing_e2e_test.go
Labels: OK to merge, Ready For Review

#5457 nil attestation tests added
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_test.go
Labels: OK to merge, Ready For Review

#5458 Fix `ListValidatorBalances` for v0.11
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Bug, OK to merge, Ready For Review

#5455 Added dappnode-release-trigger.yml workflow
  .github/workflows/dappnode-release-trigger.yml
Labels: OK to merge

#5459 Delete archival DB methods
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archive.go
  beacon-chain/db/kv/archive_test.go
  beacon-chain/db/kv/kv.go
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/archive.pb.go
  proto/beacon/p2p/v1/archive.proto
Labels: Ready For Review

#5461 Debug log pubkey chainstart already added
  beacon-chain/powchain/log_processing.go
Labels: OK to merge, Ready For Review

#5453 Update wallet keymanager for v0.11
  WORKSPACE
  third_party/herumi/bls_eth_go_binary.BUILD
  validator/keymanager/BUILD.bazel
  validator/keymanager/wallet.go
Labels: OK to merge

#5454 Add Separate Network Config
  beacon-chain/p2p/encoder/BUILD.bazel
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/fork.go
  beacon-chain/p2p/sender.go
  beacon-chain/p2p/subnets.go
  beacon-chain/sync/deadlines.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/validate_aggregate_proof.go
  shared/params/BUILD.bazel
  shared/params/config.go
  shared/params/network_config.go
Labels: Networking, OK to merge, Ready For Review

#5464 Revert archival deprecations
  beacon-chain/archiver/BUILD.bazel
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archive.go
  beacon-chain/db/kv/archive_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/flags/BUILD.bazel
  beacon-chain/flags/archive.go
  beacon-chain/flags/config.go
  beacon-chain/main.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/service.go
  beacon-chain/usage.go
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/archive.pb.go
  proto/beacon/p2p/v1/archive.proto
Labels: OK to merge, Priority: High

#5466 Replay and generate state using proper parent root
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/hot_test.go
Labels: Bug, OK to merge, Priority: Critical

#5467 Fix overflow in currentSlot
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: Bug, OK to merge, Priority: Critical

#5469 Fix Bootnode
  tools/bootnode/bootnode.go
Labels: OK to merge, Ready For Review

#5471 Add default bootnode for discv5
  shared/cmd/flags.go
Labels: Enhancement, OK to merge, Priority: High, Ready For Review

#5479 Change prysm script to support windows
  prysm.sh
Labels: OK to merge

#5478 Add `HasBlock` to verify parent check
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: OK to merge, Priority: High, Ready For Review

#5475 Retrieve last ancestor state from DB. (Radical improvement from 5466)
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/hot_test.go
Labels: Enhancement, OK to merge, Ready For Review

#5473 Fix Bootnode Again
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
Labels: OK to merge

#5480 Less Scary Connection Logs
  beacon-chain/p2p/service.go
Labels: OK to merge, Ready For Review

#5474 Add Geth Logging
  beacon-chain/BUILD.bazel
  beacon-chain/main.go
Labels: OK to merge, Ready For Review

#5366 Add WaitForSynced to beacon node for validator startup
  beacon-chain/core/feed/state/events.go
  beacon-chain/rpc/testing/beacon_node_validator_service_mock.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/sync/initial-sync/service.go
Labels: OK to merge, Ready For Review

#5498 Disable some block checks without state mgmt
  beacon-chain/sync/validate_beacon_blocks.go
Labels: OK to merge

#5497 Disable Attester/Proposer Slashing Protection
  shared/featureconfig/flags.go
Labels: OK to merge, Priority: Critical, Ready For Review

#5501 Save init sync cached blocks before regenerate state
  beacon-chain/blockchain/init_sync_process_block.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/state/stategen/hot.go
Labels: OK to merge, Priority: Critical, Ready For Review

#5505 Better Bug Report and Issue Templates for Prysm
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Enhancement, OK to merge, Ready For Review

#5499 Configurable pubsub router
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/service.go
  beacon-chain/usage.go
  shared/cmd/flags.go
Labels: OK to merge, Ready For Review

#5500 p2p/sync: Wrong genesis digest is used to register pubsub topic subscriptions (race condition)
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/metrics.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
  shared/p2putils/BUILD.bazel
  shared/p2putils/fork.go
Labels: Bug, OK to merge, Priority: Critical, Ready For Review

#5507 Fix prysm.sh for arm64
  prysm.sh
Labels: OK to merge

#5504 Change prometheus port for different parts of Prysm
  beacon-chain/flags/base.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/usage.go
  shared/cmd/flags.go
  slasher/flags/flags.go
  slasher/main.go
  slasher/node/node.go
  slasher/usage.go
  validator/flags/flags.go
  validator/main.go
  validator/node/node.go
  validator/usage.go
Labels: OK to merge, Ready For Review

#5245 Add Reference Copying
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/slashing.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/cloners.go
  beacon-chain/state/field_trie.go
  beacon-chain/state/getters.go
  beacon-chain/state/references_test.go
  beacon-chain/state/setters.go
  beacon-chain/state/state_trie.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/memorypool/memorypool.go
Labels: OK to merge, Ready For Review

#5441 More efficient list indexed attestation endpoint
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
Labels: Ready For Review

#5517 Add back archival endpoint `ListValidatorAssignments` with fallback
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/service.go
Labels: OK to merge, Ready For Review

#5520 Add back archival endpoint `ValidatorParticipation` with fallback
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge, Ready For Review

#5488 Make Connections Less Aggressive
  beacon-chain/p2p/service.go
Labels: OK to merge

#5528 Update prysm.sh to use prysmaticlabs.com/releases
  prysm.sh
Labels: OK to merge, Ready For Review

#5527 Validator: fix percentages to be per 100
  validator/client/validator_metrics.go
Labels: OK to merge, Ready For Review

#5518 Add back archival endpoint `ListBeaconCommittees` with fallback
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
Labels: OK to merge, Ready For Review

#5529 Cancel Initial Sync Properly
  beacon-chain/sync/initial-sync-old/service.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/service.go
Labels: OK to merge, Ready For Review

#5532 Fix slasher historic attestation detection
  slasher/detection/service.go
Labels: Ready For Review

#5541 Run Gofmt on Repo
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/service_norace_test.go
  beacon-chain/cache/checkpoint_state_test.go
  beacon-chain/cache/committee_ids.go
  beacon-chain/state/references_test.go
  shared/bytesutil/bytes_test.go
  shared/keystore/deposit_input.go
  tools/analyzers/errcheck/embedded_walker_test.go
Labels: OK to merge, Ready For Review

#5539 add --dev flag
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5460 Add Metrics to Bootnode
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
Labels: Enhancement, OK to merge, Ready For Review

#5545 Add Clock-Based Slot to Metrics
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/receive_block.go
Labels: OK to merge, Ready For Review

#5544 Regen and save historical states as default
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/check_historical_state.go
  beacon-chain/db/kv/regen_historical_states.go
  beacon-chain/state/stategen/migrate.go
Labels: OK to merge, Priority: High, Ready For Review

#5535 Update to 1.14.1
  WORKSPACE
Labels: OK to merge

#5547 Log warn instead of return error
  beacon-chain/blockchain/process_block_helpers.go
Labels: OK to merge, Ready For Review

#5516 Optimize GetDuties to not call Eth1 functions
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
Labels: OK to merge

#5465 Use WaitForSynced in validator client for startup
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/internal/beacon_node_validator_service_mock.go
Labels: OK to merge, Ready For Review

#5396 WaitForActivation optimizations
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/rpc/validator/status_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#5519 Add back archival endpoint `GetValidatorActiveSetChanges` with fallback
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#5548 Change ListIndexedAttestations to convert attestations from target root
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
Labels: Ready For Review

#5554 Fix Panic in Discv5
  WORKSPACE
Labels: Ready For Review

#5557 Migration should not fail process block routine
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/replay.go
Labels: OK to merge, Priority: High, Ready For Review

#5534 Slasher batch db read and a write
  slasher/db/iface/interface.go
  slasher/db/kv/spanner.go
  slasher/db/kv/spanner_test.go
Labels: Ready For Review

#5559 fix tests in //beacon-chain/rpc/beacon
  beacon-chain/rpc/beacon/attestations_test.go
  shared/featureconfig/config.go
Labels: OK to merge

#5565 Continue if archival state is not in DB
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
  beacon-chain/state/stategen/migrate.go
Labels: Enhancement, OK to merge, Priority: High, Ready For Review

#5563 Change Validator Status for visible deposit back to DEPOSITED
  beacon-chain/rpc/validator/status.go
  beacon-chain/rpc/validator/status_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge

#5558 /healthz endpoint accepts JSON now
  WORKSPACE
  shared/prometheus/BUILD.bazel
  shared/prometheus/content_negotiation.go
  shared/prometheus/service.go
  shared/prometheus/service_test.go
Labels: OK to merge, Ready For Review

#5567 Invert `--disable-new-state-mgmt` to `--enable-new-state-mgmt`
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/service.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/check_historical_state.go
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/assignments_test.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Priority: Critical, Ready For Review

#5561 Shift To Trace Logs
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets_test.go
Labels: OK to merge, Ready For Review

#5570 No More EthereumAPIs Patch
  WORKSPACE
  beacon-chain/rpc/validator/assignments.go
  proto/beacon/p2p/v1/BUILD.bazel
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
  tools/ssz.bzl
  validator/internal/beacon_node_validator_service_mock.go
Labels: OK to merge

#5573 Add hotfix for E2E
  beacon-chain/rpc/beacon/validators.go
  endtoend/evaluators/validator.go
Labels: OK to merge

#5575 Handle Nil State Object
  beacon-chain/state/getters.go
  beacon-chain/state/getters_test.go
Labels: OK to merge, Ready For Review
