Repository OffchainLabs/prysm, pull requests merged in 2020-11, with the labels that each got.

#7693 Fix param naming in BestNonFinalized
  beacon-chain/p2p/peers/status.go
Labels: Cleanup, OK to merge, Ready For Review

#7678 Continue In ProcessPreGenesisDeposits
  beacon-chain/core/blocks/deposit.go
  beacon-chain/core/blocks/deposit_test.go
Labels: Ready For Review

#7681 Avoid Setting State to Nil In Process Deposit
  beacon-chain/powchain/deposit.go
Labels: Audit, OK to merge, Ready For Review

#7698 Allocate Fewer Large Slices
  beacon-chain/core/epoch/precompute/slashing.go
  beacon-chain/rpc/beacon/validators.go
Labels: OK to merge, Ready For Review

#7646 Update Dependencies for Bug Fixes and OSS Vulnerability Patching
  deps.bzl
  go.mod
  go.sum
Labels: Audit, OK to merge, Ready For Review, Security

#7687 Use batch verify signature for a signle block
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, cpu-profile-improvement

#7702 Update which state to use for participation endpoint
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#7706 Fix Arm64 Builds For Herumi
  third_party/herumi/bls_eth_go_binary.BUILD
Labels: Ready For Review

#7715 Retrieve State From Last Finalized Checkpoint
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
Labels: Ready For Review

#7717 Remove expensive validators only method
  beacon-chain/blockchain/testing/BUILD.bazel
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/state/getters.go
  beacon-chain/state/getters_test.go
Labels: Ready For Review

#7682 Use Atomic Booleans in Sync Service
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  shared/abool/BUILD.bazel
  shared/abool/abool.go
  shared/abool/abool_test.go
Labels: Audit, OK to merge, Ready For Review, Security

#7713 Include exiting and slashing as active in metrics
  beacon-chain/blockchain/metrics.go
Labels: OK to merge, Ready For Review

#7669 Include Multilock for GetAttPreState With Tests
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/cache/checkpoint_state.go
  beacon-chain/cache/checkpoint_state_test.go
  shared/mputil/BUILD.bazel
  shared/mputil/multilock.go
  shared/mputil/multilock_test.go
Labels: Enhancement, OK to merge, Ready For Review

#7708 call LogValidatorGainsAndLosses at end of epoch
  validator/client/metrics.go
  validator/client/runner.go
Labels: OK to merge, Ready For Review

#7721 Fix `GetValidatorParticipation` slot to epoch conversion
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#7723 Stop Sync Service More Cleanly
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/sync/subscriber.go
Labels: Ready For Review

#7725 Fuzz: sigp/beaconfuzz#91
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/proposer_slashing.go
  beacon-chain/core/blocks/proposer_slashing_regression_test.go
  beacon-chain/core/blocks/testdata/beaconfuzz_91_beacon.ssz
  beacon-chain/core/blocks/testdata/beaconfuzz_91_proposer_slashing.ssz
Labels: Bug, Fuzz, OK to merge, Priority: Critical

#7727 Update genesis time and deposit contract
  beacon-chain/flags/base.go
  shared/featureconfig/config.go
  shared/params/mainnet_config.go
  shared/params/network_config.go
Labels: OK to merge, Ready For Review

#7719 Check if all validators are exited on every slot
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/runner_test.go
Labels: Ready For Review

#7718 Refactor p2p requests: extract BeaconBlocksByRangeRequest and BeaconBlocksByRootRequest
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_send_request.go
  beacon-chain/sync/rpc_send_request_test.go
Labels: OK to merge, Ready For Review

#7730 Remove redundant error return from filterPeers()
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
Labels: Cleanup, OK to merge, Ready For Review

#7728 Powchain: Minor fix for log statement
  beacon-chain/powchain/service.go
Labels: OK to merge

#7731 Remove duplicated --slots-per-archive-point in help menu
  beacon-chain/usage.go
Labels: OK to merge, Ready For Review

#7716 Reduce Hashing When Filling In Forkchoice Blocks
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: OK to merge, Ready For Review

#7726 Add Backoff For Peer Dials
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/peers/peerdata/store.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_goodbye_test.go
Labels: Networking, OK to merge, Ready For Review

#7704 Init-sync fetcher: backtracking
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
Labels: OK to merge, Ready For Review

#7733 Add one more assertion to fetcher test
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
Labels: Cleanup, OK to merge, Ready For Review

#7738 Fix Pull Request Template Language
  .github/PULL_REQUEST_TEMPLATE.md
Labels: OK to merge, Ready For Review

#7736 Change To Mainnet Block Time
  shared/params/mainnet_config.go
  shared/params/testnet_altona_config.go
  shared/params/testnet_medalla_config.go
  shared/params/testnet_spadina_config.go
  shared/params/testnet_zinken_config.go
Labels: OK to merge, Ready For Review

#7564 Init-sync: backtracking to alternative forks
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/blocks_queue_utils.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Batch Sync, OK to merge, Priority: Critical, Ready For Review, Sync

#7741 Add DeepSource for Bash Files
  .deepsource.toml
Labels: OK to merge, Ready For Review

#7737 Add `--mainnet` no-op flag for easier docker tooling
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#7722 Minor Log Improvement to gRPC Server
  beacon-chain/rpc/service.go
  endtoend/components/beacon_node.go
  slasher/rpc/service.go
Labels: OK to merge, Ready For Review

#7729 Startup routine to clean up dirty states in DB
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/state/stategen/service.go
Labels: OK to merge, Ready For Review

#7742 Keep Non Finalized States
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
Labels: OK to merge, Ready For Review

#7743 Add toledo config
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/params/BUILD.bazel
  shared/params/testnet_toledo_config.go
  validator/accounts/cmd_accounts.go
  validator/accounts/cmd_wallet.go
Labels: Ready For Review

#7748 Fix comment on DisableAccountMetricFlag
  validator/flags/flags.go
Labels: OK to merge

#7710 Pass By Value Instead Of Reference
  beacon-chain/blockchain/head.go
  beacon-chain/core/blocks/attester_slashing.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/new.go
  beacon-chain/core/epoch/precompute/slashing.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/validators/validator.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/state/getters.go
Labels: OK to merge, Ready For Review

#7747 Allow exiting validators to attest
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#7685 Prevent Usage of Stdlib File/Dir Writing With Static Analysis
  BUILD.bazel
  beacon-chain/core/state/interop/BUILD.bazel
  beacon-chain/core/state/interop/write_block_to_disk.go
  beacon-chain/core/state/interop/write_state_to_disk.go
  beacon-chain/db/kv/backup.go
  beacon-chain/db/kv/kv.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/utils.go
  endtoend/helpers/helpers.go
  endtoend/params/params.go
  nogo_config.json
  shared/fileutil/fileutil.go
  shared/fileutil/fileutil_test.go
  shared/keystore/BUILD.bazel
  shared/keystore/key.go
  shared/tos/BUILD.bazel
  shared/tos/tos.go
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/kv.go
  tools/analyzers/properpermissions/BUILD.bazel
  tools/analyzers/properpermissions/analyzer.go
  tools/analyzers/properpermissions/analyzer_test.go
  tools/analyzers/properpermissions/testdata/BUILD.bazel
  tools/analyzers/properpermissions/testdata/custom_imports.go
  tools/analyzers/properpermissions/testdata/regular_imports.go
  tools/beacon-fuzz/BUILD.bazel
  tools/beacon-fuzz/main.go
  tools/benchmark-files-gen/BUILD.bazel
  tools/benchmark-files-gen/main.go
  tools/enr-calculator/BUILD.bazel
  tools/enr-calculator/main.go
  tools/genesis-state-gen/main.go
  tools/interop/export-genesis/BUILD.bazel
  tools/interop/export-genesis/main.go
  tools/keystores/BUILD.bazel
  tools/keystores/main.go
  tools/update-genesis-time/BUILD.bazel
  tools/update-genesis-time/main.go
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_backup_test.go
  validator/accounts/wallet/BUILD.bazel
  validator/accounts/wallet/wallet.go
  validator/accounts/wallet_create_test.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/rpc/BUILD.bazel
  validator/rpc/auth.go
Labels: Audit, Ready For Review, Security

#7754 Update delete state(s) functions
  beacon-chain/db/kv/state.go
  beacon-chain/state/stategen/setter_test.go
Labels: Ready For Review

#7744 Batch verify aggregated attestation signatures
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
Labels: OK to merge, Ready For Review, cpu-profile-improvement

#7759 Run gazelle to sort deps.bzl
  deps.bzl
Labels: Ready For Review

#7758 Correct how AllValidatorsAreExited creates status request
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge

#7751 Fix Seen Cache Interval
  beacon-chain/p2p/parameter_test.go
  beacon-chain/p2p/pubsub.go
Labels: OK to merge, Ready For Review

#7755 Add more validation to AllValidatorsAreExited
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Bug, Enhancement, OK to merge, Ready For Review

#7757 Don't Terminate Log Processing Early
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service_test.go
  beacon-chain/powchain/testing/mock.go
Labels: OK to merge, Ready For Review

#7605 Use new attestation protection
  validator/client/BUILD.bazel
  validator/client/attest.go
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/client/attest_test.go
  validator/client/propose_test.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/db/iface/BUILD.bazel
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/attestation_history_v2_test.go
  validator/db/kv/proposal_history_v2.go
  validator/db/kv/proposal_history_v2_test.go
  validator/node/node.go
Labels: OK to merge, Ready For Review

#7761 Remove redundant calls to os.exit() in TestMain
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/cache_test.go
  beacon-chain/core/epoch/spectest/spectest_test.go
  beacon-chain/p2p/peers/peers_test.go
  beacon-chain/p2p/peers/scorers/scorers_test.go
  beacon-chain/powchain/powchain_test.go
  beacon-chain/rpc/beacon/beacon_test.go
  beacon-chain/rpc/validator/validator_test.go
  beacon-chain/state/stateutil/stateutil_test.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/sync_test.go
  shared/aggregation/attestations/attestations_test.go
  shared/slotutil/slotutil_test.go
  slasher/beaconclient/service_test.go
  slasher/db/kv/kv_test.go
  slasher/detection/attestations/attestations_test.go
  slasher/detection/proposals/proposals_test.go
  slasher/node/node_test.go
  slasher/rpc/rpc_test.go
  tools/bootnode/bootnode_test.go
  tools/sendDepositTx/sendDeposits_test.go
  validator/client/service_test.go
Labels: OK to merge, Ready For Review, Testing

#7762 Honor the --max-msg-size option in the gRPC service.
  beacon-chain/node/node.go
  beacon-chain/rpc/service.go
Labels: OK to merge, Ready For Review

#7760 Fix Blst Build For OSX
  shared/bls/blst/BUILD.bazel
  shared/bls/blst/aliases.go
  shared/bls/blst/init.go
  shared/bls/blst/public_key.go
  shared/bls/blst/secret_key.go
  shared/bls/blst/signature.go
  shared/bls/blst/stub.go
Labels: OK to merge, Ready For Review

#7709 Attestation performance metrics
  validator/client/attest.go
  validator/client/metrics.go
Labels: OK to merge, Ready For Review

#7756 Miscellaneous Keystore Fixes
  validator/accounts/accounts_delete.go
  validator/keymanager/imported/keymanager.go
Labels: Ready For Review

#7769 Use t.TempDir() in tests
  beacon-chain/db/kv/kv_test.go
  beacon-chain/db/testing/BUILD.bazel
  beacon-chain/db/testing/setup_db.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/options_test.go
  shared/fileutil/BUILD.bazel
  shared/fileutil/fileutil_test.go
  shared/keystore/BUILD.bazel
  shared/keystore/key_test.go
  shared/keystore/keystore_test.go
  shared/testutil/BUILD.bazel
  shared/testutil/tempdir.go
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/kv_test.go
  slasher/db/testing/BUILD.bazel
  slasher/db/testing/setup_db.go
  slasher/db/testing/setup_db_test.go
  slasher/node/BUILD.bazel
  slasher/node/node_test.go
  tools/keystores/BUILD.bazel
  tools/keystores/main_test.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_backup_test.go
  validator/accounts/accounts_delete_test.go
  validator/accounts/accounts_exit_test.go
  validator/accounts/accounts_import_test.go
  validator/accounts/wallet/BUILD.bazel
  validator/accounts/wallet/wallet_test.go
  validator/accounts/wallet_create_test.go
  validator/accounts/wallet_recover_test.go
  validator/client/service_test.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/db_test.go
  validator/db/kv/manage_test.go
  validator/db/testing/BUILD.bazel
  validator/db/testing/setup_db.go
  validator/db/testing/setup_db_test.go
  validator/keymanager/remote/BUILD.bazel
  validator/keymanager/remote/keymanager_test.go
  validator/node/BUILD.bazel
  validator/node/node_test.go
  validator/rpc/BUILD.bazel
  validator/rpc/auth_test.go
Labels: OK to merge, Ready For Review, Testing

#7771 Add chain info tests
  beacon-chain/blockchain/chain_info_test.go
Labels: OK to merge, Ready For Review, Testing

#7770 Fix Prysm Runtime Data Races
  beacon-chain/state/state_trie.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  shared/rand/rand.go
Labels: Ready For Review, Security

#7776 Remove Recursive Read Lock in Shared/Rand
  shared/rand/rand.go
Labels: OK to merge, Priority: Critical, Ready For Review

#7774 Fix Up Exits Pool Logic
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/operations/voluntaryexits/BUILD.bazel
  beacon-chain/operations/voluntaryexits/service.go
  beacon-chain/operations/voluntaryexits/service_test.go
Labels: Bug, OK to merge, Ready For Review

#7777 Remove unused chainStartPubKeys logic
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/powchain/log_processing.go
Labels: OK to merge, Ready For Review

#7768 Use requested epoch for `GetValidatorParticipation`
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge, Ready For Review

#7778 Add Go Report Card to Prysm
  README.md
Labels: Enhancement, OK to merge, Ready For Review

#7779 Fix readme typo
  README.md
Labels: OK to merge, Ready For Review

#7772 Stop early PendingExits
  beacon-chain/operations/voluntaryexits/service.go
Labels: OK to merge, Ready For Review

#7775 Add configurable deposit amounts to testutil
  shared/testutil/BUILD.bazel
  shared/testutil/deposits.go
  shared/testutil/deposits_test.go
Labels: Ready For Review

#7783 Add EIP-2333 Conformity Tests
  shared/bls/BUILD.bazel
  shared/bls/bls.go
  validator/keymanager/derived/BUILD.bazel
  validator/keymanager/derived/eip_test.go
Labels: OK to merge, Priority: High, Ready For Review, Testing

#7786 `RandaoSignatureSet` to not return state
  beacon-chain/core/blocks/randao_test.go
  beacon-chain/core/blocks/signature.go
  beacon-chain/core/state/transition.go
Labels: Ready For Review

#7784 Enable head sync only during period of non-finality
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/blockchain_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: OK to merge, Ready For Review

#7184 Add Gossip Scoring For Peers
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/gossip_scoring_params.go
  beacon-chain/p2p/pubsub.go
  beacon-chain/p2p/service.go
  shared/featureconfig/flags.go
Labels: Networking, OK to merge, Ready For Review

#7793 Fix `finalized` response for `GetValidatorParticipation`
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#7782 Update genesis delay to one week
  shared/params/mainnet_config.go
Labels: Ready For Review

#7794 Change connect/disconnect logs to debug
  beacon-chain/p2p/handshake.go
Labels: OK to merge, Ready For Review

#7792 Warn missing protection db
  validator/node/BUILD.bazel
  validator/node/node.go
Labels: OK to merge, Ready For Review

#7795 Mitigate potential overflow. ethereum/eth2.0-specs#2129
  beacon-chain/core/helpers/block.go
  beacon-chain/core/helpers/block_test.go
Labels: OK to merge

#7796 Remove Outdated Keystore Cryptography
  deps.bzl
  go.mod
  go.sum
  validator/keymanager/derived/BUILD.bazel
  validator/keymanager/derived/eip_test.go
  validator/keymanager/derived/keymanager.go
  validator/keymanager/derived/v1derivation/BUILD.bazel
  validator/keymanager/derived/v1derivation/util.go
Labels: OK to merge, Ready For Review, Security, release-target

#7797 Add Pyrmont config
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/params/BUILD.bazel
  shared/params/testnet_pyrmont_config.go
  validator/accounts/cmd_accounts.go
  validator/accounts/cmd_wallet.go
Labels: OK to merge, Ready For Review

#7789 Immediate Slashing Protection Data Storage
  validator/client/attest.go
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/db/iface/interface.go
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/attestation_history_v2_test.go
Labels: OK to merge, Ready For Review

#7469 Align to spec v1.0.0
  WORKSPACE
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/precompute/slashing_test.go
  beacon-chain/core/state/benchmarks_test.go
  go.mod
  proto/beacon/p2p/v1/generated.ssz.go
  proto/beacon/rpc/v1_gateway/debug.pb.go
  proto/ssz_proto_library.bzl
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/params/BUILD.bazel
  shared/params/mainnet_config.go
  shared/params/minimal_config.go
  shared/params/testnet_pyrmont_config.go
  shared/params/testnet_toledo_config.go
  validator/accounts/cmd_accounts.go
  validator/accounts/cmd_wallet.go
Labels: OK to merge, Ready For Review

#7800 Update rules_go, prune unused go_repositories
  DEPENDENCIES.md
  WORKSPACE
  deps.bzl
Labels: OK to merge

#7802 Remove testnets prior to spec v1.0.0
  shared/featureconfig/config.go
  shared/featureconfig/config_test.go
  shared/featureconfig/flags.go
  shared/params/BUILD.bazel
  shared/params/testnet_altona_config.go
  shared/params/testnet_medalla_config.go
  shared/params/testnet_onyx_config.go
  shared/params/testnet_spadina_config.go
  shared/params/testnet_zinken_config.go
  tools/bootnode/bootnode.go
  tools/cluster-pk-manager/client/main.go
  tools/cluster-pk-manager/server/main.go
  tools/sendDepositTx/sendDeposits.go
  validator/accounts/cmd_accounts.go
  validator/accounts/cmd_wallet.go
Labels: Cleanup, OK to merge

#7803 Fix Windows Builds For Blst
  shared/bls/blst/BUILD.bazel
  shared/bls/blst/aliases.go
  shared/bls/blst/bls_benchmark_test.go
  shared/bls/blst/init.go
  shared/bls/blst/public_key.go
  shared/bls/blst/public_key_test.go
  shared/bls/blst/secret_key.go
  shared/bls/blst/secret_key_test.go
  shared/bls/blst/signature.go
  shared/bls/blst/signature_test.go
  shared/bls/blst/stub.go
  tools/cross-toolchain/cc_toolchain.BUILD.bazel.tpl
  tools/cross-toolchain/cc_toolchain_config_windows.bzl.tpl
Labels: OK to merge, Ready For Review

#7790 Clean Up GoodByes
  beacon-chain/p2p/connection_gater.go
  beacon-chain/p2p/connection_gater_test.go
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/error.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
Labels: OK to merge, Ready For Review

#7804 Update Go-Ethereum Dependency
  WORKSPACE
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#7805 Make Blst the Default Library
  shared/featureconfig/config.go
  shared/featureconfig/deprecated_flags.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#7801 Add Partial Deposits in E2E
  endtoend/components/BUILD.bazel
  endtoend/components/validator.go
  endtoend/endtoend_test.go
Labels: OK to merge, Ready For Review

#7809 Simplify Terms of Service Log
  shared/tos/tos.go
Labels: OK to merge, Ready For Review

#7812 Fix instances of "The result of append is not used anywhere SCC-SA4010"
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/rpc/validator/assignments.go
Labels: Cleanup, OK to merge

#7814 Update TestMain() to use os.Exit()
  beacon-chain/blockchain/blockchain_test.go
  beacon-chain/cache/cache_test.go
  beacon-chain/core/epoch/spectest/spectest_test.go
  beacon-chain/p2p/peers/peers_test.go
  beacon-chain/p2p/peers/scorers/scorers_test.go
  beacon-chain/powchain/powchain_test.go
  beacon-chain/rpc/beacon/beacon_test.go
  beacon-chain/rpc/validator/validator_test.go
  beacon-chain/state/stateutil/stateutil_test.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/sync_test.go
  shared/aggregation/attestations/attestations_test.go
  shared/slotutil/slotutil_test.go
  slasher/beaconclient/service_test.go
  slasher/db/kv/kv_test.go
  slasher/detection/attestations/attestations_test.go
  slasher/detection/proposals/proposals_test.go
  slasher/node/node_test.go
  slasher/rpc/rpc_test.go
  tools/bootnode/bootnode_test.go
  tools/sendDepositTx/sendDeposits_test.go
Labels: Priority: Critical, Ready For Review

#7811 Loadblock returns err on invalid range
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/replay.go
Labels: OK to merge, Ready For Review

#7824 Update Bazel Go-Ethereum
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review

#7825 Remove a few old metrics
  beacon-chain/operations/slashings/metrics.go
  beacon-chain/operations/slashings/service.go
  beacon-chain/sync/metrics.go
  beacon-chain/sync/pending_attestations_queue.go
Labels: OK to merge, Ready For Review

#7830 Update go-pbs after v1 changes
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1_gateway/debug.pb.go
  proto/cluster/services.pb.go
  proto/validator/accounts/v2_gateway/keymanager.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.go
Labels: Bug, OK to merge, Priority: Critical, release-target

#7821 Refactor HD Wallets for Enhanced Security
  go.mod
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts.go
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_backup_test.go
  validator/accounts/accounts_create.go
  validator/accounts/accounts_create_test.go
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_enable_disable.go
  validator/accounts/accounts_enable_disable_test.go
  validator/accounts/accounts_exit.go
  validator/accounts/accounts_import.go
  validator/accounts/accounts_import_test.go
  validator/accounts/accounts_list.go
  validator/accounts/accounts_list_test.go
  validator/accounts/cmd_accounts.go
  validator/accounts/iface/wallet.go
  validator/accounts/testing/BUILD.bazel
  validator/accounts/testing/mock.go
  validator/accounts/wallet/BUILD.bazel
  validator/accounts/wallet/wallet.go
  validator/accounts/wallet/wallet_test.go
  validator/accounts/wallet_create.go
  validator/accounts/wallet_create_test.go
  validator/accounts/wallet_recover.go
  validator/accounts/wallet_recover_test.go
  validator/client/BUILD.bazel
  validator/client/service.go
  validator/client/validator.go
  validator/keymanager/derived/BUILD.bazel
  validator/keymanager/derived/backup.go
  validator/keymanager/derived/backup_test.go
  validator/keymanager/derived/eip_test.go
  validator/keymanager/derived/keymanager.go
  validator/keymanager/derived/keymanager_test.go
  validator/keymanager/derived/mnemonic.go
  validator/keymanager/imported/import.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/accounts.go
  validator/rpc/accounts_test.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: Accounts, OK to merge, Ready For Review, Refactor, Security, release-target

#7835 Remove WaitForSynced
  beacon-chain/rpc/beaconv1/validator.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
  deps.bzl
  go.mod
  go.sum
  scripts/update-mockgen.sh
  shared/featureconfig/config.go
  shared/featureconfig/deprecated_flags.go
  shared/featureconfig/flags.go
  shared/mock/beacon_validator_client_mock.go
  shared/mock/beacon_validator_server_mock.go
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review

#7833 Add --mainnet no-op to validator sub-commands
  validator/accounts/cmd_accounts.go
  validator/accounts/cmd_wallet.go
Labels: OK to merge, Ready For Review

#7823 Check Sub Group for Herumi and Fix Edge Cases
  deps.bzl
  go.mod
  go.sum
  shared/bls/bls_test.go
  shared/bls/blst/public_key.go
  shared/bls/blst/secret_key.go
  shared/bls/blst/secret_key_test.go
  shared/bls/common/error.go
  shared/bls/herumi/init.go
  shared/bls/herumi/secret_key.go
  shared/bls/herumi/secret_key_test.go
  shared/bls/spectest/sign_test.go
Labels: OK to merge, Ready For Review

#7836 Add Back Flag to Subscribe to All Subnets
  beacon-chain/flags/base.go
  beacon-chain/flags/config.go
  beacon-chain/main.go
  beacon-chain/sync/metrics.go
  beacon-chain/sync/subscriber.go
  beacon-chain/usage.go
Labels: OK to merge, Ready For Review, release-target

#7831 Remove Keymanageropts Pattern from Wallets and Remove Enable/Disable Feature for V1 CLI
  go.mod
  go.sum
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  validator/accounts/accounts_delete_test.go
  validator/accounts/accounts_enable_disable.go
  validator/accounts/accounts_import_test.go
  validator/accounts/accounts_list.go
  validator/accounts/accounts_list_test.go
  validator/accounts/cmd_accounts.go
  validator/accounts/testing/mock.go
  validator/accounts/wallet/BUILD.bazel
  validator/accounts/wallet/wallet.go
  validator/accounts/wallet/wallet_test.go
  validator/accounts/wallet_create.go
  validator/accounts/wallet_create_test.go
  validator/accounts/wallet_recover.go
  validator/accounts/wallet_recover_test.go
  validator/keymanager/derived/keymanager.go
  validator/keymanager/derived/keymanager_test.go
  validator/keymanager/imported/BUILD.bazel
  validator/keymanager/imported/backup_test.go
  validator/keymanager/imported/enable_disable.go
  validator/keymanager/imported/enable_disable_test.go
  validator/keymanager/imported/import_test.go
  validator/keymanager/imported/keymanager.go
  validator/keymanager/imported/keymanager_test.go
  validator/keymanager/imported/refresh.go
  validator/node/node.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: Accounts, Cleanup, OK to merge, Ready For Review, Security, release-target

#7826 Hardening aggregated attestation queue check
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/validate_aggregate_proof.go
Labels: OK to merge, Ready For Review, Security, release-target

#7841 Refactor scoring service
  beacon-chain/p2p/peers/scorers/bad_responses.go
  beacon-chain/p2p/peers/scorers/bad_responses_test.go
  beacon-chain/p2p/peers/scorers/block_providers.go
  beacon-chain/p2p/peers/scorers/block_providers_test.go
  beacon-chain/p2p/peers/scorers/service.go
  beacon-chain/p2p/peers/scorers/service_test.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/service.go
Labels: Ready For Review

#7834 Hardening unaggregated attestation queue check
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/validate_beacon_attestation.go
Labels: OK to merge, Ready For Review, Security, release-target

#7839 Source lrg target
  slasher/detection/attestations/spanner.go
  slasher/detection/attestations/spanner_test.go
Labels: OK to merge

#7847 Validate beacon block in pending queue
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review, Security, release-target

#7675 Implement Standard Slashing Protection JSON With Importing Logic
  validator/db/iface/interface.go
  validator/db/kv/proposal_history.go
  validator/db/kv/proposal_history_v2.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/format.go
  validator/slashing-protection/local/standard-protection-format/helpers.go
  validator/slashing-protection/local/standard-protection-format/helpers_test.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
Labels: OK to merge, Priority: Critical, Ready For Review

#7843 Extract common types from sync
  beacon-chain/p2p/types/BUILD.bazel
  beacon-chain/p2p/types/rpc_errors.go
  beacon-chain/p2p/types/rpc_goodbye_codes.go
  beacon-chain/sync/error.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rate_limiter_test.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_goodbye_test.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_ping_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
Labels: OK to merge, Ready For Review

#7849 Remove listen for ChainStarted in WaitForChainStart
  beacon-chain/core/feed/state/events.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
Labels: OK to merge

#7851 Handle Deposit Prune Proof Panic
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/cache/depositcache/deposits_cache_test.go
Labels: Ready For Review

#7850 Save Powchain Metadata To Disk On Chainstart
  beacon-chain/powchain/log_processing.go
Labels: Ready For Review, release-target

#7480 Peer status peer scorer
  beacon-chain/p2p/peers/peerdata/store.go
  beacon-chain/p2p/peers/scorers/BUILD.bazel
  beacon-chain/p2p/peers/scorers/bad_responses.go
  beacon-chain/p2p/peers/scorers/peer_status.go
  beacon-chain/p2p/peers/scorers/peer_status_test.go
  beacon-chain/p2p/peers/scorers/service.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
Labels: OK to merge, Ready For Review

#7853 Return Finalized State Early from StateByRoot
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
Labels: Ready For Review, release-target

#7852 Change Back Metadata Error Check
  beacon-chain/sync/rpc_ping.go
Labels: OK to merge, Ready For Review

#7816 Pending block queue caching with TTL
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/fuzz_exports.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: OK to merge, Ready For Review, Security, release-target

#7861 Cache ETH1 Headers When Requesting Logs
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
Labels: OK to merge, Priority: Critical, Ready For Review

#7837 Check Target Root Better
  beacon-chain/sync/validate_aggregate_proof.go
Labels: OK to merge, Ready For Review, Security, release-target

#7844 Add Basic Support for IP Tracker
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
Labels: Networking, OK to merge, Ready For Review, Security, release-target

#7865 Update eth2 specs version badge in README
  README.md
Labels: OK to merge, Ready For Review

#7869 Update Gossipsub Parameters
  beacon-chain/p2p/parameter_test.go
  beacon-chain/p2p/pubsub.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Networking, OK to merge, Ready For Review, release-target

#7854 Various Powershell Fixes
  prysm.ps1
Labels: OK to merge

#7855 Save GenesisValidatorsRoot from WaitForChainStart
  validator/client/validator.go
  validator/client/validator_test.go
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/db/kv/genesis.go
  validator/db/kv/genesis_test.go
  validator/db/kv/manage.go
  validator/db/kv/schema.go
Labels: OK to merge, Ready For Review

#7863 Reduce no attestation in pool to warn
  beacon-chain/rpc/validator/aggregator.go
  validator/client/aggregate.go
Labels: Ready For Review

#7870 Hotfix for WaitForChainStart GenesisValidatorsRoot Check
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#7873 Dynamic Reloading of Keys on Any FSNotify Event
  validator/keymanager/imported/refresh.go
  validator/keymanager/imported/refresh_test.go
Labels: Accounts, OK to merge, Ready For Review, release-target

#7864 Verify GenesisValidatorRoot Matches the One in DB on Slashing Protection Import
  validator/db/iface/interface.go
  validator/slashing-protection/local/standard-protection-format/helpers.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
Labels: OK to merge, Ready For Review

#7874 Fix potential panic with nil *big.Int
  beacon-chain/powchain/block_cache.go
  beacon-chain/powchain/block_cache_test.go
  beacon-chain/powchain/block_reader.go
Labels: OK to merge

#7877 Remove deprecated feature flags
  shared/featureconfig/deprecated_flags.go
Labels: OK to merge, Ready For Review, release-target

#7879 Remove chain not started error
  beacon-chain/blockchain/service.go
  beacon-chain/sync/service.go
Labels: OK to merge, Ready For Review, release-target

#7872 Fix spec diff with comments. Fixes #7856
  shared/params/mainnet_config.go
Labels: OK to merge, Priority: Critical, Ready For Review

#7881 Remove outdated code in accounts
  validator/accounts/cmd_accounts.go
  validator/accounts/cmd_wallet.go
  validator/accounts/wallet/BUILD.bazel
  validator/accounts/wallet/wallet_test.go
Labels: Ready For Review

#7882 Add Test For Earliest Voting Block
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: OK to merge, Ready For Review

#7885 p2p: return error when attempting to connect to a bad peer
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets_test.go
Labels: OK to merge, Ready For Review

#7886 Fix creation time of beacon-node, validator and slasher
  beacon-chain/BUILD.bazel
  slasher/BUILD.bazel
  validator/BUILD.bazel
Labels: OK to merge

#7884 Make Follow Distance Lookup Simpler
  beacon-chain/powchain/service.go
Labels: OK to merge, Ready For Review, release-target

#7891 Change attestation signature error to DEBUG level
  beacon-chain/sync/validate_beacon_attestation.go
Labels: OK to merge

#7890 RPC: healthz should return an error when the node is syncing
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
Labels: OK to merge

#7647 highest slashing attestation RPC endpoint
  proto/slashing/slashing.pb.go
  proto/slashing/slashing.proto
  slasher/rpc/server.go
  validator/testing/slasher_mock.go
Labels: OK to merge, Ready For Review

#7899 Fix Pending Queue For Unaggregated Attestations
  beacon-chain/sync/pending_attestations_queue.go
Labels: Ready For Review, release-target

#7901 Add More Default CORS Domains to the gRPC Gateway
  beacon-chain/flags/base.go
  validator/flags/flags.go
Labels: OK to merge, Ready For Review

#7883 Fix Alpine Docker Image
  WORKSPACE
Labels: OK to merge

#7906 Update boot node to not use pyrmont
  tools/bootnode/bootnode.go
Labels: OK to merge, Ready For Review

#7912 Remove Deprecated Tooling
  go.mod
  tools/contract-addr/BUILD.bazel
  tools/contract-addr/main.go
  tools/relaynode/BUILD.bazel
  tools/relaynode/relaynode.go
  tools/sendDepositTx/BUILD.bazel
  tools/sendDepositTx/README.md
  tools/sendDepositTx/sendDeposits.go
  tools/sendDepositTx/sendDeposits_test.go
  tools/update-genesis-time/BUILD.bazel
  tools/update-genesis-time/README.md
  tools/update-genesis-time/main.go
Labels: OK to merge, Ready For Review

#7914 Update sync logging levels
  beacon-chain/sync/deadlines.go
  beacon-chain/sync/error.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_send_request.go
  beacon-chain/sync/rpc_send_request_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_beacon_attestation.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_voluntary_exit.go
Labels: Ready For Review

#7904 Use params network config as default bootstrap nodes and deposit contract
  beacon-chain/flags/BUILD.bazel
  beacon-chain/flags/base.go
  shared/cmd/flags.go
Labels: OK to merge, Ready For Review

#7915 More Default CORS Rules
  beacon-chain/flags/base.go
Labels: OK to merge, Ready For Review

#7916 P2P: Increase outbound message queue size to 256
  beacon-chain/p2p/service.go
Labels: OK to merge, Ready For Review

#7919 Add teku's bootnode
  scripts/check-todo.sh
  shared/params/mainnet_config.go
Labels: OK to merge, Ready For Review

#7913 Give error message if trying to import into non-imported wallet
  validator/accounts/accounts_import.go
  validator/accounts/accounts_import_test.go
Labels: OK to merge

#7925 Bake In Mainnet Bootnodes
  shared/params/mainnet_config.go
Labels: OK to merge, Ready For Review, release-target

#7922 Add Back Error/Debug Logs
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: OK to merge, Ready For Review

#7910 Fix Up READMEs for Mainnet
  CONTRIBUTING.md
  README.md
  TESTNET.md
  beacon-chain/README.md
  contracts/README.md
  contracts/deposit-contract/README.md
  endtoend/README.md
  proto/README.md
  scripts/README.md
  slasher/README.md
  third_party/README.md
  validator/README.md
Labels: OK to merge, Ready For Review

#7927 Exit Pending Queue Properly
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
Labels: OK to merge, Security, Sync, release-target

#7932 Make grpc-headers flag work
  validator/accounts/accounts_exit.go
  validator/client/service.go
Labels: OK to merge, Ready For Review
