Repository OffchainLabs/prysm, pull requests merged in 2020-05, with the labels that each got.

#5668 Implement GetBeaconState Endpoint
  beacon-chain/flags/base.go
  beacon-chain/gateway/BUILD.bazel
  beacon-chain/gateway/gateway.go
  beacon-chain/gateway/server/main.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/state.go
  beacon-chain/rpc/beacon/state_test.go
  beacon-chain/rpc/service.go
  beacon-chain/usage.go
  proto/beacon/rpc/v1/debug.proto
Labels: OK to merge, Ready For Review

#5702 replaced 265 with 256 ...derp
  prysm.bat
Labels: OK to merge

#5701 Revert Validator Reference Copy
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/slashing.go
  beacon-chain/state/references_test.go
  beacon-chain/state/setters.go
Labels: OK to merge, Ready For Review

#5704 Custom Method For Block Signing Root
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/core/helpers/signing_root_test.go
  beacon-chain/state/stateutil/blocks.go
Labels: Ready For Review

#5699 Move recreated constants out of smaller scopes
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/epoch/precompute/slashing.go
Labels: Ready For Review

#5707 Enforce validator's keystore dir
  validator/accounts/account.go
  validator/accounts/account_test.go
Labels: OK to merge, Ready For Review

#5706 Rename Precompute Balance vars to be more descriptive
  beacon-chain/archiver/service.go
  beacon-chain/archiver/service_test.go
  beacon-chain/blockchain/metrics.go
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/epoch/precompute/justification_finalization.go
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
  beacon-chain/core/epoch/precompute/new.go
  beacon-chain/core/epoch/precompute/new_test.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/epoch/precompute/slashing.go
  beacon-chain/core/epoch/precompute/slashing_test.go
  beacon-chain/core/epoch/precompute/type.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/rpc/beacon/validators.go
Labels: OK to merge, Ready For Review

#5710 SlotToTime helper
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
Labels: OK to merge, Ready For Review

#5712 Regen historical state: don't skip saving historical state
  beacon-chain/db/kv/regen_historical_states.go
Labels: OK to merge, Ready For Review

#5691 Re-enable skipped block list paging unit test
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/beacon_test.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/validators_stream_test.go
  beacon-chain/rpc/beacon/validators_test.go
  shared/params/config.go
  shared/params/config_test.go
Labels: OK to merge, Ready For Review

#5726 Add more domains to domain cache
  validator/client/service.go
  validator/client/validator.go
Labels: Ready For Review

#5709 Return Genesis Block
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
Labels: OK to merge, Ready For Review

#5722 Remove silent errors from slasher
  slasher/detection/listeners.go
  slasher/detection/proposals/detector.go
  slasher/detection/service.go
Labels: OK to merge, Ready For Review

#5728 fixes runtime panic in state/getters
  beacon-chain/state/getters.go
  beacon-chain/state/getters_test.go
Labels: OK to merge, Ready For Review

#5723 Log out public key with accounts create
  validator/accounts/account.go
Labels: OK to merge, Ready For Review

#5737 Use cached state to validate `beacon_aggregate_and_proof`
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/validate_aggregate_proof.go
Labels: Ready For Review

#5732 Add params and update spec param names
  shared/params/config.go
Labels: OK to merge, Ready For Review

#5738 Add sent block time metric
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/receive_block.go
Labels: Ready For Review

#5661 Verify sig slasher
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/rpc/beacon/attestations_test.go
  shared/attestationutil/BUILD.bazel
  shared/attestationutil/attestation_utils.go
  shared/p2putils/BUILD.bazel
  shared/p2putils/fork.go
  slasher/beaconclient/chain_data.go
  slasher/beaconclient/chain_data_test.go
  slasher/beaconclient/service.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/server_test.go
Labels: Ready For Review

#5743 Use the custom HTR in a few more places
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/subscriber_handlers.go
  beacon-chain/sync/subscriber_test.go
  slasher/detection/BUILD.bazel
  slasher/detection/listeners.go
  validator/client/BUILD.bazel
  validator/client/validator_propose.go
Labels: Ready For Review

#5744 Add More Flags To Dev Mode
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5730 Retry Initialization of ETH1 Connection
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: OK to merge, Ready For Review

#5747 More explicit error message on wrong process when running prysm.sh
  prysm.sh
Labels: OK to merge, Ready For Review

#5694 Load chain config from file
  beacon-chain/BUILD.bazel
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/usage.go
  fuzz/block_fuzz.go
  fuzz/block_header_fuzz.go
  fuzz/common.go
  shared/cmd/flags.go
  shared/params/BUILD.bazel
  shared/params/config.go
  shared/params/loader.go
  shared/params/loader_test.go
  shared/testutil/spectest.go
Labels: Ready For Review

#5734 Add Persistent Subnets
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/committee_ids.go
  beacon-chain/cache/committee_ids_test.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation.go
  shared/params/network_config.go
Labels: Networking, Ready For Review

#5724 Move "Enter a password" cmd instructions to shared/cmd
  shared/cmd/BUILD.bazel
  shared/cmd/helpers.go
  validator/accounts/BUILD.bazel
  validator/accounts/account.go
Labels: Ready For Review

#5750 Update to v0.11.2 badge
  README.md
Labels: OK to merge

#5751 Add Chain Config File for Validator
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/usage.go
Labels: OK to merge, Ready For Review

#5755 Future slot check for state end point
  beacon-chain/rpc/beacon/state.go
  beacon-chain/rpc/beacon/state_test.go
Labels: Bug, Ready For Review

#5761 Remove Old Sync Routine
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/sync/initial-sync-old/BUILD.bazel
  beacon-chain/sync/initial-sync-old/log.go
  beacon-chain/sync/initial-sync-old/round_robin.go
  beacon-chain/sync/initial-sync-old/round_robin_test.go
  beacon-chain/sync/initial-sync-old/service.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5760 Memory Improvements
  beacon-chain/blockchain/head.go
  beacon-chain/sync/initial-sync/round_robin.go
Labels: OK to merge, Ready For Review

#5757 Remove flag requirement from accounts keys
  validator/accounts/BUILD.bazel
  validator/accounts/account.go
  validator/accounts/account_test.go
  validator/main.go
Labels: Ready For Review

#5685 Implement Stream Duties Functionality
  WORKSPACE
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/core/feed/state/events.go
  beacon-chain/rpc/testing/BUILD.bazel
  beacon-chain/rpc/testing/beacon_node_validator_service_mock.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  validator/internal/beacon_node_validator_service_mock.go
Labels: API, Ready For Review

#5770 Fix cold state generation
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: Bug, Ready For Review

#5756 Update gateway max resv size to 16MB
  beacon-chain/gateway/gateway.go
  beacon-chain/gateway/server/main.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/usage.go
  shared/cmd/flags.go
  validator/flags/flags.go
  validator/main.go
  validator/node/node.go
  validator/usage.go
Labels: OK to merge, Ready For Review

#5766 Refactors block fetching function to fetcher
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/service.go
Labels: OK to merge, Ready For Review

#5759 Add--disable-historical-detection flag to slasher
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  slasher/detection/BUILD.bazel
  slasher/detection/service.go
  slasher/usage.go
Labels: OK to merge

#5762 Add confirm password to validator accounts create
  shared/cmd/helpers.go
  validator/accounts/account.go
  validator/accounts/account_test.go
  validator/main.go
Labels: Ready For Review

#5772 Update BLS and use constant for SetETHmode
  shared/bls/bls.go
  third_party/herumi/herumi.bzl
Labels: OK to merge

#5767 Update Bootnode to v0.11.2
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
Labels: Ready For Review

#5773 BLS code cleanup
  shared/bls/BUILD.bazel
  shared/bls/bls.go
  shared/bls/bls_benchmark_test.go
  shared/bls/bls_test.go
Labels: OK to merge, Ready For Review

#5774 Init-sync discard debug logs in tests
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: OK to merge, Ready For Review

#5758 Cleanup usage of cli.context in validator/node
  validator/node/node.go
Labels: Ready For Review

#5776 Change non-mutating validator accesses to ReadOnly
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/validator/exit.go
  beacon-chain/state/getters.go
  beacon-chain/sync/validate_voluntary_exit.go
Labels: Ready For Review

#5777 Use alpine base image including libstdc++
  WORKSPACE
Labels: OK to merge, Ready For Review

#5765 Is slashable block rpc endpoint implementation
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/sync/validate_beacon_blocks.go
  slasher/beaconclient/chain_data.go
  slasher/beaconclient/chain_data_test.go
  slasher/beaconclient/service.go
  slasher/detection/proposals/detector.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/server_test.go
Labels: Ready For Review

#5780 Don't Copy The Whole Validator Map each time
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/state/setters.go
Labels: Ready For Review

#5695 Refactor validator protection for attesters
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/client/fake_validator_test.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
  validator/client/validator_propose_test.go
  validator/client/validator_test.go
  validator/db/attestation_history.go
  validator/db/attestation_history_test.go
  validator/db/iface/interface.go
  validator/db/proposal_history.go
Labels: Ready For Review

#5778 Reduce memory usage for new-state-mgmt at init sync
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/cache/hot_state_cache.go
  beacon-chain/cache/hot_state_cache_test.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/setter.go
Labels: OK to merge

#5742 Release enableCustomBlockHTR to all
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/core/helpers/signing_root_test.go
  beacon-chain/state/stateutil/blocks.go
  beacon-chain/state/stateutil/blocks_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#5786 Temporarily remove new state mgmt from e2e
  shared/featureconfig/flags.go
Labels: OK to merge

#5788 Make IP Static for Public IPs
  beacon-chain/p2p/discovery.go
Labels: OK to merge, Ready For Review

#5785 Refactor ReceiveBlock to receive the block root.
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/subscriber_beacon_blocks.go
Labels: OK to merge, Ready For Review

#5789 Duplicate init sync test target for better coverage reporting
  beacon-chain/sync/initial-sync/BUILD.bazel
Labels: OK to merge, Ready For Review

#5782 Gate disable lookback behind featureflag
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  slasher/detection/attestations/BUILD.bazel
  slasher/detection/attestations/spanner.go
Labels: OK to merge

#5792 Remove ETH1 Data Vote Cache
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/eth1_data.go
  beacon-chain/cache/eth1_data_test.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/state/transition.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5791 Fix test setup and change participation min back to 100%
  endtoend/components/beacon_node.go
  endtoend/evaluators/metrics.go
  endtoend/evaluators/validator.go
  endtoend/long_minimal_e2e_test.go
  endtoend/minimal_antiflake_e2e_1_test.go
  endtoend/minimal_antiflake_e2e_2_test.go
  endtoend/minimal_e2e_test.go
  endtoend/minimal_slashing_e2e_test.go
  endtoend/params/params.go
Labels: Ready For Review

#5794 Add Ability to Restrict Outbound Dials
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/options_test.go
  beacon-chain/usage.go
  shared/cmd/flags.go
Labels: OK to merge, Ready For Review

#5800 Moves connectPeers to common test setup file
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: OK to merge, Ready For Review

#5795 `GetValidatorPerformance` return `Unavailable` when syncing
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/service.go
Labels: Ready For Review

#5802 Check for pending deposits and exit early, if possible
  beacon-chain/rpc/validator/proposer.go
Labels: OK to merge

#5803 No magic number for `BlockBodyRoot`
  beacon-chain/state/stateutil/blocks.go
Labels: Ready For Review

#5799 Fix Issues With Peer Handshakes
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/fork.go
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/monitoring.go
  beacon-chain/sync/rpc_goodbye.go
Labels: Ready For Review

#5810 Check for Zero Value
  beacon-chain/p2p/handshake.go
Labels: Ready For Review

#5697 Add Docker Image for Genesis State Generator
  tools/genesis-state-gen/BUILD.bazel
Labels: OK to merge, Ready For Review

#5813 Reduce state copies for `SubmitAggregateSelectionProof`
  beacon-chain/rpc/validator/aggregator.go
Labels: Enhancement, OK to merge, Ready For Review

#5815 Run `go fmt` in prysm
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
Labels: OK to merge, Ready For Review

#5817 Add fix for nil state in InitializeFromProto
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/state_trie.go
  beacon-chain/state/state_trie_test.go
Labels: OK to merge

#5818 Add attestation inclusion histogram
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/process_block.go
Labels: OK to merge

#5811 Validate Finalized Root in Status RPC Requests
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/finalized_block_roots_test.go
  beacon-chain/sync/error.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
Labels: Ready For Review

#5819 Add metric for reorg count
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/metrics.go
Labels: OK to merge

#5824 Removes deprecated flag from config
  shared/featureconfig/config.go
Labels: OK to merge, Ready For Review

#5825 Adds BlockBatchLimitBurstFactor flag
  beacon-chain/flags/base.go
  beacon-chain/flags/config.go
  beacon-chain/main.go
  beacon-chain/sync/service.go
  beacon-chain/usage.go
Labels: OK to merge, Ready For Review

#5828 Revert Change Added in #5811
  beacon-chain/sync/rpc_status.go
Labels: Ready For Review

#5832 Update spec tests to v0.11.2
  WORKSPACE
Labels: Ready For Review

#5831 Fix historical detection for the slasher
  beacon-chain/rpc/beacon/attestations.go
  slasher/beaconclient/receivers.go
  slasher/detection/service.go
Labels: OK to merge, Ready For Review

#5834 Add fast function for comparing attestation data
  beacon-chain/core/blocks/block_operations.go
  shared/attestationutil/BUILD.bazel
  shared/attestationutil/attestation_utils.go
  shared/attestationutil/attestation_utils_test.go
  slasher/detection/BUILD.bazel
  slasher/detection/detect.go
Labels: Ready For Review

#5764 Use A Single State in Sync
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
Labels: Ready For Review

#5821 Properly Divide SecondsPerSlot Into Milliseconds
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/service.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_blocks_queue.go
  endtoend/BUILD.bazel
  endtoend/endtoend_test.go
  shared/slotutil/slottime.go
  validator/client/BUILD.bazel
  validator/client/validator.go
  validator/client/validator_aggregate.go
  validator/client/validator_aggregate_test.go
  validator/client/validator_attest.go
Labels: Priority: High, Ready For Review

#5835 Move cheaper operations earlier into detection code path
  slasher/detection/detect.go
Labels: Ready For Review

#5809 Stream p2p agg attestation
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
Labels: Ready For Review

#5841 Remove extra committee shuffling for initial syncing
  beacon-chain/core/helpers/committee.go
Labels: Enhancement, Ready For Review

#5833 Delay atts until subsequent slot
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review

#5845 Regen historical using `ArchivedPointRoot` then `State`
  beacon-chain/db/kv/regen_historical_states.go
Labels: OK to merge, Ready For Review

#5846 Ensure proper block slot for process block header
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
Labels: OK to merge, Ready For Review

#5847 Allow a Larger Allowance for Peer Faults
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_status.go
Labels: OK to merge, Ready For Review

#5853 Fixes bug with excessive rate limiting
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/sync_test.go
Labels: OK to merge, Ready For Review

#5850 Check Whether Block Is Already Processed
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
Labels: OK to merge, Ready For Review

#5852 Return Status And Goodbye for Different Fork Digests
  beacon-chain/sync/error.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_goodbye_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
Labels: Ready For Review

#5856 Revert "Check Whether Block Is Already Processed"
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
Labels: OK to merge

#5848 Validate slashings upon pool exit
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/log.go
  beacon-chain/operations/slashings/service.go
  beacon-chain/operations/slashings/service_attester_test.go
  beacon-chain/operations/slashings/service_proposer_test.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/sync/subscriber_test.go
  slasher/beaconclient/receivers.go
Labels: OK to merge, Ready For Review

#5820 Add testing for EnableFieldTrie in state_trie.go
  beacon-chain/state/state_trie_test.go
Labels: OK to merge, Ready For Review

#5858 Fix state gen migration
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/migrate_test.go
Labels: Bug, OK to merge, Ready For Review

#5687 Update GetValidatorPerformance to support validator indices
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge

#5859 Remove out of date scripts and fix mockgen script
  beacon-chain/blockchain/metrics.go
  beacon-chain/state/stateutil/blocks_test.go
  scripts/deploy-deposit-contract.sh
  scripts/setup-8-validators.sh
  scripts/start-beacon-chain.sh
  scripts/start-single-validator.sh
  scripts/update-go-pbs.sh
  scripts/update-mockgen.sh
  shared/cmd/helpers_test.go
Labels: Ready For Review

#5860 Refactors redundant global variables from sync
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/sync/sync_test.go
Labels: OK to merge, Ready For Review

#5849 Fix Stream Duties Server + Get Duties Before ChainStart
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/rpc_status.go
Labels: Ready For Review

#5863 More Handshake Cleanup
  beacon-chain/sync/rpc_status.go
Labels: Ready For Review

#5862 Unify generated mocks into shared/mock
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/testing/BUILD.bazel
  beacon-chain/rpc/testing/beacon_chain_service_mock.go
  beacon-chain/rpc/testing/doc.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/server_test.go
  scripts/update-mockgen.sh
  shared/mock/BUILD.bazel
  shared/mock/beacon_chain_service_mock.go
  shared/mock/beacon_service_mock.go
  shared/mock/beacon_validator_client_mock.go
  shared/mock/beacon_validator_server_mock.go
  shared/mock/node_service_mock.go
  validator/client/BUILD.bazel
  validator/client/validator_propose_test.go
  validator/client/validator_test.go
  validator/internal/BUILD.bazel
  validator/internal/README.md
  validator/internal/node_mock.go
Labels: Ready For Review

#5871 Add `skip-regen-historical-states` flag
  beacon-chain/blockchain/service.go
  beacon-chain/node/node.go
  beacon-chain/state/stategen/service.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Enhancement, Ready For Review

#5872 Add Suggestion to Paste in Deposit Data into Prylabs/Participate
  validator/accounts/account.go
Labels: OK to merge, Ready For Review

#5866 Adds rate limiting tests to beaconBlocksByRangeRPCHandler
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/rpc_test.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
Labels: OK to merge, Ready For Review

#5873 Add RPC Debug Server, Toggle Logging via gRPC
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/debug/BUILD.bazel
  beacon-chain/rpc/debug/server.go
  beacon-chain/rpc/debug/state.go
  beacon-chain/rpc/debug/state_test.go
  beacon-chain/rpc/service.go
  proto/beacon/rpc/v1/BUILD.bazel
  proto/beacon/rpc/v1/debug.proto
Labels: API, Enhancement, OK to merge, Ready For Review

#5876 Revert "Add cache to Eth1 RPC functions (#5347)"
  beacon-chain/powchain/block_reader.go
  beacon-chain/powchain/block_reader_test.go
Labels: OK to merge, Priority: High, Ready For Review

#5880 Enhancing block tree viewer
  beacon-chain/blockchain/info.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/no_vote_test.go
  beacon-chain/forkchoice/protoarray/nodes.go
  beacon-chain/forkchoice/protoarray/nodes_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/forkchoice/protoarray/vote_test.go
Labels: Enhancement, Ready For Review

#5881 Optimizes FSM event triggering
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/fsm.go
  beacon-chain/sync/initial-sync/fsm_benchmark_test.go
  beacon-chain/sync/initial-sync/fsm_test.go
Labels: OK to merge, Ready For Review

#5884 More Verbose Logs for Incoming Blocks
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/receivers.go
Labels: OK to merge, Ready For Review, Slasher

#5888 Make `SlotsPerArchivedPoint` configurable
  beacon-chain/flags/base.go
  beacon-chain/node/node.go
  beacon-chain/usage.go
  shared/params/config.go
Labels: Ready For Review

#5891 Shift To Debug Logs
  beacon-chain/sync/deadlines.go
  beacon-chain/sync/rpc_ping.go
Labels: Ready For Review

#5892 Remove DB check for receiving p2p slashings
  beacon-chain/sync/subscriber_handlers.go
  beacon-chain/sync/subscriber_test.go
Labels: OK to merge, Ready For Review

#5893 Fix Slashing Metrics
  beacon-chain/operations/slashings/service.go
Labels: Ready For Review

#5894 Sort Blocks Before Returning them To Peer
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/utils.go
  beacon-chain/sync/utils_test.go
Labels: OK to merge, Ready For Review

#5877 Fix silent internet error in prysm.sh
  prysm.bat
  prysm.sh
Labels: OK to merge, Ready For Review

#5887 Implements WRR in init-sync, full bandwidth utilization
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5899 Handle missing archived index
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: OK to merge, Ready For Review

#5842 Prevent parent block with same slot
  README.md
  WORKSPACE
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
Labels: OK to merge, Ready For Review

#5869 Change validator password
  validator/accounts/account.go
  validator/accounts/account_test.go
  validator/keymanager/BUILD.bazel
  validator/keymanager/direct_keystore.go
  validator/main.go
Labels: OK to merge

#5879 Allow wallet passphrases to be environment variables
  validator/keymanager/wallet.go
  validator/keymanager/wallet_test.go
Labels: OK to merge

#5886 Optimize slasher handling of duplicate attestations
  beacon-chain/rpc/beacon/attestations.go
  slasher/detection/BUILD.bazel
  slasher/detection/detect.go
  slasher/detection/detect_test.go
Labels: Ready For Review

#5784 Command to fetch validator statuses + MultipleValidatorStatus
  WORKSPACE
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/rpc/validator/status_test.go
  shared/mock/beacon_validator_client_mock.go
  shared/mock/beacon_validator_server_mock.go
  validator/BUILD.bazel
  validator/accounts/BUILD.bazel
  validator/accounts/account.go
  validator/accounts/status.go
  validator/accounts/status_test.go
  validator/client/service.go
  validator/main.go
  validator/node/node.go
Labels: OK to merge

#5904 Enable validator account metrics by default
  shared/featureconfig/flags.go
  validator/flags/flags.go
  validator/main.go
  validator/node/node.go
  validator/usage.go
Labels: Ready For Review

#5903 Filter inactive penalties processing by slashed
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
Labels: Ready For Review, v0.12

#5909 Fix proposer reward calculation for slashed attested
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
Labels: OK to merge, Ready For Review, v0.12

#5908 Fix prysm.bat internet warning
  prysm.bat
Labels: OK to merge

#5906 Re-arranges fetcher locks -> per peer level
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
Labels: OK to merge, Ready For Review

#5913 Ensure We Use Request.Epoch in the Validator Duties Server Implementation
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
Labels: Bug, OK to merge, Priority: Critical, Ready For Review

#5916 Add rewards penalties minimal spec tests
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/epoch/spectest/rewards_and_penalties_minimal_test.go
  beacon-chain/core/epoch/spectest/rewards_and_penalties_test.go
Labels: v0.12

#5917 Change To Debug Logs
  beacon-chain/p2p/service.go
Labels: OK to merge, Ready For Review

#5910 Add Schlesi Fork Regression Test
  beacon-chain/core/state/interop_regression_test.go
  beacon-chain/core/state/regression_files/schlesi_lighthouse_block.ssz
  beacon-chain/core/state/regression_files/schlesi_lighthouse_pre_state.ssz
  beacon-chain/core/state/regression_files/schlesi_pyspec_post_state.ssz
Labels: OK to merge, Ready For Review, Testnet, v0.12

#5895 External slashing protection
  beacon-chain/flags/base.go
  beacon-chain/rpc/validator/status_test.go
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/sync/subscriber_beacon_blocks.go
  fuzz/testing/beacon_fuzz_states.go
  nogo_config.json
  shared/blockutil/BUILD.bazel
  shared/blockutil/block_utils.go
  shared/cmd/helpers_test.go
  shared/cmd/password_reader.go
  shared/cmd/password_reader_mock.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/grpcutils/BUILD.bazel
  shared/grpcutils/grpcutils.go
  slasher/detection/BUILD.bazel
  slasher/detection/listeners.go
  slasher/flags/flags.go
  slasher/main.go
  slasher/node/node.go
  slasher/rpc/server.go
  slasher/rpc/service.go
  slasher/usage.go
  validator/client/BUILD.bazel
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_attest.go
  validator/client/validator_propose.go
  validator/flags/flags.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/slashing-protection/BUILD.bazel
  validator/slashing-protection/external.go
  validator/slashing-protection/external_test.go
  validator/slashing-protection/protector.go
  validator/slashing-protection/slasher_client.go
  validator/usage.go
Labels: Ready For Review

#5923 Log Active Validator Count
  beacon-chain/powchain/log_processing.go
Labels: OK to merge, Ready For Review

#5928 Fix Flags in Create Subcommand
  validator/main.go
Labels: OK to merge, Ready For Review

#5931 Enable domain data cache by default
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5932 Blockchain service provides `IsCanonical` getter
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/helpers.go
  beacon-chain/forkchoice/protoarray/nodes.go
  beacon-chain/forkchoice/protoarray/nodes_test.go
  beacon-chain/forkchoice/protoarray/types.go
Labels: Enhancement, OK to merge, Ready For Review

#5930 Change ListIndexedAttestations to be more slasher friendly
  beacon-chain/rpc/beacon/attestations.go
  slasher/beaconclient/chain_data.go
  slasher/beaconclient/historical_data_retrieval.go
  slasher/detection/service.go
Labels: OK to merge, Ready For Review

#5927 Fix slasher pool to not ignore valid slashings
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/service.go
  beacon-chain/operations/slashings/service_attester_test.go
Labels: OK to merge, Ready For Review

#5934 Return err instead of 0 for unavailable participation
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: Ready For Review

#5926 Add Debug Block Endpoint + Return SSZ-Encoded
  beacon-chain/rpc/debug/BUILD.bazel
  beacon-chain/rpc/debug/block.go
  beacon-chain/rpc/debug/block_test.go
  beacon-chain/rpc/debug/server.go
  beacon-chain/rpc/debug/state.go
  beacon-chain/rpc/debug/state_test.go
  proto/beacon/rpc/v1/debug.proto
Labels: API, Ready For Review

#5936 Add Slasher double block detection to E2E
  beacon-chain/rpc/validator/proposer.go
  endtoend/evaluators/slashing.go
  endtoend/minimal_slashing_e2e_test.go
  endtoend/types/types.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5939 Skip spec tests until v0.12 changes are complete
  beacon-chain/core/blocks/spectest/attestation_test.go
  beacon-chain/core/blocks/spectest/attester_slashing_test.go
  beacon-chain/core/blocks/spectest/block_header_test.go
  beacon-chain/core/blocks/spectest/block_processing_test.go
  beacon-chain/core/blocks/spectest/deposit_test.go
  beacon-chain/core/blocks/spectest/proposer_slashing_test.go
  beacon-chain/core/blocks/spectest/voluntary_exit_test.go
  beacon-chain/core/epoch/spectest/final_updates_test.go
  beacon-chain/core/epoch/spectest/justification_and_finalization_test.go
  beacon-chain/core/epoch/spectest/registry_test.go
  beacon-chain/core/epoch/spectest/rewards_and_penalties_test.go
  beacon-chain/core/epoch/spectest/slashings_test.go
  beacon-chain/core/helpers/spectest/shuffle_yaml_test.go
  beacon-chain/core/state/spectest/slot_processing_test.go
Labels: Ready For Review

#5938 Rename PersistentCommitteePeriod to ShardCommitteePeriod and update config
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/sync/validate_voluntary_exit_test.go
  shared/benchutil/pregen.go
  shared/params/config.go
  shared/testutil/block_test.go
Labels: Ready For Review

#5948 Remove redundant check in future target epoch time
  beacon-chain/blockchain/process_attestation.go
Labels: Ready For Review, v0.12

#5950 Recover skipped archived point
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/migrate_test.go
  shared/cmd/flags.go
Labels: Enhancement, Ready For Review

#5951 Remove Byte Mempool
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/field_trie.go
  beacon-chain/state/getters.go
  beacon-chain/state/setters.go
  beacon-chain/state/state_trie.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/memorypool/BUILD.bazel
  shared/memorypool/memorypool.go
  shared/memorypool/memorypool_test.go
Labels: Ready For Review

#5947 Ensure FFG and LMD votes are consistent
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_attestation_test.go
Labels: Ready For Review, v0.12

#5944 Make ETH1Data Determination More Strict
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
Labels: OK to merge, Ready For Review, v0.12

#5941 Adhere to ETH1 Follow Distance
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/rpc/validator/status.go
  shared/params/config.go
Labels: OK to merge, Ready For Review, v0.12

#5949 Enforce Non-Empty Attestation Indices
  shared/attestationutil/BUILD.bazel
  shared/attestationutil/attestation_utils.go
  shared/attestationutil/attestation_utils_test.go
Labels: v0.12

#5940 Handles issue with empty dirs on validator accounts create
  validator/accounts/account.go
  validator/accounts/account_test.go
  validator/keymanager/direct_keystore.go
Labels: OK to merge, Ready For Review

#5954 Only log attester slashing found for valid slashings
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/submit.go
  slasher/beaconclient/submit_test.go
  slasher/detection/service.go
Labels: Ready For Review
