Repository OffchainLabs/prysm, pull requests merged in 2020-02, with the labels that each got.

#4701 Ensure exits are not for an already exited validator
  beacon-chain/operations/voluntaryexits/BUILD.bazel
  beacon-chain/operations/voluntaryexits/service.go
  beacon-chain/operations/voluntaryexits/service_test.go
  beacon-chain/rpc/validator/exit.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/sync/subscriber_handlers.go
Labels: OK to merge

#4699 Beacon state: copy on write for certain large fields
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/getters.go
  beacon-chain/state/setters.go
  beacon-chain/state/types.go
  beacon-chain/state/types_test.go
Labels: Ready For Review

#4707 Pruning old states: Use a warning level log instead of fatal
  beacon-chain/blockchain/service.go
Labels: Bug, OK to merge, Priority: High, Ready For Review

#4709 Pending blocks queue: Better locking priority
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
Labels: Enhancement, OK to merge, Ready For Review

#4710 Use sync.pool for keccak256 and sha256
  shared/hashutil/hash.go
  shared/hashutil/hash_test.go
Labels: Ready For Review

#4712 Better eth1data equals
  beacon-chain/core/blocks/block_operations.go
Labels: Enhancement, OK to merge, Ready For Review

#4713 BeaconState: Use copy on write for validator index map
  beacon-chain/state/getters.go
  beacon-chain/state/setters.go
  beacon-chain/state/types.go
Labels: Enhancement, OK to merge, Ready For Review

#4705 Handle attestations with missing block
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/node/server.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/metrics.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
Labels: Enhancement, OK to merge, Priority: High, Ready For Review

#4714 Propagate blocks again after we process it in pending blocks queue
  beacon-chain/sync/pending_blocks_queue.go
Labels: OK to merge, Ready For Review

#4711 Custom Copy of Pending Attestations
  beacon-chain/core/state/transition_test.go
  beacon-chain/state/getters.go
Labels: OK to merge, Ready For Review

#4715 Copy head state to ensure it is never mutated
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/service_test.go
Labels: OK to merge, Ready For Review

#4716 Minor fixes
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/service.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/cache/checkpoint_state.go
  beacon-chain/cache/checkpoint_state_test.go
Labels: OK to merge, Ready For Review

#4719 Only update committee cache if it doesn't have that key already
  beacon-chain/core/helpers/committee.go
Labels: Enhancement, OK to merge, Ready For Review

#4721 Pubsub: Ignore block already in database
  beacon-chain/sync/subscriber_beacon_blocks.go
Labels: OK to merge, Ready For Review

#4722 Fork choice: only update head if the new block is a higher block slot
  beacon-chain/blockchain/receive_block.go
Labels: Enhancement, OK to merge, Ready For Review

#4725 Relegate some p2p messages
  beacon-chain/p2p/handshake.go
Labels: OK to merge

#4717 Release Proposer Index Cache
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/state/benchmarks_test.go
  beacon-chain/powchain/service.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#4674 Add get slashing endpoints
  proto/beacon/rpc/v1_gateway/BUILD.bazel
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/slashing/slashing.pb.go
  proto/slashing/slashing.proto
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/server_test.go
Labels: OK to merge, Ready For Review

#4728 Insert block to fork choice after saving the block to DB
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/state/types.go
Labels: OK to merge, Ready For Review

#4732 SSZ state cache: Only use cached value when flag is on
  shared/stateutil/state_root.go
Labels: OK to merge

#4731 Better log for `Requesting block for pending attestation...`
  beacon-chain/sync/pending_attestations_queue.go
Labels: OK to merge

#4733 Better state locking
  beacon-chain/state/getters.go
  beacon-chain/state/setters.go
  beacon-chain/state/types.go
Labels: Ready For Review

#4735 Beacon State: Ensure all fields are dirty on initialization
  beacon-chain/state/types.go
Labels: Ready For Review

#4737 Increase BLS pubkey cache to 100k from 10k
  shared/bls/bls.go
Labels: OK to merge

#4595 Add Endpoint to Return Current Chain Config Parameters
  WORKSPACE
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/config.go
  beacon-chain/rpc/beacon/config_test.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
Labels: API, OK to merge

#4743 Resolve Miscellaneous Bugs in Beacon Node
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/powchain/service.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/sync/rpc.go
  tools/bootnode/bootnode.go
Labels: Enhancement, Ready For Review

#4744 Misc fork choice improvements
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/receive_block.go
Labels: OK to merge

#4698 Cleanup slasher codebase
  slasher/db/attester_slashings.go
  slasher/db/block_header.go
  slasher/db/block_header_test.go
  slasher/db/indexed_attestations.go
  slasher/db/indexed_attestations_test.go
  slasher/db/min_max_span.go
  slasher/db/min_max_span_test.go
  slasher/db/proposer_slashings.go
  slasher/db/proposer_slashings_test.go
  slasher/rpc/detect_update_min_max_span.go
  slasher/rpc/server.go
  slasher/service/data_update.go
  slasher/service/service.go
Labels: OK to merge

#4745 Update dependencies from renovate
  WORKSPACE
Labels: Priority: Medium

#4747 Update blockchain metrics
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/forkchoice/BUILD.bazel
  beacon-chain/blockchain/forkchoice/metrics.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/metrics/BUILD.bazel
  beacon-chain/blockchain/metrics/metrics.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_block.go
Labels: OK to merge, Ready For Review

#4748 Render blocktree graph in page
  beacon-chain/blockchain/info.go
Labels: Enhancement, Ready For Review

#4749 Don't insert head to proto array DAG as index 0
  beacon-chain/blockchain/service.go
Labels: Bug, Forkchoice

#4752 RPC: Use the proper db access level, use head root from head fetcher
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/server.go
Labels: OK to merge, Ready For Review

#4746 Update All Libp2p Dependencies
  WORKSPACE
  beacon-chain/p2p/addr_factory_test.go
Labels: OK to merge

#4750 Insert initial sync missing blocks to fork choice store
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/store.go
Labels: Enhancement, Forkchoice, OK to merge

#4754 Update head slot metric after compute head
  beacon-chain/blockchain/receive_block.go
Labels: Bug, Forkchoice, OK to merge

#4570 Sync to highest possible head given the peers available
  beacon-chain/sync/initial-sync/round_robin.go
Labels: Ready For Review

#4758 DB: Do not allow attempts to save a nil state
  beacon-chain/db/kv/state.go
Labels: Bug, Priority: High, Ready For Review

#4761 Update higherThanFinalized in the loop
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: Bug, Forkchoice, OK to merge

#4764 Block tree enhancements
  beacon-chain/blockchain/info.go
Labels: Enhancement, Forkchoice

#4759 Include Latest Ethereum APIs Definitions in Prysm
  WORKSPACE
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/testing/beacon_chain_service_mock.go
  shared/mock/BUILD.bazel
  shared/mock/beacon_chain_service_mock.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
Labels: API, OK to merge, Ready For Review

#4765 Add test for GetBlock
  beacon-chain/rpc/validator/proposer_test.go
Labels: OK to merge, Ready For Review

#4766 Add & use FinalizedCheckpointEpoch() to state
  beacon-chain/blockchain/forkchoice/log.go
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/metrics/metrics.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/state/benchmarks_test.go
  beacon-chain/core/state/state_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/state/getters.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  shared/testutil/block_test.go
Labels: Enhancement, OK to merge, Ready For Review

#4751 Beacon State: Track field references
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/checkpoint_state.go
  beacon-chain/cache/checkpoint_state_test.go
  beacon-chain/cache/skip_slot_cache_test.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/references_test.go
  beacon-chain/state/setters.go
  beacon-chain/state/types.go
Labels: OK to merge, Ready For Review

#4768 Fix block tree cosmetic bugs
  beacon-chain/blockchain/info.go
Labels: Enhancement, OK to merge

#4753 Attestation Verification Improvements
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/aggregate_test.go
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/block.go
  beacon-chain/operations/attestations/kv/forkchoice.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/state/getters.go
Labels: OK to merge, Ready For Review

#4774 Disable forkchoice pre-processing of attestations
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/aggregate_test.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Enhancement, OK to merge, Ready For Review

#4775 Remove All Batch DB Calls
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/blocks.go
Labels: OK to merge, Ready For Review

#4776 Save attestation to DB gated by archival flag
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/state/references_test.go
Labels: Enhancement, OK to merge

#4769 Use balancesLength and randaoMixesLength to save copy on read
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/state/getters.go
Labels: Ready For Review

#4779 Log a warning if attempting to save a nil state
  beacon-chain/blockchain/process_block_helpers.go
Labels: Bug, OK to merge, Ready For Review

#4770 Faster BLS publickey.Copy
  shared/bls/bls.go
  shared/bls/bls_test.go
Labels: OK to merge, Ready For Review

#4780 Add `forkchoiceAggregateAttestations` to flag list
  shared/featureconfig/flags.go
Labels: Bug, OK to merge

#4778 Use proto array forkchoice as default
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/forkchoice/BUILD.bazel
  beacon-chain/blockchain/forkchoice/benchmark_test.go
  beacon-chain/blockchain/forkchoice/doc.go
  beacon-chain/blockchain/forkchoice/lmd_ghost_test.yaml
  beacon-chain/blockchain/forkchoice/lmd_ghost_yaml_test.go
  beacon-chain/blockchain/forkchoice/log.go
  beacon-chain/blockchain/forkchoice/process_attestation.go
  beacon-chain/blockchain/forkchoice/process_attestation_test.go
  beacon-chain/blockchain/forkchoice/process_block.go
  beacon-chain/blockchain/forkchoice/process_block_test.go
  beacon-chain/blockchain/forkchoice/service.go
  beacon-chain/blockchain/forkchoice/service_test.go
  beacon-chain/blockchain/forkchoice/tree_test.go
  beacon-chain/blockchain/info.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/operations/attestations/aggregate_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Enhancement, Forkchoice

#4736 Fix(Genesis): Api genesis block now returns properly
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
Labels: OK to merge

#4784 Rlock for computing head
  beacon-chain/forkchoice/protoarray/store.go
  shared/bls/bls_test.go
Labels: Bug, Forkchoice, OK to merge

#4771 Stream Blocks Functionality for RPC
  beacon-chain/blockchain/testing/BUILD.bazel
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/core/feed/block/BUILD.bazel
  beacon-chain/core/feed/block/events.go
  beacon-chain/core/feed/block/notifier.go
  beacon-chain/node/node.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
Labels: API, OK to merge, Ready For Review

#4785 BeaconState: remaining shared reference fields with conditional copy on write
  beacon-chain/state/setters.go
  beacon-chain/state/types.go
Labels: Enhancement, OK to merge, Ready For Review

#4726 Slashing operations pool
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/doc.go
  beacon-chain/operations/slashings/service.go
  beacon-chain/operations/slashings/service_attester_test.go
  beacon-chain/operations/slashings/service_proposer_test.go
  beacon-chain/operations/slashings/types.go
Labels: Ready For Review

#4782 Strict verify attestations in pubsub
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/state/setters.go
  beacon-chain/state/types.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/subscriber_committee_index_beacon_attestation.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Enhancement, OK to merge, Ready For Review

#4789 Update Slices More Efficiently
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/state/setters.go
  beacon-chain/sync/initial-sync/service.go
Labels: Ready For Review

#4790 Revert "Update Slices More Efficiently"
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/state/setters.go
  beacon-chain/sync/initial-sync/service.go
Labels: OK to merge

#4767 Fix Dynamic Topic Subscriptions
  beacon-chain/sync/subscriber.go
Labels: Ready For Review

#4786 Update head on per attestation and minor refactor clean ups
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_norace_test.go
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/no_vote_test.go
  beacon-chain/forkchoice/protoarray/nodes.go
  beacon-chain/forkchoice/protoarray/store.go
Labels: Enhancement, Forkchoice, OK to merge, Ready For Review

#4796 Report unhealthy if we think we are out of sync
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/sync/service.go
Labels: Enhancement, OK to merge, Ready For Review

#4799 Don't save nil head state
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/head.go
Labels: Enhancement, OK to merge

#4798 Delete block attestations from the pool
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  shared/featureconfig/flags.go
Labels: Enhancement, Ready For Review

#4803 Prevent panic on wrong interface conversion
  beacon-chain/sync/rpc_goodbye.go
Labels: Bug, OK to merge, Ready For Review

#4800 Handle head state for init sync cache state
  beacon-chain/blockchain/head.go
Labels: Enhancement, OK to merge, Ready For Review

#4802 Feature flag to disable head update on attestation basis
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/sync/rpc_goodbye.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Enhancement, Forkchoice

#4808 Removed spans for fork choice helpers
  beacon-chain/forkchoice/protoarray/nodes.go
  beacon-chain/forkchoice/protoarray/nodes_test.go
Labels: Forkchoice, OK to merge, Ready For Review

#4797 Slasher proto and function renames
  proto/slashing/slashing.pb.go
  proto/slashing/slashing.proto
  slasher/db/block_header.go
  slasher/db/block_header_test.go
  slasher/db/db.go
  slasher/db/indexed_attestations.go
  slasher/db/schema.go
  slasher/rpc/server.go
  slasher/service/BUILD.bazel
  slasher/service/data_update.go
  slasher/service/service.go
  validator/db/db.go
Labels: OK to merge

#4811 Optimize Copying of Fields
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/setters.go
  beacon-chain/state/types.go
  shared/memorypool/BUILD.bazel
  shared/memorypool/memorypool.go
  shared/memorypool/memorypool_test.go
Labels: Ready For Review

#4791 Update attester wait time
  beacon-chain/blockchain/receive_block.go
  beacon-chain/core/feed/state/events.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/server.go
  validator/client/validator_attest.go
  validator/client/validator_attest_test.go
Labels: Enhancement, OK to merge, Ready For Review

#4818 Increase check point state cache size to 10
  beacon-chain/cache/checkpoint_state.go
Labels: OK to merge

#4817 Clear initial sync state caches after round robin sync
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/service.go
Labels: OK to merge, Ready For Review

#4819 Expose fork choice `node`
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/helpers.go
  beacon-chain/forkchoice/protoarray/store.go
Labels: Enhancement, Ready For Review

#4820 Release flag to aggregate attestations in fork choice.
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/aggregate_test.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#4812 Slasher committees cache
  beacon-chain/rpc/testing/beacon_chain_service_mock.go
  shared/mock/beacon_chain_service_mock.go
  slasher/cache/BUILD.bazel
  slasher/cache/committees_cache.go
  slasher/cache/committees_cache_test.go
  slasher/service/BUILD.bazel
  slasher/service/data_update.go
  slasher/service/service.go
Labels: OK to merge, Ready For Review

#4821 Optimize `Hasblock`
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: Enhancement

#4822 Add nil check to peers status
  beacon-chain/p2p/peers/status.go
Labels: OK to merge, Ready For Review

#4824 Add mempool feature flag
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/memorypool/BUILD.bazel
  shared/memorypool/memorypool.go
Labels: Enhancement, OK to merge, Priority: Critical, Ready For Review

#4825 Revert state copy PR #4811
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/setters.go
  beacon-chain/state/types.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/memorypool/BUILD.bazel
  shared/memorypool/memorypool.go
  shared/memorypool/memorypool_test.go
Labels: OK to merge, Ready For Review

#4831 Fix Goodbye RPC handler
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_goodbye_test.go
Labels: Ready For Review

#4830 Check HeadState First
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block_helpers.go
Labels: OK to merge, Ready For Review

#4827 Add Paginated Attestation Pool to Prysm
  WORKSPACE
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  shared/mock/beacon_chain_service_mock.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
Labels: API, Enhancement, Ready For Review

#4833 Add Lock to Processing Pending Attestations
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
Labels: Bug, OK to merge, Ready For Review

#4835 Include Beacon Client Package in Slasher
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/receivers.go
  slasher/beaconclient/receivers_test.go
  slasher/beaconclient/service.go
Labels: Ready For Review

#4837 Improve attestation cache check from O(n) to O(1) access time
  beacon-chain/operations/attestations/kv/aggregated.go
Labels: OK to merge, Ready For Review

#4839 Fix Pending Attestation Queue Panic
  beacon-chain/sync/pending_attestations_queue.go
Labels: OK to merge, Ready For Review

#4840 Add Pending Attestation Lock fix
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/validate_aggregate_proof.go
Labels: Ready For Review

#4838 Better block attestation inclusion
  beacon-chain/operations/attestations/aggregate.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  shared/testutil/block.go
  tools/benchmark-files-gen/main.go
Labels: Ready For Review

#4845 Better attesting summary reporting
  WORKSPACE
  beacon-chain/core/state/transition.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/testing/beacon_chain_service_mock.go
  shared/featureconfig/flags.go
  shared/mock/beacon_chain_service_mock.go
  slasher/beaconclient/receivers_test.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
  validator/client/validator_metrics.go
Labels: Enhancement

#4847 Create backups without freelist.
  beacon-chain/db/kv/backup.go
Labels: OK to merge, Ready For Review

#4849 Secure lock when accessing the map only
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
Labels: Ready For Review

#4851 Revert "Check HeadState First"
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block_helpers.go
Labels: OK to merge

#4850 Change Positionining of Warning Log
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: OK to merge, Ready For Review

#4854 Beacon State: More consistent nil return for state
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/encoding.go
  beacon-chain/db/kv/encoding_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/state/getters.go
Labels: OK to merge, Ready For Review

#4806 Remove remaining instances of proto.clone()
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/checkpoint_state.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/attester.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/cloners.go
  beacon-chain/state/getters.go
  beacon-chain/state/setters.go
  shared/bytesutil/bytes.go
Labels: OK to merge, Ready For Review

#4858 Include Slashing Submission Endpoints + Slashing Pool in Beacon Node
  WORKSPACE
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/operations/slashings/service.go
  beacon-chain/operations/slashings/service_attester_test.go
  beacon-chain/operations/slashings/service_proposer_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/beacon/slashings.go
  beacon-chain/rpc/beacon/slashings_test.go
  beacon-chain/rpc/service.go
  shared/mock/beacon_chain_service_mock.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
Labels: API, Ready For Review

#4860 Change to Custom Hashing for BlockHeaders
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  shared/stateutil/blocks.go
Labels: OK to merge, Ready For Review

#4862 Copy Checkpoint Root Properly
  shared/stateutil/attestations.go
  shared/stateutil/blocks.go
  shared/stateutil/state_root.go
  shared/stateutil/validators.go
Labels: OK to merge

#4856 Implementing Slasher Node Runtime
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  slasher/BUILD.bazel
  slasher/beaconclient/receivers.go
  slasher/beaconclient/service.go
  slasher/main.go
  slasher/node/BUILD.bazel
  slasher/node/node.go
  slasher/node/node_test.go
  slasher/usage.go
Labels: OK to merge, Ready For Review

#4863 Dont Initialize Zeroed Out State
  beacon-chain/powchain/service.go
Labels: OK to merge, Ready For Review

#4865 Prevent balance goes out of bound
  validator/client/validator_metrics.go
Labels: OK to merge, Ready For Review

#4866 Send Slashing Objects to Beacon Node via RPC
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/service.go
  slasher/beaconclient/submit.go
  slasher/beaconclient/submit_test.go
  slasher/node/BUILD.bazel
  slasher/node/node.go
Labels: API, Ready For Review

#4867 Detection Service Creation
  slasher/beaconclient/receivers_test.go
  slasher/beaconclient/service.go
  slasher/beaconclient/submit.go
  slasher/detection/BUILD.bazel
  slasher/detection/attestations/BUILD.bazel
  slasher/detection/attestations/attestation_test.go
  slasher/detection/attestations/attestations.go
  slasher/detection/attestations/attestations_bench_test.go
  slasher/detection/listeners.go
  slasher/detection/listeners_test.go
  slasher/detection/service.go
  slasher/node/BUILD.bazel
  slasher/node/node.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
Labels: Ready For Review

#4870 Improve block descendant error log
  beacon-chain/blockchain/process_block_helpers.go
Labels: Enhancement, Ready For Review

#4869 Better `head` object coupling for chain service
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/info.go
  beacon-chain/blockchain/metrics/BUILD.bazel
  beacon-chain/blockchain/metrics/metrics.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_norace_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/node.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/beacon/slashings.go
  beacon-chain/rpc/beacon/slashings_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/service.go
  validator/client/validator_metrics.go
Labels: Enhancement, OK to merge, Ready For Review

#4873 Enable attestation cache flag by default, deprecate feature flag
  beacon-chain/cache/attestation_data.go
  beacon-chain/cache/feature_flag_test.go
  beacon-chain/core/state/benchmarks_test.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/attester_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#4871 Update README for Patching Ethereum APIs
  third_party/README.md
Labels: OK to merge

#4876 Check attestation bitlist length in aggregation to prevent panic
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
Labels: Ready For Review

#4823 fixed panic: runtime error: integer divide by zero #4777
  beacon-chain/sync/pending_attestations_queue.go
Labels: Ready For Review

#4881 Fix reply block edge cases and tests
  beacon-chain/stategen/BUILD.bazel
  beacon-chain/stategen/replay.go
  beacon-chain/stategen/replay_test.go
Labels: Enhancement, Ready For Review

#4888 Handle nil head block in cache
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/validator/server.go
Labels: Bug, Ready For Review

#4889 Replay block same slots different root edge case
  beacon-chain/stategen/replay.go
  beacon-chain/stategen/replay_test.go
Labels: Enhancement

#4892 Implement ListIndexedAttestations Endpoint in Prysm
  WORKSPACE
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
  shared/mock/beacon_chain_service_mock.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
Labels: API, Ready For Review

#4893 Define debug images for Prysm beacon chain and validator binaries
  beacon-chain/BUILD.bazel
  tools/BUILD.bazel
  tools/binary_targets.bzl
  validator/BUILD.bazel
Labels: CI, Enhancement, Ready For Review

#4895 Save Attestations In Initial Sync if Archive Enabled
  beacon-chain/blockchain/process_block.go
Labels: Enhancement, OK to merge, Ready For Review

#4897 Utilise a Flag to Toggle With the GC
  beacon-chain/flags/base.go
  beacon-chain/main.go
  beacon-chain/usage.go
Labels: OK to merge, Ready For Review

#4899 Only set gc percent if the flag is set
  beacon-chain/main.go
Labels: OK to merge, Ready For Review

#4883 fuzzing core/state package without skip slot cache
  beacon-chain/core/epoch/precompute/new.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
  beacon-chain/core/state/state_fuzz_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_fuzz_test.go
  beacon-chain/state/getters.go
  beacon-chain/state/setters.go
  beacon-chain/state/types.go
  shared/mock/beacon_chain_service_mock.go
Labels: Ready For Review

#4898 Export `LoadBlocks` and `ReplayBlocks`
  beacon-chain/stategen/replay.go
  beacon-chain/stategen/replay_test.go
Labels: Enhancement, Ready For Review

#4901 Enhance signature fails to verify message
  beacon-chain/blockchain/process_attestation_helpers.go
Labels: Enhancement, Ready For Review

#4844 Bound Initial Sync Cache Size
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/init_sync_process_block.go
  beacon-chain/blockchain/init_sync_process_block_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/state.go
  shared/bytesutil/bytes.go
  shared/bytesutil/bytes_test.go
Labels: Ready For Review

#4903 Add mempool feature flag
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/memorypool/BUILD.bazel
  shared/memorypool/memorypool.go
Labels: OK to merge

#4908 gRPC retry requests
  validator/client/BUILD.bazel
  validator/client/service.go
Labels: OK to merge, Ready For Review

#4909 Delete States More Efficiently
  beacon-chain/db/kv/state.go
Labels: OK to merge, Ready For Review

#4904 Handing pending atts if they dont have the state
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
Labels: Bug, Priority: Critical

#4911 Add a clarifying comment from #4909
  beacon-chain/db/kv/state.go
Labels: OK to merge, Ready For Review

#4894 Request All Indexed Attestations Since Genesis in Slasher on Startup
  beacon-chain/blockchain/process_block.go
  beacon-chain/rpc/beacon/blocks.go
  shared/mock/BUILD.bazel
  shared/mock/node_service_mock.go
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/chain_data.go
  slasher/beaconclient/chain_data_test.go
  slasher/beaconclient/historical_data_retrieval.go
  slasher/beaconclient/historical_data_retrieval_test.go
  slasher/beaconclient/receivers.go
  slasher/beaconclient/receivers_test.go
  slasher/beaconclient/service.go
  slasher/beaconclient/service_test.go
  slasher/beaconclient/submit.go
  slasher/beaconclient/submit_test.go
  slasher/db/iface/interface.go
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/chain_data.go
  slasher/db/kv/chain_data_test.go
  slasher/db/kv/kv.go
  slasher/db/kv/schema.go
  slasher/detection/BUILD.bazel
  slasher/detection/listeners.go
  slasher/detection/listeners_test.go
  slasher/detection/service.go
  slasher/node/node.go
Labels: Ready For Review

#4902 Add Slashings Into Blocks from Pool
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/server.go
  shared/testutil/BUILD.bazel
  shared/testutil/block.go
Labels: Ready For Review

#4922 Fix Fork Copying
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/getters.go
  beacon-chain/state/types_test.go
Labels: Ready For Review

#4921 Shift Stateutils to State Package
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/transition.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/arrays.go
  beacon-chain/state/stateutil/attestations.go
  beacon-chain/state/stateutil/blocks.go
  beacon-chain/state/stateutil/helpers.go
  beacon-chain/state/stateutil/state_root.go
  beacon-chain/state/stateutil/state_root_cache_fuzz_test.go
  beacon-chain/state/stateutil/state_root_test.go
  beacon-chain/state/stateutil/validators.go
  beacon-chain/state/types.go
  beacon-chain/state/types_test.go
  proto/testing/BUILD.bazel
  proto/testing/ssz_static_test.go
Labels: OK to merge

#4920 Define an Efficient Spanner Struct Implementation for Slasher
  slasher/detection/attestations/BUILD.bazel
  slasher/detection/attestations/spanner.go
  slasher/detection/attestations/spanner_test.go
Labels: Priority: High, Ready For Review

#4930 attestations in pool count metrics
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/aggregate.go
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/operations/attestations/metrics.go
  beacon-chain/operations/attestations/pool.go
  shared/featureconfig/flags.go
  slasher/beaconclient/historical_data_retrieval.go
  validator/client/service.go
Labels: Enhancement, OK to merge, Ready For Review

#4932 Fix aggregated attestation pool grows large in size
  beacon-chain/operations/attestations/aggregate.go
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/kv.go
Labels: Bug, Priority: High, Ready For Review

#4928 Consider missing validator count for performance metric
  validator/client/validator_metrics.go
Labels: Bug, OK to merge, Ready For Review

#4926 Add a configurable flag for gRPC retries
  validator/client/service.go
  validator/flags/flags.go
  validator/main.go
  validator/node/node.go
  validator/usage.go
Labels: OK to merge, Ready For Review

#4914 Validator: cache domain data calls
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/client/BUILD.bazel
  validator/client/fake_validator_test.go
  validator/client/grpc_interceptor.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_aggregate.go
  validator/client/validator_attest.go
  validator/client/validator_propose.go
Labels: Ready For Review

#4938 Release --initial-sync-cache-state
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Enhancement, Ready For Review

#4943 Replay blocks and generate state without sig verification
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_fuzz_test.go
  beacon-chain/stategen/BUILD.bazel
  beacon-chain/stategen/replay.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Enhancement, Ready For Review

#4941 Stream Indexed Attestations RPC Implementation
  beacon-chain/node/node.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/testing/beacon_chain_service_mock.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
Labels: API, OK to merge, Priority: High, Ready For Review

#4949 Clean up unused / deprecated protobuf definitions
  beacon-chain/rpc/testing/BUILD.bazel
  beacon-chain/rpc/testing/validator_service_mock.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/db/powchain.pb.go
  proto/beacon/p2p/v1/archive.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/services.proto
  proto/beacon/rpc/v1_gateway/BUILD.bazel
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/faucet/faucet.pb.go
  proto/testing/test.pb.go
  tools/cluster-pk-manager/server/BUILD.bazel
  tools/cluster-pk-manager/server/keyChecker.go
  validator/internal/BUILD.bazel
  validator/internal/validator_service_mock.go
Labels: OK to merge

#4950 Move stategen package under /state
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
  beacon-chain/state/stategen/service.go
Labels: OK to merge, Ready For Review

#4937 Plug-In Attester Slashing Detection Into Slasher Runtime
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/node/node.go
  beacon-chain/rpc/beacon/attestations.go
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/historical_data_retrieval.go
  slasher/beaconclient/historical_data_retrieval_test.go
  slasher/beaconclient/receivers.go
  slasher/beaconclient/receivers_test.go
  slasher/beaconclient/service.go
  slasher/db/iface/interface.go
  slasher/db/kv/indexed_attestations.go
  slasher/db/kv/kv.go
  slasher/db/kv/schema.go
  slasher/db/testing/BUILD.bazel
  slasher/db/testing/setup_db.go
  slasher/db/testing/setup_db_test.go
  slasher/detection/BUILD.bazel
  slasher/detection/attestations/BUILD.bazel
  slasher/detection/attestations/attestations_bench_test.go
  slasher/detection/attestations/attestations_test.go
  slasher/detection/attestations/mock_spanner.go
  slasher/detection/detect.go
  slasher/detection/detect_test.go
  slasher/detection/listeners.go
  slasher/detection/listeners_test.go
  slasher/detection/service.go
  slasher/node/node.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/server_test.go
Labels: Enhancement, Priority: High

#4959 Move blockchain service metrics package
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/metrics/BUILD.bazel
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_block.go
  tools/cluster-pk-manager/server/keyChecker.go
Labels: Enhancement, OK to merge, Ready For Review

#4951 Migrate SubmitAggregateAndProof
  WORKSPACE
  beacon-chain/rpc/aggregator/BUILD.bazel
  beacon-chain/rpc/aggregator/server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/aggregator.go
  beacon-chain/rpc/validator/aggregator_test.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_aggregate.go
  validator/client/validator_aggregate_test.go
  validator/client/validator_propose_test.go
  validator/internal/BUILD.bazel
  validator/internal/aggregator_service_mock.go
  validator/internal/beacon_node_validator_service_mock.go
Labels: OK to merge, Ready For Review

#4962 Removed duplicated SaveAttestations
  beacon-chain/blockchain/process_block.go
Labels: Enhancement, Ready For Review

#4963 Use correct image name for validator debug image
  validator/BUILD.bazel
Labels: OK to merge, Ready For Review
