Repository OffchainLabs/prysm, pull requests merged in 2020-03, with the labels that each got.

#4972 Check HeadState First
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block_helpers.go
Labels: Ready For Review

#4967 Define state summary proto
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/db/powchain.pb.go
  proto/beacon/p2p/v1/archive.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1/slasher.pb.go
  proto/beacon/rpc/v1_gateway/BUILD.bazel
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/beacon/rpc/v1_gateway/slasher.pb.go
Labels: Ready For Review, new-state-mgmt

#4971 State summary DB methods
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/state_summary.go
  beacon-chain/db/kv/state_summary_test.go
  validator/client/validator_propose_test.go
  validator/internal/beacon_node_validator_service_mock.go
Labels: OK to merge, Ready For Review, new-state-mgmt

#4974 Add Flag for Checking HeadState
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block_helpers.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge

#4977 Archived point index DB methods
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archived_point.go
  beacon-chain/db/kv/archived_point_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  validator/client/validator_propose_test.go
  validator/internal/beacon_node_validator_service_mock.go
Labels: Ready For Review, new-state-mgmt

#4968 Fix crash when reporting validator metrics
  validator/client/validator_metrics.go
Labels: OK to merge

#4966 Better logs for forking
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/receive_attestation.go
Labels: Enhancement, Ready For Review

#4991 Add Noise Support To Prysm
  WORKSPACE
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/options.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Networking, OK to merge, Ready For Review

#4960 Plug-in double voting detection into detection service
  beacon-chain/rpc/beacon/attestations.go
  slasher/beaconclient/historical_data_retrieval.go
  slasher/beaconclient/receivers.go
  slasher/db/iface/interface.go
  slasher/db/kv/indexed_attestations.go
  slasher/db/kv/indexed_attestations_test.go
  slasher/detection/BUILD.bazel
  slasher/detection/attestations/mock_spanner.go
  slasher/detection/detect.go
  slasher/detection/detect_test.go
  slasher/detection/listeners.go
  slasher/detection/listeners_test.go
  slasher/detection/service.go
  slasher/rpc/server_test.go
  slasher/service/service.go
Labels: OK to merge, Ready For Review

#4992 Update outdated spec function names and comments
  beacon-chain/archiver/service_test.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/validator/status_test.go
  shared/trieutil/sparse_merkle.go
  shared/trieutil/sparse_merkle_test.go
  tools/sendDepositTx/sendDeposits_test.go
Labels: OK to merge

#4993 Add epoch boundary root map
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/epoch_boundary_root.go
  beacon-chain/state/stategen/epoch_boundary_root_test.go
  beacon-chain/state/stategen/service.go
Labels: Ready For Review, new-state-mgmt

#4994 Remove Deprecated Slasher Code
  slasher/BUILD.bazel
  slasher/cache/BUILD.bazel
  slasher/cache/committees_cache.go
  slasher/cache/committees_cache_test.go
  slasher/service/BUILD.bazel
  slasher/service/data_update.go
  slasher/service/service.go
  slasher/service/service_test.go
Labels: OK to merge, Ready For Review

#4995 Stub Slasher RPC Methods
  proto/slashing/slashing.pb.go
  proto/slashing/slashing.proto
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/server_test.go
Labels: OK to merge

#4999 Add log file for stategen pkg
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/log.go
Labels: Ready For Review, new-state-mgmt

#5000 Add error definitions for state gen pkg
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/errors.go
Labels: OK to merge, Ready For Review, new-state-mgmt

#4978 init sync: adds blocks fetcher service
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
Labels: Ready For Review

#5003 Create .bazelversion
  .bazelversion
Labels: OK to merge, Ready For Review

#5004 LRU cache for state gen
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/hot_state_cache.go
  beacon-chain/cache/hot_state_cache_test.go
Labels: OK to merge, Ready For Review, new-state-mgmt

#4996 Remove unused DB functions and proto from Slasher
  proto/slashing/slashing.pb.go
  proto/slashing/slashing.proto
  slasher/db/iface/interface.go
  slasher/db/kv/indexed_attestations.go
  slasher/db/kv/indexed_attestations_test.go
Labels: OK to merge, Ready For Review

#5011 Feature flag to gate prune state upon start up
  beacon-chain/blockchain/service.go
  beacon-chain/state/stategen/log.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5010 Windows friendly stdin reads for passwords
  validator/accounts/account.go
  validator/keymanager/direct_keystore.go
Labels: OK to merge

#5012 Allow Peers to Also be Specified Using ENRs
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/service.go
Labels: Networking, Ready For Review

#5005 Methods to retrieves last saved state and block for stategen pkg
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
  beacon-chain/state/stategen/service.go
Labels: Ready For Review, new-state-mgmt

#4945 First cut at multi-arch cross compiling toolchain
  .bazelrc
  WORKSPACE
  third_party/kafka/BUILD.bazel
  tools/cross-toolchain/BUILD.bazel
  tools/cross-toolchain/Dockerfile
  tools/cross-toolchain/README.md
  tools/cross-toolchain/cc_toolchain.BUILD.bazel.tpl
  tools/cross-toolchain/cc_toolchain_config_linux_arm64.bzl.tpl
  tools/cross-toolchain/cc_toolchain_config_osx.bzl.tpl
  tools/cross-toolchain/cc_toolchain_config_windows.bzl.tpl
  tools/cross-toolchain/configs/.latest.bazelrc
  tools/cross-toolchain/configs/clang/bazel_2.1.1/cc/BUILD
  tools/cross-toolchain/configs/clang/bazel_2.1.1/cc/armeabi_cc_toolchain_config.bzl
  tools/cross-toolchain/configs/clang/bazel_2.1.1/cc/builtin_include_directory_paths
  tools/cross-toolchain/configs/clang/bazel_2.1.1/cc/cc_toolchain_config.bzl
  tools/cross-toolchain/configs/clang/bazel_2.1.1/cc/cc_wrapper.sh
  tools/cross-toolchain/configs/clang/bazel_2.1.1/config/BUILD
  tools/cross-toolchain/configs/clang/bazel_2.1.1/java/BUILD
  tools/cross-toolchain/configs/clang/bazel_2.1.1/prysm_toolchains/BUILD.bazel
  tools/cross-toolchain/configs/clang/bazel_2.1.1/prysm_toolchains/WORKSPACE
  tools/cross-toolchain/configs/clang/bazel_2.1.1/prysm_toolchains/cc_toolchain_config_linux_arm64.bzl
  tools/cross-toolchain/configs/clang/bazel_2.1.1/prysm_toolchains/cc_toolchain_config_osx.bzl
  tools/cross-toolchain/configs/clang/bazel_2.1.1/prysm_toolchains/cc_toolchain_config_windows.bzl
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/cc/BUILD
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/cc/armeabi_cc_toolchain_config.bzl
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/cc/builtin_include_directory_paths
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/cc/cc_toolchain_config.bzl
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/cc/cc_wrapper.sh
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/config/BUILD
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/java/BUILD
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/prysm_toolchains/BUILD.bazel
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/prysm_toolchains/WORKSPACE
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/prysm_toolchains/cc_toolchain_config_linux_arm64.bzl
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/prysm_toolchains/cc_toolchain_config_osx.bzl
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/prysm_toolchains/cc_toolchain_config_windows.bzl
  tools/cross-toolchain/configs/versions.bzl
  tools/cross-toolchain/empty.bzl
  tools/cross-toolchain/install_clang_cross10.sh
  tools/cross-toolchain/install_osxcross.sh
  tools/cross-toolchain/prysm_toolchains.bzl
  tools/cross-toolchain/rbe_toolchains_config.bzl
  tools/cross-toolchain/regenerate.sh
Labels: OK to merge, Ready For Review

#5009 Plugging in spanner db
  slasher/detection/attestations/BUILD.bazel
  slasher/detection/attestations/iface/iface.go
  slasher/detection/attestations/spanner.go
  slasher/detection/attestations/spanner_test.go
  slasher/detection/service.go
Labels: Ready For Review

#5016 Fixes race condition at genesis
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/service.go
Labels: Ready For Review

#5019 Cross-compile OSX: Remove dropbox link, add sha256 check
  WORKSPACE
  tools/cross-toolchain/configs/clang/bazel_2.1.1/config/BUILD
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/config/BUILD
  tools/cross-toolchain/configs/versions.bzl
  tools/cross-toolchain/install_osxcross.sh
  tools/cross-toolchain/rbe_toolchains_config.bzl
Labels: Ready For Review

#5018 Run buildifer, remove duplicated WORKSPACE entries
  .bazelrc
  .buildkite-bazelrc
  WORKSPACE
  bazel.sh
  beacon-chain/core/helpers/BUILD.bazel
  proto/slashing/BUILD.bazel
  third_party/kafka/BUILD.bazel
Labels: OK to merge, Ready For Review

#5017 Report Validator Status in Duties
  beacon-chain/rpc/validator/assignments.go
Labels: Enhancement, OK to merge, Ready For Review

#5021 Asynchronous Dials To Peers
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/service.go
Labels: Networking, Ready For Review

#5028 Update bazel.sh
  bazel.sh
Labels: CI, OK to merge, Ready For Review

#5023 Add SlotsPerArchivedPoint flag and a check
  beacon-chain/flags/base.go
  beacon-chain/main.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/service.go
  beacon-chain/state/stategen/service_test.go
  beacon-chain/usage.go
Labels: Ready For Review, new-state-mgmt

#5027 Change ETH1 Constant
  beacon-chain/powchain/log_processing.go
Labels: Ready For Review

#5026 Fix Custom Delay Flag
  beacon-chain/flags/base.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/usage.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5032 Add sha256 to external dependency librdkafka
  WORKSPACE
Labels: OK to merge, Ready For Review

#5033 Define -c opt for release builds
  .bazelrc
Labels: CI, OK to merge, Ready For Review

#5036 Update rbe_autoconf
  WORKSPACE
  tools/cross-toolchain/configs/clang/bazel_2.1.1/config/BUILD
  tools/cross-toolchain/configs/gcc/bazel_2.1.1/config/BUILD
  tools/cross-toolchain/rbe_toolchains_config.bzl
Labels: OK to merge, Ready For Review

#5034 Load hot state by root
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/hot_test.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/service.go
Labels: Ready For Review, new-state-mgmt

#5039 Add Prometheus Service for Slasher
  slasher/node/BUILD.bazel
  slasher/node/node.go
Labels: OK to merge, Ready For Review

#5038 Add Config Change for Validator
  shared/featureconfig/config.go
  validator/node/BUILD.bazel
  validator/node/node.go
Labels: OK to merge, Ready For Review

#5020 Prepare Slasher for Production
  slasher/db/iface/interface.go
  slasher/db/kv/attester_slashings.go
  slasher/db/kv/block_header.go
  slasher/db/kv/chain_data.go
  slasher/db/kv/indexed_attestations.go
  slasher/db/kv/proposer_slashings.go
  slasher/db/kv/spanner.go
  slasher/db/kv/spanner_test.go
  slasher/detection/attestations/BUILD.bazel
  slasher/detection/attestations/spanner.go
  slasher/detection/attestations/spanner_test.go
  slasher/detection/detect.go
  slasher/detection/service.go
Labels: OK to merge

#5035 Compute state up to slot
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: Ready For Review, new-state-mgmt

#5037 Change slasher cache to LRU cache
  shared/debug/debug.go
  slasher/cache/BUILD.bazel
  slasher/cache/span_cache.go
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/kv.go
  slasher/db/kv/kv_test.go
  slasher/db/kv/spanner.go
  slasher/db/kv/spanner_test.go
  slasher/db/testing/setup_db.go
Labels: Ready For Review

#5029 Aggregate Attestations Before Streaming to Slasher
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/service.go
Labels: Enhancement, OK to merge, Priority: High, Ready For Review

#5052 Add hot state by slot retrival
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/hot_test.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: Ready For Review, new-state-mgmt

#5042 Add prysm.sh script
  .gitignore
  prysm.sh
Labels: Ready For Review

#5041 Batch saving of attestations from stream for slasher
  slasher/beaconclient/receivers.go
  slasher/beaconclient/receivers_test.go
  slasher/beaconclient/service.go
  slasher/detection/attestations/spanner_test.go
Labels: Enhancement, Ready For Review

#5053 Better Nil Check in Slasher
  slasher/detection/detect.go
  slasher/detection/service.go
Labels: OK to merge, Ready For Review

#5055 Build herumi's BLS from source
  .bazelrc
  WORKSPACE
  shared/bls/BUILD.bazel
  shared/bls/spectest/BUILD.bazel
  third_party/herumi/BUILD.bazel
  third_party/herumi/bls.BUILD
  third_party/herumi/bls_eth_go_binary.BUILD
  third_party/herumi/bls_eth_go_binary_serialization_alloc_fix.patch
  third_party/herumi/herumi.bzl
  third_party/herumi/mcl.BUILD
Labels: Ready For Review

#5050 Discovery Fixes
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
Labels: Networking, Ready For Review

#5058 Improve HTR of State
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/blocks.go
  beacon-chain/state/stateutil/hash_function.go
  beacon-chain/state/stateutil/helpers.go
Labels: OK to merge

#5060 Add in Slasher Metrics
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/metrics.go
  beacon-chain/operations/slashings/service.go
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/metrics.go
  slasher/beaconclient/receivers.go
  slasher/cache/span_cache.go
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/kv.go
  slasher/db/kv/spanner.go
  slasher/detection/BUILD.bazel
  slasher/detection/attestations/BUILD.bazel
  slasher/detection/attestations/spanner.go
  slasher/detection/detect.go
  slasher/detection/metrics.go
Labels: OK to merge, Ready For Review

#5067 fixes data race in state.Slot
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/getters.go
  beacon-chain/state/getters_test.go
Labels: OK to merge

#5068 fixes races in blocks fetcher
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
Labels: Ready For Review

#5070 Include Bazel Genrule for Fast SSZ
  WORKSPACE
  tools/ssz.bzl
Labels: OK to merge, Ready For Review

#5075 Archived point retrieval and recovery
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
  beacon-chain/state/stategen/service.go
  slasher/beaconclient/receivers_test.go
  slasher/beaconclient/service.go
  slasher/detection/attestations/spanner.go
Labels: Ready For Review, new-state-mgmt

#5071 Verify Slashing Signatures Before Putting Into Blocks
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/metrics.go
  beacon-chain/operations/slashings/service.go
  beacon-chain/operations/slashings/service_attester_test.go
  beacon-chain/operations/slashings/service_proposer_test.go
  beacon-chain/rpc/beacon/slashings.go
  beacon-chain/rpc/beacon/slashings_test.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
Labels: Bug, OK to merge, Priority: Critical, Ready For Review

#5076 State migration from hot to cold (archived)
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/service.go
Labels: Ready For Review, new-state-mgmt

#5077 Save cold state
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
Labels: Ready For Review, new-state-mgmt

#5069 Return statuses on duties
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  validator/client/validator.go
  validator/client/validator_aggregate.go
  validator/client/validator_attest.go
  validator/client/validator_metrics.go
  validator/client/validator_propose.go
Labels: OK to merge

#5079 Load epoch boundary root
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/hot_test.go
Labels: Ready For Review, new-state-mgmt

#5073 Broadcast slashing
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/beacon/slashings.go
  beacon-chain/rpc/beacon/slashings_test.go
  beacon-chain/rpc/service.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5083 Save hot state
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/hot_test.go
Labels: OK to merge, Ready For Review, new-state-mgmt

#5084 Method to retrieve block slot via block root
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
  validator/client/validator.go
Labels: Ready For Review, new-state-mgmt

#5085 Use Target Epoch to Determine Indexed Attestations for Slasher
  beacon-chain/rpc/beacon/attestations.go
Labels: Priority: High, Ready For Review

#5086 Load cold state by root
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
Labels: Ready For Review, new-state-mgmt

#5092 Fix slasher rpc disconnect on error
  slasher/beaconclient/receivers.go
Labels: Ready For Review

#5066 Include ejected indices in ActiveSetChanges endpoint
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  proto/beacon/p2p/v1/archive.pb.go
  proto/beacon/p2p/v1/archive.proto
Labels: Ready For Review

#5087 Better attestation pool with map instead of expiration cache
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/node.go
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/block.go
  beacon-chain/operations/attestations/kv/block_test.go
  beacon-chain/operations/attestations/kv/forkchoice.go
  beacon-chain/operations/attestations/kv/forkchoice_test.go
  beacon-chain/operations/attestations/kv/kv.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/metrics.go
  beacon-chain/operations/attestations/prune_expired.go
  beacon-chain/operations/attestations/prune_expired_test.go
  beacon-chain/operations/attestations/service.go
Labels: Enhancement, Ready For Review

#5093 Make spanner tests more thorough, fixes
  slasher/detection/BUILD.bazel
  slasher/detection/attestations/BUILD.bazel
  slasher/detection/attestations/spanner.go
  slasher/detection/attestations/spanner_test.go
  slasher/detection/attestations/types/types.go
  slasher/detection/detect.go
  slasher/detection/detect_test.go
Labels: Ready For Review

#5047 handle slashing from p2p
  beacon-chain/node/node.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_handlers.go
  beacon-chain/sync/subscriber_test.go
Labels: Ready For Review

#4947 Update to go 1.14
  WORKSPACE
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/operations/attestations/service.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
  proto/cluster/services.pb.go
  third_party/boltdb/bolt.BUILD
Labels: OK to merge, Ready For Review

#5094 Use Current Time Slot for Fetching Committees in RPC
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
Labels: OK to merge, Ready For Review

#5097 Get cold intermediate state with slot
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
Labels: Ready For Review, new-state-mgmt

#5099 Minor Improvements
  beacon-chain/blockchain/chain_info.go
  shared/attestationutil/attestation_utils.go
Labels: OK to merge, Ready For Review

#5100 New state setter
  beacon-chain/operations/attestations/service.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/setter.go
  beacon-chain/state/stategen/setter_test.go
Labels: OK to merge, Ready For Review, new-state-mgmt

#5098 Init sync pre queue
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: Ready For Review

#5101 New state getter
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
Labels: OK to merge, Ready For Review, new-state-mgmt

#5103 Tweak validator logging
  validator/client/runner.go
  validator/client/validator_aggregate.go
Labels: OK to merge

#5102 Resume new state mgmt
  beacon-chain/state/stategen/service.go
  beacon-chain/state/stategen/service_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
Labels: Ready For Review, new-state-mgmt

#5106 Update README for Slasher
  slasher/README.md
Labels: OK to merge

#5107 Fix reward and penality zero epoch bug
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
Labels: Bug, Fuzz, OK to merge

#5064 Init sync blocks queue
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
Labels: Ready For Review

#5108 Part 1 of integrating new state mgmt to run time
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/init_sync_process_block_test.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/service.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archived_point.go
  beacon-chain/db/kv/archived_point_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/state.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/hot_test.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
  beacon-chain/state/stategen/service.go
  beacon-chain/state/stategen/service_test.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review, new-state-mgmt

#5115 asserts non-nil state
  beacon-chain/blockchain/head.go
Labels: Bug

#5096 Refactoring of initial sync
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/sync/initial-sync-old/BUILD.bazel
  beacon-chain/sync/initial-sync-old/log.go
  beacon-chain/sync/initial-sync-old/round_robin.go
  beacon-chain/sync/initial-sync-old/round_robin_test.go
  beacon-chain/sync/initial-sync-old/service.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/round_robin.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#5117 Add New State Utils
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/arrays.go
  beacon-chain/state/stateutil/attestations.go
  beacon-chain/state/stateutil/blocks.go
  beacon-chain/state/stateutil/trie_helpers.go
  beacon-chain/state/stateutil/trie_helpers_test.go
  beacon-chain/state/stateutil/validators.go
  shared/trieutil/sparse_merkle.go
  shared/trieutil/zerohashes.go
Labels: Ready For Review

#5122 Handle rewards overflow
  beacon-chain/core/epoch/precompute/reward_penalty.go
Labels: Ready For Review, spec-v0.11

#5118 Add Field Trie to State
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/field_trie.go
  beacon-chain/state/field_trie_test.go
  beacon-chain/state/stateutil/trie_helpers_test.go
  shared/memorypool/memorypool.go
Labels: Ready For Review

#5082 Integrate Field Tries into Current State
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/slashing.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/field_trie.go
  beacon-chain/state/setters.go
  beacon-chain/state/state_trie.go
  beacon-chain/state/types.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5128 Change to Batch Size
  beacon-chain/sync/initial-sync/round_robin.go
Labels: Ready For Review

#5129 Minor slasher fixes
  slasher/beaconclient/receivers.go
Labels: Ready For Review

#5123 Attestation Dynamic Committee Subnets
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/committee_ids.go
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#5121 Add ssz marshal and unmarshal for most data structures
  WORKSPACE
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
  proto/beacon/p2p/v1/BUILD.bazel
  shared/bytesutil/bytes.go
  shared/testutil/block.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
  third_party/com_github_prysmaticlabs_go_ssz.patch
  tools/ssz.bzl
Labels: OK to merge, Ready For Review

#5136 Attestation: Add a check for overflow
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_test.go
Labels: Bug, Fuzz, OK to merge

#5141 Add fetching validators by indices and public keys
  WORKSPACE
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
Labels: OK to merge, Ready For Review

#4878 Allow setting flags via yaml config file.
  WORKSPACE
  beacon-chain/BUILD.bazel
  beacon-chain/core/state/spectest/BUILD.bazel
  beacon-chain/flags/BUILD.bazel
  beacon-chain/flags/archive.go
  beacon-chain/flags/base.go
  beacon-chain/flags/config.go
  beacon-chain/flags/interop.go
  beacon-chain/main.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
  beacon-chain/usage.go
  beacon-chain/usage_test.go
  shared/cmd/BUILD.bazel
  shared/cmd/customflags.go
  shared/cmd/flags.go
  shared/cmd/wrap_flags.go
  shared/debug/BUILD.bazel
  shared/debug/debug.go
  shared/featureconfig/BUILD.bazel
  shared/featureconfig/config.go
  shared/featureconfig/config_test.go
  shared/featureconfig/filter_flags.go
  shared/featureconfig/flags.go
  shared/featureconfig/flags_test.go
  slasher/BUILD.bazel
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/attester_slashings_test.go
  slasher/db/kv/block_header_test.go
  slasher/db/kv/chain_data_test.go
  slasher/db/kv/indexed_attestations_test.go
  slasher/db/kv/kv_test.go
  slasher/db/kv/proposer_slashings_test.go
  slasher/db/kv/spanner_test.go
  slasher/db/kv/validator_id_pubkey_test.go
  slasher/flags/BUILD.bazel
  slasher/flags/flags.go
  slasher/main.go
  slasher/node/BUILD.bazel
  slasher/node/node.go
  slasher/node/node_test.go
  slasher/usage.go
  slasher/usage_test.go
  tools/deployContract/BUILD.bazel
  tools/deployContract/deployContract.go
  tools/drainContracts/BUILD.bazel
  tools/drainContracts/drainContracts.go
  tools/sendDepositTx/BUILD.bazel
  tools/sendDepositTx/sendDeposits.go
  validator/BUILD.bazel
  validator/flags/BUILD.bazel
  validator/flags/flags.go
  validator/flags/interop.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/node_test.go
  validator/usage.go
  validator/usage_test.go
Labels: Ready For Review

#5142 Fix new state mgmt sync stuck in a loop
  beacon-chain/blockchain/service.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  shared/bytesutil/bytes.go
Labels: Ready For Review, new-state-mgmt

#5146 Align aggregator action with v0.11
  WORKSPACE
  beacon-chain/rpc/aggregator/server.go
  beacon-chain/rpc/validator/aggregator.go
  beacon-chain/rpc/validator/aggregator_test.go
  shared/params/config.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
  validator/client/validator_aggregate.go
  validator/client/validator_aggregate_test.go
  validator/internal/beacon_node_validator_service_mock.go
Labels: Ready For Review, spec-v0.11

#5159 Refactor attestationutil.AttestingIndices
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/validator/aggregator_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  shared/attestationutil/BUILD.bazel
  shared/attestationutil/attestation_utils.go
  shared/attestationutil/attestation_utils_test.go
  tools/blocktree/main.go
Labels: OK to merge, Ready For Review

#5160 Use faster bitfield BitIndices to build attesting indices
  WORKSPACE
  shared/attestationutil/attestation_utils.go
  shared/attestationutil/attestation_utils_test.go
Labels: OK to merge, Ready For Review

#5162 Update go-bitfield
  WORKSPACE
Labels: OK to merge, Ready For Review

#5165 Remove Head Root from Beacon Block by Range Request
  beacon-chain/sync/initial-sync-old/round_robin.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/round_robin.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  proto/beacon/p2p/v1/types.pb.go
  proto/cluster/services.pb.go
  proto/faucet/faucet.pb.go
  proto/slashing/slashing.pb.go
  proto/testing/test.pb.go
Labels: OK to merge, Ready For Review, spec-v0.11

#5163 New byteutils for state gen
  beacon-chain/main.go
  shared/attestationutil/attestation_utils_test.go
  shared/bytesutil/bytes.go
  shared/bytesutil/bytes_test.go
  shared/featureconfig/filter_flags.go
  slasher/main.go
  tools/deployContract/deployContract.go
  tools/drainContracts/drainContracts.go
  tools/sendDepositTx/sendDeposits.go
  validator/main.go
Labels: OK to merge, Ready For Review, new-state-mgmt

#5161 BLS: some minor improvements
  shared/bls/BUILD.bazel
  shared/bls/bls.go
  shared/bls/bls_benchmark_test.go
  shared/bls/bls_test.go
Labels: OK to merge, Ready For Review

#5166 Align finalized slot check with v0.11
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review, spec-v0.11

#5158 Add DoS resistance for v0.11
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
Labels: Ready For Review, spec-v0.11

#5173 Add Fork Digest Helper
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/core/helpers/signing_root_test.go
Labels: Ready For Review, spec-v0.11

#5177 Add CORS preflight support
  beacon-chain/flags/base.go
  beacon-chain/gateway/BUILD.bazel
  beacon-chain/gateway/cors.go
  beacon-chain/gateway/gateway.go
  beacon-chain/gateway/server/main.go
  beacon-chain/node/node.go
Labels: Ready For Review

#5178 Buildkite changes
  .buildkite-bazelrc
Labels: OK to merge

#5174 Extend DoS prevention to rest of operation objects
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_handlers.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  beacon-chain/sync/validate_voluntary_exit.go
  beacon-chain/sync/validate_voluntary_exit_test.go
Labels: Ready For Review, spec-v0.11

#5180 Shard //beacon-chain/core/state:go_default_test
  beacon-chain/core/state/BUILD.bazel
Labels: OK to merge, Ready For Review

#5145 Change ListAttestations to get attestations from blocks
  WORKSPACE
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  endtoend/components/validator.go
  slasher/beaconclient/historical_data_retrieval.go
  third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
Labels: Ready For Review

#5172 Add Snappy Framing to the Encoder
  beacon-chain/p2p/encoder/ssz.go
Labels: Ready For Review, spec-v0.11

#5182 Add `HighestSlotBlock` Getter for db
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
Labels: Ready For Review, spec-v0.11

#5184 Change E2E config ports to be non-commonly used
  endtoend/params/params.go
Labels: OK to merge

#5183 Correctly return attestation data for late requests
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/exit_test.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/state/getters.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/pending_attestations_queue_test.go
Labels: Ready For Review

#5179 Move Subnet Functionality to its Own File
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/subnets_test.go
Labels: Ready For Review

#5187 Add Improvements to State Benchmarks
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/benchmarks_test.go
Labels: Ready For Review

#5190 Setup Slasher RPC server
  slasher/detection/detect.go
  slasher/detection/detect_test.go
  slasher/detection/listeners.go
  slasher/detection/service.go
  slasher/node/BUILD.bazel
  slasher/node/node.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/service.go
  slasher/rpc/service_test.go
Labels: Ready For Review

#5193 Replace boltdb imports with bbolt import
  WORKSPACE
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/archive.go
  beacon-chain/db/kv/archived_point.go
  beacon-chain/db/kv/attestations.go
  beacon-chain/db/kv/backup.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/deposit_contract.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/operations.go
  beacon-chain/db/kv/powchain.go
  beacon-chain/db/kv/slashings.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_summary.go
  beacon-chain/db/kv/utils.go
  beacon-chain/db/kv/validators.go
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/attester_slashings.go
  slasher/db/kv/block_header.go
  slasher/db/kv/chain_data.go
  slasher/db/kv/indexed_attestations.go
  slasher/db/kv/kv.go
  slasher/db/kv/proposer_slashings.go
  slasher/db/kv/spanner.go
  slasher/db/kv/validator_id_pubkey.go
  third_party/boltdb/bolt.BUILD
  tools/cluster-pk-manager/server/BUILD.bazel
  tools/cluster-pk-manager/server/db.go
  validator/db/BUILD.bazel
  validator/db/attestation_history.go
  validator/db/db.go
  validator/db/proposal_history.go
Labels: OK to merge

#5192 Add `HighestSlotState` Getter for db
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
  slasher/rpc/service.go
Labels: Blocked, new-state-mgmt

#5197 Add span to HTR and skip slot cache
  beacon-chain/blockchain/service.go
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/skip_slot_cache.go
  beacon-chain/core/state/benchmarks_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/state_trie.go
  beacon-chain/state/types_test.go
  shared/testutil/block.go
Labels: OK to merge

#5194 Apply fixes to block slots methods in DB
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/kv.go
Labels: Bug, OK to merge, Ready For Review

#5199 Add ipv6 multiaddr support
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/options.go
Labels: OK to merge, Ready For Review

#5198 Add enable-state-field-trie for e2e
  beacon-chain/state/field_trie.go
  beacon-chain/state/state_trie.go
  shared/featureconfig/flags.go
  shared/sliceutil/slice.go
  shared/sliceutil/slice_test.go
Labels: OK to merge, Ready For Review

#5200 Remove deprecated aggregator service
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/aggregator/BUILD.bazel
  beacon-chain/rpc/aggregator/server.go
  beacon-chain/rpc/service.go
  proto/beacon/rpc/v1/services.proto
Labels: Ready For Review

#5195 Add `HighestSlotBlocksBelow` getter for db
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
Labels: Ready For Review, new-state-mgmt

#5205 Remove extra udp port log
  beacon-chain/p2p/service.go
Labels: OK to merge, Ready For Review

#5203 Add gRPC headers flag support for validator client side
  endtoend/components/validator.go
  validator/client/service.go
  validator/flags/flags.go
  validator/main.go
  validator/node/node.go
  validator/usage.go
Labels: Ready For Review

#5206 Verify proposer signature in sync
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review, spec-v0.11

#5204 Fix Incorrect Logging for IPV6 Addresses
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service.go
Labels: OK to merge

#5207 Fix Signed Attestation In Sync
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
Labels: Networking, Ready For Review

#5181 Add Eth2 Fork ENR Functionality
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/feed/state/events.go
  beacon-chain/node/node.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/config.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/sender_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets_test.go
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/messages.proto
  shared/params/config.go
Labels: Ready For Review

#5208 Verify aggregator signature in sync
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/core/helpers/signing_root_test.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
Labels: Ready For Review, spec-v0.11

#5214 Add alpine based docker images for validator and beacon chain
  WORKSPACE
  beacon-chain/BUILD.bazel
  tools/BUILD.bazel
  tools/binary_targets.bzl
  tools/build_settings.bzl
  validator/BUILD.bazel
Labels: Ready For Review

#5213 Add `HighestSlotStatesBelow` DB getter
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
Labels: OK to merge, Ready For Review

#5191 Add Fork Digest For Gossip Topics
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/fork.go
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/decode_pubsub.go
  beacon-chain/sync/error.go
  beacon-chain/sync/initial-sync-old/round_robin_test.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_committee_index_beacon_attestation.go
  beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: Networking, Ready For Review, spec-v0.11

#5221 Add Fast Copy of Trie
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/state/state_trie.go
Labels: Ready For Review

#5219 Custom Block HTR
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/blocks.go
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/attestations.go
  beacon-chain/state/stateutil/benchmark_test.go
  beacon-chain/state/stateutil/blocks.go
  beacon-chain/state/stateutil/blocks_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#5209 is slashable attestation endpoint implementation
  slasher/detection/detect.go
  slasher/node/node.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/server.go
  slasher/rpc/server_test.go
  slasher/rpc/service.go
Labels: OK to merge, Ready For Review

#5223 Short circuit genesis condition for new state mgmt
  beacon-chain/state/stategen/getter.go
Labels: Ready For Review

#5217 Faster hashing for attestation pool
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/benchmark_test.go
  beacon-chain/operations/attestations/kv/block.go
  beacon-chain/operations/attestations/kv/forkchoice.go
  beacon-chain/operations/attestations/kv/kv.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
Labels: OK to merge, Ready For Review

#5224 Handle genesis case for blocks/states at slot index
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/rpc/beacon/blocks.go
  slasher/rpc/server.go
  slasher/rpc/service.go
Labels: Bug, OK to merge, Ready For Review

#5228 Revert "Add Fast Copy of Trie"
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/state/state_trie.go
Labels: OK to merge

#5148 init-sync revamp
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/fsm.go
  beacon-chain/sync/initial-sync/fsm_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: Ready For Review

#5229 Fix Incorrect Attester Slashing Method
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/block_operations.go
  beacon-chain/core/blocks/block_regression_test.go
Labels: Bug, Priority: Critical

#5225 Prune garbage state is not for new state mgmt
  beacon-chain/blockchain/service.go
Labels: Bug, OK to merge, new-state-mgmt

#5230 Productionization new state service part 1
  beacon-chain/blockchain/service.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/archived_point.go
  beacon-chain/db/kv/archived_point_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_summary_test.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/cold.go
  beacon-chain/state/stategen/cold_test.go
  beacon-chain/state/stategen/epoch_boundary_root.go
  beacon-chain/state/stategen/epoch_boundary_root_test.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/hot.go
  beacon-chain/state/stategen/hot_test.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
  beacon-chain/state/stategen/service.go
  beacon-chain/state/stategen/service_test.go
  beacon-chain/state/stategen/setter_test.go
  proto/beacon/db/attestation_container.pb.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/db/powchain.pb.go
  proto/beacon/p2p/v1/archive.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/beacon/rpc/v1/services.pb.go
  proto/beacon/rpc/v1_gateway/services.pb.go
Labels: Ready For Review

#5233 Prevent panic for different size bitlists
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
Labels: OK to merge, Ready For Review
