Repository OffchainLabs/prysm, pull requests merged in 2020-12, with the labels that each got.

#7946 Improve genesis event log and load blocks to fork choice log
  beacon-chain/blockchain/service.go
  beacon-chain/interop-cold-start/service.go
  shared/slotutil/countdown.go
  shared/slotutil/countdown_test.go
Labels: OK to merge, Ready For Review

#8007 Fix Miscellaneous Deep Source Issues
  beacon-chain/state/stategen/errors.go
  endtoend/components/validator.go
  scripts/check-todo.sh
  scripts/interop_start.sh
  scripts/update-go-pbs.sh
  scripts/update-go-ssz.sh
  shared/mputil/multilock.go
  shared/promptutil/validate.go
  shared/promptutil/validate_test.go
  shared/testutil/deposits.go
  shared/tos/tos.go
  slasher/detection/attestations/spanner.go
  validator/client/attest_protect.go
  validator/keymanager/imported/import.go
  validator/rpc/wallet.go
Labels: Ready For Review

#7992 Remove Exclusion List
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/service.go
Labels: Networking, OK to merge, Ready For Review

#7998 Log with field error instead of err
  beacon-chain/sync/initial-sync/round_robin.go
Labels: OK to merge, Ready For Review

#8011 Create Bucket If Not Exists When Fetching Proposal History
  validator/db/kv/proposal_history_v2.go
  validator/db/kv/proposal_history_v2_test.go
Labels: OK to merge, Priority: Critical, Ready For Review

#8002 Pending block queue lock fixes
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: OK to merge, Ready For Review

#8009 Fix missing space in error message in account list
  validator/accounts/wallet/wallet.go
Labels: OK to merge

#8006 Update README to include branching strategy
  README.md
Labels: OK to merge, Ready For Review

#8018 Add Buffer For Inbound Peers
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/connection_gater.go
  beacon-chain/p2p/connection_gater_test.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service_test.go
  deps.bzl
  go.mod
Labels: Networking, Ready For Review

#7991 Init sync: remove redundant start slot code
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
Labels: OK to merge, Ready For Review, Sync

#8022 Update deprecated multiaddr-net package
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/connection_gater.go
  go.mod
Labels: OK to merge, Ready For Review

#8020 Change LowestSignedProposal to Also Return a Boolean for Slashing Protection
  validator/db/iface/interface.go
  validator/db/kv/proposal_history_v2.go
  validator/db/kv/proposal_history_v2_test.go
  validator/slashing-protection/local/standard-protection-format/export.go
Labels: Ready For Review

#7978 Fix Interop Mode
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/pubsub.go
Labels: OK to merge, Ready For Review

#8023 Remove logging deposit inclusion slot
  beacon-chain/rpc/validator/status.go
  beacon-chain/rpc/validator/status_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#8004 Update `LowestSignedTargetEpoch` to include exists
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/db/iface/interface.go
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/attestation_history_v2_test.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
Labels: OK to merge, Ready For Review

#8003 Logging with `PadLevelText` to true
  beacon-chain/BUILD.bazel
  beacon-chain/main.go
  validator/BUILD.bazel
  validator/main.go
Labels: Discussion, OK to merge, Ready For Review

#7953 Make TLS connections to a remote wallet non-mandatory
  validator/accounts/accounts_list_test.go
  validator/accounts/cmd_wallet.go
  validator/accounts/prompt/prompt.go
  validator/accounts/wallet_create_test.go
  validator/accounts/wallet_edit_test.go
  validator/flags/flags.go
  validator/keymanager/remote/keymanager.go
  validator/keymanager/remote/keymanager_test.go
Labels: OK to merge, Ready For Review

#7974 Init-sync: enable peer scorer by default
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers_test.go
  beacon-chain/sync/initial-sync/round_robin.go
Labels: OK to merge, Ready For Review, Sync

#7977 Add test for local protection genesis attestation
  validator/client/attest_protect_test.go
Labels: OK to merge, Ready For Review

#7999 Init sync: conditional syncing to finalized slot
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: OK to merge, Ready For Review, Sync

#8034 Invert enable-sync-backtracking
  shared/featureconfig/config.go
  shared/featureconfig/deprecated_flags.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#8027 Export Attesting History for Slashing Interchange Standard
  validator/client/attest_protect_test.go
  validator/slashing-protection/local/standard-protection-format/export.go
  validator/slashing-protection/local/standard-protection-format/export_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
Labels: Priority: High, Ready For Review

#8038 Skip bogus init-sync test
  beacon-chain/sync/initial-sync/service_test.go
Labels: OK to merge, Ready For Review

#8036 Revert "Logging with `PadLevelText` to true"
  beacon-chain/BUILD.bazel
  beacon-chain/main.go
  validator/BUILD.bazel
  validator/main.go
Labels: OK to merge, Ready For Review

#8039 Round robin: half open interval in syncToFinalizedEpoch
  beacon-chain/sync/initial-sync/round_robin.go
Labels: OK to merge, Ready For Review, Sync

#7971 Update blst to v0.3.1 and incorporate subgroup changes
  deps.bzl
  go.mod
  go.sum
  shared/bls/blst/public_key.go
  shared/bls/blst/signature.go
Labels: Cryptography, OK to merge

#8013 Update attestation schedule log with total attester count
  validator/client/validator.go
Labels: OK to merge, Ready For Review

#8042 Unskip fixed init-sync service test
  beacon-chain/sync/initial-sync/service_test.go
Labels: OK to merge, Ready For Review

#8045 Update rules_go to v0.24.9 and golang to v1.15.6
  WORKSPACE
Labels: OK to merge, Ready For Review

#8046 Update TestMain(): do not call os.Exit() explicitly
  beacon-chain/blockchain/blockchain_test.go
  beacon-chain/cache/cache_test.go
  beacon-chain/core/epoch/spectest/spectest_test.go
  beacon-chain/p2p/peers/peers_test.go
  beacon-chain/p2p/peers/scorers/scorers_test.go
  beacon-chain/powchain/powchain_test.go
  beacon-chain/rpc/beacon/beacon_test.go
  beacon-chain/rpc/validator/validator_test.go
  beacon-chain/state/stateutil/stateutil_test.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/sync_test.go
  shared/aggregation/attestations/attestations_test.go
  shared/slotutil/slotutil_test.go
  slasher/beaconclient/service_test.go
  slasher/db/kv/kv_test.go
  slasher/detection/attestations/attestations_test.go
  slasher/detection/proposals/proposals_test.go
  slasher/node/node_test.go
  slasher/rpc/rpc_test.go
  tools/bootnode/bootnode_test.go
Labels: OK to merge, Ready For Review

#8044 Attestation aggregation: removes redundant code from max-cover benchmarks
  shared/aggregation/attestations/attestations_bench_test.go
Labels: Cleanup, OK to merge, Ready For Review

#8043 Attestation aggregation: maxcover vs naive aggregation effectiveness test
  shared/aggregation/attestations/BUILD.bazel
  shared/aggregation/attestations/attestations_test.go
Labels: OK to merge, Ready For Review

#8031 Validate Proposers Are Not Slashable With Regard to Data Within Slasher Interchange JSON
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
Labels: Ready For Review

#8047 fix(grpcHeaders): accept values with "=" symbols
  validator/client/BUILD.bazel
  validator/client/service.go
  validator/client/service_test.go
Labels: OK to merge

#8040 Export Slashing Protection History Via CLI
  validator/BUILD.bazel
  validator/flags/flags.go
  validator/main.go
  validator/slashing-protection/BUILD.bazel
  validator/slashing-protection/cli_export.go
  validator/slashing-protection/cli_export_test.go
  validator/slashing-protection/cmd.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/import_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
  validator/testing/BUILD.bazel
  validator/testing/protection_history.go
Labels: Ready For Review

#8041 Load graffiti from file
  endtoend/components/validator.go
  endtoend/evaluators/BUILD.bazel
  endtoend/evaluators/operations.go
  endtoend/helpers/helpers.go
  endtoend/minimal_e2e_test.go
  validator/client/BUILD.bazel
  validator/client/propose.go
  validator/client/propose_test.go
  validator/client/service.go
  validator/client/validator.go
  validator/flags/flags.go
  validator/graffiti/BUILD.bazel
  validator/graffiti/parse_graffiti.go
  validator/graffiti/parse_graffiti_test.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/usage.go
Labels: OK to merge, Ready For Review

#8060 Init sync: minor fixes
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/round_robin.go
Labels: Cleanup, OK to merge, Ready For Review

#8033 Resolve panic on shutdown with offline eth1 node
  beacon-chain/powchain/service.go
Labels: OK to merge

#8061 Restore database CLI command
  beacon-chain/BUILD.bazel
  beacon-chain/db/BUILD.bazel
  beacon-chain/db/cmd.go
  beacon-chain/db/kv/backup_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/restore.go
  beacon-chain/db/restore_test.go
  beacon-chain/main.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/usage.go
  shared/cmd/flags.go
  slasher/BUILD.bazel
  slasher/db/BUILD.bazel
  slasher/db/cmd.go
  slasher/db/kv/backup_test.go
  slasher/db/kv/kv.go
  slasher/db/restore.go
  slasher/db/restore_test.go
  slasher/main.go
  slasher/node/node.go
  validator/BUILD.bazel
  validator/db/BUILD.bazel
  validator/db/cmd.go
  validator/db/restore.go
  validator/db/restore_test.go
  validator/main.go
Labels: Ready For Review

#8067 Add EIP-3076 Invariants for Proposer Slashing Protection
  validator/client/propose_protect.go
  validator/client/propose_protect_test.go
  validator/client/propose_test.go
Labels: Ready For Review

#7880 Add EIP-3076 Interchange JSON CLI command to validator
  shared/promptutil/prompt.go
  validator/accounts/prompt/prompt.go
  validator/flags/flags.go
  validator/keymanager/imported/import.go
  validator/slashing-protection/BUILD.bazel
  validator/slashing-protection/cli_export.go
  validator/slashing-protection/cli_import.go
  validator/slashing-protection/cli_import_export_test.go
  validator/slashing-protection/cmd.go
  validator/slashing-protection/external.go
  validator/slashing-protection/slasher_client.go
Labels: Ready For Review

#8068 Add state field count to config
  beacon-chain/state/state_trie.go
  beacon-chain/state/stateutil/arrays.go
  beacon-chain/state/stateutil/state_root.go
  beacon-chain/state/stateutil/state_root_test.go
  beacon-chain/state/types.go
  shared/params/config.go
  shared/params/mainnet_config.go
Labels: OK to merge, Ready For Review

#8077 Add beacon block nil body checks
  shared/blockutil/block_utils.go
  shared/blockutil/block_utils_test.go
  validator/client/propose_protect_test.go
Labels: Ready For Review

#8051 Filter Slashable Attester Public Keys in Slashing Interchange Import
  validator/client/BUILD.bazel
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/client/service.go
  validator/client/validator.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/slashing-protection/BUILD.bazel
  validator/slashing-protection/cli_import_export_test.go
  validator/slashing-protection/iface/BUILD.bazel
  validator/slashing-protection/iface/protector.go
  validator/slashing-protection/local/attesting-history/BUILD.bazel
  validator/slashing-protection/local/attesting-history/check_slashable_attestation.go
  validator/slashing-protection/local/attesting-history/check_slashable_attestation_test.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
  validator/testing/BUILD.bazel
  validator/testing/protection_history.go
Labels: Ready For Review

#8081 Warn when creating an imported wallet
  validator/accounts/wallet_create.go
Labels: OK to merge, Ready For Review

#8069 Remove custom block body root and block root methods
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/benchmark_test.go
  beacon-chain/state/stateutil/blocks.go
  beacon-chain/state/stateutil/blocks_test.go
  proto/migration/BUILD.bazel
  proto/migration/migration.go
  shared/blockutil/BUILD.bazel
  shared/blockutil/block_utils.go
  shared/blockutil/block_utils_test.go
  validator/client/propose_protect_test.go
Labels: OK to merge, Ready For Review

#8082 Save Slashable Keys to Disk in the Validator Client
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/db/kv/schema.go
  validator/db/kv/slashable_keys.go
  validator/db/kv/slashable_keys_test.go
  validator/slashing-protection/local/standard-protection-format/import.go
Labels: Ready For Review

#8078 Update waiting validator methods to be context aware
  endtoend/components/validator.go
  validator/client/BUILD.bazel
  validator/client/aggregate.go
  validator/client/aggregate_test.go
  validator/client/attest.go
Labels: OK to merge, Ready For Review

#8088 Validator client logs time left to next duty
  validator/client/BUILD.bazel
  validator/client/log.go
  validator/client/log_test.go
  validator/client/mock_validator.go
  validator/client/runner.go
Labels: OK to merge, Ready For Review

#8089 Properly Handle Duplicate Public Key Entries in Slashing Interchange Imports
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
Labels: Ready For Review

#8057 Attempt to reconnect when waiting for activation
  validator/client/BUILD.bazel
  validator/client/validator.go
  validator/client/validator_test.go
  validator/client/wait_for_activation.go
  validator/client/wait_for_activation_test.go
Labels: Bug, Ready For Review

#8063 Attestation aggregation: remove proper set duplicates
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/proposer_utils.go
  beacon-chain/rpc/validator/proposer_utils_test.go
Labels: OK to merge, Ready For Review

#8062 Add Fallback Option for Eth1 Nodes
  beacon-chain/blockchain/service_test.go
  beacon-chain/flags/base.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/usage.go
  shared/cmd/helpers.go
  shared/cmd/helpers_test.go
Labels: Enhancement, OK to merge, Ready For Review

#8090 Expand Password Input Errors
  validator/rpc/auth.go
Labels: OK to merge

#8086 Simpler and Safer Attester Slashing Protection
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/client/BUILD.bazel
  validator/client/attest.go
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/client/propose.go
  validator/client/propose_test.go
  validator/client/runner.go
  validator/client/service_test.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/attestation_history_v2_test.go
  validator/db/kv/backup_test.go
  validator/db/kv/db.go
  validator/db/kv/db_test.go
  validator/db/kv/proposal_history_v2_test.go
  validator/db/restore_test.go
  validator/db/testing/setup_db.go
  validator/db/testing/setup_db_test.go
  validator/node/node.go
  validator/node/node_test.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
Labels: OK to merge, Priority: Critical, Ready For Review

#8000 Refetch validating keys if no keys are fetched
  validator/client/validator.go
  validator/client/validator_test.go
  validator/client/wait_for_activation.go
  validator/client/wait_for_activation_test.go
Labels: OK to merge, Ready For Review

#8085 Check for Signing Root Mismatch When Submitting Proposals and Importing Proposals in Slashing Interchange
  beacon-chain/state/stateutil/attestations.go
  validator/client/propose.go
  validator/client/propose_protect.go
  validator/client/propose_protect_test.go
  validator/client/propose_test.go
  validator/client/validator.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
Labels: Ready For Review

#8048 Refactor Subnet Search
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/iterator.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/subscriber.go
  shared/params/mainnet_config.go
  shared/params/network_config.go
  shared/params/testnet_e2e_config.go
Labels: Networking, OK to merge, Ready For Review

#7942 Add Inbound Peer Limit
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/connection_gater.go
  beacon-chain/p2p/connection_gater_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
Labels: Networking, OK to merge, Ready For Review

#8102 Remove Saving Of Target And Source Epoch
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
Labels: OK to merge, Priority: High, Ready For Review

#8103 Remove unused vars in tests
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/operations/slashings/service_attester_test.go
  beacon-chain/operations/voluntaryexits/service_test.go
  beacon-chain/sync/rpc_status_test.go
Labels: Cleanup, OK to merge, Ready For Review

#8065 Change block_arrival_latency buckets to exponential format
  beacon-chain/sync/metrics.go
Labels: OK to merge

#8015 Update go-libp2p to 0.12.0
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/encoder/ssz_test.go
  beacon-chain/p2p/pubsub.go
  beacon-chain/p2p/sender.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/error.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_send_request.go
  beacon-chain/sync/rpc_status.go
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge

#8106 Validator code health improvements
  validator/accounts/accounts_list.go
  validator/client/metrics.go
Labels: OK to merge, Ready For Review

#8099 Fix Slasher Backup DB panic on call.
  slasher/node/node.go
Labels: OK to merge, Ready For Review

#8104 Remove duplicate package imports
  beacon-chain/p2p/connection_gater.go
  beacon-chain/p2p/service.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
Labels: Cleanup, OK to merge, Ready For Review

#8113 Set Empty Epochs in Between Attestations as FAR_FUTURE_EPOCH in Attesting History
  validator/db/kv/historical_attestations.go
  validator/db/kv/historical_attestations_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
Labels: Ready For Review

#8109 Beacon node code health improvements
  beacon-chain/core/blocks/attestation.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/p2p/pubsub_filter.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/state/stateutil/attestations.go
Labels: OK to merge, Ready For Review

#8096 Skip proposer indices cache update if exists
  beacon-chain/cache/proposer_indices.go
  beacon-chain/cache/proposer_indices_disabled.go
  beacon-chain/cache/proposer_indices_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
Labels: OK to merge, Ready For Review

#8111 CI: Disable remote caching of GoStdLib
  .bazelrc
Labels: CI, OK to merge, Priority: Low, Ready For Review

#8117 Add extra methods to shared/fileutil
  shared/fileutil/fileutil.go
  shared/fileutil/fileutil_test.go
Labels: OK to merge, Ready For Review

#8107 More Efficient Validation of Proposer Index
  beacon-chain/sync/metrics.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Enhancement, OK to merge, Ready For Review

#7858 Add Slashing Interchange, EIP-3076, Spec Tests to Prysm
  WORKSPACE
  validator/client/BUILD.bazel
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/client/slashing_protection_interchange_test.go
  validator/slashing-protection/local/attesting-history/check_slashable_attestation.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/export.go
  validator/slashing-protection/local/standard-protection-format/helpers.go
  validator/slashing-protection/local/standard-protection-format/helpers_test.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
Labels: Ready For Review

#8122 Validator DB cleanup: remove obsolete buckets
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/db.go
  validator/db/kv/proposal_history_v2.go
  validator/db/kv/schema.go
Labels: Cleanup, OK to merge, Priority: Low, Ready For Review

#8095 Fix issue with roaming data dir on Wins
  beacon-chain/BUILD.bazel
  beacon-chain/main.go
  shared/cmd/defaults.go
  shared/tos/tos.go
  validator/BUILD.bazel
  validator/flags/flags.go
  validator/main.go
Labels: Ready For Review

#8120 FC test coverage improvement
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/node_test.go
  beacon-chain/forkchoice/protoarray/nodes.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
Labels: OK to merge, Ready For Review

#8094 Allow update cache at last slot of the epoch
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
Labels: OK to merge, Ready For Review

#8121 Implement Migration for Unattested Epochs in Attesting History Database
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/db/kv/historical_attestations_test.go
  validator/db/kv/migration.go
  validator/db/kv/migration_unattested_epochs.go
  validator/db/kv/migration_unattested_epochs_test.go
  validator/db/kv/schema.go
  validator/node/node.go
Labels: Ready For Review

#8125 Pass context to NewKVStore
  beacon-chain/db/db.go
  beacon-chain/db/kv/backup_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/kv_test.go
  beacon-chain/db/restore_test.go
  beacon-chain/db/testing/setup_db.go
  beacon-chain/node/node.go
  fuzz/block_fuzz.go
  tools/blocktree/main.go
  tools/extractor/main.go
  tools/interop/export-genesis/main.go
Labels: OK to merge, Ready For Review

#8129 Validator database: use snappy compression on encoded attestation history
  validator/db/kv/BUILD.bazel
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/db.go
  validator/db/kv/migration.go
  validator/db/kv/migration_snappy_history.go
  validator/db/kv/migration_snappy_history_test.go
  validator/db/kv/schema.go
  validator/node/node.go
Labels: OK to merge, Ready For Review

#8130 Limit prometheus requests in flight, set timeout to reasonable 30 seconds
  shared/prometheus/service.go
Labels: OK to merge

#8127 Consolidate Required Web UI Endpoints Into Single Protobuf File
  beacon-chain/forkchoice/protoarray/store_test.go
  go.sum
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/rpc/health.go
Labels: OK to merge, Ready For Review

#8135 Do Not Verify Attestations When Packing Them
  beacon-chain/rpc/validator/proposer_utils.go
Labels: OK to merge, Ready For Review

#8137 Fix participation query returning balances of orphaned chain
  beacon-chain/node/node.go
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/service.go
Labels: Ready For Review

#8140 Lock Only When Needed When Fetching Attesting History
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/db.go
Labels: OK to merge, Priority: Critical, Ready For Review

#8110 Refactor Method Signatures For Powchain
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/block_cache.go
  beacon-chain/powchain/block_cache_test.go
  beacon-chain/powchain/block_reader.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/testing/BUILD.bazel
  beacon-chain/powchain/testing/faulty_mock.go
  beacon-chain/powchain/testing/mock.go
  beacon-chain/powchain/types/BUILD.bazel
  beacon-chain/powchain/types/eth1_types.go
  beacon-chain/powchain/types/eth1_types_test.go
  beacon-chain/rpc/validator/proposer.go
Labels: Eth1chain, OK to merge, Ready For Review

#8142 Clean up account logs and errors
  validator/accounts/accounts.go
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_enable_disable.go
  validator/accounts/accounts_import.go
  validator/accounts/accounts_import_test.go
  validator/accounts/accounts_list.go
  validator/accounts/wallet/wallet.go
  validator/accounts/wallet_create.go
  validator/accounts/wallet_edit.go
  validator/accounts/wallet_recover.go
Labels: Cleanup, OK to merge, Ready For Review

#8145 Add Instead of Subtract in Epoch Boundary Check
  beacon-chain/blockchain/process_block.go
Labels: OK to merge, Ready For Review

#8139 Implement Unified Validator API Endpoints for Beacon Chain Information
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/beacon.go
  validator/rpc/beacon_test.go
  validator/rpc/gateway/gateway.go
  validator/rpc/intercepter.go
  validator/rpc/server.go
Labels: OK to merge, Ready For Review

#8133 Make TLS mandatory by default when unmarshalling remote wallet options
  validator/keymanager/remote/keymanager.go
  validator/keymanager/remote/keymanager_test.go
Labels: OK to merge, Ready For Review

#8143 Add Public Method To Retrieve Discovery Address
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/p2p.go
Labels: API, Networking, OK to merge, Ready For Review

#8146 Fallback To Historical Sync For Powchain
  beacon-chain/powchain/log_processing.go
Labels: Eth1chain, OK to merge, Ready For Review

#8148 Update `Attestation schedule...` log for clarify
  validator/client/validator.go
Labels: OK to merge, Ready For Review

#8151 Remove Logout from Validator RPC Authenticated Paths
  validator/rpc/intercepter.go
Labels: OK to merge, Ready For Review

#8153 Move hot state cache to stategen
  beacon-chain/cache/BUILD.bazel
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/hot_state_cache.go
  beacon-chain/state/stategen/hot_state_cache_test.go
  beacon-chain/state/stategen/service.go
  beacon-chain/state/stategen/setter.go
  beacon-chain/state/stategen/setter_test.go
Labels: OK to merge, Ready For Review

#8156 Init sync: minor style fixes
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/fsm.go
Labels: Cleanup, OK to merge, Ready For Review

#8150 Stream Validator and Beacon Logs via gRPC Streams
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/node/BUILD.bazel
  beacon-chain/rpc/node/server.go
  beacon-chain/rpc/node/server_test.go
  beacon-chain/rpc/service.go
  go.mod
  proto/beacon/rpc/v1/health.pb.go
  proto/beacon/rpc/v1/health.proto
  proto/beacon/rpc/v1_gateway/health.pb.go
  proto/beacon/rpc/v1_gateway/health.pb.gw.go
  proto/validator/accounts/v2/BUILD.bazel
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  shared/logutil/BUILD.bazel
  shared/logutil/stream.go
  shared/logutil/stream_test.go
  shared/prometheus/BUILD.bazel
  shared/prometheus/service.go
  validator/client/BUILD.bazel
  validator/client/service.go
  validator/client/service_test.go
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/beacon.go
  validator/rpc/health.go
  validator/rpc/health_test.go
  validator/rpc/intercepter.go
  validator/rpc/server.go
Labels: OK to merge, Ready For Review

#8155 Revert Inbound Peer Limit
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
Labels: Networking, OK to merge, Ready For Review

#8158 Fix import shadowing of db package
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/info_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service_norace_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/beaconv1/blocks_test.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/replay_test.go
  beacon-chain/state/stategen/service.go
  beacon-chain/state/stategen/service_test.go
  beacon-chain/state/stategen/setter_test.go
Labels: Cleanup, OK to merge, Ready For Review

#8161 Flag to enable duty count down
  validator/client/log.go
  validator/client/log_test.go
  validator/client/service.go
  validator/client/validator.go
  validator/flags/flags.go
  validator/main.go
  validator/node/node.go
  validator/usage.go
Labels: OK to merge, Ready For Review

#8147 Fix issue with custom chain/network ID configuration
  beacon-chain/cache/subnet_ids.go
  beacon-chain/flags/base.go
  beacon-chain/node/node.go
  beacon-chain/powchain/service.go
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  shared/params/BUILD.bazel
  shared/params/config.go
  shared/params/loader.go
  shared/params/loader_test.go
  shared/params/mainnet_config.go
  shared/params/minimal_config.go
  shared/params/network_config.go
  shared/params/testnet_e2e_config.go
  shared/params/testnet_pyrmont_config.go
  shared/params/testnet_toledo_config.go
Labels: OK to merge, Ready For Review

#8162 Fix Unknown Validator Edge Case in ListValidatorBalances
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: API, Bug, OK to merge, Ready For Review
