Repository OffchainLabs/prysm, pull requests merged in 2020-09, with the labels that each got.

#7148 Update `ProcessBlock` to use a pipeline
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/attester_slashing.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/block_regression_test.go
  beacon-chain/core/blocks/deposit.go
  beacon-chain/core/blocks/deposit_test.go
  beacon-chain/core/blocks/eth1_data.go
  beacon-chain/core/blocks/eth1_data_test.go
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/blocks/exit_test.go
  beacon-chain/core/blocks/header.go
  beacon-chain/core/blocks/header_test.go
  beacon-chain/core/blocks/proposer_slashing.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/blocks/randao_test.go
  beacon-chain/core/blocks/spectest/deposit_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_fuzz_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/validator/proposer_test.go
  fuzz/attester_slashing_fuzz.go
  fuzz/proposer_slashing_fuzz.go
  shared/testutil/spectest.go
Labels: Cleanup, Ready For Review

#7154 Removes redundant SignedAggregateAndProof declaration
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/testing/ssz_static_test.go
Labels: OK to merge, Ready For Review

#7153 Remove Deprecated Request Type
  beacon-chain/p2p/rpc_topic_mappings.go
  beacon-chain/p2p/rpc_topic_mappings_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  proto/beacon/p2p/v1/generated.ssz.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
Labels: OK to merge, Ready For Review

#7095 Fixes: Accounts-V2: listing accounts produces incorrect output
  validator/accounts/v2/accounts_list_test.go
  validator/keymanager/v2/derived/backup.go
  validator/keymanager/v2/derived/backup_test.go
  validator/keymanager/v2/derived/derived.go
  validator/keymanager/v2/derived/derived_test.go
  validator/keymanager/v2/direct/backup.go
  validator/keymanager/v2/direct/backup_test.go
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/direct_test.go
  validator/keymanager/v2/direct/refresh.go
  validator/keymanager/v2/direct/refresh_test.go
Labels: OK to merge

#7151 Handle Zero Root Requests
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
Labels: OK to merge, Ready For Review

#7155 Use state slot to verify exit signature
  beacon-chain/rpc/validator/exit.go
  beacon-chain/rpc/validator/exit_test.go
  beacon-chain/sync/validate_voluntary_exit.go
  beacon-chain/sync/validate_voluntary_exit_test.go
Labels: OK to merge, Ready For Review

#7152 Fix Snappy Framed Reader
  beacon-chain/p2p/encoder/BUILD.bazel
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/encoder/ssz_test.go
Labels: OK to merge, Ready For Review

#7157 Update Protos for Wallet Creation
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
Labels: API, OK to merge, Ready For Review

#7149 Add overflow check for `StartSlot`
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/core/epoch/precompute/justification_finalization.go
  beacon-chain/core/helpers/block.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/service_attester_test.go
  beacon-chain/operations/slashings/service_proposer_test.go
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/status.go
  beacon-chain/rpc/beacon/assignments.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beacon/committees_test.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/exit.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_blocks.go
  validator/client/validator.go
Labels: OK to merge, Ready For Review

#7165 Check initial sync block is descendent of current finalized block
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: Ready For Review

#7160 Verify Attestation Time Correctly
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  shared/mathutil/math_helper.go
  shared/mathutil/math_helper_test.go
Labels: OK to merge, Ready For Review

#7166 Asserts response invariants in beaconBlocksByRange
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
Labels: OK to merge, Ready For Review

#7167 Set head as finalized root (instead of archived root) on start
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: OK to merge, Ready For Review

#7168 Hardens block validation in init-sync
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
Labels: OK to merge, Ready For Review

#7031 Deprecate beacon chain slasher flags
  beacon-chain/flags/base.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/rpc/service.go
  beacon-chain/usage.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#7158 Prepare Validator Client for Web Usage
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/wallet_recover.go
  validator/client/BUILD.bazel
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/validator.go
  validator/db/kv/db.go
  validator/flags/flags.go
  validator/keymanager/v2/direct/import.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/auth.go
  validator/rpc/auth_test.go
  validator/rpc/gateway/gateway.go
  validator/rpc/health.go
  validator/rpc/health_test.go
  validator/rpc/intercepter.go
  validator/rpc/server.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
  validator/usage.go
Labels: API, AccountsV2, OK to merge, Ready For Review

#7169 Prevent far future target epoch for attestation state
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
Labels: Ready For Review

#7170 Remove deprecated health end points
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/rpc/BUILD.bazel
  validator/rpc/gateway/gateway.go
  validator/rpc/health.go
  validator/rpc/health_test.go
  validator/rpc/server.go
Labels: Ready For Review

#7171 Add Node Connection Endpoint to Validator Client
  beacon-chain/gateway/cors.go
  beacon-chain/main.go
  beacon-chain/usage.go
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/client/service.go
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/gateway/gateway.go
  validator/rpc/health.go
  validator/rpc/health_test.go
  validator/rpc/intercepter.go
  validator/rpc/intercepter_test.go
  validator/rpc/server.go
Labels: API, OK to merge, Ready For Review

#7172 Implement Create and List Accounts Validator RPC
  validator/keymanager/v2/derived/derived.go
  validator/keymanager/v2/derived/derived_test.go
  validator/keymanager/v2/direct/BUILD.bazel
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/direct_test.go
  validator/rpc/BUILD.bazel
  validator/rpc/accounts.go
  validator/rpc/accounts_test.go
  validator/rpc/auth.go
  validator/rpc/gateway/gateway.go
  validator/rpc/server.go
Labels: AccountsV2, OK to merge, Ready For Review

#7178 Revert 6966
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/node/node.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/sync/initial-sync/service.go
  shared/params/config.go
  shared/params/testnet_medalla_config.go
Labels: Ready For Review

#7175 Fixes timer resources leak in CountdownToGenesis
  shared/slotutil/BUILD.bazel
  shared/slotutil/countdown.go
  shared/slotutil/countdown_test.go
  shared/slotutil/slotutil_test.go
Labels: OK to merge, Ready For Review

#7179 Add Beacon Gateway Flag to Validator Client
  beacon-chain/flags/base.go
  beacon-chain/gateway/cors.go
  validator/client/service.go
  validator/flags/flags.go
  validator/main.go
  validator/node/node.go
  validator/rpc/health.go
  validator/rpc/health_test.go
  validator/rpc/server.go
  validator/usage.go
Labels: API, OK to merge, Ready For Review

#7180 Pipelines for `ProcessBlockNoVerifyAttSigs` and `ProcessBlockStateRoot`
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/header.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/blocks/spectest/block_header_test.go
  beacon-chain/core/state/transition.go
  fuzz/block_header_fuzz.go
Labels: Ready For Review

#7182 Ensure `aggregateAndProofSig` returns when err'ing
  validator/client/aggregate.go
  validator/client/aggregate_test.go
Labels: OK to merge, Ready For Review

#7177 Hash Pubsub Messages Correctly
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/pubsub.go
  beacon-chain/p2p/pubsub_test.go
Labels: Ready For Review

#7187 Prevent zero hashes signatures in `SubmitSignedAggregateSelectionProof`
  beacon-chain/rpc/validator/aggregator.go
  beacon-chain/rpc/validator/aggregator_test.go
Labels: Ready For Review

#7189 Improves asyncutils/Debounce
  shared/asyncutil/BUILD.bazel
  shared/asyncutil/debounce.go
  shared/asyncutil/debounce_test.go
Labels: OK to merge, Ready For Review

#7191 Revert "Pipelines for `ProcessBlockNoVerifyAttSigs` and `ProcessBlockStateRoot`"
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/header.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/blocks/spectest/block_header_test.go
  beacon-chain/core/state/transition.go
  fuzz/block_header_fuzz.go
Labels: OK to merge, Priority: Critical, Ready For Review

#7176 Safer validator protection db dir
  shared/fileutil/BUILD.bazel
  shared/fileutil/fileutil.go
  validator/db/kv/db.go
  validator/node/BUILD.bazel
  validator/node/node.go
Labels: OK to merge, Ready For Review, Slasher

#7190 Fix unclosed tickers/timers
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/operations/attestations/prune_expired.go
  beacon-chain/p2p/peers/scorer_manager_test.go
  beacon-chain/powchain/service.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  shared/fileutil/fileutil.go
  slasher/beaconclient/chain_data.go
  slasher/beaconclient/receivers.go
  validator/client/validator.go
Labels: OK to merge, Ready For Review

#7181 Fix Health Reporting for Validator Client Node Connection
  validator/rpc/health.go
  validator/rpc/health_test.go
Labels: API, OK to merge, Ready For Review

#7194 Add Chain Genesis Info to Node Connection Response
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  validator/client/service.go
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/health.go
  validator/rpc/health_test.go
  validator/rpc/server.go
Labels: API, OK to merge, Ready For Review

#7192 Fix span names in `transition.go`
  beacon-chain/core/state/transition.go
Labels: Ready For Review

#7195 Fix Small Issue in Validator RPC Health Endpoint
  validator/rpc/health.go
  validator/rpc/health_test.go
Labels: API, OK to merge, Ready For Review

#7136 Replace context.Background() with more appropriate context
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/state/state.go
  beacon-chain/db/kv/migration_archived_index.go
  beacon-chain/node/node.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/handshake.go
  beacon-chain/p2p/pubsub_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/powchain/deposit.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/validate_beacon_blocks.go
  fuzz/rpc_status_fuzz.go
  shared/event/subscription.go
  shared/mock/beacon_validator_client_mock.go
  slasher/node/node.go
  validator/accounts/v1/status.go
  validator/accounts/v2/accounts_deposit.go
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/accounts_list.go
  validator/accounts/v2/accounts_list_test.go
  validator/client/attest.go
  validator/client/attest_test.go
  validator/client/propose.go
  validator/client/service.go
  validator/keymanager/v1/direct.go
  validator/keymanager/v1/direct_test.go
  validator/keymanager/v1/keymanager.go
  validator/keymanager/v1/remote.go
  validator/keymanager/v1/wallet.go
  validator/keymanager/v2/direct/direct.go
  validator/main.go
  validator/node/node.go
Labels: OK to merge, Ready For Review

#7162 Voluntary exit CLI/Client integration
  beacon-chain/core/blocks/exit.go
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_exit.go
  validator/accounts/v2/accounts_exit_test.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/iface/BUILD.bazel
  validator/accounts/v2/iface/wallet.go
  validator/accounts/v2/testing/BUILD.bazel
  validator/accounts/v2/testing/mock.go
  validator/client/BUILD.bazel
  validator/client/metrics.go
  validator/client/propose.go
  validator/client/propose_test.go
  validator/client/service.go
  validator/client/validator.go
  validator/flags/flags.go
Labels: Ready For Review

#7199 Verify attesting indices in no verify method
  beacon-chain/core/blocks/attestation.go
Labels: Ready For Review

#7207 Correct accounts and validator error messages
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/blocks/exit_test.go
  validator/keymanager/v2/direct/direct.go
Labels: OK to merge, Ready For Review

#7203 Disallows bitlist duplicates in seen_bits cache
  beacon-chain/operations/attestations/kv/seen_bits.go
  beacon-chain/operations/attestations/kv/seen_bits_test.go
Labels: OK to merge, Ready For Review

#7206 Att aggregator filter by slot and index
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/pool.go
  beacon-chain/rpc/validator/aggregator.go
Labels: OK to merge, Ready For Review

#7201 Implement helper method `WeakSubjectivityCheckptEpoch`
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  shared/params/config.go
  shared/params/mainnet_config.go
Labels: OK to merge, Ready For Review

#7204 Removes attestation pool pruning from UnaggregatedAttestations getter
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/pool.go
  beacon-chain/operations/attestations/prune_expired.go
Labels: OK to merge, Ready For Review

#7209 Check attestation slot before broadcast
  beacon-chain/rpc/validator/aggregator.go
  beacon-chain/rpc/validator/aggregator_test.go
Labels: Ready For Review

#7205 Fix rename issue
  shared/fileutil/BUILD.bazel
  shared/fileutil/fileutil.go
  shared/fileutil/fileutil_test.go
  validator/node/node.go
Labels: Ready For Review

#7214 Invert enable-finalized-deposits-cache
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge

#7188 Fix propose protect error handling
  slasher/rpc/server.go
  validator/client/propose_protect.go
  validator/slashing-protection/external.go
  validator/slashing-protection/external_test.go
  validator/slashing-protection/protector.go
  validator/testing/protector_mock.go
Labels: Ready For Review, Slasher

#7217 Reverse error condition.
  beacon-chain/operations/attestations/prune_expired.go
Labels: OK to merge

#7221 Skip initial roughtime result when `EnableRoughtime` is disabled
  shared/roughtime/roughtime.go
Labels: Ready For Review

#7197 Local protection proposal schema update
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/db/kv/new_proposal_history.go
  validator/db/kv/new_proposal_history_test.go
  validator/db/kv/schema.go
Labels: OK to merge, Ready For Review, Slasher

#7226 Fix out of bound check in `AncestorRoot`
  beacon-chain/forkchoice/protoarray/nodes_test.go
  beacon-chain/forkchoice/protoarray/store.go
Labels: Bug, OK to merge, Ready For Review

#7215 Shadowed Predeclared Indentifier analyzer
  BUILD.bazel
  nogo_config.json
  shared/cmd/password_reader.go
  shared/event/feed_test.go
  shared/params/loader.go
  shared/testutil/state.go
  shared/trieutil/sparse_merkle_test.go
  slasher/db/kv/spanner_new.go
  tools/analyzers/shadowpredecl/BUILD.bazel
  tools/analyzers/shadowpredecl/analyzer.go
  tools/analyzers/shadowpredecl/analyzer_test.go
  tools/analyzers/shadowpredecl/testdata/BUILD.bazel
  tools/analyzers/shadowpredecl/testdata/shadow.go
Labels: Ready For Review

#7233 fix exit comment
  beacon-chain/core/blocks/exit.go
Labels: OK to merge

#7234 Updates proposer tests namings
  beacon-chain/rpc/validator/proposer_test.go
Labels: OK to merge, Ready For Review

#6625 Add beacon state unmarshal fuzzer, afl support
  .bazelrc
  .gitignore
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_disabled.go
  beacon-chain/cache/committees.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
  beacon-chain/db/BUILD.bazel
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/voluntaryexits/BUILD.bazel
  beacon-chain/p2p/encoder/BUILD.bazel
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/fuzz_exports.go
  fuzz/BUILD.bazel
  fuzz/README.md
  fuzz/attestation_fuzz.go
  fuzz/attester_slashing_fuzz.go
  fuzz/block_fuzz.go
  fuzz/block_header_fuzz.go
  fuzz/deposit_corpus/.gitkeep
  fuzz/deposit_fuzz.go
  fuzz/generated.ssz.go
  fuzz/inputs.go
  fuzz/proposer_slashing_fuzz.go
  fuzz/ssz_encoder_attestations_fuzz.go
  fuzz/state_fuzz.go
  fuzz/voluntary_exit_corpus/.gitkeep
  fuzz/voluntary_exit_fuzz.go
  proto/testing/BUILD.bazel
  scripts/upload_fuzzers.sh
  shared/params/spectest/config.go
  shared/params/testutils.go
  shared/testutil/spectest.go
  third_party/afl/BUILD.bazel
  third_party/afl/afl-fuzz
  third_party/afl/afl-fuzz.c
  third_party/afl/afl-showmap.c
  third_party/afl/afl_driver.cpp
  third_party/afl/alloc-inl.h
  third_party/afl/config.h
  third_party/afl/debug.h
  third_party/afl/hash.h
  third_party/afl/llvm_mode/afl-llvm-rt.o.c
  third_party/afl/types.h
  tools/BUILD.bazel
  tools/fuzzit_wrapper.sh
  tools/go/def.bzl
  tools/go/fuzz.bzl
Labels: Fuzz, Ready For Review

#7235 Add Spadina config
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/params/BUILD.bazel
  shared/params/testnet_spadina_config.go
Labels: Ready For Review

#7242 Opt out `--use-check-point-cache`
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#6363 QSP-16 Fix Support for IPv6
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/options_test.go
  beacon-chain/p2p/utils.go
  shared/iputils/external_ip.go
  shared/iputils/external_ip_test.go
Labels: Audit, Ready For Review

#7244 Opt out --batch-block-verify
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Ready For Review

#7246 Core pkg: properly return errs
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/db/kv/regen_historical_states.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
Labels: Audit, Ready For Review

#7240 Streaming Logs via Websocket Server
  beacon-chain/core/feed/BUILD.bazel
  go.mod
  shared/logutil/BUILD.bazel
  shared/logutil/logutil.go
  shared/logutil/stream.go
  shared/prometheus/BUILD.bazel
  shared/prometheus/service.go
Labels: Ready For Review

#7245 Save cached blocks before `Stop()` in blockchains service
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: OK to merge, Ready For Review

#7222 Use passphrase for HD-wallets
  validator/accounts/v2/accounts_create_test.go
  validator/accounts/v2/wallet_create_test.go
  validator/accounts/v2/wallet_test.go
  validator/keymanager/v2/derived/derived.go
Labels: AccountsV2, OK to merge, Ready For Review

#7254 Use Bufio Large Buffer Instead of Scanner for Large Files in E2E
  endtoend/helpers/helpers.go
Labels: OK to merge, Ready For Review

#7247 Restructure Prysm Wallet V2 Package to Prevent Import Cycles
  shared/promptutil/prompt.go
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_backup.go
  validator/accounts/v2/accounts_backup_test.go
  validator/accounts/v2/accounts_create.go
  validator/accounts/v2/accounts_create_test.go
  validator/accounts/v2/accounts_delete.go
  validator/accounts/v2/accounts_delete_test.go
  validator/accounts/v2/accounts_deposit.go
  validator/accounts/v2/accounts_deposit_test.go
  validator/accounts/v2/accounts_exit.go
  validator/accounts/v2/accounts_exit_test.go
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/accounts_import_test.go
  validator/accounts/v2/accounts_list.go
  validator/accounts/v2/accounts_list_test.go
  validator/accounts/v2/prompt/BUILD.bazel
  validator/accounts/v2/prompt/prompt.go
  validator/accounts/v2/wallet/BUILD.bazel
  validator/accounts/v2/wallet/wallet.go
  validator/accounts/v2/wallet/wallet_test.go
  validator/accounts/v2/wallet_create.go
  validator/accounts/v2/wallet_create_test.go
  validator/accounts/v2/wallet_edit.go
  validator/accounts/v2/wallet_edit_test.go
  validator/accounts/v2/wallet_recover.go
  validator/accounts/v2/wallet_recover_test.go
  validator/client/BUILD.bazel
  validator/client/service.go
  validator/client/validator.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/accounts_test.go
  validator/rpc/auth.go
  validator/rpc/auth_test.go
  validator/rpc/server.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: AccountsV2, Ready For Review, Refactor

#7257 Fix IPV6 Address Retrieval
  shared/iputils/external_ip.go
  shared/iputils/external_ip_test.go
Labels: OK to merge, Priority: High, Ready For Review

#7258 Add Flag To Disable Initial Sync
  beacon-chain/flags/base.go
  beacon-chain/flags/config.go
  beacon-chain/main.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/usage.go
Labels: OK to merge, Ready For Review

#7259 Disables resync when init-sync is disabled
  beacon-chain/sync/service.go
Labels: OK to merge, Ready For Review

#7260 Fix gazelle warning when `fuzzing_enabled` is not provided
  beacon-chain/cache/BUILD.bazel
Labels: OK to merge, Ready For Review

#7249 No-op Instruction analyzer
  BUILD.bazel
  nogo_config.json
  shared/bls/blst/signature.go
  shared/bls/blst/signature_test.go
  shared/bls/herumi/signature.go
  shared/bls/herumi/signature_test.go
  tools/analyzers/nop/BUILD.bazel
  tools/analyzers/nop/analyzer.go
  tools/analyzers/nop/analyzer_test.go
  tools/analyzers/nop/testdata/BUILD.bazel
  tools/analyzers/nop/testdata/no_op.go
Labels: OK to merge, Ready For Review

#7216 Implement and test GetWeakSubjectivityCheckpoint
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/validators_test.go
  deps.bzl
  go.mod
  go.sum
  shared/mock/beacon_service_mock.go
  shared/params/mainnet_config.go
Labels: Ready For Review

#7261 Update Spadina fork version to 0x02
  shared/params/testnet_spadina_config.go
Labels: OK to merge, Ready For Review

#7256 Add and verify `weak-subjectivity-checkpoint` flag
  beacon-chain/flags/base.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/helper.go
  beacon-chain/node/helper_test.go
  beacon-chain/node/node.go
  beacon-chain/sync/initial-sync/service.go
Labels: Ready For Review

#7263 Websocket Connection Fixes
  shared/logutil/stream.go
Labels: OK to merge, Ready For Review

#7265 Streaming logs: add backfill of messages for new connections"
  shared/logutil/BUILD.bazel
  shared/logutil/stream.go
  shared/logutil/stream_test.go
  shared/mock/beacon_service_mock.go
Labels: Ready For Review

#7252 Check that the headers are equal while ignoring the signature for proposer slashings
  beacon-chain/core/blocks/proposer_slashing.go
  beacon-chain/core/blocks/proposer_slashing_test.go
Labels: Bug, Ready For Review

#7200 Align eth1data Majority Vote with the spec
  beacon-chain/powchain/testing/mock.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
Labels: OK to merge, Ready For Review

#7270 Add missing error handling in slasher
  slasher/rpc/server.go
Labels: OK to merge, Ready For Review

#7272 Fix Blst Signature Copy Test
  shared/bls/blst/BUILD.bazel
  shared/bls/blst/signature_test.go
Labels: OK to merge, Ready For Review

#7251 Update weak subjectivity check point computation
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/core/helpers/slot_epoch_test.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
Labels: Ready For Review

#7267 Attestation proposing: more tests
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/proposer_utils.go
Labels: OK to merge, Ready For Review

#7268 Improve error message when creating a wallet in place of one that already exists
  validator/accounts/v2/wallet_create.go
  validator/accounts/v2/wallet_create_test.go
Labels: OK to merge

#7276 Update spec tests to v0.12.3
  WORKSPACE
  beacon-chain/core/epoch/precompute/spectest/rewards_penalties_test.go
  proto/testing/ssz_static_mainnet_test.go
Labels: OK to merge, Ready For Review

#7275 Add config `PROPORTIONAL_SLASHING_MULTIPLIER`
  beacon-chain/core/epoch/epoch_processing.go
  shared/params/config.go
  shared/params/mainnet_config.go
  shared/params/minimal_config.go
Labels: OK to merge, Ready For Review

#7278 Two more gossip validations for unaggregated atts subnet
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
Labels: Ready For Review

#7285 Init sync refactor state initialization check + tests
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
Labels: OK to merge, Ready For Review, Test

#7273 Implement ChangeWalletPassword API Endpoint
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/keymanager/v2/derived/derived.go
  validator/keymanager/v2/derived/derived_test.go
  validator/keymanager/v2/direct/direct.go
  validator/keymanager/v2/direct/direct_test.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: API, AccountsV2, Ready For Review

#7292 Fix sha after v0.12.3 tarballs were re-uploaded. Unskip test to resolve #7277.
  WORKSPACE
  proto/testing/ssz_static_mainnet_test.go
Labels: OK to merge, Priority: Critical, Ready For Review

#7291 Remove renovate.json
  renovate.json
Labels: OK to merge, Ready For Review

#7289 Add slasher grpc logs
  slasher/beaconclient/BUILD.bazel
  slasher/beaconclient/receivers.go
  slasher/beaconclient/service.go
Labels: OK to merge, Ready For Review

#7288 Add target epoch and slot consistency check
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
Labels: OK to merge, Ready For Review

#7299 Remove Roughtime Usage From Prysm
  deps.bzl
  go.mod
  go.sum
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/roughtime/BUILD.bazel
  shared/roughtime/roughtime.go
Labels: OK to merge, Ready For Review

#7300 Fix prompt default handling
  shared/promptutil/BUILD.bazel
  shared/promptutil/prompt.go
  shared/promptutil/validate_test.go
Labels: OK to merge

#7303 Update Go-Ethereum Fork
  beacon-chain/p2p/metaData
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#7295 Store Hashed Password to Wallet Path
  validator/accounts/v2/accounts_create_test.go
  validator/accounts/v2/accounts_exit_test.go
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/wallet/BUILD.bazel
  validator/accounts/v2/wallet/wallet.go
  validator/accounts/v2/wallet_create.go
  validator/accounts/v2/wallet_recover.go
  validator/accounts/v2/wallet_recover_test.go
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/db/kv/schema.go
  validator/db/kv/web_api.go
  validator/db/kv/web_api_test.go
  validator/keymanager/v2/derived/derived.go
  validator/rpc/BUILD.bazel
  validator/rpc/accounts_test.go
  validator/rpc/auth.go
  validator/rpc/auth_test.go
  validator/rpc/intercepter.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: AccountsV2, Bug, OK to merge, Ready For Review

#7304 Update Message ID
  beacon-chain/p2p/pubsub.go
  beacon-chain/p2p/pubsub_test.go
Labels: OK to merge

#7290 Disallow Creation of Multiple Wallets at Wallet Path
  validator/accounts/v2/wallet/wallet.go
  validator/accounts/v2/wallet_create.go
  validator/accounts/v2/wallet_create_test.go
Labels: AccountsV2, Bug, OK to merge, Ready For Review

#7311 Fixes e2e "chain started" check
  beacon-chain/sync/service.go
  endtoend/endtoend_test.go
Labels: OK to merge, Ready For Review

#7307 Log grpc error chain
  beacon-chain/rpc/beacon/validators.go
Labels: OK to merge, Ready For Review

#7308 Remove long deprecated historical regen states in DB
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/check_historical_state.go
  beacon-chain/db/kv/check_historical_test_test.go
  beacon-chain/db/kv/regen_historical_states.go
  beacon-chain/node/node.go
Labels: OK to merge, Ready For Review

#7309 Add spadina network name
  shared/params/testnet_spadina_config.go
Labels: OK to merge, Ready For Review

#7286 Init sync: minor refactoring and more tests for Service
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
Labels: OK to merge, Ready For Review, Test

#7314 Fix Validator For Spadina
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/cmd_wallet.go
Labels: OK to merge, Ready For Review

#7316 Better naming for constructor funcs
  beacon-chain/blockchain/service_test.go
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/cache/depositcache/deposits_cache_test.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/node/node.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/rpc/validator/status_test.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/service.go
  fuzz/rpc_status_fuzz.go
  shared/keystore/key_test.go
  shared/keystore/keystore.go
  shared/keystore/keystore_test.go
  shared/prometheus/logrus_collector_test.go
  shared/prometheus/service.go
  shared/prometheus/service_test.go
  slasher/beaconclient/service.go
  slasher/detection/service.go
  slasher/node/node.go
  slasher/rpc/server_test.go
  tools/sendDepositTx/sendDeposits.go
  validator/accounts/v1/account.go
  validator/accounts/v1/account_test.go
  validator/accounts/v2/accounts_import.go
  validator/accounts/v2/wallet/wallet.go
  validator/accounts/v2/wallet_create.go
  validator/accounts/v2/wallet_create_test.go
  validator/accounts/v2/wallet_recover.go
  validator/node/node.go
  validator/slashing-protection/slasher_client.go
Labels: OK to merge, Ready For Review

#7318 Fix Bazel Reference For Go-Ethereum
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/block_reader_test.go
  deps.bzl
Labels: OK to merge, Ready For Review

#7321 Unnecessary Slice-to-Slice Conversion analyzer
  BUILD.bazel
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/blocks/block_regression_test.go
  beacon-chain/core/blocks/exit_test.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/blocks/signature.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/db/kv/state.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/rpc/validator/aggregator_test.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/server_test.go
  beacon-chain/state/cloners.go
  beacon-chain/state/getters.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  beacon-chain/sync/validate_voluntary_exit_test.go
  contracts/deposit-contract/depositContract_test.go
  contracts/deposit-contract/testutils.go
  nogo_config.json
  shared/bytesutil/bytes_test.go
  shared/depositutil/deposit_test.go
  shared/hashutil/merkleRoot_test.go
  shared/htrutils/merkleize.go
  shared/testutil/deposits.go
  shared/testutil/helpers_test.go
  slasher/db/kv/indexed_attestations.go
  slasher/rpc/server.go
  tools/analyzers/slicedirect/BUILD.bazel
  tools/analyzers/slicedirect/analyzer.go
  tools/analyzers/slicedirect/analyzer_test.go
  tools/analyzers/slicedirect/testdata/BUILD.bazel
  tools/analyzers/slicedirect/testdata/slice.go
  validator/accounts/v1/account.go
  validator/client/metrics.go
  validator/client/propose.go
  validator/client/validator.go
  validator/db/kv/new_proposal_history.go
Labels: OK to merge, Ready For Review

#7313 Fix an edge case when loading replay start state by slot
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: OK to merge, Ready For Review

#7323 Return an error when any of the eth1 clients are nil
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/block_reader.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/service.go
Labels: OK to merge, Ready For Review

#7327 Update Bootnode With New Flags
  tools/bootnode/BUILD.bazel
  tools/bootnode/bootnode.go
Labels: OK to merge, Ready For Review

#7328 Update BLST to Latest Commit
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#7330 Add Spadina Bootnodes
  shared/params/testnet_spadina_config.go
Labels: OK to merge, Ready For Review

#7332 Package-level comments for static analyzers
  tools/analyzers/comparesame/analyzer.go
  tools/analyzers/cryptorand/analyzer.go
  tools/analyzers/featureconfig/analyzer.go
  tools/analyzers/maligned/analyzer.go
  tools/analyzers/nop/analyzer.go
  tools/analyzers/shadowpredecl/analyzer.go
Labels: OK to merge, Ready For Review

#7305 Make voluntary exits release-ready
  shared/promptutil/validate.go
  shared/promptutil/validate_test.go
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_exit.go
  validator/accounts/v2/accounts_exit_test.go
  validator/accounts/v2/cmd_accounts.go
Labels: OK to merge, Ready For Review

#7320 Improves test coverage of init-sync queue
  beacon-chain/sync/initial-sync/blocks_queue_test.go
Labels: OK to merge, Ready For Review, Test

#7338 Revert 7242: Opt out --use-check-point-cache
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#7326 Skip duplicated aggregated attestation in pending queue
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
Labels: OK to merge, Ready For Review

#7324 Fix Change Wallet Password Logic
  validator/keymanager/v2/direct/BUILD.bazel
  validator/keymanager/v2/direct/direct.go
  validator/rpc/auth.go
  validator/rpc/wallet.go
Labels: AccountsV2, OK to merge, Ready For Review

#7340 Reset hot state cache size to 32
  beacon-chain/cache/hot_state_cache.go
Labels: OK to merge, Ready For Review

#7341 Implement Wallet Config and HasWallet Endpoints
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/rpc/BUILD.bazel
  validator/rpc/auth.go
  validator/rpc/intercepter.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: API, Ready For Review

#7337 Reject Messages With Invalid Fields in GossipSub
  beacon-chain/p2p/service.go
Labels: Networking, OK to merge

#7336 Better Chainstart Logging
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: OK to merge, Ready For Review

#7345 Disable Libp2p Protocols
  beacon-chain/p2p/options.go
Labels: OK to merge, Ready For Review

#7348 Warn About Deprecation of Accounts-V1 Within the Next 2 Releases
  shared/featureconfig/config.go
Labels: OK to merge, Ready For Review

#7347 Display More Info for Validating Keys on Startup
  validator/client/service.go
  validator/node/node.go
Labels: OK to merge, Ready For Review

#7344 Add, use and test `VerifyWeakSubjectivityRoot`
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/weak_subjectivity_checks.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/usage.go
Labels: OK to merge, Ready For Review

#7352 Add New Compiler Flags for BLST
  shared/bls/blst/bls_benchmark_test.go
  third_party/blst/blst.BUILD
Labels: OK to merge, Ready For Review

#7351 Fix panic that happens if you wallet-v2 recover 1 account
  validator/accounts/v2/wallet_recover.go
  validator/accounts/v2/wallet_recover_test.go
Labels: OK to merge

#7133 gRPC load balancing
  validator/client/BUILD.bazel
  validator/client/multiple_endpoints_grpc_resolver.go
  validator/client/service.go
Labels: OK to merge

#7354 Fix ListValidators inactive check
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge, Ready For Review

#7359 Ensure block root is non zeros for setting head before genesis
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: OK to merge, Ready For Review

#7361 Fix URL to voluntary exit documentation
  validator/accounts/v2/accounts_exit.go
Labels: OK to merge, Ready For Review

#7365 Fixes NotNil assertion
  beacon-chain/blockchain/process_attestation_test.go
  shared/testutil/assertions/BUILD.bazel
  shared/testutil/assertions/assertions.go
  shared/testutil/assertions/assertions_test.go
  slasher/db/kv/block_header_test.go
Labels: OK to merge, Ready For Review, Test

#7368 Remaining Proto Definitions for Validator RPC Methods
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/rpc/accounts.go
  validator/rpc/accounts_test.go
  validator/rpc/wallet.go
Labels: API, AccountsV2, OK to merge, Ready For Review

#7357 Remove processSlots from slashing check
  beacon-chain/core/blocks/proposer_slashing.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_proposer_slashing.go
Labels: Ready For Review

#7363 Fix failing static analyzer tests
  tools/analyzers/README.md
  tools/analyzers/cryptorand/testdata/custom_import.go
  tools/analyzers/cryptorand/testdata/rand_new.go
  tools/analyzers/nop/testdata/no_op.go
Labels: OK to merge, Ready For Review

#7370 accommodate systems that use sha256sum
  prysm.sh
Labels: OK to merge

#7364 Fix Finalized Epoch Checks
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/finalized_block_roots_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
Labels: Ready For Review

#7379 Remove Deposit Command from Validator Client
  validator/accounts/v2/BUILD.bazel
  validator/accounts/v2/accounts_deposit.go
  validator/accounts/v2/accounts_deposit_test.go
  validator/accounts/v2/cmd_accounts.go
Labels: OK to merge, Ready For Review

#7349 Introduce checks for existing wallets into two edge cases
  validator/accounts/v2/wallet/wallet.go
  validator/accounts/v2/wallet/wallet_test.go
  validator/accounts/v2/wallet_create.go
  validator/accounts/v2/wallet_recover.go
  validator/accounts/v2/wallet_recover_test.go
  validator/rpc/auth.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: Ready For Review

#7385 Add slasher support for different testnets
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge

#7378 Ensure genesis state retrieval doesn't use zero hashes root
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: OK to merge, Ready For Review

#7388 Removes unused validator flags
  validator/flags/flags.go
Labels: OK to merge, Ready For Review

#7391 Add Zinken config
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  shared/params/BUILD.bazel
  shared/params/testnet_zinken_config.go
  validator/accounts/v2/cmd_accounts.go
  validator/accounts/v2/cmd_wallet.go
Labels: Ready For Review

#7389 Import Accounts RPC Implementation
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: API, Ready For Review

#7358 Optional services flags
  slasher/main.go
  slasher/node/node.go
  slasher/usage.go
  validator/flags/flags.go
  validator/main.go
  validator/node/node.go
  validator/usage.go
Labels: OK to merge, Ready For Review

#7395 Update min genesis time for Zinken
  shared/params/testnet_zinken_config.go
Labels: OK to merge, Ready For Review

#7398 Check err for `filterAttestationsForBlockInclusion`
  beacon-chain/rpc/validator/proposer.go
Labels: OK to merge, Ready For Review

#7396 DB: Return error when saving nil eth1data
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/powchain.go
  beacon-chain/db/kv/powchain_test.go
Labels: OK to merge, Ready For Review
