Repository OffchainLabs/prysm, pull requests merged in 2021-06, with the labels that each got.

#8872 Feature/debian packages
  beacon-chain/package/BUILD.bazel
  beacon-chain/package/beacon-chain.yaml
  beacon-chain/package/postinst.sh
  beacon-chain/package/preinst.sh
  beacon-chain/package/prysm-beacon-chain.service
  shared/BUILD.bazel
  validator/package/BUILD.bazel
  validator/package/postinst.sh
  validator/package/preinst.sh
  validator/package/prysm-validator.service
  validator/package/validator.yaml
Labels: OK to merge

#8967 Altair: Add sync committee spec test
  spectest/mainnet/altair/operations/BUILD.bazel
  spectest/mainnet/altair/operations/sync_committee_test.go
  spectest/minimal/altair/operations/BUILD.bazel
  spectest/minimal/altair/operations/sync_committee_test.go
  spectest/shared/altair/operations/BUILD.bazel
  spectest/shared/altair/operations/sync_committee.go
Labels: Ready For Review

#8961 Fix Interop Mode
  beacon-chain/node/config.go
  beacon-chain/node/config_test.go
  beacon-chain/node/node.go
Labels: OK to merge, Ready For Review

#8907 Altair: new protos/state object
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/generated.ssz.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
Labels: OK to merge, Ready For Review

#8962 Add Metadata V2 Object and Interface
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/peers/BUILD.bazel
  beacon-chain/p2p/peers/peerdata/BUILD.bazel
  beacon-chain/p2p/peers/peerdata/store.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_metadataprovider.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/p2p/utils.go
  beacon-chain/rpc/debug/p2p.go
  beacon-chain/rpc/nodev1/BUILD.bazel
  beacon-chain/rpc/nodev1/node.go
  beacon-chain/rpc/nodev1/node_test.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_metadata_test.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_ping_test.go
  beacon-chain/sync/rpc_status_test.go
  fuzz/generated.ssz.go
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/generated.ssz.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/messages.proto
  proto/beacon/rpc/v1/debug.pb.go
  proto/beacon/rpc/v1/debug.proto
  shared/grpcutils/grpcutils_test.go
  shared/interfaces/BUILD.bazel
  shared/interfaces/metadata_interface.go
  shared/interfaces/metadata_wrapper.go
  tools/analyzers/interfacechecker/analyzer.go
  validator/rpc/beacon_test.go
  validator/slashing-protection/cli_import_export_test.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/slasher_client_test.go
Labels: Networking, Ready For Review

#8969 Altair: Utilize block interface for clean up
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/attestation.go
  beacon-chain/core/altair/attestation_test.go
  beacon-chain/core/altair/block.go
  beacon-chain/core/altair/block_test.go
  beacon-chain/core/altair/state.go
  beacon-chain/core/altair/state_fuzz_test.go
  beacon-chain/core/altair/transition.go
  beacon-chain/core/altair/transition_fuzz_test.go
  beacon-chain/core/altair/transition_no_verify_sig.go
  beacon-chain/core/altair/transition_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/genesis.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/altair_transition_no_verify_sig_test.go
  beacon-chain/core/state/state.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_no_verify_sig.go
  beacon-chain/state/interface/phase0.go
  beacon-chain/state/state-altair/BUILD.bazel
  beacon-chain/state/state-altair/getters.go
  beacon-chain/state/stateV0/BUILD.bazel
  beacon-chain/state/stateV0/getters_misc.go
  shared/interfaces/BUILD.bazel
  shared/interfaces/altair_block_wrapper.go
  shared/interfaces/block_interface.go
  shared/interfaces/phase0_block_wrapper.go
  shared/interfaces/version/BUILD.bazel
  shared/interfaces/version/version.go
  shared/testutil/BUILD.bazel
  shared/testutil/altair/BUILD.bazel
  shared/testutil/altair/altair.go
  shared/testutil/helpers.go
  spectest/shared/altair/finality/BUILD.bazel
  spectest/shared/altair/finality/finality.go
  spectest/shared/altair/sanity/BUILD.bazel
  spectest/shared/altair/sanity/block_processing.go
  spectest/shared/altair/sanity/slot_processing.go
Labels: Ready For Review

#8972 use urfave defaulting method for correct help text
  cmd/client-stats/flags/flags.go
  cmd/client-stats/main.go
Labels: OK to merge

#8973 Checkin Generated Protobufs and Proto Files for EthereumAPIs
  proto/eth/LICENSE
  proto/eth/ext/BUILD.bazel
  proto/eth/ext/options.pb.go
  proto/eth/ext/options.proto
  proto/eth/v1/BUILD.bazel
  proto/eth/v1/README.md
  proto/eth/v1/attestation.pb.go
  proto/eth/v1/attestation.pb.gw.go
  proto/eth/v1/attestation.proto
  proto/eth/v1/beacon_block.pb.go
  proto/eth/v1/beacon_block.pb.gw.go
  proto/eth/v1/beacon_block.proto
  proto/eth/v1/beacon_chain_service.pb.go
  proto/eth/v1/beacon_chain_service.pb.gw.go
  proto/eth/v1/beacon_chain_service.proto
  proto/eth/v1/beacon_debug_service.pb.go
  proto/eth/v1/beacon_debug_service.pb.gw.go
  proto/eth/v1/beacon_debug_service.proto
  proto/eth/v1/beacon_state.pb.go
  proto/eth/v1/beacon_state.pb.gw.go
  proto/eth/v1/beacon_state.proto
  proto/eth/v1/generated.ssz.go
  proto/eth/v1/node.pb.go
  proto/eth/v1/node.pb.gw.go
  proto/eth/v1/node.proto
  proto/eth/v1/testdata/invalid-offset.attestation.ssz
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator.pb.gw.go
  proto/eth/v1/validator.proto
  proto/eth/v1/validator_service.pb.go
  proto/eth/v1/validator_service.pb.gw.go
  proto/eth/v1/validator_service.proto
  proto/eth/v1alpha1/BUILD.bazel
  proto/eth/v1alpha1/README.md
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/attestation.pb.gw.go
  proto/eth/v1alpha1/attestation.proto
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_block.pb.gw.go
  proto/eth/v1alpha1/beacon_block.proto
  proto/eth/v1alpha1/beacon_block_altair.pb.go
  proto/eth/v1alpha1/beacon_block_altair.pb.gw.go
  proto/eth/v1alpha1/beacon_block_altair.proto
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.gw.go
  proto/eth/v1alpha1/beacon_chain.proto
  proto/eth/v1alpha1/generated.ssz.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/node.pb.gw.go
  proto/eth/v1alpha1/node.proto
  proto/eth/v1alpha1/swagger.proto
  proto/eth/v1alpha1/swagger.swagger.json
  proto/eth/v1alpha1/swagger_description.md
  proto/eth/v1alpha1/sync_committee.pb.go
  proto/eth/v1alpha1/sync_committee.pb.gw.go
  proto/eth/v1alpha1/sync_committee.proto
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.pb.gw.go
  proto/eth/v1alpha1/validator.proto
Labels: OK to merge, Ready For Review

#8977 Add clientstats spec as a README.md
  shared/clientstats/README.md
Labels: OK to merge

#8978 Enhance attestation signature set checks
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/signature.go
Labels: Ready For Review

#8980 Mirror EthereumAPIs Bash Script
  scripts/mirror-ethereumapis.sh
Labels: OK to merge, Ready For Review

#8986 Fix EthereumAPIs Mirror Script
  scripts/mirror-ethereumapis.sh
Labels: OK to merge, Ready For Review

#8982 Add caches for sync committee signature and contribution
  beacon-chain/operations/synccommittee/BUILD.bazel
  beacon-chain/operations/synccommittee/contribution.go
  beacon-chain/operations/synccommittee/contribution_test.go
  beacon-chain/operations/synccommittee/error.go
  beacon-chain/operations/synccommittee/kv.go
  beacon-chain/operations/synccommittee/signature.go
  beacon-chain/operations/synccommittee/signature_test.go
  go.sum
  shared/copyutil/cloners.go
Labels: Ready For Review

#8905 Handle Multiple Block Types in Req/Resp
  beacon-chain/blockchain/chain_info.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/encoder/network_encoding.go
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/encoder/ssz_test.go
  beacon-chain/p2p/rpc_topic_mappings.go
  beacon-chain/p2p/sender.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/p2p/types/BUILD.bazel
  beacon-chain/p2p/types/object_mapping.go
  beacon-chain/p2p/types/object_mapping_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/context.go
  beacon-chain/sync/decode_pubsub.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rate_limiter_test.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_chunked_response.go
  beacon-chain/sync/rpc_chunked_response_test.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_metadata_test.go
  beacon-chain/sync/rpc_ping.go
  beacon-chain/sync/rpc_ping_test.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/rpc_status_test.go
  shared/interfaces/BUILD.bazel
  shared/interfaces/altair_block_wrapper.go
  shared/interfaces/block_interface.go
  shared/interfaces/metadata_interface.go
  shared/interfaces/metadata_wrapper.go
  shared/interfaces/phase0_block_wrapper.go
Labels: Networking, Ready For Review

#8988 Do not use proto casing in `v1alpha1` API JSON fields
  shared/gateway/gateway.go
Labels: API, Ready For Review

#8990 Remove unused ClosestPowerOf2 method
  shared/mathutil/math_helper.go
  shared/mathutil/math_helper_test.go
Labels: OK to merge

#8991 Improve Mirror Bash Script for EthereumAPIs
  scripts/mirror-ethereumapis.sh
Labels: OK to merge, Ready For Review

#8984 Refactor API Middleware into more manageable code
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/rpc/apimiddleware/BUILD.bazel
  beacon-chain/rpc/apimiddleware/endpoints.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/server/BUILD.bazel
  beacon-chain/server/main.go
  shared/gateway/BUILD.bazel
  shared/gateway/api_middleware.go
  shared/gateway/api_middleware_processing.go
  shared/gateway/api_middleware_structs.go
  shared/gateway/gateway.go
  shared/gateway/gateway_test.go
  shared/gateway/middleware_structs.go
Labels: API, Ready For Review

#8992 Fix repo name in mirror script
  scripts/mirror-ethereumapis.sh
Labels: OK to merge

#8995 Run go imports
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/db/powchain.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/debug.pb.go
  proto/beacon/rpc/v1/debug.pb.gw.go
  proto/beacon/rpc/v1/health.pb.go
  proto/beacon/rpc/v1/health.pb.gw.go
  proto/beacon/rpc/v1/slasher.pb.go
  proto/beacon/rpc/v1/slasher.pb.gw.go
  proto/eth/ext/options.pb.go
  proto/eth/v1/attestation.pb.go
  proto/eth/v1/beacon_block.pb.go
  proto/eth/v1/beacon_chain_service.pb.go
  proto/eth/v1/beacon_chain_service.pb.gw.go
  proto/eth/v1/beacon_debug_service.pb.go
  proto/eth/v1/beacon_debug_service.pb.gw.go
  proto/eth/v1/beacon_state.pb.go
  proto/eth/v1/node.pb.go
  proto/eth/v1/node.pb.gw.go
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator_service.pb.go
  proto/eth/v1/validator_service.pb.gw.go
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_block_altair.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.gw.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/node.pb.gw.go
  proto/eth/v1alpha1/sync_committee.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.pb.gw.go
  proto/validator/accounts/v2/keymanager.pb.go
  proto/validator/accounts/v2/keymanager.pb.gw.go
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.pb.gw.go
Labels: Ready For Review

#8998 API Middleware unit tests
  beacon-chain/rpc/apimiddleware/BUILD.bazel
  beacon-chain/rpc/apimiddleware/endpoints.go
  beacon-chain/rpc/apimiddleware/endpoints_test.go
  shared/gateway/BUILD.bazel
  shared/gateway/api_middleware_processing.go
  shared/gateway/api_middleware_processing_test.go
Labels: API, Ready For Review

#9000 Update prysm.sh to support Mac M1 chip
  prysm.sh
Labels: OK to merge

#8999 Protobuf Changes for Eth2 APIs EventSource Support
  deps.bzl
  go.mod
  go.sum
  proto/eth/v1/BUILD.bazel
  proto/eth/v1/attestation.pb.go
  proto/eth/v1/beacon_block.pb.go
  proto/eth/v1/beacon_chain_service.pb.go
  proto/eth/v1/beacon_debug_service.pb.go
  proto/eth/v1/beacon_state.pb.go
  proto/eth/v1/events_service.pb.go
  proto/eth/v1/events_service.pb.gw.go
  proto/eth/v1/events_service.proto
  proto/eth/v1/node.pb.go
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator_service.pb.go
Labels: OK to merge, Ready For Review

#8976 Client-stats: Fail gracefully when metrics are missing
  shared/clientstats/BUILD.bazel
  shared/clientstats/scrapers.go
  shared/clientstats/scrapers_test.go
Labels: OK to merge

#8993 Altair Add back minimal spec tests
  .bazelignore
  proto/beacon/p2p/v1/types.proto
  proto/eth/v1alpha1/BUILD.bazel
  proto/eth/v1alpha1/beacon_block_altair.proto
  proto/ssz_proto_library.bzl
  spectest/minimal/altair/fork/BUILD.bazel
Labels: Ready For Review

#8970 Implement SSZ version of `/blocks/{block_id}`
  beacon-chain/rpc/apimiddleware/BUILD.bazel
  beacon-chain/rpc/apimiddleware/endpoints.go
  beacon-chain/rpc/apimiddleware/endpoints_test.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/beaconv1/blocks.go
  beacon-chain/rpc/beaconv1/blocks_test.go
  beacon-chain/rpc/nodev1/node_test.go
  deps.bzl
  go.sum
  proto/eth/v1/beacon_chain_service.pb.go
  proto/eth/v1/beacon_chain_service.pb.gw.go
  proto/eth/v1/beacon_chain_service.proto
Labels: API, Ready For Review

#9003 Altair: Copy sync aggregate
  shared/copyutil/cloners.go
Labels: Ready For Review

#9005 Altair: Align to alpha7
  WORKSPACE
  beacon-chain/core/altair/block.go
  beacon-chain/core/altair/block_test.go
  beacon-chain/core/altair/sync_committee.go
  beacon-chain/core/state/transition_no_verify_sig.go
  beacon-chain/operations/synccommittee/kv.go
  beacon-chain/operations/synccommittee/signature.go
  beacon-chain/operations/synccommittee/signature_test.go
  fuzz/generated.ssz.go
  proto/beacon/p2p/v1/generated.ssz.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v1alpha1/BUILD.bazel
  proto/eth/v1alpha1/generated.ssz.go
  proto/eth/v1alpha1/sync_committee.pb.go
  proto/eth/v1alpha1/sync_committee.proto
  shared/copyutil/cloners.go
  shared/params/mainnet_config.go
  spectest/shared/altair/operations/sync_committee.go
  spectest/shared/altair/ssz_static/ssz_static.go
Labels: Ready For Review

#9004 Altair: save state in DB
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/altair.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
Labels: Ready For Review

#9010 New Proto Messages Required for Event Streams
  proto/eth/ext/options.pb.go
  proto/eth/v1/events_service.pb.go
  proto/eth/v1/events_service.proto
  proto/eth/v1alpha1/attestation.pb.go
  proto/eth/v1alpha1/beacon_block.pb.go
  proto/eth/v1alpha1/beacon_block_altair.pb.go
  proto/eth/v1alpha1/beacon_chain.pb.go
  proto/eth/v1alpha1/node.pb.go
  proto/eth/v1alpha1/sync_committee.pb.go
  proto/eth/v1alpha1/validator.pb.go
Labels: OK to merge, Ready For Review

#9009 Update mirror-ethereumapis.sh to include committer name / email
  scripts/mirror-ethereumapis.sh
Labels: OK to merge, Ready For Review

#8894 Graffiti hex support
  validator/graffiti/BUILD.bazel
  validator/graffiti/log.go
  validator/graffiti/parse_graffiti.go
  validator/graffiti/parse_graffiti_test.go
  validator/node/node.go
Labels: OK to merge

#9017 Update jwt-go library to fix CVE-2020-26160
  deps.bzl
  go.mod
  go.sum
  proto/testing/gocast.go
  validator/rpc/BUILD.bazel
  validator/rpc/auth.go
  validator/rpc/auth_test.go
  validator/rpc/intercepter.go
  validator/rpc/intercepter_test.go
Labels: Priority: Medium, Ready For Review, Security

#9011 Capture ChainReorg, FinalizedCheckpoint, and NewHead Events in Beacon Node
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/feed/state/events.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  shared/slotutil/slottime.go
  shared/slotutil/slottime_test.go
Labels: Ready For Review

#8996 Change To LRU from FIFO Cache
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_fuzz_test.go
  beacon-chain/cache/committee_test.go
Labels: OK to merge, Ready For Review

#9018 Sync committee to use priority queue
  beacon-chain/operations/synccommittee/BUILD.bazel
  beacon-chain/operations/synccommittee/contribution.go
  beacon-chain/operations/synccommittee/contribution_test.go
  beacon-chain/operations/synccommittee/error.go
  beacon-chain/operations/synccommittee/kv.go
  beacon-chain/operations/synccommittee/message.go
  beacon-chain/operations/synccommittee/message_test.go
  beacon-chain/operations/synccommittee/signature.go
  beacon-chain/operations/synccommittee/signature_test.go
  deps.bzl
  go.mod
  go.sum
  shared/copyutil/cloners.go
  shared/queue/BUILD.bazel
  shared/queue/LICENSE
  shared/queue/priority_queue.go
Labels: Ready For Review

#9013 Altair: sign block can handle versioning
  proto/validator/accounts/v2/keymanager.pb.go
  proto/validator/accounts/v2/keymanager.proto
  shared/interfaces/altair_block_wrapper.go
  shared/interfaces/block_interface.go
  shared/interfaces/phase0_block_wrapper.go
  validator/client/BUILD.bazel
  validator/client/propose.go
  validator/client/propose_test.go
Labels: Ready For Review

#9020 Proto mirror script fix
  scripts/mirror-ethereumapis.sh
Labels: CI, OK to merge, Ready For Review

#9024 RPC: Surface underlying error when failing to return a state.
  beacon-chain/rpc/beacon/validators.go
Labels: OK to merge, Ready For Review

#9022 Add Better Zero Key Checks
  shared/bls/blst/secret_key.go
  shared/bls/blst/secret_key_test.go
  shared/bls/common/interface.go
Labels: Ready For Review

#9026 Refactor helpers for Altair
  beacon-chain/core/blocks/deposit.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/genesis.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/state.go
Labels: OK to merge, Ready For Review

#9035 Create `ValidatorIndexOutOfRangeError`
  beacon-chain/state/stateV0/getters_validator.go
Labels: API, OK to merge, Ready For Review

#9001 Add Events Streaming Endpoint for Eth2 Standard API
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/eventsv1/BUILD.bazel
  beacon-chain/rpc/eventsv1/events.go
  beacon-chain/rpc/eventsv1/events_test.go
  beacon-chain/rpc/eventsv1/server.go
  beacon-chain/rpc/service.go
  proto/migration/BUILD.bazel
  proto/migration/migration.go
  proto/migration/migration_test.go
  scripts/update-mockgen.sh
  shared/gateway/BUILD.bazel
  shared/gateway/gateway.go
  shared/mock/BUILD.bazel
  shared/mock/event_service_mock.go
Labels: OK to merge, Priority: High, Ready For Review

#9037 Altair: add sync committee to duty rpc
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/operations/synccommittee/contribution.go
  beacon-chain/operations/synccommittee/kv.go
  beacon-chain/operations/synccommittee/message.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.proto
  validator/client/iface/validator.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#9039 fixes 9029 + a few related client-stats fixes/improvements
  beacon-chain/powchain/prometheus.go
  shared/clientstats/BUILD.bazel
  shared/clientstats/README.md
  shared/clientstats/scrapers.go
  shared/clientstats/scrapers_test.go
Labels: OK to merge

#9044 Revert "Invert `attest-timely` flag"
  shared/featureconfig/config.go
  shared/featureconfig/deprecated_flags.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#9045 Go imports
  proto/eth/v1/beacon_chain_service.pb.go
  proto/eth/v1/beacon_chain_service.pb.gw.go
  proto/eth/v1/beacon_debug_service.pb.go
  proto/eth/v1/beacon_debug_service.pb.gw.go
Labels: OK to merge, Ready For Review

#9046 Rename field ops service to att service
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/node.go
  fuzz/block_fuzz.go
Labels: OK to merge, Ready For Review

#8975 Process future Blocks and Attestations
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/rpc/validator/aggregator.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  shared/slotutil/slottime.go
  shared/slotutil/slottime_test.go
Labels: Enhancement, OK to merge, Ready For Review

#9051 Add fallback check to sync committee helper
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/error.go
  beacon-chain/cache/sync_committee.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/operations/synccommittee/BUILD.bazel
  beacon-chain/rpc/validator/assignments.go
Labels: Ready For Review

#9016 Add Sync Committee Pipelines
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/sync_committee_test.go
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/attestation_test.go
  beacon-chain/core/altair/block_test.go
  beacon-chain/core/altair/epoch_spec_test.go
  beacon-chain/core/altair/fork_transition_test.go
  beacon-chain/core/altair/reward_test.go
  beacon-chain/core/altair/sync_committee.go
  beacon-chain/core/altair/sync_committee_test.go
  beacon-chain/core/feed/operation/events.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/altair_transition_no_verify_sig_test.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/state_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/operations/synccommittee/BUILD.bazel
  beacon-chain/operations/synccommittee/pool.go
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/p2p/topics.go
  beacon-chain/state/state-altair/BUILD.bazel
  beacon-chain/state/state-altair/state_trie_block_box_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
  beacon-chain/sync/subscriber_sync_committee.go
  beacon-chain/sync/subscriber_sync_contribution_proof.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_sync_committee.go
  beacon-chain/sync/validate_sync_committee_test.go
  beacon-chain/sync/validate_sync_contrbution_proof.go
  beacon-chain/sync/validate_sync_contrbution_proof_test.go
  fuzz/block_fuzz.go
  fuzz/rpc_status_fuzz.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v1alpha1/generated.ssz.go
  shared/testutil/BUILD.bazel
  shared/testutil/altair.go
  shared/testutil/altair/BUILD.bazel
  shared/testutil/altair/altair.go
  shared/testutil/attestation.go
  shared/testutil/block.go
  shared/testutil/helpers.go
  shared/testutil/sync_committee.go
  validator/client/BUILD.bazel
  validator/client/propose_test.go
Labels: Ready For Review

#9048 Altair: Validator can submit sync committee msg
  beacon-chain/node/node.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/server.go
  beacon-chain/rpc/validator/sync_committee.go
  beacon-chain/rpc/validator/sync_committee_test.go
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.pb.gw.go
  proto/eth/v1alpha1/validator.proto
  shared/mock/beacon_validator_client_mock.go
  validator/client/BUILD.bazel
  validator/client/iface/validator.go
  validator/client/runner.go
  validator/client/sync_committee.go
  validator/client/sync_committee_test.go
  validator/client/testutil/mock_validator.go
Labels: Ready For Review

#9053 Better comments for aggregator functions
  validator/client/aggregate.go
  validator/client/validator.go
Labels: OK to merge, Ready For Review

#9055 Do not register API Middleware with validator gateway
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  shared/gateway/api_middleware.go
  shared/gateway/gateway.go
  shared/gateway/gateway_test.go
Labels: API, OK to merge, Ready For Review

#8888 Adding ability to override directory permissions for db backup
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/backup.go
  beacon-chain/db/kv/backup_test.go
  shared/backuputil/http_backup_handler.go
  shared/fileutil/fileutil.go
  shared/fileutil/fileutil_test.go
  slasher/db/kv/backup.go
  slasher/db/kv/backup_test.go
  validator/db/kv/backup.go
  validator/db/kv/backup_test.go
Labels: OK to merge, Ready For Review

#9057 Fix sync committee duty off by 1
  beacon-chain/rpc/validator/sync_committee.go
  beacon-chain/rpc/validator/sync_committee_test.go
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.pb.gw.go
  proto/eth/v1alpha1/validator.proto
  shared/mock/beacon_validator_client_mock.go
  validator/client/BUILD.bazel
  validator/client/sync_committee.go
  validator/client/sync_committee_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review

#9059 Testutil: Reset deposit cache internally
  beacon-chain/core/blocks/block_regression_test.go
  beacon-chain/core/blocks/deposit_test.go
  beacon-chain/core/blocks/header_test.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/exit_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  endtoend/BUILD.bazel
  endtoend/minimal_e2e_test.go
  endtoend/minimal_slashing_e2e_test.go
  shared/testutil/deposits.go
  shared/testutil/deposits_test.go
Labels: OK to merge, Ready For Review

#9056 Add Block Proposals In Altair
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  proto/eth/ext/options.pb.go
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.pb.gw.go
  proto/eth/v1alpha1/validator.proto
  shared/blockutil/BUILD.bazel
  shared/blockutil/block_utils.go
  shared/mock/beacon_chain_service_mock.go
  shared/mock/beacon_service_mock.go
  shared/mock/beacon_validator_client_mock.go
  shared/mock/beacon_validator_server_mock.go
  shared/mock/keymanager_mock.go
  shared/mock/node_service_mock.go
  validator/client/propose.go
  validator/client/propose_protect.go
  validator/client/propose_protect_test.go
  validator/client/propose_test.go
  validator/client/slashing_protection_interchange_test.go
Labels: Ready For Review

#9050 Make the `shared/gateway` package unaware of consuming services
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/server/BUILD.bazel
  beacon-chain/server/main.go
  shared/gateway/BUILD.bazel
  shared/gateway/gateway.go
  shared/gateway/gateway_test.go
  validator/node/BUILD.bazel
  validator/node/node.go
Labels: OK to merge, Ready For Review

#9058 Altair: check validator is an aggregator for sync committee
  beacon-chain/core/altair/sync_committee.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/sync_committee.go
  beacon-chain/rpc/validator/sync_committee_test.go
  proto/beacon/p2p/v1/generated.ssz.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/eth/v1/generated.ssz.go
  proto/eth/v1alpha1/generated.ssz.go
  proto/eth/v1alpha1/validator.pb.go
  proto/eth/v1alpha1/validator.pb.gw.go
  proto/eth/v1alpha1/validator.proto
  shared/mock/beacon_validator_client_mock.go
  validator/client/BUILD.bazel
  validator/client/iface/validator.go
  validator/client/runner.go
  validator/client/sync_committee.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review

#9061 Fix Small Type Assertion Bug in Slasher
  slasher/db/kv/spanner_new.go
Labels: OK to merge, Ready For Review

#9060 Prevent Exporting False Positive Slashing Event Due to Old Prysm DB Schema Bug
  validator/slashing-protection/local/standard-protection-format/export.go
  validator/slashing-protection/local/standard-protection-format/export_test.go
Labels: OK to merge, Priority: High, Ready For Review

#9068 Add Lock To Validator Map Handler
  beacon-chain/state/stateutil/validator_map_handler.go
Labels: Ready For Review

#9069 Disable No Freelist Sync In Backups
  beacon-chain/db/kv/backup.go
Labels: Ready For Review

#9073 Double java heap size for buildkite
  .buildkite-bazelrc
Labels: CI, OK to merge, Ready For Review

#9075 Add goimports check
  .github/workflows/go.yml
Labels: OK to merge, Ready For Review

#9076 Remove copy when push to priority queue
  beacon-chain/operations/synccommittee/message.go
  go.mod
  go.sum
  shared/queue/BUILD.bazel
  shared/queue/priority_queue.go
Labels: Ready For Review

#9077 Add sync committee head state cache
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/sync_committee.go
  beacon-chain/rpc/validator/sync_committee_test.go
Labels: Ready For Review

#9079 Add New Parameters for Sync Committees And Sync Contribution
  beacon-chain/p2p/gossip_scoring_params.go
Labels: Networking, Ready For Review

#9042 Add a test for e2e validator to run against prior release
  BUILD.bazel
  endtoend/BUILD.bazel
  endtoend/components/validator.go
  endtoend/minimal_e2e_test.go
  endtoend/types/types.go
Labels: OK to merge, Ready For Review

#9074 Altair: Use Validator Index for Sync Committee Caching
  beacon-chain/cache/sync_committee.go
  beacon-chain/cache/sync_committee_disabled.go
  beacon-chain/cache/sync_committee_test.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/sync_committee.go
Labels: Ready For Review

#9083 Implement Beacon Validator RPC V2 In Proper Package
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v2/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v2/validator/proposer.go
  beacon-chain/rpc/prysm/v2/validator/proposer_test.go
  beacon-chain/rpc/prysm/v2/validator/server.go
  beacon-chain/rpc/prysm/v2/validator/sync_committee.go
  beacon-chain/rpc/prysm/v2/validator/sync_committee_test.go
  beacon-chain/rpc/service.go
Labels: Ready For Review

#9081 Use correct fork version object for domain data
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
Labels: Ready For Review

#9084 Use same version of spectests and spec in WORKSPACE
  WORKSPACE
  shared/params/loader_test.go
Labels: Ready For Review

#9085 Revert "Improve performance during CheckAttesterDoubleVotes"
  beacon-chain/db/slasherkv/BUILD.bazel
  beacon-chain/db/slasherkv/kv.go
  beacon-chain/db/slasherkv/pruning.go
  beacon-chain/db/slasherkv/schema.go
  beacon-chain/db/slasherkv/slasher.go
  beacon-chain/db/slasherkv/slasher_test.go
Labels: OK to merge, Ready For Review

#9086 Parallelized Double Vote Detection in Slasher With Disk-Space Efficient Schema
  beacon-chain/db/slasherkv/BUILD.bazel
  beacon-chain/db/slasherkv/pruning.go
  beacon-chain/db/slasherkv/slasher.go
  beacon-chain/db/slasherkv/slasher_test.go
Labels: OK to merge, Ready For Review

#9090 Add Updated Fork Utils
  beacon-chain/p2p/fork_test.go
  beacon-chain/rpc/eth/v1/beacon/BUILD.bazel
  beacon-chain/rpc/eth/v1/beacon/config.go
  beacon-chain/rpc/eth/v1/beacon/config_test.go
  shared/p2putils/BUILD.bazel
  shared/p2putils/fork.go
  shared/p2putils/fork_test.go
  shared/params/config.go
  shared/params/mainnet_config.go
  shared/params/minimal_config.go
  shared/params/network_config.go
Labels: Ready For Review

#9080 Run `text/event-stream` values returned from grpc-gateway through API Middleware
  beacon-chain/node/node.go
  beacon-chain/rpc/apimiddleware/BUILD.bazel
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eventsv1/BUILD.bazel
  beacon-chain/rpc/eventsv1/events.go
  beacon-chain/rpc/eventsv1/events_test.go
  beacon-chain/server/main.go
  deps.bzl
  go.mod
  go.sum
Labels: API, OK to merge, Ready For Review

#9089 Add Sync Subnet Id Cache
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/sync_subnet_ids.go
  beacon-chain/cache/sync_subnet_ids_test.go
Labels: Ready For Review

#9093 Remove verbatim strings with flag names on startup
  cmd/beacon-chain/flags/BUILD.bazel
  cmd/validator/flags/BUILD.bazel
  endtoend/components/BUILD.bazel
  endtoend/components/beacon_node.go
  endtoend/components/validator.go
Labels: Cleanup, OK to merge, Ready For Review

#9096 Block Stream V2 Protos
  proto/eth/ext/options.pb.go
  proto/prysm/v2/validator.pb.go
  proto/prysm/v2/validator.pb.gw.go
  proto/prysm/v2/validator.proto
Labels: OK to merge, Ready For Review

#9092 Move common gateway registration code to new package
  beacon-chain/gateway/BUILD.bazel
  beacon-chain/gateway/helpers.go
  beacon-chain/gateway/helpers_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/server/BUILD.bazel
  beacon-chain/server/main.go
Labels: OK to merge, Ready For Review

#9103 Update spec test to alpha8
  WORKSPACE
  beacon-chain/rpc/apimiddleware/BUILD.bazel
Labels: Ready For Review

#9099 Fix a few bugs in the API
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/nodev1/node.go
  beacon-chain/rpc/nodev1/node_test.go
Labels: API, Ready For Review

#9101 Move API param handling to separate file
  shared/gateway/BUILD.bazel
  shared/gateway/api_middleware_processing.go
  shared/gateway/api_middleware_processing_test.go
  shared/gateway/param_handling.go
  shared/gateway/param_handling_test.go
Labels: API, OK to merge, Ready For Review

#9105 No length check in AggregatePublicKeys
  shared/bls/blst/public_key.go
  shared/bls/blst/public_key_test.go
Labels: OK to merge

#9107 Remove old protos
  proto/eth/v1alpha1/beacon_block_altair.pb.go
  proto/eth/v1alpha1/beacon_block_altair.pb.gw.go
  proto/eth/v1alpha1/beacon_block_altair.proto
  proto/eth/v1alpha1/generated.ssz.go
  proto/eth/v1alpha1/sync_committee.pb.go
  proto/eth/v1alpha1/sync_committee.pb.gw.go
  proto/eth/v1alpha1/sync_committee.proto
Labels: OK to merge, Ready For Review

#9094 Add New V2 Streaming Blocks Method
  beacon-chain/rpc/apimiddleware/BUILD.bazel
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
  beacon-chain/rpc/prysm/v2/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v2/validator/blocks.go
  scripts/update-mockgen.sh
  shared/event/feed.go
  shared/event/feed_test.go
  shared/mock/BUILD.bazel
  shared/mock/beacon_altair_validator_client_mock.go
  shared/mock/beacon_altair_validator_server_mock.go
  shared/mock/beacon_validator_client_mock.go
  shared/mock/beacon_validator_client_v2_mock.go
  shared/p2putils/fork_test.go
  validator/client/attest.go
  validator/client/attest_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review

#9111 Small API Middleware improvements
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  shared/gateway/api_middleware.go
  shared/gateway/api_middleware_processing.go
  shared/gateway/api_middleware_structs.go
  shared/gateway/param_handling.go
Labels: API, OK to merge, Ready For Review

#9112 Make Eth APIs flag name implementation agnostic
  beacon-chain/node/node.go
  beacon-chain/server/main.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  endtoend/components/beacon_node.go
Labels: API, OK to merge, Ready For Review

#9102 Handle comma-separated query parameters in API requests
  shared/gateway/param_handling.go
  shared/gateway/param_handling_test.go
Labels: API, OK to merge, Ready For Review

#9063 Tool for Exploring BoltDB in Human-Readable Formats
  go.mod
  tools/exploredb/BUILD.bazel
  tools/exploredb/main.go
Labels: Enhancement, OK to merge, Ready For Review

#9106 Add proposer sync contribution type
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/proposer_attestations.go
  beacon-chain/rpc/validator/proposer_attestations_test.go
  beacon-chain/rpc/validator/proposer_sync_aggregate.go
  beacon-chain/rpc/validator/proposer_sync_aggregate_test.go
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review

#9113 Reorder WORKSPACE go dependency registration
  WORKSPACE
  deps.bzl
Labels: OK to merge, Ready For Review

#9115 Submitting sync committee message logs
  validator/client/sync_committee.go
Labels: Ready For Review

#9117 Retrieve validators through v1 API in e2e
  beacon-chain/server/main.go
  endtoend/evaluators/BUILD.bazel
  endtoend/evaluators/api.go
  endtoend/minimal_e2e_test.go
Labels: E2E Tests, Ready For Review

#9114 Naive aggregation for `SyncCommitteeContribution`
  deps.bzl
  go.mod
  go.sum
  shared/aggregation/sync_contribution/BUILD.bazel
  shared/aggregation/sync_contribution/contribution.go
  shared/aggregation/sync_contribution/naive.go
  shared/aggregation/sync_contribution/naive_test.go
  shared/aggregation/testing/BUILD.bazel
  shared/aggregation/testing/bitlistutils.go
  shared/copyutil/BUILD.bazel
  shared/copyutil/cloners.go
Labels: OK to merge, Ready For Review

#9121 Add search for most profitable sync contribution
  beacon-chain/rpc/validator/proposer_sync_aggregate.go
  beacon-chain/rpc/validator/proposer_sync_aggregate_test.go
Labels: OK to merge, Ready For Review

#9124 Altair: proposer pack sync aggregate
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v2/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v2/validator/proposer.go
  beacon-chain/rpc/prysm/v2/validator/proposer_sync_aggregate.go
  beacon-chain/rpc/prysm/v2/validator/proposer_sync_aggregate_test.go
  beacon-chain/rpc/prysm/v2/validator/proposer_test.go
Labels: Ready For Review

#9129 Return an error on unrecognized arguments when running default commands in Prysm
  cmd/beacon-chain/main.go
  cmd/client-stats/main.go
  cmd/slasher/main.go
  cmd/validator/main.go
  shared/cmd/flags.go
  shared/cmd/flags_test.go
Labels: OK to merge, Ready For Review

#9131 Green Altair e2e tests
  beacon-chain/cache/sync_committee.go
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/operations/synccommittee/BUILD.bazel
  beacon-chain/rpc/prysm/v2/validator/BUILD.bazel
  shared/p2putils/BUILD.bazel
  shared/p2putils/fork.go
  shared/params/minimal_config.go
  spectest/mainnet/altair/epoch_processing/BUILD.bazel
  spectest/mainnet/altair/finality/BUILD.bazel
  spectest/mainnet/altair/fork_helper/BUILD.bazel
  spectest/mainnet/altair/fork_transition/BUILD.bazel
  spectest/mainnet/altair/operations/BUILD.bazel
  spectest/mainnet/altair/rewards/BUILD.bazel
  spectest/mainnet/altair/sanity/BUILD.bazel
  spectest/mainnet/altair/ssz_static/BUILD.bazel
  spectest/minimal/altair/epoch_processing/BUILD.bazel
  spectest/minimal/altair/finality/BUILD.bazel
  spectest/minimal/altair/fork/BUILD.bazel
  spectest/minimal/altair/operations/BUILD.bazel
  spectest/minimal/altair/rewards/BUILD.bazel
  spectest/minimal/altair/sanity/BUILD.bazel
  spectest/minimal/altair/ssz_static/BUILD.bazel
Labels: Ready For Review
