Repository OffchainLabs/prysm, pull requests merged in 2021-01, with the labels that each got.

#8193 Compare strings using strings.EqualFold()
  beacon-chain/db/restore.go
  shared/tos/tos.go
  slasher/db/restore.go
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_enable_disable.go
  validator/accounts/accounts_exit.go
  validator/accounts/wallet_create.go
  validator/accounts/wallet_recover.go
  validator/db/restore.go
Labels: Cleanup, OK to merge, Ready For Review

#8171 Validator nil duty should not panic
  validator/client/log.go
  validator/client/log_test.go
Labels: OK to merge, Ready For Review

#8183 Update int -> string conversion to make go test happy
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/precompute/slashing_test.go
Labels: OK to merge, Ready For Review

#8192 Remove redundant lambda around cleanup code
  beacon-chain/core/blocks/deposit_test.go
  beacon-chain/powchain/service_test.go
Labels: OK to merge, Ready For Review

#8167 Add new GetVersion API to Health Service
  go.mod
  go.sum
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/rpc/BUILD.bazel
  validator/rpc/health.go
Labels: OK to merge, Ready For Review

#8141 Bring back disable slashing broadcast flag
  beacon-chain/rpc/beacon/BUILD.bazel
  beacon-chain/rpc/beacon/slashings.go
  beacon-chain/rpc/beacon/slashings_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: Discussion, OK to merge

#8191 Fix import shadowing of state package
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/epoch/spectest/justification_and_finalization_test.go
  beacon-chain/core/epoch/spectest/rewards_and_penalties_test.go
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/state/stategen/setter.go
Labels: Cleanup, OK to merge, Ready For Review

#8160 Add mutex to params/config
  DEPENDENCIES.md
  shared/params/BUILD.bazel
  shared/params/checktags_test.go
  shared/params/config.go
  shared/params/config_test.go
  shared/params/config_utils_develop.go
  shared/params/config_utils_prod.go
Labels: OK to merge, Ready For Review

#8166 Add slot in epoch field for `Attestation schedule..." log
  validator/client/validator.go
Labels: OK to merge, Ready For Review

#8159 Add names to certain return values in accounts
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_exit.go
  validator/accounts/wallet_recover.go
Labels: OK to merge, Ready For Review

#8164 Fix file permission checks for Windows
  shared/params/io_config.go
Labels: OK to merge, Ready For Review

#8097 Fix for prysm.bat issue 'Validator' is not recognized as an internal or external command
  prysm.bat
Labels: OK to merge

#8149 Configurable Interval for Debouncing Keystore Reloading in Validator Client
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/keymanager/imported/BUILD.bazel
  validator/keymanager/imported/refresh.go
Labels: OK to merge, Ready For Review

#8190 Fix data races in tests accessing beacon config concurrently
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/checktags_test.go
Labels: OK to merge, Ready For Review

#8202 Add space at the start of comments
  beacon-chain/core/blocks/deposit_test.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/node/node.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service_test.go
  beacon-chain/powchain/testing/faulty_mock.go
  beacon-chain/powchain/testing/mock.go
  shared/bytesutil/bytes_test.go
  shared/cmd/config.go
  shared/journald/journald.go
  slasher/db/kv/indexed_attestations.go
  slasher/db/kv/spanner_new.go
  slasher/db/kv/spanner_new_test.go
  slasher/detection/attestations/spanner.go
  validator/accounts/accounts_backup_test.go
  validator/client/attest_protect.go
  validator/client/metrics_test.go
  validator/client/propose_test.go
  validator/keymanager/derived/mnemonic.go
Labels: OK to merge, Ready For Review

#8199 Remove redundant parentheses around nil values
  beacon-chain/cache/depositcache/deposits_cache_test.go
  beacon-chain/db/kv/deposit_contract_test.go
  slasher/db/kv/attester_slashings_test.go
  slasher/db/kv/block_header_test.go
  slasher/db/kv/proposer_slashings_test.go
  slasher/db/kv/validator_id_pubkey_test.go
  validator/db/kv/historical_attestations_test.go
Labels: OK to merge, Ready For Review

#8200 Declare err in loop to limit its scope
  beacon-chain/p2p/pubsub.go
  beacon-chain/p2p/utils.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  slasher/detection/detect.go
Labels: OK to merge, Ready For Review

#8206 Stream verified block
  beacon-chain/blockchain/receive_block.go
  beacon-chain/core/feed/state/BUILD.bazel
  beacon-chain/core/feed/state/events.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/slashings.go
  beacon-chain/rpc/beacon/slashings_test.go
  deps.bzl
  go.mod
  go.sum
  shared/mock/beacon_service_mock.go
  slasher/beaconclient/receivers.go
  slasher/beaconclient/receivers_test.go
Labels: Ready For Review

#8207 Implement GetVersion in the node API
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/nodev1/BUILD.bazel
  beacon-chain/rpc/nodev1/node.go
  beacon-chain/rpc/nodev1/node_test.go
  beacon-chain/rpc/service.go
  shared/version/version.go
Labels: OK to merge, Ready For Review

#8211 Optimal Local Slashing Protection DB Schema
  validator/db/kv/BUILD.bazel
  validator/db/kv/attester_protection.go
  validator/db/kv/attester_protection_test.go
  validator/db/kv/db.go
  validator/db/kv/schema.go
Labels: Enhancement, OK to merge, Priority: Critical, Ready For Review

#8214 Check if initial sync service has been initialized
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
Labels: OK to merge, Ready For Review

#8215 Revert changes to sync service status check
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
Labels: OK to merge, Ready For Review

#8216 Move attestation protection call after signing
  validator/client/attest.go
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/client/attest_test.go
Labels: Ready For Review

#8213 Attestation Aggregation: optimize attestation list validation
  shared/aggregation/attestations/maxcover.go
  shared/aggregation/attestations/maxcover_test.go
  shared/aggregation/maxcover.go
  shared/aggregation/maxcover_test.go
Labels: OK to merge, Ready For Review

#8217 Implement GetHealth in the node API
  beacon-chain/rpc/nodev1/BUILD.bazel
  beacon-chain/rpc/nodev1/node.go
  beacon-chain/rpc/nodev1/node_test.go
  beacon-chain/sync/initial-sync/testing/mock.go
  beacon-chain/sync/service.go
  fuzz/block_fuzz.go
Labels: OK to merge, Ready For Review

#8212 DB Migration for Optimal Local Slashing Protection
  shared/progressutil/BUILD.bazel
  shared/progressutil/progress.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/migration.go
  validator/db/kv/migration_optimal_attester_protection.go
  validator/db/kv/migration_optimal_attester_protection_test.go
Labels: OK to merge, Ready For Review

#8197 Fix Attest early if valid block is received before 4 seconds
  validator/client/BUILD.bazel
  validator/client/attest.go
  validator/client/attest_test.go
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#8182 Block Fetching with Graceful Retry
  beacon-chain/powchain/log_processing.go
Labels: OK to merge, Ready For Review

#8187 Show number of user pubkeys for attesting and proposing in "Next duty" log output
  validator/client/log.go
  validator/client/log_test.go
Labels: OK to merge

#8203 Multiple discovery addresses
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/p2p.go
Labels: OK to merge, Ready For Review

#8224 Max-cover: remove redundant dedup routine
  shared/aggregation/attestations/maxcover.go
  shared/aggregation/maxcover.go
  shared/aggregation/maxcover_test.go
Labels: OK to merge, Ready For Review

#8220 Update variable names that are same as imports
  beacon-chain/blockchain/service_test.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/info.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/p2p/watch_peers.go
  beacon-chain/powchain/service.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_stream.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/subscriber_test.go
Labels: Ready For Review

#8225 Update FastSSZ To Latest Commit
  deps.bzl
  go.mod
  go.sum
  proto/beacon/p2p/v1/generated.ssz.go
Labels: OK to merge, Ready For Review

#8227 Update Bitfield Dependency
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8222 Fix to TLS v1.3
  validator/keymanager/remote/keymanager.go
Labels: OK to merge, Ready For Review, Security

#8228 Hydrate attestation for tests
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/block_regression_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/block_test.go
  beacon-chain/operations/attestations/kv/forkchoice_test.go
  beacon-chain/operations/attestations/kv/seen_bits_test.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/prune_expired_test.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/validator/aggregator_test.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/proposer_utils_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  shared/testutil/BUILD.bazel
  shared/testutil/attestation.go
  shared/testutil/attestation_test.go
  shared/testutil/block.go
  validator/client/aggregate_test.go
Labels: OK to merge, Ready For Review

#8221 Prune Validator Attester Records Older than Weak Subjectivity Periods
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/db/kv/prune_attester_protection.go
  validator/db/kv/prune_attester_protection_test.go
Labels: Ready For Review

#8219 Integrate New Slashing Protection DB Methods at Runtime
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/attester_slashing.go
  shared/slashutil/BUILD.bazel
  shared/slashutil/surround_votes.go
  shared/slashutil/surround_votes_test.go
  slasher/detection/BUILD.bazel
  slasher/detection/detect.go
  slasher/detection/detect_test.go
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/db/iface/BUILD.bazel
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/attestation_history_v2_test.go
  validator/db/kv/attester_protection.go
  validator/db/kv/attester_protection_test.go
  validator/db/kv/db.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/format.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
Labels: OK to merge, Ready For Review

#8229 Fuzzing: conditional BLS enabled via environment variable
  fuzz/block_fuzz.go
  fuzz/common.go
Labels: OK to merge

#8226 Add Peer Logger
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/service.go
Labels: OK to merge, Ready For Review

#8231 Optimize Migration for new Attester Protection DB
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/db/kv/migration.go
  validator/db/kv/migration_optimal_attester_protection.go
  validator/db/kv/migration_optimal_attester_protection_test.go
Labels: OK to merge, Priority: High, Ready For Review

#8235 Add timely attest bug fix flag for #8185
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
  validator/client/attest.go
  validator/client/attest_test.go
Labels: Ready For Review

#8237 Revert New Attester Protection DB Logic
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/attester_slashing.go
  shared/progressutil/BUILD.bazel
  shared/progressutil/progress.go
  shared/slashutil/BUILD.bazel
  shared/slashutil/surround_votes.go
  shared/slashutil/surround_votes_test.go
  slasher/detection/BUILD.bazel
  slasher/detection/detect.go
  slasher/detection/detect_test.go
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/db/iface/BUILD.bazel
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/attestation_history_v2_test.go
  validator/db/kv/attester_protection.go
  validator/db/kv/attester_protection_test.go
  validator/db/kv/db.go
  validator/db/kv/migration_optimal_attester_protection.go
  validator/db/kv/migration_optimal_attester_protection_test.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/format.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
Labels: OK to merge, Ready For Review

#8234 Hydrate header test helper
  beacon-chain/core/blocks/header_test.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/db/kv/slashings_test.go
  beacon-chain/rpc/validator/attester_test.go
  shared/testutil/block.go
  shared/testutil/state.go
  slasher/db/kv/BUILD.bazel
  slasher/db/kv/proposer_slashings_test.go
  slasher/rpc/server_test.go
  validator/client/attest.go
Labels: OK to merge, Ready For Review, Testing

#8246 Hydrate signed block helper
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks_test.go
  shared/testutil/block.go
  shared/testutil/block_test.go
Labels: OK to merge, Ready For Review

#8247 Remove timeout debug log
  validator/client/attest.go
Labels: OK to merge, Ready For Review

#8243 Batch Attestation Records and Flush All at Once in Validator DB
  validator/client/attest_protect.go
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/attester_protection.go
  validator/db/kv/attester_protection_test.go
  validator/db/kv/db.go
  validator/db/kv/db_test.go
  validator/db/kv/historical_attestations.go
  validator/db/kv/log.go
  validator/db/kv/migration_optimal_attester_protection_test.go
  validator/slashing-protection/local/standard-protection-format/import.go
Labels: Priority: High, Ready For Review

#8242 Add Back New Attester Protection DB Logic
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/attester_slashing.go
  shared/progressutil/BUILD.bazel
  shared/progressutil/progress.go
  shared/slashutil/BUILD.bazel
  shared/slashutil/surround_votes.go
  shared/slashutil/surround_votes_test.go
  slasher/detection/BUILD.bazel
  slasher/detection/detect.go
  slasher/detection/detect_test.go
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/db/iface/BUILD.bazel
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/attestation_history_v2.go
  validator/db/kv/attestation_history_v2_test.go
  validator/db/kv/attester_protection.go
  validator/db/kv/attester_protection_test.go
  validator/db/kv/db.go
  validator/db/kv/db_test.go
  validator/db/kv/migration_optimal_attester_protection.go
  validator/db/kv/migration_optimal_attester_protection_test.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/format.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
Labels: OK to merge, Ready For Review

#8244 Add DepositMessage in preparation to remove go-ssz
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/deposit.go
  proto/beacon/p2p/v1/BUILD.bazel
  proto/beacon/p2p/v1/generated.ssz.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/p2p/v1/types.proto
  proto/testing/ssz_static_test.go
  shared/depositutil/BUILD.bazel
  shared/depositutil/deposit.go
  shared/depositutil/deposit_test.go
  shared/interop/BUILD.bazel
  shared/interop/generate_genesis_state.go
  shared/testutil/BUILD.bazel
  shared/testutil/deposits.go
Labels: Enhancement, OK to merge

#8248 Remove Snappy from Validator Slashing Protection DB
  validator/db/kv/BUILD.bazel
  validator/db/kv/migration_optimal_attester_protection.go
  validator/db/kv/migration_optimal_attester_protection_test.go
Labels: OK to merge, Ready For Review

#8249 Replace HTTP code with gRPC code in GetHealth API endpoint
  beacon-chain/rpc/nodev1/BUILD.bazel
  beacon-chain/rpc/nodev1/node.go
Labels: API, OK to merge, Ready For Review

#8251 Allow to create an empty imported wallet
  validator/accounts/accounts.go
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_enable_disable.go
  validator/accounts/accounts_exit.go
  validator/accounts/accounts_exit_test.go
  validator/accounts/accounts_list.go
  validator/accounts/wallet_create.go
  validator/accounts/wallet_create_test.go
  validator/keymanager/imported/enable_disable.go
  validator/keymanager/imported/enable_disable_test.go
  validator/keymanager/imported/import.go
  validator/keymanager/imported/import_test.go
  validator/keymanager/imported/keymanager.go
  validator/keymanager/imported/refresh.go
  validator/keymanager/imported/refresh_test.go
  validator/rpc/wallet.go
Labels: Accounts, OK to merge, Ready For Review

#8241 Implement GetSyncStatus in the node API
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/nodev1/BUILD.bazel
  beacon-chain/rpc/nodev1/node.go
  beacon-chain/rpc/nodev1/node_test.go
  beacon-chain/rpc/nodev1/server.go
  beacon-chain/rpc/service.go
Labels: API, OK to merge, Ready For Review

#8184 Added db.BlocksBySlot and db.BlockRootsBySlot
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/beaconv1/blocks.go
  tools/blocktree/main.go
  tools/extractor/BUILD.bazel
  tools/extractor/main.go
Labels: OK to merge, Ready For Review

#8250 Removed some simple go-ssz usage
  beacon-chain/core/epoch/precompute/spectest/rewards_penalties_test.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/getter_test.go
  fuzz/block_fuzz.go
Labels: OK to merge, Ready For Review

#8255 Coverage results upload fix for CI
  .gitignore
  scripts/ci-coverage.sh
  tools/gocovmerge/BUILD.bazel
  tools/gocovmerge/main.go
Labels: CI, OK to merge, Ready For Review

#8256 Update prometheus/client_golang
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8252 Disallow duties request where req.Epoch > current.Epoch+1
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/aggregator.go
  beacon-chain/rpc/validator/aggregator_test.go
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/assignments_test.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/attester_test.go
  beacon-chain/rpc/validator/exit_test.go
  beacon-chain/rpc/validator/server.go
Labels: OK to merge, Ready For Review, Security

#8258 Copied over ssz.DeepEqual as sszutil.DeepEqual from go-ssz
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/skip_slot_cache_test.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/types_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc_metadata_test.go
  shared/aggregation/attestations/BUILD.bazel
  shared/aggregation/attestations/attestations_test.go
  shared/sszutil/BUILD.bazel
  shared/sszutil/deep_equal.go
  shared/sszutil/deep_equal_test.go
  tools/pcli/BUILD.bazel
  tools/pcli/main.go
Labels: OK to merge

#8261 Add hydrate indexed att test helper
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/db/kv/slashings_test.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/operations/attestations/prune_expired_test.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/rpc/validator/proposer_utils_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_attester_slashing_test.go
  shared/testutil/attestation.go
  shared/testutil/attestation_test.go
  slasher/db/kv/attester_slashings_test.go
  validator/client/aggregate_test.go
Labels: OK to merge, Ready For Review

#8262 Allow Multiple Targets Per Source Epoch in Attester Protection
  validator/db/kv/attester_protection.go
  validator/db/kv/attester_protection_test.go
Labels: Bug, OK to merge, Priority: Critical, Ready For Review

#8263 Update Dependencies
  WORKSPACE
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review

#8265 Testutil: Can generate attestation at epoch boundary
  shared/testutil/attestation.go
  shared/testutil/attestation_test.go
Labels: Ready For Review

#8230 Implement GetIdentity in the node API
  beacon-chain/node/node.go
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/mock_host.go
  beacon-chain/p2p/testing/mock_metadataprovider.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/rpc/nodev1/BUILD.bazel
  beacon-chain/rpc/nodev1/node.go
  beacon-chain/rpc/nodev1/node_test.go
  beacon-chain/rpc/nodev1/server.go
  beacon-chain/rpc/service.go
Labels: API, OK to merge, Ready For Review

#8260 Prune Excess Peers Better
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/sync/rpc_status.go
Labels: Networking, OK to merge, Ready For Review

#8266 Add `on_block` finality test
  beacon-chain/blockchain/process_block_test.go
Labels: OK to merge, Ready For Review

#8270 Blocks filtering should return genesis when startSlot=0 and endSlot=0
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
Labels: OK to merge

#8271 Implement Migration Up/Down Logic for Validator DB
  validator/db/BUILD.bazel
  validator/db/cmd.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/attester_protection.go
  validator/db/kv/db.go
  validator/db/kv/migration.go
  validator/db/kv/migration_optimal_attester_protection.go
  validator/db/kv/migration_optimal_attester_protection_test.go
  validator/db/kv/schema.go
  validator/db/migrate.go
  validator/node/node.go
Labels: Priority: High, Ready For Review

#8272 Add a helper to validate nil attestation
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_attestation.go
Labels: OK to merge, Ready For Review

#8269 isCanonical for slot 0 should return true
  beacon-chain/rpc/beacon/validators.go
  beacon-chain/rpc/beacon/validators_test.go
Labels: OK to merge

#8279 Allow Validator Database Rollbacks
  validator/db/BUILD.bazel
  validator/db/migrate.go
  validator/db/migrate_test.go
  validator/db/testing/BUILD.bazel
  validator/db/testing/setup_db.go
Labels: OK to merge, Priority: Critical, Ready For Review

#8280 Use remote cache in CI
  .buildkite-bazelrc
Labels: CI, OK to merge

#8281 Revert "Use remote cache in CI"
  .buildkite-bazelrc
Labels: CI, OK to merge

#8275 Add Initial Support For Gossip Scoring Service
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/peers/peerdata/BUILD.bazel
  beacon-chain/p2p/peers/peerdata/store.go
  beacon-chain/p2p/peers/scorers/BUILD.bazel
  beacon-chain/p2p/peers/scorers/gossip_scorer.go
  beacon-chain/p2p/peers/scorers/gossip_scorer_test.go
  beacon-chain/p2p/peers/scorers/service.go
  beacon-chain/p2p/pubsub.go
  beacon-chain/rpc/debug/p2p.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/db/powchain.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/debug.pb.go
  proto/beacon/rpc/v1/debug.proto
  proto/beacon/rpc/v1/health.pb.go
  proto/beacon/rpc/v1_gateway/debug.pb.go
  proto/faucet/faucet.pb.go
  proto/slashing/slashing.pb.go
  proto/testing/test.pb.go
  proto/validator/accounts/v2/keymanager.pb.go
  proto/validator/accounts/v2/web_api.pb.go
Labels: Networking, OK to merge, Ready For Review

#8286 Better receiver names in beacon chain module
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/cache/subnet_ids.go
  beacon-chain/db/kv/state_summary_cache.go
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/block.go
  beacon-chain/operations/attestations/kv/forkchoice.go
  beacon-chain/operations/attestations/kv/seen_bits.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/p2p/pubsub_filter.go
  beacon-chain/p2p/types/types.go
  beacon-chain/powchain/block_cache.go
  beacon-chain/rpc/validator/proposer_utils.go
Labels: Cleanup, OK to merge, Ready For Review

#8292 Stamp binaries by default
  .bazelrc
Labels: OK to merge, Ready For Review

#8273 Add verify slot target epoch function and apply all
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_attestation.go
Labels: OK to merge, Ready For Review

#8293 Add test TestStore_OnAttestation_Ok
  beacon-chain/blockchain/process_attestation_test.go
Labels: OK to merge, Ready For Review

#8291 Update fastssz
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8285 Return error on `AttestingIndices` bitfield length check
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/signature.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/debug/block.go
  beacon-chain/rpc/debug/block_test.go
  beacon-chain/rpc/validator/aggregator_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  shared/attestationutil/attestation_utils.go
  shared/attestationutil/attestation_utils_test.go
Labels: OK to merge, Ready For Review

#8295 Update bitfield dependency
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8276 Remove duplicated LMD FFG check for fork choice attestation
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
Labels: OK to merge, Ready For Review

#8296 Better receiver names in validator and slasher modules
  slasher/beaconclient/chain_data.go
  slasher/beaconclient/historical_data_retrieval.go
  slasher/beaconclient/receivers.go
  slasher/beaconclient/service.go
  slasher/beaconclient/submit.go
  slasher/beaconclient/validator_retrieval.go
  slasher/db/kv/attester_slashings.go
  slasher/db/kv/block_header.go
  slasher/db/kv/chain_data.go
  slasher/db/kv/highest_attestation.go
  slasher/db/kv/indexed_attestations.go
  slasher/db/kv/kv.go
  slasher/db/kv/proposer_slashings.go
  slasher/db/kv/spanner_new.go
  slasher/db/kv/validator_id_pubkey.go
  slasher/db/types/types.go
  slasher/detection/attestations/mock_spanner.go
  slasher/detection/attestations/types/types.go
  slasher/detection/detect.go
  slasher/detection/listeners.go
  slasher/detection/proposals/detector.go
  slasher/detection/service.go
  slasher/node/node.go
  slasher/rpc/server.go
  validator/accounts/testing/mock.go
  validator/db/kv/attester_protection.go
  validator/db/kv/db.go
  validator/db/kv/deprecated_attester_protection.go
  validator/db/kv/migration_optimal_attester_protection.go
  validator/db/kv/proposer_protection.go
  validator/db/kv/prune_attester_protection.go
  validator/keymanager/derived/keymanager.go
  validator/keymanager/imported/backup.go
  validator/keymanager/imported/enable_disable.go
  validator/keymanager/imported/import.go
  validator/keymanager/imported/keymanager.go
  validator/keymanager/imported/refresh.go
  validator/keymanager/remote/keymanager.go
  validator/node/node.go
Labels: Cleanup, OK to merge, Ready For Review

#8288 Implement ListPeers in the node API
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/testing/mock_peersprovider.go
  beacon-chain/rpc/nodev1/BUILD.bazel
  beacon-chain/rpc/nodev1/node.go
  beacon-chain/rpc/nodev1/node_test.go
  deps.bzl
  go.mod
  go.sum
Labels: API, OK to merge, Ready For Review

#8277 Remove duplicated target root check for fork choice attestation
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_test.go
Labels: OK to merge, Ready For Review

#8302 verifyDepositDataWithDomain: Use helpers.ComputeSigningRoot
  beacon-chain/core/blocks/deposit.go
Labels: Cleanup, OK to merge, Ready For Review

#8268 Align Slashing Interchange With Optimized Slashing Protection
  shared/slashutil/BUILD.bazel
  shared/slashutil/double_votes.go
  shared/slashutil/double_votes_test.go
  validator/client/BUILD.bazel
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/client/propose_test.go
  validator/db/iface/interface.go
  validator/db/kv/attester_protection.go
  validator/db/kv/migration_optimal_attester_protection.go
  validator/slashing-protection/BUILD.bazel
  validator/slashing-protection/cli_import_export_test.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/export_test.go
  validator/slashing-protection/local/standard-protection-format/format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
  validator/testing/protection_history.go
Labels: Ready For Review

#8257 Remove go-ssz entirely from prysm
  DEPENDENCIES.md
  WORKSPACE
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/header_test.go
  beacon-chain/core/blocks/spectest/BUILD.bazel
  beacon-chain/core/epoch/precompute/spectest/BUILD.bazel
  beacon-chain/core/epoch/spectest/BUILD.bazel
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/spectest/BUILD.bazel
  beacon-chain/db/kafka/BUILD.bazel
  beacon-chain/db/kafka/export_wrapper.go
  beacon-chain/p2p/types/BUILD.bazel
  beacon-chain/p2p/types/types.go
  beacon-chain/p2p/types/types_test.go
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/types_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  deps.bzl
  fuzz/BUILD.bazel
  go.mod
  go.sum
  proto/testing/BUILD.bazel
  proto/testing/ssz_regression_test.go
  proto/testing/ssz_static_test.go
  shared/testutil/BUILD.bazel
  shared/testutil/helpers.go
  shared/testutil/helpers_test.go
  slasher/rpc/BUILD.bazel
  slasher/rpc/server_test.go
  tools/pcli/BUILD.bazel
  tools/pcli/main.go
  validator/client/BUILD.bazel
  validator/client/aggregate.go
  validator/client/propose.go
Labels: OK to merge, Ready For Review

#8301 Rm forkchoice attestation verification
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_helpers.go
  shared/attestationutil/attestation_utils.go
  shared/attestationutil/attestation_utils_test.go
Labels: OK to merge, Ready For Review

#8303 Remove unnecessary state copy
  beacon-chain/blockchain/process_attestation_helpers.go
Labels: Cleanup, Ready For Review

#8305 Update bitfield dependency
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8253 Safe Math for ETH1 Batch Headers Request
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: OK to merge, Ready For Review

#8307 Update to v1.15.7
  WORKSPACE
Labels: Ready For Review, Security

#8308 Attestation aggregation: baseline benchmark
  shared/aggregation/attestations/attestations_bench_test.go
Labels: OK to merge, Ready For Review

#8306 Peer count node api
  beacon-chain/rpc/nodev1/node.go
  beacon-chain/rpc/nodev1/node_test.go
Labels: API, OK to merge, Ready For Review

#8310 Refactor `on_attestation` return signature
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/receive_attestation.go
Labels: Cleanup, OK to merge, Ready For Review

#8313 GetDuties: Refactor assignment status to deduplicate status computation
  beacon-chain/rpc/validator/assignments.go
Labels: Cleanup, Ready For Review

#8304 Batch Save Imported EIP-3076 Attestations
  validator/db/iface/interface.go
  validator/db/kv/attester_protection.go
  validator/db/kv/attester_protection_test.go
  validator/slashing-protection/local/standard-protection-format/import.go
Labels: OK to merge, Ready For Review

#8315 Fix Deposit Count Metrics
  beacon-chain/powchain/service.go
Labels: Ready For Review

#8311 Max-cover: minor optimizations
  shared/aggregation/attestations/maxcover.go
  shared/aggregation/attestations/maxcover_test.go
Labels: Ready For Review

#8318 Replace bytes.Equal with assert.DeepEqual in tests
  beacon-chain/blockchain/head_test.go
  beacon-chain/core/blocks/randao_test.go
  beacon-chain/core/state/skip_slot_cache_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/db/kv/migration_archived_index_test.go
  beacon-chain/db/kv/migration_block_slot_index_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/options_test.go
  beacon-chain/p2p/types/types_test.go
  beacon-chain/rpc/beaconv1/blocks_test.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/state/state_trie_test.go
  beacon-chain/state/stateutil/attestations_test.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/rpc_test.go
Labels: Cleanup, OK to merge, Ready For Review

#8309 Refactor `verifyAttestationIndices` method
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_helpers.go
Labels: Cleanup, OK to merge, Ready For Review

#8312 Test for `processAttestations`
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service.go
Labels: OK to merge, Ready For Review

#8119 Allow dynamic key reloading when having inactive keys (imported & derived)
  validator/accounts/BUILD.bazel
  validator/accounts/accounts.go
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_list.go
  validator/accounts/accounts_list_test.go
  validator/accounts/wallet_create.go
  validator/accounts/wallet_edit.go
  validator/client/BUILD.bazel
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/client/wait_for_activation.go
  validator/client/wait_for_activation_test.go
  validator/keymanager/BUILD.bazel
  validator/keymanager/derived/BUILD.bazel
  validator/keymanager/derived/keymanager.go
  validator/keymanager/remote/BUILD.bazel
  validator/keymanager/remote/keymanager.go
  validator/keymanager/types.go
Labels: Accounts, OK to merge, Ready For Review

#8024 [Feature] - Slashing Interchange Support
  WORKSPACE
  shared/promptutil/prompt.go
  shared/slashutil/BUILD.bazel
  shared/slashutil/double_votes.go
  shared/slashutil/double_votes_test.go
  validator/BUILD.bazel
  validator/accounts/prompt/prompt.go
  validator/client/BUILD.bazel
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/client/attest_test.go
  validator/client/propose.go
  validator/client/propose_protect.go
  validator/client/propose_protect_test.go
  validator/client/propose_test.go
  validator/client/service.go
  validator/client/slashing_protection_interchange_test.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/attester_protection.go
  validator/db/kv/attester_protection_test.go
  validator/db/kv/db.go
  validator/db/kv/deprecated_attester_protection.go
  validator/db/kv/deprecated_attester_protection_test.go
  validator/db/kv/eip_blacklisted_keys.go
  validator/db/kv/eip_blacklisted_keys_test.go
  validator/db/kv/migration_optimal_attester_protection.go
  validator/db/kv/proposer_protection.go
  validator/db/kv/proposer_protection_test.go
  validator/db/kv/schema.go
  validator/flags/flags.go
  validator/keymanager/imported/import.go
  validator/main.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/slashing-protection/BUILD.bazel
  validator/slashing-protection/cli_export.go
  validator/slashing-protection/cli_import.go
  validator/slashing-protection/cli_import_export_test.go
  validator/slashing-protection/cmd.go
  validator/slashing-protection/iface/BUILD.bazel
  validator/slashing-protection/iface/protector.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/export.go
  validator/slashing-protection/local/standard-protection-format/export_test.go
  validator/slashing-protection/local/standard-protection-format/format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/format/format.go
  validator/slashing-protection/local/standard-protection-format/helpers.go
  validator/slashing-protection/local/standard-protection-format/helpers_test.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
  validator/testing/BUILD.bazel
  validator/testing/protection_history.go
Labels: Ready For Review

#8321 Fix Deadlock in Runtime
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/state_test.go
  beacon-chain/state/state_trie.go
  beacon-chain/state/validator_map_test.go
Labels: Priority: High, Ready For Review

#8289 Cancel node context after StopAll
  beacon-chain/node/node.go
  slasher/node/node.go
  validator/node/node.go
Labels: Ready For Review

#8322 Update the Toolchain Registration
  WORKSPACE
Labels: OK to merge, Ready For Review

#8329 Remove test assertion that reads a package-level variable
  validator/accounts/accounts_import_test.go
Labels: OK to merge, Ready For Review

#8326 Fix IPV6 binding for Beacon Node
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
Labels: Networking, OK to merge, Ready For Review

#8320 Rename getter functions to be idiomatic
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/core/blocks/signature.go
  beacon-chain/core/helpers/signing_root.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/fork.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/peers/benchmark_test.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/utils.go
  beacon-chain/rpc/beacon/attestations.go
  beacon-chain/rpc/node/server.go
  beacon-chain/rpc/node/server_test.go
  beacon-chain/rpc/nodev1/node.go
  beacon-chain/rpc/nodev1/node_test.go
  beacon-chain/rpc/validator/assignments.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/state/state_trie.go
  beacon-chain/state/stateutil/arrays.go
  beacon-chain/state/stateutil/trie_helpers.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/subscriber.go
  endtoend/components/beacon_node.go
  endtoend/endtoend_test.go
  endtoend/evaluators/metrics.go
  endtoend/helpers/epochTimer.go
  fuzz/testing/beacon_fuzz_states.go
  fuzz/testing/beacon_fuzz_states_test.go
  shared/htrutils/merkleize.go
  shared/htrutils/merkleize_test.go
  shared/iputils/external_ip.go
  shared/keystore/keystore.go
  shared/prereq/prereq.go
  shared/prometheus/logrus_collector_test.go
  shared/slotutil/slotticker.go
  shared/slotutil/slotticker_test.go
  shared/tracing/tracer.go
  shared/version/version.go
  slasher/main.go
  slasher/node/node.go
  tools/analyzers/errcheck/analyzer.go
  tools/analyzers/slicedirect/testdata/slice.go
  tools/bootnode/bootnode.go
  tools/deployContract/deployContract.go
  tools/drainContracts/drainContracts.go
  tools/eth1exporter/main.go
  tools/pcli/main.go
  validator/client/validator.go
  validator/client/wait_for_activation.go
  validator/main.go
  validator/node/node.go
  validator/rpc/health.go
  validator/slashing-protection/local/standard-protection-format/export.go
  validator/slashing-protection/local/standard-protection-format/export_test.go
Labels: OK to merge

#8317 Rename non-generated files ending with '_mock'
  beacon-chain/powchain/testing/BUILD.bazel
  beacon-chain/powchain/testing/mock_faulty_powchain.go
  beacon-chain/powchain/testing/mock_powchain.go
  validator/testing/BUILD.bazel
  validator/testing/mock_protector.go
  validator/testing/mock_slasher.go
Labels: Cleanup, OK to merge, Ready For Review

#8336 Change sszutil DeepEqual to ignore unexported fields
  shared/sszutil/deep_equal.go
  shared/sszutil/deep_equal_test.go
Labels: Ready For Review

#8338 Update bitfield dependency
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8316 Implement GetDepositContract in the config API
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/config.go
  beacon-chain/rpc/beaconv1/config_test.go
Labels: API, OK to merge, Ready For Review

#8337 Rename `NewService` to `New`
  beacon-chain/blockchain/info_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/node/node.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/operations/attestations/prune_expired_test.go
  beacon-chain/operations/attestations/service.go
  beacon-chain/operations/attestations/service_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/peers/scorers/service.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/pubsub_filter_test.go
  beacon-chain/p2p/pubsub_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/service.go
  fuzz/block_fuzz.go
  fuzz/rpc_status_fuzz.go
  shared/prometheus/logrus_collector_test.go
  shared/prometheus/service.go
  shared/prometheus/service_test.go
  slasher/beaconclient/service.go
  slasher/detection/service.go
  slasher/node/node.go
  slasher/rpc/server_test.go
  slasher/rpc/service.go
  slasher/rpc/service_test.go
  validator/node/node.go
  validator/slashing-protection/slasher_client.go
Labels: OK to merge, Ready For Review

#8339 Update Prombolt Collector
  beacon-chain/db/kv/kv.go
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge

#8332 Update seen att slashing cache to use map
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_attester_slashing_test.go
Labels: OK to merge, Ready For Review

#8335 Begin Slasher Service Definition and Configuration
  beacon-chain/slasher/BUILD.bazel
  beacon-chain/slasher/doc.go
  beacon-chain/slasher/log.go
  beacon-chain/slasher/params.go
  beacon-chain/slasher/params_test.go
  beacon-chain/slasher/receive.go
  beacon-chain/slasher/receive_test.go
  beacon-chain/slasher/service.go
  beacon-chain/slasher/service_test.go
  beacon-chain/slasher/types/BUILD.bazel
  beacon-chain/slasher/types/types.go
Labels: Ready For Review

#8341 Handle subscriber error
  validator/client/attest.go
  validator/client/service.go
  validator/client/validator.go
Labels: Ready For Review

#8343 More blockchain pkg tests
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/metrics_test.go
  beacon-chain/blockchain/service_test.go
Labels: Ready For Review

#8334 process grpc header flag for exit
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_exit.go
  validator/accounts/accounts_exit_test.go
  validator/accounts/wallet_create_test.go
Labels: OK to merge

#8348 Wait for one third before grabbing the lock
  validator/client/attest.go
Labels: Ready For Review

#8347 Add role based lock for validator
  validator/client/attest.go
  validator/client/propose.go
Labels: OK to merge, Ready For Review

#8342 Add Database Schema and Methods for Optimized Slasher
  beacon-chain/db/iface/BUILD.bazel
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/BUILD.bazel
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/slasher.go
  beacon-chain/db/kv/slasher_test.go
  beacon-chain/slasher/BUILD.bazel
  beacon-chain/slasher/params.go
  beacon-chain/slasher/params_test.go
  beacon-chain/slasher/types/types.go
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review

#8349 Use strings builder for attester lock key
  validator/client/attest.go
Labels: OK to merge, Ready For Review

#8328 Implement GetSpec in the config API
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/config.go
  beacon-chain/rpc/beaconv1/config_test.go
  shared/params/config.go
  shared/params/mainnet_config.go
  shared/params/testnet_e2e_config.go
  shared/params/testnet_pyrmont_config.go
  shared/params/testnet_toledo_config.go
Labels: API, OK to merge, Ready For Review

#8354 Introduce helper function for adding context metadata from gRPC headers
  shared/grpcutils/BUILD.bazel
  shared/grpcutils/grpcutils.go
  shared/grpcutils/grpcutils_test.go
  slasher/beaconclient/service.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_exit.go
  validator/client/BUILD.bazel
  validator/client/service.go
  validator/rpc/BUILD.bazel
  validator/rpc/beacon.go
  validator/rpc/beacon_test.go
  validator/slashing-protection/BUILD.bazel
  validator/slashing-protection/slasher_client.go
  validator/slashing-protection/slasher_client_test.go
Labels: Cleanup

#8352 Max-cover: optimized implementation based on Bitlist64
  shared/aggregation/BUILD.bazel
  shared/aggregation/maxcover.go
  shared/aggregation/maxcover_bench_test.go
  shared/aggregation/maxcover_test.go
  shared/aggregation/testing/bitlistutils.go
Labels: OK to merge, Ready For Review

#8345 Implement GetForkSchedule in the config API
  beacon-chain/rpc/beaconv1/config.go
  beacon-chain/rpc/beaconv1/config_test.go
  deps.bzl
  go.mod
  go.sum
Labels: API, Ready For Review

#8350 Defining and Implementing the Chunker Interface for MinSpans
  beacon-chain/slasher/BUILD.bazel
  beacon-chain/slasher/chunks.go
  beacon-chain/slasher/chunks_test.go
  beacon-chain/slasher/types/types.go
Labels: Ready For Review

#8356 Update bitfield dependency
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8359 Bind Discovery Using Neutral Network Version
  beacon-chain/p2p/discovery.go
Labels: Networking, Ready For Review

#8360 Add wallet file flag to edit-config command
  validator/accounts/cmd_wallet.go
Labels: OK to merge, Ready For Review

#8357 Next slot state caching
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/state/BUILD.bazel
  beacon-chain/core/state/trailing_slot_state_cache.go
  beacon-chain/core/state/trailing_slot_state_cache_test.go
  beacon-chain/core/state/transition.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/rpc/validator/proposer.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#8358 Implement MaxSpanChunksSlice for Optimized Slasher
  beacon-chain/slasher/chunks.go
  beacon-chain/slasher/chunks_test.go
Labels: Ready For Review

#8364 Update bitfield dependency
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8368 Remove unused channel from Powchain Service
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
Labels: Cleanup, OK to merge, Ready For Review

#8366 Update README.md
  README.md
Labels: OK to merge, Ready For Review

#8363 Remove unused feature flag config fields
  shared/featureconfig/config.go
Labels: Cleanup, OK to merge, Ready For Review
