Repository OffchainLabs/prysm, pull requests merged in 2021-10, with the labels that each got.

#9723 Use Unique Slot Time Tickers for Slasher
  beacon-chain/slasher/service.go
  beacon-chain/slasher/service_test.go
Labels: Ready For Review, Priority: Critical, OK to merge

#9597 Add Golangci-lint to GitHub Actions and add Deadcode linter
  .github/workflows/go.yml
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  config/features/flags.go
Labels: OK to merge

#9727 Pin Base Images
  WORKSPACE
  tools/BUILD.bazel
Labels: Ready For Review, OK to merge, Security

#9722 eth2 api: use balance instead of effective balance
  beacon-chain/rpc/eth/beacon/validator.go
  beacon-chain/rpc/eth/beacon/validator_test.go
Labels: Ready For Review, OK to merge

#9732 Web UI Fix for Prysm V2.0.0
  api/gateway/gateway.go
Labels: Ready For Review, OK to merge

#9735 Register Slashing Protection Client in Validator
  validator/client/service.go
Labels: Ready For Review, OK to merge

#9541 GetBlock() - Simple optimisations
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  config/features/config.go
  config/features/flags.go
Labels: Ready For Review

#9728 Allow fetching sync committee duties for current and next period's epochs
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
Labels: Ready For Review, API

#9742 Bring Eth2FastAggregateVerify Inline With the Spec
  crypto/bls/blst/signature.go
Labels: Ready For Review, Security

#9747 Health Endpoints Not Registered in Validator gRPC Gateway Fix
  validator/node/node.go
Labels: Ready For Review, OK to merge

#9838 Use GET Request for Slashing Protection Export
  proto/prysm/v1alpha1/validator-client/web_api.pb.go
  proto/prysm/v1alpha1/validator-client/web_api.pb.gw.go
  proto/prysm/v1alpha1/validator-client/web_api.proto
Labels: Ready For Review, OK to merge

#9830 Remove de-duplication condition for seen aggregates
  beacon-chain/sync/validate_aggregate_proof.go
Labels: Ready For Review, OK to merge
