Repository OffchainLabs/prysm, pull requests merged in 2021-11, with the labels that each got.

#9831 Fix Individual Votes RPC Endpoint
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/altair/epoch_precompute_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
Labels: Ready For Review

#9834 Use `BeaconBlockIsNil` helper more
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/altair/attestation.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/header.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/helpers/block.go
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/db/kv/backup.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/state.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  testing/endtoend/evaluators/fork.go
Labels: Ready For Review, OK to merge

#9817 Define Validator Key Management Standard API Schema
  proto/eth/service/BUILD.bazel
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.pb.gw.go
  proto/eth/service/key_management.proto
Labels: Ready For Review, OK to merge, Accounts, Web UI

#9847 stateutil: Remove duplicated MerkleizeTrieLeaves method
  beacon-chain/state/fieldtrie/field_trie.go
  beacon-chain/state/stateutil/trie_helpers.go
  beacon-chain/state/stateutil/trie_helpers_test.go
Labels: Ready For Review, OK to merge

#9841 Rename Interop-Cold-Start Package to Deterministic-Genesis
  beacon-chain/deterministic-genesis/BUILD.bazel
  beacon-chain/deterministic-genesis/log.go
  beacon-chain/deterministic-genesis/service.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
Labels: Ready For Review, OK to merge

#9848 Validate Password on RPC CreateWallet Request
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: Ready For Review, OK to merge

#9846 Return proper responses from `KeyManagement` service
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.proto
Labels: Ready For Review, OK to merge, API

#9849 Empty Genesis Validators Root Check in Slashing Protection Export
  validator/rpc/slashing_test.go
  validator/slashing-protection/local/standard-protection-format/export.go
  validator/slashing-protection/local/standard-protection-format/export_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
Labels: Ready For Review, OK to merge

#9832 Weak subjectivity verification refactor
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/weak_subjectivity_checks.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
Labels: Ready For Review, OK to merge

#9840 Use prev epoch source naming correctly
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/altair/epoch_precompute_test.go
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/epoch/precompute/type.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/state/phase0.go
Labels: Ready For Review, OK to merge

#9837 Simplify should update justified
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: Ready For Review, OK to merge

#9855 Rename Web UI Performance Endpoint to Summary
  proto/prysm/v1alpha1/validator-client/web_api.pb.go
  proto/prysm/v1alpha1/validator-client/web_api.pb.gw.go
  proto/prysm/v1alpha1/validator-client/web_api.proto
Labels: Ready For Review, OK to merge

#9857 Use ` math.MaxUint64`
  beacon-chain/rpc/prysm/v1alpha1/debug/block.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  time/slots/slottime_test.go
Labels: Ready For Review, OK to merge

#9845 State fixed-size array: `block_roots` and `state_roots`
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/upgrade.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/state.go
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/state/custom-types/state_arrays.go
  beacon-chain/state/phase0.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/field_roots.go
  beacon-chain/state/v1/getters_block.go
  beacon-chain/state/v1/getters_state.go
  beacon-chain/state/v1/setters_block.go
  beacon-chain/state/v1/setters_state.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/field_roots.go
  beacon-chain/state/v2/getters_block.go
  beacon-chain/state/v2/getters_state.go
  beacon-chain/state/v2/setters_block.go
  beacon-chain/state/v2/setters_state.go
  deps.bzl
  go.mod
  go.sum
  proto/eth/v1/beacon_state.pb.go
  proto/eth/v1/beacon_state.proto
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/eth/v2/generated.ssz.go
  proto/migration/BUILD.bazel
  proto/migration/v1alpha1_to_v1.go
  proto/prysm/v1alpha1/beacon_state.pb.go
  proto/prysm/v1alpha1/beacon_state.proto
  proto/prysm/v1alpha1/generated.ssz.go
  testing/util/BUILD.bazel
  testing/util/altair.go
  testing/util/state.go
  tools/exploredb/main.go
Labels: Ready For Review, OKR Item

#9861 State fixed-size array: `historical_roots` and `randao_mixes`
  beacon-chain/core/altair/upgrade.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/transition/state.go
  beacon-chain/state/custom-types/state_arrays.go
  beacon-chain/state/phase0.go
  beacon-chain/state/v1/field_roots.go
  beacon-chain/state/v1/getters_misc.go
  beacon-chain/state/v1/getters_randao.go
  beacon-chain/state/v1/setters_misc.go
  beacon-chain/state/v1/setters_randao.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v2/field_roots.go
  beacon-chain/state/v2/getters_misc.go
  beacon-chain/state/v2/getters_randao.go
  beacon-chain/state/v2/setters_misc.go
  beacon-chain/state/v2/setters_randao.go
  beacon-chain/state/v2/state_trie.go
  deps.bzl
  encoding/bytesutil/bytes.go
  go.mod
  go.sum
  proto/eth/v1/beacon_state.pb.go
  proto/eth/v1/beacon_state.proto
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/eth/v2/generated.ssz.go
  proto/migration/v1alpha1_to_v1.go
  proto/prysm/v1alpha1/beacon_state.pb.go
  proto/prysm/v1alpha1/beacon_state.proto
  proto/prysm/v1alpha1/generated.ssz.go
  testing/util/altair.go
  testing/util/state.go
  tools/exploredb/main.go
Labels: Ready For Review, OKR Item

#9852 fix #9851 using GenesisState when zero hash in stategen StateByRoot/StateByRootInitialSync
  beacon-chain/state/stategen/getter.go
Labels: OK to merge

#9866 GenesisState when zero hash tests
  beacon-chain/state/stategen/getter_test.go
Labels: Ready For Review

#9843 Share finalized state at start up
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/options.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/state/stategen/mock.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/service.go
  beacon-chain/state/stategen/service_test.go
Labels: Ready For Review, OK to merge

#9864 Move `GenesisTime` to the native beacon state
  beacon-chain/core/altair/upgrade.go
  beacon-chain/core/transition/state.go
  beacon-chain/state/v1/field_roots.go
  beacon-chain/state/v1/getters_misc.go
  beacon-chain/state/v1/getters_state.go
  beacon-chain/state/v1/setters_misc.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v1/types.go
  beacon-chain/state/v2/field_roots.go
  beacon-chain/state/v2/getters_misc.go
  beacon-chain/state/v2/getters_state.go
  beacon-chain/state/v2/setters_misc.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v2/types.go
  proto/prysm/v1alpha1/beacon_state.pb.go
  proto/prysm/v1alpha1/generated.ssz.go
  testing/util/altair.go
Labels: Ready For Review, OKR Item

#9865 Update Kintsugi engine API
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/powchain/execution_engine.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/service.go
  deps.bzl
  go.mod
  go.sum
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_debug_service.pb.gw.go
  proto/eth/service/validator_service.pb.gw.go
Labels: Kintsugi :tea:

#9863 Implement List Keystores for Standard API
  validator/rpc/BUILD.bazel
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
Labels: Ready For Review, OK to merge

#9867 Kintsugi ssz
  beacon-chain/blockchain/process_block.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  deps.bzl
  encoding/ssz/BUILD.bazel
  encoding/ssz/htrutils.go
  go.mod
  go.sum
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/executionpayload.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
  proto/prysm/v1alpha1/transaction.ssz.go
  testing/spectest/shared/merge/ssz_static/BUILD.bazel
  testing/spectest/shared/merge/ssz_static/execpayload_test.go
  testing/spectest/shared/merge/ssz_static/ssz_static.go
Labels: Kintsugi :tea:

#9872 Update Kintsugi consensus implementations
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  deps.bzl
  encoding/ssz/htrutils.go
  go.mod
  go.sum
  testing/spectest/shared/merge/ssz_static/execpayload_test.go
Labels: Kintsugi :tea:

#9871 Move primitive fields to the native beacon state
  beacon-chain/core/altair/upgrade.go
  beacon-chain/core/transition/state.go
  beacon-chain/state/v1/field_roots.go
  beacon-chain/state/v1/getters_eth1.go
  beacon-chain/state/v1/getters_misc.go
  beacon-chain/state/v1/getters_state.go
  beacon-chain/state/v1/getters_validator.go
  beacon-chain/state/v1/setters_eth1.go
  beacon-chain/state/v1/setters_misc.go
  beacon-chain/state/v1/setters_validator.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v1/types.go
  beacon-chain/state/v2/getters_eth1.go
  beacon-chain/state/v2/getters_misc.go
  beacon-chain/state/v2/getters_participation.go
  beacon-chain/state/v2/getters_state.go
  beacon-chain/state/v2/getters_validator.go
  beacon-chain/state/v2/setters_eth1.go
  beacon-chain/state/v2/setters_misc.go
  beacon-chain/state/v2/setters_participation.go
  beacon-chain/state/v2/setters_validator.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v2/types.go
  proto/prysm/v1alpha1/beacon_state.pb.go
  proto/prysm/v1alpha1/generated.ssz.go
  testing/util/altair.go
  testing/util/state.go
Labels: Ready For Review, OKR Item

#9874 Move remaining non-struct fields out of the proto state
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/upgrade.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/state.go
  beacon-chain/state/v1/field_roots.go
  beacon-chain/state/v1/getters_block.go
  beacon-chain/state/v1/getters_checkpoint.go
  beacon-chain/state/v1/getters_misc.go
  beacon-chain/state/v1/getters_randao.go
  beacon-chain/state/v1/getters_state.go
  beacon-chain/state/v1/setters_block.go
  beacon-chain/state/v1/setters_checkpoint.go
  beacon-chain/state/v1/setters_misc.go
  beacon-chain/state/v1/setters_randao.go
  beacon-chain/state/v1/setters_state.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v1/types.go
  beacon-chain/state/v2/getters_block.go
  beacon-chain/state/v2/getters_checkpoint.go
  beacon-chain/state/v2/getters_misc.go
  beacon-chain/state/v2/getters_randao.go
  beacon-chain/state/v2/getters_state.go
  beacon-chain/state/v2/setters_block.go
  beacon-chain/state/v2/setters_checkpoint.go
  beacon-chain/state/v2/setters_misc.go
  beacon-chain/state/v2/setters_randao.go
  beacon-chain/state/v2/setters_state.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v2/types.go
  proto/prysm/v1alpha1/beacon_state.pb.go
  proto/prysm/v1alpha1/generated.ssz.go
  testing/util/BUILD.bazel
  testing/util/altair.go
  testing/util/state.go
Labels: Ready For Review, OK to merge

#9879 time pkg: can upgrade to merge helper
  beacon-chain/core/time/slot_epoch.go
  beacon-chain/core/time/slot_epoch_test.go
Labels: Ready For Review, OK to merge, Merge

#9875 Update spec tests to v1.1.5
  WORKSPACE
  config/params/loader_test.go
Labels: Ready For Review, OK to merge, Merge

#9890 Remove unused import
  proto/prysm/v1alpha1/validator-client/keymanager.proto
Labels: Ready For Review, OK to merge

#9894 Remove Superflous Errors From Parameter Registration
  beacon-chain/p2p/gossip_scoring_params.go
  beacon-chain/p2p/gossip_scoring_params_test.go
Labels: Ready For Review, OK to merge, Cleanup

#9896 Update security.txt
  .well-known/security.txt
Labels: OK to merge

#9891 Add cli override setting for merge
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/config.go
  beacon-chain/node/config_test.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/config_test.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  config/params/BUILD.bazel
  config/params/config.go
  config/params/loader_test.go
  config/params/mainnet_config.go
Labels: Ready For Review, Merge

#9892 Improve RNG Documentation
  crypto/rand/rand.go
Labels: OK to merge, Security

#9884 Use Next Slot Cache In More Places
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
Labels: Ready For Review, OK to merge

#9893 Exit Scoring Service Properly
  beacon-chain/p2p/peers/scorers/service.go
Labels: Security

#9860 Change Gossip message size and Chunk SIze from 1 MB t0 10MB
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/encoder/ssz_test.go
  beacon-chain/p2p/fork_watcher.go
  beacon-chain/p2p/message_id.go
  beacon-chain/p2p/message_id_test.go
  config/params/mainnet_config.go
  config/params/network_config.go
Labels: Kintsugi :tea:

#9903 Clean Up Methods In Prysm
  beacon-chain/cache/skip_slot_cache.go
  beacon-chain/cache/skip_slot_cache_test.go
  beacon-chain/core/signing/domain.go
  beacon-chain/core/signing/domain_test.go
  beacon-chain/core/transition/transition.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/operations.go
  beacon-chain/db/kv/operations_test.go
  beacon-chain/db/kv/slashings.go
  beacon-chain/db/kv/slashings_test.go
  beacon-chain/state/phase0.go
  beacon-chain/state/v1/setters_state.go
  beacon-chain/state/v2/setters_state.go
  monitoring/clientstats/scrapers.go
  validator/client/slashing_protection_interchange_test.go
  validator/slashing-protection-history/round_trip_test.go
Labels: Ready For Review, Cleanup

#9887 Add merge block protobuf
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
Labels: Ready For Review, OK to merge, Merge

#9900 Register start-up state when interop mode
  beacon-chain/node/node.go
Labels: Ready For Review, OK to merge

#9898 Validator monitor process slashings
  beacon-chain/core/blocks/attester_slashing.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/monitor/BUILD.bazel
  beacon-chain/monitor/doc.go
  beacon-chain/monitor/process_block.go
  beacon-chain/monitor/process_block_test.go
  beacon-chain/monitor/service.go
  beacon-chain/monitor/service_test.go
Labels: OK to merge

#9888 Add merge state protobuf
  proto/prysm/v1alpha1/beacon_state.pb.go
  proto/prysm/v1alpha1/beacon_state.proto
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
Labels: Ready For Review, OK to merge, Merge

#9907 Add Network Flags to Slashing Protection Export Command
  cmd/validator/slashing-protection/slashing-protection.go
Labels: Ready For Review, OK to merge

#9899 Monitor exits
  beacon-chain/monitor/BUILD.bazel
  beacon-chain/monitor/process_exit.go
  beacon-chain/monitor/process_exit_test.go
Labels: OK to merge

#9885 Add in Deposit Map To Cache
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/cache/depositcache/deposits_cache_test.go
  beacon-chain/powchain/service_test.go
Labels: Ready For Review, OK to merge

#9908 Add merge state type definitions
  beacon-chain/state/types/types.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/types.go
  config/params/config.go
  config/params/mainnet_config.go
  runtime/version/fork.go
Labels: Ready For Review, Merge

#9914 Add field roots for beacon state v3
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/field_root_eth1.go
  beacon-chain/state/v3/field_root_test.go
  beacon-chain/state/v3/field_root_validator.go
  beacon-chain/state/v3/field_root_vector.go
  beacon-chain/state/v3/field_roots.go
Labels: OK to merge

#9904 Prevent Reprocessing of a Block From Our Pending Queue
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
Labels: Ready For Review

#9909 Warn Users if Slashing Protection History is Empty
  cmd/validator/slashing-protection/export.go
Labels: Ready For Review, OK to merge

#9919 Warn Users In Case Slashing Protection Exports are Empty
  cmd/validator/slashing-protection/export.go
Labels: Ready For Review, OK to merge

#9920 Unskip v2 end to end check for prior release
  testing/endtoend/minimal_e2e_test.go
Labels: Ready For Review, OK to merge

#9901 Monitor attestations
  beacon-chain/monitor/BUILD.bazel
  beacon-chain/monitor/process_attestation.go
  beacon-chain/monitor/process_attestation_test.go
  beacon-chain/monitor/service.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/mock.go
  beacon-chain/state/stategen/service.go
Labels: Ready For Review

#9886 Implement Validator Standard Key Manager API Delete Keystores
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.proto
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_delete.go
  validator/keymanager/BUILD.bazel
  validator/keymanager/derived/BUILD.bazel
  validator/keymanager/derived/keymanager.go
  validator/keymanager/imported/BUILD.bazel
  validator/keymanager/imported/delete.go
  validator/keymanager/imported/delete_test.go
  validator/keymanager/imported/keymanager.go
  validator/keymanager/imported/keymanager_test.go
  validator/keymanager/types.go
  validator/keymanager/types_test.go
  validator/rpc/BUILD.bazel
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
  validator/slashing-protection-history/export.go
  validator/slashing-protection-history/round_trip_test.go
Labels: Ready For Review, OK to merge

#9921 Monitor metrics
  beacon-chain/monitor/BUILD.bazel
  beacon-chain/monitor/metrics.go
  beacon-chain/monitor/process_attestation.go
  beacon-chain/monitor/service.go
Labels: Ready For Review, OK to merge

#9822 Switch to lazy state balance cache
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/info_test.go
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/mock_test.go
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/state_balance_cache.go
  beacon-chain/blockchain/state_balance_cache_test.go
  testing/assertions/assertions.go
  testing/require/requires.go
Labels: OK to merge

#9806 Stop packing deposits early if we reach max allowed
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
Labels: Ready For Review, OK to merge

#9915 Add getters and setters for beacon state v3 (part 1)
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/deprecated_getters.go
  beacon-chain/state/v3/deprecated_getters_test.go
  beacon-chain/state/v3/deprecated_setters.go
  beacon-chain/state/v3/deprecated_setters_test.go
  beacon-chain/state/v3/getters_block.go
  beacon-chain/state/v3/getters_block_test.go
  beacon-chain/state/v3/getters_checkpoint.go
  beacon-chain/state/v3/getters_eth1.go
  beacon-chain/state/v3/getters_misc.go
  beacon-chain/state/v3/getters_participation.go
  beacon-chain/state/v3/getters_randao.go
  beacon-chain/state/v3/getters_state.go
  beacon-chain/state/v3/getters_sync_committee.go
  beacon-chain/state/v3/getters_test.go
  beacon-chain/state/v3/getters_validator.go
  beacon-chain/state/v3/getters_validator_test.go
  beacon-chain/state/v3/setters_block.go
  beacon-chain/state/v3/setters_checkpoint.go
  beacon-chain/state/v3/setters_eth1.go
  beacon-chain/state/v3/setters_misc.go
  beacon-chain/state/v3/setters_participation.go
  beacon-chain/state/v3/setters_randao.go
  beacon-chain/state/v3/setters_state.go
  beacon-chain/state/v3/setters_sync_committee.go
  beacon-chain/state/v3/setters_validator.go
  beacon-chain/state/v3/state_trie.go
  beacon-chain/state/v3/types.go
Labels: Ready For Review, Merge

#9910 Monitor blocks
  beacon-chain/monitor/metrics.go
  beacon-chain/monitor/process_attestation_test.go
  beacon-chain/monitor/process_block.go
  beacon-chain/monitor/process_block_test.go
  beacon-chain/monitor/service.go
Labels: Ready For Review

#9916 Add getters and setters for beacon state v3 (part 2)
  beacon-chain/state/v1/unsupported_getters.go
  beacon-chain/state/v1/unsupported_setters.go
  beacon-chain/state/v2/deprecated_getters.go
  beacon-chain/state/v2/deprecated_setters.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/getters_payload_header.go
  beacon-chain/state/v3/setters_payload_header.go
  beacon-chain/state/v3/types.go
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
Labels: Ready For Review, Merge

#9925 Properly generate SSZ files for the native beacon state
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/generated.ssz.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/generated.ssz.go
  deps.bzl
  go.mod
  go.sum
  hack/update-go-ssz.sh
  nogo_config.json
Labels: Ready For Review, OKR Item

#9926 Rename To Signature Batch
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/header_test.go
  beacon-chain/core/blocks/randao_test.go
  beacon-chain/core/blocks/signature.go
  beacon-chain/core/signing/signing_root.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/sync/batch_verifier.go
  beacon-chain/sync/batch_verifier_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_sync_committee_message.go
  beacon-chain/sync/validate_sync_contribution_proof.go
  crypto/bls/BUILD.bazel
  crypto/bls/signature_batch.go
  crypto/bls/signature_batch_test.go
  testing/spectest/shared/altair/operations/attestation.go
  testing/spectest/shared/phase0/operations/attestation.go
Labels: Ready For Review

#9918 Rename coinbase to fee recipient
  beacon-chain/node/config.go
  beacon-chain/node/config_test.go
  beacon-chain/rpc/eth/beacon/config_test.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  config/params/config.go
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/beacon_state.pb.go
  proto/prysm/v1alpha1/beacon_state.proto
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
Labels: OK to merge, Merge

#9928 Use `prysmaticlabs/fastssz`
  deps.bzl
  go.mod
  go.sum
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Ready For Review, OK to merge, Merge

#9929 Add merge beacon chain objects and generate ssz.go
  proto/eth/v1/generated.ssz.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Ready For Review, OK to merge, Merge

#9923 Monitor sync committee
  beacon-chain/cache/sync_committee_test.go
  beacon-chain/monitor/BUILD.bazel
  beacon-chain/monitor/metrics.go
  beacon-chain/monitor/process_attestation.go
  beacon-chain/monitor/process_attestation_test.go
  beacon-chain/monitor/process_block.go
  beacon-chain/monitor/process_block_test.go
  beacon-chain/monitor/process_exit.go
  beacon-chain/monitor/process_exit_test.go
  beacon-chain/monitor/process_sync_committee.go
  beacon-chain/monitor/process_sync_committee_test.go
  beacon-chain/monitor/service.go
  beacon-chain/monitor/service_test.go
  testing/util/sync_committee.go
Labels: Ready For Review

#9931 Revert #9830
  beacon-chain/sync/validate_aggregate_proof.go
Labels: Ready For Review, Priority: High

#9924 Import Keystores Standard API Implementation
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.pb.gw.go
  proto/eth/service/key_management.proto
  proto/prysm/v1alpha1/validator-client/web_api.pb.go
  proto/prysm/v1alpha1/validator-client/web_api.pb.gw.go
  proto/prysm/v1alpha1/validator-client/web_api.proto
  validator/accounts/accounts_import.go
  validator/accounts/accounts_import_test.go
  validator/accounts/accounts_list_test.go
  validator/keymanager/derived/keymanager.go
  validator/keymanager/imported/BUILD.bazel
  validator/keymanager/imported/delete.go
  validator/keymanager/imported/delete_test.go
  validator/keymanager/imported/import.go
  validator/keymanager/imported/import_test.go
  validator/keymanager/imported/keymanager_test.go
  validator/keymanager/types.go
  validator/keymanager/types_test.go
  validator/rpc/server.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: Ready For Review

#9906 Add merge beacon block wrappers
  proto/prysm/v1alpha1/block/block_interfaces.go
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
  proto/prysm/v1alpha1/wrapper/beacon_block.go
  proto/prysm/v1alpha1/wrapper/beacon_block_test.go
  testing/util/block.go
Labels: Ready For Review, Merge

#9939 Rest of the merge state implementation
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/field_roots.go
  beacon-chain/state/v3/getters_state.go
  beacon-chain/state/v3/getters_test.go
  beacon-chain/state/v3/setters_test.go
  beacon-chain/state/v3/state_trie.go
  beacon-chain/state/v3/state_trie_test.go
Labels: Ready For Review, Merge

#9944 Add test utility merge state
  beacon-chain/state/v3/BUILD.bazel
  testing/util/BUILD.bazel
  testing/util/merge_state.go
  testing/util/merge_state_test.go
Labels: OK to merge, Merge

#9945 Allow requests for next sync committee
  beacon-chain/rpc/eth/beacon/sync_committee.go
  beacon-chain/rpc/eth/beacon/sync_committee_test.go
  beacon-chain/rpc/testutil/BUILD.bazel
  beacon-chain/rpc/testutil/mock_genesis_timefetcher.go
Labels: Ready For Review, OK to merge

#9922 Refactor States To Allow for Single Cached Hasher
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/state.go
  beacon-chain/state/fieldtrie/BUILD.bazel
  beacon-chain/state/fieldtrie/field_trie_test.go
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/eth1_root.go
  beacon-chain/state/stateutil/field_root_attestation.go
  beacon-chain/state/stateutil/field_root_eth1.go
  beacon-chain/state/stateutil/field_root_test.go
  beacon-chain/state/stateutil/field_root_validator.go
  beacon-chain/state/stateutil/field_root_vector.go
  beacon-chain/state/stateutil/pending_attestation_root.go
  beacon-chain/state/stateutil/state_hasher.go
  beacon-chain/state/stateutil/trie_helpers_test.go
  beacon-chain/state/stateutil/validator_root.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/field_roots.go
  beacon-chain/state/v1/getters_attestation.go
  beacon-chain/state/v1/getters_eth1.go
  beacon-chain/state/v1/getters_misc.go
  beacon-chain/state/v1/getters_validator.go
  beacon-chain/state/v1/getters_validator_test.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/field_root_test.go
  beacon-chain/state/v2/field_roots.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/field_root_eth1.go
  beacon-chain/state/v3/field_root_validator.go
  beacon-chain/state/v3/field_root_vector.go
  beacon-chain/state/v3/field_roots.go
  beacon-chain/state/v3/state_trie.go
  testing/util/BUILD.bazel
  testing/util/altair.go
Labels: Ready For Review, OK to merge

#9949 Alter config filed name to devnet if it's not populated in file
  config/params/loader.go
  config/params/loader_test.go
Labels: Ready For Review

#9951 Check for syncstatus before performing a voluntary exit
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_exit.go
Labels: Ready For Review, OK to merge

#9955 Update spec tests to v1.1.6
  WORKSPACE
  config/params/loader_test.go
Labels: Ready For Review, OK to merge

#9933 Monitor service
  beacon-chain/monitor/BUILD.bazel
  beacon-chain/monitor/process_attestation_test.go
  beacon-chain/monitor/process_block_test.go
  beacon-chain/monitor/process_exit_test.go
  beacon-chain/monitor/service.go
  beacon-chain/monitor/service_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  cmd/flags.go
  cmd/wrap_flags.go
Labels: Ready For Review
