Repository OffchainLabs/prysm, pull requests merged in 2021-02, with the labels that each got.

#8287 Add canonical flag to ListBlocks API response
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beacon/blocks_test.go
Labels: OK to merge, Ready For Review

#8371 Deprecate enableSyncBacktracking flag
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  shared/featureconfig/config.go
  shared/featureconfig/deprecated_flags.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#8370 Simplify expressions
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/helpers/slot_epoch.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/rpc/validator/attester_test.go
  shared/params/loader.go
  validator/accounts/accounts_import.go
Labels: OK to merge, Ready For Review

#8375 Remove redundant bool return value from CheckSlashable
  beacon-chain/slasher/chunks.go
  beacon-chain/slasher/chunks_test.go
Labels: OK to merge, Ready For Review

#8278 Make validator stable when beacon node goes offline
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#8362 Ajust constructor names of nodes
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
  slasher/main.go
  slasher/node/node.go
  slasher/node/node_test.go
  validator/node/node.go
Labels: Cleanup, OK to merge, Ready For Review

#8376 Add missed feature flag usage
  beacon-chain/blockchain/process_block.go
Labels: OK to merge, Ready For Review

#8377 Update Herumi BLS Library
  deps.bzl
  go.mod
  go.sum
  third_party/herumi/herumi.bzl
Labels: OK to merge, Ready For Review

#8361 Display URLs for tracking exited validators
  shared/params/BUILD.bazel
  shared/params/mainnet_config.go
  shared/params/testnet_e2e_config.go
  shared/params/testnet_pyrmont_config.go
  shared/params/testnet_toledo_config.go
  shared/params/values.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_exit.go
  validator/accounts/accounts_exit_test.go
Labels: Accounts, OK to merge, Ready For Review

#8380 Implement GetGenesis in the beacon API
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/state.go
  beacon-chain/rpc/beaconv1/state_test.go
Labels: API, Ready For Review

#8378 Add Batch Method for Reading Validator Proposing Histories
  validator/db/iface/interface.go
  validator/db/kv/proposer_protection.go
  validator/db/kv/proposer_protection_test.go
  validator/slashing-protection/local/standard-protection-format/BUILD.bazel
  validator/slashing-protection/local/standard-protection-format/export.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
Labels: OK to merge, Priority: High, Ready For Review

#8382 Update Ethdo Keystore Deps
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8385 Update bitfield dependency
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8387 Ran code inspect for clean up
  fuzz/common.go
  shared/bls/blst/stub.go
  tools/analyzers/slicedirect/testdata/slice.go
  validator/accounts/accounts.go
  validator/accounts/accounts_delete.go
  validator/accounts/wallet/wallet.go
  validator/db/kv/attester_protection.go
  validator/keymanager/derived/keymanager.go
  validator/keymanager/remote/keymanager.go
  validator/slashing-protection/cli_export.go
  validator/slashing-protection/local/standard-protection-format/export.go
  validator/slashing-protection/local/standard-protection-format/format/format.go
  validator/slashing-protection/local/standard-protection-format/import.go
  validator/slashing-protection/local/standard-protection-format/import_test.go
  validator/slashing-protection/local/standard-protection-format/round_trip_test.go
  validator/testing/protection_history.go
Labels: Cleanup, Ready For Review

#8389 Revert DEPENDENCIES.md change from #8257
  DEPENDENCIES.md
Labels: OK to merge, Priority: Low, Ready For Review

#8390 Add Spans for Validator DB Methods
  validator/db/kv/attester_protection.go
  validator/db/kv/prune_attester_protection.go
Labels: OK to merge, Ready For Review

#8386 Add Helpers Required for Attestation Slashing Detection, Begin Detection Framework
  beacon-chain/slasher/BUILD.bazel
  beacon-chain/slasher/chunks.go
  beacon-chain/slasher/chunks_test.go
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/detect_attestations_test.go
  beacon-chain/slasher/receive.go
  beacon-chain/slasher/receive_test.go
  beacon-chain/slasher/service.go
  endtoend/endtoend_test.go
  endtoend/helpers/BUILD.bazel
  shared/slotutil/BUILD.bazel
  shared/slotutil/epochticker.go
  shared/slotutil/epochticker_test.go
Labels: Ready For Review

#8391 Revert "Change sszutil DeepEqual to ignore unexported fields"
  shared/sszutil/deep_equal.go
  shared/sszutil/deep_equal_test.go
Labels: OK to merge

#8388 Add Custom Deadline for Slot Progression
  beacon-chain/blockchain/process_block.go
Labels: OK to merge, Ready For Review

#8392 Validator testing library should be marked as testonly
  validator/testing/BUILD.bazel
Labels: OK to merge, Priority: Low, Ready For Review

#7938 Attestation aggregation: optimizations and benchmarks
  shared/aggregation/attestations/attestations.go
  shared/aggregation/attestations/attestations_bench_test.go
  shared/aggregation/attestations/attestations_test.go
  shared/aggregation/attestations/maxcover.go
  shared/aggregation/attestations/maxcover_test.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#8395 Block validator buckets
  validator/db/kv/db.go
Labels: OK to merge, Ready For Review

#8394 Update span names
  beacon-chain/core/state/transition.go
  beacon-chain/state/stategen/replay.go
Labels: Cleanup, OK to merge, Ready For Review

#8400 Detection Further Helpers and Types for Attester Slashing Detection
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/slasher.go
  beacon-chain/db/kv/slasher_test.go
  beacon-chain/slasher/chunks.go
  beacon-chain/slasher/chunks_test.go
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/detect_attestations_test.go
  beacon-chain/slasher/receive.go
  beacon-chain/slasher/receive_test.go
  beacon-chain/slasher/service.go
  beacon-chain/slasher/types/types.go
Labels: Ready For Review

#8403 Clean up unused functions
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/rpc/nodev1/node_test.go
  shared/abool/abool_test.go
  shared/bls/bls.go
  shared/bls/common/error.go
  shared/bls/constants.go
  shared/bls/error.go
  shared/browser/browser.go
  shared/bytesutil/bytes.go
  shared/depositutil/BUILD.bazel
  shared/depositutil/deposit.go
  shared/iputils/external_ip.go
  shared/keystore/keystore.go
  slasher/cache/span_cache.go
  slasher/db/kv/kv_test.go
  validator/client/runner_test.go
  validator/db/kv/migration.go
Labels: Cleanup, OK to merge, Ready For Review

#8398 Use `EnableNextSlotStateCache` few more places
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/rpc/validator/attester.go
Labels: Ready For Review

#8413 Update Herumi with a fix for older intel chips
  third_party/herumi/herumi.bzl
Labels: OK to merge, Ready For Review

#8412 Feature flag: update head timely
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/receive_block.go
  shared/featureconfig/config.go
  shared/featureconfig/flags.go
Labels: OK to merge, Ready For Review

#8381 Update head per slot
  beacon-chain/blockchain/receive_attestation.go
Labels: OK to merge, Ready For Review

#8421 Add DeepSSZEqual and DeepNotSSZEqual
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/state/state_test.go
  beacon-chain/operations/slashings/service_proposer_test.go
  shared/testutil/assert/assertions.go
  shared/testutil/assertions/BUILD.bazel
  shared/testutil/assertions/assertions.go
  shared/testutil/assertions/assertions_test.go
  shared/testutil/require/requires.go
Labels: OK to merge, Ready For Review

#8417 Update ethereumapis deps
  deps.bzl
  go.mod
  go.sum
Labels: OK to merge, Ready For Review

#8418 Provide TLS certificate to gRPC gateway
  beacon-chain/gateway/BUILD.bazel
  beacon-chain/gateway/gateway.go
  beacon-chain/gateway/server/main.go
  beacon-chain/node/node.go
Labels: OK to merge, Ready For Review

#8405 Insert Finalized Deposits In Another Routine
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: Priority: High, Ready For Review

#8420 Add `timeSinceSlotStart` field to "Synced new block..." log
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/receive_block.go
Labels: OK to merge, Ready For Review

#8422 Send feed faster with UpdateHeadTimely feature flag
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_block.go
Labels: OK to merge, Ready For Review

#8423 Detection Algorithm for Optimized Slasher
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/slasher.go
  beacon-chain/db/kv/slasher_test.go
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/detect_attestations_test.go
  beacon-chain/slasher/receive.go
Labels: Ready For Review

#8409 Process attestation: reduce checkpoint copies
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/state/getters.go
  beacon-chain/state/getters_test.go
Labels: OK to merge, Ready For Review

#8397 Make Individual Validators Immutable
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/slashing.go
  beacon-chain/state/getters.go
  beacon-chain/state/references_test.go
  beacon-chain/state/setters.go
Labels: OK to merge, Ready For Review

#8424 Some improvements to proposer cache
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/helpers/validators.go
Labels: OK to merge, Ready For Review

#8415 Exclude unexported fields for protos in sszutils.DeepEqual
  shared/sszutil/BUILD.bazel
  shared/sszutil/deep_equal.go
  shared/sszutil/deep_equal_test.go
Labels: OK to merge, Ready For Review

#8425 Use a Slim Base Image for our Cross-Build Toolchain Docker Image
  tools/cross-toolchain/Dockerfile
  tools/cross-toolchain/configs/clang/bazel_3.7.0/cc/module.modulemap
  tools/cross-toolchain/configs/clang/bazel_3.7.0/config/BUILD
  tools/cross-toolchain/configs/clang/bazel_3.7.0/prysm_toolchains/BUILD.bazel
  tools/cross-toolchain/configs/clang/bazel_3.7.0/prysm_toolchains/cc_toolchain_config_windows.bzl
  tools/cross-toolchain/configs/versions.bzl
  tools/cross-toolchain/rbe_toolchains_config.bzl
Labels: OK to merge, Security

#8319 Refactor validator subnet subscriptions to be non-blocking
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Ready For Review

#8399 Add Ability to Specify All Public Keys When Exiting Validators
  validator/accounts/accounts_exit.go
  validator/accounts/accounts_exit_test.go
  validator/accounts/cmd_accounts.go
  validator/accounts/wallet_create_test.go
  validator/flags/flags.go
Labels: OK to merge, Ready For Review

#8431 Increase Validation Queue
  beacon-chain/p2p/service.go
Labels: Networking, OK to merge, Priority: High, Ready For Review

#8432 Validator: add a DEBUG log to show batch attestation save duration
  validator/db/kv/attester_protection.go
Labels: OK to merge

#8435 Add Mutex and Block Profiling
  beacon-chain/main.go
  beacon-chain/usage.go
  shared/debug/debug.go
  validator/main.go
  validator/usage.go
Labels: OK to merge, Priority: Critical, Ready For Review

#8402 Implement GetStateRoot in the beacon API
  beacon-chain/powchain/testing/mock_powchain.go
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/server.go
  beacon-chain/rpc/beaconv1/state.go
  beacon-chain/rpc/beaconv1/state_test.go
  beacon-chain/rpc/service.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/mock.go
  beacon-chain/state/stategen/service.go
  shared/bytesutil/BUILD.bazel
  shared/bytesutil/bytes.go
  shared/bytesutil/bytes_test.go
Labels: API, OK to merge, Ready For Review

#8438 On Block Cleanup
  beacon-chain/blockchain/process_block.go
Labels: Cleanup, OK to merge

#8437 Beacon API: update GetStateRoot
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/state.go
  beacon-chain/rpc/beaconv1/state_test.go
Labels: OK to merge

#8436 Process attestation: skip if forkchoice attestation count == 0
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/operations/attestations/kv/forkchoice.go
  beacon-chain/operations/attestations/kv/forkchoice_test.go
  beacon-chain/operations/attestations/pool.go
Labels: OK to merge, Ready For Review

#8440 Revert "Rename `NewService` to `New` (#8337)"
  beacon-chain/blockchain/info_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/interop-cold-start/service.go
  beacon-chain/node/node.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/operations/attestations/prune_expired_test.go
  beacon-chain/operations/attestations/service.go
  beacon-chain/operations/attestations/service_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/peers/scorers/service.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/pubsub_filter_test.go
  beacon-chain/p2p/pubsub_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/service.go
  fuzz/block_fuzz.go
  fuzz/rpc_status_fuzz.go
  shared/prometheus/logrus_collector_test.go
  shared/prometheus/service.go
  shared/prometheus/service_test.go
  slasher/beaconclient/service.go
  slasher/detection/service.go
  slasher/node/node.go
  slasher/rpc/server_test.go
  slasher/rpc/service.go
  slasher/rpc/service_test.go
  validator/node/node.go
  validator/slashing-protection/slasher_client.go
Labels: Cleanup, OK to merge, Ready For Review

#8434 Validator: Make read operation use db.view instead of db.update
  validator/db/kv/proposer_protection.go
Labels: OK to merge, Ready For Review

#8433 Validator: Safer pending attestation records flushing
  validator/db/kv/BUILD.bazel
  validator/db/kv/attester_protection.go
  validator/db/kv/attester_protection_test.go
  validator/db/kv/db.go
Labels: OK to merge, Ready For Review

#8442 Methods For StartEpoch and Slashing Helper Types for Optimized Slasher
  beacon-chain/slasher/chunks.go
  beacon-chain/slasher/chunks_test.go
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/helpers.go
  beacon-chain/slasher/helpers_test.go
  beacon-chain/slasher/params.go
  beacon-chain/slasher/params_test.go
  beacon-chain/slasher/types/BUILD.bazel
  beacon-chain/slasher/types/types.go
Labels: Ready For Review

#8445 Code inspect - clean ups
  beacon-chain/rpc/validator/assignments.go
  shared/hashutil/hash.go
  slasher/beaconclient/receivers.go
  tools/analyzers/comparesame/analyzer.go
  tools/analyzers/cryptorand/analyzer.go
  tools/analyzers/errcheck/analyzer.go
  tools/analyzers/featureconfig/analyzer.go
  tools/analyzers/maligned/analyzer.go
  tools/analyzers/nop/analyzer.go
  tools/analyzers/properpermissions/analyzer.go
  tools/analyzers/shadowpredecl/analyzer.go
  tools/analyzers/slicedirect/analyzer.go
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_exit.go
  validator/client/aggregate.go
  validator/client/propose.go
Labels: Cleanup, Ready For Review

#8439 Fix error formatting inside fmt.Errorf
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  validator/accounts/wallet_create.go
  validator/slashing-protection/local/standard-protection-format/import.go
Labels: Cleanup, OK to merge, Ready For Review

#8443 Use latest block header + slot as skip slot cache key
  beacon-chain/core/state/skip_slot_cache.go
Labels: OK to merge, Ready For Review

#8447 Verify nil block helper
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attester_slashing.go
  beacon-chain/core/blocks/deposit.go
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/blocks/proposer_slashing.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/helpers/block.go
  beacon-chain/core/state/transition.go
  beacon-chain/db/kv/state.go
  beacon-chain/rpc/beacon/blocks.go
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/state.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
Labels: OK to merge

#8444 Ensure Default Wallet Password Permissions Are Consistent
  shared/fileutil/fileutil.go
  shared/fileutil/fileutil_test.go
  validator/node/node.go
Labels: Ready For Review, Security

#8448 Configurable DB Mmap Size for Beacon Node and Validator Client
  beacon-chain/db/db.go
  beacon-chain/db/db_kafka_wrapped.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/backup_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/kv_test.go
  beacon-chain/db/restore_test.go
  beacon-chain/db/testing/setup_db.go
  beacon-chain/main.go
  beacon-chain/node/node.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/usage.go
  fuzz/BUILD.bazel
  fuzz/block_fuzz.go
  shared/cmd/flags.go
  tools/blocktree/BUILD.bazel
  tools/blocktree/main.go
  tools/extractor/BUILD.bazel
  tools/extractor/main.go
  tools/interop/export-genesis/BUILD.bazel
  tools/interop/export-genesis/main.go
  validator/db/kv/attester_protection_test.go
  validator/db/kv/backup_test.go
  validator/db/kv/db.go
  validator/db/kv/db_test.go
  validator/db/kv/proposer_protection_test.go
  validator/db/migrate.go
  validator/db/restore_test.go
  validator/db/testing/setup_db.go
  validator/db/testing/setup_db_test.go
  validator/main.go
  validator/node/node.go
  validator/slashing-protection/cli_export.go
  validator/slashing-protection/cli_import.go
  validator/usage.go
Labels: OK to merge, Priority: Critical, Ready For Review

#8429 Mask credentials for logging
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/service.go
  shared/logutil/BUILD.bazel
  shared/logutil/logutil.go
  shared/logutil/logutil_test.go
Labels: OK to merge, Ready For Review

#8449 Remove unused core functions
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/blocks/exit_test.go
Labels: OK to merge, Ready For Review

#8452 Validator: Choose a reasonable cap for the attested target epochs slice
  validator/db/kv/attester_protection.go
Labels: OK to merge, Ready For Review

#8451 Validator: Annotate attestation error spans
  validator/client/attest.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/attester_protection.go
Labels: OK to merge, Ready For Review

#8454 Remove Outdated Chainservice Method
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
Labels: Cleanup, Ready For Review

#8455 Deprecate Uneeded Flags
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/cache/cache_test.go
  beacon-chain/rpc/validator/BUILD.bazel
  beacon-chain/rpc/validator/proposer.go
  beacon-chain/rpc/validator/proposer_test.go
  shared/featureconfig/config.go
  shared/featureconfig/deprecated_flags.go
  shared/featureconfig/flags.go
Labels: Cleanup, OK to merge, Ready For Review

#8457 Better feature flag logging
  shared/featureconfig/config.go
Labels: OK to merge, Ready For Review

#8462 Clean Up Go Sum
  go.sum
Labels: OK to merge, Ready For Review

#8456 Implement GetStateFork in the beacon API
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/state.go
  beacon-chain/rpc/beaconv1/state_test.go
Labels: API, Ready For Review

#8467 Ignore Analyzers Package in DeepSource Config
  .deepsource.toml
Labels: OK to merge, Ready For Review

#8465 Reform Inbound Limit
  beacon-chain/p2p/connection_gater.go
  beacon-chain/p2p/connection_gater_test.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/peers/status.go
Labels: Networking, OK to merge, Ready For Review

#8450 Begin Receiving and Processing Blocks for Optimized Slasher
  beacon-chain/slasher/receive.go
  beacon-chain/slasher/receive_test.go
  beacon-chain/slasher/service.go
  beacon-chain/slasher/types/types.go
Labels: Ready For Review

#8460 Stop Early in Validator Surround Vote Local Protection
  validator/db/kv/BUILD.bazel
  validator/db/kv/attester_protection.go
  validator/db/kv/db.go
  validator/db/kv/migration.go
  validator/db/kv/migration_source_target_epochs_bucket.go
  validator/db/kv/migration_source_target_epochs_bucket_test.go
  validator/db/kv/prune_attester_protection.go
  validator/db/kv/schema.go
  validator/db/migrate.go
Labels: OK to merge, Priority: High, Ready For Review

#8471 Use Correct Peer Status Method
  beacon-chain/p2p/discovery.go
Labels: OK to merge, Ready For Review

#8476 Implement GetFinalityCheckpoints in the beacon API
  beacon-chain/rpc/beaconv1/state.go
  beacon-chain/rpc/beaconv1/state_test.go
Labels: API, Ready For Review

#8472 Reformat healthz message by adding a comma
  shared/prometheus/service.go
  shared/prometheus/service_test.go
Labels: OK to merge, Ready For Review

#8330 Hide beacon operation field in log if it's 0
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/log_test.go
Labels: OK to merge, Ready For Review

#8477 Use Eth2 type CommitteeIndex
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_disabled.go
  beacon-chain/cache/committee_test.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/committee.go
  beacon-chain/core/helpers/committee_test.go
  beacon-chain/core/state/transition_test.go
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/operations/attestations/pool.go
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/committees.go
  beacon-chain/rpc/beaconv1/blocks_test.go
  beacon-chain/rpc/validator/attester.go
  beacon-chain/rpc/validator/proposer_test.go
  beacon-chain/state/stateutil/attestations.go
  beacon-chain/sync/validate_beacon_attestation.go
  deps.bzl
  endtoend/evaluators/slashing.go
  go.mod
  go.sum
  shared/testutil/attestation.go
  shared/testutil/block.go
  validator/client/validator.go
Labels: OK to merge, Ready For Review

#8479 Constrain read/write channels
  beacon-chain/blockchain/receive_attestation.go
  validator/client/mock_validator.go
  validator/client/runner.go
  validator/client/validator.go
  validator/client/wait_for_activation.go
Labels: Cleanup, OK to merge, Ready For Review

#8446 Detect Slashable Surround Votes in Optimized Slasher
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/slasher.go
  beacon-chain/db/kv/slasher_test.go
  beacon-chain/slasher/chunks.go
  beacon-chain/slasher/chunks_test.go
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/detect_attestations_test.go
  beacon-chain/slasher/helpers_test.go
  beacon-chain/slasher/receive.go
  beacon-chain/slasher/receive_test.go
  beacon-chain/slasher/types/types.go
Labels: Ready For Review

#8490 Update Geth Fork
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review

#8493 Add nil check for validator db migration
  validator/db/kv/migration_source_target_epochs_bucket.go
Labels: OK to merge

#8487 Remove mutated fields from slasher args
  beacon-chain/slasher/chunks.go
  beacon-chain/slasher/chunks_test.go
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/detect_attestations_test.go
Labels: Ready For Review

#8484 Use DeepSSZEqual for tests
  beacon-chain/rpc/beacon/attestations_test.go
  beacon-chain/rpc/beacon/blocks_test.go
  shared/sszutil/deep_equal.go
Labels: OK to merge, Ready For Review

#8470 Double Block Slashing Detection for Optimized Slasher
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/slasher.go
  beacon-chain/db/kv/slasher_test.go
  beacon-chain/slasher/BUILD.bazel
  beacon-chain/slasher/detect_blocks.go
  beacon-chain/slasher/detect_blocks_test.go
  beacon-chain/slasher/helpers.go
  beacon-chain/slasher/helpers_test.go
  beacon-chain/slasher/receive.go
  beacon-chain/slasher/receive_test.go
  beacon-chain/slasher/types/types.go
Labels: Ready For Review

#8491 Move timings of synced block to debug level
  beacon-chain/blockchain/log.go
Labels: OK to merge, Ready For Review

#8480 Attester Double Vote Detection for Optimized Slasher
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kafka/passthrough.go
  beacon-chain/db/kv/slasher.go
  beacon-chain/db/kv/slasher_test.go
  beacon-chain/slasher/BUILD.bazel
  beacon-chain/slasher/chunks_test.go
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/detect_attestations_test.go
  beacon-chain/slasher/detect_blocks.go
  beacon-chain/slasher/helpers.go
  beacon-chain/slasher/receive.go
  beacon-chain/slasher/types/types.go
Labels: Ready For Review

#8494 Fix duplicate import
  beacon-chain/p2p/connection_gater_test.go
Labels: Cleanup, OK to merge, Ready For Review

#8489 Clean duplicated topic field in debug log
  beacon-chain/sync/subscriber.go
Labels: OK to merge, Ready For Review

#8496 ETH2 API: Add outline for debug endpoints
  beacon-chain/rpc/debugv1/BUILD.bazel
  beacon-chain/rpc/debugv1/debug.go
  beacon-chain/rpc/debugv1/server.go
Labels: Ready For Review

#8344 Require Web UI Password Only for POST Requests or Sensitive Information
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/rpc/auth.go
  validator/rpc/auth_test.go
  validator/rpc/intercepter.go
  validator/rpc/intercepter_test.go
  validator/rpc/server.go
  validator/rpc/wallet_test.go
Labels: Ready For Review, Web UI

#8498 Use `validatorIndex` instead of `validatorID`
  beacon-chain/core/helpers/committee.go
  beacon-chain/rpc/validator/status.go
  beacon-chain/state/setters.go
  slasher/beaconclient/validator_retrieval.go
  slasher/cache/validators_cache.go
  slasher/db/iface/interface.go
  slasher/db/kv/block_header.go
  slasher/db/kv/block_header_test.go
  slasher/db/kv/schema.go
  slasher/db/kv/spanner_new_test.go
  slasher/db/kv/validator_id_pubkey.go
  slasher/db/kv/validator_id_pubkey_test.go
Labels: Cleanup, Ready For Review

#8492 Implement ListPoolAttesterSlashings in the beacon API
  beacon-chain/blockchain/service.go
  beacon-chain/node/node.go
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/mock.go
  beacon-chain/operations/slashings/types.go
  beacon-chain/rpc/beacon/server.go
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/pool.go
  beacon-chain/rpc/beaconv1/pool_test.go
  beacon-chain/rpc/beaconv1/server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/sync/service.go
  proto/migration/migration.go
Labels: API, Ready For Review

#8507 Add In ValidateKeystores Validator Endpoint
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2/web_api.proto
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  tools/keystores/main.go
  validator/accounts/accounts_list.go
  validator/keymanager/imported/import.go
  validator/keymanager/imported/keymanager.go
  validator/keymanager/types.go
  validator/rpc/BUILD.bazel
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: OK to merge, Ready For Review

#8505 Better Handling of Subscriber Errors in Logs Streams
  beacon-chain/rpc/node/server.go
  beacon-chain/rpc/service.go
  validator/rpc/health.go
Labels: Priority: Critical, Ready For Review

#8499 Use DeepSSZEqual to satisfy go tests
  beacon-chain/db/kv/state_test.go
  beacon-chain/db/restore_test.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/rpc/beacon/blocks_test.go
  beacon-chain/rpc/beacon/validators_test.go
  beacon-chain/rpc/validator/aggregator_test.go
  beacon-chain/state/stategen/epoch_boundary_state_cache_test.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/replay_test.go
  beacon-chain/state/stategen/service_test.go
  beacon-chain/state/types_test.go
Labels: OK to merge, Ready For Review

#8506 Remove outdated and skipped TestConsistentGenesisState
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/log_processing_test.go
Labels: Cleanup, OK to merge, Ready For Review

#8510 Fix slice out of bounds error in validator db migration
  validator/db/kv/migration_source_target_epochs_bucket.go
  validator/db/kv/migration_source_target_epochs_bucket_test.go
Labels: OK to merge, Ready For Review

#8508 Implement ListPoolProposerSlashings and ListPoolVoluntaryExits in the beacon API
  beacon-chain/blockchain/service.go
  beacon-chain/node/node.go
  beacon-chain/operations/slashings/mock.go
  beacon-chain/operations/voluntaryexits/BUILD.bazel
  beacon-chain/operations/voluntaryexits/mock.go
  beacon-chain/operations/voluntaryexits/service.go
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/pool.go
  beacon-chain/rpc/beaconv1/pool_test.go
  beacon-chain/rpc/beaconv1/server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/validator/server.go
  beacon-chain/sync/service.go
  proto/migration/migration.go
Labels: OK to merge, Ready For Review

#8511 Analyze Secret Credential Additions in DeepSource
  .deepsource.toml
Labels: OK to merge, Ready For Review

#8512 Propagate Cancellation To Beacon Node Server
  validator/rpc/health.go
Labels: OK to merge, Ready For Review

#8503 Listen for account changes only when required
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_backup_test.go
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_delete_test.go
  validator/accounts/accounts_enable_disable.go
  validator/accounts/accounts_enable_disable_test.go
  validator/accounts/accounts_exit.go
  validator/accounts/accounts_import.go
  validator/accounts/accounts_import_test.go
  validator/accounts/accounts_list.go
  validator/accounts/accounts_list_test.go
  validator/accounts/iface/wallet.go
  validator/accounts/testing/BUILD.bazel
  validator/accounts/testing/mock.go
  validator/accounts/wallet/BUILD.bazel
  validator/accounts/wallet/wallet.go
  validator/accounts/wallet_create.go
  validator/accounts/wallet_recover.go
  validator/accounts/wallet_recover_test.go
  validator/client/BUILD.bazel
  validator/client/propose_test.go
  validator/client/service.go
  validator/client/validator.go
  validator/client/wait_for_activation_test.go
  validator/keymanager/derived/keymanager.go
  validator/keymanager/derived/keymanager_test.go
  validator/keymanager/imported/keymanager.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/accounts_test.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: Accounts, OK to merge, Ready For Review

#8501 Add Better Peer Pruning
  beacon-chain/cache/subnet_ids.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_test.go
Labels: Networking, OK to merge, Ready For Review

#8485 Log block arrival time
  beacon-chain/sync/validate_beacon_blocks.go
Labels: OK to merge, Ready For Review

#8482 Graffiti ordered index
  validator/client/propose.go
  validator/client/propose_test.go
  validator/client/service.go
  validator/client/validator.go
  validator/db/iface/interface.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/db.go
  validator/db/kv/graffiti.go
  validator/db/kv/graffiti_test.go
  validator/db/kv/schema.go
  validator/graffiti/BUILD.bazel
  validator/graffiti/parse_graffiti.go
  validator/graffiti/parse_graffiti_test.go
Labels: OK to merge, Ready For Review

#8515 Implement SubmitAttesterSlashing in the beacon API
  beacon-chain/operations/slashings/mock.go
  beacon-chain/rpc/beaconv1/BUILD.bazel
  beacon-chain/rpc/beaconv1/pool.go
  beacon-chain/rpc/beaconv1/pool_test.go
  proto/migration/migration.go
Labels: API, Ready For Review

#8517 Remove unused code
  go.mod
  go.sum
  shared/browser/BUILD.bazel
  shared/browser/browser.go
  shared/bytesutil/bytes.go
  shared/keystore/key.go
  validator/client/propose_test.go
  validator/rpc/health_test.go
Labels: Cleanup, OK to merge, Ready For Review

#8519 RPC: Proper status code for error
  beacon-chain/rpc/beacon/slashings.go
  beacon-chain/rpc/beaconv1/pool.go
Labels: OK to merge, Ready For Review

#8522 HF1: Add penalty config values
  beacon-chain/rpc/beaconv1/config_test.go
  shared/params/config.go
  shared/params/loader_test.go
  shared/params/mainnet_config.go
  shared/params/minimal_config.go
Labels: Ready For Review

#8521 Update to go 1.16
  WORKSPACE
  beacon-chain/core/state/stateutils/BUILD.bazel
  beacon-chain/p2p/peers/peerdata/BUILD.bazel
  beacon-chain/p2p/peers/scorers/BUILD.bazel
  contracts/deposit-contract/BUILD.bazel
  deps.bzl
  go.mod
  go.sum
  shared/attestationutil/BUILD.bazel
  shared/bytesutil/BUILD.bazel
  shared/depositutil/BUILD.bazel
  shared/fileutil/BUILD.bazel
  shared/hashutil/BUILD.bazel
  shared/htrutils/BUILD.bazel
  shared/interop/BUILD.bazel
  shared/iputils/BUILD.bazel
  shared/mathutil/BUILD.bazel
  shared/messagehandler/BUILD.bazel
  shared/pagination/BUILD.bazel
  shared/runutil/BUILD.bazel
  shared/sliceutil/BUILD.bazel
  shared/sszutil/BUILD.bazel
  shared/testutil/assertions/BUILD.bazel
  slasher/detection/attestations/types/BUILD.bazel
  validator/accounts/wallet/BUILD.bazel
  validator/keymanager/BUILD.bazel
Labels: OK to merge, Ready For Review

#8523 Update Test Case in Batching Public Keys
  validator/db/kv/migration_source_target_epochs_bucket_test.go
Labels: OK to merge, Ready For Review

#8525 Fix Default Transport Option
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/options.go
  go.mod
Labels: Ready For Review

#8520 Add --list-validator-indices flag
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_list.go
  validator/accounts/accounts_list_test.go
  validator/accounts/cmd_accounts.go
  validator/flags/flags.go
Labels: OK to merge, Ready For Review

#8528 Ran go import
  endtoend/evaluators/slashing.go
  proto/beacon/db/finalized_block_root_container.pb.go
  proto/beacon/db/powchain.pb.go
  proto/beacon/p2p/v1/messages.pb.go
  proto/beacon/p2p/v1/types.pb.go
  proto/beacon/rpc/v1/debug.pb.go
  proto/beacon/rpc/v1/health.pb.go
  proto/beacon/rpc/v1_gateway/debug.pb.go
  proto/beacon/rpc/v1_gateway/debug.pb.gw.go
  proto/beacon/rpc/v1_gateway/health.pb.go
  proto/validator/accounts/v2/keymanager.pb.go
  proto/validator/accounts/v2/web_api.pb.go
  proto/validator/accounts/v2_gateway/keymanager.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.go
  proto/validator/accounts/v2_gateway/web_api.pb.gw.go
  validator/accounts/accounts_list.go
  validator/accounts/accounts_list_test.go
Labels: Cleanup
