Repository OffchainLabs/prysm, pull requests merged in 2021-12, with the labels that each got.

#9943 Monitor aggregated logs
  beacon-chain/monitor/process_block.go
  beacon-chain/monitor/process_block_test.go
  beacon-chain/monitor/service_test.go
Labels: Ready For Review, OK to merge

#9957 Remove Balances Timeout
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
Labels: Ready For Review, OK to merge

#9964 Faster Doppelganger Check
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go
Labels: Ready For Review, OK to merge

#9956 Fix grpc client connected... logging
  beacon-chain/rpc/service.go
Labels: Ready For Review, OK to merge

#9965 fix operation precedence
  beacon-chain/monitor/process_block.go
Labels: OK to merge

#9966 Add v1alpha1_to_v2.go
  proto/migration/BUILD.bazel
  proto/migration/v1alpha1_to_v1.go
  proto/migration/v1alpha1_to_v1_test.go
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v1alpha1_to_v2_test.go
Labels: OK to merge

#9960 Update Libp2p to v0.15.1
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery.go
  deps.bzl
  go.mod
  go.sum
  third_party/libp2p_tls.patch
  validator/client/multiple_endpoints_grpc_resolver.go
Labels: Ready For Review, OK to merge

#9961 Cleanup From Deepsource
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/db/slasherkv/pruning.go
  beacon-chain/db/slasherkv/slasher.go
  beacon-chain/operations/slashings/mock.go
  beacon-chain/p2p/gossip_scoring_params_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/slasher/mock_slashing_checker.go
  beacon-chain/state/v1/unsupported_setters.go
  beacon-chain/state/v2/deprecated_setters.go
  beacon-chain/state/v3/deprecated_setters.go
  beacon-chain/state/v3/state_trie.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  tools/deployContract/deployContract.go
  validator/keymanager/imported/import.go
  validator/rpc/wallet.go
  validator/slashing-protection-history/import.go
  validator/testing/mock_slasher.go
Labels: Ready For Review, OK to merge

#9967 Update go-ethereum to v1.10.13
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review, OK to merge

#9959 Replace a Few IntFlags with Uint64Flags
  beacon-chain/node/node.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/connection_gater_test.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/peers/scorers/block_providers.go
  beacon-chain/p2p/peers/scorers/block_providers_test.go
  beacon-chain/p2p/peers/scorers/service_test.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_test.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/flags/config.go
  cmd/flags.go
Labels: Ready For Review, OK to merge

#9968 Filter Errored Keys from Returned Slashing Protection History in Standard API
  validator/rpc/standard_api.go
  validator/slashing-protection-history/export.go
Labels: Ready For Review, OK to merge

#9938 Ensure Slashing Protection Exports and Keymanager API Work According to Spec
  validator/accounts/accounts_import.go
  validator/accounts/accounts_list_test.go
  validator/keymanager/imported/delete.go
  validator/keymanager/imported/delete_test.go
  validator/keymanager/imported/import.go
  validator/keymanager/imported/import_test.go
  validator/keymanager/imported/keymanager_test.go
  validator/rpc/BUILD.bazel
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
  validator/slashing-protection-history/export.go
  validator/slashing-protection-history/round_trip_test.go
Labels: Ready For Review

#9977 stateutil: Reduce allocations by specifying slice capacity eager
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/validator_root.go
  beacon-chain/state/stateutil/validator_root_test.go
Labels: Enhancement, Ready For Review, OK to merge

#9978 Native merge beacon state
  beacon-chain/state/fieldtrie/field_trie.go
  beacon-chain/state/fieldtrie/field_trie_test.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stateutil/trie_helpers_test.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/field_roots.go
  beacon-chain/state/v1/state_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/field_roots.go
  beacon-chain/state/v2/getters_misc.go
  beacon-chain/state/v2/getters_validator.go
  beacon-chain/state/v2/setters_test.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/field_roots.go
  beacon-chain/state/v3/generated.ssz.go
  beacon-chain/state/v3/getters_block.go
  beacon-chain/state/v3/getters_block_test.go
  beacon-chain/state/v3/getters_checkpoint.go
  beacon-chain/state/v3/getters_eth1.go
  beacon-chain/state/v3/getters_misc.go
  beacon-chain/state/v3/getters_participation.go
  beacon-chain/state/v3/getters_payload_header.go
  beacon-chain/state/v3/getters_randao.go
  beacon-chain/state/v3/getters_state.go
  beacon-chain/state/v3/getters_sync_committee.go
  beacon-chain/state/v3/getters_test.go
  beacon-chain/state/v3/getters_validator.go
  beacon-chain/state/v3/setters_block.go
  beacon-chain/state/v3/setters_checkpoint.go
  beacon-chain/state/v3/setters_eth1.go
  beacon-chain/state/v3/setters_misc.go
  beacon-chain/state/v3/setters_participation.go
  beacon-chain/state/v3/setters_payload_header.go
  beacon-chain/state/v3/setters_randao.go
  beacon-chain/state/v3/setters_state.go
  beacon-chain/state/v3/setters_sync_committee.go
  beacon-chain/state/v3/setters_test.go
  beacon-chain/state/v3/setters_validator.go
  beacon-chain/state/v3/state_trie.go
  beacon-chain/state/v3/types.go
  nogo_config.json
  proto/migration/v1alpha1_to_v2.go
Labels: Ready For Review, OKR Item

#9979 typos
  beacon-chain/monitor/process_block.go
  beacon-chain/monitor/process_block_test.go
Labels: OK to merge

#9878 Add and use merge penalty params
  beacon-chain/core/blocks/attester_slashing.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/blocks/proposer_slashing.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/config.go
  config/params/mainnet_config.go
Labels: Ready For Review, OK to merge, Merge

#9983 Remove unused validator proto imports
  proto/eth/service/key_management.proto
Labels: Ready For Review

#9984 Create `toProtoNoLock` function
  beacon-chain/state/v1/field_roots.go
  beacon-chain/state/v1/getters_state.go
  beacon-chain/state/v2/field_roots.go
  beacon-chain/state/v2/getters_state.go
  beacon-chain/state/v3/field_roots.go
  beacon-chain/state/v3/getters_state.go
Labels: Ready For Review

#9985 Use Cached Finalized State When Pruning Deposits
  beacon-chain/powchain/log_processing.go
Labels: Ready For Review, OK to merge

#9988 Do not rely on peer order in `TestDebugServer_ListPeers`
  beacon-chain/rpc/prysm/v1alpha1/debug/p2p_test.go
Labels: Ready For Review, OK to merge

#9833 Slasher Significant Optimizations
  beacon-chain/db/iface/interface.go
  beacon-chain/db/slasherkv/pruning.go
  beacon-chain/db/slasherkv/slasher.go
  beacon-chain/db/slasherkv/slasher_test.go
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/detect_attestations_test.go
  beacon-chain/slasher/receive.go
  beacon-chain/slasher/receive_test.go
  beacon-chain/slasher/rpc.go
  beacon-chain/slasher/rpc_test.go
  beacon-chain/slasher/service.go
  beacon-chain/slasher/service_test.go
  beacon-chain/sync/BUILD.bazel
  testing/endtoend/slasher_simulator_e2e_test.go
  testing/slasher/simulator/BUILD.bazel
  testing/slasher/simulator/attestation_generator.go
  testing/slasher/simulator/simulator.go
Labels: Ready For Review, OK to merge, Cleanup

#9986 Add more merge related protobufs
  proto/eth/service/key_management.pb.go
  proto/eth/v2/beacon_block.pb.go
  proto/eth/v2/beacon_block.proto
  proto/eth/v2/version.pb.go
  proto/eth/v2/version.proto
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
Labels: Ready For Review, OK to merge, Merge

#9989 Display Num Pruned Items in Slasher Only When Actually Prunes
  beacon-chain/slasher/receive.go
Labels: Ready For Review, OK to merge

#9987 make db merge compatible
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/block_merge_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/key.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
  testing/util/BUILD.bazel
  testing/util/merge.go
Labels: Ready For Review, OK to merge, Merge

#9936 API Middleware for Keymanager Standard API Endpoints
  api/gateway/BUILD.bazel
  api/gateway/apimiddleware/api_middleware.go
  api/gateway/gateway.go
  api/gateway/gateway_test.go
  api/gateway/options.go
  beacon-chain/node/node.go
  beacon-chain/server/main.go
  proto/eth/service/BUILD.bazel
  proto/eth/service/key_management.pb.gw.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/apimiddleware/BUILD.bazel
  validator/rpc/apimiddleware/endpoint_factory.go
  validator/rpc/apimiddleware/structs.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
Labels: Ready For Review, OK to merge, API

#9993 Add Safe Sub64 Method
  math/math_helper.go
  math/math_helper_test.go
Labels: Ready For Review, OK to merge

#9982 Use merge configs for processing
  beacon-chain/blockchain/metrics.go
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/altair/epoch_precompute_test.go
  beacon-chain/core/altair/transition.go
  beacon-chain/core/altair/transition_test.go
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/config.go
  config/params/mainnet_config.go
Labels: Ready For Review, Merge

#9996 Add missing config cleanup in tests
  beacon-chain/rpc/prysm/v1alpha1/beacon/attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/committees_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/blocks_test.go
Labels: Ready For Review, OK to merge, Cleanup

#9991 Web3signer: Add an HTTP Client Wrapper to Interact with Remote Server
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/client.go
  validator/keymanager/remote-web3signer/client_test.go
  validator/keymanager/remote-web3signer/log.go
Labels: Enhancement, Ready For Review, API

#10005 Add Justifications for Gosec Ignored
  crypto/bls/blst/signature.go
  crypto/keystore/keystore.go
  crypto/rand/rand.go
  encoding/ssz/deep_equal.go
  runtime/prereqs/prereq.go
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/boot_node.go
  testing/endtoend/components/eth1.go
  testing/endtoend/components/validator.go
  testing/endtoend/helpers/helpers.go
  tools/specs-checker/download.go
  validator/accounts/wallet_recover.go
Labels: Ready For Review, Priority: Critical, OK to merge

#10004 Add More Fields to Remote Signer Sign Request
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
Labels: Ready For Review, OK to merge

#9998 Standardize config overriding in tests across repo
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/time/slot_epoch_test.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/db/slasherkv/pruning_test.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/blocks_test.go
  beacon-chain/state/v1/types_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10003 Add Missing spec tests in sss_static.go
  testing/spectest/shared/altair/ssz_static/ssz_static.go
  testing/spectest/shared/phase0/ssz_static/ssz_static.go
Labels: OK to merge

#10007 Use Static Sizes for State Fields
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/eth1_root.go
  beacon-chain/state/stateutil/field_root_attestation.go
  beacon-chain/state/stateutil/field_root_validator.go
  beacon-chain/state/stateutil/participation_bit_root.go
  beacon-chain/state/stateutil/state_hasher.go
  beacon-chain/state/stateutil/validator_root.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/setters_attestation.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/state_trie.go
  config/BUILD.bazel
  config/fieldparams/BUILD.bazel
  config/fieldparams/mainnet.go
  config/fieldparams/mainnet_test.go
  config/fieldparams/minimal.go
  config/fieldparams/minimal_test.go
  encoding/ssz/BUILD.bazel
  encoding/ssz/htrutils.go
  testing/util/block.go
  testing/util/block_test.go
Labels: Ready For Review

#10010 Use `fieldparams` in native beacon state
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/state.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/beacon/attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/beacon_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/committees_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/validator_test.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/custom-types/BUILD.bazel
  beacon-chain/state/custom-types/sizes_mainnet.go
  beacon-chain/state/custom-types/sizes_minimal.go
  beacon-chain/state/custom-types/state_arrays.go
  beacon-chain/state/custom-types/state_arrays_test.go
  beacon-chain/state/phase0.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/getters_block.go
  beacon-chain/state/v1/getters_block_test.go
  beacon-chain/state/v1/getters_randao.go
  beacon-chain/state/v1/getters_state.go
  beacon-chain/state/v1/setters_block.go
  beacon-chain/state/v1/setters_randao.go
  beacon-chain/state/v1/setters_state.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v1/types_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/getters_block.go
  beacon-chain/state/v2/getters_block_test.go
  beacon-chain/state/v2/getters_randao.go
  beacon-chain/state/v2/getters_state.go
  beacon-chain/state/v2/setters_block.go
  beacon-chain/state/v2/setters_randao.go
  beacon-chain/state/v2/setters_state.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/getters_block.go
  beacon-chain/state/v3/getters_block_test.go
  beacon-chain/state/v3/getters_randao.go
  beacon-chain/state/v3/getters_state.go
  beacon-chain/state/v3/setters_block.go
  beacon-chain/state/v3/setters_randao.go
  beacon-chain/state/v3/setters_state.go
  beacon-chain/state/v3/state_trie.go
  deps.bzl
  go.mod
  go.sum
  proto/migration/BUILD.bazel
  proto/migration/v1alpha1_to_v1_test.go
  testing/util/BUILD.bazel
  testing/util/altair.go
  testing/util/block_test.go
  testing/util/state.go
Labels: Ready For Review, OKR Item

#10000 Add more merge processing (non substrantive)
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/sync_committee_head_state.go
  beacon-chain/cache/sync_committee_head_state_test.go
  beacon-chain/core/altair/epoch_precompute_test.go
  beacon-chain/core/altair/transition_test.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/db/kv/state.go
  testing/util/merge_state.go
Labels: Ready For Review, OK to merge, Merge

#9981 Add beacon state upgrade to merge version helper function
  beacon-chain/core/execution/BUILD.bazel
  beacon-chain/core/execution/upgrade.go
  beacon-chain/core/execution/upgrade_test.go
  beacon-chain/state/phase0.go
Labels: Ready For Review, Merge

#10012 Use field params root length
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/attestation_test.go
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
  beacon-chain/core/epoch/precompute/reward_penalty_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/transition_test.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/finalized_block_roots_test.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/fork_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/beacon/attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/committees_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/state_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/getters_block_test.go
  beacon-chain/state/v2/getters_misc.go
  beacon-chain/state/v2/setters_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
  proto/migration/BUILD.bazel
  proto/migration/v1alpha1_to_v1_test.go
  testing/util/BUILD.bazel
  testing/util/altair.go
  testing/util/attestation.go
  testing/util/attestation_test.go
  testing/util/block.go
  testing/util/helpers_test.go
  testing/util/state.go
  testing/util/sync_committee.go
  validator/client/BUILD.bazel
  validator/client/attest_test.go
  validator/client/sync_committee_test.go
  validator/client/validator.go
  validator/db/kv/BUILD.bazel
  validator/db/kv/deprecated_attester_protection.go
  validator/db/kv/proposer_protection.go
Labels: Ready For Review, OK to merge

#10019 Use signature length from `fieldparams`
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/sync_committee.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/deposit_test.go
  beacon-chain/core/blocks/genesis.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/prune_expired_test.go
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/service_proposer_test.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/deposit_test.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/debug/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/debug/block_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/exit.go
  beacon-chain/slasher/BUILD.bazel
  beacon-chain/slasher/helpers.go
  beacon-chain/slasher/helpers_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_blocks_test.go
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
  config/params/config.go
  config/params/mainnet_config.go
  crypto/bls/blst/BUILD.bazel
  crypto/bls/blst/signature.go
  proto/prysm/v1alpha1/attestation/BUILD.bazel
  proto/prysm/v1alpha1/attestation/attestation_utils_test.go
  proto/prysm/v1alpha1/block/BUILD.bazel
  proto/prysm/v1alpha1/block/block_utils_test.go
  proto/testing/BUILD.bazel
  proto/testing/tags_test.go
  testing/endtoend/evaluators/BUILD.bazel
  testing/endtoend/evaluators/slashing.go
  testing/util/attestation_test.go
  testing/util/block.go
  validator/client/slashing_protection_interchange_test.go
  validator/client/validator_test.go
Labels: Ready For Review

#10013 Minor cleanups on monitor service
  beacon-chain/monitor/process_attestation.go
  beacon-chain/monitor/process_attestation_test.go
  beacon-chain/monitor/process_block.go
  beacon-chain/monitor/process_block_test.go
  beacon-chain/monitor/process_exit.go
  beacon-chain/monitor/process_sync_committee.go
  beacon-chain/monitor/process_sync_committee_test.go
  beacon-chain/monitor/service.go
  beacon-chain/monitor/service_test.go
Labels: Ready For Review, OK to merge

#10022 Fix state alias v3
  beacon-chain/core/execution/upgrade.go
Labels: Ready For Review, OK to merge

#10029 Merkle Proof Support for BeaconState Finalized Root and Sync Committees
  beacon-chain/core/blocks/deposit.go
  beacon-chain/state/fieldtrie/field_trie_helpers.go
  beacon-chain/state/phase0.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/proofs.go
  beacon-chain/state/v1/proofs_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/proofs.go
  beacon-chain/state/v2/proofs_test.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/proofs.go
  beacon-chain/state/v3/proofs_test.go
  container/trie/sparse_merkle.go
  container/trie/sparse_merkle_test.go
Labels: Ready For Review

#10026 Add is_merge_block helper
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
  beacon-chain/state/phase0.go
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
Labels: Ready For Review, OK to merge, Merge

#10027 Add is_execution_enabled helper
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
Labels: Ready For Review, Merge

#10033 Update spec test to v1.1.7
  WORKSPACE
  config/params/loader_test.go
Labels: Ready For Review, OK to merge

#10041 Spectest 1.1.8
  WORKSPACE
  beacon-chain/core/execution/upgrade.go
  beacon-chain/core/execution/upgrade_test.go
  beacon-chain/core/time/slot_epoch.go
  beacon-chain/core/time/slot_epoch_test.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/config.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  config/params/testnet_prater_config.go
  config/params/testnet_pyrmont_config.go
Labels: Ready For Review, OK to merge

#10045 Update bazel version to 4.2.2
  .bazelversion
Labels: Ready For Review, OK to merge
