Repository OffchainLabs/prysm, pull requests merged in 2022-12, with the labels that each got.

#11713 Handle BLS to execution changes included in blocks
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/node/node.go
Labels: Ready For Review

#11716 Add State Check For BLS Execution Change Messages
  beacon-chain/sync/validate_bls_to_execution_change.go
  beacon-chain/sync/validate_bls_to_execution_change_test.go
Labels: Ready For Review, OK to merge

#11710 Add payload attribute type
  consensus-types/blocks/getters.go
  consensus-types/blocks/types.go
  consensus-types/payload-attribute/BUILD.bazel
  consensus-types/payload-attribute/getters.go
  consensus-types/payload-attribute/getters_test.go
  consensus-types/payload-attribute/interface.go
  consensus-types/payload-attribute/types.go
Labels: Ready For Review, OK to merge

#11711 Add REST implementation for Validator's `DomainData`
  hack/update-mockgen.sh
  testing/mock/validator_client_mock.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/domain_data.go
  validator/client/beacon-api/domain_data_test.go
  validator/client/beacon-api/genesis.go
  validator/client/beacon-api/genesis_test.go
  validator/client/beacon-api/handlers_test.go
  validator/client/beacon-api/mock/BUILD.bazel
  validator/client/beacon-api/mock/genesis_mock.go
Labels: OK to merge

#11708 Update state Beacon APIs to Capella
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/core/capella/upgrade_test.go
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/debug/debug.go
  beacon-chain/rpc/eth/debug/debug_test.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/getters_withdrawal.go
  beacon-chain/state/state-native/getters_withdrawal_test.go
  beacon-chain/state/state-native/types/types.go
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v1alpha1_to_v2_test.go
Labels: Ready For Review, OK to merge, API

#11712 Add REST implementation for Validator's `ValidatorIndex`
  hack/update-mockgen.sh
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/attestation_data.go
  validator/client/beacon-api/attestation_data_test.go
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/genesis.go
  validator/client/beacon-api/genesis_test.go
  validator/client/beacon-api/handlers_test.go
  validator/client/beacon-api/index.go
  validator/client/beacon-api/index_test.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/json_rest_handler_test.go
  validator/client/beacon-api/mock/BUILD.bazel
  validator/client/beacon-api/mock/json_rest_handler_mock.go
  validator/client/beacon-api/state_validators.go
  validator/client/beacon-api/state_validators_test.go
  validator/client/beacon-api/wait_for_chain_start_test.go
Labels: OK to merge

#11306 E2E: beacon APIs Part 1
  .gitignore
  testing/endtoend/BUILD.bazel
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/components/lighthouse_validator.go
  testing/endtoend/components/validator.go
  testing/endtoend/deps.bzl
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/evaluators/beaconapi_evaluators/BUILD.bazel
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api_verify.go
  testing/endtoend/evaluators/beaconapi_evaluators/util.go
  testing/endtoend/evaluators/validator.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/types/types.go
Labels: OK to merge, Cleanup, E2E Tests

#11726 Fix DeepSource errors in the Validator's REST API
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/index_test.go
  validator/client/beacon-api/json_rest_handler_test.go
Labels: OK to merge

#11727 Update go to 1.19.4
  WORKSPACE
Labels: OK to merge

#11730 Fix Lint and Minor Bugs in E2E
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/components/validator.go
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/evaluators/validator.go
  testing/endtoend/mainnet_scenario_e2e_test.go
Labels: Ready For Review, OK to merge

#11733 Fix to Post Submit E2E
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/types/types.go
Labels: Bug, E2E Tests

#11738 Add Back Cross Client Option
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/types/types.go
Labels: Ready For Review, E2E Tests

#11734 e2e: Print process IDs for debugging.
  testing/endtoend/component_handler_test.go
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/eth1/depositor.go
  testing/endtoend/components/eth1/node.go
  testing/endtoend/components/lighthouse_validator.go
  testing/endtoend/components/tracing_sink.go
  testing/endtoend/components/validator.go
  testing/endtoend/components/web3remotesigner.go
  testing/endtoend/endtoend_test.go
  testing/endtoend/types/types.go
Labels: OK to merge

#11704 Onboard validator's Beacon REST API usage to e2e tests
  .bazelrc
  cmd/validator/flags/BUILD.bazel
  cmd/validator/flags/beacon_api_flags.go
  cmd/validator/flags/grpc_flags.go
  cmd/validator/main.go
  cmd/validator/usage.go
  config/features/config.go
  config/features/flags.go
  hack/update-mockgen.sh
  testing/endtoend/BUILD.bazel
  testing/endtoend/components/validator.go
  testing/endtoend/minimal_scenario_e2e_test.go
  testing/endtoend/types/types.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/activation.go
  validator/client/beacon-api/activation_test.go
  validator/client/beacon-api/attestation_data.go
  validator/client/beacon-api/attestation_data_test.go
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/domain_data.go
  validator/client/beacon-api/domain_data_test.go
  validator/client/beacon-api/genesis.go
  validator/client/beacon-api/genesis_test.go
  validator/client/beacon-api/index.go
  validator/client/beacon-api/index_test.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/json_rest_handler_test.go
  validator/client/beacon-api/state_validators.go
  validator/client/beacon-api/state_validators_test.go
  validator/client/beacon-api/wait_for_chain_start_test.go
  validator/client/grpc-api/grpc_validator_client_test.go
  validator/client/validator-client-factory/BUILD.bazel
  validator/client/validator-client-factory/grpc_validator_client_factory.go
  validator/client/validator-client-factory/validator_client_factory.go
Labels: OK to merge

#11745 beacondb: Remove cache look up and lock request from boltdb transaction for state summaries
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/state_summary.go
  beacon-chain/db/kv/validated_checkpoint.go
  beacon-chain/db/kv/validated_checkpoint_test.go
Labels: Ready For Review, OK to merge

#11736 remove warning for unsupported platform
  runtime/prereqs/prereq.go
Labels: UX

#11719 Use payload attribute type for engine-API
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/testing/BUILD.bazel
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, OK to merge, Withdrawals

#11718 Check BLS changes when requesting from pool
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/operations/blstoexec/BUILD.bazel
  beacon-chain/operations/blstoexec/pool.go
  beacon-chain/operations/blstoexec/pool_test.go
  beacon-chain/sync/validate_bls_to_execution_change.go
  crypto/bls/blst/BUILD.bazel
  crypto/bls/common/BUILD.bazel
  testing/spectest/shared/capella/operations/bls_to_execution_changes.go
Labels: Ready For Review, OK to merge, Withdrawals

#11739 Fix DeepSource errors in `proposer_bellatrix.go`
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
Labels: OK to merge

#11752 Remove `Test_IsExecutionEnabledCapella`
  beacon-chain/core/blocks/payload_test.go
Labels: OK to merge

#11731 Add REST implementation for Validator's `ProposeBeaconBlock`
  api/client/builder/types.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  encoding/bytesutil/bytes.go
  encoding/bytesutil/bytes_test.go
  proto/engine/v1/json_marshal_unmarshal.go
  runtime/interop/generate_keys.go
  testing/spectest/shared/common/forkchoice/service.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/beacon_block_json_helpers.go
  validator/client/beacon-api/beacon_block_json_helpers_test.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/json_rest_handler_test.go
  validator/client/beacon-api/mock/json_rest_handler_mock.go
  validator/client/beacon-api/propose_beacon_block.go
  validator/client/beacon-api/propose_beacon_block_altair_test.go
  validator/client/beacon-api/propose_beacon_block_bellatrix_test.go
  validator/client/beacon-api/propose_beacon_block_blinded_bellatrix_test.go
  validator/client/beacon-api/propose_beacon_block_blinded_capella_test.go
  validator/client/beacon-api/propose_beacon_block_phase0_test.go
  validator/client/beacon-api/propose_beacon_block_test.go
  validator/client/beacon-api/test-helpers/BUILD.bazel
  validator/client/beacon-api/test-helpers/test_helpers.go
Labels: OK to merge

#11755 fix validator client
  beacon-chain/rpc/apimiddleware/structs.go
  validator/client/beacon-api/beacon_block_json_helpers.go
  validator/client/beacon-api/beacon_block_json_helpers_test.go
Labels: OK to merge

#11749 API `finalized` metadata field - update protos
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  proto/eth/v2/beacon_block.pb.go
  proto/eth/v2/beacon_block.proto
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/eth/v2/ssz.pb.go
  proto/eth/v2/ssz.proto
  proto/eth/v2/sync_committee.pb.go
  proto/eth/v2/sync_committee.proto
Labels: Ready For Review, OK to merge, API

#11751 Add block setters for consensus type
  consensus-types/blocks/BUILD.bazel
  consensus-types/blocks/execution.go
  consensus-types/blocks/execution_test.go
  consensus-types/blocks/factory.go
  consensus-types/blocks/factory_test.go
  consensus-types/blocks/getters.go
  consensus-types/blocks/getters_test.go
  consensus-types/blocks/setters.go
  consensus-types/interfaces/beacon_block.go
  consensus-types/mock/block.go
  consensus-types/payload-attribute/getters_test.go
Labels: Ready For Review, OK to merge

#11735 Adding exit codes to cli commands
  cmd/beacon-chain/jwt/jwt.go
  cmd/beacon-chain/main.go
  cmd/prysmctl/checkpointsync/download.go
  cmd/prysmctl/db/query.go
  cmd/prysmctl/p2p/request_blocks.go
  cmd/prysmctl/testnet/generate_genesis.go
  cmd/prysmctl/weaksubjectivity/BUILD.bazel
  cmd/prysmctl/weaksubjectivity/checkpoint.go
  cmd/validator/main.go
Labels: Bug, OK to merge, UX

#11761 fix mismatch of code and comment
  beacon-chain/blockchain/chain_info_test.go
Labels: OK to merge

#11764 Do not remove attestations twice
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/receive_block.go
Labels: Ready For Review, Cleanup

#11763 state: Improve replay state logs metadata
  beacon-chain/state/stategen/replay.go
Labels: Ready For Review, OK to merge

#11768 Add --stamp to release builds
  .bazelrc
Labels: Ready For Review, OK to merge

#11742 Validator: Add trace span information for AttestationRecord save requests
  validator/db/kv/attester_protection.go
  validator/db/kv/db.go
  validator/keymanager/local/keymanager.go
Labels: Ready For Review, OK to merge

#11723 Correct duties calculation for old slots
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
Labels: Ready For Review, OK to merge, API

#11652 Fixed comments of the template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: OK to merge

#11759 Add capella cases for RPC calls
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
Labels: Ready For Review, OK to merge, API

#11757 Add REST implementation for `ValidatorStatus`
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/activation.go
  validator/client/beacon-api/activation_test.go
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/index.go
  validator/client/beacon-api/index_test.go
  validator/client/beacon-api/state_validators.go
  validator/client/beacon-api/state_validators_test.go
  validator/client/beacon-api/status.go
  validator/client/beacon-api/status_test.go
Labels: OK to merge

#11732 Reconstruct full Capella block
  beacon-chain/blockchain/pow_block.go
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  encoding/bytesutil/bytes.go
  encoding/bytesutil/bytes_test.go
  proto/engine/v1/BUILD.bazel
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
Labels: Ready For Review, OK to merge, Withdrawals

#11778 SparseMerkleTrie depth fix & regression tests
  container/trie/sparse_merkle.go
  container/trie/sparse_merkle_test.go
Labels: OK to merge

#11777 More user-friendly message in `ErrUndefinedExecutionEngineError`
  beacon-chain/blockchain/error.go
Labels: OK to merge, UX

#11772 Add REST implementation for Validator's `GetBeaconBlock`
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/structs.go
  encoding/bytesutil/bytes.go
  encoding/bytesutil/bytes_test.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_block_proto_helpers.go
  validator/client/beacon-api/beacon_block_proto_helpers_test.go
  validator/client/beacon-api/get_beacon_block.go
  validator/client/beacon-api/get_beacon_block_altair_test.go
  validator/client/beacon-api/get_beacon_block_bellatrix_test.go
  validator/client/beacon-api/get_beacon_block_phase0_test.go
  validator/client/beacon-api/get_beacon_block_test.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/propose_beacon_block_altair_test.go
  validator/client/beacon-api/propose_beacon_block_bellatrix_test.go
  validator/client/beacon-api/propose_beacon_block_phase0_test.go
  validator/client/beacon-api/test-helpers/BUILD.bazel
  validator/client/beacon-api/test-helpers/altair_beacon_block_test_helpers.go
  validator/client/beacon-api/test-helpers/bellatrix_beacon_block_test_helpers.go
  validator/client/beacon-api/test-helpers/phase0_beacon_block_test_helpers.go
  validator/client/beacon-api/test-helpers/test_helpers.go
  validator/keymanager/remote-web3signer/v1/web3signer_types.go
Labels: OK to merge

#11706 Update block Beacon APIs to Capella
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/blinded_blocks.go
  beacon-chain/rpc/eth/beacon/blinded_blocks_test.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/state/state-native/getters_withdrawal.go
  beacon-chain/state/state-native/getters_withdrawal_test.go
  beacon-chain/state/state-native/hasher_test.go
  consensus-types/blocks/execution_test.go
  consensus-types/blocks/proto_test.go
  consensus-types/payload-attribute/getters_test.go
  encoding/ssz/htrutils.go
  encoding/ssz/htrutils_test.go
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/generated.ssz.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
  proto/eth/v2/BUILD.bazel
  proto/eth/v2/beacon_block.pb.go
  proto/eth/v2/beacon_block.proto
  proto/eth/v2/generated.ssz.go
  proto/eth/v2/withdrawals.pb.go
  proto/eth/v2/withdrawals.proto
  proto/migration/v1alpha1_to_v2.go
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
  testing/util/block.go
  testing/util/merge.go
Labels: OK to merge, API, Withdrawals

#11783 Add `finalized` metadata field to API responses
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/eth/beacon/server.go
  beacon-chain/rpc/service.go
Labels: Ready For Review, OK to merge, API

#11775 Engine API: new/get_payload for Capella
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/testing/BUILD.bazel
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, OK to merge

#11760 Implement bound on expected withdrawals
  WORKSPACE
  beacon-chain/core/blocks/payload_test.go
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/rpc/eth/beacon/config_test.go
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/getters_withdrawal.go
  beacon-chain/state/state-native/getters_withdrawal_test.go
  config/params/config.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  testing/spectest/shared/altair/operations/block_header.go
  testing/spectest/shared/bellatrix/operations/block_header.go
  testing/spectest/shared/capella/operations/block_header.go
  testing/spectest/shared/phase0/operations/block_header.go
Labels: OK to merge, Withdrawals

#11787 Fix command to fetch latest stable version (#11782)
  hack/workspace_status.sh
Labels: OK to merge

#11788 Add `finalized` metadata field to API block fetching
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/blinded_blocks.go
  beacon-chain/rpc/eth/beacon/blinded_blocks_test.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
Labels: Ready For Review, API

#11789 Improve tests for `ProduceBlockV2`
  beacon-chain/rpc/eth/validator/validator_test.go
Labels: Ready For Review, OK to merge, API

#11795 Remove copy for block setters
  consensus-types/blocks/setters.go
Labels: Ready For Review, OK to merge

#11784 Add REST implementation for Validator's `PrepareBeaconProposer`
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/prepare_beacon_proposer.go
  validator/client/beacon-api/prepare_beacon_proposer_test.go
Labels: OK to merge

#11785 Add REST implementation for Validator's `ProposeExit`
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/propose_exit.go
  validator/client/beacon-api/propose_exit_test.go
Labels: OK to merge

#11796 Lock Finalization Cleanup
  beacon-chain/state/state-native/state_trie.go
Labels: Ready For Review

#11802 E2E from Phase0 or Bellatrix
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/state.go
  beacon-chain/execution/service.go
  beacon-chain/execution/testing/genesis.go
  cmd/config.go
  config/params/loader.go
  config/params/loader_test.go
  config/params/testdata/e2e_config.yaml
  config/params/testnet_config_test.go
  config/params/testnet_e2e_config.go
  runtime/interop/BUILD.bazel
  runtime/interop/premined_genesis_state.go
  runtime/tos/tos.go
  testing/endtoend/BUILD.bazel
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/components/validator.go
  testing/endtoend/components/web3remotesigner.go
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/evaluators/BUILD.bazel
  testing/endtoend/evaluators/fee_recipient.go
  testing/endtoend/evaluators/operations.go
  testing/endtoend/fork.go
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
  testing/endtoend/types/BUILD.bazel
  testing/endtoend/types/fork.go
  testing/endtoend/types/types.go
Labels: OK to merge

#11801 Implement `getPoolBLSToExecutionChanges` API endpoint
  beacon-chain/node/node.go
  beacon-chain/operations/blstoexec/mock/BUILD.bazel
  beacon-chain/operations/blstoexec/mock/mock.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/pool.go
  beacon-chain/rpc/eth/beacon/pool_test.go
  beacon-chain/rpc/eth/beacon/server.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v2/BUILD.bazel
  proto/eth/v2/beacon_chain.pb.go
  proto/eth/v2/beacon_chain.pb.gw.go
  proto/eth/v2/beacon_chain.proto
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v1alpha1_to_v2_test.go
Labels: Ready For Review, OK to merge, API

#11806 Query duties - epoch changes
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/testutil/mock_state_fetcher.go
Labels: Ready For Review, OK to merge, API

#11803 Fix Multiclient E2E
  beacon-chain/blockchain/chain_info.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/genesis.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/components/lighthouse_validator.go
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api_verify.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/params/params.go
Labels: Ready For Review, OK to merge, E2E Tests

#11809 Cleaner genesis state population
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/blocks/genesis.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/setters_attestation.go
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/genesis.go
  testing/spectypes/BUILD.bazel
  testing/util/BUILD.bazel
  testing/util/premine-state.go
Labels: OK to merge

#11762 Check BLS_TO_EXECUTION_CHANGE as if they were from Capella
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/core/blocks/withdrawals_test.go
Labels: Ready For Review, Withdrawals

#11818 Allow proposer duties one epoch in advance part 2
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
Labels: Ready For Review

#11819 attempt to fix WaitForTextInFile log corruption
  testing/endtoend/helpers/helpers.go
Labels: OK to merge

#11810 Use Single Log File in E2E
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/boot_node.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/components/lighthouse_validator.go
  testing/endtoend/components/web3remotesigner.go
Labels: Ready For Review, OK to merge, E2E Tests

#11808 Proposer RPC: helpers to get exits and slashings
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_empty_block.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_empty_block_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_exists.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_exists_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_slashings.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_slashings_test.go
  testing/util/BUILD.bazel
  testing/util/block.go
  testing/util/block_test.go
Labels: Ready For Review, OK to merge

#11830 Fix BUILD.bazel for v1alpha1 rpcs
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
Labels: Ready For Review, OK to merge

#11833 Track head slot through head block
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/receive_attestation_test.go
Labels: Ready For Review, OK to merge

#11828 fix trace name of function `ExecuteStateTransitionNoVerifyAnySig`
  beacon-chain/core/transition/transition_no_verify_sig.go
Labels: OK to merge
