Repository OffchainLabs/prysm, pull requests merged in 2022-10, with the labels that each got.

#11441 More efficient way of computing skip slot cache key
  beacon-chain/blockchain/head_sync_committee_info_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/skip_slot_cache.go
  beacon-chain/core/transition/skip_slot_cache_test.go
  beacon-chain/core/transition/transition.go
  beacon-chain/rpc/eth/beacon/pool_test.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Ready For Review, optimization

#11537 Fix Validator Monitor Registration
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
Labels: Ready For Review

#11536 Handle New Agent Version For Lodestar
  beacon-chain/p2p/monitoring.go
Labels: Ready For Review, OK to merge

#11540 Keymanager API: fix fee recipient API and add persistence
  validator/accounts/testing/BUILD.bazel
  validator/accounts/testing/mock.go
  validator/client/iface/BUILD.bazel
  validator/client/iface/validator.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/service.go
  validator/client/testutil/BUILD.bazel
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
Labels: Bug, OK to merge, API, Keymanager-API

#11524 Add flag to enable logging on rejected gossip message
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/subscriber.go
  config/features/config.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#11501 Migrate Historical States In Separate Routine
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/service.go
Labels: Ready For Review, OK to merge

#11547 Expose structs from API Middleware
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  validator/rpc/apimiddleware/endpoint_factory.go
  validator/rpc/apimiddleware/structs.go
  validator/rpc/apimiddleware/structs_test.go
Labels: Ready For Review, OK to merge, API

#11552 Add Withdrawal helpers
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/readonly_validator.go
  beacon-chain/state/state-native/readonly_validator_test.go
Labels: Ready For Review

#11556 Enable TLS for multiple beacon endpoints
  validator/client/multiple_endpoints_grpc_resolver.go
Labels: Ready For Review, Validator Client

#11555 Fix complains and bad test
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/state/testing/getters_block.go
  crypto/ecdsa/utils.go
  proto/prysm/v1alpha1/cloners_test.go
  testing/endtoend/evaluators/execution_engine.go
  validator/accounts/cli_options.go
  validator/accounts/testing/mock.go
  validator/rpc/standard_api_test.go
Labels: Ready For Review, OK to merge, Cleanup

#11515 prysmctl: validator exit
  cmd/prysmctl/BUILD.bazel
  cmd/prysmctl/main.go
  cmd/prysmctl/signing/BUILD.bazel
  cmd/prysmctl/signing/cmd.go
  cmd/validator/accounts/BUILD.bazel
  cmd/validator/accounts/accounts.go
  cmd/validator/accounts/exit.go
  cmd/validator/accounts/wallet_utils.go
  cmd/validator/accounts/wallet_utils_test.go
  cmd/validator/flags/BUILD.bazel
  config/params/values.go
  runtime/interop/generate_keys_test.go
  validator/accounts/accounts_exit.go
  validator/client/propose.go
  validator/node/node.go
  validator/node/node_test.go
Labels: Web3Signer, UX, prysmctl

#11558 Handle unaggregated attestation event
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
  beacon-chain/rpc/apimiddleware/structs.go
Labels: Ready For Review, API

#11538 `/eth/v1/beacon/blinded_blocks/{block_id}` API endpoint
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v2/beacon_block.pb.go
  proto/eth/v2/beacon_block.proto
  proto/eth/v2/ssz.pb.go
  proto/eth/v2/ssz.proto
Labels: Ready For Review, OK to merge, API

#11562 Remove `ValidatorCapella` protobuf
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.proto
Labels: Ready For Review, OK to merge, Cleanup

#11546 Reduce Block Burst Factor
  cmd/beacon-chain/flags/base.go
Labels: Ready For Review, OK to merge

#11560 Vendor Leaky Bucket Implementation
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/connection_gater_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/round_robin_test.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/rpc_goodbye_test.go
  beacon-chain/sync/rpc_metadata_test.go
  beacon-chain/sync/rpc_ping_test.go
  beacon-chain/sync/rpc_status_test.go
  container/leaky-bucket/BUILD.bazel
  container/leaky-bucket/LICENSE
  container/leaky-bucket/collector.go
  container/leaky-bucket/collector_test.go
  container/leaky-bucket/heap.go
  container/leaky-bucket/heap_test.go
  container/leaky-bucket/leakybucket.go
  container/leaky-bucket/leakybucket_test.go
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review

#11563 Add validator index with Withdrawal pb
  beacon-chain/state/state-native/setters_withdrawal_test.go
  proto/engine/v1/BUILD.bazel
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/generated.ssz.go
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Ready For Review, OK to merge, Spec

#11568 Beacon api: get duties prune payload id cache
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
Labels: Ready For Review, OK to merge

#11569 Fix locks in Capella setters
  beacon-chain/state/state-native/setters_withdrawal.go
Labels: Ready For Review, OK to merge

#11565 fix typo and log error
  beacon-chain/db/iface/interface.go
  testing/util/block.go
  testing/util/block_test.go
Labels: OK to merge

#11567 Retrieve proposer existence in cache with correct parameter
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review

#11575 revert moving validator-exit command
  cmd/validator/accounts/accounts.go
Labels: OK to merge

#10863 Add error if chain-config-file used concurrently with network
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
  config/features/flags.go
Labels: OK to merge

#11578 bazel: remove --stamp for builds
  .bazelrc
Labels: Ready For Review, CI, OK to merge

#11572 some minor fixes
  beacon-chain/blockchain/error.go
  beacon-chain/state/stategen/replay.go
Labels: OK to merge

#11417 tool to search db for a key prefix
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/kv.go
  cmd/prysmctl/BUILD.bazel
  cmd/prysmctl/db/BUILD.bazel
  cmd/prysmctl/db/buckets.go
  cmd/prysmctl/db/cmd.go
  cmd/prysmctl/db/query.go
  cmd/prysmctl/main.go
Labels: OK to merge

#11577 bazel: Check in 5.3.0 cross compile clang toolchain
  .bazelrc
  tools/cross-toolchain/configs/.latest.bazelrc
  tools/cross-toolchain/configs/clang/bazel_5.3.0/cc/BUILD
  tools/cross-toolchain/configs/clang/bazel_5.3.0/cc/armeabi_cc_toolchain_config.bzl
  tools/cross-toolchain/configs/clang/bazel_5.3.0/cc/builtin_include_directory_paths
  tools/cross-toolchain/configs/clang/bazel_5.3.0/cc/cc_toolchain_config.bzl
  tools/cross-toolchain/configs/clang/bazel_5.3.0/cc/cc_wrapper.sh
  tools/cross-toolchain/configs/clang/bazel_5.3.0/cc/module.modulemap
  tools/cross-toolchain/configs/clang/bazel_5.3.0/config/BUILD
  tools/cross-toolchain/configs/clang/bazel_5.3.0/java/BUILD
  tools/cross-toolchain/configs/clang/bazel_5.3.0/prysm_toolchains/BUILD.bazel
  tools/cross-toolchain/configs/clang/bazel_5.3.0/prysm_toolchains/WORKSPACE
  tools/cross-toolchain/configs/clang/bazel_5.3.0/prysm_toolchains/cc_toolchain_config_linux_arm64.bzl
  tools/cross-toolchain/configs/clang/bazel_5.3.0/prysm_toolchains/cc_toolchain_config_osx.bzl
  tools/cross-toolchain/configs/clang/bazel_5.3.0/prysm_toolchains/cc_toolchain_config_windows.bzl
  tools/cross-toolchain/configs/versions.bzl
Labels: Ready For Review, CI, OK to merge

#11583 Increase Block Burst Factor For E2E
  testing/endtoend/components/beacon_node.go
Labels: Ready For Review, OK to merge, E2E Tests

#11585 Forkchoice: add unknown roots in error msgs
  beacon-chain/forkchoice/doubly-linked-tree/store.go
Labels: Ready For Review

#11589 Add more buckets for block arrival latency histogram
  beacon-chain/sync/metrics.go
Labels: Ready For Review, OK to merge

#11594 corrected method name in comment
  beacon-chain/blockchain/execution_engine.go
Labels: OK to merge

#11593 some minor fixes
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/slasher/process_slashings.go
  testing/slasher/simulator/simulator.go
Labels: OK to merge, Cleanup

#11566 Capella beacon block
  consensus-types/blocks/execution_test.go
  consensus-types/blocks/factory.go
  consensus-types/blocks/factory_test.go
  consensus-types/blocks/getters.go
  consensus-types/blocks/getters_test.go
  consensus-types/blocks/proto.go
  consensus-types/blocks/proto_test.go
  consensus-types/blocks/testing/factory.go
  consensus-types/blocks/testing/mutator.go
  consensus-types/blocks/types.go
  consensus-types/interfaces/beacon_block.go
  consensus-types/mock/block.go
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
Labels: Ready For Review, OK to merge, Withdrawals

#11596 Add 4844 containers to protobuf
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/blobs.pb.go
  proto/prysm/v1alpha1/blobs.proto
Labels: Ready For Review, Blobspace
