Repository OffchainLabs/prysm, pull requests merged in 2022-09, with the labels that each got.

#11372 Better batch block processing warning
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: Ready For Review, OK to merge, UX

#11377 Performance Metrics for Prysm
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/metrics.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/state.go
  beacon-chain/state/stategen/metrics.go
  beacon-chain/state/stategen/replayer.go
  beacon-chain/sync/metrics.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review, OK to merge

#11362 less ominous --weak-subjectivity-checkpoint warning
  beacon-chain/blockchain/weak_subjectivity_checks.go
Labels: OK to merge

#11373 Simplify `BeaconBlockIsNil()`
  consensus-types/blocks/factory.go
  consensus-types/blocks/getters.go
Labels: Ready For Review, OK to merge

#11353 Fix fillInMissingBlocks
  beacon-chain/blockchain/process_block_helpers.go
Labels: Ready For Review, OK to merge

#11385 Defensive pulls protoarray
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
Labels: Ready For Review, OK to merge

#11386 Add in P2P Metrics for Mainnet
  beacon-chain/p2p/monitoring.go
  beacon-chain/p2p/service.go
Labels: Ready For Review, OK to merge

#11390 Fix Div By 0 in Small Helper
  beacon-chain/p2p/monitoring.go
Labels: Ready For Review, OK to merge

#11389 Remove activation/exit queue metrics
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
Labels: Ready For Review, OK to merge

#11331 Wallet Create CLI manager integration
  cmd/validator/accounts/backup_test.go
  cmd/validator/accounts/delete_test.go
  cmd/validator/accounts/exit_test.go
  cmd/validator/accounts/import.go
  cmd/validator/accounts/import_test.go
  cmd/validator/wallet/BUILD.bazel
  cmd/validator/wallet/create.go
  cmd/validator/wallet/create_test.go
  cmd/validator/wallet/edit_test.go
  cmd/validator/wallet/wallet.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_import_test.go
  validator/accounts/accounts_list_test.go
  validator/accounts/cli_manager.go
  validator/accounts/cli_options.go
  validator/accounts/wallet_create.go
  validator/node/BUILD.bazel
  validator/node/node_test.go
  validator/rpc/accounts_test.go
  validator/rpc/health.go
  validator/rpc/slashing_test.go
  validator/rpc/standard_api_test.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: OK to merge, Cleanup, UX

#11394 add forkchoice node timestamp to json response
  beacon-chain/rpc/apimiddleware/structs.go
Labels: Ready For Review, OK to merge

#11397 Harden witholding fix
  beacon-chain/forkchoice/doubly-linked-tree/node.go
  beacon-chain/forkchoice/protoarray/store.go
Labels: Ready For Review, OK to merge

#11395 Better log fee recipient mismatch
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
Labels: Ready For Review, OK to merge

#11402 remove children slice when pruning
  beacon-chain/forkchoice/doubly-linked-tree/store.go
Labels: Ready For Review, OK to merge

#11403 fix forkchoice endpoint
  beacon-chain/rpc/apimiddleware/structs.go
Labels: Ready For Review, OK to merge

#11410 Log `ready for merge` every min
  beacon-chain/execution/check_transition_config.go
Labels: Ready For Review, OK to merge, UX

#11375 Fixed size arrays in block interfaces and structs
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/header.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/blocks/signature.go
  beacon-chain/core/transition/transition_fuzz_test.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/monitor/process_block.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/rpc/statefetcher/fetcher_test.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/history.go
  beacon-chain/state/stategen/mock_test.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replayer_test.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/validate_beacon_blocks.go
  consensus-types/blocks/factory.go
  consensus-types/blocks/factory_test.go
  consensus-types/blocks/getters.go
  consensus-types/blocks/getters_test.go
  consensus-types/blocks/proto.go
  consensus-types/blocks/proto_test.go
  consensus-types/blocks/types.go
  consensus-types/interfaces/BUILD.bazel
  consensus-types/interfaces/beacon_block.go
  consensus-types/interfaces/utils.go
  consensus-types/mock/BUILD.bazel
  consensus-types/mock/block.go
  proto/migration/v1alpha1_to_v1.go
  testing/endtoend/evaluators/operations.go
  tools/blocktree/BUILD.bazel
  tools/blocktree/main.go
  validator/client/propose.go
  validator/client/propose_test.go
Labels: Ready For Review, OK to merge

#11396 Validate downloaded state slot matches header slot
  api/client/beacon/checkpoint.go
  api/client/beacon/checkpoint_test.go
Labels: Ready For Review, OK to merge

#11214 Tests for builder service
  api/client/builder/BUILD.bazel
  api/client/builder/client.go
  api/client/builder/testing/BUILD.bazel
  api/client/builder/testing/mock.go
  beacon-chain/builder/BUILD.bazel
  beacon-chain/builder/option.go
  beacon-chain/builder/service.go
  beacon-chain/builder/service_test.go
Labels: Ready For Review, OK to merge, Builder

#11404 Fall back to uncached getPaylod if first time outs
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
Labels: Ready For Review, OK to merge

#11387 Prune during on_tick
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/node.go
  beacon-chain/forkchoice/doubly-linked-tree/node_test.go
  beacon-chain/forkchoice/doubly-linked-tree/on_tick.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/doubly-linked-tree/vote_test.go
Labels: Ready For Review, OK to merge

#11425 Fix Gossipsub Parameter
  beacon-chain/p2p/parameter_test.go
  beacon-chain/p2p/pubsub.go
  beacon-chain/p2p/service.go
Labels: Ready For Review, OK to merge

#11427 Update bazel to 5.3.0 (LTS)
  .bazelrc
  .bazelversion
Labels: CI, OK to merge

#11429 Cancel context propoerly for validator runner
  validator/client/runner.go
Labels: Ready For Review, OK to merge

#11421 Report voted fractions for a given root
  beacon-chain/core/epoch/precompute/justification_finalization.go
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
  beacon-chain/forkchoice/doubly-linked-tree/node.go
  beacon-chain/forkchoice/doubly-linked-tree/node_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/node.go
  beacon-chain/forkchoice/protoarray/unrealized_justification.go
Labels: Ready For Review, OK to merge, Forkchoice

#11428 clean up: godoc comments, redundant castings and more
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/db/kv/execution_chain.go
  beacon-chain/execution/log_processing.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service_test.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/prysm/v1alpha1/cloners_test.go
  validator/accounts/wallet_create.go
  validator/rpc/standard_api_test.go
Labels: Ready For Review, OK to merge, Cleanup

#11434 Forkchoice: track highest received root
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/types.go
Labels: Ready For Review, Forkchoice

#11435 Metrics: capture reorg distances and depths
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/metrics.go
Labels: Ready For Review, OK to merge

#11424 Update block arrival histogram values
  beacon-chain/sync/metrics.go
Labels: Ready For Review, OK to merge

#11420 Remove unused `WithTimeout` method
  api/client/builder/client.go
Labels: Ready For Review

#11412 Release `headLock` on error
  beacon-chain/blockchain/head.go
Labels: Ready For Review

#11391 Implement optimistic sync spectests
  beacon-chain/execution/BUILD.bazel
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/builder.go
  testing/spectest/shared/common/forkchoice/runner.go
  testing/spectest/shared/common/forkchoice/service.go
  testing/spectest/shared/common/forkchoice/type.go
  testing/spectest/utils/utils.go
Labels: Ready For Review, OK to merge

#11453 Remove optimistic sync candidate check
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/node/config.go
  beacon-chain/node/config_test.go
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/config.go
  config/params/configset_test.go
  config/params/mainnet_config.go
  config/params/testnet_config_test.go
Labels: Ready For Review, OK to merge

#11459 Dont return if proposer boost roots are missing
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, OK to merge

#11463 do not return on error during on_tick
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review

#11470 Don't return out of routine when update head errors out
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review, OK to merge

#11487 Change Default Timeout To 30 Seconds
  network/auth.go
Labels: Ready For Review, Priority: High, OK to merge

#11483 Beacon api: propoerly submit blind block
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
Labels: Bug, Ready For Review, OK to merge

#11486 Remove unwanted wrapper of GRPC status error
  beacon-chain/rpc/eth/beacon/blocks.go
Labels: OK to merge

#11488 Beacon api: produce block should skip mev-boost
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.proto
Labels: Bug, Ready For Review, OK to merge

#11498 Fix sync tests and update to 1.2.0
  WORKSPACE
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, OK to merge

#11492 Update consensus layer badge to v1.2.0
  README.md
Labels: Ready For Review, OK to merge

#11455 Remove protoarray forkchoice
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/mock_test.go
  beacon-chain/blockchain/pow_block_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/doc.go
  beacon-chain/forkchoice/protoarray/errors.go
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/helpers.go
  beacon-chain/forkchoice/protoarray/helpers_test.go
  beacon-chain/forkchoice/protoarray/metrics.go
  beacon-chain/forkchoice/protoarray/no_vote_test.go
  beacon-chain/forkchoice/protoarray/node.go
  beacon-chain/forkchoice/protoarray/node_test.go
  beacon-chain/forkchoice/protoarray/on_tick.go
  beacon-chain/forkchoice/protoarray/on_tick_test.go
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
  beacon-chain/forkchoice/protoarray/proposer_boost.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/forkchoice/protoarray/unrealized_justification.go
  beacon-chain/forkchoice/protoarray/unrealized_justification_test.go
  beacon-chain/forkchoice/protoarray/vote_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  testing/spectest/mainnet/altair/forkchoice/forkchoice_test.go
  testing/spectest/mainnet/bellatrix/forkchoice/forkchoice_test.go
  testing/spectest/mainnet/phase0/forkchoice/forkchoice_test.go
  testing/spectest/minimal/altair/forkchoice/forkchoice_test.go
  testing/spectest/minimal/bellatrix/forkchoice/forkchoice_test.go
  testing/spectest/minimal/phase0/forkchoice/forkchoice_test.go
Labels: Ready For Review, OK to merge

#11502 Remove `INTERVALS_PER_SLOT` from place holder for test
  config/params/loader_test.go
Labels: Ready For Review, OK to merge

#11514 Fix attestations update head error logging
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review, UX

#11512 fix validator loggin timeTillDuty as a negative number
  validator/client/validator.go
Labels: Ready For Review, OK to merge

#11506 Don't mark builder status unhealthy if mev-boost status is non 200
  beacon-chain/builder/metric.go
  beacon-chain/builder/service.go
Labels: Ready For Review, OK to merge, Builder

#11513 Add a justified balance getter to forkchoice
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/errors.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/mock/mock.go
  beacon-chain/state/stategen/service.go
Labels: Ready For Review

#11519 Remove state code owners
  .github/CODEOWNERS
Labels: Ready For Review, OK to merge, Cleanup

#11503 update head should go even without attestations
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
Labels: Ready For Review, OK to merge

#11489 Add CLI flag to define execution engine timout
  beacon-chain/execution/engine_client.go
  beacon-chain/node/config.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  config/params/config.go
  config/params/mainnet_config.go
Labels: Ready For Review, OK to merge
