Repository OffchainLabs/prysm, pull requests merged in 2022-03, with the labels that each got.

#10289 Release lock before return `validatedTips`
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
Labels: Bug, OK to merge, Optimistic-sync

#10285 Add engine methods to block processing
  beacon-chain/blockchain/mock_engine_test.go
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
Labels: Ready For Review, OK to merge, Merge, Execution Engine

#10296 validator: Fix flaky test TestServer_RefreshJWTSecretOnFileChange
  validator/rpc/auth_token_test.go
Labels: Ready For Review, CI, OK to merge, Cleanup

#10250 Check Engine API Transition Configuration in Background
  beacon-chain/blockchain/mock_engine_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/check_transition_config.go
  beacon-chain/powchain/check_transition_config_test.go
  beacon-chain/powchain/engine-api-client/v1/BUILD.bazel
  beacon-chain/powchain/engine-api-client/v1/client.go
  beacon-chain/powchain/engine-api-client/v1/client_test.go
  beacon-chain/powchain/engine-api-client/v1/errors.go
  beacon-chain/powchain/engine-api-client/v1/mocks/BUILD.bazel
  beacon-chain/powchain/engine-api-client/v1/mocks/client.go
  beacon-chain/powchain/service.go
Labels: Ready For Review, OK to merge, Execution Engine

#10291 Validator RPC: add optimistic status check
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee.go
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee_test.go
Labels: Ready For Review, OK to merge, Optimistic-sync

#10304 Disable Vectorized HTR from Our Dev Flag
  beacon-chain/state/stateutil/field_root_validator.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#10305 Bellatrix validator terminal block helpers
  beacon-chain/powchain/engine-api-client/v1/mocks/BUILD.bazel
  beacon-chain/powchain/engine-api-client/v1/mocks/client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
Labels: Ready For Review, Merge

#10306 Refactor E2E port registration
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/boot_node.go
  testing/endtoend/components/eth1.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/components/lighthouse_validator.go
  testing/endtoend/components/validator.go
  testing/endtoend/endtoend_test.go
  testing/endtoend/evaluators/api_gateway_v1alpha1.go
  testing/endtoend/evaluators/api_middleware.go
  testing/endtoend/evaluators/metrics.go
  testing/endtoend/evaluators/node.go
  testing/endtoend/helpers/helpers.go
  testing/endtoend/params/BUILD.bazel
  testing/endtoend/params/params.go
  testing/endtoend/params/params_test.go
Labels: Ready For Review, OK to merge, Cleanup, E2E Tests

#10309 Better Error Log In Context Deadlines
  beacon-chain/p2p/subnets.go
Labels: Ready For Review, OK to merge, Cleanup

#10308 Update GoHashTree Library
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review, OK to merge

#10290 Remove Support for 2d-list Hashers
  beacon-chain/state/stateutil/block_header_root.go
  beacon-chain/state/stateutil/eth1_root.go
  beacon-chain/state/stateutil/field_root_attestation.go
  beacon-chain/state/stateutil/field_root_validator.go
  beacon-chain/state/stateutil/participation_bit_root.go
  beacon-chain/state/stateutil/pending_attestation_root.go
  beacon-chain/state/stateutil/sync_committee.root.go
  beacon-chain/state/stateutil/validator_root.go
  encoding/ssz/helpers.go
  encoding/ssz/helpers_test.go
  encoding/ssz/htrutils.go
  encoding/ssz/htrutils_fuzz_test.go
  encoding/ssz/htrutils_test.go
  encoding/ssz/merkleize.go
Labels: OK to merge, Cleanup

#10310 Add Better Error Logs for Context Deadlines
  beacon-chain/p2p/pubsub.go
Labels: Ready For Review, OK to merge, Cleanup

#10303 Spawn attestation routine at a better place
  beacon-chain/blockchain/service.go
Labels: Ready For Review, OK to merge

#10300 cherry picked PR for #10274
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_proposer_slashing_test.go
  beacon-chain/sync/validate_sync_committee_message.go
  beacon-chain/sync/validate_sync_committee_message_test.go
  beacon-chain/sync/validate_sync_contribution_proof.go
  beacon-chain/sync/validate_sync_contribution_proof_test.go
  beacon-chain/sync/validate_voluntary_exit.go
  beacon-chain/sync/validate_voluntary_exit_test.go
Labels: OK to merge, Merge, Optimistic-sync

#10277 Run multiple go-ethereum nodes in e2e
  testing/endtoend/BUILD.bazel
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/eth1/BUILD.bazel
  testing/endtoend/components/eth1/helpers.go
  testing/endtoend/components/eth1/miner.go
  testing/endtoend/components/eth1/node.go
  testing/endtoend/components/eth1/node_set.go
  testing/endtoend/components/tracing_sink.go
  testing/endtoend/components/validator.go
  testing/endtoend/endtoend_test.go
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/minimal_slashing_e2e_test.go
  testing/endtoend/params/params.go
  testing/endtoend/static-files/eth1/BUILD.bazel
  testing/endtoend/static-files/eth1/UTC--2021-12-22T19-14-08.590377700Z--878705ba3f8bc32fcf7f4caa1a35e72af65cf766
  testing/endtoend/static-files/eth1/genesis.json
Labels: E2E Tests

#10301 cherry picked PR of #10233
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: OK to merge, Merge, Optimistic-sync

#10314 Support Bellatrix state in `getStateV2` standard API
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/debug/debug.go
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/migration/v1alpha1_to_v1.go
  proto/migration/v1alpha1_to_v1_test.go
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v1alpha1_to_v2_test.go
  testing/util/state.go
  testing/util/state_test.go
Labels: API, Merge

#10311 RPC: add prepare execution payload
  beacon-chain/powchain/engine-api-client/v1/mocks/client.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/service.go
Labels: Ready For Review, OK to merge, Merge

#10297 Validator: deduplicate fork logic for block proposals
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  proto/prysm/v1alpha1/block/BUILD.bazel
  proto/prysm/v1alpha1/block/block_interfaces.go
  proto/prysm/v1alpha1/validator-client/BUILD.bazel
  proto/prysm/v1alpha1/validator-client/interface.go
  proto/prysm/v1alpha1/wrapper/BUILD.bazel
  proto/prysm/v1alpha1/wrapper/beacon_block.go
  proto/prysm/v1alpha1/wrapper/beacon_block_altair.go
  proto/prysm/v1alpha1/wrapper/beacon_block_altair_test.go
  proto/prysm/v1alpha1/wrapper/beacon_block_bellatrix.go
  proto/prysm/v1alpha1/wrapper/beacon_block_bellatrix_test.go
  proto/prysm/v1alpha1/wrapper/beacon_block_phase0.go
  proto/prysm/v1alpha1/wrapper/beacon_block_phase0_test.go
  validator/client/propose.go
  validator/client/propose_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10319 Rest of kiln changes
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/service.go
  beacon-chain/node/node.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
Labels: Ready For Review, OK to merge, Merge

#10320 E2E: Cleanup old Eth1 code
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/eth1.go
  testing/endtoend/components/eth1/helpers.go
Labels: Ready For Review, OK to merge, E2E Tests

#10323 Allow E2E To Run Control Tests
  testing/endtoend/components/beacon_node.go
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/minimal_slashing_e2e_test.go
  testing/endtoend/types/types.go
Labels: Ready For Review, E2E Tests

#10326 fix TestLockUnlock_CleansUnused
  async/multilock_test.go
Labels: OK to merge

#10328 fix TestSyncHandlers_WaitTillSynced
  beacon-chain/sync/service_test.go
Labels: OK to merge

#10325 Handle Port Registration Better
  testing/endtoend/components/tracing_sink.go
  testing/endtoend/params/params.go
  testing/endtoend/params/params_test.go
Labels: Ready For Review

#10329 Correct package name in features' README file
  config/features/README.md
Labels: Ready For Review, OK to merge, Cleanup

#10324 Bellatrix API support for block endpoints
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  proto/migration/BUILD.bazel
  proto/migration/v1alpha1_to_v1_test.go
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v1alpha1_to_v2_test.go
  proto/prysm/v1alpha1/wrapper/beacon_block.go
  proto/prysm/v1alpha1/wrapper/beacon_block_altair.go
  proto/prysm/v1alpha1/wrapper/beacon_block_bellatrix.go
  proto/prysm/v1alpha1/wrapper/beacon_block_phase0.go
  testing/util/block.go
  testing/util/block_test.go
Labels: Ready For Review, OK to merge, API, Merge

#10321 Kiln run time changes
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Ready For Review, OK to merge, Merge

#10229 Add USE_PRYSM_MODERN environment variable
  prysm.bat
  prysm.sh
Labels: OK to merge

#10332 PrepareBeaconProposer Protobuf Schema
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator.proto
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.pb.gw.go
  proto/prysm/v1alpha1/validator.proto
  testing/mock/BUILD.bazel
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
Labels: Ready For Review, OK to merge, API

#10338 Boost proposer later
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
Labels: Ready For Review, OK to merge

#10313 Adding ExtractKeystores to the Keymanager interface
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_list_test.go
  validator/client/validator_test.go
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote/keymanager.go
  validator/keymanager/remote/mock/BUILD.bazel
  validator/keymanager/remote/mock/mock_keymanager.go
  validator/keymanager/types.go
Labels: OK to merge

#10333 Flagutil: utility for json file from directory or url and unmarshal to struct
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/node_test.go
  validator/node/testdata/test-unmarshal-bad.json
  validator/node/testdata/test-unmarshal-good.json
Labels: Enhancement

#10344 this is safer if a goroutine require fails
  validator/client/validator_test.go
Labels: OK to merge

#10337 Minor Cleanup from #10255
  beacon-chain/state/stategen/replayer.go
  beacon-chain/state/stategen/replayer_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10341 Add unlock to `IsOptimistic` returns
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
Labels: Ready For Review, OK to merge

#10340 remove optimistic control flag
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/forkchoice/doubly-linked-tree/ffg_update_test.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/doubly-linked-tree/metrics.go
  beacon-chain/forkchoice/doubly-linked-tree/no_vote_test.go
  beacon-chain/forkchoice/doubly-linked-tree/node.go
  beacon-chain/forkchoice/doubly-linked-tree/node_test.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync_test.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/vote_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/no_vote_test.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/vote_test.go
Labels: Ready For Review, OK to merge

#10354 Fix Mnemonic Validation
  validator/accounts/BUILD.bazel
  validator/accounts/testdata/fuzz/FuzzValidateMnemonic/0258716f94e00f9df0da869fd97f9e0d0c6ac83eb528677d918f0ac9be5f4b8d
  validator/accounts/wallet_recover.go
  validator/accounts/wallet_recover_fuzz_test.go
  validator/accounts/wallet_recover_test.go
Labels: Ready For Review, Security

#10356 Fix sync committee assignment for Bellatrix
  beacon-chain/core/time/BUILD.bazel
  beacon-chain/core/time/slot_epoch.go
  beacon-chain/core/time/slot_epoch_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go
Labels: Ready For Review, OK to merge, Merge

#10348 Bellatrix publish block - API Middleware fixes
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
Labels: Ready For Review, OK to merge, API, Merge

#10359 Return early if ttd is not reached
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
Labels: Ready For Review, OK to merge, Merge

#10358 enable optimistic sync
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge, Merge, Optimistic-sync

#10349 Insert stored fee recipient for `ForkchoiceUpdated` call
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/node/config.go
  beacon-chain/node/config_test.go
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/beacon/config_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  config/params/config.go
Labels: Ready For Review, OK to merge, Merge

#10364 Handle pre state Altair with valid payload
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
Labels: Ready For Review, OK to merge, Merge

#10361 Add Bellatrix version to `ProduceBlock` API
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
Labels: Ready For Review, OK to merge, API, Merge

#10366 Update `default fee recipient` error log
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
Labels: Ready For Review, Merge

#10298 Spec test v1.1.10
  WORKSPACE
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, OK to merge, Spec

#10316 Some improvements for the state package testing
  beacon-chain/state/state-native/v1/getters_block_test.go
  beacon-chain/state/state-native/v1/getters_test.go
  beacon-chain/state/state-native/v1/getters_validator_test.go
  beacon-chain/state/state-native/v2/BUILD.bazel
  beacon-chain/state/state-native/v2/getters_block_test.go
  beacon-chain/state/state-native/v2/getters_test.go
  beacon-chain/state/state-native/v2/getters_validator_test.go
  beacon-chain/state/state-native/v2/references_test.go
  beacon-chain/state/state-native/v3/BUILD.bazel
  beacon-chain/state/state-native/v3/getters_block_test.go
  beacon-chain/state/state-native/v3/getters_test.go
  beacon-chain/state/state-native/v3/getters_validator_test.go
  beacon-chain/state/state-native/v3/references_test.go
  beacon-chain/state/testing/BUILD.bazel
  beacon-chain/state/testing/getters.go
  beacon-chain/state/testing/getters_block.go
  beacon-chain/state/testing/getters_validator.go
  beacon-chain/state/v1/getters_block_test.go
  beacon-chain/state/v1/getters_test.go
  beacon-chain/state/v1/getters_validator_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/deprecated_getters_test.go
  beacon-chain/state/v2/getters_block_test.go
  beacon-chain/state/v2/getters_test.go
  beacon-chain/state/v2/getters_validator_test.go
  beacon-chain/state/v2/references_test.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/getters_block_test.go
  beacon-chain/state/v3/getters_test.go
  beacon-chain/state/v3/getters_validator_test.go
  beacon-chain/state/v3/references_test.go
Labels: OK to merge

#10355 Update optimisticCandidateBlock to specs version
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
Labels: Ready For Review, OK to merge

#10357 Add database methods for optimistic sync
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/error.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/validated_checkpoint.go
  beacon-chain/db/kv/validated_checkpoint_test.go
  beacon-chain/forkchoice/doubly-linked-tree/errors.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/doubly-linked-tree/node.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/errors.go
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
Labels: Ready For Review, OK to merge, Merge, Optimistic-sync

#10367 PrepareBeaconProposer API
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: API, Merge

#10378 Update default fee warning
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Ready For Review, OK to merge, Merge

#10377 Add API Middleware Support for Fee Recipients Endpoint
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Labels: Ready For Review, OK to merge, API

#10374 API middleware support for bellatrix in `produceBlockV2`
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
Labels: Ready For Review, OK to merge, API, Merge

#10376 Fix `BaseFeePerGas` endianess
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/core/transition/bellatrix_transition_no_verify_sig_test.go
  beacon-chain/powchain/engine-api-client/v1/client_test.go
  beacon-chain/state/state-native/v3/setters_test.go
  beacon-chain/state/v3/setters_test.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
Labels: Ready For Review, OK to merge, Merge

#10381 Bellatrix fork choice spec tests
  testing/spectest/mainnet/bellatrix/forkchoice/BUILD.bazel
  testing/spectest/mainnet/bellatrix/forkchoice/forkchoice_test.go
  testing/spectest/minimal/bellatrix/forkchoice/BUILD.bazel
  testing/spectest/minimal/bellatrix/forkchoice/forkchoice_test.go
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/runner.go
  testing/spectest/shared/common/forkchoice/service.go
  testing/spectest/shared/common/forkchoice/type.go
Labels: Ready For Review, OK to merge, Merge

#10390 Add missing tests to state retrieval
  beacon-chain/rpc/eth/debug/debug_test.go
Labels: Ready For Review, OK to merge, API, Merge

#10392 Add notifyNewPayload to onBlockBatch
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
Labels: Ready For Review, Merge

#10394 Call FCU on update head after process attestation
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
Labels: OK to merge

#10312 Implement Fee Recipient: CLI flags and Calling Beacon API
  cmd/validator/flags/BUILD.bazel
  cmd/validator/flags/flags.go
  cmd/validator/main.go
  cmd/validator/usage.go
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
  config/validator/service/BUILD.bazel
  config/validator/service/fee-recipient-config.go
  proto/prysm/v1alpha1/validator.pb.go
  testing/mock/BUILD.bazel
  testing/mock/beacon_validator_client_mock.go
  validator/accounts/testing/mock.go
  validator/client/BUILD.bazel
  validator/client/iface/validator.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/client/wait_for_activation.go
  validator/client/wait_for_activation_test.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/node_test.go
  validator/node/testdata/good-prepare-beacon-proposer-config-multiple.json
  validator/node/testdata/good-prepare-beacon-proposer-config.json
Labels: Enhancement, API, Merge

#10380 Checkpoint Sync 1/5 - fork/version detection and unmarshaling support
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/wss.go
  beacon-chain/node/config.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/state-native/v2/state_trie.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v3/BUILD.bazel
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
  config/params/BUILD.bazel
  config/params/config.go
  config/params/loader.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  config/params/testnet_config_test.go
  config/params/testnet_e2e_config.go
  config/params/testnet_prater_config.go
  config/params/testnet_prater_config_test.go
  config/params/testnet_pyrmont_config.go
  config/params/values.go
  encoding/ssz/detect/BUILD.bazel
  encoding/ssz/detect/configfork.go
  encoding/ssz/detect/configfork_test.go
  encoding/ssz/detect/fieldspec.go
  encoding/ssz/detect/fieldspec_test.go
  network/forks/BUILD.bazel
  network/forks/errors.go
  network/forks/ordered.go
  network/forks/ordered_test.go
  proto/BUILD.bazel
  validator/node/node.go
Labels: Ready For Review, OK to merge

#10402 Fee recipient flag rename for beacon node
  beacon-chain/node/config.go
  beacon-chain/node/config_test.go
  cmd/beacon-chain/flags/BUILD.bazel
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
Labels: OK to merge, Cleanup, Merge

#10400 Insert payload hash to forkchoice store nodes
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/forkchoice/doubly-linked-tree/ffg_update_test.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/doubly-linked-tree/no_vote_test.go
  beacon-chain/forkchoice/doubly-linked-tree/node_test.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync_test.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/doubly-linked-tree/vote_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/helpers.go
  beacon-chain/forkchoice/protoarray/no_vote_test.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/forkchoice/protoarray/vote_test.go
Labels: Ready For Review, OK to merge, Merge

#10401 Return correct header root from API calls
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
Labels: Ready For Review, OK to merge, API

#10382 Migrating Keymanager account list functionality into each type
  validator/accounts/accounts_list.go
  validator/accounts/accounts_list_test.go
  validator/accounts/wallet_edit.go
  validator/client/validator_test.go
  validator/keymanager/derived/BUILD.bazel
  validator/keymanager/derived/keymanager.go
  validator/keymanager/local/BUILD.bazel
  validator/keymanager/local/keymanager.go
  validator/keymanager/remote-utils/BUILD.bazel
  validator/keymanager/remote-utils/format.go
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote/BUILD.bazel
  validator/keymanager/remote/keymanager.go
  validator/keymanager/remote/mock/mock_keymanager.go
  validator/keymanager/types.go
Labels: OK to merge, Cleanup

#10398 set optimistic status on notify payload
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
Labels: Ready For Review, OK to merge

#10404 rename prepare beacon proposer to fee recipient
  validator/client/validator_test.go
  validator/node/node.go
  validator/node/node_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10406 Fee Recipient : ux log fixes and prevent validator from calling beacon node if flags are not provided.
  validator/accounts/testing/mock.go
  validator/client/service.go
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/client/wait_for_activation.go
  validator/client/wait_for_activation_test.go
  validator/node/node.go
  validator/node/node_test.go
Labels: Bug, Cleanup, Merge

#10373 Complete coverage for in beacon chain state for getters checkpoint
  beacon-chain/state/state-native/v1/getters_checkpoint_test.go
  beacon-chain/state/state-native/v2/getters_checkpoint_test.go
  beacon-chain/state/state-native/v3/getters_checkpoint_test.go
  beacon-chain/state/testing/BUILD.bazel
  beacon-chain/state/testing/getters_checkpoint.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/getters_checkpoint_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/getters_checkpoint_test.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/getters_checkpoint_test.go
Labels: OK to merge

#10408 Block Processing And State Transition Improvments
  beacon-chain/blockchain/process_block.go
  beacon-chain/state/fieldtrie/field_trie_helpers.go
  beacon-chain/state/stateutil/participation_bit_root.go
  beacon-chain/state/stateutil/trie_helpers.go
  encoding/ssz/helpers.go
Labels: Ready For Review, OK to merge, Cleanup

#10368 RPC: Deduplicate block production logic
  beacon-chain/rpc/eth/beacon/blocks.go
Labels: Ready For Review, OK to merge

#10409 Add Method To Modify Participation Bits
  beacon-chain/core/altair/attestation.go
  beacon-chain/state/altair.go
  beacon-chain/state/phase0.go
  beacon-chain/state/state-native/v1/state_test.go
  beacon-chain/state/state-native/v1/unsupported_setters.go
  beacon-chain/state/state-native/v2/setters_participation.go
  beacon-chain/state/state-native/v2/setters_test.go
  beacon-chain/state/state-native/v3/setters_participation.go
  beacon-chain/state/state-native/v3/setters_test.go
  beacon-chain/state/testing/BUILD.bazel
  beacon-chain/state/testing/setters_participation.go
  beacon-chain/state/v1/state_test.go
  beacon-chain/state/v1/unsupported_setters.go
  beacon-chain/state/v2/setters_participation.go
  beacon-chain/state/v2/setters_test.go
  beacon-chain/state/v3/setters_participation.go
  beacon-chain/state/v3/setters_test.go
Labels: Enhancement, Ready For Review

#10403 return invalid roots from SetOptimisticToInvalid
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
Labels: Ready For Review, Merge

#10397 Setup Optimistic sync when starting the service
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: OK to merge

#10295 Ignore attestations voting for the wrong finalized checkpoint
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_attestation.go
Labels: Ready For Review, OK to merge, Spec

#10407 Add tracings for engine api methods
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/powchain/engine-api-client/v1/BUILD.bazel
  beacon-chain/powchain/engine-api-client/v1/client.go
Labels: Ready For Review, OK to merge, Merge

#10384 Checkpoint Sync 2/5 - API support for retrieving weak subjectivity data
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/weak_subjectivity.go
  beacon-chain/core/helpers/weak_subjectivity_test.go
  beacon-chain/rpc/apimiddleware/BUILD.bazel
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/server.go
  beacon-chain/rpc/eth/beacon/state.go
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  beacon-chain/rpc/eth/helpers/error_handling.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/assignments.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/committees.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/committees_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
  beacon-chain/rpc/prysm/v1alpha1/debug/state.go
  beacon-chain/rpc/prysm/v1alpha1/debug/state_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/statefetcher/BUILD.bazel
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/rpc/statefetcher/fetcher_test.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/history.go
  beacon-chain/state/stategen/history_test.go
  beacon-chain/state/stategen/mock/replayer.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
  beacon-chain/state/stategen/replayer.go
  beacon-chain/state/stategen/replayer_test.go
  beacon-chain/state/stategen/service.go
  beacon-chain/sync/initial-sync/round_robin.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  proto/prysm/v1alpha1/beacon_chain.pb.go
  proto/prysm/v1alpha1/beacon_chain.pb.gw.go
  proto/prysm/v1alpha1/beacon_chain.proto
  testing/mock/beacon_service_mock.go
Labels: OK to merge

#10421 fix issue #10420
  beacon-chain/rpc/eth/helpers/sync.go
Labels: OK to merge

#10417 Update Go-Ethereum
  .github/actions/gomodtidy/entrypoint.sh
  deps.bzl
  go.mod
  go.sum
  testing/endtoend/components/eth1/miner.go
  testing/endtoend/components/eth1/node.go
Labels: Ready For Review, OK to merge, Merge

#10307 Use --http-web3provider for Execution Engine Connection
  beacon-chain/powchain/options.go
  beacon-chain/powchain/service.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/powchain/options.go
  cmd/beacon-chain/usage.go
Labels: Ready For Review, OK to merge

#10426 Properly initialize replayer builder for rpc
  beacon-chain/rpc/service.go
Labels: Ready For Review, OK to merge

#10422 Ensure finalized root can't be zeros
  beacon-chain/blockchain/service.go
Labels: Ready For Review, OK to merge

#10418 Allow inner protoarray nodes to become VALID
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
Labels: Ready For Review, OK to merge, Merge, Optimistic-sync

#10389 Add `execution_optimistic` field to API responses
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/feed/block/events.go
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/eth/beacon/state.go
  beacon-chain/rpc/eth/beacon/state_test.go
  beacon-chain/rpc/eth/beacon/sync_committee.go
  beacon-chain/rpc/eth/beacon/sync_committee_test.go
  beacon-chain/rpc/eth/beacon/validator.go
  beacon-chain/rpc/eth/beacon/validator_test.go
  beacon-chain/rpc/eth/debug/BUILD.bazel
  beacon-chain/rpc/eth/debug/debug.go
  beacon-chain/rpc/eth/debug/debug_test.go
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/events/events_test.go
  beacon-chain/rpc/eth/helpers/sync.go
  beacon-chain/rpc/eth/helpers/sync_test.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  proto/eth/v1/events.pb.go
  proto/eth/v1/events.proto
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator.proto
  proto/eth/v2/beacon_block.pb.go
  proto/eth/v2/beacon_block.proto
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/eth/v2/sync_committee.pb.go
  proto/eth/v2/sync_committee.proto
  proto/eth/v2/validator.pb.go
  proto/eth/v2/validator.proto
Labels: OK to merge, API, Merge

#10385 Checkpoint Sync 3/5 - beacon node api client lib and prysmctl cli tool
  api/client/beacon/BUILD.bazel
  api/client/beacon/checkpoint.go
  api/client/beacon/checkpoint_test.go
  api/client/beacon/client.go
  api/client/beacon/client_test.go
  api/client/beacon/doc.go
  api/client/beacon/errors.go
  beacon-chain/core/helpers/weak_subjectivity.go
  beacon-chain/core/helpers/weak_subjectivity_test.go
  beacon-chain/rpc/eth/beacon/blocks.go
  cmd/prysmctl/BUILD.bazel
  cmd/prysmctl/checkpoint/BUILD.bazel
  cmd/prysmctl/checkpoint/checkpoint.go
  cmd/prysmctl/checkpoint/latest.go
  cmd/prysmctl/checkpoint/save.go
  cmd/prysmctl/main.go
  go.mod
  network/forks/errors.go
  network/forks/ordered.go
  network/forks/ordered_test.go
Labels: OK to merge

#10436 Fix Beacon API Responses For Bellatrix
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
Labels: Ready For Review, OK to merge, Merge

#10440 Remove Ristretto Cache For Public Keys
  crypto/bls/blst/BUILD.bazel
  crypto/bls/blst/public_key.go
Labels: Enhancement, Ready For Review

#10412 Update LastValidatedCheckpoint on DB
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/process_block_helpers.go
Labels: Ready For Review, OK to merge, Merge, Optimistic-sync

#10435 Cleanup helpers in `beacon-chain/core/blocks/payload.go`
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/sync/validate_beacon_blocks.go
  proto/prysm/v1alpha1/wrapper/beacon_block.go
  proto/prysm/v1alpha1/wrapper/beacon_block_altair.go
  proto/prysm/v1alpha1/wrapper/beacon_block_phase0.go
Labels: Ready For Review, OK to merge

#10413 Stop Checking Transition Configuration Post-Merge
  beacon-chain/core/blocks/payload.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/check_transition_config.go
  beacon-chain/powchain/check_transition_config_test.go
  beacon-chain/powchain/service.go
Labels: Ready For Review, OK to merge

#10386 Checkpoint Sync 4/5 - enable checkpoint sync to be used by beacon node
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/weak_subjectivity_checks.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
  beacon-chain/db/errors.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/error.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/wss.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/helpers/error_handling.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/service.go
  beacon-chain/sync/backfill/BUILD.bazel
  beacon-chain/sync/backfill/status.go
  beacon-chain/sync/backfill/status_test.go
  beacon-chain/sync/checkpoint/BUILD.bazel
  beacon-chain/sync/checkpoint/api.go
  beacon-chain/sync/checkpoint/file.go
  cmd/beacon-chain/BUILD.bazel
  cmd/beacon-chain/blockchain/options.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/sync/checkpoint/BUILD.bazel
  cmd/beacon-chain/sync/checkpoint/options.go
  cmd/beacon-chain/usage.go
  cmd/wrap_flags.go
Labels: OK to merge

#10427 Deterministic Proposer Root Boosting in Forkchoice
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/forkchoice/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/proposer_boost.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/types/BUILD.bazel
  beacon-chain/forkchoice/types/types.go
Labels: Ready For Review, OK to merge

#10414 Add Histogram Response Buckets to Engine API Methods
  beacon-chain/powchain/engine-api-client/v1/BUILD.bazel
  beacon-chain/powchain/engine-api-client/v1/client.go
  beacon-chain/powchain/engine-api-client/v1/metrics.go
Labels: Ready For Review, OK to merge, API, Execution Engine

#10444 Add Balance Read Lock When Aggregating Validator Metrics
  validator/client/metrics.go
Labels: Ready For Review

#10428 Forkchoice spec test: set boost with deterministic timing
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/runner.go
Labels: Ready For Review, OK to merge

#10454 Remove TODOs that were already taken care of
  beacon-chain/blockchain/receive_block.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: OK to merge

#10455 Align Beacon API with 2.2.0 spec
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
Labels: Ready For Review, OK to merge, API

#10459 Fix execution block's base fee endianness marshal/unmarshal
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
Labels: Bug, Ready For Review, Merge

#10452 Clean up blockchain pkg
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/state_balance_cache.go
  beacon-chain/blockchain/state_balance_cache_test.go
  beacon-chain/blockchain/testing/mock.go
Labels: Ready For Review, OK to merge

#10461 Spectest: Improve test size and timeouts
  testing/spectest/mainnet/altair/finality/BUILD.bazel
  testing/spectest/mainnet/altair/fork_transition/BUILD.bazel
  testing/spectest/mainnet/altair/forkchoice/BUILD.bazel
  testing/spectest/mainnet/altair/random/BUILD.bazel
  testing/spectest/mainnet/altair/sanity/BUILD.bazel
  testing/spectest/mainnet/bellatrix/finality/BUILD.bazel
  testing/spectest/mainnet/bellatrix/fork_transition/BUILD.bazel
  testing/spectest/mainnet/bellatrix/forkchoice/BUILD.bazel
  testing/spectest/mainnet/bellatrix/sanity/BUILD.bazel
  testing/spectest/mainnet/phase0/finality/BUILD.bazel
  testing/spectest/mainnet/phase0/forkchoice/BUILD.bazel
  testing/spectest/mainnet/phase0/random/BUILD.bazel
  testing/spectest/mainnet/phase0/sanity/BUILD.bazel
  testing/spectest/minimal/altair/forkchoice/BUILD.bazel
  testing/spectest/minimal/bellatrix/forkchoice/BUILD.bazel
  testing/spectest/minimal/phase0/forkchoice/BUILD.bazel
  testing/spectest/shared/common/ssz_static/BUILD.bazel
Labels: Ready For Review, CI, OK to merge

#10449 refactor genesis state flag handling, support url
  api/client/beacon/client.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/genesis.go
  beacon-chain/db/kv/genesis_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/sync/genesis/BUILD.bazel
  beacon-chain/sync/genesis/api.go
  beacon-chain/sync/genesis/file.go
  cmd/beacon-chain/BUILD.bazel
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/sync/genesis/BUILD.bazel
  cmd/beacon-chain/sync/genesis/options.go
  cmd/beacon-chain/usage.go
Labels: Ready For Review, OK to merge

#10457 Log terminal total difficulty status
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/check_transition_config.go
  beacon-chain/powchain/check_transition_config_test.go
Labels: Ready For Review, OK to merge, Merge

#10453 insert block to forkchoice after notifyNewPayload
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, Merge, Optimistic-sync

#10446 Return historical non-canonical blocks as optimistic
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
Labels: Ready For Review, OK to merge, Optimistic-sync

#10471 github workflows: pin go version to 1.17
  .github/actions/gomodtidy/entrypoint.sh
  .github/workflows/dappnode-release-trigger.yml
  .github/workflows/go.yml
Labels: CI, Priority: Critical, OK to merge

#10472 Remove duplicated engine mock
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/mock_engine_test.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/pow_block_test.go
  beacon-chain/powchain/engine-api-client/v1/mocks/client.go
Labels: Ready For Review, Cleanup

#10470 Sync: don't set block to bad due to timeout
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/powchain/engine-api-client/v1/client.go
  beacon-chain/powchain/engine-api-client/v1/client_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
Labels: Ready For Review, OK to merge, Merge
