Repository OffchainLabs/prysm, pull requests merged in 2022-06, with the labels that each got.

#10785 Validator client: add submit registration
  beacon-chain/core/signing/BUILD.bazel
  beacon-chain/core/signing/signature.go
  beacon-chain/core/signing/signature_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  config/params/config.go
  config/params/mainnet_config.go
  proto/engine/v1/generated.ssz.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/generated.ssz.go
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.pb.gw.go
  proto/prysm/v1alpha1/validator.proto
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
  validator/client/BUILD.bazel
  validator/client/propose_test.go
  validator/client/registration.go
  validator/client/registration_test.go
Labels: Ready For Review, OK to merge, Builder

#10798 Fix Fuzzing
  .github/workflows/go.yml
  crypto/bls/blst/stub.go
  fuzzbuzz.yaml
Labels: Bug, Ready For Review, OK to merge, Fuzz

#10801 Update forkchoice justified on init sync
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: Bug, Ready For Review, OK to merge

#10789 Add builder service skeleton and flag
  beacon-chain/builder/BUILD.bazel
  beacon-chain/builder/option.go
  beacon-chain/builder/service.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/node/options.go
  cmd/beacon-chain/BUILD.bazel
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
Labels: Ready For Review, OK to merge, Builder

#10793 Wrap unknown RPC errors
  beacon-chain/powchain/engine_client.go
Labels: Ready For Review, OK to merge

#10802 rewind cursor upon nil value (bucket)
  beacon-chain/db/kv/blocks.go
Labels: OK to merge

#10760 API SSZ content negotiation
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
Labels: Ready For Review, OK to merge, API

#10811 Change name and return type of HighestSlotBlocksBelow
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/state/stategen/history.go
  beacon-chain/state/stategen/history_test.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/mock_test.go
  beacon-chain/state/stategen/replayer.go
Labels: Ready For Review, OK to merge

#10818 Revert "Change name and return type of HighestSlotBlocksBelow (#10811)"
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/state/stategen/history.go
  beacon-chain/state/stategen/history_test.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/mock_test.go
  beacon-chain/state/stategen/replayer.go
Labels: Ready For Review, OK to merge

#10814 Set fee recipient validator index as per spec.
  beacon-chain/rpc/apimiddleware/structs.go
Labels: Bug, OK to merge, API

#10816 goppelganger -> doppelganger
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
Labels: Ready For Review, OK to merge

#10806 Add Back Timestamp Related Deposit Processing
  beacon-chain/powchain/block_reader.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: Ready For Review, OK to merge, Ropsten-required

#10817 Update ropsten TTD
  config/params/testnet_ropsten_config.go
Labels: Ready For Review, OK to merge, Ropsten-required

#10803 Fill missing payload ID
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service.go
Labels: Ready For Review, OK to merge

#10774 Change forkchoice API
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/forkchoice/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/errors.go
  beacon-chain/forkchoice/doubly-linked-tree/ffg_update_test.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/doubly-linked-tree/no_vote_test.go
  beacon-chain/forkchoice/doubly-linked-tree/node.go
  beacon-chain/forkchoice/doubly-linked-tree/node_test.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync_test.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification_test.go
  beacon-chain/forkchoice/doubly-linked-tree/vote_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/errors.go
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/no_vote_test.go
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/unrealized_justification_test.go
  beacon-chain/forkchoice/protoarray/vote_test.go
Labels: Ready For Review, OK to merge

#10829 Clean Up State Finalizer
  beacon-chain/state/state-native/state_trie.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v3/state_trie.go
Labels: Ready For Review, OK to merge, Cleanup

#10831 Only prune in newer finalization
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/service.go
Labels: Bug, Ready For Review, OK to merge

#10804 Suggested-Fee-Recipient flag should not override
  cmd/validator/flags/flags.go
  validator/node/node.go
  validator/node/node_test.go
Labels: Bug, OK to merge, docs-required

#10749 Validator client builder support
  api/client/builder/BUILD.bazel
  api/client/builder/client_test.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  cmd/beacon-chain/flags/BUILD.bazel
  cmd/beacon-chain/flags/base.go
  cmd/validator/flags/BUILD.bazel
  cmd/validator/flags/flags.go
  cmd/validator/main.go
  cmd/validator/usage.go
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
  config/params/config.go
  config/params/mainnet_config.go
  config/validator/service/BUILD.bazel
  config/validator/service/fee-recipient-config.go
  config/validator/service/proposer-settings.go
  proto/prysm/v1alpha1/generated.ssz.go
  testing/mock/beacon_validator_client_mock.go
  validator/accounts/testing/mock.go
  validator/client/BUILD.bazel
  validator/client/iface/validator.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/service.go
  validator/client/testutil/BUILD.bazel
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/client/wait_for_activation.go
  validator/client/wait_for_activation_test.go
  validator/keymanager/remote/mock/BUILD.bazel
  validator/keymanager/remote/mock/mock_keymanager.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/node_test.go
  validator/node/testdata/bad-prepare-beacon-proposer-config.json
  validator/node/testdata/good-prepare-beacon-proposer-config.yaml
  validator/node/testdata/test-unmarshal-bad.json
  validator/node/testdata/test-unmarshal-good.json
Labels: OK to merge, API, docs-required

#10833 Update spec labels
  README.md
Labels: Cleanup

#10825 Integrate builder client into builder service
  beacon-chain/builder/BUILD.bazel
  beacon-chain/builder/error.go
  beacon-chain/builder/metric.go
  beacon-chain/builder/option.go
  beacon-chain/builder/service.go
  beacon-chain/db/iface/interface.go
Labels: OK to merge, Builder

#10808 Integrate Engine Proxy into E2E
  network/endpoint.go
  testing/endtoend/component_handler_test.go
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/eth1/BUILD.bazel
  testing/endtoend/components/eth1/helpers.go
  testing/endtoend/components/eth1/proxy.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/endtoend_test.go
  testing/endtoend/params/params.go
  testing/endtoend/params/params_test.go
  testing/middleware/engine-api-proxy/BUILD.bazel
  testing/middleware/engine-api-proxy/options.go
  testing/middleware/engine-api-proxy/proxy.go
Labels: Ready For Review, OK to merge, E2E Tests

#10830 Efficiently Pack Uint64 Lists
  beacon-chain/state/fieldtrie/BUILD.bazel
  beacon-chain/state/fieldtrie/field_trie_helpers.go
  beacon-chain/state/stateutil/validator_root.go
Labels: Ready For Review, OK to merge, Cleanup

#10824 Refactor validator accounts backup to remove cli context dependency
  cmd/validator/accounts/BUILD.bazel
  cmd/validator/accounts/accounts.go
  cmd/validator/accounts/backup.go
  cmd/validator/accounts/backup_test.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_helper.go
  validator/accounts/cli_manager.go
  validator/accounts/cli_options.go
Labels: OK to merge

#10820 use slot:block index correctly
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/utils.go
  beacon-chain/db/kv/utils_test.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/state/stategen/history.go
  beacon-chain/state/stategen/history_test.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/mock_test.go
  beacon-chain/state/stategen/replayer.go
Labels: Ready For Review, OK to merge

#10839 enable dev on Ropsten
  config/features/config.go
Labels: Ready For Review, OK to merge

#10849 checkpoint sync e2e to use 3m timeout w/ elapsed log
  testing/endtoend/endtoend_test.go
Labels: Ready For Review, OK to merge

#10847 Update engine api buckets
  beacon-chain/powchain/metrics.go
Labels: Ready For Review, OK to merge

#10837 Native Blocks Ep. 1 - New types and functions
  consensus-types/blocks/BUILD.bazel
  consensus-types/blocks/factory.go
  consensus-types/blocks/factory_test.go
  consensus-types/blocks/getters.go
  consensus-types/blocks/getters_test.go
  consensus-types/blocks/proto.go
  consensus-types/blocks/proto_test.go
  consensus-types/blocks/testing/BUILD.bazel
  consensus-types/blocks/testing/factory.go
  consensus-types/blocks/testing/mutator.go
  consensus-types/blocks/types.go
Labels: OK to merge

#10842 Add optimistic status to chainhead
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/server.go
  beacon-chain/rpc/service.go
  proto/prysm/v1alpha1/beacon_chain.pb.go
  proto/prysm/v1alpha1/beacon_chain.proto
Labels: Ready For Review, OK to merge

#10852 API's `IsOptimistic` - update `header.StateRoot` only when block is not missing
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/eth/helpers/sync.go
  beacon-chain/rpc/eth/helpers/sync_test.go
Labels: Ready For Review, OK to merge, API

#10851 Add ttd metric
  beacon-chain/powchain/check_transition_config.go
  beacon-chain/powchain/metrics.go
Labels: Ready For Review, OK to merge

#10855 Fix default mainnet log when using chain config
  config/features/BUILD.bazel
  config/features/config.go
Labels: Ready For Review, OK to merge

#10823 Forkchoice checkpoints
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/mock_test.go
  beacon-chain/blockchain/new_slot.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/pow_block_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/forkchoice/doubly-linked-tree/ffg_update_test.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/doubly-linked-tree/no_vote_test.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification_test.go
  beacon-chain/forkchoice/doubly-linked-tree/vote_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/no_vote_test.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/forkchoice/protoarray/unrealized_justification.go
  beacon-chain/forkchoice/protoarray/unrealized_justification_test.go
  beacon-chain/forkchoice/protoarray/vote_test.go
  beacon-chain/forkchoice/types/BUILD.bazel
  beacon-chain/forkchoice/types/types.go
  beacon-chain/node/node.go
  beacon-chain/rpc/prysm/v1alpha1/debug/forkchoice.go
  beacon-chain/rpc/prysm/v1alpha1/debug/forkchoice_test.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, OK to merge

#10836 Add Optimistic Sync Scenario Testing
  testing/endtoend/BUILD.bazel
  testing/endtoend/component_handler_test.go
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/eth1/helpers.go
  testing/endtoend/components/eth1/node_set.go
  testing/endtoend/components/eth1/proxy.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/components/lighthouse_validator.go
  testing/endtoend/components/validator.go
  testing/endtoend/deps.bzl
  testing/endtoend/endtoend_test.go
  testing/endtoend/evaluators/BUILD.bazel
  testing/endtoend/evaluators/execution_engine.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
  testing/endtoend/types/types.go
  testing/middleware/engine-api-proxy/proxy.go
  testing/middleware/engine-api-proxy/proxy_test.go
Labels: Ready For Review, OK to merge, E2E Tests

#10750 Sync: don't process pending blocks w/o genesis time
  beacon-chain/sync/pending_blocks_queue.go
Labels: Bug, OK to merge, E2E Tests

#10866 Active balance: return `EFFECTIVE_BALANCE_INCREMENT` as min
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/rewards_penalties_test.go
Labels: Ready For Review, Spec

#10865 Disallow lower justified epoch to override higher epoch
  beacon-chain/core/epoch/precompute/justification_finalization.go
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
Labels: Ready For Review, OK to merge, Spec

#10841 Refactor validator accounts exit to remove cli context dependency
  cmd/validator/accounts/BUILD.bazel
  cmd/validator/accounts/accounts.go
  cmd/validator/accounts/exit.go
  cmd/validator/accounts/exit_test.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_exit.go
  validator/accounts/accounts_exit_test.go
  validator/accounts/accounts_helper.go
  validator/accounts/cli_manager.go
  validator/accounts/cli_options.go
Labels: Ready For Review, OK to merge

#10872 Fix gosec scan: G112 (CWE-400) Potential Slowloris Attack
  api/gateway/gateway.go
  monitoring/prometheus/service.go
  monitoring/prometheus/simple_server.go
  testing/endtoend/components/tracing_sink.go
  testing/middleware/engine-api-proxy/proxy.go
Labels: Ready For Review, OK to merge, Security

#10873 Fix message typo for `ErrorIs`
  testing/assertions/assertions.go
Labels: OK to merge, Cleanup

#10871 update info message about ws checkpoint
  beacon-chain/blockchain/weak_subjectivity_checks.go
Labels: Ready For Review, OK to merge

#10867 Enable gocognit linter
  .github/workflows/go.yml
  .golangci.yml
Labels: Ready For Review, OK to merge

#10773 Merge ascii art banner
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/merge_ascii_art.go
  beacon-chain/blockchain/pow_block.go
Labels: Ready For Review, OK to merge

#10874 Move `computeCheckpoints` to private
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/justification_finalization.go
  beacon-chain/core/epoch/precompute/precompute_test.go
Labels: Ready For Review, OK to merge

#10875 Fix Fuzzing Failures in Our CI
  .github/workflows/go.yml
Labels: Ready For Review, CI, OK to merge, Fuzz

#10879 Adding additional checksum check for fee recipient.
  validator/node/node.go
Labels: OK to merge, Cleanup, ux

#10880 Enable native state for Sepolia
  config/features/config.go
Labels: Ready For Review, OK to merge

#10881 Ignore genesis state url and checkpoint sync flags after first run of prysm
  beacon-chain/sync/checkpoint/BUILD.bazel
  beacon-chain/sync/checkpoint/api.go
  beacon-chain/sync/checkpoint/file.go
  beacon-chain/sync/genesis/BUILD.bazel
  beacon-chain/sync/genesis/api.go
  crypto/bls/blst/stub.go
Labels: Ready For Review, OK to merge

#10623 Graduate Prune Canonical Attestations Feature
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#10845 Add payload data logging
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/receive_block.go
Labels: Ready For Review, OK to merge

#10882 submit lists of validator registrations
  api/client/builder/client.go
  api/client/builder/client_test.go
  beacon-chain/builder/BUILD.bazel
  beacon-chain/builder/service.go
  consensus-types/forks/bellatrix/execution_payload.go
Labels: Ready For Review, OK to merge, Builder

#10862 Refactor: Continue reducing cognitive complexity
  api/gateway/apimiddleware/process_field.go
  beacon-chain/db/kv/state.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  validator/db/kv/migration_optimal_attester_protection.go
Labels: Ready For Review, OK to merge

#10887 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Ready For Review, OK to merge

#10889 Pad `Uint256`'s `SSZBytes` to length 32
  api/client/builder/types.go
  api/client/builder/types_test.go
Labels: Bug, Ready For Review, OK to merge, Builder

#10884 Improve Field Trie Recomputation
  beacon-chain/state/fieldtrie/field_trie.go
  beacon-chain/state/state-native/state_trie.go
  beacon-chain/state/state-native/state_trie_test.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v1/state_trie_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/state_test.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/state_test.go
  beacon-chain/state/v3/state_trie.go
Labels: Ready For Review, OK to merge

#10895 Small API Middleware upgrades
  api/gateway/apimiddleware/process_request.go
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/structs.go
Labels: Ready For Review, OK to merge, API

#10898 Revert `enable-native-state` flag
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#10897 Do not downcast time in currentslot
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/receive_block_test.go
  time/slots/slottime.go
Labels: Ready For Review, OK to merge

#10896 Prune within forkchoice
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/vote_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/vote_test.go
Labels: Ready For Review

#10854 Refactor: Reduce cognitive complexity for 5 out of top 10 functions in code base
  beacon-chain/powchain/log_processing.go
  beacon-chain/sync/pending_attestations_queue.go
  validator/client/metrics.go
  validator/client/runner.go
  validator/client/wait_for_activation.go
Labels: OK to merge

#10819 Enable fastssz to use vectorized HTR hashing algo
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/config.go
  beacon-chain/node/node.go
  deps.bzl
  go.mod
  go.sum
  validator/node/BUILD.bazel
  validator/node/node.go
Labels: OK to merge

#10905 Use forkchoice to verify finalized descendant
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: Ready For Review, OK to merge

#10906 Change gocognit complextity threshold to 65
  .golangci.yml
Labels: OK to merge

#10912 Add spec URLs to API docs
  proto/eth/service/beacon_chain_service.proto
  proto/eth/service/beacon_debug_service.proto
  proto/eth/service/events_service.proto
  proto/eth/service/node_service.proto
  proto/eth/service/validator_service.proto
Labels: Ready For Review, OK to merge, API

#10907 Change submit validator registration to registration(s)
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.pb.gw.go
  proto/prysm/v1alpha1/validator.proto
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
  validator/client/registration.go
  validator/client/registration_test.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/client/wait_for_activation_test.go
Labels: Ready For Review, OK to merge, Builder

#10915 Return error when requesting future state
  beacon-chain/rpc/statefetcher/BUILD.bazel
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/rpc/statefetcher/fetcher_test.go
Labels: Ready For Review, OK to merge

#10893 Apply Proposer Boost from forkchoice
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/proposer_boost.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/store.go
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/builder.go
Labels: Ready For Review, OK to merge

#10924 Register builder service
  beacon-chain/builder/option.go
  beacon-chain/builder/service.go
  beacon-chain/node/node.go
Labels: Ready For Review, Builder

#10914 Deprecate Step Parameter from our Block By Range Requests
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
Labels: Ready For Review, OK to merge, Sync

#10908 RPC: builder block
  beacon-chain/builder/service.go
  beacon-chain/builder/testing/BUILD.bazel
  beacon-chain/builder/testing/mock.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
Labels: Ready For Review, OK to merge, Builder

#10927 Update fastssz dependency
  go.mod
  go.sum
Labels: Ready For Review, OK to merge

#10926 Rename `upgrade_to_altair.go` to `upgrade_to_bellatrix.go`
  testing/spectest/shared/bellatrix/fork/BUILD.bazel
  testing/spectest/shared/bellatrix/fork/upgrade_to_bellatrix.go
Labels: Ready For Review, OK to merge, Cleanup

#10919 cmd/beacon-chain: add jwtcommands
  cmd/beacon-chain/BUILD.bazel
  cmd/beacon-chain/main.go
Labels: OK to merge

#10929 Stop ruining our lives with flaky e2e
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
Labels: OK to merge

#10930 Ignore nil node when saving orphaned atts
  beacon-chain/blockchain/head.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
Labels: Ready For Review, OK to merge

#10903 Deprecate store in blockchain pkg
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/init_sync_process_block.go
  beacon-chain/blockchain/init_sync_process_block_test.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/store/BUILD.bazel
  beacon-chain/blockchain/store/doc.go
  beacon-chain/blockchain/store/new.go
  beacon-chain/blockchain/store/new_test.go
  beacon-chain/blockchain/store/setter_getter.go
  beacon-chain/blockchain/store/setter_getter_test.go
  beacon-chain/blockchain/store/type.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/on_tick.go
  beacon-chain/forkchoice/doubly-linked-tree/on_tick_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/on_tick.go
  beacon-chain/forkchoice/protoarray/on_tick_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/validate_beacon_blocks.go
  testing/spectest/shared/common/forkchoice/builder.go
Labels: Ready For Review, OK to merge

#10937 Fix Builder Service Panic
  beacon-chain/builder/service.go
Labels: OK to merge

#10935 State: add fuzz test for unmarshal ssz
  beacon-chain/state/v1/state_fuzz_test.go
Labels: OK to merge

#10938 Fix Eth1Connection API Panic
  beacon-chain/rpc/prysm/v1alpha1/node/server.go
Labels: Ready For Review, OK to merge

#10932 Relinquish peerLock when blockFetcher context is done
  beacon-chain/sync/initial-sync/blocks_fetcher.go
Labels: OK to merge

#10939 Update fastssz dependency in `deps.bzl`
  deps.bzl
  proto/engine/v1/generated.ssz.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Ready For Review

#10940 Update sepolia ttd
  config/params/testnet_sepolia_config.go
Labels: Ready For Review, OK to merge

#10942 RPC: Add submit registration endpoint
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Ready For Review, OK to merge

#10918 typo: convert tab to space
  prysm.sh
Labels: OK to merge

#10943 Add More Visibility Into Sync Committee Message Participation
  beacon-chain/core/altair/sync_committee.go
  beacon-chain/core/altair/sync_committee_test.go
  validator/accounts/testing/mock.go
  validator/client/iface/validator.go
  validator/client/log.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/sync_committee.go
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
Labels: Ready For Review, OK to merge

#10944 Add additional logging fields for post-merge transition blocks
  validator/client/propose.go
Labels: OK to merge

#10945 Integrate better fastssz validation errors into Prysm
  beacon-chain/operations/attestations/kv/aggregated_test.go
  deps.bzl
  go.mod
  go.sum
  proto/engine/v1/generated.ssz.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Ready For Review, OK to merge

#10951 Don't log `terminal difficulty has not been reached yet...` until Bellatrix
  beacon-chain/powchain/check_transition_config.go
Labels: Ready For Review, OK to merge, ux

#10952 Testutil refactor attestations
  beacon-chain/blockchain/metrics_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/core/altair/attestation_test.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/blocks/block_regression_test.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/monitor/process_block_test.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/block_test.go
  beacon-chain/operations/attestations/kv/forkchoice_test.go
  beacon-chain/operations/attestations/kv/seen_bits_test.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/operations/attestations/prune_expired_test.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/eth/events/events_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/slasher/process_slashings_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_attester_slashing_test.go
  proto/migration/v1alpha1_to_v1_test.go
  testing/util/altair.go
  testing/util/attestation.go
  testing/util/attestation_test.go
  testing/util/block.go
  tools/benchmark-files-gen/main.go
  validator/client/aggregate_test.go
  validator/client/attest_test.go
Labels: OK to merge

#10953 RPC adds builder service
  beacon-chain/builder/service.go
  beacon-chain/node/node.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
Labels: Ready For Review, OK to merge, Builder

#10936 Experimental disable boundary checks
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/epoch/precompute/justification_finalization.go
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/on_tick.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/on_tick.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/forkchoice/protoarray/unrealized_justification.go
  beacon-chain/forkchoice/protoarray/unrealized_justification_test.go
  beacon-chain/state/state-native/getters_participation.go
  beacon-chain/state/stateutil/unrealized_justification.go
  beacon-chain/state/v2/getters_participation.go
  beacon-chain/state/v3/getters_participation.go
  config/features/config.go
  config/features/flags.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: OK to merge

#10528 E2E: fee-recipient evaluator
  config/validator/service/proposer-settings.go
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/eth1/miner.go
  testing/endtoend/components/eth1/node.go
  testing/endtoend/components/validator.go
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/evaluators/BUILD.bazel
  testing/endtoend/evaluators/fee_recipient.go
  validator/node/node.go
Labels: OK to merge, E2E Tests, Merge

#10954 Can get payload header from builder
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
Labels: Ready For Review, OKR Item, Builder

#10960 Fee Recipient E2E misscounting deterministic keys leading to flakes
  testing/endtoend/evaluators/fee_recipient.go
Labels: Bug, OK to merge, E2E Tests

#10959 Log error in `fetchBlocksFromPeer`
  beacon-chain/sync/initial-sync/blocks_fetcher.go
Labels: Ready For Review, OK to merge

#10963 do not overwrite log
  beacon-chain/blockchain/log.go
Labels: Ready For Review, OK to merge

#10962 More sepolia boot nodes
  config/params/testnet_sepolia_config.go
Labels: Ready For Review, OK to merge
