Repository OffchainLabs/prysm, pull requests merged in 2022-01, with the labels that each got.

#10049 Update `Transactions` and `ExtraData` non empty check
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
Labels: Ready For Review

#10039 Use prysm require test lib
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/pubsub_filter_test.go
Labels: Ready For Review, OK to merge

#10028 Add validate payload helpers
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
Labels: Ready For Review, OK to merge, Merge

#10030 Add HTR for txs
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
  encoding/ssz/BUILD.bazel
  encoding/ssz/htrutils.go
  encoding/ssz/htrutils_test.go
Labels: Ready For Review, OK to merge, Merge

#10016 Web3signer keymanager: key manager implementation
  beacon-chain/p2p/metaData
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/client.go
  validator/keymanager/remote-web3signer/client_test.go
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/keymanager_test.go
Labels: Enhancement, API, Web3Signer

#10054 Add `process_execution_payload` implementation
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
Labels: Ready For Review, Merge

#10057 Updating eip3076_spec_tests and eth_networks URLs
  WORKSPACE
Labels: OK to merge

#10055 p2p: no alloc extract of gossip digest
  beacon-chain/p2p/pubsub.go
  beacon-chain/p2p/pubsub_test.go
Labels: Enhancement, Ready For Review, Networking, OK to merge

#10060 Add process_execution_payload to process_block
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/bellatrix_transition_no_verify_sig_test.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/core/transition/transition_no_verify_sig_test.go
  testing/util/BUILD.bazel
  testing/util/bellatrix.go
Labels: Ready For Review, OK to merge, Merge

#10062 Can upgrade to Bellatrix in process slots
  beacon-chain/core/execution/BUILD.bazel
  beacon-chain/core/execution/upgrade_test.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_test.go
Labels: Ready For Review, OK to merge, Merge

#10052 Allow comma-separated event topics
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/events/events_test.go
Labels: Ready For Review, OK to merge, API

#10044 #10036 Replace codename Merge with Bellatrix (1st step)
  beacon-chain/blockchain/metrics.go
  beacon-chain/cache/sync_committee_head_state.go
  beacon-chain/cache/sync_committee_head_state_test.go
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/altair/epoch_precompute_test.go
  beacon-chain/core/altair/transition.go
  beacon-chain/core/altair/transition_test.go
  beacon-chain/core/blocks/attester_slashing.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/blocks/payload_test.go
  beacon-chain/core/blocks/proposer_slashing.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/execution/upgrade.go
  beacon-chain/core/execution/upgrade_test.go
  beacon-chain/core/time/slot_epoch.go
  beacon-chain/core/time/slot_epoch_test.go
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/db/kv/block_merge_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/key.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/state/stateutil/state_hasher.go
  beacon-chain/state/types/types.go
  beacon-chain/state/v3/deprecated_getters.go
  beacon-chain/state/v3/deprecated_getters_test.go
  beacon-chain/state/v3/deprecated_setters.go
  beacon-chain/state/v3/deprecated_setters_test.go
  beacon-chain/state/v3/field_roots.go
  beacon-chain/state/v3/getters_block_test.go
  beacon-chain/state/v3/getters_misc.go
  beacon-chain/state/v3/getters_state.go
  beacon-chain/state/v3/getters_test.go
  beacon-chain/state/v3/setters_test.go
  beacon-chain/state/v3/state_trie.go
  beacon-chain/state/v3/state_trie_test.go
  beacon-chain/state/v3/types.go
  cmd/beacon-chain/flags/base.go
  config/params/config.go
  config/params/mainnet_config.go
  proto/eth/ext/options.pb.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/beacon_state.pb.go
  proto/prysm/v1alpha1/beacon_state.proto
  proto/prysm/v1alpha1/cloners_test.go
  proto/prysm/v1alpha1/generated.ssz.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
  proto/prysm/v1alpha1/wrapper/beacon_block.go
  proto/prysm/v1alpha1/wrapper/beacon_block_test.go
  runtime/version/fork.go
  testing/util/merge_state.go
  testing/util/merge_state_test.go
  validator/keymanager/remote-web3signer/client.go
Labels: Ready For Review, OK to merge

#10032 Initialize Merkle Layers and Recompute Dirty Fields in BeaconState Proofs
  beacon-chain/state/phase0.go
  beacon-chain/state/v1/proofs.go
  beacon-chain/state/v1/proofs_test.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v2/proofs.go
  beacon-chain/state/v2/proofs_test.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v3/proofs.go
  beacon-chain/state/v3/proofs_test.go
  beacon-chain/state/v3/state_trie.go
Labels: Ready For Review

#10071 Update README.md
  README.md
Labels: OK to merge

#10040 Export reverse byte order function
  encoding/bytesutil/bytes.go
  encoding/bytesutil/bytes_test.go
  runtime/interop/BUILD.bazel
  runtime/interop/generate_keys.go
Labels: Ready For Review, OK to merge

#10061 Web3Signer: Object Mapper and Types
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/README.md
  validator/keymanager/remote-web3signer/client.go
  validator/keymanager/remote-web3signer/client_test.go
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/v1/BUILD.bazel
  validator/keymanager/remote-web3signer/v1/custom_mappers.go
  validator/keymanager/remote-web3signer/v1/custom_mappers_test.go
  validator/keymanager/remote-web3signer/v1/mocks.go
  validator/keymanager/remote-web3signer/v1/web3signer_types.go
Labels: Enhancement, Ready For Review, API, Web3Signer

#10075 tools/deployContract: Remove specific k8s code
  go.mod
  go.sum
  tools/deployContract/BUILD.bazel
  tools/deployContract/deployContract.go
Labels: Ready For Review, OK to merge, Cleanup

#10076 Do not reuse endpoint struct between API Middleware requests
  api/gateway/apimiddleware/api_middleware.go
Labels: Ready For Review, OK to merge, API

#10081 Spectests: Refactor ssz_static tests to deduplicate code and test custom HTR
  testing/spectest/shared/altair/ssz_static/BUILD.bazel
  testing/spectest/shared/altair/ssz_static/ssz_static.go
  testing/spectest/shared/bellatrix/ssz_static/BUILD.bazel
  testing/spectest/shared/bellatrix/ssz_static/ssz_static.go
  testing/spectest/shared/common/ssz_static/BUILD.bazel
  testing/spectest/shared/common/ssz_static/ssz_static.go
  testing/spectest/shared/common/ssz_static/ssz_static_example_test.go
  testing/spectest/shared/common/ssz_static/types.go
  testing/spectest/shared/phase0/ssz_static/BUILD.bazel
  testing/spectest/shared/phase0/ssz_static/ssz_static.go
Labels: Ready For Review, OK to merge, Cleanup

#10079 Make Radek and Nishant code owners of duplicated state code
  .github/CODEOWNERS
Labels: Ready For Review, OK to merge

#10066 Added analyzer for detecting recursive/nested mutex read locks.
  nogo_config.json
  tools/analyzers/recursivelock/BUILD.bazel
  tools/analyzers/recursivelock/analyzer.go
  tools/analyzers/recursivelock/analyzer_test.go
  tools/analyzers/recursivelock/testdata/BUILD.bazel
  tools/analyzers/recursivelock/testdata/badlockswithmethods.go
  tools/analyzers/recursivelock/testdata/badlockswithstructs.go
  tools/analyzers/recursivelock/testdata/complexlocks.go
  tools/analyzers/recursivelock/testdata/globallocks.go
  tools/analyzers/recursivelock/testdata/nonrlocks.go
  tools/analyzers/recursivelock/testdata/types.go
Labels: OK to merge

#10082 p2p: Update libp2p and libp2p-pubsub
  beacon-chain/p2p/connection_gater_test.go
  beacon-chain/p2p/dial_relay_node_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/testing/p2p.go
  deps.bzl
  go.mod
  go.sum
  testing/fuzz/rpc_status_fuzz.go
Labels: Ready For Review, Networking, OK to merge

#10073 Eth1 connections
  beacon-chain/node/node.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/powchain/testing/mock_powchain.go
  beacon-chain/rpc/prysm/v1alpha1/node/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/node/server.go
  beacon-chain/rpc/prysm/v1alpha1/node/server_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/testutil/BUILD.bazel
  beacon-chain/rpc/testutil/mock_powchain_info_fetcher.go
  proto/prysm/v1alpha1/node.pb.go
  proto/prysm/v1alpha1/node.pb.gw.go
  proto/prysm/v1alpha1/node.proto
  testing/mock/node_service_mock.go
Labels: Ready For Review

#10085 Add propose block bellatrix
  validator/client/propose.go
  validator/client/propose_test.go
Labels: Ready For Review, OK to merge, Merge

#10090 refactoring: Deduplicate code
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/block_altair_test.go
  beacon-chain/db/kv/block_merge_test.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/finalized_block_roots_test.go
  beacon-chain/rpc/eth/beacon/sync_committee.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  config/fieldparams/BUILD.bazel
  config/fieldparams/common_test.go
  config/fieldparams/mainnet_test.go
  config/fieldparams/minimal_test.go
  proto/prysm/v1alpha1/wrapper/beacon_block.go
  proto/prysm/v1alpha1/wrapper/beacon_block_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10077 Eth2api: `GetBlockSSZ` supports bellatrix block
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/BUILD.bazel
  proto/eth/v2/generated.ssz.go
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v1alpha1_to_v2_test.go
  proto/prysm/v1alpha1/beacon_chain.pb.go
  proto/prysm/v1alpha1/beacon_chain.proto
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Ready For Review, OK to merge, Merge

#10074 Move ErrNilValidatorsInState from one in each state version to a common one
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/error.go
  beacon-chain/state/state-native/v1/getters_validator.go
  beacon-chain/state/state-native/v1/getters_validator_test.go
  beacon-chain/state/state-native/v2/BUILD.bazel
  beacon-chain/state/state-native/v2/getters_validator.go
  beacon-chain/state/state-native/v2/getters_validator_test.go
  beacon-chain/state/state-native/v3/BUILD.bazel
  beacon-chain/state/state-native/v3/getters_validator.go
  beacon-chain/state/state-native/v3/getters_validator_test.go
  beacon-chain/state/v1/getters_validator.go
  beacon-chain/state/v1/getters_validator_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/getters_validator.go
  beacon-chain/state/v2/getters_validator_test.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/getters_validator.go
  beacon-chain/state/v3/getters_validator_test.go
Labels: OK to merge

#10093 Remove `CanonicalStateChan`
  beacon-chain/rpc/prysm/v1alpha1/beacon/server.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go
  beacon-chain/rpc/service.go
Labels: Ready For Review, OK to merge, Cleanup

#10084 Web3Signer: Sign Method Implementation
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
  validator/client/aggregate.go
  validator/client/aggregate_test.go
  validator/client/attest.go
  validator/client/attest_test.go
  validator/client/propose.go
  validator/client/propose_test.go
  validator/client/sync_committee.go
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/client.go
  validator/keymanager/remote-web3signer/client_test.go
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/keymanager_test.go
  validator/keymanager/remote-web3signer/v1/BUILD.bazel
  validator/keymanager/remote-web3signer/v1/custom_mappers.go
  validator/keymanager/remote-web3signer/v1/custom_mappers_test.go
  validator/keymanager/remote-web3signer/v1/mocks.go
  validator/keymanager/remote-web3signer/v1/requests.go
  validator/keymanager/remote-web3signer/v1/requests_test.go
  validator/keymanager/remote-web3signer/v1/web3signer_types.go
Labels: Ready For Review, API, Web3Signer

#10088 e2e: Add web3signer component
  WORKSPACE
  testing/endtoend/BUILD.bazel
  testing/endtoend/README.md
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/validator.go
  testing/endtoend/components/web3remotesigner.go
  testing/endtoend/components/web3remotesigner_test.go
  testing/endtoend/deps.bzl
  testing/endtoend/endtoend_test.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/types/types.go
  testing/endtoend/web3signer.BUILD
Labels: Ready For Review, OK to merge

#10089 Update stategen for Bellatrix
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: Ready For Review, OK to merge, Merge

#10101 Use Better Head Info Fetcher
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee.go
Labels: Ready For Review, Cleanup

#10103 Cleanup Up Resources Correctly
  beacon-chain/powchain/service.go
Labels: Ready For Review, OK to merge

#10102 Do Not Copy State During Upgrade
  beacon-chain/core/altair/upgrade.go
  beacon-chain/core/execution/upgrade.go
Labels: Ready For Review, OK to merge

#10072 Bellatrix p2p changes
  beacon-chain/p2p/encoder/ssz.go
  beacon-chain/p2p/encoder/ssz_test.go
  beacon-chain/p2p/fork_watcher.go
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/p2p/gossip_topic_mappings_test.go
  beacon-chain/p2p/message_id.go
  beacon-chain/p2p/message_id_test.go
  beacon-chain/p2p/pubsub_filter.go
  beacon-chain/p2p/rpc_topic_mappings_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/types/object_mapping.go
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/config.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  config/params/network_config.go
Labels: Ready For Review, Merge

#10104 Remove commented code
  beacon-chain/blockchain/service.go
Labels: Ready For Review, OK to merge

#10115 Resolve issues with G304
  testing/endtoend/helpers/helpers.go
  tools/specs-checker/download.go
  validator/accounts/accounts_backup.go
Labels: OK to merge, Security

#10111 Make Batch Verification Of Gossip Default
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#10106 Filter Duplicates Messages For Sync Contributions
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee.go
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee_test.go
Labels: Ready For Review, OK to merge

#10113 Make Get Block Optimization Default
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#10105 Use Batch Decompression For Signatures
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee.go
  crypto/bls/bls.go
  crypto/bls/blst/signature.go
  crypto/bls/blst/signature_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10086 Native beacon state: v1
  beacon-chain/state/state-native/custom-types/BUILD.bazel
  beacon-chain/state/state-native/custom-types/block_roots.go
  beacon-chain/state/state-native/custom-types/block_roots_test.go
  beacon-chain/state/state-native/custom-types/historical_roots.go
  beacon-chain/state/state-native/custom-types/historical_roots_test.go
  beacon-chain/state/state-native/custom-types/randao_mixes.go
  beacon-chain/state/state-native/custom-types/randao_mixes_test.go
  beacon-chain/state/state-native/custom-types/state_roots.go
  beacon-chain/state/state-native/custom-types/state_roots_test.go
  beacon-chain/state/state-native/v1/BUILD.bazel
  beacon-chain/state/state-native/v1/beacon_state_mainnet.go
  beacon-chain/state/state-native/v1/beacon_state_mainnet_test.go
  beacon-chain/state/state-native/v1/beacon_state_minimal.go
  beacon-chain/state/state-native/v1/beacon_state_minimal_test.go
  beacon-chain/state/state-native/v1/generated.ssz.go
  beacon-chain/state/state-native/v1/getters_attestation.go
  beacon-chain/state/state-native/v1/getters_block.go
  beacon-chain/state/state-native/v1/getters_block_test.go
  beacon-chain/state/state-native/v1/getters_checkpoint.go
  beacon-chain/state/state-native/v1/getters_eth1.go
  beacon-chain/state/state-native/v1/getters_misc.go
  beacon-chain/state/state-native/v1/getters_randao.go
  beacon-chain/state/state-native/v1/getters_state.go
  beacon-chain/state/state-native/v1/getters_test.go
  beacon-chain/state/state-native/v1/getters_validator.go
  beacon-chain/state/state-native/v1/proofs.go
  beacon-chain/state/state-native/v1/references_test.go
  beacon-chain/state/state-native/v1/setters_attestation.go
  beacon-chain/state/state-native/v1/setters_attestation_test.go
  beacon-chain/state/state-native/v1/setters_block.go
  beacon-chain/state/state-native/v1/setters_checkpoint.go
  beacon-chain/state/state-native/v1/setters_eth1.go
  beacon-chain/state/state-native/v1/setters_misc.go
  beacon-chain/state/state-native/v1/setters_randao.go
  beacon-chain/state/state-native/v1/setters_state.go
  beacon-chain/state/state-native/v1/setters_validator.go
  beacon-chain/state/state-native/v1/state_test.go
  beacon-chain/state/state-native/v1/state_trie.go
  beacon-chain/state/state-native/v1/types.go
  beacon-chain/state/state-native/v1/types_test.go
  deps.bzl
  encoding/bytesutil/bytes.go
  encoding/bytesutil/bytes_test.go
  go.mod
  go.sum
  hack/update-go-ssz.sh
  nogo_config.json
Labels: Ready For Review, OKR Item

#10112 Make Balance Trie Computation Default
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#10118 Add blockchain store for checkpoints
  beacon-chain/blockchain/store/BUILD.bazel
  beacon-chain/blockchain/store/doc.go
  beacon-chain/blockchain/store/setter_getter.go
  beacon-chain/blockchain/store/setter_getter_test.go
  beacon-chain/blockchain/store/type.go
Labels: Ready For Review, OK to merge

#10114 Extract conditional slot processing to new function
  beacon-chain/blockchain/head_sync_committee_info.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/rpc/eth/validator/validator.go
Labels: Ready For Review, OK to merge, Cleanup

#10125 Use store in blockchain service
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/store/BUILD.bazel
  beacon-chain/blockchain/store/new.go
  beacon-chain/blockchain/store/new_test.go
  beacon-chain/blockchain/store/setter_getter.go
  beacon-chain/blockchain/store/setter_getter_test.go
  beacon-chain/blockchain/store/type.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
Labels: Ready For Review, OK to merge

#10130 Add `on_tick` from spec
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/new_slot.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review, OK to merge

#10124 Is optimistic
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/types.go
Labels: Ready For Review, OK to merge, Merge, optmistic-sync

#10128 Unify validator status response in RPC
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_stream.go
Labels: Ready For Review, API

#10121 Native beacon state: v2
  beacon-chain/state/state-native/v1/types.go
  beacon-chain/state/state-native/v2/BUILD.bazel
  beacon-chain/state/state-native/v2/beacon_state_mainnet.go
  beacon-chain/state/state-native/v2/beacon_state_mainnet_test.go
  beacon-chain/state/state-native/v2/beacon_state_minimal.go
  beacon-chain/state/state-native/v2/beacon_state_minimal_test.go
  beacon-chain/state/state-native/v2/generated.ssz.go
  beacon-chain/state/state-native/v2/getters_block.go
  beacon-chain/state/state-native/v2/getters_block_test.go
  beacon-chain/state/state-native/v2/getters_checkpoint.go
  beacon-chain/state/state-native/v2/getters_eth1.go
  beacon-chain/state/state-native/v2/getters_misc.go
  beacon-chain/state/state-native/v2/getters_participation.go
  beacon-chain/state/state-native/v2/getters_randao.go
  beacon-chain/state/state-native/v2/getters_state.go
  beacon-chain/state/state-native/v2/getters_sync_committee.go
  beacon-chain/state/state-native/v2/getters_test.go
  beacon-chain/state/state-native/v2/getters_validator.go
  beacon-chain/state/state-native/v2/proofs.go
  beacon-chain/state/state-native/v2/proofs_test.go
  beacon-chain/state/state-native/v2/setters_block.go
  beacon-chain/state/state-native/v2/setters_checkpoint.go
  beacon-chain/state/state-native/v2/setters_eth1.go
  beacon-chain/state/state-native/v2/setters_misc.go
  beacon-chain/state/state-native/v2/setters_participation.go
  beacon-chain/state/state-native/v2/setters_randao.go
  beacon-chain/state/state-native/v2/setters_state.go
  beacon-chain/state/state-native/v2/setters_sync_committee.go
  beacon-chain/state/state-native/v2/setters_test.go
  beacon-chain/state/state-native/v2/setters_validator.go
  beacon-chain/state/state-native/v2/state_trie.go
  beacon-chain/state/state-native/v2/state_trie_test.go
  beacon-chain/state/state-native/v2/types.go
  nogo_config.json
Labels: Ready For Review, OKR Item

#10140 Fix native state imports
  beacon-chain/state/state-native/v2/BUILD.bazel
  beacon-chain/state/state-native/v2/beacon_state_mainnet.go
  beacon-chain/state/state-native/v2/beacon_state_minimal.go
  beacon-chain/state/state-native/v2/getters_validator.go
  beacon-chain/state/state-native/v2/state_trie.go
Labels: Ready For Review, OK to merge

#10137 Fix Fork Choice prunning
  beacon-chain/forkchoice/protoarray/errors.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/vote_test.go
Labels: OK to merge

#10145 Fix Checking of Minimal Preset
  config/params/loader.go
Labels: Ready For Review

#10142 Remove unused code
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
Labels: OK to merge

#10097 Bellatrix sync changes
  beacon-chain/sync/rpc_chunked_response.go
  beacon-chain/sync/rpc_chunked_response_test.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review, OK to merge, Merge

#10144 State balance cache: handle input zeros
  beacon-chain/blockchain/state_balance_cache.go
  beacon-chain/blockchain/state_balance_cache_test.go
Labels: Ready For Review, OK to merge

#10063 go 1.18 fuzz tests: initial testing
  beacon-chain/p2p/pubsub_fuzz_test.go
  encoding/ssz/htrutils_fuzz_test.go
Labels: Ready For Review, OK to merge

#10083 Fork Choice Proposer Boost Changes
  beacon-chain/blockchain/new_slot.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/proposer_boost.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/config.go
  config/params/loader_test.go
  config/params/mainnet_config.go
Labels: Ready For Review, Priority: High, OK to merge

#10151 Update fuzzbuzz.yaml
  fuzzbuzz.yaml
Labels: OK to merge

#10064 Update rules_go to v0.29.0
  BUILD.bazel
  WORKSPACE
  third_party/io_bazel_rules_go.patch
  tools/analyzers/comparesame/BUILD.bazel
  tools/analyzers/cryptorand/BUILD.bazel
  tools/analyzers/errcheck/BUILD.bazel
  tools/analyzers/featureconfig/BUILD.bazel
  tools/analyzers/ineffassign/BUILD.bazel
  tools/analyzers/interfacechecker/BUILD.bazel
  tools/analyzers/maligned/BUILD.bazel
  tools/analyzers/nop/BUILD.bazel
  tools/analyzers/properpermissions/BUILD.bazel
  tools/analyzers/recursivelock/BUILD.bazel
  tools/analyzers/shadowpredecl/BUILD.bazel
  tools/analyzers/slicedirect/BUILD.bazel
Labels: Ready For Review, OK to merge

#10157 Fix P2P Test
  beacon-chain/p2p/broadcaster_test.go
Labels: Ready For Review, OK to merge

#10129 Update synced tips
  beacon-chain/forkchoice/protoarray/errors.go
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
Labels: Ready For Review, OK to merge, Merge, optmistic-sync

#10159 Implement fork choice spec tests
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/new_slot.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/process_attestation.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/cache/depositcache/BUILD.bazel
  beacon-chain/forkchoice/BUILD.bazel
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/state/stategen/BUILD.bazel
  testing/spectest/mainnet/altair/forkchoice/BUILD.bazel
  testing/spectest/mainnet/altair/forkchoice/forkchoice_test.go
  testing/spectest/mainnet/phase0/forkchoice/BUILD.bazel
  testing/spectest/mainnet/phase0/forkchoice/forkchoice_test.go
  testing/spectest/minimal/altair/forkchoice/BUILD.bazel
  testing/spectest/minimal/altair/forkchoice/forkchoice_test.go
  testing/spectest/minimal/phase0/forkchoice/BUILD.bazel
  testing/spectest/minimal/phase0/forkchoice/forkchoice_test.go
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/runner.go
  testing/spectest/shared/common/forkchoice/service.go
  testing/spectest/shared/common/forkchoice/type.go
Labels: Ready For Review, OK to merge, OKR Item
