Repository OffchainLabs/prysm, pull requests merged in 2022-04, with the labels that each got.

#10466 Save head after FCU
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  testing/spectest/shared/common/forkchoice/runner.go
Labels: Ready For Review, OK to merge, Merge

#10438 Move Engine API to Powchain and Consolidate Connection Management
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/pow_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/auth.go
  beacon-chain/powchain/auth_test.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/check_transition_config.go
  beacon-chain/powchain/check_transition_config_test.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/engine-api-client/v1/BUILD.bazel
  beacon-chain/powchain/engine-api-client/v1/mocks/BUILD.bazel
  beacon-chain/powchain/engine-api-client/v1/options.go
  beacon-chain/powchain/engine_client.go
  beacon-chain/powchain/engine_client_test.go
  beacon-chain/powchain/errors.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/metrics.go
  beacon-chain/powchain/options.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/powchain/testing/BUILD.bazel
  beacon-chain/powchain/testing/mock_engine_client.go
  beacon-chain/powchain/testing/mock_powchain.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  cmd/beacon-chain/powchain/options.go
Labels: Ready For Review

#10350 process the optimistic blocks whose parent are optimistic too
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: OK to merge

#10479 Fix execution payload field names in API Middleware
  beacon-chain/rpc/apimiddleware/structs.go
Labels: Ready For Review, OK to merge, API

#10482 RPC: GetValidatorPerformance for Bellatrix
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
Labels: Bug, Ready For Review

#10480 Sync: process pending block with optimistic parent
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
Labels: Ready For Review, OK to merge, Merge

#10437 Enable Bellatrix E2E
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/powchain/service.go
  config/params/testnet_e2e_config.go
  deps.bzl
  go.mod
  go.sum
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/eth1/BUILD.bazel
  testing/endtoend/components/eth1/miner.go
  testing/endtoend/components/eth1/node.go
  testing/endtoend/components/eth1/node_set.go
  testing/endtoend/components/eth1/transactions.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/deps.bzl
  testing/endtoend/endtoend_test.go
  testing/endtoend/evaluators/operations.go
  testing/endtoend/evaluators/validator.go
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/params/params.go
  testing/endtoend/params/params_test.go
  testing/endtoend/static-files/eth1/genesis.json
  testing/endtoend/types/types.go
Labels: Ready For Review, OK to merge, E2E Tests, Merge

#10464 Optimistic check: handle zeros check point root
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
Labels: Bug, Ready For Review, OK to merge, Merge

#10430 Add Lock Analyzer
  beacon-chain/forkchoice/protoarray/store.go
  tools/analyzers/recursivelock/analyzer.go
  tools/analyzers/recursivelock/testdata/badlockswithmethods.go
  tools/analyzers/recursivelock/testdata/complexlocks.go
  tools/analyzers/recursivelock/testdata/nonrlocks.go
  tools/analyzers/recursivelock/testdata/types.go
Labels: Ready For Review, OK to merge

#10463 save origin block root before finalize
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/wss.go
  beacon-chain/db/kv/wss_test.go
Labels: OK to merge

#10485 Use correct head for `notifyForkchoiceUpdate`
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service_norace_test.go
Labels: Bug, Ready For Review

#10439 Remove synced tips and use last valid hash
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/forkchoice/doubly-linked-tree/errors.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/node.go
  beacon-chain/forkchoice/doubly-linked-tree/node_test.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/errors.go
  beacon-chain/forkchoice/protoarray/helpers.go
  beacon-chain/forkchoice/protoarray/metrics.go
  beacon-chain/forkchoice/protoarray/node.go
  beacon-chain/forkchoice/protoarray/node_test.go
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/forkchoice/protoarray/vote_test.go
Labels: Ready For Review, OK to merge, Merge, Optimistic-sync

#10399 Remove invalid nodes
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/error.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_summary.go
  beacon-chain/db/kv/state_summary_cache.go
  beacon-chain/db/kv/state_summary_test.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/state/stategen/epoch_boundary_state_cache.go
  beacon-chain/state/stategen/epoch_boundary_state_cache_test.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/mock/mock.go
  beacon-chain/state/stategen/service.go
Labels: Merge

#10488 Fix receipts root field name in API Middleware
  beacon-chain/rpc/apimiddleware/structs.go
Labels: Ready For Review, OK to merge, API

#10481 Payload ID caching
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/blockchain/optimistic_sync_test.go
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_norace_test.go
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/payload_id.go
  beacon-chain/cache/payload_id_test.go
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/core/helpers/beacon_committee_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/service.go
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, Merge

#10490 web3signer: fixes json altair block
  validator/keymanager/remote-web3signer/v1/web3signer_types.go
Labels: Bug, API, Web3Signer

#10486 Fix Issues From Multiclient E2E
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/eth1/node.go
  testing/endtoend/endtoend_test.go
Labels: Ready For Review, OK to merge, E2E Tests, Merge

#10492 Deal with node balance underflow
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/errors.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/doubly-linked-tree/metrics.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/metrics.go
  beacon-chain/forkchoice/protoarray/store.go
Labels: OK to merge

#10498 Proper Connection Management for ETH JSON-RPC Client for Startup and Runtime
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/rpc_connection.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/powchain/testing/mock_powchain.go
  cmd/beacon-chain/flags/base.go
Labels: Ready For Review, Priority: High, Merge, Execution Engine

#10501 Set Auth Differently In Our Powchain Constructor
  beacon-chain/powchain/BUILD.bazel
  beacon-chain/powchain/check_transition_config.go
  beacon-chain/powchain/options.go
  beacon-chain/powchain/rpc_connection.go
  beacon-chain/powchain/service.go
  cmd/beacon-chain/powchain/options.go
  network/BUILD.bazel
  network/auth.go
  network/auth_test.go
  network/endpoint.go
  testing/endtoend/components/beacon_node.go
Labels: Ready For Review, Merge

#10503 Fix optimistic logging
  beacon-chain/blockchain/optimistic_sync.go
Labels: OK to merge

#10505 Fetch Non Finalized Deposits Better
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/cache/depositcache/deposits_cache_test.go
  beacon-chain/deterministic-genesis/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
Labels: Ready For Review

#10496 Can prune nodes from canonical and payload maps
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
Labels: Bug, Ready For Review, OK to merge

#10509 Save state to DB after proposer boost
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge

#10302 Remote Key Manager API(web3signer)
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.pb.gw.go
  proto/eth/service/key_management.proto
  validator/client/service.go
  validator/client/validator.go
  validator/keymanager/BUILD.bazel
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/keymanager_test.go
  validator/keymanager/types.go
  validator/keymanager/types_test.go
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/apimiddleware/endpoint_factory.go
  validator/rpc/apimiddleware/structs.go
  validator/rpc/apimiddleware/structs_test.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
Labels: Enhancement, API, Web3Signer, Keymanager-API

#10504 Metrics tracking EE VALID/SYNCING/INVALID response counter
  beacon-chain/blockchain/metrics.go
  beacon-chain/blockchain/optimistic_sync.go
  beacon-chain/forkchoice/doubly-linked-tree/metrics.go
  beacon-chain/forkchoice/doubly-linked-tree/node.go
  beacon-chain/forkchoice/protoarray/metrics.go
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
Labels: Ready For Review, OK to merge, Merge

#10500 Move `GetTerminalBlockHash` to powchain engine
  beacon-chain/powchain/engine_client.go
  beacon-chain/powchain/engine_client_test.go
  beacon-chain/powchain/testing/BUILD.bazel
  beacon-chain/powchain/testing/mock_engine_client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, OK to merge, Cleanup

#10511 Fix Nasty Finalization Bug
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: Bug, Ready For Review, Priority: High

#10123 e2e: Provide e2e config yaml to web3signer
  config/params/BUILD.bazel
  config/params/loader_test.go
  config/params/testdata/e2e_config.yaml
  testing/endtoend/BUILD.bazel
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/validator.go
  testing/endtoend/components/web3remotesigner.go
  testing/endtoend/components/web3remotesigner_test.go
  testing/endtoend/deps.bzl
  testing/endtoend/endtoend_test.go
  testing/endtoend/minimal_e2e_test.go
Labels: Ready For Review, OK to merge, E2E Tests, Web3Signer

#10516 Use forkchoice first when checking canonical status
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review

#10518 Update to 1.17.9
  WORKSPACE
Labels: Ready For Review, OK to merge

#10517 Handle Finalized Deposit Insertion Better
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/cache/depositcache/deposits_cache_test.go
Labels: Ready For Review, Priority: High

#10502 Handle nil execution block response when logging TTD
  beacon-chain/powchain/check_transition_config.go
  beacon-chain/powchain/check_transition_config_test.go
  proto/engine/v1/json_marshal_unmarshal_test.go
Labels: Ready For Review, ux

#10527 Static analysis: gocognit
  BUILD.bazel
  deps.bzl
  go.mod
  go.sum
  nogo_config.json
  tools/analyzers/gocognit/BUILD.bazel
  tools/analyzers/gocognit/CognitiveComplexity.pdf
  tools/analyzers/gocognit/README.md
  tools/analyzers/gocognit/analyzer.go
Labels: Ready For Review, OK to merge, Cleanup, Tools

#10524 Fix Another Off By 1 In Our Finalized Trie
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/cache/depositcache/deposits_cache_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: Bug, Ready For Review, OK to merge

#10523 Simplify Initial Sync
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
Labels: OK to merge, Sync, Cleanup

#10522 Remove feature and flag Pyrmont testnet
  cmd/validator/accounts/accounts.go
  cmd/validator/slashing-protection/slashing-protection.go
  cmd/validator/wallet/wallet.go
  config/features/config.go
  config/features/config_test.go
  config/features/deprecated_flags.go
  config/features/flags.go
  config/params/BUILD.bazel
  config/params/testnet_pyrmont_config.go
  config/params/values.go
  tools/eth1voting/README.md
  tools/eth1voting/main.go
  validator/accounts/accounts_exit.go
Labels: OK to merge

#10532 Service constructors and `Start()` - better separation of concerns
  beacon-chain/deterministic-genesis/service.go
  beacon-chain/monitor/service.go
  beacon-chain/node/node.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/service.go
  validator/client/service.go
  validator/client/service_test.go
  validator/rpc/health_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10535 Rename receipt root to receipts root
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
  beacon-chain/core/execution/upgrade.go
  beacon-chain/core/execution/upgrade_test.go
  beacon-chain/state/state-native/v3/setters_test.go
  beacon-chain/state/v3/setters_test.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/eth/v2/generated.ssz.go
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v1alpha1_to_v2_test.go
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
  proto/prysm/v1alpha1/generated.ssz.go
  testing/util/bellatrix_state.go
  testing/util/block.go
  testing/util/state.go
Labels: Ready For Review, OK to merge

#10529 Add process payload header
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  proto/prysm/v1alpha1/block/block_interfaces.go
  proto/prysm/v1alpha1/block/mock/block.go
  proto/prysm/v1alpha1/wrapper/beacon_block_altair.go
  proto/prysm/v1alpha1/wrapper/beacon_block_altair_test.go
  proto/prysm/v1alpha1/wrapper/beacon_block_bellatrix.go
  proto/prysm/v1alpha1/wrapper/beacon_block_bellatrix_test.go
  proto/prysm/v1alpha1/wrapper/beacon_block_phase0.go
  proto/prysm/v1alpha1/wrapper/blinded_beacon_block_bellatrix.go
  proto/prysm/v1alpha1/wrapper/blinded_beacon_block_bellatrix_test.go
Labels: Ready For Review, OK to merge, MEV

#10537 Rename optimistic_sync.go to execution_engine.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10538 misleading comment in receive_block.go
  beacon-chain/blockchain/receive_block.go
Labels: OK to merge

#10520 Clean up batch process block
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge, Cleanup

#10542 gocognit: Lower complexity threshold to 100, fix a few complexity issues
  beacon-chain/db/kv/migration_state_validators.go
  beacon-chain/db/kv/state.go
  nogo_config.json
  tools/analyzers/gocognit/analyzer.go
Labels: Ready For Review, OK to merge, Cleanup

#10540 Fix E2E Failures
  beacon-chain/powchain/block_reader.go
  config/params/testdata/e2e_config.yaml
  config/params/testnet_e2e_config.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/params/params.go
  testing/endtoend/static-files/eth1/genesis.json
  validator/client/validator.go
Labels: Ready For Review, OK to merge

#10547 Remove Proposer Selection Feature
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_utils_bench_test.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#10423 Update libp2p to latest release
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/context.go
  beacon-chain/sync/context_test.go
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review, OK to merge

#10548 Graduate Optimized Get Block Feature
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_eth1data.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, Cleanup

#10549 Graduate Optimized Balance Update Feature
  beacon-chain/core/epoch/BUILD.bazel
  beacon-chain/core/epoch/epoch_processing.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, OK to merge, Cleanup

#10550 Graduate Active Balance Cache Feature
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/active_balance.go
  beacon-chain/cache/active_balance_test.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, OK to merge, Cleanup

#10555 Suggested Fee Recipient : bug fix
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Bug, OK to merge, Merge

#10558 Add lock to `PeerStatusScorer.SetHeadSlot`
  beacon-chain/p2p/peers/scorers/peer_status.go
Labels: Ready For Review, OK to merge

#10559 Update Beacon API's Postman collection to 2.2.0
  hack/beacon-node-api/beacon-node-api.postman-collection.json
Labels: Ready For Review, OK to merge

#10560 Use the T.TempDir and B.TempDir to create temp dirs for testing
  beacon-chain/node/node_test.go
  cmd/beacon-chain/powchain/options_test.go
  cmd/validator/slashing-protection/import_export_test.go
  io/file/fileutil_test.go
  tools/http-request-sink/main_test.go
  tools/interop/split-keys/main_test.go
  validator/db/kv/attester_protection_test.go
  validator/rpc/auth_token_test.go
  validator/rpc/wallet_test.go
Labels: OK to merge, Cleanup

#10475 Add in State Slot for Sync Committee Cache
  beacon-chain/core/helpers/sync_committee.go
  beacon-chain/core/helpers/sync_committee_test.go
Labels: Ready For Review, OK to merge, Merge

#10561 Fix Transaction Pool in E2E
  testing/endtoend/components/eth1/miner.go
  testing/endtoend/components/eth1/node.go
  testing/endtoend/components/eth1/transactions.go
Labels: Ready For Review, OK to merge, E2E Tests

#10526 Move validate merge transition block outside of notify new payload
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/blocks/payload.go
Labels: Ready For Review, OK to merge, Cleanup, Merge

#10513 E2E: switching to run time generated yaml for web3signer
  config/params/testnet_e2e_config.go
  testing/endtoend/BUILD.bazel
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/web3remotesigner.go
  testing/endtoend/components/web3remotesigner_test.go
  testing/endtoend/endtoend_test.go
Labels: OK to merge, E2E Tests, Web3Signer

#10533 Engine API Proxy Utility for Merge Testing
  testing/middleware/engine-api-proxy/BUILD.bazel
  testing/middleware/engine-api-proxy/options.go
  testing/middleware/engine-api-proxy/proxy.go
  testing/middleware/engine-api-proxy/proxy_test.go
Labels: Ready For Review, OK to merge, Merge, Execution Engine

#10552 Graduate Balance Trie Feature
  beacon-chain/state/state-native/v1/BUILD.bazel
  beacon-chain/state/state-native/v1/setters_misc.go
  beacon-chain/state/state-native/v1/state_trie.go
  beacon-chain/state/state-native/v1/state_trie_test.go
  beacon-chain/state/state-native/v2/BUILD.bazel
  beacon-chain/state/state-native/v2/setters_misc.go
  beacon-chain/state/state-native/v2/state_trie.go
  beacon-chain/state/state-native/v2/state_trie_test.go
  beacon-chain/state/state-native/v3/BUILD.bazel
  beacon-chain/state/state-native/v3/setters_misc.go
  beacon-chain/state/state-native/v3/state_trie.go
  beacon-chain/state/state-native/v3/state_trie_test.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/setters_misc.go
  beacon-chain/state/v1/state_trie.go
  beacon-chain/state/v1/state_trie_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/setters_misc.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v2/state_trie_test.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/setters_misc.go
  beacon-chain/state/v3/state_trie.go
  beacon-chain/state/v3/state_trie_test.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
  testing/spectest/mainnet/altair/epoch_processing/BUILD.bazel
  testing/spectest/mainnet/altair/epoch_processing/epoch_processing_test.go
  testing/spectest/mainnet/altair/random/BUILD.bazel
  testing/spectest/mainnet/altair/random/random_test.go
  testing/spectest/mainnet/altair/rewards/BUILD.bazel
  testing/spectest/mainnet/altair/rewards/rewards_test.go
  testing/spectest/mainnet/altair/sanity/BUILD.bazel
  testing/spectest/mainnet/altair/sanity/sanity_test.go
  testing/spectest/mainnet/phase0/epoch_processing/BUILD.bazel
  testing/spectest/mainnet/phase0/epoch_processing/epoch_processing_test.go
  testing/spectest/mainnet/phase0/random/BUILD.bazel
  testing/spectest/mainnet/phase0/random/random_test.go
  testing/spectest/mainnet/phase0/rewards/BUILD.bazel
  testing/spectest/mainnet/phase0/rewards/rewards_test.go
  testing/spectest/mainnet/phase0/sanity/BUILD.bazel
  testing/spectest/mainnet/phase0/sanity/sanity_test.go
Labels: Ready For Review, Cleanup

#10563 Disable Transaction Evaluator
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/minimal_e2e_test.go
Labels: Ready For Review, OK to merge, E2E Tests, Execution Engine

#10543 Fee Recipient: API/logs run only after bellatrix
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Bug, OK to merge, Merge, ux

#10331 Blinded block APIs
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  proto/engine/v1/BUILD.bazel
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/generated.ssz.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
  proto/eth/v2/BUILD.bazel
  proto/eth/v2/beacon_block.pb.go
  proto/eth/v2/beacon_block.proto
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/eth/v2/generated.ssz.go
  proto/eth/v2/validator.pb.go
  proto/eth/v2/validator.proto
  proto/migration/BUILD.bazel
  proto/migration/v1alpha1_to_v1_test.go
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v1alpha1_to_v2_test.go
  testing/util/block.go
  testing/util/block_test.go
  testing/util/merge.go
Labels: Ready For Review, API, Merge

#10556 Don't mark block as bad with unknown ee error
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review, OK to merge, Merge

#10564 Add proposer index and graffiti to received block log
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review, OK to merge, ux

#10557 Add lock around reading eth1data
  beacon-chain/powchain/block_reader.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
Labels: Ready For Review, OK to merge

#10553 Graduate Batch Gossip Verification Feature
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_sync_committee_message.go
  beacon-chain/sync/validate_sync_contribution_proof.go
  beacon-chain/sync/validate_sync_contribution_proof_test.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, Cleanup

#10572 Fix Broken E2E Runs
  testing/endtoend/BUILD.bazel
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/multiclient_e2e_test.go
Labels: Ready For Review, Priority: High, OK to merge

#10567 Add support for blst modern builds on linux amd64
  third_party/blst/blst.BUILD
Labels: Ready For Review, OK to merge

#10571 Fee Recipient: improve logs
  validator/client/validator.go
Labels: Ready For Review, OK to merge, ux

#10566 Code cleanup in `blockchain` module
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/store/new.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/blockchain/weak_subjectivity_checks.go
  beacon-chain/rpc/prysm/v1alpha1/debug/forkchoice.go
  beacon-chain/rpc/prysm/v1alpha1/debug/forkchoice_test.go
  beacon-chain/rpc/prysm/v1alpha1/debug/server.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review, OK to merge, Cleanup

#10574 Cleanup Discarded Connections Correctly
  beacon-chain/powchain/rpc_connection.go
  beacon-chain/powchain/service.go
Labels: Bug, Ready For Review, Priority: High, OK to merge

#10534 Move ETH2 Types Into Prysm
  consensus-types/primitives/BUILD.bazel
  consensus-types/primitives/committee_index.go
  consensus-types/primitives/committee_index_test.go
  consensus-types/primitives/domain.go
  consensus-types/primitives/domain_test.go
  consensus-types/primitives/epoch.go
  consensus-types/primitives/epoch_test.go
  consensus-types/primitives/slot.go
  consensus-types/primitives/slot_test.go
  consensus-types/primitives/sszbytes.go
  consensus-types/primitives/sszbytes_test.go
  consensus-types/primitives/sszuint64.go
  consensus-types/primitives/sszuint64_test.go
  consensus-types/primitives/validator.go
  consensus-types/primitives/validator_test.go
  math/BUILD.bazel
  math/math_helper.go
  math/math_helper_test.go
Labels: Ready For Review, OK to merge

#10554 Refactor validator accounts list to remove cli context dependency
  cmd/validator/accounts/BUILD.bazel
  cmd/validator/accounts/accounts.go
  cmd/validator/accounts/list.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_list.go
  validator/accounts/cli_manager.go
  validator/accounts/cli_options.go
  validator/accounts/iface/BUILD.bazel
  validator/accounts/wallet/BUILD.bazel
  validator/client/BUILD.bazel
  validator/keymanager/BUILD.bazel
Labels: OK to merge

#10581 Max Epoch Helper from Eth2-Types
  consensus-types/primitives/BUILD.bazel
  consensus-types/primitives/epoch.go
  consensus-types/primitives/epoch_test.go
Labels: Ready For Review, OK to merge

#10562 Fallback To Rebuilding Deposit Tries
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits_test.go
Labels: Ready For Review, OK to merge

#10582 Fix Doppelganger Check
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go
Labels: Ready For Review, Priority: High, OK to merge, v2.1.0-bug

#10583 p2p: Fix pubsub fuzz test
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/pubsub_fuzz_test.go
Labels: Ready For Review, OK to merge, Fuzz

#10591 Debug log when new head is not in db
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review, ux
