Repository OffchainLabs/prysm, pull requests merged in 2022-05, with the labels that each got.

#10594 Forkchoice use parent hash when removing invalid blocks
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/forkchoice/doubly-linked-tree/errors.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/optimistic_sync.go
  beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
Labels: Ready For Review, Merge, Optimistic-sync

#10597 remove equivocating votes from forkchoice
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/helpers.go
  beacon-chain/forkchoice/protoarray/helpers_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/types.go
Labels: Ready For Review, OK to merge, Spec

#10603 Use remove equivocating validators
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
Labels: Ready For Review, OK to merge, Spec

#10510 notifyForkchoiceUpdate can prune invalid blocks
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
Labels: Ready For Review, OK to merge, Merge

#10610 Revert "Simplify Initial Sync (#10523)"
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
Labels: Ready For Review, OK to merge

#10606 Use notify engine if changed head method
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge

#10604 Warn Users if EE Returns Unexpected Fee Recipient Address
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
Labels: Ready For Review, OK to merge, Merge

#10580 Handle blind block for DB
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/key.go
  beacon-chain/db/kv/schema.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  consensus-types/wrapper/blinded_beacon_block_bellatrix.go
  consensus-types/wrapper/blinded_beacon_block_bellatrix_test.go
  runtime/version/fork.go
  testing/util/merge.go
Labels: Ready For Review, OK to merge, Merge

#10611 No timeout for API events
  beacon-chain/rpc/apimiddleware/custom_handlers.go
Labels: Ready For Review, OK to merge, API

#10614 Update consensus spec version to v1.1.10
  README.md
Labels: Ready For Review, OK to merge, Spec

#10609 More Useful Log When Auth Fails to Execution Client
  beacon-chain/powchain/engine_client.go
Labels: Ready For Review, OK to merge, Merge, ux

#10600 Fix Flaky Sync Committee Evaluator
  testing/endtoend/evaluators/validator.go
Labels: Ready For Review, OK to merge

#10613 Don't mark undefined ee error block bad for regular processing
  beacon-chain/sync/subscriber_beacon_blocks.go
Labels: Ready For Review, OK to merge

#10616 Spectest: refactor forkchoice helper
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/builder.go
  testing/spectest/shared/common/forkchoice/builder_test.go
  testing/spectest/shared/common/forkchoice/runner.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: OK to merge

#10618 fuzz: build with -tags=fuzz,blst_disabled
  .github/workflows/go.yml
  crypto/bls/blst/stub.go
Labels: Ready For Review, OK to merge, Fuzz

#10592 Refactor and use has_block getter
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10620 Fix `isProcessedBlock` order of operation
  beacon-chain/sync/initial-sync/round_robin.go
Labels: OK to merge

#10608 Use Single Beacon Block Wrapper Function Across Prysm
  beacon-chain/blockchain/log_test.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/blocks/payload_test.go
  beacon-chain/monitor/process_attestation_test.go
  beacon-chain/monitor/process_block_test.go
  beacon-chain/monitor/process_exit_test.go
  beacon-chain/monitor/process_sync_committee_test.go
  consensus-types/interfaces/utils_test.go
  consensus-types/wrapper/beacon_block.go
  consensus-types/wrapper/beacon_block_altair.go
  consensus-types/wrapper/beacon_block_altair_test.go
  consensus-types/wrapper/beacon_block_bellatrix.go
  consensus-types/wrapper/beacon_block_bellatrix_test.go
  consensus-types/wrapper/beacon_block_phase0.go
  consensus-types/wrapper/blinded_beacon_block_bellatrix.go
  consensus-types/wrapper/blinded_beacon_block_bellatrix_test.go
  tools/eth1voting/main.go
  validator/client/propose_test.go
Labels: Enhancement, Ready For Review, Cleanup

#10127 Update Batch Verification Routine
  beacon-chain/sync/batch_verifier.go
  beacon-chain/sync/metrics.go
  config/features/config.go
  config/features/flags.go
  crypto/bls/BUILD.bazel
  crypto/bls/bls.go
  crypto/bls/blst/public_key.go
  crypto/bls/blst/public_key_test.go
  crypto/bls/blst/signature.go
  crypto/bls/blst/signature_test.go
  crypto/bls/blst/stub.go
  crypto/bls/common/interface.go
  crypto/bls/signature_batch.go
  crypto/bls/signature_batch_test.go
Labels: Enhancement, Ready For Review, OK to merge

#10619 fuzz: Fix tests with fuzz tags
  beacon-chain/cache/active_balance_test.go
  beacon-chain/cache/committee_fuzz_test.go
  beacon-chain/cache/committee_test.go
  beacon-chain/cache/proposer_indices.go
  beacon-chain/cache/proposer_indices_disabled.go
  beacon-chain/cache/proposer_indices_test.go
  beacon-chain/core/helpers/validators_test.go
  crypto/bls/blst/BUILD.bazel
Labels: Ready For Review, OK to merge, Fuzz

#10622 Graduate Orphaned Attestation Insertion Feature
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#10626 Remove junk metadata file
  .gitignore
  beacon-chain/p2p/metaData
Labels: Ready For Review, OK to merge, Cleanup

#10630 Checkpoint sync fixes
  api/client/beacon/checkpoint.go
  api/client/beacon/client.go
  api/client/beacon/client_test.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/wss_test.go
Labels: OK to merge

#10627 Use justified hash as safe block hash
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review, OK to merge, Merge, Spec

#10633 Change log when head changes
  beacon-chain/blockchain/receive_attestation.go
Labels: OK to merge

#10636 Move head change attestation log
  beacon-chain/blockchain/receive_attestation.go
Labels: OK to merge, ux

#10643 Remove unused method
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
Labels: Ready For Review

#10656 simplify config names, use strings
  beacon-chain/db/kv/genesis_test.go
  beacon-chain/db/kv/wss_test.go
  beacon-chain/state/genesis/genesis.go
  beacon-chain/state/genesis/genesis_test.go
  config/params/BUILD.bazel
  config/params/mainnet_config.go
  config/params/minimal_config.go
  config/params/registry.go
  config/params/testnet_e2e_config.go
  config/params/testnet_prater_config.go
  config/params/values.go
  encoding/ssz/detect/configfork_test.go
  network/forks/ordered_test.go
  validator/accounts/accounts_exit.go
Labels: OK to merge

#10615 Insert over-the-wire slashing to forkchoice
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_attester_slashing.go
Labels: Ready For Review, OK to merge, Spec

#10649 Perform Request Size Limiting When Caching Eth1 Headers
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
Labels: Ready For Review, OK to merge, Merge

#10660 Fix Multiclient E2E Runs
  testing/endtoend/evaluators/validator.go
Labels: Ready For Review, E2E Tests, Merge

#10652 Improvements to `powchain` package
  beacon-chain/powchain/block_reader.go
  beacon-chain/powchain/block_reader_test.go
  beacon-chain/powchain/errors.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/powchain/log_processing_test.go
  beacon-chain/powchain/service.go
  beacon-chain/powchain/service_test.go
  beacon-chain/powchain/testing/mock_faulty_powchain.go
  beacon-chain/powchain/testing/mock_powchain.go
Labels: Ready For Review, OK to merge, Cleanup

#10662 fuzz: Add fuzz tests for sparse merkle trie
  beacon-chain/blockchain/service_test.go
  beacon-chain/cache/depositcache/deposits_cache_test.go
  beacon-chain/core/altair/deposit_test.go
  beacon-chain/core/blocks/deposit_test.go
  beacon-chain/core/helpers/genesis.go
  beacon-chain/powchain/deposit_test.go
  beacon-chain/powchain/log_processing.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go
  container/trie/BUILD.bazel
  container/trie/sparse_merkle.go
  container/trie/sparse_merkle_test.go
  container/trie/sparse_merkle_trie_fuzz_test.go
  container/trie/testdata/fuzz/FuzzSparseMerkleTrie_HashTreeRoot/5838cdfae7b16cde2707c04599b62223e7bade8dafdd8a1c53b8f881e8f79d99
  container/trie/testdata/fuzz/FuzzSparseMerkleTrie_Insert/d863478086b8f8e8c854ec74d4d5360ffbe979064b58f619eb3d5fddfdae64c8
  container/trie/testdata/fuzz/FuzzSparseMerkleTrie_MerkleProof/ec4893c52de558dbac9a850e4266850e109a9e6bc6bab59953b2a30027f66a93
  container/trie/testdata/fuzz/FuzzSparseMerkleTrie_VerifyMerkleProofWithDepth/826f574b1f684ccfa610c2db07e0dc5ecfe453c6c95e4597476616ba0358c236
  contracts/deposit/deposit_tree_test.go
  runtime/interop/generate_genesis_state.go
  runtime/interop/generate_genesis_state_test.go
  testing/util/deposits.go
  testing/util/deposits_test.go
Labels: Ready For Review, OK to merge, Fuzz

#10645 Add engine timeout values
  beacon-chain/powchain/engine_client.go
Labels: Ready For Review, OK to merge, Spec

#10607 Cleanup of `stategen` package
  beacon-chain/blockchain/service.go
  beacon-chain/state/stategen/cacher.go
  beacon-chain/state/stategen/epoch_boundary_state_cache.go
  beacon-chain/state/stategen/epoch_boundary_state_cache_test.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/getter_test.go
  beacon-chain/state/stategen/history.go
  beacon-chain/state/stategen/hot_state_cache.go
  beacon-chain/state/stategen/migrate.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/mock_test.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/service.go
  beacon-chain/state/stategen/setter.go
  beacon-chain/state/stategen/setter_test.go
Labels: Ready For Review, OK to merge, Cleanup

#10653 Process atts and update head before proposing
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/beacon/server.go
  beacon-chain/rpc/eth/validator/server.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/server.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_phase0.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/service.go
Labels: Ready For Review, OK to merge, Spec

#10671 Improve `ReceiveBlock`'s comment
  beacon-chain/blockchain/receive_block.go
Labels: Ready For Review, OK to merge, Cleanup

#10657 Cache and use justified and finalized payload block hash
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/new_slot.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/store/setter_getter.go
  beacon-chain/blockchain/store/setter_getter_test.go
  beacon-chain/blockchain/store/type.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
Labels: Ready For Review, OK to merge, Merge

#10375 Add in State Fuzzing
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/state_fuzz_test.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/state_fuzz_test.go
  beacon-chain/state/v2/testdata/fuzz/FuzzV2StateHashTreeRoot/52875ab39ad0eeec927085f3330d00508d015fe3c204b6bc6607296f64ec221c
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/state_fuzz_test.go
Labels: Ready For Review, OK to merge, Fuzz

#10676 Add Sync Block Topic Fuzz Target
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/sync_fuzz_test.go
Labels: Ready For Review, OK to merge, Fuzz

#10677 native-state: Simplify MarshalSSZ
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/ssz.go
Labels: Ready For Review, OK to merge

#10680 Don't return nil with new head
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
Labels: Ready For Review

#10664 Fee recipient: checksum log
  beacon-chain/node/config.go
  beacon-chain/node/config_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/node_test.go
  validator/node/testdata/good-prepare-beacon-proposer-config-badchecksum.json
Labels: OK to merge, Merge, ux

#10682 Add More Block Fuzz Targets
  beacon-chain/sync/sync_fuzz_test.go
Labels: Ready For Review, Fuzz

#10675 regression test off-by-one
  beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync_test.go
Labels: OK to merge

#10651 handle failure to update head
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
Labels: Ready For Review, OK to merge

#10654 Extract `OptimisticSyncFetcher` interface
  beacon-chain/blockchain/chain_info.go
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/eth/beacon/server.go
  beacon-chain/rpc/eth/beacon/state.go
  beacon-chain/rpc/eth/beacon/state_test.go
  beacon-chain/rpc/eth/beacon/sync_committee.go
  beacon-chain/rpc/eth/beacon/sync_committee_test.go
  beacon-chain/rpc/eth/beacon/validator.go
  beacon-chain/rpc/eth/beacon/validator_test.go
  beacon-chain/rpc/eth/debug/debug.go
  beacon-chain/rpc/eth/debug/debug_test.go
  beacon-chain/rpc/eth/debug/server.go
  beacon-chain/rpc/eth/helpers/sync.go
  beacon-chain/rpc/eth/helpers/sync_test.go
  beacon-chain/rpc/eth/validator/server.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee_test.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/service.go
Labels: Ready For Review, OK to merge, Cleanup

#10685 Fix `error.Is` ordering
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
Labels: Bug, Ready For Review, OK to merge

#10668 fuzz: Fix off by one error in sparse merkle trie item insertion
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service_test.go
  beacon-chain/powchain/service.go
  container/trie/BUILD.bazel
  container/trie/sparse_merkle.go
  container/trie/sparse_merkle_test.go
  container/trie/sparse_merkle_trie_fuzz_test.go
  container/trie/testdata/fuzz/FuzzSparseMerkleTrie_Insert/fuzzbuzz-97663548a1e2280a081745e5fa25c289f7121c0b
Labels: Ready For Review, OK to merge, Fuzz

#10663 Allow SSZ-serialized blocks in `publishBlock`
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  config/params/config.go
  encoding/ssz/detect/configfork.go
  network/forks/ordered.go
  network/forks/ordered_test.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v2/beacon_block.pb.go
  proto/eth/v2/beacon_block.proto
  proto/migration/v1alpha1_to_v2_test.go
Labels: Ready For Review, OK to merge, API

#10673 Fix bugs in `/eth/v1/beacon/blinded_blocks`
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/rpc/apimiddleware/structs.go
Labels: Ready For Review, OK to merge, API

#10687 Changes to SSZ handling
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/eth/debug/debug.go
  beacon-chain/rpc/eth/debug/debug_test.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/service/beacon_debug_service.pb.go
  proto/eth/service/beacon_debug_service.proto
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.proto
  proto/eth/v1/beacon_state.pb.go
  proto/eth/v1/beacon_state.proto
  proto/eth/v2/BUILD.bazel
  proto/eth/v2/beacon_block.pb.go
  proto/eth/v2/beacon_block.proto
  proto/eth/v2/ssz.pb.go
  proto/eth/v2/ssz.pb.gw.go
  proto/eth/v2/ssz.proto
Labels: Ready For Review, OK to merge, API

#10688 Blockchain: Use get_block to retrieve block
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/service.go
Labels: Ready For Review, OK to merge, Cleanup

#10646 Remove invalid terminal block error code
  beacon-chain/powchain/engine_client.go
  beacon-chain/powchain/engine_client_test.go
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
Labels: Ready For Review, OK to merge, Spec

#10684 fee-recipient: update error log to warn log
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: OK to merge, ux

#10689 Improve beacon node doesn't have a parent in db logs
  beacon-chain/sync/initial-sync/round_robin.go
Labels: Ready For Review, OK to merge, ux

#10698 Add better debugging logs for validate block p2p pipeline
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review, OK to merge, ux

#10697 SSZ responses for block production
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_handlers_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
Labels: Ready For Review, OK to merge

#10686 Refactor validator accounts delete to remove cli context dependency
  cmd/validator/accounts/BUILD.bazel
  cmd/validator/accounts/accounts.go
  cmd/validator/accounts/delete.go
  cmd/validator/accounts/delete_test.go
  cmd/validator/accounts/list.go
  cmd/validator/accounts/wallet_utils.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_backup.go
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_delete_test.go
  validator/accounts/accounts_exit.go
  validator/accounts/accounts_helper.go
  validator/accounts/cli_manager.go
  validator/accounts/cli_options.go
  validator/accounts/petnames/BUILD.bazel
  validator/keymanager/derived/BUILD.bazel
  validator/keymanager/local/BUILD.bazel
  validator/keymanager/remote/BUILD.bazel
Labels: Ready For Review, OK to merge

#10590 Web3signer: Bellatrix Block
  testing/endtoend/components/validator.go
  testing/endtoend/components/web3remotesigner.go
  testing/endtoend/deps.bzl
  testing/endtoend/endtoend_test.go
  testing/endtoend/minimal_e2e_test.go
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/metrics.go
  validator/keymanager/remote-web3signer/v1/BUILD.bazel
  validator/keymanager/remote-web3signer/v1/mock/BUILD.bazel
  validator/keymanager/remote-web3signer/v1/mock/mocks.go
  validator/keymanager/remote-web3signer/v1/requests.go
  validator/keymanager/remote-web3signer/v1/requests_test.go
  validator/keymanager/remote-web3signer/v1/web3signer_types.go
Labels: OK to merge, Merge, Web3Signer

#10699 Weak subjectivity warning copy update, warn -> info
  beacon-chain/blockchain/weak_subjectivity_checks.go
Labels: Ready For Review, OK to merge

#10700 Add bopsten config and cli flag
  cmd/validator/accounts/accounts.go
  cmd/validator/slashing-protection/slashing-protection.go
  cmd/validator/wallet/wallet.go
  config/features/config.go
  config/features/flags.go
  config/params/BUILD.bazel
  config/params/testnet_ropsten_config.go
  config/params/values.go
Labels: Ready For Review, OK to merge, Merge, ux

#10711 Fix Tests in sync/validate_beacon_blocks.go to Pass for the Right Reasons
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: Ready For Review, OK to merge

#10710 Clean up various warnings
  api/client/beacon/client.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/cache/committee_test.go
  beacon-chain/db/errors.go
  beacon-chain/db/kv/error.go
  beacon-chain/monitor/service_test.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/debug/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/debug/state_test.go
  beacon-chain/rpc/testutil/mock_powchain_info_fetcher.go
  beacon-chain/state/fieldtrie/field_trie.go
  beacon-chain/state/fieldtrie/field_trie_helpers.go
  beacon-chain/state/state-native/custom-types/historical_roots.go
  beacon-chain/state/stategen/mock/mock.go
  consensus-types/primitives/committee_index_test.go
  consensus-types/primitives/slot_test.go
  consensus-types/primitives/validator_test.go
  consensus-types/wrapper/beacon_block_bellatrix_test.go
  contracts/deposit/helper.go
  crypto/bls/blst/signature_test.go
  crypto/bls/signature_batch_test.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/evaluators/validator.go
  testing/util/attestation.go
  validator/accounts/accounts_delete.go
  validator/client/metrics_test.go
  validator/client/service.go
  validator/client/testutil/mock_validator.go
  validator/keymanager/remote-web3signer/v1/custom_mappers.go
  validator/keymanager/remote-web3signer/v1/custom_mappers_test.go
  validator/keymanager/remote-web3signer/v1/mock/mocks.go
  validator/keymanager/remote-web3signer/v1/web3signer_types.go
Labels: Ready For Review, OK to merge, Cleanup

#10717 run e2e for 12 epochs
  testing/endtoend/endtoend_test.go
Labels: OK to merge

#10715 Fix Slasher E2E Flakiness
  beacon-chain/slasher/service.go
Labels: Ready For Review, OK to merge

#10708 Drop Down Expected Sync Participation During Fork
  testing/endtoend/evaluators/validator.go
Labels: Ready For Review, OK to merge, E2E Tests

#10650 Raise Soft File Descriptor Limit Up To The Hard Limit
  cmd/beacon-chain/BUILD.bazel
  cmd/beacon-chain/main.go
  runtime/fdlimits/BUILD.bazel
  runtime/fdlimits/fdlimits.go
  runtime/fdlimits/fdlimits_test.go
Labels: Ready For Review, OK to merge

#10696 Scenario End To End Testing
  testing/endtoend/BUILD.bazel
  testing/endtoend/component_handler_test.go
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/boot_node.go
  testing/endtoend/components/eth1/helpers.go
  testing/endtoend/components/eth1/miner.go
  testing/endtoend/components/eth1/node.go
  testing/endtoend/components/eth1/node_set.go
  testing/endtoend/components/eth1/transactions.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/components/lighthouse_validator.go
  testing/endtoend/components/tracing_sink.go
  testing/endtoend/components/validator.go
  testing/endtoend/components/web3remotesigner.go
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/endtoend_test.go
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
  testing/endtoend/minimal_slashing_e2e_test.go
  testing/endtoend/multiclient_e2e_test.go
  testing/endtoend/types/types.go
Labels: Ready For Review, OK to merge, E2E Tests, Merge

#10706 Encapsulate Fork-Specific Parameters Under BeaconState Interface
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/altair/transition.go
  beacon-chain/state/phase0.go
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/spec_parameters.go
  beacon-chain/state/v1/BUILD.bazel
  beacon-chain/state/v1/spec_parameters.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/spec_parameters.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/spec_parameters.go
Labels: Ready For Review, OK to merge, Cleanup

#10726 Refactor high complexity StreamBlocksAltair
  beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go
Labels: Enhancement, Ready For Review, OK to merge, Cleanup

#10681 More selective on marking block as bad
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/error_test.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/pow_block.go
  beacon-chain/blockchain/pow_block_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review, OK to merge, Ropsten-required

#10728 Add new slot tests
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/new_slot_test.go
Labels: Ready For Review, OK to merge

#10729 Chain info: Return err if checkpoint is nil
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/new_slot.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/store/BUILD.bazel
  beacon-chain/blockchain/store/new_test.go
  beacon-chain/blockchain/store/setter_getter.go
  beacon-chain/blockchain/store/setter_getter_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/blockchain/weak_subjectivity_checks_test.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_peers.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_queue_test.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc_status.go
  beacon-chain/sync/validate_beacon_blocks.go
  testing/spectest/shared/common/forkchoice/builder.go
Labels: Ready For Review, OK to merge, Cleanup

#10707 Remove Unnecessary State Interfaces
  beacon-chain/cache/sync_committee.go
  beacon-chain/cache/sync_committee_disabled.go
  beacon-chain/core/altair/attestation.go
  beacon-chain/core/altair/block.go
  beacon-chain/core/altair/deposit.go
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/altair/epoch_spec.go
  beacon-chain/core/altair/sync_committee.go
  beacon-chain/core/altair/sync_committee_test.go
  beacon-chain/core/altair/transition.go
  beacon-chain/core/altair/upgrade.go
  beacon-chain/core/helpers/sync_committee.go
  beacon-chain/core/transition/altair_transition_no_verify_sig_test.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/db/kv/migration_state_validators_test.go
  beacon-chain/rpc/eth/debug/BUILD.bazel
  beacon-chain/rpc/eth/debug/debug.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/altair.go
  beacon-chain/state/bellatrix.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/state_trie.go
  beacon-chain/state/v2/state_trie.go
  beacon-chain/state/v3/state_trie.go
  proto/migration/v1alpha1_to_v2.go
  testing/spectest/shared/altair/fork/transition.go
  testing/util/altair.go
  testing/util/state.go
  testing/util/sync_aggregate.go
Labels: Ready For Review, OK to merge

#10731 Move BeaconBlockNil Checker Function to Consensus-Types/Wrapper Package
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/init_sync_process_block.go
  beacon-chain/blockchain/pow_block.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/attestation.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/header.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/block.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/backup.go
  beacon-chain/db/kv/finalized_block_roots.go
  beacon-chain/db/kv/state.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/statefetcher/BUILD.bazel
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/history.go
  beacon-chain/state/stategen/replay.go
  beacon-chain/sync/backfill/BUILD.bazel
  beacon-chain/sync/backfill/status.go
  beacon-chain/sync/backfill/status_test.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks.go
  consensus-types/wrapper/beacon_block.go
  testing/endtoend/evaluators/fork.go
Labels: Ready For Review, OK to merge

#10658 Track unrealized justification/finalization in forkchoice
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/errors.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification_test.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/errors.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/forkchoice/protoarray/unrealized_justification.go
  beacon-chain/forkchoice/protoarray/unrealized_justification_test.go
  go.mod
Labels: Blocked, OK to merge

#10724 Change synced new block log
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/receive_block.go
Labels: Ready For Review, OK to merge

#10736 Consolidate blockchain errors
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/init_sync_process_block.go
  beacon-chain/blockchain/state_balance_cache.go
  beacon-chain/blockchain/weak_subjectivity_checks.go
Labels: Ready For Review, OK to merge, Cleanup

#10702 Do not update forkchoice checkpoints on calls to Head
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/mock_test.go
  beacon-chain/blockchain/new_slot.go
  beacon-chain/blockchain/new_slot_test.go
  beacon-chain/blockchain/pow_block_test.go
  beacon-chain/blockchain/process_attestation_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/errors.go
  beacon-chain/forkchoice/doubly-linked-tree/ffg_update_test.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/doubly-linked-tree/no_vote_test.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification_test.go
  beacon-chain/forkchoice/doubly-linked-tree/vote_test.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/errors.go
  beacon-chain/forkchoice/protoarray/ffg_update_test.go
  beacon-chain/forkchoice/protoarray/no_vote_test.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
  beacon-chain/forkchoice/protoarray/types.go
  beacon-chain/forkchoice/protoarray/unrealized_justification_test.go
  beacon-chain/forkchoice/protoarray/vote_test.go
  beacon-chain/node/node.go
  beacon-chain/rpc/prysm/v1alpha1/debug/forkchoice_test.go
  go.mod
  testing/spectest/shared/common/forkchoice/builder.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, OK to merge

#10703 Builder client
  api/client/builder/BUILD.bazel
  api/client/builder/client.go
  api/client/builder/client_test.go
  api/client/builder/errors.go
  api/client/builder/testdata/blinded-block.json
  api/client/builder/testdata/execution-payload.json
  api/client/builder/types.go
  api/client/builder/types_test.go
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
Labels: Ready For Review, OK to merge

#10739 Fix withdrawal epoch overflows
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  testing/spectest/shared/altair/epoch_processing/registry_updates.go
  testing/spectest/shared/bellatrix/epoch_processing/registry_updates.go
  testing/spectest/shared/phase0/epoch_processing/registry_updates.go
Labels: Ready For Review, OK to merge, Spec

#10732 Move ExecutionPayload Utils to Consensus Types Subpackage
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/payload.go
  beacon-chain/core/blocks/payload_test.go
  consensus-types/forks/bellatrix/BUILD.bazel
  consensus-types/forks/bellatrix/execution_payload.go
Labels: Ready For Review, OK to merge

#10665 Update proposer boost score and spec tests
  WORKSPACE
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/protoarray/proposer_boost_test.go
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  config/params/testdata/e2e_config.yaml
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/builder.go
  testing/spectest/shared/common/forkchoice/runner.go
  testing/spectest/shared/common/forkchoice/type.go
Labels: Ready For Review, OK to merge, Ropsten-required

#10727 Refactor migrateStateValidators for better readability
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/migration_state_validators.go
  beacon-chain/db/kv/migration_state_validators_test.go
Labels: Enhancement, Ready For Review, OK to merge, Cleanup

#10742 Use Correct Math Library
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  time/slots/BUILD.bazel
  time/slots/slottime.go
Labels: Ready For Review, OK to merge

#10744 Update .buildkite-bazelrc: change CI to use toplevel remote caching.
  .buildkite-bazelrc
Labels: Ready For Review, CI, OK to merge

#10746 Engine metrics: help text typos
  beacon-chain/powchain/metrics.go
Labels: Ready For Review, OK to merge, Cleanup

#10740 Add new DomainType for application usage
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/config.go
  config/params/mainnet_config.go
  encoding/bytesutil/bytes.go
  encoding/bytesutil/bytes_test.go
Labels: Ready For Review, OK to merge

#10747 Sync: use copied bits for seen cache
  beacon-chain/sync/validate_beacon_attestation.go
Labels: Ready For Review, OK to merge

#10751 Fix Scenario Tests
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
Labels: Ready For Review

#10752 Update Golang X Tools to Support Generics in Prysm
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review, OK to merge

#10674 Ignore subset aggregates
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  beacon-chain/sync/validate_sync_contribution_proof.go
  beacon-chain/sync/validate_sync_contribution_proof_test.go
  proto/prysm/v1alpha1/sync_committee_mainnet.go
  proto/prysm/v1alpha1/sync_committee_minimal.go
Labels: Ready For Review, OK to merge, Spec

#10753 Add in Separate Directories per Test
  testing/endtoend/components/web3remotesigner_test.go
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/minimal_slashing_e2e_test.go
  testing/endtoend/params/BUILD.bazel
  testing/endtoend/params/params.go
Labels: Ready For Review, CI, OK to merge, E2E Tests

#10723 Sync from finalized
  api/client/beacon/checkpoint.go
  api/client/beacon/checkpoint_test.go
  api/client/beacon/client.go
  beacon-chain/sync/checkpoint/api.go
  cmd/prysmctl/checkpoint/latest.go
  cmd/prysmctl/checkpoint/save.go
  testing/endtoend/BUILD.bazel
  testing/endtoend/component_handler_test.go
  testing/endtoend/components/beacon_node.go
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/endtoend_test.go
  testing/endtoend/evaluators/node.go
  testing/endtoend/helpers/helpers.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
  testing/endtoend/types/types.go
Labels: OK to merge

#10757 Add a fuzz test for fieldtrie
  beacon-chain/state/fieldtrie/BUILD.bazel
  beacon-chain/state/fieldtrie/field_trie.go
  beacon-chain/state/fieldtrie/field_trie_test.go
  beacon-chain/state/fieldtrie/testdata/fuzz/FuzzFieldTrie/c1898b8d556154d8a9d00cf2a64226dd5d76f33e27c373df2c409670db9b4877
Labels: Ready For Review, Fuzz

#10758 Make Common Dep Set For E2E
  testing/endtoend/BUILD.bazel
Labels: Ready For Review, E2E Tests

#10761 Fix error message with incorrect flag names
  validator/node/node.go
Labels: Ready For Review, OK to merge, Cleanup

#10763 Add back ttd override flags
  beacon-chain/node/config.go
  beacon-chain/node/config_test.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
Labels: Ready For Review, OK to merge, Ropsten-required

#10765 Remove Unnecessary Stack Traces for Engine Errors
  beacon-chain/blockchain/process_block.go
  beacon-chain/powchain/engine_client.go
Labels: Ready For Review, OK to merge

#10769 Write To Only One File For Geth Logs
  testing/endtoend/components/eth1/miner.go
  testing/endtoend/components/eth1/node.go
Labels: Ready For Review, OK to merge, E2E Tests

#10741 service.head race condition fix
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/service.go
Labels: Ready For Review, OK to merge

#10659 Unrealized justification
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/epoch/precompute/BUILD.bazel
  beacon-chain/core/epoch/precompute/justification_finalization.go
  beacon-chain/core/epoch/precompute/justification_finalization_test.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/error.go
  beacon-chain/state/state-native/getters_participation.go
  beacon-chain/state/state-native/getters_participation_test.go
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/unrealized_justification.go
  beacon-chain/state/stateutil/unrealized_justification_test.go
  beacon-chain/state/v1/getters_test.go
  beacon-chain/state/v1/unsupported_getters.go
  beacon-chain/state/v2/BUILD.bazel
  beacon-chain/state/v2/error.go
  beacon-chain/state/v2/getters_participation.go
  beacon-chain/state/v2/getters_participation_test.go
  beacon-chain/state/v2/getters_test.go
  beacon-chain/state/v3/BUILD.bazel
  beacon-chain/state/v3/error.go
  beacon-chain/state/v3/getters_participation.go
  beacon-chain/state/v3/getters_participation_test.go
  beacon-chain/state/v3/getters_test.go
Labels: Ready For Review, OK to merge

#10722 add mutex for validator.highestValidSlot
  validator/client/attest.go
  validator/client/validator.go
Labels: Ready For Review, OK to merge

#10768 Clean up onBlockBatch and prune forkchoice on init sync
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
Labels: Bug, Ready For Review, OK to merge

#10767 Reinsert reorg atts
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/forkchoice/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/error.go
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/protoarray/BUILD.bazel
  beacon-chain/forkchoice/protoarray/store.go
  beacon-chain/forkchoice/protoarray/store_test.go
Labels: Bug, Ready For Review, OK to merge

#10776 Do not fill in blocks that are not in the finalized branch
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
Labels: Bug, Ready For Review, OK to merge

#10791 Ensure finalized root can't be zeros
  beacon-chain/blockchain/process_block_helpers.go
Labels: Bug, OK to merge

#10786 Add and verify context in AddCommitteeShuffledList
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_disabled.go
  beacon-chain/cache/committee_fuzz_test.go
  beacon-chain/cache/committee_test.go
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/core/helpers/beacon_committee_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/transition/benchmarks_test.go
Labels: Ready For Review

#10775 Run mockgen
  testing/mock/BUILD.bazel
  testing/mock/beacon_chain_service_mock.go
  testing/mock/beacon_service_mock.go
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
  testing/mock/node_service_mock.go
  validator/client/validator_test.go
  validator/client/wait_for_activation_test.go
Labels: Cleanup, Builder

#10778 Mark e2e test targets as flaky for now
  testing/endtoend/BUILD.bazel
Labels: Ready For Review, OK to merge
