Repository OffchainLabs/prysm, pull requests merged in 2023-09, with the labels that each got.

#12782 HTTP implementation of `/eth/v1/beacon/pool/sync_committees`
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/core/service.go
  beacon-chain/rpc/core/validator.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  beacon-chain/rpc/eth/beacon/server.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/beacon/sync_committee.go
  beacon-chain/rpc/eth/beacon/sync_committee_test.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee.go
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee_test.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/validator.pb.go
  proto/eth/v2/sync_committee.pb.go
  proto/eth/v2/sync_committee.proto
  validator/client/beacon-api/sync_committee.go
  validator/client/beacon-api/sync_committee_test.go
Labels: OK to merge, API

#12837 fix(sync/rpc): use blobs by root when requesting block
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
Labels: Ready For Review, OK to merge

#12849 db: fix save blob sidecar using wrong prefix
  beacon-chain/db/kv/blob.go
  beacon-chain/db/kv/blob_test.go
Labels: Bug, OK to merge, Deneb

#12855 db: Use blobRotatingKey alias for readability
  beacon-chain/db/kv/blob.go
  beacon-chain/db/kv/blob_test.go
Labels: OK to merge

#12838 fix(builder): handle no blob bundle
  api/client/builder/client_test.go
  api/client/builder/types.go
  api/client/builder/types_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb.go
Labels: Ready For Review, OK to merge

#12822 Fix 12784
  beacon-chain/blockchain/process_block.go
  config/params/config.go
Labels: OK to merge

#12857 fix phase0 block parsing on submitblock
  beacon-chain/rpc/apimiddleware/custom_hooks.go
Labels: OK to merge, API

#12860 Fix Execution Block Unmarshalling in Deneb
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
Labels: Ready For Review, OK to merge

#12861 add a RW lock for duties
  validator/client/attest.go
  validator/client/validator.go
Labels: OK to merge

#12863 reject blocks with more commitments than spec
  beacon-chain/sync/validate_beacon_blocks.go
  beacon-chain/sync/validate_beacon_blocks_test.go
Labels: OK to merge

#12873 Tests for init-sync DA
  beacon-chain/blockchain/process_block_test.go
  config/params/BUILD.bazel
  config/params/config_test.go
Labels: OK to merge

#12866 fix: use correct blob root in blobs sidecar
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Ready For Review, OK to merge

#12865 fix: correct blob sidecar count
  beacon-chain/sync/subscriber.go
  config/params/config.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/network_config.go
Labels: Ready For Review, OK to merge

#12872 HTTP implementation of `/eth/v1/config/deposit_contract`
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/eth/beacon/config.go
  beacon-chain/rpc/eth/beacon/config_test.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
Labels: OK to merge, API

#12868 function to merge and validate saved/new blobs
  beacon-chain/db/kv/blob.go
  beacon-chain/db/kv/blob_test.go
Labels: OK to merge

#12878 Add Delay Option for Genesis to Prysmctl
  cmd/prysmctl/testnet/generate_genesis.go
Labels: Ready For Review, OK to merge

#12847 don't send pre-genesis signed validator registration objects to relayers
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge

#12880 Allow equivocating blobs
  beacon-chain/db/kv/blob.go
  beacon-chain/db/kv/blob_test.go
Labels: OK to merge

#12871 deneb - validator beacon rest apis
  beacon-chain/rpc/eth/shared/structs_blocks_conversions.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/get_beacon_block.go
  validator/client/beacon-api/get_beacon_block_test.go
  validator/client/beacon-api/propose_beacon_block.go
  validator/client/beacon-api/propose_beacon_block_blinded_deneb_test.go
  validator/client/beacon-api/propose_beacon_block_deneb_test.go
  validator/client/beacon-api/stream_blocks.go
  validator/client/beacon-api/stream_blocks_test.go
Labels: OK to merge, API, Deneb

#12835 REST implementation of ` /eth/v1/beacon/states/{state_id}/fork`
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/beacon/state.go
  beacon-chain/rpc/eth/beacon/state_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/service.go
  cmd/prysmctl/validator/BUILD.bazel
  cmd/prysmctl/validator/withdraw_test.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  testing/endtoend/evaluators/beaconapi_evaluators/BUILD.bazel
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/doppelganger_test.go
Labels: OK to merge, API

#12883 Improved Logging for Blob Sidecar
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/subscriber_blob_sidecar.go
  beacon-chain/sync/validate_blob.go
  cmd/prysmctl/p2p/request_blobs.go
  validator/client/propose.go
Labels: Ready For Review, OK to merge, Deneb

#12810 HTTP Beacon API: `/eth/v1/validator/duties`
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/eth/validator/structs.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/service.go
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator.proto
  proto/eth/v2/validator.pb.go
  proto/eth/v2/validator.proto
  testing/endtoend/evaluators/api_middleware.go
  testing/endtoend/evaluators/beaconapi_evaluators/BUILD.bazel
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
  validator/client/beacon-api/duties.go
  validator/client/beacon-api/duties_test.go
  validator/client/beacon-api/mock/BUILD.bazel
  validator/client/beacon-api/mock/duties_mock.go
  validator/client/beacon-api/submit_aggregate_selection_proof_test.go
  validator/client/beacon-api/subscribe_committee_subnets_test.go
  validator/client/beacon-api/sync_committee_test.go
Labels: OK to merge, API

#12882 Simplify DA check to avoid blob/block timing inconsistencies
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_blob.go
  beacon-chain/blockchain/service.go
Labels: OK to merge

#12852 Deneb api cleanup
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/shared/testing/json.go
Labels: OK to merge, API, Cleanup, Deneb

#12890 Fix build @com_github_ethereum_c_kzg_4844//...
  third_party/com_github_ethereum_c_kzg_4844.patch
Labels: Ready For Review, OK to merge, Deneb

#12879 HTTP Beacon API: `/eth/v1/beacon/states/{state_id}/committees`
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/beacon/validator.go
  beacon-chain/rpc/eth/beacon/validator_test.go
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  beacon-chain/rpc/eth/helpers/error_handling.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  validator/client/beacon-api/duties.go
  validator/client/beacon-api/duties_test.go
  validator/client/beacon-api/mock/BUILD.bazel
  validator/client/beacon-api/mock/duties_mock.go
Labels: OK to merge, API

#12892 don't save blob sidecar syncing to head if 0
  beacon-chain/sync/initial-sync/round_robin.go
Labels: Ready For Review, OK to merge, Deneb

#12901 Update blind blobs bundle max commitment size
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/generated.ssz.go
Labels: Ready For Review, OK to merge, Deneb

#12891 Update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready For Review, OK to merge

#12876 default to 7 seconds for first aggregation
  config/features/flags.go
Labels: Ready For Review, OK to merge

#12888 feat: add blob arrival gossip metric
  beacon-chain/sync/metrics.go
  beacon-chain/sync/validate_blob.go
Labels: Ready For Review, OK to merge, Deneb

#12906 Fix deneb builder bid HTR
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/generated.ssz.go
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Bug, Ready For Review, OK to merge, Deneb

#12903 keep track of block being synced
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/currently_syncing_block.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/pending_blocks_queue.go
Labels: Ready For Review, OK to merge

#12905 Dont process blocks twice
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
Labels: OK to merge

#12909 Fix proposer duties sorting
  beacon-chain/rpc/eth/validator/handlers.go
Labels: Ready For Review, OK to merge, API

#12917 Fix Deneb Fork Registration
  beacon-chain/sync/fork_watcher.go
  beacon-chain/sync/fork_watcher_test.go
Labels: Ready For Review, Deneb

#12910 Fix builder blind block namings
  api/client/builder/client.go
  api/client/builder/client_test.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/rpc/eth/beacon/blinded_blocks.go
  beacon-chain/rpc/eth/beacon/blinded_blocks_test.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/shared/structs_blocks_conversions.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/unblinder.go
  beacon-chain/rpc/prysm/v1alpha1/validator/unblinder_test.go
  consensus-types/blocks/factory.go
  consensus-types/blocks/factory_test.go
  consensus-types/blocks/getters.go
  consensus-types/blocks/proto.go
  consensus-types/blocks/proto_test.go
  consensus-types/blocks/testing/factory.go
  encoding/ssz/detect/configfork_test.go
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v2_to_v1alpha1.go
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
  proto/prysm/v1alpha1/generated.ssz.go
  testing/endtoend/evaluators/operations.go
  testing/util/block.go
  validator/client/beacon-api/propose_beacon_block.go
  validator/client/beacon-api/propose_beacon_block_blinded_deneb_test.go
Labels: Bug, OK to merge, Deneb

#12921 Deneb builder fix
  api/client/builder/BUILD.bazel
  api/client/builder/client.go
  api/client/builder/client_test.go
  beacon-chain/rpc/eth/shared/structs_blocks_conversions.go
Labels: Bug, Ready For Review, OK to merge, API, Deneb

#12920 remove unused function
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/block.go
  beacon-chain/operations/attestations/pool.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  beacon-chain/operations/attestations/prune_expired_test.go
Labels: Ready For Review, OK to merge

#12923 Copy kzg commitments when using builder block
  beacon-chain/rpc/prysm/v1alpha1/validator/unblinder.go
  beacon-chain/rpc/prysm/v1alpha1/validator/unblinder_test.go
Labels: Ready For Review, OK to merge, Deneb

#12922 Add Blind Blob Sidecar Signing in Validator Client
  validator/client/blob.go
  validator/client/blob_test.go
  validator/client/propose.go
  validator/client/propose_test.go
Labels: Ready For Review, OK to merge, Deneb

#12889 Handle Specific Blob Retrieval Error in DB
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge, Deneb

#12902 `GetFinalityCheckpoints` and `GetGenesis` HTTP endpoints
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/beacon/state.go
  beacon-chain/rpc/eth/beacon/state_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  testing/endtoend/evaluators/beaconapi_evaluators/BUILD.bazel
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api_verify.go
  validator/client/beacon-api/beacon_api_beacon_chain_client.go
  validator/client/beacon-api/beacon_api_beacon_chain_client_test.go
  validator/client/beacon-api/beacon_api_node_client_test.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/domain_data_test.go
  validator/client/beacon-api/genesis.go
  validator/client/beacon-api/genesis_test.go
  validator/client/beacon-api/json_rest_handler_test.go
  validator/client/beacon-api/mock/BUILD.bazel
  validator/client/beacon-api/mock/genesis_mock.go
  validator/client/beacon-api/wait_for_chain_start_test.go
Labels: OK to merge, API

#12916 HTTP API: GetLiveness and GetBlockHeader
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/shared/BUILD.bazel
  beacon-chain/rpc/eth/shared/errors.go
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/eth/validator/structs.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  proto/eth/v2/validator.pb.go
  proto/eth/v2/validator.proto
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
  validator/client/beacon-api/beacon_api_beacon_chain_client.go
  validator/client/beacon-api/beacon_api_beacon_chain_client_test.go
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/doppelganger_test.go
Labels: OK to merge, API

#12932 Fix Pagination Panic
  api/pagination/pagination.go
  api/pagination/pagination_test.go
Labels: Ready For Review, Security

#12935 Return correct root from `GetBlockHeader`
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
Labels: Ready For Review, OK to merge, API

#12939 Do not cache proposer ID on GetProposerDuties
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
Labels: Ready For Review, OK to merge

#12938 Fix Unhandled Error
  beacon-chain/sync/rpc_send_request_test.go
Labels: Ready For Review, OK to merge

#12887 HTTP validator APIs
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_validator.go
  beacon-chain/rpc/eth/beacon/handlers_validators_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/beacon/validator.go
  beacon-chain/rpc/eth/beacon/validator_test.go
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  beacon-chain/rpc/eth/helpers/error_handling.go
  beacon-chain/rpc/eth/shared/errors.go
  beacon-chain/rpc/prysm/validator/BUILD.bazel
  beacon-chain/rpc/prysm/validator/validator_count.go
  beacon-chain/rpc/prysm/validator/validator_count_test.go
  beacon-chain/rpc/service.go
  consensus-types/validator/types.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator.proto
  testing/endtoend/evaluators/api_middleware.go
  validator/client/beacon-api/activation.go
  validator/client/beacon-api/activation_test.go
  validator/client/beacon-api/beacon_api_beacon_chain_client.go
  validator/client/beacon-api/beacon_api_beacon_chain_client_test.go
  validator/client/beacon-api/doppelganger.go
  validator/client/beacon-api/doppelganger_test.go
  validator/client/beacon-api/duties_test.go
  validator/client/beacon-api/index_test.go
  validator/client/beacon-api/mock/state_validators_mock.go
  validator/client/beacon-api/state_validators.go
  validator/client/beacon-api/state_validators_test.go
  validator/client/beacon-api/status.go
  validator/client/beacon-api/status_test.go
  validator/client/beacon-api/submit_aggregate_selection_proof_test.go
  validator/client/beacon-api/sync_committee_test.go
Labels: OK to merge, API

#12940 Use headstate when requesting current epochs
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
Labels: Ready For Review, OK to merge

#12937 Amend Bug Report Template Requirements
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Ready For Review, OK to merge

#12928 Deneb: blob sidecar events
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/core/feed/operation/events.go
  beacon-chain/rpc/eth/events/BUILD.bazel
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/events/events_test.go
  beacon-chain/sync/subscriber_blob_sidecar.go
  proto/eth/v1/events.pb.go
  proto/eth/v1/events.proto
  proto/migration/v1alpha1_to_v2.go
Labels: OK to merge, API, Deneb

#12897 db: Log a warning if the genesis state is smaller than 1Kb
  beacon-chain/db/kv/genesis.go
  beacon-chain/sync/genesis/BUILD.bazel
  beacon-chain/sync/genesis/api.go
  beacon-chain/sync/genesis/file.go
  beacon-chain/sync/genesis/log.go
Labels: Enhancement, Ready For Review, OK to merge, UX

#12919 Update holesky config for new genesis
  WORKSPACE
  config/params/testnet_holesky_config.go
Labels: Ready For Review, OK to merge

#12943 Refactor construct generic beacon block for proposer
  beacon-chain/db/kv/blob_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/construct_generic_block.go
  beacon-chain/rpc/prysm/v1alpha1/validator/construct_generic_block_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Labels: Ready For Review, Cleanup

#12953 Fix TestService_ReceiveBlock
  beacon-chain/blockchain/receive_block_test.go
  testing/util/block.go
Labels: Ready For Review, Priority: High, OK to merge, Test

#12954 forkchoice return last canonical root of epoch
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/last_root.go
  beacon-chain/forkchoice/doubly-linked-tree/last_root_test.go
  beacon-chain/forkchoice/interfaces.go
Labels: Ready For Review, OK to merge

#12957 Fix More Racy Tests in Blockchain
  beacon-chain/blockchain/receive_block_test.go
Labels: Ready For Review, OK to merge

#12944 Avoid Public Key Copies During Aggregation
  crypto/bls/blst/public_key.go
  crypto/bls/blst/public_key_test.go
Labels: Ready For Review, OK to merge, optimization

#11748 clean up code around setting geth client headers
  beacon-chain/execution/rpc_connection.go
  network/endpoint.go
  testing/middleware/builder/builder.go
Labels: OK to merge

#12951 Refactor `getLocalPayloadAndBlobs` with New Helper `getParentBlockHash`
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
Labels: Ready For Review, OK to merge, Cleanup

#12827 HTTP Beacon API: `/eth/v1/beacon/blocks` and `/eth/v1/beacon/blinded_blocks`
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/blinded_blocks.go
  beacon-chain/rpc/eth/beacon/blinded_blocks_test.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/blob/handlers.go
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/service.go
  network/http/BUILD.bazel
  network/http/reader.go
  network/http/reader_test.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
Labels: OK to merge, API

#12961 cleanup on api types
  api/client/beacon/BUILD.bazel
  api/client/beacon/client.go
  api/client/builder/BUILD.bazel
  api/client/builder/client.go
  api/client/builder/testdata/blinded-block-capella.json
  api/client/builder/types.go
  api/client/builder/types_test.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/shared/structs_blocks_conversions.go
  testing/middleware/builder/BUILD.bazel
  testing/middleware/builder/builder.go
  validator/client/beacon-api/registration.go
Labels: API, Cleanup

#12941 Add a flag to configure blob retention epoch period
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/blob.go
  beacon-chain/db/kv/blob_test.go
  beacon-chain/db/kv/flags.go
  beacon-chain/db/kv/flags_test.go
  beacon-chain/node/node.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
Labels: Ready For Review, OK to merge, Deneb

#12964 Deprecate `--safe-slots-to-import-optimistically` beacon flag
  cmd/beacon-chain/flags/base.go
Labels: Ready For Review

#12428 Multiarch docker containers
  .buildkite-bazelrc
  WORKSPACE
  cmd/beacon-chain/BUILD.bazel
  cmd/prysmctl/BUILD.bazel
  cmd/validator/BUILD.bazel
  hack/build_and_upload_docker.sh
  tools/BUILD.bazel
  tools/image_deps.bzl
  tools/multi_arch.bzl
  tools/prysm_image.bzl
Labels: Ready For Review, OK to merge

#12967 Docker: Add "manual" build tag to reduce build times in CI
  cmd/beacon-chain/BUILD.bazel
  cmd/prysmctl/BUILD.bazel
  cmd/validator/BUILD.bazel
  tools/beacon-fuzz/BUILD.bazel
  tools/cross-toolchain/darwin_cc_hack.bzl
  tools/image_deps.bzl
  tools/prysm_image.bzl
  tools/ssz.bzl
  tools/target_migration.bzl
Labels: Ready For Review, CI, OK to merge

#12959 Deneb spectests release v1.4.0-beta.2-hotfix
  WORKSPACE
  beacon-chain/blockchain/receive_blob.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/forkchoice/doubly-linked-tree/proposer_boost_test.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/rpc/eth/beacon/config_test.go
  beacon-chain/sync/subscriber_blob_sidecar.go
  config/params/config.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  config/params/testdata/e2e_config.yaml
  config/params/testnet_e2e_config.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/blobs.proto
  proto/prysm/v1alpha1/generated.ssz.go
  testing/endtoend/evaluators/operations.go
  testing/spectest/general/deneb/kzg/verify_blob_kzg_proof_batch_test.go
  testing/spectest/general/phase0/bls/aggregate_test.go
  testing/spectest/general/phase0/bls/aggregate_verify_test.go
  testing/spectest/general/phase0/bls/fast_aggregate_verify_test.go
  testing/spectest/general/phase0/bls/sign_test.go
  testing/spectest/general/phase0/bls/verify_test.go
  testing/spectest/minimal/deneb/forkchoice/forkchoice_test.go
  testing/spectest/shared/common/forkchoice/BUILD.bazel
  testing/spectest/shared/common/forkchoice/builder.go
  testing/spectest/shared/common/forkchoice/runner.go
  testing/spectest/shared/common/forkchoice/service.go
  testing/spectest/shared/common/forkchoice/type.go
Labels: Ready For Review, OK to merge

#12969 Fix `GetBeaconBlock` to use `skip-mev-boost`
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Labels: Bug, Ready For Review

#12962 Updating Teku mainnet bootnodes ENRs
  config/params/mainnet_config.go
Labels: OK to merge

#12720 Default to the portable version of blst
  .bazelrc
  .github/workflows/go.yml
  third_party/blst/blst.BUILD
Labels: OK to merge

#12974 Return RpcError from core service's `SubmitSyncMessage`
  beacon-chain/rpc/core/validator.go
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee.go
Labels: Ready For Review, OK to merge, API
