Repository OffchainLabs/prysm, pull requests merged in 2023-06, with the labels that each got.

#12432 Add `broadcast_validation` to block publishing
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/blinded_blocks.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/beacon/server.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/helpers/sync.go
  beacon-chain/rpc/eth/helpers/sync_test.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/service.go
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review, OK to merge, API

#12483 Fix the bug that return 500 in /eth/v1/node/peers interface
  beacon-chain/rpc/eth/node/node.go
Labels: OK to merge

#12481 Proposer RPC: GetBlock for Deneb
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_empty_block.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_empty_block_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Deneb

#12485 Add Appropriate Size for the Attestation Queue
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
Labels: Ready For Review, OK to merge, Sync

#12489 Update spec tests to v1.4.0-alpha.1
  WORKSPACE
Labels: Ready For Review, OK to merge

#12486 Update Libp2p to v0.27.5
  deps.bzl
  go.mod
  go.sum
  tools/analyzers/uintcast/analyzer.go
Labels: dependencies

#12181 prysmctl: output proposer settings
  api/client/BUILD.bazel
  api/client/beacon/BUILD.bazel
  api/client/beacon/checkpoint.go
  api/client/beacon/checkpoint_test.go
  api/client/beacon/client.go
  api/client/beacon/client_test.go
  api/client/beacon/errors.go
  api/client/client.go
  api/client/client_test.go
  api/client/errors.go
  api/client/options.go
  api/client/validator/BUILD.bazel
  api/client/validator/client.go
  cmd/prysmctl/checkpointsync/BUILD.bazel
  cmd/prysmctl/checkpointsync/download.go
  cmd/prysmctl/validator/BUILD.bazel
  cmd/prysmctl/validator/cmd.go
  cmd/prysmctl/validator/error.go
  cmd/prysmctl/validator/proposer_settings.go
  cmd/prysmctl/validator/proposer_settings_test.go
  cmd/prysmctl/weaksubjectivity/BUILD.bazel
  cmd/prysmctl/weaksubjectivity/checkpoint.go
  validator/client/validator.go
Labels: OK to merge, prysmctl

#12502 Always Favour Yamux for Multiplexing
  beacon-chain/p2p/options.go
  beacon-chain/p2p/options_test.go
Labels: Ready For Review, Priority: High, OK to merge

#12503 Ignore Phase0 Blocks For Monitor
  beacon-chain/monitor/process_sync_committee.go
Labels: Ready For Review, OK to merge

#12504 optimization(proposer-rpc): move htr to after broadcast
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Labels: Ready For Review

#12510 feat(rpc/validator): stream and use deneb block
  beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review, Deneb

#12509 feat(blockchain): update payload attribute for deneb
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/rpc/eth/events/events.go
Labels: Ready For Review, Deneb

#12512 feat(config): update max blobs per block to 6
  WORKSPACE
  beacon-chain/db/kv/blob_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/network_config.go
Labels: Ready For Review, Deneb

#12507 Add Patch For Libp2p
  deps.bzl
  third_party/com_github_libp2p_go_libp2p.patch
Labels: Ready For Review, OK to merge

#12447 Checkpoint sync: get block using state.latest_block_header.slot
  api/client/beacon/checkpoint.go
  api/client/beacon/checkpoint_test.go
Labels: OK to merge

#12287 Use next slot cache for sync committee
  beacon-chain/blockchain/head_sync_committee_info.go
  beacon-chain/blockchain/head_sync_committee_info_test.go
Labels: OK to merge

#12505 change update duties to handle all validators exited check
  validator/accounts/testing/mock.go
  validator/client/iface/validator.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge, Cleanup

#12516 benchmark cold hashing of capella beaconstates
  tools/pcli/main.go
Labels: OK to merge

#12524 Remove Defer In ProposeGenericBlock
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Labels: Ready For Review, Priority: High, OK to merge

#12525 Ignore Late Message Logs
  beacon-chain/core/altair/sync_committee.go
  beacon-chain/core/helpers/attestation.go
  beacon-chain/sync/subscriber.go
Labels: Ready For Review, OK to merge, Cleanup

#12529 log the right blocknumber
  beacon-chain/blockchain/log.go
Labels: Ready For Review, OK to merge

#12530 Reopenning fix for keystore field name change to align with EIP2335
  cmd/validator/accounts/delete_test.go
  tools/keystores/main.go
  validator/accounts/accounts_import.go
  validator/accounts/accounts_import_test.go
  validator/accounts/accounts_list_test.go
  validator/keymanager/local/backup.go
  validator/keymanager/local/import_test.go
  validator/keymanager/types.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
  validator/rpc/wallet.go
  validator/rpc/wallet_test.go
Labels: Bug

#12499 BlobSidecarsByRange rpc handler
  beacon-chain/p2p/rpc_topic_mappings.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/blobs_test.go
  beacon-chain/sync/block_batcher.go
  beacon-chain/sync/block_batcher_test.go
  beacon-chain/sync/metrics.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rate_limiter_test.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_blob_sidecars_by_range.go
  beacon-chain/sync/rpc_blob_sidecars_by_range_test.go
  beacon-chain/sync/rpc_send_request.go
  beacon-chain/sync/rpc_send_request_test.go
Labels: OK to merge

#12420 BlobSidecarsByRoot
  beacon-chain/p2p/peers/peers_test.go
  beacon-chain/p2p/rpc_topic_mappings.go
  beacon-chain/p2p/types/BUILD.bazel
  beacon-chain/p2p/types/rpc_errors.go
  beacon-chain/p2p/types/types.go
  beacon-chain/p2p/types/types_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/blobs_test.go
  beacon-chain/sync/block_batcher.go
  beacon-chain/sync/block_batcher_test.go
  beacon-chain/sync/context.go
  beacon-chain/sync/error.go
  beacon-chain/sync/metrics.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rate_limiter_test.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_blob_sidecars_by_range.go
  beacon-chain/sync/rpc_blob_sidecars_by_range_test.go
  beacon-chain/sync/rpc_blob_sidecars_by_root.go
  beacon-chain/sync/rpc_blob_sidecars_by_root_test.go
  beacon-chain/sync/rpc_chunked_response.go
  beacon-chain/sync/rpc_send_request.go
  beacon-chain/sync/rpc_send_request_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/sync_test.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/flags/config.go
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
  config/params/BUILD.bazel
  config/params/config.go
  config/params/configset.go
  config/params/interop.go
  config/params/loader.go
  config/params/mainnet_config.go
  config/params/testnet_e2e_config.go
Labels: OK to merge

#12523 Integrate generate genesis
  cmd/prysmctl/testnet/generate_genesis.go
  runtime/interop/genesis.go
  runtime/interop/premine-state.go
Labels: OK to merge

#12537 ssz detection support for deneb
  encoding/ssz/detect/configfork.go
  encoding/ssz/detect/configfork_test.go
Labels: OK to merge

#12536 Ensure File Does Not Exist
  tools/interop/convert-keys/BUILD.bazel
  tools/interop/convert-keys/main.go
  tools/specs-checker/BUILD.bazel
  tools/specs-checker/download.go
Labels: OK to merge, Cleanup

#12487 multiple validator status - optimization
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
  validator/client/beacon-api/status.go
Labels: Cleanup

#12540 Fix Uint256 Json Parsing
  api/client/builder/types.go
  api/client/builder/types_test.go
  beacon-chain/rpc/apimiddleware/structs_marshalling.go
  beacon-chain/rpc/apimiddleware/structs_marshalling_test.go
Labels: Ready For Review, OK to merge, API

#12541 Fix Fuzz Target For ExecutionPayload
  beacon-chain/execution/engine_client_fuzz_test.go
  proto/engine/v1/json_marshal_unmarshal.go
Labels: Ready For Review, OK to merge, Fuzz

#12459 Do not validate merge transition block after Capella
  beacon-chain/blockchain/process_block.go
Labels: OK to merge

#12526 fix: late block task wait for initial sync
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/node/node.go
Labels: OK to merge

#12465 disable nil payloadid log on relayers flags
  beacon-chain/blockchain/execution_engine.go
Labels: Ready For Review, OK to merge

#12544 feat(prysmctl): request blobs
  cmd/prysmctl/p2p/BUILD.bazel
  cmd/prysmctl/p2p/p2p.go
  cmd/prysmctl/p2p/request_blobs.go
Labels: Ready For Review, Deneb

#12551 fix typo (beacon-chain/node/node.go)
  beacon-chain/node/node.go
Labels: OK to merge

#12480 `getAttestationRewards` API endpoint
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/altair/epoch_precompute_test.go
  beacon-chain/rpc/eth/rewards/BUILD.bazel
  beacon-chain/rpc/eth/rewards/handlers.go
  beacon-chain/rpc/eth/rewards/handlers_test.go
  beacon-chain/rpc/eth/rewards/server.go
  beacon-chain/rpc/eth/rewards/structs.go
  beacon-chain/rpc/service.go
  testing/spectest/shared/altair/rewards/rewards_penalties.go
  testing/spectest/shared/bellatrix/rewards/rewards_penalties.go
  testing/spectest/shared/capella/rewards/rewards_penalties.go
Labels: Ready For Review, OK to merge, API

#12519 Add expected withdrawals API
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/eth/builder/BUILD.bazel
  beacon-chain/rpc/eth/builder/handlers.go
  beacon-chain/rpc/eth/builder/handlers_test.go
  beacon-chain/rpc/eth/builder/server.go
  beacon-chain/rpc/eth/builder/structs.go
  beacon-chain/rpc/service.go
Labels: OK to merge

#12558 Remove unneded helper
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service_test.go
Labels: Ready For Review, OK to merge, Cleanup

#12553 feat: aggregate atts using fixed pool of go routines
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  config/features/config.go
  config/features/flags.go
Labels: Ready For Review, OK to merge

#12559 use the incoming payload status instead of calling forkchoice
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge, Cleanup

#12135 Add hermetic_cc_toolchain for a hermetic cc toolchain
  .bazelrc
  .bazelversion
  WORKSPACE
  build/bazelrc/hermetic-cc.bazelrc
  tools/cross-toolchain/darwin_cc_hack.bzl
Labels: Ready For Review, OK to merge

#12484 Cache next epoch proposers at epoch boundary
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service.go
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/core/helpers/beacon_committee_test.go
  beacon-chain/core/helpers/validators.go
Labels: Ready For Review, OK to merge

#12571 fix: use diff context to update proposer cache background
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge

#12560 Remove forkchoice call from notify new payload
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge

#12569 Update protobuf and protobuf deps
  .bazelrc
  BUILD.bazel
  WORKSPACE
  deps.bzl
Labels: Ready For Review, OK to merge

#12573 Update geth
  beacon-chain/node/config_test.go
  cmd/validator/flags/flags_test.go
  deps.bzl
  go.mod
  go.sum
  third_party/com_github_ethereum_c_kzg_4844.patch
Labels: OK to merge

#12456 Registration Cache used by default and other UX changes for Proposer settings
  beacon-chain/node/node.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  config/features/deprecated_flags.go
  config/features/flags.go
  config/validator/service/proposer_settings.go
  config/validator/service/proposer_settings_test.go
  validator/accounts/testing/mock.go
  validator/client/iface/validator.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/service.go
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/db/kv/proposer_settings.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/node_test.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
Labels: OK to merge, Cleanup, Builder

#12578 run `ineffassign` for all code
  api/client/beacon/checkpoint_test.go
  encoding/ssz/detect/configfork_test.go
  nogo_config.json
  testing/endtoend/component_handler_test.go
  testing/endtoend/components/eth1/transactions.go
  testing/endtoend/components/lighthouse_validator.go
  testing/endtoend/endtoend_test.go
Labels: OK to merge

#12533 Increase validator client startup proposer settings deadline
  validator/client/runner.go
  validator/client/runner_test.go
Labels: OK to merge
