Repository OffchainLabs/prysm, pull requests merged in 2023-04, with the labels that each got.

#12220 Enable Static Peer ID
  beacon-chain/node/node.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/options_test.go
  beacon-chain/p2p/utils.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  cmd/flags.go
Labels: Ready For Review, Networking, OK to merge

#12219 Implement `/eth/v1/beacon/blobs/{block_id}` API endpoint
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/eth/blob/BUILD.bazel
  beacon-chain/rpc/eth/blob/handlers.go
  beacon-chain/rpc/eth/blob/handlers_test.go
  beacon-chain/rpc/eth/blob/server.go
  beacon-chain/rpc/eth/blob/structs.go
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  beacon-chain/rpc/eth/helpers/http.go
  beacon-chain/rpc/eth/helpers/http_test.go
  beacon-chain/rpc/service.go
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
Labels: Ready For Review

#12231 Testnet: override Eth1Data for genesisState from input JSON
  cmd/prysmctl/testnet/generate_genesis.go
Labels: OK to merge

#12227 Add flag to boost local block value
  beacon-chain/node/config.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  cmd/beacon-chain/flags/base.go
  config/params/config.go
Labels: OK to merge, Builder

#12233 refactor next slot cache
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/transition/trailing_slot_state_cache.go
  beacon-chain/core/transition/trailing_slot_state_cache_test.go
  beacon-chain/core/transition/transition.go
Labels: Bug, Ready For Review, OK to merge

#12243 Default to local payload should set block to not blind
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
Labels: Ready For Review, OK to merge

#12247 Fix Next State Mismatch
  beacon-chain/core/transition/trailing_slot_state_cache.go
  beacon-chain/core/transition/trailing_slot_state_cache_test.go
  beacon-chain/core/transition/transition.go
Labels: Ready For Review, Priority: High

#12236 Builder: fix nil panic edgecase
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
Labels: Bug, Builder

#12244 build tag to exclude mainnet genesis from prysmctl
  beacon-chain/state/genesis/BUILD.bazel
  beacon-chain/state/genesis/genesis.go
  beacon-chain/state/genesis/genesis_mainnet.go
  cmd/prysmctl/BUILD.bazel
Labels: OK to merge

#12241 Remove unused beacon-chain/server binary
  beacon-chain/server/BUILD.bazel
  beacon-chain/server/log.go
  beacon-chain/server/main.go
Labels: OK to merge, API, Cleanup

#12249 Add orphaned operations to the appropriate pool
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service_test.go
Labels: Ready For Review

#12250 Fix Deadlock in StreamChainHead
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go
Labels: Bug

#12238 Update go to version 1.19.8
  WORKSPACE
Labels: Ready For Review, OK to merge, Security

#12263 Fix capella unblind block with bls field
  api/client/builder/client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_capella.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_capella_test.go
  validator/client/runner_test.go
  validator/client/wait_for_activation_test.go
Labels: Bug, Builder

#12264 Fix User Agent In Builder Client
  api/client/builder/client.go
Labels: Ready For Review, Priority: High, OK to merge

#12245 Add REST API endpoint for beacon chain client's `GetChainHead`
  validator/client/beacon-api/beacon_api_beacon_chain_client.go
  validator/client/beacon-api/beacon_api_beacon_chain_client_test.go
Labels: OK to merge

#12260 Add prepare-all-payloads flag
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/forkchoice_update_execution.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/feed/state/events.go
  beacon-chain/rpc/eth/events/events.go
  config/features/config.go
  config/features/flags.go
Labels: OK to merge

#12268 prysmctl using the same genesis func as e2e
  beacon-chain/execution/testing/BUILD.bazel
  beacon-chain/state/stateutil/BUILD.bazel
  cmd/prysmctl/testnet/BUILD.bazel
  cmd/prysmctl/testnet/generate_genesis.go
  cmd/prysmctl/testnet/generate_genesis_test.go
  runtime/interop/BUILD.bazel
  runtime/interop/genesis.go
  runtime/interop/premine-state.go
  runtime/version/BUILD.bazel
  runtime/version/fork.go
  testing/endtoend/components/BUILD.bazel
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/eth1/BUILD.bazel
  testing/endtoend/components/eth1/miner.go
  testing/endtoend/components/eth1/node.go
  testing/util/BUILD.bazel
Labels: OK to merge

#12277 Fix Panic In Builder Service
  beacon-chain/builder/service.go
  beacon-chain/builder/service_test.go
Labels: Bug, Ready For Review, Priority: High, Builder

#12267 4844: `getBlindedBlock` ssz Beacon API
  beacon-chain/rpc/eth/beacon/blinded_blocks.go
  beacon-chain/rpc/eth/beacon/blinded_blocks_test.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Ready For Review, Blobspace

#12279 Check that Builder Is Configured
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Bug, Ready For Review, OK to merge, Builder

#12283 support modifying genesis.json for capella
  cmd/prysmctl/testnet/generate_genesis.go
  runtime/interop/genesis.go
Labels: OK to merge

#12290 Correctly use Gwei to compare builder bid value
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
Labels: Bug, Ready For Review, Priority: High

#12293 Fix Broken Dependency
  deps.bzl
  go.mod
  go.sum
  monitoring/journald/BUILD.bazel
  monitoring/journald/journald_linux.go
  monitoring/journald/journalhook.go
  monitoring/journald/journalhook_test.go
Labels: Ready For Review, dependencies

#12294 Add License For Vendored Dependency
  monitoring/journald/LICENSE
Labels: Ready For Review, OK to merge

#12224 Add support for engine_exchangeCapabilities
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
Labels: OK to merge

#12282 Deflake `TestWaitForActivation_AccountsChanged`
  go.mod
  go.sum
  validator/client/BUILD.bazel
  validator/client/wait_for_activation_test.go
Labels: Ready For Review, OK to merge

#12295 Fix Attester Slashing Validation In Gossip
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_attester_slashing_test.go
Labels: Ready For Review, Networking, OK to merge

#12284 Keymanager fixes for bad file writes
  validator/accounts/testing/mock.go
  validator/keymanager/local/BUILD.bazel
  validator/keymanager/local/delete.go
  validator/keymanager/local/delete_test.go
  validator/keymanager/local/import.go
  validator/keymanager/local/import_test.go
  validator/keymanager/local/keymanager.go
Labels: Priority: High

#12296 windows: Fix build after PR 12293
  monitoring/journald/BUILD.bazel
  monitoring/journald/journalhook_linux.go
  monitoring/journald/journalhook_linux_test.go
Labels: Bug, Priority: High, OK to merge

#12273 Enable whitespace linter & fix findings
  .golangci.yml
  api/client/builder/client.go
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/db/kv/state.go
  beacon-chain/execution/service.go
  beacon-chain/execution/testing/mock_execution_chain.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/gateway/helpers.go
  beacon-chain/monitor/process_block.go
  beacon-chain/operations/blstoexec/pool.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_stream.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_eth1data.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/service.go
  beacon-chain/state/fieldtrie/field_trie.go
  beacon-chain/state/state-native/getters_participation.go
  beacon-chain/state/state-native/state_trie.go
  beacon-chain/state/testing/getters.go
  beacon-chain/state/testing/getters_block.go
  cmd/prysmctl/p2p/request_blocks.go
  cmd/prysmctl/validator/withdraw.go
  cmd/validator/accounts/wallet_utils.go
  consensus-types/blocks/getters.go
  crypto/bls/blst/public_key.go
  crypto/keystore/keystore.go
  math/math_helper.go
  monitoring/journald/journalhook_linux.go
  testing/endtoend/components/eth1/transactions.go
  testing/endtoend/evaluators/operations.go
  testing/endtoend/evaluators/slashing.go
  testing/endtoend/helpers/epochTimer.go
  testing/spectest/shared/common/forkchoice/builder.go
  testing/spectest/shared/common/forkchoice/runner.go
  time/slots/slotticker.go
  tools/bootnode/bootnode.go
  tools/exploredb/main.go
  tools/gocovmerge/main.go
  validator/accounts/wallet/wallet.go
  validator/client/aggregate.go
  validator/client/beacon-api/duties.go
  validator/client/validator.go
  validator/keymanager/derived/keymanager.go
  validator/keymanager/local/keymanager.go
  validator/keymanager/remote-web3signer/v1/custom_mappers.go
  validator/keymanager/remote-web3signer/v1/mock/mocks.go
  validator/node/node.go
  validator/rpc/slashing.go
  validator/testing/mock_slasher.go
Labels: OK to merge

#12302 builder: add more tracing data for builder code paths
  beacon-chain/builder/BUILD.bazel
  beacon-chain/builder/service.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
Labels: Ready For Review, OK to merge

#12270 Enable nilerr linter & fix findings
  .golangci.yml
  beacon-chain/core/helpers/sync_committee.go
  beacon-chain/core/helpers/sync_committee_test.go
  beacon-chain/rpc/eth/node/node.go
  beacon-chain/rpc/testutil/mock_blocker.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  testing/endtoend/components/eth1/transactions.go
  validator/rpc/beacon.go
  validator/rpc/health.go
Labels: OK to merge

#12271 Enable dupword linter & fix findings
  .golangci.yml
  api/client/beacon/checkpoint.go
  async/scatter.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/altair/epoch_spec.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/reward_penalty.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/rpc/eth/node/node.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
  beacon-chain/slasher/chunks.go
  beacon-chain/slasher/doc.go
  beacon-chain/state/state-native/setters_attestation.go
  beacon-chain/state/state-native/setters_eth1.go
  beacon-chain/state/state-native/setters_participation.go
  beacon-chain/state/state-native/setters_validator.go
  beacon-chain/state/state-native/types_test.go
  cmd/prysmctl/checkpointsync/download.go
  cmd/validator/slashing-protection/export.go
  cmd/validator/slashing-protection/import.go
  cmd/wrap_flags.go
  container/leaky-bucket/leakybucket.go
  crypto/bls/bls.go
  crypto/bls/blst/doc.go
  encoding/ssz/merkleize.go
  hack/interop_start.sh
  io/logs/stream.go
  testing/endtoend/params/params.go
  tools/analyzers/errcheck/analyzer.go
  validator/accounts/userprompt/prompt.go
  validator/client/beacon-api/doppelganger.go
  validator/db/kv/attester_protection.go
Labels: OK to merge

#12306 validator exit says you can't withdraw - cosmetic issue
  validator/accounts/accounts_helper.go
Labels: UX

#12310 improve the blinded block error
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
Labels: UX

#12304 db: Deduplicate saveCheckpoint functionality
  beacon-chain/db/kv/checkpoint.go
  beacon-chain/db/kv/validated_checkpoint.go
Labels: OK to merge, Cleanup

#12313 Add Exceptions For Transaction Fuzzer
  testing/endtoend/components/eth1/transactions.go
Labels: Ready For Review, OK to merge

#12309 Return errors from `ProduceBlindedBlock`
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
Labels: Ready For Review, API

#12291 Change native execution value to Gwei Uint64
  api/client/builder/BUILD.bazel
  api/client/builder/bid.go
  api/client/builder/client.go
  beacon-chain/builder/testing/mock.go
  beacon-chain/core/blocks/payload_test.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  beacon-chain/state/state-native/getters_payload_header.go
  beacon-chain/state/state-native/hasher_test.go
  consensus-types/blocks/execution.go
  consensus-types/blocks/execution_test.go
  consensus-types/blocks/factory.go
  consensus-types/blocks/getters.go
  consensus-types/blocks/getters_test.go
  consensus-types/blocks/proto.go
  consensus-types/blocks/proto_test.go
  consensus-types/interfaces/beacon_block.go
  math/math_helper.go
  math/math_helper_test.go
  testing/spectest/shared/capella/operations/withdrawals.go
Labels: Ready For Review, OK to merge

#12307 Merge payload bundle and get payload
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/sync/context.go
  deps.bzl
  go.mod
  go.sum
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/generated.ssz.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Blobspace

#12325 Corrected err return for GenesisState while calling db.View
  beacon-chain/db/kv/state.go
Labels: OK to merge

#12327 Remove unused argument from field index
  beacon-chain/state/fieldtrie/BUILD.bazel
  beacon-chain/state/fieldtrie/field_trie_helpers.go
  beacon-chain/state/state-native/state_trie.go
  beacon-chain/state/state-native/types/types.go
Labels: Ready For Review, OK to merge, Cleanup

#12326 Avoid double state copy in `latestAncestor`
  beacon-chain/state/stategen/getter.go
Labels: Ready For Review, OK to merge

#12329 Move some errors to separate `consensus-types` package
  api/client/builder/BUILD.bazel
  api/client/builder/bid.go
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/log.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/payload.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/blinded_blocks.go
  beacon-chain/rpc/eth/beacon/blocks.go
  cmd/prysmctl/p2p/BUILD.bazel
  cmd/prysmctl/p2p/request_blocks.go
  consensus-types/BUILD.bazel
  consensus-types/blocks/BUILD.bazel
  consensus-types/blocks/execution.go
  consensus-types/blocks/execution_test.go
  consensus-types/blocks/getters.go
  consensus-types/blocks/proto.go
  consensus-types/blocks/setters.go
  consensus-types/blocks/types.go
  consensus-types/payload-attribute/BUILD.bazel
  consensus-types/payload-attribute/getters.go
  consensus-types/types.go
Labels: Ready For Review, OK to merge, Cleanup

#12332 blockchain: add more spans to analyze block production timing
  beacon-chain/blockchain/forkchoice_update_execution.go
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review, OK to merge

#12321 Move update next slot cache earlier
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge

#12319 Use mock v1alpha1 server in Beacon API's validator functions
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/server.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee.go
  beacon-chain/rpc/service.go
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.pb.gw.go
  proto/prysm/v1alpha1/validator.proto
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
  validator/client/grpc-api/grpc_validator_client.go
Labels: Ready For Review, API

#12338 Fix committee test race
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/active_balance.go
  beacon-chain/cache/active_balance_disabled.go
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_disabled.go
  beacon-chain/cache/proposer_indices.go
  beacon-chain/cache/proposer_indices_disabled.go
  beacon-chain/cache/sync_committee.go
  beacon-chain/cache/sync_committee_disabled.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/core/helpers/beacon_committee_test.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  beacon-chain/core/helpers/sync_committee.go
  beacon-chain/core/helpers/sync_committee_test.go
  beacon-chain/core/helpers/validators_test.go
Labels: OK to merge

#12341 Keymanager mock cleanup
  validator/client/attest_test.go
  validator/client/key_reload_test.go
  validator/client/propose_test.go
  validator/client/validator_test.go
  validator/client/wait_for_activation_test.go
Labels: OK to merge

#12333 Update to go1.20
  WORKSPACE
  deps.bzl
  encoding/bytesutil/BUILD.bazel
  encoding/bytesutil/bytes_go120.go
  encoding/bytesutil/bytes_legacy.go
  go.mod
  go.sum
Labels: Ready For Review, OK to merge

#12324 log correctly the head changed when it actually changes
  beacon-chain/blockchain/forkchoice_update_execution.go
  beacon-chain/blockchain/forkchoice_update_execution_test.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review, OK to merge

#12322 Validator registration filter non active keys before submission
  validator/client/validator.go
  validator/client/validator_test.go
  validator/node/node.go
  validator/node/node_test.go
Labels: Builder

#12345 Beacon-api: save atts to pool
  beacon-chain/rpc/eth/beacon/pool.go
  beacon-chain/rpc/eth/beacon/pool_test.go
Labels: Bug, Ready For Review

#12342 InsertFinalizedDeposits: return an error
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/cache/depositcache/deposits_cache_test.go
  beacon-chain/execution/service.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: OK to merge

#12316 Unregister validator - fix behind feature flag
  beacon-chain/builder/BUILD.bazel
  beacon-chain/builder/option.go
  beacon-chain/builder/service.go
  beacon-chain/builder/testing/BUILD.bazel
  beacon-chain/builder/testing/mock.go
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/error.go
  beacon-chain/cache/registration.go
  beacon-chain/cache/registration_test.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder_test.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  config/params/config.go
  config/params/mainnet_config.go
Labels: OK to merge, Builder, UX
