Repository OffchainLabs/prysm, pull requests merged in 2023-10, with the labels that each got.

#12976 Do Not Calculate Churn With 0 Exits
  beacon-chain/core/blocks/exit.go
Labels: Ready For Review, OK to merge

#12973 Remove go-playground/validator from Beacon API
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/structs.go
Labels: Ready For Review, OK to merge, API

#12853 [1/5] Light client sync protocol
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/lightclient.go
  beacon-chain/blockchain/lightclient_test.go
  beacon-chain/rpc/eth/beacon/blinded_blocks.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  beacon-chain/rpc/eth/helpers/error_handling.go
  beacon-chain/rpc/eth/rewards/BUILD.bazel
  beacon-chain/rpc/eth/rewards/handlers.go
  proto/eth/v2/BUILD.bazel
  proto/eth/v2/beacon_lightclient.pb.go
  proto/eth/v2/beacon_lightclient.pb.gw.go
  proto/eth/v2/beacon_lightclient.proto
  proto/eth/v2/custom.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
Labels: OK to merge

#12985 Tweak LastRoot to return head root
  beacon-chain/forkchoice/doubly-linked-tree/last_root.go
  beacon-chain/forkchoice/doubly-linked-tree/last_root_test.go
Labels: Ready For Review, OK to merge

#12986 Revert "Do not cache proposer ID on GetProposerDuties (#12939)"
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
Labels: Ready For Review, OK to merge

#12979 Handle hex in `Blocker`, `Stater` and optimistic mode checker
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  beacon-chain/rpc/eth/helpers/sync.go
  beacon-chain/rpc/eth/helpers/sync_test.go
  beacon-chain/rpc/lookup/BUILD.bazel
  beacon-chain/rpc/lookup/blocker.go
  beacon-chain/rpc/lookup/blocker_test.go
  beacon-chain/rpc/lookup/stater.go
  beacon-chain/rpc/lookup/stater_test.go
Labels: Ready For Review, OK to merge, API

#12971 Refactor churn limit helpers
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/helpers/weak_subjectivity.go
  beacon-chain/core/validators/validator.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_stream.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
Labels: Ready For Review, OK to merge

#12983 Don't mark block as bad in `validateBeaconBlock` for pending queue
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review, OK to merge

#12832 beacon-node/state: alloc 1more item for append case
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/setters_attestation.go
  beacon-chain/state/state-native/setters_attestation_test.go
  beacon-chain/state/state-native/setters_eth1.go
  beacon-chain/state/state-native/setters_eth1_test.go
  beacon-chain/state/state-native/setters_misc.go
  beacon-chain/state/state-native/setters_misc_test.go
  beacon-chain/state/state-native/setters_participation.go
  beacon-chain/state/state-native/setters_participation_test.go
  beacon-chain/state/state-native/setters_validator.go
  beacon-chain/state/state-native/setters_validator_test.go
Labels: OK to merge

#12996 Don't prune proposer ID cache in a loop
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
Labels: Bug, Ready For Review, OK to merge

#12989 Remove remote slashing protection feature
  beacon-chain/rpc/prysm/v1alpha1/slasher/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/slasher/attestations.go
  beacon-chain/rpc/prysm/v1alpha1/slasher/attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/slasher/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/slasher/server.go
  beacon-chain/rpc/prysm/v1alpha1/slasher/server_test.go
  beacon-chain/slasher/BUILD.bazel
  beacon-chain/slasher/mock/BUILD.bazel
  beacon-chain/slasher/mock/mock_slashing_checker.go
  beacon-chain/slasher/service_test.go
  config/features/config.go
  config/features/config_test.go
  config/features/flags.go
  proto/prysm/v1alpha1/slasher.pb.go
  proto/prysm/v1alpha1/slasher.pb.gw.go
  proto/prysm/v1alpha1/slasher.proto
  testing/mock/BUILD.bazel
  testing/mock/slasher_client_mock.go
  testing/validator-mock/BUILD.bazel
  testing/validator-mock/slasher_client_mock.go
  validator/client/BUILD.bazel
  validator/client/attest_protect.go
  validator/client/attest_protect_test.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_slasher_client.go
  validator/client/grpc-api/BUILD.bazel
  validator/client/grpc-api/grpc_slasher_client.go
  validator/client/iface/BUILD.bazel
  validator/client/iface/slasher_client.go
  validator/client/propose_protect.go
  validator/client/propose_protect_test.go
  validator/client/propose_test.go
  validator/client/service.go
  validator/client/slasher-client-factory/BUILD.bazel
  validator/client/slasher-client-factory/slasher_client_factory.go
  validator/client/validator.go
  validator/testing/BUILD.bazel
  validator/testing/mock_slasher.go
Labels: OK to merge, Cleanup

#12995 Use middleware to handle comma-separated query params
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/node/router.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_validator.go
  beacon-chain/rpc/eth/beacon/handlers_validators_test.go
  beacon-chain/rpc/eth/blob/BUILD.bazel
  beacon-chain/rpc/eth/blob/handlers.go
  beacon-chain/rpc/eth/blob/handlers_test.go
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/prysm/validator/validator_count.go
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
Labels: API

#13008 Build Blocks in Parallel Permanently
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
  proto/prysm/v1alpha1/slasher.pb.go
  proto/prysm/v1alpha1/slasher.pb.gw.go
Labels: Ready For Review

#13000 Fix Long Running E2E
  testing/endtoend/evaluators/operations.go
Labels: OK to merge, E2E Tests

#13007 Fix Initial Sync PreProcessing
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/round_robin_test.go
Labels: Ready For Review, Priority: High, OK to merge, Sync, Release Issue

#13009 update go 1.20.9
  WORKSPACE
Labels: Ready For Review, OK to merge, Security

#12549 Using the multi value slice for the beacon state
  beacon-chain/blockchain/metrics_test.go
  beacon-chain/core/altair/reward_test.go
  beacon-chain/core/blocks/randao.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/helpers/sync_committee_test.go
  beacon-chain/core/transition/state.go
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  beacon-chain/rpc/eth/beacon/state_test.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/state/fieldtrie/BUILD.bazel
  beacon-chain/state/fieldtrie/field_trie.go
  beacon-chain/state/fieldtrie/field_trie_helpers.go
  beacon-chain/state/fieldtrie/field_trie_test.go
  beacon-chain/state/fieldtrie/helpers_test.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/beacon_state_mainnet.go
  beacon-chain/state/state-native/beacon_state_minimal.go
  beacon-chain/state/state-native/custom-types/block_roots.go
  beacon-chain/state/state-native/custom-types/block_roots_test.go
  beacon-chain/state/state-native/custom-types/historical_roots.go
  beacon-chain/state/state-native/custom-types/randao_mixes.go
  beacon-chain/state/state-native/custom-types/randao_mixes_test.go
  beacon-chain/state/state-native/custom-types/state_roots.go
  beacon-chain/state/state-native/custom-types/state_roots_test.go
  beacon-chain/state/state-native/getters_block.go
  beacon-chain/state/state-native/getters_misc.go
  beacon-chain/state/state-native/getters_participation.go
  beacon-chain/state/state-native/getters_randao.go
  beacon-chain/state/state-native/getters_state.go
  beacon-chain/state/state-native/getters_validator.go
  beacon-chain/state/state-native/getters_validator_test.go
  beacon-chain/state/state-native/getters_withdrawal.go
  beacon-chain/state/state-native/hasher.go
  beacon-chain/state/state-native/multi_value_slices.go
  beacon-chain/state/state-native/mvslice_fuzz_test.go
  beacon-chain/state/state-native/references_test.go
  beacon-chain/state/state-native/setters_block.go
  beacon-chain/state/state-native/setters_randao.go
  beacon-chain/state/state-native/setters_state.go
  beacon-chain/state/state-native/setters_validator.go
  beacon-chain/state/state-native/state_trie.go
  beacon-chain/state/state-native/types.go
  beacon-chain/state/state-native/types/BUILD.bazel
  beacon-chain/state/state-native/types/types.go
  beacon-chain/state/state-native/types_test.go
  beacon-chain/state/stategen/migrate_test.go
  beacon-chain/state/stategen/mock_test.go
  config/features/config.go
  config/features/flags.go
  consensus-types/types.go
  container/multi-value-slice/BUILD.bazel
  container/multi-value-slice/interfaces/BUILD.bazel
  container/multi-value-slice/interfaces/interfaces.go
  container/multi-value-slice/multi_value_slice.go
  container/multi-value-slice/multi_value_slice_test.go
  runtime/interop/premine-state.go
Labels: Ready For Review, OK to merge

#13014 Optimize Exits Gossip Validation
  beacon-chain/sync/validate_voluntary_exit.go
Labels: Ready For Review, OK to merge

#12826 beacon-chain/execution: no need to reread and unmarshal the eth1Data twice
  beacon-chain/execution/service.go
  beacon-chain/execution/service_test.go
Labels: OK to merge

#13012 Check blob exists before requesting from peer
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
Labels: Ready For Review, OK to merge, Deneb

#13013 Check block exists in pending queue before requesting from peer
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_blocks_queue.go
Labels: Ready For Review, OK to merge

#13022 Fix missing docker dependencies
  tools/image_deps.bzl
Labels: Ready For Review, OK to merge

#13019 Fix comment of `BlobSidecarsBySlot`
  beacon-chain/db/kv/blob.go
Labels: Ready For Review, OK to merge

#13027 Improvements to `produceBlockV3`
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/eth/validator/handlers_block_test.go
Labels: Ready For Review, OK to merge, API

#13016 beacon-chain/execution: fix a data race in testcase
  beacon-chain/execution/block_reader_test.go
Labels: OK to merge

#12963 HTTP API: `/eth/v1/beacon/pool/bls_to_execution_changes`
  api/client/beacon/BUILD.bazel
  api/client/beacon/client.go
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  beacon-chain/rpc/eth/beacon/pool.go
  beacon-chain/rpc/eth/beacon/pool_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/service.go
  cmd/prysmctl/validator/BUILD.bazel
  cmd/prysmctl/validator/withdraw.go
  cmd/prysmctl/validator/withdraw_test.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/service/beacon_debug_service.pb.gw.go
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.proto
  proto/eth/v1/BUILD.bazel
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  proto/eth/v2/BUILD.bazel
  proto/eth/v2/beacon_chain.pb.go
  proto/eth/v2/beacon_chain.proto
  proto/eth/v2/withdrawals.pb.go
  proto/eth/v2/withdrawals.proto
  proto/prysm/v1alpha1/beacon_chain.pb.gw.go
  proto/prysm/v1alpha1/debug.pb.gw.go
  proto/prysm/v1alpha1/health.pb.gw.go
  proto/prysm/v1alpha1/node.pb.gw.go
  proto/prysm/v1alpha1/slasher.pb.gw.go
  proto/prysm/v1alpha1/validator-client/keymanager.pb.gw.go
  proto/prysm/v1alpha1/validator-client/web_api.pb.gw.go
  proto/prysm/v1alpha1/validator.pb.gw.go
  testing/endtoend/evaluators/BUILD.bazel
  testing/endtoend/evaluators/operations.go
  validator/client/beacon-api/beacon_block_json_helpers.go
  validator/client/beacon-api/beacon_block_json_helpers_test.go
Labels: OK to merge, API

#13026 Refactor Pending Block Queue Logic in Sync Package
  beacon-chain/sync/pending_blocks_queue.go
Labels: Ready For Review, Priority: High, OK to merge

#13010 HTTP Beacon APIs for node
  beacon-chain/gateway/helpers.go
  beacon-chain/gateway/helpers_test.go
  beacon-chain/rpc/apimiddleware/BUILD.bazel
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/node/BUILD.bazel
  beacon-chain/rpc/eth/node/handlers.go
  beacon-chain/rpc/eth/node/handlers_peers.go
  beacon-chain/rpc/eth/node/handlers_peers_test.go
  beacon-chain/rpc/eth/node/handlers_test.go
  beacon-chain/rpc/eth/node/node.go
  beacon-chain/rpc/eth/node/node_test.go
  beacon-chain/rpc/eth/node/server_test.go
  beacon-chain/rpc/eth/node/structs.go
  beacon-chain/rpc/service.go
  proto/eth/service/BUILD.bazel
  proto/eth/service/node_service.pb.go
  proto/eth/service/node_service.pb.gw.go
  proto/eth/service/node_service.proto
  proto/eth/v1/node.pb.go
  proto/eth/v1/node.proto
  testing/endtoend/evaluators/beaconapi_evaluators/BUILD.bazel
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/beacon_api_node_client.go
  validator/client/beacon-api/beacon_api_node_client_test.go
  validator/client/beacon-api/doppelganger_test.go
  validator/client/beacon-api/status_test.go
  validator/client/beacon-api/submit_aggregate_selection_proof_test.go
  validator/client/beacon-api/validator_count_test.go
Labels: API

#13015 Request missing blobs while processing pending queue
  beacon-chain/sync/pending_blocks_queue.go
Labels: Ready For Review, OK to merge, Deneb

#13038 Exit early if blob by root request is empty
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
Labels: Ready For Review, OK to merge, Deneb

#13001 HTTP Beacon APIs: 3 state endpoints
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_state.go
  beacon-chain/rpc/eth/beacon/handlers_state_test.go
  beacon-chain/rpc/eth/beacon/state.go
  beacon-chain/rpc/eth/beacon/state_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/beacon/sync_committee.go
  beacon-chain/rpc/eth/beacon/sync_committee_test.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  proto/eth/v1/node.pb.go
  proto/eth/v1/node.proto
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/eth/v2/sync_committee.pb.go
  proto/eth/v2/sync_committee.proto
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/evaluators/BUILD.bazel
  testing/endtoend/evaluators/api_middleware.go
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
Labels: Ready For Review, OK to merge, API

#13043 Add more blob and block checks for by range
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
Labels: Ready For Review, OK to merge, Deneb

#13045 Remove confusing comment
  beacon-chain/state/stategen/setter.go
Labels: Ready For Review, OK to merge

#13047 Reject blobs with invalid parent
  beacon-chain/sync/validate_blob.go
  beacon-chain/sync/validate_blob_test.go
Labels: Bug, Ready For Review, OK to merge

#12999 fix(beacon-chain/rpc): blob_sidecar event stream handler
  beacon-chain/rpc/apimiddleware/custom_handlers.go
Labels: OK to merge

#13034 Add state not found test case
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/shared/BUILD.bazel
  beacon-chain/rpc/eth/shared/errors.go
  beacon-chain/rpc/eth/shared/errors_test.go
Labels: OK to merge

#13044 Verify blobs that arrived from by root request
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/verify/BUILD.bazel
  beacon-chain/sync/verify/blob.go
  beacon-chain/sync/verify/blob_test.go
Labels: Ready For Review, OK to merge, Deneb

#12956 Proposer: better handling of blobs bundle
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
Labels: Ready For Review, OK to merge, Cleanup

#12767 Deneb - web3signer
  config/params/loader.go
  encoding/ssz/htrutils.go
  encoding/ssz/htrutils_test.go
  testing/endtoend/components/web3remotesigner.go
  testing/endtoend/deps.bzl
  validator/keymanager/remote-web3signer/README.md
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/keymanager_test.go
  validator/keymanager/remote-web3signer/metrics.go
  validator/keymanager/remote-web3signer/v1/BUILD.bazel
  validator/keymanager/remote-web3signer/v1/mock/BUILD.bazel
  validator/keymanager/remote-web3signer/v1/mock/mocks.go
  validator/keymanager/remote-web3signer/v1/requests.go
  validator/keymanager/remote-web3signer/v1/requests_test.go
  validator/keymanager/remote-web3signer/v1/web3signer_types.go
Labels: OK to merge, Web3Signer, Deneb

#13056 remove bad comment
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
Labels: Ready For Review, OK to merge

#13032 HTTP VALIDATOR API: `/eth/v1/validator/{pubkey}/voluntary_exit`
  api/server/BUILD.bazel
  api/server/middleware.go
  api/server/util.go
  api/server/util_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.pb.gw.go
  proto/eth/service/key_management.proto
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/apimiddleware/BUILD.bazel
  validator/rpc/apimiddleware/custom_hooks.go
  validator/rpc/apimiddleware/custom_hooks_test.go
  validator/rpc/apimiddleware/endpoint_factory.go
  validator/rpc/apimiddleware/structs.go
  validator/rpc/handlers_keymanager.go
  validator/rpc/handlers_keymanager_test.go
  validator/rpc/server.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
  validator/rpc/structs.go
Labels: Ready For Review, OK to merge, API, Cleanup

#13050 Fix blob_sidecar SSE payload
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/structs.go
Labels: OK to merge

#13005 Add pending blobs queue for missing parent block
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/node/node.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/options.go
  beacon-chain/sync/pending_blobs_queue.go
  beacon-chain/sync/pending_blobs_queue_test.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_blob.go
  beacon-chain/sync/validate_bls_to_execution_change_test.go
  beacon-chain/sync/validate_sync_committee_message_test.go
  beacon-chain/sync/validate_sync_contribution_proof_test.go
Labels: Ready For Review, OK to merge, Deneb

#13061 Use correct context for `sendBatchRootRequest`
  beacon-chain/sync/validate_blob.go
Labels: Bug, Ready For Review, Deneb

#13062 Passing block as arugment for sidecar validation
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
Labels: Bug, Ready For Review, OK to merge, Deneb

#13057 CLEANUP: validator exit prompt
  cmd/validator/accounts/exit_test.go
  io/prompt/validate.go
  io/prompt/validate_test.go
  validator/accounts/accounts_exit.go
  validator/accounts/accounts_exit_test.go
  validator/accounts/accounts_helper.go
Labels: OK to merge, Cleanup, prysmctl

#13066 Fix Withdrawals Marshalling
  proto/engine/v1/json_marshal_unmarshal.go
Labels: Ready For Review, OK to merge

#13073 rpc/apimiddleware: Test all paths can be created
  beacon-chain/rpc/apimiddleware/BUILD.bazel
  beacon-chain/rpc/apimiddleware/endpoint_factory_test.go
Labels: Ready For Review, OK to merge, API

#13077 Set Verbosity of Goodbye Logs to Trace
  beacon-chain/rpc/apimiddleware/endpoint_factory_test.go
  beacon-chain/rpc/eth/beacon/blinded_blocks_test.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/sync/rpc_goodbye.go
  cmd/prysmctl/p2p/handler.go
  proto/prysm/v1alpha1/slasher.pb.gw.go
Labels: Ready For Review, OK to merge, UX

#13053 Fix typos
  beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go
  prysm.bat
Labels: OK to merge

#13068 Set Better Slice Capacities in the State
  beacon-chain/state/state-native/getters_validator.go
  beacon-chain/state/state-native/setters_participation.go
  beacon-chain/state/state-native/setters_validator.go
Labels: Ready For Review, OK to merge

#13059 HTTP VALIDATOR API: remote keymanager api `/eth/v1/remotekeys`
  api/client/validator/BUILD.bazel
  api/client/validator/client.go
  cmd/prysmctl/validator/BUILD.bazel
  cmd/prysmctl/validator/cmd.go
  cmd/prysmctl/validator/proposer_settings_test.go
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.pb.gw.go
  proto/eth/service/key_management.proto
  validator/keymanager/BUILD.bazel
  validator/keymanager/constants.go
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/keymanager_test.go
  validator/keymanager/types.go
  validator/rpc/BUILD.bazel
  validator/rpc/apimiddleware/endpoint_factory.go
  validator/rpc/apimiddleware/structs.go
  validator/rpc/apimiddleware/structs_test.go
  validator/rpc/handlers_keymanager.go
  validator/rpc/handlers_keymanager_test.go
  validator/rpc/server.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
  validator/rpc/structs.go
Labels: Ready For Review, OK to merge, API, Cleanup

#13067 Add Clarification To Sync Committee Cache
  beacon-chain/operations/synccommittee/message.go
Labels: Ready For Review, OK to merge

#13023 docs: fix typo
  monitoring/prometheus/README.md
Labels: OK to merge

#13076 Fix redundant type converstion
  api/client/builder/client_test.go
  beacon-chain/blockchain/lightclient.go
  beacon-chain/db/kv/blob_test.go
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/shared/structs_blocks_conversions.go
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/state/state-native/setters_attestation.go
  beacon-chain/state/state-native/setters_attestation_test.go
  beacon-chain/state/stateutil/field_root_attestation.go
  beacon-chain/sync/rpc_handler_test.go
  beacon-chain/sync/service.go
  crypto/bls/signature_batch_test.go
  proto/eth/v2/custom.go
  testing/middleware/builder/builder.go
Labels: Ready For Review, OK to merge, Cleanup

#13083 sync only up to previous epoch on phase 1
  beacon-chain/sync/initial-sync/round_robin.go
Labels: Ready For Review

#13087 Fix Multivalue Slice Deadlock
  beacon-chain/state/state-native/references_test.go
  beacon-chain/state/state-native/setters_validator.go
  beacon-chain/sync/backfill/status_test.go
Labels: Ready For Review, Priority: High, OK to merge

#13018 beacon-node/rpc: fix go test datarace
  beacon-chain/p2p/testing/mock_broadcaster.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  beacon-chain/rpc/eth/beacon/pool_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/slashings_test.go
Labels: OK to merge

#13091 Fix Builder Testing For Multiclient Runs
  testing/endtoend/component_handler_test.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/components/lighthouse_validator.go
Labels: Ready For Review, OK to merge, E2E Tests

#13092 Refactor Error String Formatting According to Go Best Practices
  cmd/prysmctl/deprecated/checkpoint/latest.go
  cmd/prysmctl/deprecated/checkpoint/save.go
  validator/accounts/accounts_import.go
Labels: Ready For Review, OK to merge, Cleanup

#13082 HTTP Validator API: `/eth/v1/validator/{pubkey}/gas_limit`
  api/server/BUILD.bazel
  api/server/middleware_test.go
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.pb.gw.go
  proto/eth/service/key_management.proto
  validator/rpc/BUILD.bazel
  validator/rpc/apimiddleware/endpoint_factory.go
  validator/rpc/apimiddleware/structs.go
  validator/rpc/handlers_keymanager.go
  validator/rpc/handlers_keymanager_test.go
  validator/rpc/server.go
  validator/rpc/server_test.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
  validator/rpc/structs.go
Labels: Ready For Review, OK to merge, API, Cleanup

#13093 Replace Empty Slice Literals with Nil Slices
  beacon-chain/cache/depositsnapshot/deposit_cache_test.go
  beacon-chain/execution/engine_client.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/peers/peerdata/store.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/rpc/prysm/node/handlers.go
  cmd/prysmctl/deprecated/cmd.go
  cmd/validator/wallet/create.go
  config/features/deprecated_flags.go
  crypto/bls/blst/public_key_test.go
  runtime/version/fork.go
  testing/endtoend/evaluators/operations.go
  testing/middleware/builder/builder.go
  validator/client/beacon-api/activation.go
  validator/client/beacon-api/status.go
Labels: Ready For Review, OK to merge, Cleanup

#13036 beacon-chain/blockchain: fix some datarace in go test
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/setup_test.go
Labels: OK to merge

#13102 Fix blob sidecar subnet check
  beacon-chain/sync/validate_blob.go
Labels: Ready For Review, OK to merge, Deneb

#13098 Replace MAX_BLOB_EPOCHS usages with more accurate terms
  beacon-chain/db/kv/blob.go
Labels: OK to merge

#13106 Check return and request lengths for blob sidecar by root
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
Labels: Ready For Review, OK to merge, Deneb

#13085 HTTP Validator API: `/eth/v1/validator/{pubkey}/feerecipient`
  api/client/validator/client.go
  cmd/prysmctl/validator/proposer_settings_test.go
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.pb.gw.go
  proto/eth/service/key_management.proto
  validator/rpc/apimiddleware/endpoint_factory.go
  validator/rpc/apimiddleware/structs.go
  validator/rpc/handlers_keymanager.go
  validator/rpc/handlers_keymanager_test.go
  validator/rpc/server.go
  validator/rpc/server_test.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
  validator/rpc/structs.go
Labels: Ready For Review, OK to merge, API, Cleanup

#13104 Fix Pending Queue Expiration Bug
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/pending_blocks_queue_test.go
  beacon-chain/sync/service.go
Labels: Ready For Review, Priority: High, OK to merge, Deneb

#13094 Reject Blob Sidecar Incorrect Index
  beacon-chain/sync/validate_blob.go
  beacon-chain/sync/validate_blob_test.go
Labels: Ready For Review, OK to merge, Deneb

#13100 Fix bug in Beacon API getBlobs
  beacon-chain/rpc/eth/blob/handlers.go
  beacon-chain/rpc/eth/blob/handlers_test.go
Labels: OK to merge

#13111 Log blob's kzg commmitment at sync
  beacon-chain/sync/validate_blob.go
Labels: Ready For Review, OK to merge, Deneb

#13099 HTTP state endpoints
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/debug/BUILD.bazel
  beacon-chain/rpc/eth/debug/debug.go
  beacon-chain/rpc/eth/debug/debug_test.go
  beacon-chain/rpc/eth/debug/handlers.go
  beacon-chain/rpc/eth/debug/handlers_test.go
  beacon-chain/rpc/eth/debug/structs.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/shared/structs_blocks.go
  beacon-chain/rpc/eth/shared/structs_blocks_conversions.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_debug_service.pb.go
  proto/eth/service/beacon_debug_service.pb.gw.go
  proto/eth/service/beacon_debug_service.proto
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  testing/endtoend/evaluators/BUILD.bazel
  testing/endtoend/evaluators/beaconapi_evaluators/BUILD.bazel
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
  testing/endtoend/evaluators/validator.go
Labels: Ready For Review, OK to merge, API

#13114 Add context deadline for pending queue's receive block
  beacon-chain/sync/pending_blocks_queue.go
Labels: Ready For Review, OK to merge

#13117 Add zero length check on indices during NextSyncCommitteeIndices
  beacon-chain/core/altair/sync_committee_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/assignments_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go
Labels: OK to merge

#13120 Update go to 1.20.10
  WORKSPACE
Labels: OK to merge

#13121 Fill state attestations
  beacon-chain/rpc/eth/debug/structs.go
Labels: Ready For Review, OK to merge

#13126 fix segmentation fork when Capella for epoch is MaxUint64
  cmd/prysmctl/testnet/generate_genesis.go
Labels: OK to merge

#13123 Check blob index duplication for blob notifier
  beacon-chain/blockchain/receive_blob.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: Bug, OK to merge, Deneb

#13084 Better Beacon API evaluator part 1
  beacon-chain/rpc/service.go
  testing/endtoend/evaluators/beaconapi_evaluators/BUILD.bazel
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api_verify.go
  testing/endtoend/evaluators/beaconapi_evaluators/util.go
  testing/endtoend/policies/policies.go
Labels: Ready For Review, OK to merge, E2E Tests

#13127 DEPRECTATION: Remove exchange transition configuration call
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/check_transition_config.go
  beacon-chain/execution/check_transition_config_test.go
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_fuzz_test.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/metrics.go
  beacon-chain/execution/service.go
  beacon-chain/execution/testing/mock_engine_client.go
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
  testing/middleware/builder/builder.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, OK to merge, API, Cleanup, Deneb

#13090 Update spectest and changed minimal preset for field elements
  WORKSPACE
  beacon-chain/blockchain/kzg/trusted_setup.json
  deps.bzl
  go.mod
  go.sum
  proto/ssz_proto_library.bzl
Labels: Ready For Review, OK to merge, Deneb

#13137 Log when sending FCU with payload attributes
  beacon-chain/blockchain/execution_engine.go
Labels: Ready For Review, OK to merge

#13138 Remove `/node/peers/{peer_id}` from Beacon API evaluator
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go
Labels: Ready For Review, OK to merge, E2E Tests

#13069 Remove no-op cancel func
  validator/client/runner.go
Labels: OK to merge

#13124 Rename Blob retention epoch flag
  beacon-chain/db/kv/flags_test.go
  cmd/beacon-chain/flags/base.go
Labels: OK to merge, Cleanup

#13116 Fix block proposals in the REST validator client
  testing/endtoend/minimal_builder_e2e_test.go
  validator/client/beacon-api/get_beacon_block.go
  validator/client/beacon-api/get_beacon_block_test.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/json_rest_handler_test.go
  validator/client/beacon-api/test-helpers/BUILD.bazel
  validator/client/beacon-api/test-helpers/bellatrix_beacon_block_test_helpers.go
  validator/client/beacon-api/test-helpers/capella_beacon_block_test_helpers.go
  validator/client/beacon-api/test-helpers/deneb_beacon_block_test_helpers.go
  validator/client/propose.go
  validator/client/propose_test.go
Labels: Ready For Review, OK to merge, Validator Client

#13142 zig: Update zig to recent main branch commit
  WORKSPACE
Labels: OK to merge

#13145 Fix Pending Queue Deadline Bug
  beacon-chain/sync/pending_blocks_queue.go
Labels: Ready For Review, OK to merge, Sync

#13113 HTTP Validator API: `/eth/v1/keystores`
  api/client/validator/BUILD.bazel
  api/client/validator/client.go
  api/gateway/BUILD.bazel
  api/gateway/gateway.go
  cmd/prysmctl/validator/BUILD.bazel
  cmd/prysmctl/validator/proposer_settings_test.go
  proto/eth/service/BUILD.bazel
  proto/eth/service/key_management.pb.go
  proto/eth/service/key_management.pb.gw.go
  proto/eth/service/key_management.proto
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_delete_test.go
  validator/accounts/accounts_import.go
  validator/accounts/accounts_import_test.go
  validator/accounts/cli_manager.go
  validator/accounts/cli_options.go
  validator/client/BUILD.bazel
  validator/client/validator_test.go
  validator/keymanager/BUILD.bazel
  validator/keymanager/derived/BUILD.bazel
  validator/keymanager/derived/keymanager.go
  validator/keymanager/local/BUILD.bazel
  validator/keymanager/local/delete.go
  validator/keymanager/local/delete_test.go
  validator/keymanager/local/import.go
  validator/keymanager/local/import_test.go
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/keymanager_test.go
  validator/keymanager/types.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/apimiddleware/BUILD.bazel
  validator/rpc/apimiddleware/endpoint_factory.go
  validator/rpc/apimiddleware/structs.go
  validator/rpc/apimiddleware/structs_test.go
  validator/rpc/handlers_keymanager.go
  validator/rpc/handlers_keymanager_test.go
  validator/rpc/server.go
  validator/rpc/server_test.go
  validator/rpc/standard_api.go
  validator/rpc/standard_api_test.go
  validator/rpc/structs.go
  validator/rpc/wallet_test.go
Labels: Ready For Review, OK to merge, API, Cleanup, Validator Client

#13150 pgo: remove default pprof profile
  cmd/beacon-chain/BUILD.bazel
  cmd/beacon-chain/pprof.beacon-chain.samples.cpu.pb.gz
Labels: OK to merge
