Repository OffchainLabs/prysm, pull requests merged in 2023-08, with the labels that each got.

#12677 fix: update nil check for new validator
  beacon-chain/state/state-native/readonly_validator.go
Labels: Ready For Review, OK to merge

#12650 add metric to check if validator is in next sync commitee
  validator/client/metrics.go
  validator/client/validator.go
Labels: OK to merge

#12681 test: add missing random and fork transition spec tests
  testing/spectest/mainnet/bellatrix/random/BUILD.bazel
  testing/spectest/mainnet/bellatrix/random/random_test.go
  testing/spectest/mainnet/capella/random/BUILD.bazel
  testing/spectest/mainnet/capella/random/random_test.go
  testing/spectest/minimal/altair/fork_transition/BUILD.bazel
  testing/spectest/minimal/altair/fork_transition/transition_test.go
  testing/spectest/minimal/bellatrix/fork_transition/BUILD.bazel
  testing/spectest/minimal/bellatrix/fork_transition/transition_test.go
  testing/spectest/minimal/bellatrix/random/BUILD.bazel
  testing/spectest/minimal/bellatrix/random/random_test.go
  testing/spectest/minimal/capella/fork_transition/BUILD.bazel
  testing/spectest/minimal/capella/fork_transition/transition_test.go
  testing/spectest/minimal/capella/random/BUILD.bazel
  testing/spectest/minimal/capella/random/random_test.go
Labels: Ready For Review, OK to merge

#12679 Update caches blocking
  beacon-chain/blockchain/process_block.go
Labels: OK to merge

#12685 test: add execution payload operation tests
  testing/spectest/mainnet/bellatrix/operations/BUILD.bazel
  testing/spectest/mainnet/bellatrix/operations/execution_payload_test.go
  testing/spectest/mainnet/capella/operations/BUILD.bazel
  testing/spectest/mainnet/capella/operations/execution_payload_test.go
  testing/spectest/minimal/bellatrix/operations/BUILD.bazel
  testing/spectest/minimal/bellatrix/operations/execution_payload_test.go
  testing/spectest/minimal/capella/operations/BUILD.bazel
  testing/spectest/minimal/capella/operations/execution_payload_test.go
  testing/spectest/shared/bellatrix/operations/BUILD.bazel
  testing/spectest/shared/bellatrix/operations/execution_payload.go
  testing/spectest/shared/capella/operations/BUILD.bazel
  testing/spectest/shared/capella/operations/execution_payload.go
Labels: Ready For Review, OK to merge

#12691 Fix: use correct context for `UpdateCommitteeCache`
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge

#12687 Remove: span for convert to indexed attestation
  proto/prysm/v1alpha1/attestation/attestation_utils.go
Labels: Ready For Review, OK to merge

#12686 HTTP Beacon API: `/eth/v1/validator/aggregate_and_proofs`
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/core/BUILD.bazel
  beacon-chain/rpc/core/log.go
  beacon-chain/rpc/core/validator.go
  beacon-chain/rpc/eth/shared/BUILD.bazel
  beacon-chain/rpc/eth/shared/errors.go
  beacon-chain/rpc/eth/shared/errors_test.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/eth/validator/structs.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go
  beacon-chain/rpc/service.go
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator.proto
Labels: Ready For Review, OK to merge, API

#12440 refactor slot tickers with intervals
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  time/slots/slotticker.go
Labels: Ready For Review

#12616 Multi Value Slice
  container/multi-value-slice/BUILD.bazel
  container/multi-value-slice/interfaces/BUILD.bazel
  container/multi-value-slice/interfaces/interfaces.go
  container/multi-value-slice/multi_value_slice.go
  container/multi-value-slice/multi_value_slice_test.go
Labels: Ready For Review, OK to merge

#12697 Prevent Pubkey Cache From Overwhelming the Go Runtime
  cache/nonblocking/lru.go
Labels: Ready For Review

#12699 Feat: aggregate parallel default
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: OK to merge

#12599 Fix prysmctl writing empty JSON/YAML files
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/beacon_state_mainnet.go
  beacon-chain/state/state-native/beacon_state_minimal.go
Labels: Ready For Review, OK to merge

#12707 Update go to 1.20.7
  WORKSPACE
Labels: Ready For Review, OK to merge

#12570 feat: implement eip4788
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  consensus-types/payload-attribute/getters.go
  consensus-types/payload-attribute/getters_test.go
  consensus-types/payload-attribute/interface.go
  consensus-types/payload-attribute/types.go
  deps.bzl
  go.mod
  go.sum
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/json_marshal_unmarshal.go
  proto/eth/service/validator_service.pb.go
  proto/eth/v1/validator.pb.go
  proto/eth/v2/validator.pb.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Deneb

#12689 HTTP Beacon API: `/eth/v1/validator/sync_committee_subscriptions`
  beacon-chain/rpc/apimiddleware/BUILD.bazel
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  beacon-chain/rpc/eth/helpers/sync.go
  beacon-chain/rpc/eth/shared/BUILD.bazel
  beacon-chain/rpc/eth/shared/request.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/eth/validator/structs.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/service.go
  consensus-types/validator/BUILD.bazel
  consensus-types/validator/types.go
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
  proto/eth/v2/validator.pb.go
  proto/eth/v2/validator.proto
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/beacon_api_node_client_test.go
  validator/client/beacon-api/doppelganger_test.go
  validator/client/beacon-api/submit_aggregate_selection_proof_test.go
Labels: Ready For Review, OK to merge, API

#12706 HTTP Beacon API: `/eth/v1/node/syncing`
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/eth/node/BUILD.bazel
  beacon-chain/rpc/eth/node/handlers.go
  beacon-chain/rpc/eth/node/handlers_test.go
  beacon-chain/rpc/eth/node/node.go
  beacon-chain/rpc/eth/node/node_test.go
  beacon-chain/rpc/eth/node/structs.go
  beacon-chain/rpc/service.go
  proto/eth/service/node_service.pb.go
  proto/eth/service/node_service.pb.gw.go
  proto/eth/service/node_service.proto
  proto/eth/v1/node.pb.go
  proto/eth/v1/node.proto
Labels: Ready For Review, API

#12717 Update BLST to v0.3.11
  deps.bzl
  go.mod
  go.sum
  third_party/blst/blst.BUILD
Labels: Ready For Review, Security

#12700 HTTP Beacon API: `/eth/v1/validator/beacon_committee_subscriptions`
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/core/BUILD.bazel
  beacon-chain/rpc/core/validator.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/validator.go
  beacon-chain/rpc/eth/beacon/validator_test.go
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  beacon-chain/rpc/eth/helpers/validator_status.go
  beacon-chain/rpc/eth/helpers/validator_status_test.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/eth/validator/structs.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go
  beacon-chain/rpc/service.go
  consensus-types/validator/types.go
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator.proto
Labels: Ready For Review, OK to merge, API

#12721 Update rules go & gazelle
  BUILD.bazel
  WORKSPACE
  build/bazel/BUILD.bazel
  config/fieldparams/BUILD.bazel
  config/params/BUILD.bazel
  crypto/bls/blst/BUILD.bazel
  deps.bzl
  encoding/ssz/htrutils_fuzz_test.go
  nogo_config.json
Labels: Ready For Review, OK to merge, Tools

#12725 Update bazel to 6.3.2
  .bazelversion
Labels: CI, OK to merge

#12723 feat: log blob commitment count
  beacon-chain/blockchain/log.go
  validator/client/propose.go
Labels: Ready For Review

#12730 feat: add validator blob signing
  consensus-types/blocks/testing/factory.go
  validator/client/BUILD.bazel
  validator/client/blob.go
  validator/client/blob_test.go
  validator/client/propose.go
  validator/client/propose_test.go
Labels: Ready For Review, Deneb

#12736 fix: payload attribute v3 return nil
  consensus-types/payload-attribute/getters.go
  consensus-types/payload-attribute/getters_test.go
Labels: Ready For Review, Deneb

#12726 deneb: fixing route handler and small cleanup items
  beacon-chain/rpc/eth/blob/BUILD.bazel
  beacon-chain/rpc/eth/blob/handlers.go
  beacon-chain/rpc/service.go
Labels: Deneb

#12734 feat: save blobs to db for subscriber
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/db/kv/blob.go
  beacon-chain/db/kv/blob_test.go
  beacon-chain/sync/subscriber_blob_sidecar.go
Labels: Ready For Review, Deneb

#12732 feat: add blob peer scoring params
  beacon-chain/p2p/gossip_scoring_params.go
Labels: Ready For Review, Deneb

#12739 Shift Error Logs To Debug
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_block.go
Labels: Ready For Review, OK to merge

#12748 set optimistic status in head at init sync
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/service_test.go
Labels: OK to merge

#12741 Use last optimistic status on batches
  beacon-chain/blockchain/receive_block.go
Labels: OK to merge

#12749 Remove Alpine Images From Prysm
  cmd/beacon-chain/BUILD.bazel
  cmd/prysmctl/BUILD.bazel
  cmd/validator/BUILD.bazel
Labels: Ready For Review, OK to merge

#12719 Remove uses of deprecated go_embed rules_go
  WORKSPACE
  validator/web/BUILD.bazel
Labels: OK to merge

#12751 test: skip deneb e2e test with tracking
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/evaluators/fork.go
  testing/endtoend/helpers/helpers.go
Labels: Ready For Review, Deneb

#12737 Remove quadratic loops when exiting
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/validators/BUILD.bazel
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
Labels: Ready For Review, OK to merge, optimization

#12704 fix(proposer): verify attestations without mutating state
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
Labels: OK to merge

#12735 HTTP Beacon API: `/pool/attestations`
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  beacon-chain/rpc/eth/beacon/pool.go
  beacon-chain/rpc/eth/beacon/pool_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/shared/errors.go
  beacon-chain/rpc/eth/shared/request.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/service.go
  network/http/writer.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
Labels: Ready For Review, OK to merge, API

#12763 add more descriptive log on FFG-LMD consistency
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review, OK to merge

#12758 REST implementation of `/eth/v1/validator/register_validator`
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/shared/BUILD.bazel
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator.proto
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/registration.go
  validator/client/beacon-api/registration_test.go
Labels: OK to merge, API, Cleanup

#12756 Add Github Go Fuzzing Workflow With Cron Schedule
  .github/workflows/fuzz.yml
Labels: Ready For Review, OK to merge

#12765 local-block-value-boost flag from float64 to uint64 [BREAKING CHANGE]
  cmd/beacon-chain/flags/base.go
Labels: OK to merge, Cleanup, UX

#12768 Update Fuzz List Timeout Github Workflow
  .github/workflows/fuzz.yml
Labels: Ready For Review, OK to merge

#12716 HTTP Beacon API: `/eth/v1/beacon/blocks/{block_id}/root`
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
  testing/endtoend/endtoend_test.go
Labels: Ready For Review, OK to merge, API

#12776 adding register validator route
  beacon-chain/rpc/service.go
Labels: OK to merge, API

#12777 HTTP implementation of voluntary exit pool endpoints
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  beacon-chain/rpc/eth/beacon/pool.go
  beacon-chain/rpc/eth/beacon/pool_test.go
  beacon-chain/rpc/eth/beacon/structs.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/service.go
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v1/beacon_chain.pb.go
  proto/eth/v1/beacon_chain.proto
Labels: Ready For Review, OK to merge, API

#12783 Add deneb config/params from deneb-integration
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/BUILD.bazel
  config/params/config.go
  config/params/interop.go
  config/params/loader.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  config/params/testdata/e2e_config.yaml
  config/params/testnet_e2e_config.go
  config/params/testnet_prater_config.go
  runtime/version/fork.go
Labels: OK to merge

#12787 chore: remove unused proto import
  proto/eth/v1/validator.proto
Labels: Ready For Review, OK to merge

#12792 Fix Sepolia Version
  config/params/testnet_sepolia_config.go
Labels: Ready For Review, OK to merge

#12795 fix: e2e config missmatch
  config/params/testdata/e2e_config.yaml
Labels: OK to merge

#12809 Add REST implementation of node version endpoint
  validator/client/beacon-api/beacon_api_node_client.go
  validator/client/beacon-api/beacon_api_node_client_test.go
Labels: OK to merge

#12814 fix: set current and prev epoch participations for interop genesis
  runtime/interop/premine-state.go
Labels: Ready For Review

#12808 Minor typo in CLI flag
  config/features/flags.go
Labels: OK to merge

#12811 fix: add back non parallel proposer
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb.go
Labels: Ready For Review

#12813 chore: improve att error
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
Labels: Ready For Review

#12818 beacon-chain/execution: use pointer instead of value to reduce copy
  beacon-chain/execution/log_processing.go
  beacon-chain/execution/log_processing_test.go
Labels: OK to merge

#12821 Holesky support
  WORKSPACE
  beacon-chain/node/node.go
  beacon-chain/state/stategen/errors.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/service.go
  cmd/beacon-chain/main.go
  cmd/prysmctl/validator/cmd.go
  cmd/validator/accounts/accounts.go
  cmd/validator/slashing-protection/slashing-protection.go
  cmd/validator/wallet/wallet.go
  config/features/config.go
  config/features/flags.go
  config/params/BUILD.bazel
  config/params/testnet_holesky_config.go
  config/params/testnet_holesky_config_test.go
  config/params/values.go
Labels: OK to merge

#12781 REST implementation of `/eth/v1/validator/prepare_beacon_proposer`
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/shared/BUILD.bazel
  beacon-chain/rpc/eth/shared/request.go
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/service.go
  proto/eth/service/validator_service.pb.go
  proto/eth/service/validator_service.pb.gw.go
  proto/eth/service/validator_service.proto
  proto/eth/v1/validator.pb.go
  proto/eth/v1/validator.proto
  validator/client/beacon-api/prepare_beacon_proposer.go
  validator/client/beacon-api/prepare_beacon_proposer_test.go
Labels: Ready For Review, OK to merge, API

#12834 config/params: Require placeholderFields to be sorted and distinct
  config/params/loader_test.go
Labels: OK to merge

#12790 fix fuzz testing
  .github/workflows/fuzz.yml
Labels: OK to merge
