Repository OffchainLabs/prysm, pull requests merged in 2023-12, with the labels that each got.

#13238 Optimize Multivalue Slice For Trie Recomputation
  beacon-chain/state/fieldtrie/BUILD.bazel
  beacon-chain/state/fieldtrie/field_trie.go
  beacon-chain/state/fieldtrie/field_trie_helpers.go
  beacon-chain/state/fieldtrie/field_trie_test.go
  beacon-chain/state/fieldtrie/helpers_test.go
  beacon-chain/state/state-native/multi_value_slices.go
  beacon-chain/state/state-native/state_trie.go
  container/multi-value-slice/BUILD.bazel
  container/multi-value-slice/multi_value_slice.go
  container/multi-value-slice/multi_value_slice_test.go
Labels: Ready For Review

#13249 track target in forkchoice
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/doubly-linked-tree/types.go
  beacon-chain/forkchoice/interfaces.go
Labels: Ready For Review, OK to merge

#13250 Verify lmd without ancestor
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
Labels: Ready For Review, OK to merge

#13233 Blob filesystem: delete blobs
  beacon-chain/db/filesystem/BUILD.bazel
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/blob_test.go
Labels: OK to merge, Deneb

#13242 Add test helpers to produce commitments and proofs
  beacon-chain/blockchain/kzg/BUILD.bazel
  beacon-chain/blockchain/kzg/validation_test.go
  go.mod
Labels: Ready For Review, OK to merge

#13191 HTTP validator API: beacon and account endpoints
  .github/workflows/go.yml
  api/BUILD.bazel
  api/constants.go
  beacon-chain/rpc/eth/shared/BUILD.bazel
  beacon-chain/rpc/eth/shared/structs.go
  beacon-chain/rpc/eth/shared/structs_validator.go
  nogo_config.json
  proto/prysm/v1alpha1/validator-client/BUILD.bazel
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
  proto/prysm/v1alpha1/validator-client/keymanager.pb.gw.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
  proto/prysm/v1alpha1/validator-client/web_api.pb.go
  proto/prysm/v1alpha1/validator-client/web_api.pb.gw.go
  proto/prysm/v1alpha1/validator-client/web_api.proto
  testing/endtoend/evaluators/api_gateway_v1alpha1.go
  testing/mock/BUILD.bazel
  testing/mock/keymanager_mock.go
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/accounts.go
  validator/rpc/accounts_test.go
  validator/rpc/auth_token.go
  validator/rpc/auth_token_test.go
  validator/rpc/beacon.go
  validator/rpc/beacon_test.go
  validator/rpc/handlers_accounts.go
  validator/rpc/handlers_accounts_test.go
  validator/rpc/handlers_auth.go
  validator/rpc/handlers_auth_test.go
  validator/rpc/handlers_beacon.go
  validator/rpc/handlers_beacon_test.go
  validator/rpc/handlers_keymanager.go
  validator/rpc/intercepter.go
  validator/rpc/server.go
  validator/rpc/server_test.go
  validator/rpc/structs.go
  validator/web/README.md
  validator/web/handler.go
Labels: OK to merge, API, Cleanup

#13252 Initialize cancellable root context in main.go
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
  cmd/beacon-chain/main.go
Labels: OK to merge

#13246 Update bazel and other CI improvements
  .bazelversion
  .buildkite-bazelrc
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  config/params/BUILD.bazel
  testing/README.md
Labels: Ready For Review, CI, OK to merge

#13258 Fix FFG LMD Consistency Check (Option 2)
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
  beacon-chain/forkchoice/interfaces.go
Labels: Ready For Review, OK to merge

#13244 forkchoice.Getter wrapper with locking wrappers
  beacon-chain/forkchoice/BUILD.bazel
  beacon-chain/forkchoice/interfaces.go
  beacon-chain/forkchoice/ro.go
  beacon-chain/forkchoice/ro_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
Labels: OK to merge

#13261 Remove Redundant Hash Computation in Cache
  beacon-chain/operations/attestations/kv/unaggregated.go
Labels: Ready For Review

#13218 Add `--jwt-id` flag
  beacon-chain/execution/options.go
  beacon-chain/execution/service.go
  beacon-chain/node/node.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  network/auth.go
  network/auth_test.go
  network/endpoint.go
  testing/middleware/builder/builder.go
  testing/middleware/engine-api-proxy/proxy.go
Labels: OK to merge

#13271 blobstorage: Improve mkdirall error
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/blob_test.go
Labels: Ready For Review, OK to merge

#13147 Blob filesystem: prune blobs
  beacon-chain/db/filesystem/BUILD.bazel
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/blob_test.go
  beacon-chain/db/filesystem/ephemeral.go
  beacon-chain/db/filesystem/flags.go
  beacon-chain/db/filesystem/flags_test.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/blob.go
  beacon-chain/db/kv/blob_test.go
  beacon-chain/node/node.go
Labels: OK to merge, Deneb

#13263 Fix Domain Data Caching
  validator/client/validator.go
Labels: Ready For Review, OK to merge

#13262 Fix Optimistic Sync Evaluator
  testing/endtoend/evaluators/execution_engine.go
Labels: Ready For Review, OK to merge, E2E Tests

#13269 Don't fetch duties for unknown keys
  validator/client/beacon-api/duties.go
  validator/client/beacon-api/duties_test.go
Labels: Ready For Review, OK to merge, Validator Client

#13265 Simplify Beacon API evaluator
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/deps.bzl
  testing/endtoend/evaluators/beaconapi/requests.go
Labels: Ready For Review, OK to merge, E2E Tests

#13276 Beacon API: routes unit test
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
Labels: Ready For Review, OK to merge, API, Cleanup

#13297 Beacon API: fix get blob returns 500 instead of empty
  beacon-chain/rpc/eth/blob/handlers_test.go
  beacon-chain/rpc/lookup/blocker.go
  beacon-chain/rpc/lookup/blocker_test.go
Labels: Bug, Ready For Review, OK to merge, API, Deneb

#13284 APIs: reusing grpc cors middleware for rest
  api/gateway/BUILD.bazel
  api/gateway/gateway.go
  api/server/BUILD.bazel
  api/server/middleware.go
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
  validator/node/node.go
Labels: OK to merge, API, Cleanup

#13179 Support New Subnet Backbone
  beacon-chain/cache/subnet_ids.go
  beacon-chain/cache/subnet_ids_test.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/rpc/core/BUILD.bazel
  beacon-chain/rpc/core/validator.go
  beacon-chain/rpc/eth/config/handlers_test.go
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go
  config/params/config.go
  config/params/loader.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  testing/endtoend/components/web3remotesigner.go
  validator/rpc/handlers_health_test.go
Labels: Ready For Review, Networking

#13296 Gracefully handle unknown validator index in the REST VC
  validator/client/BUILD.bazel
  validator/client/beacon-api/index.go
  validator/client/validator.go
Labels: Validator Client

#13303 Run Evaluator In the Middle Of An Epoch
  testing/endtoend/endtoend_test.go
Labels: Ready For Review, E2E Tests

#13309 Simplify post-evaluation in Beacon API evaluator
  testing/endtoend/evaluators/beaconapi/util.go
  testing/endtoend/evaluators/beaconapi/verify.go
Labels: Ready For Review, E2E Tests

#13294 Use verified blob for gossip checks
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/mock_blob_verifier.go
  beacon-chain/sync/options.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_blob_sidecar.go
  beacon-chain/sync/validate_blob.go
  beacon-chain/sync/validate_blob_test.go
  beacon-chain/sync/validate_bls_to_execution_change_test.go
  beacon-chain/sync/validate_sync_committee_message_test.go
  beacon-chain/sync/validate_sync_contribution_proof_test.go
  beacon-chain/sync/validate_voluntary_exit_test.go
Labels: Ready For Review, Deneb

#13312 Initialize blob storage for initial sync service
  beacon-chain/node/node.go
Labels: Ready For Review

#13253 Blob filesystem add pruning at startup
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
Labels: OK to merge, Deneb

#13315 Beacon APIs: re enabling blob events
  beacon-chain/core/feed/operation/BUILD.bazel
  beacon-chain/core/feed/operation/events.go
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/events/events_test.go
  beacon-chain/sync/blobs_test.go
  beacon-chain/sync/subscriber_blob_sidecar.go
  testing/util/blob.go
  testing/util/block.go
Labels: Ready For Review, API, Deneb

#13320 Handle HTTP 404 Not Found in `SubmitAggregateAndProof`
  validator/client/BUILD.bazel
  validator/client/aggregate.go
Labels: Ready For Review, Validator Client

#13314 Remove signed block requirement from no-verify functions
  beacon-chain/core/altair/attestation.go
  beacon-chain/core/altair/attestation_test.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_fuzz_test.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/core/transition/transition_no_verify_sig_test.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/rpc/eth/rewards/BUILD.bazel
  beacon-chain/rpc/eth/rewards/handlers.go
  beacon-chain/rpc/eth/rewards/service.go
  beacon-chain/rpc/eth/rewards/testing/mock.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/eth/validator/handlers_block_test.go
  consensus-types/blocks/factory.go
  testing/spectest/shared/altair/operations/attestation.go
  testing/spectest/shared/bellatrix/operations/attestation.go
  testing/spectest/shared/capella/operations/attestation.go
  testing/spectest/shared/capella/operations/bls_to_execution_changes.go
  testing/spectest/shared/deneb/operations/attestation.go
  testing/spectest/shared/deneb/operations/bls_to_execution_changes.go
  testing/spectest/shared/phase0/operations/attestation.go
Labels: Cleanup

#13275 Blob filesystem add pruning during blob write
  beacon-chain/db/filesystem/BUILD.bazel
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/blob_test.go
Labels: Deneb

#13323 Add missing testnet configs to default configsets
  config/params/init.go
Labels: Ready For Review

#13325 Clean Up Goodbye Stream Errors
  beacon-chain/sync/rpc.go
Labels: Ready For Review, OK to merge

#13329 Increase buffer of events channel
  beacon-chain/rpc/eth/events/events.go
Labels: Ready For Review, API

#13328 CLI: fixing account import ux bugs
  cmd/validator/accounts/import.go
  cmd/validator/accounts/wallet_utils_test.go
  cmd/validator/wallet/BUILD.bazel
  cmd/validator/wallet/create_test.go
  validator/accounts/BUILD.bazel
  validator/accounts/accounts_import.go
  validator/accounts/wallet/BUILD.bazel
  validator/accounts/wallet/wallet.go
  validator/accounts/wallet/wallet_test.go
  validator/accounts/wallet_create.go
  validator/keymanager/local/keymanager.go
  validator/node/node.go
Labels: Bug, Ready For Review, Cleanup, UX

#13331 Enhance Pruning Logs
  beacon-chain/db/filesystem/blob.go
  beacon-chain/node/node.go
Labels: Deneb

#13327 Hook to slot stream instead of block stream on the VC
  beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/validator/blocks_test.go
  hack/update-mockgen.sh
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.pb.gw.go
  proto/prysm/v1alpha1/validator.proto
  testing/mock/beacon_chain_service_mock.go
  testing/mock/beacon_service_mock.go
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
  testing/mock/node_service_mock.go
  testing/validator-mock/validator_client_mock.go
  validator/accounts/testing/mock.go
  validator/client/attest.go
  validator/client/attest_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/mock/beacon_block_converter_mock.go
  validator/client/beacon-api/mock/genesis_mock.go
  validator/client/beacon-api/mock/json_rest_handler_mock.go
  validator/client/beacon-api/mock/state_validators_mock.go
  validator/client/beacon-api/stream_blocks.go
  validator/client/grpc-api/grpc_validator_client.go
  validator/client/iface/validator.go
  validator/client/iface/validator_client.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review, Validator Client

#13334 Builder API: Fix max field check on toProto function
  api/client/builder/types.go
  api/client/builder/types_test.go
Labels: Bug, Ready For Review, Builder, Deneb

#13335 Excluse DA wait time for chain processing time
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/receive_block.go
Labels: Ready For Review

#13349 Add more color to sending blob by range req log
  beacon-chain/sync/rpc_send_request.go
Labels: Ready For Review

#13352 Use `SkipMevBoost` properly during block production
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/eth/validator/handlers_block_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Labels: Ready For Review

#13317 Enable Deneb For E2E Scenario Tests
  api/client/builder/client.go
  api/client/builder/types.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/ephemeral.go
  beacon-chain/db/kv/blob_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/kv_test.go
  beacon-chain/p2p/types/types.go
  beacon-chain/rpc/eth/config/handlers_test.go
  beacon-chain/sync/blobs_test.go
  beacon-chain/sync/rpc_blob_sidecars_by_range.go
  beacon-chain/sync/rpc_blob_sidecars_by_range_test.go
  beacon-chain/sync/rpc_blob_sidecars_by_root.go
  beacon-chain/sync/rpc_blob_sidecars_by_root_test.go
  beacon-chain/sync/rpc_send_request.go
  cmd/beacon-chain/storage/options.go
  cmd/beacon-chain/storage/options_test.go
  config/params/config.go
  config/params/config_test.go
  config/params/loader.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/mainnet_config_test.go
  config/params/network_config.go
  testing/endtoend/deps.bzl
  testing/endtoend/evaluators/beaconapi/BUILD.bazel
  testing/endtoend/evaluators/beaconapi/requests.go
  testing/endtoend/evaluators/beaconapi/verify.go
  testing/endtoend/evaluators/builder.go
  testing/endtoend/evaluators/fee_recipient.go
  testing/endtoend/evaluators/fork.go
  testing/endtoend/evaluators/operations.go
  testing/endtoend/evaluators/validator.go
  testing/endtoend/helpers/helpers.go
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/minimal_builder_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
  testing/middleware/builder/builder.go
Labels: Ready For Review, E2E Tests, Deneb

#13358 Check builder header kzg commitment at Proposer RPC
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Ready For Review

#13365 Do not skip mev boost in `v3` block production endpoint
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/eth/validator/handlers_block_test.go
Labels: Ready For Review, API

#13345 Small encoding fixes on logs and http error code change
  beacon-chain/rpc/eth/beacon/handlers_validator.go
  beacon-chain/rpc/eth/beacon/handlers_validators_test.go
  validator/client/sync_committee.go
Labels: Ready For Review, API, Cleanup

#13368 Use block value correctly when proposing a block
  consensus-types/blocks/getters.go
Labels: Ready For Review

#13304 Update Libp2p To v0.32.1 and Go to v1.21.5
  .github/actions/gomodtidy/Dockerfile
  .github/workflows/fuzz.yml
  .github/workflows/go.yml
  .golangci.yml
  WORKSPACE
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/dial_relay_node_test.go
  beacon-chain/p2p/info.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/rpc/eth/node/handlers_peers_test.go
  beacon-chain/rpc/eth/node/handlers_test.go
  beacon-chain/rpc/prysm/v1alpha1/node/server.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  cmd/prysmctl/p2p/handler.go
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review, dependencies

#13375 Initialize Inactivity Scores Correctly
  beacon-chain/state/state-native/getters_state.go
  beacon-chain/state/state-native/state_trie_test.go
Labels: Bug, Ready For Review, Deneb

#13376 Update block publishing to 2.4.2 spec
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
Labels: Ready For Review, API

#12987 refactor Payload Id caches
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/forkchoice_update_execution.go
  beacon-chain/blockchain/forkchoice_update_execution_test.go
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/setup_test.go
  beacon-chain/blockchain/tracked_proposer.go
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/payload_id.go
  beacon-chain/cache/payload_id_test.go
  beacon-chain/cache/proposer_indices_disabled.go
  beacon-chain/cache/tracked_validators.go
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/node/node.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/eth/validator/server.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
  beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/service.go
  consensus-types/primitives/BUILD.bazel
  consensus-types/primitives/execution_address.go
  consensus-types/primitives/payload_id.go
  testing/spectest/shared/common/forkchoice/service.go
  validator/client/BUILD.bazel
  validator/client/runner.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review

#13369 Simplify error handling for JsonRestHandler
  testing/assertions/assertions.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/activation_test.go
  validator/client/beacon-api/attestation_data.go
  validator/client/beacon-api/attestation_data_test.go
  validator/client/beacon-api/beacon_api_beacon_chain_client.go
  validator/client/beacon-api/beacon_api_beacon_chain_client_test.go
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/beacon_api_node_client.go
  validator/client/beacon-api/beacon_api_node_client_test.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/domain_data.go
  validator/client/beacon-api/domain_data_test.go
  validator/client/beacon-api/doppelganger_test.go
  validator/client/beacon-api/duties.go
  validator/client/beacon-api/duties_test.go
  validator/client/beacon-api/errors.go
  validator/client/beacon-api/genesis.go
  validator/client/beacon-api/genesis_test.go
  validator/client/beacon-api/get_beacon_block.go
  validator/client/beacon-api/get_beacon_block_test.go
  validator/client/beacon-api/index_test.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/json_rest_handler_test.go
  validator/client/beacon-api/mock/BUILD.bazel
  validator/client/beacon-api/mock/genesis_mock.go
  validator/client/beacon-api/mock/json_rest_handler_mock.go
  validator/client/beacon-api/prepare_beacon_proposer.go
  validator/client/beacon-api/prepare_beacon_proposer_test.go
  validator/client/beacon-api/propose_attestation.go
  validator/client/beacon-api/propose_attestation_test.go
  validator/client/beacon-api/propose_beacon_block.go
  validator/client/beacon-api/propose_beacon_block_test.go
  validator/client/beacon-api/propose_exit.go
  validator/client/beacon-api/propose_exit_test.go
  validator/client/beacon-api/prysm_beacon_chain_client.go
  validator/client/beacon-api/registration.go
  validator/client/beacon-api/registration_test.go
  validator/client/beacon-api/state_validators.go
  validator/client/beacon-api/state_validators_test.go
  validator/client/beacon-api/status_test.go
  validator/client/beacon-api/stream_blocks.go
  validator/client/beacon-api/stream_blocks_test.go
  validator/client/beacon-api/submit_aggregate_selection_proof.go
  validator/client/beacon-api/submit_aggregate_selection_proof_test.go
  validator/client/beacon-api/submit_signed_aggregate_proof.go
  validator/client/beacon-api/submit_signed_aggregate_proof_test.go
  validator/client/beacon-api/submit_signed_contribution_and_proof.go
  validator/client/beacon-api/submit_signed_contribution_and_proof_test.go
  validator/client/beacon-api/subscribe_committee_subnets.go
  validator/client/beacon-api/subscribe_committee_subnets_test.go
  validator/client/beacon-api/sync_committee.go
  validator/client/beacon-api/sync_committee_test.go
  validator/client/beacon-api/validator_count_test.go
  validator/client/beacon-api/wait_for_chain_start_test.go
Labels: Cleanup, Validator Client

#13381 Log value of local payload when proposing
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
Labels: Ready For Review

#13384 Replace validator count with validator indices in update fee recipient log
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Labels: Ready For Review

#13383 update shuffling caches before calling FCU on epoch boundaries
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/tracked_proposer.go
Labels: Ready For Review

#13380 Rewrite `ProposeBlock` endpoint
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/unblinder.go
  beacon-chain/rpc/prysm/v1alpha1/validator/unblinder_test.go
  consensus-types/blocks/getters.go
  consensus-types/interfaces/beacon_block.go
Labels: Ready For Review

#13385 Remove unsafe proposers
  beacon-chain/blockchain/process_block.go
  beacon-chain/cache/proposer_indices.go
  beacon-chain/cache/proposer_indices_test.go
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
Labels: Ready For Review
