Repository OffchainLabs/prysm, pull requests merged in 2023-01, with the labels that each got.

#11822 Add back BLS changes from orphaned blocks
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  testing/util/BUILD.bazel
  testing/util/attestation.go
  testing/util/block.go
  testing/util/capella_block.go
  testing/util/capella_state.go
  testing/util/helpers.go
Labels: Ready For Review, OK to merge

#11836 Add test utility helper to generate valid `bls-to-exec`
  testing/util/BUILD.bazel
  testing/util/capella_block.go
  testing/util/capella_block_test.go
Labels: Ready For Review, OK to merge

#11829 Add `canUseBuilder` helper method
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder_test.go
Labels: Ready For Review

#11825 Better version checks for future proof
  beacon-chain/blockchain/log.go
  beacon-chain/blockchain/metrics.go
  beacon-chain/core/blocks/attester_slashing.go
  beacon-chain/core/blocks/proposer_slashing.go
  beacon-chain/core/transition/transition.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
Labels: Ready For Review, OK to merge

#11844 Rename proposer_exists
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_exits.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_exits_test.go
Labels: Ready For Review, OK to merge

#11786 Add REST implementation for `MultipleValidatorStatus`
  hack/update-mockgen.sh
  validator/client/beacon-api/activation.go
  validator/client/beacon-api/activation_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/index.go
  validator/client/beacon-api/index_test.go
  validator/client/beacon-api/mock/BUILD.bazel
  validator/client/beacon-api/mock/state_validators_mock.go
  validator/client/beacon-api/state_validators.go
  validator/client/beacon-api/state_validators_test.go
  validator/client/beacon-api/status.go
  validator/client/beacon-api/status_test.go
Labels: OK to merge

#11811 Shift Multiclient E2E to Post-Submit
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
Labels: Ready For Review, OK to merge

#11846 Remove Lock from Checkpoint Cache as LRU is Already Thread-Safe
  beacon-chain/cache/checkpoint_state.go
Labels: Ready For Review, OK to merge

#11849 Log forkchoice weights on reorgs
  beacon-chain/blockchain/head.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  beacon-chain/forkchoice/interfaces.go
Labels: Ready For Review

#11847 Add `context` to beacon API REST implementation
  validator/client/beacon-api/activation.go
  validator/client/beacon-api/activation_test.go
  validator/client/beacon-api/attestation_data.go
  validator/client/beacon-api/attestation_data_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/domain_data.go
  validator/client/beacon-api/domain_data_test.go
  validator/client/beacon-api/genesis.go
  validator/client/beacon-api/genesis_test.go
  validator/client/beacon-api/get_beacon_block.go
  validator/client/beacon-api/get_beacon_block_altair_test.go
  validator/client/beacon-api/get_beacon_block_bellatrix_test.go
  validator/client/beacon-api/get_beacon_block_phase0_test.go
  validator/client/beacon-api/get_beacon_block_test.go
  validator/client/beacon-api/index.go
  validator/client/beacon-api/index_test.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/json_rest_handler_test.go
  validator/client/beacon-api/mock/genesis_mock.go
  validator/client/beacon-api/mock/json_rest_handler_mock.go
  validator/client/beacon-api/mock/state_validators_mock.go
  validator/client/beacon-api/prepare_beacon_proposer.go
  validator/client/beacon-api/prepare_beacon_proposer_test.go
  validator/client/beacon-api/propose_beacon_block.go
  validator/client/beacon-api/propose_beacon_block_altair_test.go
  validator/client/beacon-api/propose_beacon_block_bellatrix_test.go
  validator/client/beacon-api/propose_beacon_block_blinded_bellatrix_test.go
  validator/client/beacon-api/propose_beacon_block_blinded_capella_test.go
  validator/client/beacon-api/propose_beacon_block_phase0_test.go
  validator/client/beacon-api/propose_beacon_block_test.go
  validator/client/beacon-api/propose_exit.go
  validator/client/beacon-api/propose_exit_test.go
  validator/client/beacon-api/state_validators.go
  validator/client/beacon-api/state_validators_test.go
  validator/client/beacon-api/status.go
  validator/client/beacon-api/status_test.go
  validator/client/beacon-api/wait_for_chain_start_test.go
Labels: OK to merge

#11845 Implement bls_to_execution_changes beacon endpoint
  beacon-chain/core/blocks/BUILD.bazel
  beacon-chain/core/blocks/exports_test.go
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/rpc/apimiddleware/custom_hooks.go
  beacon-chain/rpc/apimiddleware/custom_hooks_test.go
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/pool.go
  beacon-chain/rpc/eth/beacon/pool_test.go
  crypto/bls/common/BUILD.bazel
  proto/eth/service/beacon_chain_service.pb.go
  proto/eth/service/beacon_chain_service.pb.gw.go
  proto/eth/service/beacon_chain_service.proto
  proto/eth/v2/withdrawals.pb.go
  proto/eth/v2/withdrawals.proto
  proto/migration/v1alpha1_to_v2.go
Labels: Ready For Review, Priority: High, OK to merge, API, Withdrawals

#11850 Prevent pollution between scenario tests
  testing/endtoend/endtoend_test.go
  testing/endtoend/evaluators/api_gateway_v1alpha1.go
  testing/endtoend/evaluators/api_middleware.go
  testing/endtoend/evaluators/beaconapi_evaluators/beacon_api_verify.go
  testing/endtoend/evaluators/data.go
  testing/endtoend/evaluators/execution_engine.go
  testing/endtoend/evaluators/fee_recipient.go
  testing/endtoend/evaluators/finality.go
  testing/endtoend/evaluators/fork.go
  testing/endtoend/evaluators/metrics.go
  testing/endtoend/evaluators/node.go
  testing/endtoend/evaluators/operations.go
  testing/endtoend/evaluators/peers.go
  testing/endtoend/evaluators/slashing.go
  testing/endtoend/evaluators/validator.go
  testing/endtoend/types/types.go
Labels: OK to merge

#11816 Add REST implementation for `SubmitValidatorRegistrations`
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/registration.go
  validator/client/beacon-api/registration_test.go
Labels: OK to merge

#11851 Better reconstruct error msg while EL client is syncing
  beacon-chain/execution/engine_client.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
Labels: Ready For Review, OK to merge

#11827 Add REST implementation for `SubmitSyncMessage`
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/sync_committee.go
  validator/client/beacon-api/sync_committee_test.go
Labels: OK to merge

#11824 Add REST implementation for validator's GetSyncMessageBlockRoot
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/sync_message_block_root.go
  validator/client/beacon-api/sync_message_block_root_test.go
Labels: OK to merge

#11826 Add REST implementation for validator's SubmitSignedAggregateSelectionProof
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_block_json_helpers.go
  validator/client/beacon-api/submit_signed_aggregate_proof.go
  validator/client/beacon-api/submit_signed_aggregate_proof_test.go
Labels: OK to merge

#11812 Add REST implementation for Validator's `SubmitSignedContributionAndProof`
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/submit_signed_contribution_and_proof.go
  validator/client/beacon-api/submit_signed_contribution_and_proof_test.go
Labels: OK to merge

#11767 add custom headers to DomainData requests
  validator/client/BUILD.bazel
  validator/client/validator.go
Labels: OK to merge

#11800 Add REST implementation for validator's ProposeAttestation
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/propose_attestation.go
  validator/client/beacon-api/propose_attestation_test.go
Labels: OK to merge

#11860 Check If Validator Is In Sync Committee
  validator/client/metrics.go
  validator/client/validator.go
Labels: Ready For Review, OK to merge

#11858 Replay state to current slot in `StateBySlot`
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/rpc/statefetcher/fetcher_test.go
Labels: Ready For Review

#11848 Add Capella support for Validator's REST API `ProposeBeaconBlock` and `GetBeaconBlock` endpoints
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_block_json_helpers.go
  validator/client/beacon-api/beacon_block_json_helpers_test.go
  validator/client/beacon-api/beacon_block_proto_helpers.go
  validator/client/beacon-api/beacon_block_proto_helpers_test.go
  validator/client/beacon-api/get_beacon_block.go
  validator/client/beacon-api/get_beacon_block_capella_test.go
  validator/client/beacon-api/get_beacon_block_test.go
  validator/client/beacon-api/propose_beacon_block.go
  validator/client/beacon-api/propose_beacon_block_capella_test.go
  validator/client/beacon-api/test-helpers/BUILD.bazel
  validator/client/beacon-api/test-helpers/capella_beacon_block_test_helpers.go
Labels: OK to merge

#11861 Replace `FutureForkStub` with specific interfaces
  beacon-chain/state/interfaces.go
Labels: Ready For Review, OK to merge, Cleanup

#11820 Fix State Fetcher
  beacon-chain/rpc/statefetcher/BUILD.bazel
  beacon-chain/rpc/statefetcher/fetcher.go
  beacon-chain/rpc/statefetcher/fetcher_test.go
Labels: Ready For Review, OK to merge, API

#11863 Add historical summaries to beacon api state
  beacon-chain/rpc/apimiddleware/structs.go
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
  proto/migration/v1alpha1_to_v2.go
  proto/migration/v1alpha1_to_v2_test.go
Labels: Ready For Review, OK to merge

#11862 Capella State Detection
  beacon-chain/core/blocks/genesis.go
  beacon-chain/db/kv/genesis_test.go
  beacon-chain/db/kv/testdata/capella_genesis.ssz
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/config.go
  config/params/interop.go
  config/params/loader.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/testdata/e2e_config.yaml
  config/params/testnet_e2e_config.go
  config/params/testnet_ropsten_config.go
  encoding/ssz/detect/configfork.go
  encoding/ssz/detect/configfork_test.go
Labels: OK to merge

#11868 Remove ShardingForkVersion/Epoch from config
  beacon-chain/rpc/eth/beacon/config_test.go
  config/params/config.go
  config/params/configset_test.go
  config/params/interop.go
  config/params/loader.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  config/params/testdata/e2e_config.yaml
  config/params/testnet_config_test.go
  config/params/testnet_e2e_config.go
  config/params/testnet_prater_config.go
  network/forks/fork_test.go
Labels: OK to merge

#11834 New prysm get block RPC
  beacon-chain/execution/testing/BUILD.bazel
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_altair.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_altair_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_capella.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_phase0.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
Labels: Blocked, Priority: High, OK to merge, Withdrawals

#11872 broadcast bls changes at the fork
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/broadcast_bls_changes.go
  beacon-chain/blockchain/service.go
Labels: OK to merge, Withdrawals

#11870 Sign BLS_TO_EXECUTION_CHANGES with GENESIS_FORK_VERSION
  WORKSPACE
  beacon-chain/core/blocks/exports_test.go
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/rpc/eth/beacon/pool_test.go
  testing/spectest/shared/altair/ssz_static/ssz_static.go
  testing/spectest/shared/bellatrix/ssz_static/ssz_static.go
  testing/spectest/shared/capella/ssz_static/ssz_static.go
  testing/util/capella_block.go
Labels: Ready For Review, Priority: High, OK to merge, Withdrawals

#11878 Move broadcast of BLS changes to the forkwatcher
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/broadcast_bls_changes.go
  beacon-chain/blockchain/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/broadcast_bls_changes.go
  beacon-chain/sync/broadcast_bls_changes_test.go
  beacon-chain/sync/fork_watcher.go
Labels: Ready For Review, OK to merge, Withdrawals

#11876 Clarify circuit breaker logs
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder_test.go
Labels: Ready For Review, OK to merge, Cleanup

#11866 Change withdrawal amount unmarshal to uint64 (gwei)
  beacon-chain/rpc/service.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
Labels: Ready For Review, OK to merge

#11865 Implement `bls_to_execution_change` API event
  beacon-chain/core/feed/operation/events.go
  beacon-chain/rpc/apimiddleware/custom_handlers.go
  beacon-chain/rpc/eth/beacon/pool.go
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/events/events_test.go
  beacon-chain/sync/subscriber_bls_to_execution_change.go
  beacon-chain/sync/subscription_topic_handler_test.go
Labels: Ready For Review, OK to merge

#11883 Stream blocks capella
  beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/validator/blocks_test.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.proto
  validator/client/validator.go
Labels: Ready For Review, OK to merge, Withdrawals

#11887 Delete interop.Dockerfile
  interop.Dockerfile
Labels: Ready For Review, OK to merge

#11875 Add REST implementation for GetSyncCommitteeContribution
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/sync_committee.go
  validator/client/beacon-api/sync_committee_test.go
  validator/client/beacon-api/sync_message_block_root.go
  validator/client/beacon-api/sync_message_block_root_test.go
Labels: OK to merge

#11877 Add additional tests to bytesutil
  encoding/bytesutil/bytes_test.go
  encoding/bytesutil/integers_test.go
Labels: Ready For Review, OK to merge

#11886 Add Disable Staking Contract Check Flag
  config/features/flags.go
Labels: Ready For Review, OK to merge

#11888 Add capella fork version for Sepolia testnet
  config/params/testnet_sepolia_config.go
Labels: Ready For Review, OK to merge

#11879 Add capella's marshal and unmarshal
  beacon-chain/execution/engine_client_test.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
Labels: Ready For Review, OK to merge

#11889 Remove Unused Block Setter
  consensus-types/blocks/getters_test.go
  consensus-types/blocks/setters.go
  consensus-types/interfaces/beacon_block.go
  consensus-types/mock/block.go
Labels: Ready For Review, OK to merge

#11821 fix TestVotes_CanFindHead
  beacon-chain/forkchoice/doubly-linked-tree/vote_test.go
Labels: Ready For Review, OK to merge

#11874 Small adjustments to Beacon API
  beacon-chain/rpc/eth/beacon/blinded_blocks.go
  beacon-chain/rpc/eth/beacon/blocks.go
  beacon-chain/rpc/eth/beacon/blocks_test.go
Labels: Ready For Review, OK to merge, API

#11835 Add REST implementation for `CheckDoppelGanger`
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/doppelganger.go
  validator/client/beacon-api/doppelganger_test.go
  validator/client/beacon-api/log.go
Labels: OK to merge

#11804 Add REST implementation for Validator's `SubscribeCommitteeSubnets`
  hack/update-mockgen.sh
  testing/mock/BUILD.bazel
  testing/mock/validator_client_mock.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/duties.go
  validator/client/beacon-api/duties_test.go
  validator/client/beacon-api/mock/BUILD.bazel
  validator/client/beacon-api/mock/duties_mock.go
  validator/client/beacon-api/subscribe_committee_subnets.go
  validator/client/beacon-api/subscribe_committee_subnets_test.go
  validator/client/grpc-api/BUILD.bazel
  validator/client/grpc-api/grpc_validator_client.go
  validator/client/iface/validator_client.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: OK to merge

#11890 Add flag for custom slasher database directory
  beacon-chain/node/node.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
Labels: Ready For Review, OK to merge

#11896 Use LIFO instead of FIFO when packing BLS changes
  beacon-chain/operations/blstoexec/pool.go
  beacon-chain/operations/blstoexec/pool_test.go
Labels: OK to merge, Withdrawals

#11892 Exit properly with terminal block hash
  beacon-chain/blockchain/pow_block.go
  beacon-chain/blockchain/pow_block_test.go
Labels: Ready For Review

#11894 Refactor BLS change pool
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/operations/blstoexec/BUILD.bazel
  beacon-chain/operations/blstoexec/mock/mock.go
  beacon-chain/operations/blstoexec/pool.go
  beacon-chain/operations/blstoexec/pool_test.go
Labels: Ready For Review, OK to merge, Withdrawals

#11902 Do not check headstate being Capella for BLS changes on gossip
  beacon-chain/sync/validate_bls_to_execution_change.go
  beacon-chain/sync/validate_bls_to_execution_change_test.go
Labels: Ready For Review, OK to merge, Withdrawals

#11790 prysmctl: changeblstoexecutionaddress ( withdrawals)
  api/client/beacon/client.go
  cmd/prysmctl/BUILD.bazel
  cmd/prysmctl/main.go
  cmd/prysmctl/signing/BUILD.bazel
  cmd/prysmctl/signing/cmd.go
  cmd/prysmctl/validator/BUILD.bazel
  cmd/prysmctl/validator/cmd.go
  cmd/prysmctl/validator/testdata/change-operations-multiple.json
  cmd/prysmctl/validator/testdata/change-operations-multiple_notfound.json
  cmd/prysmctl/validator/testdata/change-operations.json
  cmd/prysmctl/validator/testdata/staking-cli-change-operations-multiple.json
  cmd/prysmctl/validator/withdraw.go
  cmd/prysmctl/validator/withdraw_test.go
  cmd/validator/accounts/accounts.go
Labels: Priority: High, OK to merge, Withdrawals

#11893 Add REST implementation for Validator's `GetDuties`
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/duties.go
  validator/client/beacon-api/duties_test.go
  validator/client/beacon-api/mock/duties_mock.go
Labels: OK to merge, API

#11910 validator exit test
  beacon-chain/core/blocks/exit_test.go
Labels: OK to merge

#11908 Return error structures from bls changes endpoint
  beacon-chain/rpc/apimiddleware/endpoint_factory.go
Labels: Ready For Review, OK to merge, Withdrawals

#11911 save genesis state to hot cache and do not look it up from disk
  beacon-chain/blockchain/chain_info_norace_test.go
  beacon-chain/blockchain/head_sync_committee_info_test.go
  beacon-chain/state/stategen/getter.go
  beacon-chain/state/stategen/service.go
Labels: Ready For Review

#11912 PrepareBeaconProposer: bug fix
  beacon-chain/rpc/eth/validator/validator.go
  beacon-chain/rpc/eth/validator/validator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Labels: Bug, OK to merge, API

#11900 Clean up unused code
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/cache/depositsnapshot/merkle_tree.go
  beacon-chain/core/signing/signing_root.go
  beacon-chain/core/transition/state-bellatrix.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/state/state-native/setters_withdrawal.go
  beacon-chain/state/stategen/mock/replayer.go
  beacon-chain/state/testing/BUILD.bazel
  beacon-chain/state/testing/getters.go
  beacon-chain/state/testing/setters_participation.go
  validator/client/beacon-api/attestation_data_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/domain_data_test.go
Labels: Ready For Review, OK to merge

#11798 beacon-chain, config: get consensus values from beacon config
  beacon-chain/state/state-native/setters_attestation.go
  beacon-chain/state/state-native/state_trie.go
  beacon-chain/state/stateutil/eth1_root.go
  beacon-chain/state/stateutil/field_root_attestation.go
  config/params/config.go
Labels: OK to merge

#11904 Update builder code to Capella
  api/client/builder/BUILD.bazel
  api/client/builder/bid.go
  api/client/builder/client.go
  api/client/builder/client_test.go
  api/client/builder/testdata/blinded-block-capella.json
  api/client/builder/testdata/execution-payload-capella.json
  api/client/builder/testing/BUILD.bazel
  api/client/builder/testing/mock.go
  api/client/builder/types.go
  api/client/builder/types_test.go
  beacon-chain/builder/BUILD.bazel
  beacon-chain/builder/service.go
  beacon-chain/builder/testing/BUILD.bazel
  beacon-chain/builder/testing/mock.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/generated.ssz.go
Labels: Ready For Review, Withdrawals

#11923 Randomize bls changes at fork
  beacon-chain/blockchain/service_test.go
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_broadcaster.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/rpc/eth/beacon/pool.go
  beacon-chain/sync/broadcast_bls_changes.go
  beacon-chain/sync/broadcast_bls_changes_test.go
  beacon-chain/sync/fork_watcher.go
Labels: Ready For Review, OK to merge, Withdrawals

#11805 Return error when using unsupported mnemonic language
  cmd/validator/accounts/backup_test.go
  cmd/validator/wallet/create.go
  cmd/validator/wallet/edit_test.go
  cmd/validator/wallet/recover_test.go
  proto/prysm/v1alpha1/validator-client/web_api.pb.go
  proto/prysm/v1alpha1/validator-client/web_api.proto
  validator/accounts/accounts_list_test.go
  validator/accounts/cli_manager.go
  validator/client/wait_for_activation_test.go
  validator/keymanager/derived/keymanager_test.go
  validator/keymanager/derived/mnemonic.go
  validator/keymanager/derived/mnemonic_test.go
  validator/rpc/accounts_test.go
  validator/rpc/standard_api_test.go
Labels: Ready For Review, OK to merge

#11909 prysmctl: withdrawal ux improvement
  cmd/prysmctl/validator/withdraw.go
  cmd/prysmctl/validator/withdraw_test.go
Labels: OK to merge

#11915 Validator client beacon api non functional fixes
  validator/client/beacon-api/attestation_data.go
  validator/client/beacon-api/beacon_api_helpers.go
  validator/client/beacon-api/state_validators.go
  validator/client/beacon-api/sync_committee.go
  validator/client/beacon-api/sync_committee_test.go
Labels: OK to merge

#11918 Use correct attribute if there's a payload ID cache miss
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
Labels: Bug, Ready For Review, OK to merge, Withdrawals

#11917 Better log for block that never became head
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge

#11720 EIP-4881: Spec implementation
  beacon-chain/cache/depositsnapshot/BUILD.bazel
  beacon-chain/cache/depositsnapshot/deposit_tree.go
  beacon-chain/cache/depositsnapshot/deposit_tree_snapshot.go
  beacon-chain/cache/depositsnapshot/merkle_tree.go
  beacon-chain/cache/depositsnapshot/zerohashes.gen.go
  container/slice/slice.go
  container/slice/slice_test.go
  encoding/bytesutil/integers.go
  encoding/bytesutil/integers_test.go
Labels: OK to merge

#11873 Cycle the BLS changes pool when falling below a threshold
  beacon-chain/operations/blstoexec/pool.go
  beacon-chain/operations/blstoexec/pool_test.go
  container/doubly-linked-list/list.go
  container/doubly-linked-list/list_test.go
Labels: Ready For Review, OK to merge, Withdrawals

#11931 Cache Fork Digest Computation
  beacon-chain/core/signing/signing_root.go
  beacon-chain/core/signing/signing_root_test.go
Labels: Ready For Review, OK to merge

#11939 Update Bazel Grail Toolchain SHA and Protect Digest Map with Lock
  WORKSPACE
  beacon-chain/core/signing/signing_root.go
Labels: Ready For Review, OK to merge

#11937 update-go-pbs.sh: fixing script for mac users & updating bazel dependency
  WORKSPACE
  hack/README.md
  hack/common.sh
Labels: Ready For Review, OK to merge

#11941 Revert Bazel Hash Change
  WORKSPACE
Labels: Ready For Review, Priority: Critical, OK to merge

#11929 Add spec tests v1.3.0 rc.2
  WORKSPACE
Labels: Ready For Review, OK to merge

#11933 Use copied head state for metrics reporting
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review, OK to merge

#11813 delete from s.nodeByPayload as well when pruneFinalizedNodeByRootMap
  beacon-chain/forkchoice/doubly-linked-tree/store.go
  beacon-chain/forkchoice/doubly-linked-tree/store_test.go
Labels: OK to merge

#11936 Rate limit broadcasting of BLS changes at the fork and at RPC endpoint
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_broadcaster.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/rpc/eth/beacon/pool.go
  beacon-chain/rpc/eth/beacon/pool_test.go
  beacon-chain/sync/broadcast_bls_changes.go
  beacon-chain/sync/broadcast_bls_changes_test.go
Labels: Bug, Ready For Review, Priority: Critical, Withdrawals

#11944 Validator client: Add missing `endpoint.DeleteRequest` - Fixes #11943
  validator/rpc/apimiddleware/endpoint_factory.go
  validator/rpc/apimiddleware/structs.go
Labels: OK to merge

#11932 Utilize Read Only Head State
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/head_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/sync/validate_bls_to_execution_change.go
Labels: Ready For Review, Priority: High, OK to merge, Withdrawals, V4

#11919 Call FCU with attribute on non head block
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/forkchoice_update_execution.go
  beacon-chain/blockchain/forkchoice_update_execution_test.go
  beacon-chain/blockchain/head.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/blockchain/receive_attestation_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
Labels: Bug, Ready For Review, Priority: High, OK to merge

#11947 Add `finalized` flag to API responses
  beacon-chain/rpc/apimiddleware/structs.go
  beacon-chain/rpc/eth/beacon/state.go
  beacon-chain/rpc/eth/beacon/state_test.go
  beacon-chain/rpc/eth/beacon/sync_committee.go
  beacon-chain/rpc/eth/beacon/sync_committee_test.go
  beacon-chain/rpc/eth/beacon/validator.go
  beacon-chain/rpc/eth/beacon/validator_test.go
  beacon-chain/rpc/eth/debug/debug.go
  beacon-chain/rpc/eth/debug/debug_test.go
  beacon-chain/rpc/eth/debug/server.go
  beacon-chain/rpc/service.go
  proto/eth/v2/beacon_state.pb.go
  proto/eth/v2/beacon_state.proto
Labels: Ready For Review, API
