Repository OffchainLabs/prysm, pull requests merged in 2024-03, with the labels that each got.

#13680 Fix Data Race in Epoch Boundary
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review

#13683 Do not check parent weight on early FCU
  beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
  beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks_test.go
Labels: Bug

#13588 REST VC metrics
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/endpoints_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/metrics.go
Labels: Ready For Review, Validator Client

#13696 keymanager api: lowercase statuses
  validator/keymanager/types.go
  validator/rpc/BUILD.bazel
  validator/rpc/handlers_keymanager.go
  validator/rpc/handlers_keymanager_test.go
Labels: API, Cleanup, Keymanager-API

#13710 Check Unrealized Justification Balances In Spectests
  beacon-chain/state/state-native/getters_participation_test.go
  beacon-chain/state/stateutil/unrealized_justification.go
  beacon-chain/state/stateutil/unrealized_justification_test.go
  testing/spectest/shared/altair/epoch_processing/justification_and_finalization.go
  testing/spectest/shared/altair/rewards/rewards_penalties.go
  testing/spectest/shared/bellatrix/epoch_processing/justification_and_finalization.go
  testing/spectest/shared/bellatrix/rewards/rewards_penalties.go
  testing/spectest/shared/capella/epoch_processing/justification_and_finalization.go
  testing/spectest/shared/capella/rewards/rewards_penalties.go
  testing/spectest/shared/deneb/epoch_processing/justification_and_finalization.go
  testing/spectest/shared/deneb/rewards/rewards_penalties.go
Labels: Ready For Review

#13702 Optimize `SubscribeCommitteeSubnets` VC action
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.proto
  testing/validator-mock/BUILD.bazel
  testing/validator-mock/validator_client_mock.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/duties.go
  validator/client/beacon-api/duties_test.go
  validator/client/beacon-api/subscribe_committee_subnets.go
  validator/client/beacon-api/subscribe_committee_subnets_test.go
  validator/client/grpc-api/grpc_validator_client.go
  validator/client/iface/validator_client.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review, API, Validator Client

#13712 Remove unused deneb code
  beacon-chain/cache/depositsnapshot/deposit_cache_test.go
  beacon-chain/cache/depositsnapshot/deposit_tree.go
  beacon-chain/cache/proposer_indices_type.go
  beacon-chain/das/BUILD.bazel
  beacon-chain/das/availability_test.go
  beacon-chain/db/errors.go
  beacon-chain/db/filesystem/BUILD.bazel
  beacon-chain/db/filesystem/blob_test.go
  beacon-chain/execution/errors.go
  beacon-chain/p2p/types/rpc_errors.go
Labels: Ready For Review

#13716 Ignore Pubsub Messages Hitting Context Deadlines
  beacon-chain/sync/subscriber.go
Labels: Ready For Review, Networking

#13703 Use justified checkpoint from head state to build attestation
  beacon-chain/rpc/core/validator.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester_mainnet_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
Labels: Ready For Review

#13722 Save invalid block to temp `save-invalid-block-temp`
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/subscriber_beacon_blocks.go
  config/features/config.go
  config/features/flags.go
Labels: Ready For Review

#13725 Save invalid blob to temp under new flag
  beacon-chain/sync/validate_blob.go
  config/features/config.go
  config/features/flags.go
Labels: Ready For Review

#13737 Add gossip blob sidecar verification ms metric
  beacon-chain/sync/metrics.go
  beacon-chain/sync/validate_blob.go
Labels: Ready For Review

#13736 Add blob index to file path
  beacon-chain/sync/validate_blob.go
Labels: Ready For Review

#13563 replace receive slot with event stream
  api/client/beacon/BUILD.bazel
  api/client/beacon/health.go
  api/client/beacon/health_test.go
  api/client/beacon/iface/BUILD.bazel
  api/client/beacon/iface/health.go
  api/client/beacon/testing/BUILD.bazel
  api/client/beacon/testing/mock.go
  api/client/errors.go
  api/client/event/BUILD.bazel
  api/client/event/event_stream.go
  api/client/event/event_stream_test.go
  beacon-chain/rpc/prysm/v1alpha1/node/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/node/server.go
  beacon-chain/rpc/prysm/v1alpha1/node/server_test.go
  proto/prysm/v1alpha1/node.pb.go
  proto/prysm/v1alpha1/node.pb.gw.go
  proto/prysm/v1alpha1/node.proto
  testing/validator-mock/BUILD.bazel
  testing/validator-mock/node_client_mock.go
  testing/validator-mock/validator_client_mock.go
  validator/accounts/cli_manager.go
  validator/accounts/testing/BUILD.bazel
  validator/accounts/testing/mock.go
  validator/client/BUILD.bazel
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_node_client.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/event_handler.go
  validator/client/beacon-api/event_handler_test.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/json_rest_handler_test.go
  validator/client/beacon-api/mock/json_rest_handler_mock.go
  validator/client/beacon-api/stream_blocks.go
  validator/client/grpc-api/BUILD.bazel
  validator/client/grpc-api/grpc_node_client.go
  validator/client/grpc-api/grpc_validator_client.go
  validator/client/grpc-api/grpc_validator_client_test.go
  validator/client/iface/BUILD.bazel
  validator/client/iface/node_client.go
  validator/client/iface/validator.go
  validator/client/iface/validator_client.go
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/service.go
  validator/client/testutil/BUILD.bazel
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/rpc/beacon.go
Labels: API, Cleanup, Validator Client, >1 Approves Required

#13740 Use correct gossip validation time
  beacon-chain/sync/validate_blob.go
Labels: Ready For Review

#13750 Always Set Inprogress Boolean In Cache
  beacon-chain/cache/skip_slot_cache.go
  beacon-chain/cache/skip_slot_cache_test.go
Labels: Ready For Review

#13756 New gossip cache size
  beacon-chain/sync/service.go
Labels: Ready For Review

#13746 Use headstate for recent checkpoints
  beacon-chain/blockchain/process_attestation_helpers.go
  beacon-chain/blockchain/process_attestation_test.go
Labels: Bug

#13762 Rewrite Pruning Implementation To Handle EIP 7045
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/prune_expired.go
  beacon-chain/operations/attestations/prune_expired_test.go
Labels: Ready For Review

#13474 Keymanager APIs - get,post,delete graffiti
  config/proposer/loader/loader_test.go
  config/proposer/loader/testdata/good-graffiti-settings.json
  config/proposer/settings.go
  config/proposer/settings_test.go
  proto/prysm/v1alpha1/validator-client/BUILD.bazel
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
  validator/accounts/testing/BUILD.bazel
  validator/accounts/testing/mock.go
  validator/client/iface/validator.go
  validator/client/propose.go
  validator/client/propose_test.go
  validator/client/service.go
  validator/client/testutil/mock_validator.go
  validator/rpc/handlers_keymanager.go
  validator/rpc/handlers_keymanager_test.go
  validator/rpc/server.go
  validator/rpc/server_test.go
  validator/rpc/structs.go
Labels: API, Keymanager-API

#13761 Update spec test to official 1.4.0
  README.md
  WORKSPACE
Labels: Ready For Review

#13745 Enable Configurable Mplex Timeouts
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/options.go
  beacon-chain/p2p/service.go
Labels: Networking

#13711 Optimize `SubmitAggregateSelectionProof` VC action
  testing/validator-mock/BUILD.bazel
  testing/validator-mock/validator_client_mock.go
  validator/client/aggregate.go
  validator/client/aggregate_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/submit_aggregate_selection_proof.go
  validator/client/beacon-api/submit_aggregate_selection_proof_test.go
  validator/client/grpc-api/grpc_validator_client.go
  validator/client/iface/validator_client.go
Labels: API, Validator Client

#13771 validator client on rest mode has an inappropriate context deadline for events
  beacon-chain/rpc/eth/events/BUILD.bazel
  beacon-chain/rpc/eth/events/events.go
  validator/client/beacon-api/beacon_api_validator_client.go
Labels: Bug, API, Validator Client

#13775 Add da waited time to sync block log
  beacon-chain/blockchain/log.go
Labels: Ready For Review

#13778 validator client should set beacon API endpoint in configurations
  validator/node/node.go
  validator/rpc/server.go
Labels: Bug, API, Validator Client

#13780 Fix get validator endpoint for empty query parameters
  validator/rpc/handlers_beacon.go
  validator/rpc/handlers_beacon_test.go
Labels: Bug, API, Web UI, Validator Client

#13770 Expand Our TTL for our Message ID Cache
  beacon-chain/p2p/parameter_test.go
  beacon-chain/p2p/pubsub.go
Labels: Networking

#13787 Log da block root in hex
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review

#13789 Optimize `GetDuties` VC action
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/duties.go
  validator/client/beacon-api/duties_test.go
Labels: Ready For Review, API, Validator Client

#13684 Utilize next slot cache in block rewards rpc
  beacon-chain/rpc/eth/rewards/BUILD.bazel
  beacon-chain/rpc/eth/rewards/handlers_test.go
  beacon-chain/rpc/eth/rewards/service.go
  beacon-chain/rpc/eth/rewards/service_test.go
  beacon-chain/rpc/service.go
Labels: Ready For Review, API

#13796 Call `GetGenesis` only once
  validator/client/beacon-api/beacon_api_node_client.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/genesis.go
  validator/client/beacon-api/genesis_test.go
  validator/client/beacon-api/wait_for_chain_start_test.go
Labels: Ready For Review, API, Validator Client

#13804 Add bid value metrics
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
Labels: Ready For Review

#13813 Simplify ValidateAttestationTime
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
Labels: Cleanup

#13814 Remove check for duplicates in pending attestation queue
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
Labels: Bug

#13819 Change goodbye message from rate limited peer to debug verbosity
  beacon-chain/sync/rpc_goodbye.go
Labels: Ready For Review

#13825 Fill in missing debug logs for blob p2p IGNORE/REJECT
  beacon-chain/verification/blob.go
Labels: Ready For Review

#13820 Maximize Peer Capacity When Syncing
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
Labels: Ready For Review, Priority: High
