Repository OffchainLabs/prysm, pull requests merged in 2024-06, with the labels that each got.

#14072 Change Attestation Log To Debug
  beacon-chain/p2p/broadcaster.go
Labels: Ready For Review

#14069 Process epoch error to use correct state version
  beacon-chain/core/altair/transition.go
  beacon-chain/core/altair/transition_test.go
  beacon-chain/core/electra/transition.go
  beacon-chain/core/transition/altair_transition_no_verify_sig_test.go
  beacon-chain/core/transition/bellatrix_transition_no_verify_sig_test.go
  beacon-chain/core/transition/transition.go
  beacon-chain/state/stategen/replay.go
Labels: Ready For Review, Priority: High

#14075 middleware for content type and accept headers
  api/gateway/BUILD.bazel
  api/gateway/gateway.go
  api/server/BUILD.bazel
  api/server/middleware.go
  api/server/middleware/BUILD.bazel
  api/server/middleware/middleware.go
  api/server/middleware/middleware_test.go
  api/server/middleware/util.go
  api/server/middleware/util_test.go
  api/server/middleware_test.go
  beacon-chain/node/BUILD.bazel
  beacon-chain/node/node.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/service.go
  validator/node/BUILD.bazel
  validator/node/node.go
Labels: Ready For Review, API

#14015 Deprectate `EnableDebugRPCEndpoints` flag
  beacon-chain/node/node.go
  beacon-chain/rpc/service.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  config/features/deprecated_flags.go
  testing/endtoend/components/beacon_node.go
Labels: Ready For Review, >1 Approves Required

#14027 EIP 7549 spectests
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/attestation.go
  testing/spectest/mainnet/electra/operations/BUILD.bazel
  testing/spectest/mainnet/electra/operations/attestation_test.go
  testing/spectest/minimal/electra/operations/BUILD.bazel
  testing/spectest/minimal/electra/operations/attestation_test.go
  testing/spectest/shared/electra/operations/BUILD.bazel
  testing/spectest/shared/electra/operations/attestation.go
  testing/spectest/shared/electra/operations/attester_slashing.go
  testing/spectest/shared/electra/operations/bls_to_execution_changes.go
  testing/spectest/shared/electra/operations/consolidations.go
  testing/spectest/shared/electra/operations/execution_layer_withdrawal_request.go
  testing/spectest/shared/electra/operations/helpers.go
  testing/spectest/shared/electra/operations/proposer_slashing.go
  testing/spectest/shared/electra/operations/sync_committee.go
  testing/spectest/shared/electra/operations/voluntary_exit.go
  testing/spectest/shared/electra/operations/withdrawals.go
Labels: Ready For Review, Spec, Tests, Electra

#14097 content type check is too strict
  api/server/middleware/middleware.go
  api/server/middleware/middleware_test.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/json_rest_handler_test.go
Labels: API

#14102 [PeerDAS] fixes and tests for gossiping out data columns
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/monitoring.go
Labels: peerDAS

#14103 [PeerDAS] implement DataColumnSidecarsByRootReq and fix related bugs
  beacon-chain/p2p/types/types.go
  beacon-chain/p2p/types/types_test.go
  beacon-chain/sync/data_columns_sampling.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_send_request.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/data_columns.pb.go
  proto/prysm/v1alpha1/data_columns.pb.gw.go
  proto/prysm/v1alpha1/data_columns.proto
  proto/prysm/v1alpha1/generated.ssz.go
Labels: peerDAS

#14106 proposer settings log ux
  config/proposer/loader/loader.go
Labels: UX

#14111 Do not fail production when consensus block value is unavailable
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/eth/validator/log.go
Labels: Ready For Review, API

#14117 [PeerDAS] Move custody subnet count into helper function
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/peerdas/BUILD.bazel
  beacon-chain/core/peerdas/helpers.go
  beacon-chain/p2p/custody.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/subnets.go
  beacon-chain/sync/data_columns_reconstruct.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_data_column_sidecars_by_root.go
Labels: peerDAS

#14125 More tracing in the validator client
  validator/client/aggregate.go
  validator/client/attest.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/activation_test.go
  validator/client/beacon-api/attestation_data_test.go
  validator/client/beacon-api/beacon_api_beacon_chain_client_test.go
  validator/client/beacon-api/beacon_api_helpers_test.go
  validator/client/beacon-api/beacon_api_node_client_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_api_validator_client_test.go
  validator/client/beacon-api/beacon_committee_selections_test.go
  validator/client/beacon-api/domain_data_test.go
  validator/client/beacon-api/doppelganger_test.go
  validator/client/beacon-api/duties_test.go
  validator/client/beacon-api/genesis_test.go
  validator/client/beacon-api/get_beacon_block_test.go
  validator/client/beacon-api/index_test.go
  validator/client/beacon-api/prepare_beacon_proposer_test.go
  validator/client/beacon-api/propose_attestation_test.go
  validator/client/beacon-api/propose_beacon_block_altair_test.go
  validator/client/beacon-api/propose_beacon_block_bellatrix_test.go
  validator/client/beacon-api/propose_beacon_block_blinded_bellatrix_test.go
  validator/client/beacon-api/propose_beacon_block_blinded_capella_test.go
  validator/client/beacon-api/propose_beacon_block_blinded_deneb_test.go
  validator/client/beacon-api/propose_beacon_block_capella_test.go
  validator/client/beacon-api/propose_beacon_block_deneb_test.go
  validator/client/beacon-api/propose_beacon_block_phase0_test.go
  validator/client/beacon-api/propose_beacon_block_test.go
  validator/client/beacon-api/propose_exit_test.go
  validator/client/beacon-api/registration_test.go
  validator/client/beacon-api/state_validators_test.go
  validator/client/beacon-api/status_test.go
  validator/client/beacon-api/stream_blocks_test.go
  validator/client/beacon-api/submit_aggregate_selection_proof_test.go
  validator/client/beacon-api/submit_signed_aggregate_proof_test.go
  validator/client/beacon-api/submit_signed_contribution_and_proof_test.go
  validator/client/beacon-api/subscribe_committee_subnets_test.go
  validator/client/beacon-api/sync_committee_selections_test.go
  validator/client/beacon-api/sync_committee_test.go
  validator/client/beacon-api/validator_count_test.go
  validator/client/beacon-api/wait_for_chain_start_test.go
  validator/client/propose.go
  validator/client/registration.go
  validator/client/runner.go
  validator/client/sync_committee.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review, Validator Client

#14122 [PeerDAS] Add data column batch size config
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc_data_column_sidecars_by_root.go
  cmd/beacon-chain/flags/base.go
  cmd/beacon-chain/flags/config.go
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  testing/endtoend/components/beacon_node.go
Labels: peerDAS

#14109 PeerDAS: Implement IncrementalDAS
  beacon-chain/core/peerdas/BUILD.bazel
  beacon-chain/core/peerdas/helpers.go
  beacon-chain/core/peerdas/helpers_test.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/custody.go
  beacon-chain/p2p/custody_test.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_host.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/p2p/utils_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/data_columns_sampling.go
  beacon-chain/sync/data_columns_sampling_test.go
  beacon-chain/sync/rpc_data_column_sidecars_by_root.go
  beacon-chain/sync/service.go
Labels: peerDAS

#14085 EIP-7549: p2p and sync
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/p2p/gossip_topic_mappings_test.go
  beacon-chain/p2p/types/BUILD.bazel
  beacon-chain/p2p/types/object_mapping.go
  beacon-chain/p2p/types/object_mapping_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/decode_pubsub.go
  beacon-chain/sync/decode_pubsub_test.go
  beacon-chain/sync/fuzz_exports.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/rpc_chunked_response.go
  beacon-chain/sync/rpc_chunked_response_test.go
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_metadata_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_beacon_aggregate_proof.go
  beacon-chain/sync/subscriber_beacon_attestation.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_electra.go
  beacon-chain/sync/validate_beacon_attestation_electra_test.go
  beacon-chain/sync/validate_beacon_attestation_test.go
Labels: Ready For Review, Networking, Electra

#14135 Enable golang.org/x/tools/go/analysis/errorsas static analysis check
  BUILD.bazel
Labels: Ready For Review

#14138 Remove electra duplicate helpers
  beacon-chain/core/electra/consolidations.go
  beacon-chain/core/electra/upgrade.go
  beacon-chain/core/electra/validator.go
  beacon-chain/core/electra/validator_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
Labels: Cleanup, Electra

#14121 EIP-7549: attestation pool
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/kv/block.go
  beacon-chain/operations/attestations/kv/forkchoice.go
  beacon-chain/operations/attestations/kv/kv.go
  beacon-chain/operations/attestations/kv/seen_bits.go
  beacon-chain/operations/attestations/kv/seen_bits_test.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/operations/attestations/kv/unaggregated_test.go
  beacon-chain/operations/attestations/pool.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/operations/attestations/service.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator.go
  proto/prysm/v1alpha1/attestation/BUILD.bazel
  proto/prysm/v1alpha1/attestation/aggregation/attestations/BUILD.bazel
  proto/prysm/v1alpha1/attestation/aggregation/attestations/maxcover.go
  proto/prysm/v1alpha1/attestation/id.go
  proto/prysm/v1alpha1/attestation/id_test.go
Labels: Ready For Review, Electra

#14139 Cleanup: making process deposit more spec readable and fork specific
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/deposit.go
  beacon-chain/core/altair/deposit_fuzz_test.go
  beacon-chain/core/altair/deposit_test.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/deposit.go
  beacon-chain/core/blocks/deposit_test.go
  beacon-chain/core/transition/state-bellatrix.go
  beacon-chain/core/transition/state.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/deposit.go
  runtime/interop/BUILD.bazel
  runtime/interop/premine-state.go
  testing/spectest/shared/phase0/operations/BUILD.bazel
  testing/spectest/shared/phase0/operations/deposit.go
Labels: Cleanup

#13682 Web3signer: persistent public keys
  cmd/validator/accounts/exit.go
  cmd/validator/accounts/wallet_utils.go
  cmd/validator/flags/flags.go
  cmd/validator/main.go
  cmd/validator/usage.go
  io/file/BUILD.bazel
  io/file/fileutil.go
  io/file/fileutil_test.go
  io/file/log.go
  testing/endtoend/components/validator.go
  testing/endtoend/minimal_scenario_e2e_test.go
  testing/endtoend/types/types.go
  validator/accounts/iface/wallet.go
  validator/accounts/testing/mock.go
  validator/accounts/wallet/wallet.go
  validator/accounts/wallet/wallet_test.go
  validator/client/BUILD.bazel
  validator/client/validator_test.go
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/internal/BUILD.bazel
  validator/keymanager/remote-web3signer/internal/client.go
  validator/keymanager/remote-web3signer/internal/client_test.go
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/keymanager_test.go
  validator/keymanager/remote-web3signer/log.go
  validator/keymanager/types.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/node/node_test.go
  validator/rpc/BUILD.bazel
  validator/rpc/handlers_keymanager.go
  validator/rpc/handlers_keymanager_test.go
Labels: API, Web3Signer, UX

#14146 Finalized validator index cache saving
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/state/state-native/setters_misc.go
Labels: Electra

#14148 Revert Backoff When Searching For Viable Peers
  beacon-chain/p2p/iterator.go
Labels: Ready For Review, Networking

#14156 Increase attestation seen cache exp time to two epochs
  beacon-chain/operations/attestations/kv/kv.go
Labels: Ready For Review

#14150 `IndexedAtt` wrapper for the slasher feed
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/receive_block.go
  beacon-chain/slasher/receive.go
  beacon-chain/slasher/receive_test.go
  beacon-chain/slasher/service.go
  beacon-chain/slasher/types/BUILD.bazel
  beacon-chain/slasher/types/types.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/validate_beacon_attestation.go
  testing/endtoend/evaluators/slashing.go
  testing/slasher/simulator/BUILD.bazel
  testing/slasher/simulator/simulator.go
Labels: Ready For Review, Slasher

#14010 Electra: Properly Calculate Proposer Probabilities for MaxEB
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
Labels: Electra

#13944 EIP-6110: Supply validator deposits on chain
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/deposit_fuzz_test.go
  beacon-chain/core/electra/deposits.go
  beacon-chain/core/electra/deposits_test.go
  beacon-chain/core/electra/transition.go
  beacon-chain/core/electra/transition_no_verify_sig.go
  beacon-chain/core/electra/transition_test.go
  beacon-chain/core/electra/validator.go
  beacon-chain/core/electra/validator_test.go
  beacon-chain/core/electra/withdrawals_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits_test.go
  runtime/interop/premine-state.go
  testing/spectest/mainnet/electra/operations/BUILD.bazel
  testing/spectest/mainnet/electra/operations/deposit_requests_test.go
  testing/spectest/mainnet/electra/operations/deposit_test.go
  testing/spectest/minimal/electra/operations/BUILD.bazel
  testing/spectest/minimal/electra/operations/deposit_requests_test.go
  testing/spectest/minimal/electra/operations/deposit_test.go
  testing/spectest/shared/electra/operations/BUILD.bazel
  testing/spectest/shared/electra/operations/deposit.go
  testing/spectest/shared/electra/operations/deposit_request.go
  testing/util/electra_state.go
Labels: Ready For Review, Electra

#14005 eip-7251: process_registry_updates
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/registry_updates.go
  beacon-chain/core/electra/registry_updates_test.go
  beacon-chain/core/electra/transition.go
  testing/spectest/mainnet/electra/epoch_processing/BUILD.bazel
  testing/spectest/mainnet/electra/epoch_processing/registry_updates_test.go
  testing/spectest/minimal/electra/epoch_processing/BUILD.bazel
  testing/spectest/minimal/electra/epoch_processing/registry_updates_test.go
  testing/spectest/shared/electra/epoch_processing/BUILD.bazel
  testing/spectest/shared/electra/epoch_processing/registry_updates.go
Labels: Electra

#14112 Update to v1.5.0-alpha.3 spec tests
  WORKSPACE
  beacon-chain/rpc/eth/config/handlers_test.go
  beacon-chain/state/state-native/getters_withdrawal_test.go
  config/params/config.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  proto/prysm/v1alpha1/attestation.pb.go
  proto/prysm/v1alpha1/attestation.proto
  testing/spectest/shared/electra/operations/deposit_request.go
  testing/spectest/shared/electra/operations/withdrawal_request.go
  testing/spectest/shared/electra/ssz_static/ssz_static.go
Labels: Ready For Review
