Repository OffchainLabs/prysm, pull requests merged in 2024-01, with the labels that each got.

#13394 Check kzg commitment count from builder
  api/client/builder/client_test.go
  api/client/builder/types.go
  api/client/builder/types_test.go
Labels: Ready For Review

#13370 Update libp2p/go-libp2p-asn-util to v0.4.1
  deps.bzl
  go.mod
  go.sum
Labels: dependencies

#13398 Increase Blob Batch Parameters in E2E
  testing/endtoend/components/beacon_node.go
Labels: Ready For Review, E2E Tests

#13395 Fix Up Builder Evaluator
  testing/endtoend/evaluators/BUILD.bazel
  testing/endtoend/evaluators/builder.go
  testing/middleware/builder/builder.go
Labels: Ready For Review, E2E Tests

#13390 Add Goerli Deneb Fork Epoch
  WORKSPACE
  config/params/BUILD.bazel
  config/params/testnet_config_test.go
  config/params/testnet_prater_config.go
  config/params/testnet_prater_config_test.go
Labels: Ready For Review

#13399 Remove getPayloadAttributes from FCU call
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/forkchoice_update_execution.go
  beacon-chain/blockchain/process_block.go
  consensus-types/payload-attribute/getters.go
  consensus-types/payload-attribute/getters_test.go
  consensus-types/payload-attribute/interface.go
Labels: Ready For Review

#13400 Simplify fcu 2
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/blockchain/forkchoice_update_execution.go
  beacon-chain/blockchain/process_block.go
  time/slots/slottime.go
  time/slots/slottime_test.go
Labels: Ready For Review

#13402 Remove the getPayloadAttribute call from updateForkchoiceWithExecution
  beacon-chain/blockchain/forkchoice_update_execution.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
Labels: Ready For Review

#13404 Fetch Goroutine Traces in E2E Too
  testing/endtoend/helpers/helpers.go
Labels: Ready For Review, E2E Tests

#13405 Make Reorging Of Late Blocks The Permanent Default
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_attestation.go
  beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
  beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review

#13355 Fix batch pruning errors
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/blob_test.go
  beacon-chain/db/filesystem/ephemeral.go
Labels: Deneb

#13412 Initialize blob storage without pruning
  beacon-chain/db/filesystem/metrics.go
  beacon-chain/node/node.go
Labels: Ready For Review

#13415 Update Our Golang Crypto Library
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review, Security

#13411 Add rpc trigger for blob sidecar event
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Ready For Review, API, Deneb

#13410 Use Afero Walk for Pruning Blob
  beacon-chain/db/filesystem/blob.go
Labels: Ready For Review

#13354 REST VC: Subscribe to Beacon API events
  api/headers.go
  beacon-chain/gateway/BUILD.bazel
  beacon-chain/gateway/helpers.go
  beacon-chain/rpc/eth/events/BUILD.bazel
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/events/events_test.go
  testing/validator-mock/validator_client_mock.go
  validator/accounts/testing/mock.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/event_handler.go
  validator/client/beacon-api/event_handler_test.go
  validator/client/beacon-api/stream_blocks.go
  validator/client/grpc-api/grpc_validator_client.go
  validator/client/iface/validator.go
  validator/client/iface/validator_client.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/testutil/mock_validator.go
  validator/client/validator-client-factory/validator_client_factory.go
  validator/client/validator.go
  validator/node/BUILD.bazel
  validator/node/node.go
  validator/rpc/handlers_health.go
  validator/rpc/handlers_health_test.go
Labels: Ready For Review, Validator Client

#13409 adding builder boost factor to get block v3
  beacon-chain/rpc/eth/shared/BUILD.bazel
  beacon-chain/rpc/eth/shared/request.go
  beacon-chain/rpc/eth/shared/request_test.go
  beacon-chain/rpc/eth/validator/BUILD.bazel
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.proto
Labels: Ready For Review, API

#13417 Enhance blob pruning log
  beacon-chain/db/filesystem/blob.go
Labels: Ready For Review

#13406 Make New Engine Methods The Permanent Default
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review

#13421 Enable Profiling for Long Running E2E Runs
  testing/endtoend/endtoend_setup_test.go
Labels: Ready For Review, E2E Tests

#13414 proposer and attester slashing sse
  beacon-chain/core/feed/operation/events.go
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  beacon-chain/rpc/eth/events/BUILD.bazel
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/events/events_test.go
  beacon-chain/rpc/eth/shared/conversions.go
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_proposer_slashing_test.go
Labels: Ready For Review, API

#13407 Make Aggregating In Parallel The Permanent Default
  beacon-chain/operations/attestations/BUILD.bazel
  beacon-chain/operations/attestations/kv/BUILD.bazel
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/aggregated_test.go
  beacon-chain/operations/attestations/prepare_forkchoice_test.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review

#13427 Unlock forkchoice store if attribute is empty
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review

#13429 Add Detailed Multi Value Metrics
  beacon-chain/blockchain/metrics.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/multi_value_slices.go
  beacon-chain/state/state-native/state_trie.go
  container/multi-value-slice/multi_value_slice.go
Labels: Ready For Review

#13438 Remove old blob types
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/kzg/BUILD.bazel
  beacon-chain/blockchain/kzg/validation.go
  beacon-chain/blockchain/kzg/validation_test.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/blob.go
  beacon-chain/db/kv/blob_test.go
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/kv_test.go
  beacon-chain/db/kv/schema.go
  beacon-chain/node/node.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/blobs.pb.go
  proto/prysm/v1alpha1/blobs.proto
  proto/prysm/v1alpha1/generated.ssz.go
  testing/spectest/general/deneb/kzg/BUILD.bazel
  testing/spectest/general/deneb/kzg/verify_blob_kzg_proof_batch_test.go
  testing/spectest/shared/deneb/ssz_static/ssz_static.go
Labels: Ready For Review

#13440 Update go to 1.21.6
  WORKSPACE
Labels: Ready For Review, Security

#13446 Use a single rest handler
  validator/accounts/cli_manager.go
  validator/client/beacon-api/beacon_api_beacon_chain_client.go
  validator/client/beacon-api/beacon_api_node_client.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/json_rest_handler.go
  validator/client/beacon-api/json_rest_handler_test.go
  validator/client/beacon-api/prysm_beacon_chain_client.go
  validator/client/beacon-chain-client-factory/beacon_chain_client_factory.go
  validator/client/node-client-factory/node_client_factory.go
  validator/client/service.go
  validator/client/validator-client-factory/validator_client_factory.go
  validator/rpc/BUILD.bazel
  validator/rpc/beacon.go
Labels: Ready For Review, Validator Client

#13456 Delete invalid blob at block processing
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/setup_test.go
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/blob_test.go
Labels: Ready For Review

#13444 Add the Abillity to Defragment the Beacon State
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/defragment.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/multi_value_slices.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  container/multi-value-slice/multi_value_slice.go
  container/multi-value-slice/multi_value_slice_test.go
Labels: Ready For Review

#13457 Fix port logging in bootnode
  tools/bootnode/bootnode.go
Labels: Ready For Review

#13467 Add Spans to Core Validator Methods
  beacon-chain/rpc/core/BUILD.bazel
  beacon-chain/rpc/core/validator.go
Labels: Ready For Review

#13448 Improve wait for activation
  validator/accounts/iface/wallet.go
  validator/accounts/testing/mock.go
  validator/accounts/wallet/wallet.go
  validator/accounts/wallet_create.go
  validator/client/key_reload.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/client/wait_for_activation.go
  validator/client/wait_for_activation_test.go
  validator/keymanager/local/keymanager.go
  validator/keymanager/local/refresh.go
Labels: UX, Validator Client

#13473 Capitalize Aggregated Unaggregated Attestations Log
  beacon-chain/operations/attestations/prepare_forkchoice.go
Labels: Ready For Review

#13465 Late block: move checking of empty attribute earlier
  beacon-chain/blockchain/process_block.go
Labels: Ready For Review

#13481 Change blob latency metrics to ms
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/metrics.go
Labels: Ready For Review

#13472 Enhance block by root log
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/pending_blocks_queue.go
Labels: Ready For Review

#13484 Allow Pcli to Run State Transitions Easily
  encoding/ssz/detect/configfork.go
  encoding/ssz/detect/configfork_test.go
  tools/pcli/BUILD.bazel
  tools/pcli/main.go
Labels: Ready For Review

#13382 Return activity penalty from attestation rewards
  beacon-chain/core/altair/epoch_precompute.go
  beacon-chain/core/altair/epoch_precompute_test.go
  beacon-chain/rpc/eth/rewards/handlers.go
  beacon-chain/rpc/eth/rewards/handlers_test.go
  beacon-chain/rpc/eth/rewards/structs.go
  testing/spectest/shared/altair/rewards/rewards_penalties.go
  testing/spectest/shared/bellatrix/rewards/rewards_penalties.go
  testing/spectest/shared/capella/rewards/rewards_penalties.go
  testing/spectest/shared/deneb/rewards/rewards_penalties.go
Labels: Ready For Review, API

#13470 Update To Deneb Compatible Lighthouse For E2E
  testing/endtoend/deps.bzl
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
Labels: Ready For Review, E2E Tests

#13488 Remove debug setting highest slot log
  validator/client/validator.go
Labels: Ready For Review

#13491 Update Sepolia Deneb fork epoch
  config/params/testnet_sepolia_config.go
Labels: Ready For Review

#13493 Fix Broken Multiclient E2E
  testing/endtoend/components/lighthouse_beacon.go
Labels: Ready For Review, E2E Tests

#13496 Fix Blob Parent Descendant Check
  beacon-chain/verification/blob.go
  beacon-chain/verification/blob_test.go
Labels: Ready For Review, Deneb

#13495 Add Debug State Transition Method
  tools/pcli/main.go
Labels: Ready For Review

#13451 cleanup duties naming
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/duties.go
  beacon-chain/rpc/prysm/v1alpha1/validator/duties_test.go
  validator/client/aggregate_test.go
  validator/client/attest.go
  validator/client/attest_test.go
  validator/client/sync_committee_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Cleanup

#13492 re-enabling jwt on keymanager API
  validator/rpc/auth_token.go
  validator/rpc/intercepter.go
  validator/rpc/intercepter_test.go
Labels: API, Security

#13490 Align aggregated att gossip validations
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_attestation.go
Labels: Ready For Review

#13510 fixing route to match specs
  beacon-chain/rpc/eth/debug/handlers_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
Labels: Bug, API

#13506 Add Holesky Deneb Epoch
  WORKSPACE
  config/params/testnet_holesky_config.go
Labels: Ready For Review

#13513 Blob API: make errors more generic
  beacon-chain/rpc/lookup/BUILD.bazel
  beacon-chain/rpc/lookup/blocker.go
Labels: API, Security

#13516 Lower Participation Rate For Multiclient Runs
  testing/endtoend/evaluators/validator.go
Labels: Ready For Review

#13517 Cleanup Validate Beacon Block
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review, Sync

#13509 Clear cache everywhere in tests of core helpers
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/helpers/beacon_committee_test.go
  beacon-chain/core/helpers/block_test.go
  beacon-chain/core/helpers/main_test.go
  beacon-chain/core/helpers/randao_test.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  beacon-chain/core/helpers/shuffle_test.go
  beacon-chain/core/helpers/sync_committee_test.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/helpers/weak_subjectivity_test.go
Labels: Ready For Review, Tests

#13521 Skip origin root when cleaning dirty state
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
Labels: Ready For Review

#13525 fixing small typo in api error messages
  beacon-chain/rpc/eth/shared/errors.go
Labels: API, UX

#13524 Enable Backfill in E2E
  beacon-chain/sync/backfill/BUILD.bazel
  beacon-chain/sync/backfill/service.go
  beacon-chain/sync/backfill/service_test.go
  beacon-chain/sync/backfill/status.go
  beacon-chain/sync/backfill/worker.go
  cmd/beacon-chain/BUILD.bazel
  cmd/beacon-chain/main.go
  cmd/beacon-chain/sync/backfill/BUILD.bazel
  cmd/beacon-chain/sync/backfill/flags/BUILD.bazel
  cmd/beacon-chain/sync/backfill/flags/flags.go
  cmd/beacon-chain/sync/backfill/options.go
  cmd/beacon-chain/usage.go
  config/features/BUILD.bazel
  config/features/flags.go
  testing/endtoend/components/beacon_node.go
Labels: Ready For Review, E2E Tests

#13531 Increase Blob Batch Limit
  cmd/beacon-chain/flags/base.go
Labels: Ready For Review

#13533 Fetch unaggregated atts in `GetAggregateAttestation`
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
Labels: Ready For Review, API

#13540 Correct metrics from ns to ms
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review

#13555 Makes Our New Deposit Trie The Default
  beacon-chain/execution/service.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review

#13542 validator exiting ux improvement, add a log and update size for promptui
  validator/accounts/accounts_helper.go
Labels: UX

#13556 Make Verbose Sig Verification the Default
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review
