Repository OffchainLabs/prysm, pull requests merged in 2024-04, with the labels that each got.

#13798 Reject Empty Bundles
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/unblinder.go
  beacon-chain/rpc/prysm/v1alpha1/validator/unblinder_test.go
Labels: Ready For Review

#13842 Send correct state root with finalization event
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
Labels: Ready For Review

#13830 Beacon-api: broadcast blobs in the event of seen block
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb_test.go
Labels: Ready For Review

#13858 Extend Broadcast Window For Attestations
  beacon-chain/p2p/broadcaster.go
Labels: Ready For Review, Networking

#13862 Add in Data Column Sidecars Data Structure
  config/params/config.go
  config/params/mainnet_config.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/data_columns.pb.go
  proto/prysm/v1alpha1/data_columns.proto
  proto/prysm/v1alpha1/generated.ssz.go
  proto/ssz_proto_library.bzl
  testing/validator-mock/node_client_mock.go
  validator/client/beacon-api/mock/json_rest_handler_mock.go
Labels: Ready For Review, peerDAS

#13872 Revert Peer Log Changes
  beacon-chain/p2p/options.go
  testing/endtoend/components/beacon_node.go
Labels: Ready For Review, E2E Tests

#13874 Handle overflow in retention period calculation
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/blob_test.go
Labels: Ready For Review

#13873 Use read only validators in Beacon API
  beacon-chain/rpc/eth/beacon/handlers_validator.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/getters_validator.go
Labels: Ready For Review, API

#13875 Return syncing status when node is optimistic
  beacon-chain/rpc/eth/node/handlers.go
  beacon-chain/rpc/eth/node/handlers_test.go
Labels: Ready For Review, API

#13868 Upgrade the Beacon API e2e evaluator
  testing/endtoend/evaluators/beaconapi/requests.go
  testing/endtoend/evaluators/beaconapi/types.go
  testing/endtoend/evaluators/beaconapi/util.go
  testing/endtoend/evaluators/beaconapi/verify.go
Labels: Ready For Review, API, E2E Tests

#13883 Add Support For Discovery Of Column Subnets
  beacon-chain/cache/BUILD.bazel
  beacon-chain/cache/column_subnet_ids.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/subscriber.go
Labels: Ready For Review, peerDAS

#13747 consistent auth token for validator apis
  api/BUILD.bazel
  api/constants.go
  api/jwt.go
  api/jwt_test.go
  cmd/beacon-chain/jwt/BUILD.bazel
  cmd/beacon-chain/jwt/jwt.go
  cmd/validator/flags/BUILD.bazel
  cmd/validator/flags/flags.go
  cmd/validator/main.go
  cmd/validator/usage.go
  cmd/validator/web/BUILD.bazel
  cmd/validator/web/web.go
  validator/node/node.go
  validator/rpc/BUILD.bazel
  validator/rpc/auth_token.go
  validator/rpc/auth_token_test.go
  validator/rpc/handlers_auth.go
  validator/rpc/handlers_auth_test.go
  validator/rpc/intercepter.go
  validator/rpc/intercepter_test.go
  validator/rpc/server.go
Labels: API, UX, Validator Client

#13894 Add Data Column Gossip Handlers
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_sidecar.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/core/blocks/signature.go
  beacon-chain/core/feed/operation/events.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/p2p/pubsub_filter_test.go
  beacon-chain/p2p/topics.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/decode_pubsub.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_data_column_sidecar.go
  beacon-chain/sync/validate_data_column_sidecar.go
Labels: Ready For Review, Networking, peerDAS

#13901 Helper for Payload Attestation Signing
  beacon-chain/rpc/eth/config/handlers_test.go
  config/params/config.go
  proto/engine/v1/BUILD.bazel
  proto/engine/v1/epbs.pb.go
  proto/engine/v1/epbs.proto
  proto/engine/v1/generated.ssz.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/generated.ssz.go
  proto/prysm/v1alpha1/payload_attestation.pb.go
  proto/prysm/v1alpha1/payload_attestation.pb.gw.go
  proto/prysm/v1alpha1/payload_attestation.proto
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
  testing/util/BUILD.bazel
  testing/util/payload_attestation.go
  validator/client/BUILD.bazel
  validator/client/payload_attestation.go
  validator/client/payload_attestation_test.go
Labels: Ready For Review

#13892 Use correct port for health check in Beacon API e2e evaluator
  testing/endtoend/evaluators/beaconapi/verify.go
  testing/endtoend/params/params.go
Labels: Ready For Review, API, E2E Tests

#13907 Electra beacon config
  WORKSPACE
  beacon-chain/rpc/eth/config/handlers_test.go
  config/params/config.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
Labels: Pectra, Electra

#13909 Add Request And Response RPC Methods For Data Columns
  beacon-chain/db/filesystem/blob.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/rpc_topic_mappings.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_peermanager.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/p2p/types/rpc_errors.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_chunked_response.go
  beacon-chain/sync/rpc_data_column_sidecars_by_root.go
  beacon-chain/sync/rpc_send_request.go
Labels: Ready For Review, peerDAS

#13929 Fix spelling
  beacon-chain/core/helpers/validators.go
Labels: Ready For Review
