Repository OffchainLabs/prysm, pull requests merged in 2024-07, with the labels that each got.

#14164 Electra: updated `get_next_sync_committee_indices`
  beacon-chain/core/altair/BUILD.bazel
  beacon-chain/core/altair/sync_committee.go
  beacon-chain/core/altair/sync_committee_test.go
Labels: Electra

#14115 EIP-7549: Aggregation gRPC metods
  beacon-chain/rpc/core/validator.go
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go
  proto/prysm/v1alpha1/attestation.go
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.pb.gw.go
  proto/prysm/v1alpha1/validator.proto
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
Labels: Ready For Review, API, Electra

#13965 Update to Go v1.22
  .github/actions/gomodtidy/Dockerfile
  .github/workflows/fuzz.yml
  .github/workflows/go.yml
  .golangci.yml
  WORKSPACE
  deps.bzl
  go.mod
  go.sum
  testing/endtoend/components/eth1/transactions.go
Labels: Ready For Review

#14163 Electra: new `process_consolidation_request`
  beacon-chain/core/electra/churn_test.go
  beacon-chain/core/electra/consolidations.go
  beacon-chain/core/electra/consolidations_test.go
  beacon-chain/core/helpers/validators.go
  testing/spectest/mainnet/electra/operations/consolidation_test.go
  testing/spectest/shared/electra/operations/consolidations.go
Labels: Electra

#14136 chore: Encapsulate all kzg functionality for PeerDAS into the kzg package
  beacon-chain/blockchain/kzg/BUILD.bazel
  beacon-chain/blockchain/kzg/kzg.go
  beacon-chain/core/peerdas/BUILD.bazel
  beacon-chain/core/peerdas/helpers.go
  beacon-chain/core/peerdas/helpers_test.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/unblinder.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/data_columns_reconstruct.go
Labels: peerDAS

#14151 Fix slasher disk usage leak.
  beacon-chain/db/iface/interface.go
  beacon-chain/db/slasherkv/BUILD.bazel
  beacon-chain/db/slasherkv/migrate.go
  beacon-chain/db/slasherkv/migrate_test.go
  beacon-chain/db/slasherkv/pruning.go
  beacon-chain/db/slasherkv/pruning_test.go
  beacon-chain/db/slasherkv/slasher.go
  beacon-chain/slasher/service.go
Labels: Slasher

#14192 Update Libp2p to v0.35.2
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review

#14184 Activate PeerDAS with the EIP7594 Fork Epoch
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/time/slot_epoch.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/utils.go
  beacon-chain/rpc/eth/config/handlers_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/data_columns_sampling.go
  beacon-chain/sync/fork_watcher.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_data_column_sidecars_by_root.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  config/features/config.go
  config/features/flags.go
  config/params/config.go
  config/params/loader.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  config/params/testnet_e2e_config.go
  config/params/testnet_holesky_config.go
  config/params/testnet_sepolia_config.go
Labels: Ready For Review, Networking, peerDAS

#14178 Add Aggregated Public Key Method
  beacon-chain/core/blocks/signature.go
  beacon-chain/state/BUILD.bazel
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/getters_validator.go
  beacon-chain/state/state-native/getters_validator_test.go
Labels: Ready For Review

#14187 PeerDAS: Add KZG verification when sampling
  beacon-chain/core/peerdas/helpers_test.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/data_columns_sampling.go
  beacon-chain/sync/data_columns_sampling_test.go
  beacon-chain/sync/validate_data_column.go
  consensus-types/blocks/kzg_test.go
Labels: Ready For Review, peerDAS

#14197 Optimize ProcessRegistryUpdates Further
  beacon-chain/core/electra/registry_updates.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/helpers/validators.go
Labels: Ready For Review

#14193 Trigger PeerDAS At Deneb For E2E
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc.go
  cmd/beacon-chain/flags/base.go
  config/params/testnet_e2e_config.go
  testing/endtoend/components/beacon_node.go
  testing/endtoend/types/fork.go
Labels: Ready For Review, peerDAS

#14176 Electra: EIP-7251 Update `process_voluntary_exit`
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/blocks/exit_test.go
  testing/spectest/mainnet/electra/operations/voluntary_exit_test.go
  testing/spectest/minimal/electra/operations/voluntary_exit_test.go
Labels: Electra

#14201 Avoid Cloning When Creating a New Gossip Message
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/p2p/gossip_topic_mappings_test.go
  beacon-chain/sync/decode_pubsub.go
Labels: Ready For Review, Networking

#14158 EIP-7549: validator client
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/attester.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
  proto/prysm/v1alpha1/validator-client/keymanager.pb.go
  proto/prysm/v1alpha1/validator-client/keymanager.proto
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.pb.gw.go
  proto/prysm/v1alpha1/validator.proto
  testing/mock/beacon_service_mock.go
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
  testing/validator-mock/chain_client_mock.go
  testing/validator-mock/prysm_chain_client_mock.go
  testing/validator-mock/validator_client_mock.go
  validator/client/aggregate.go
  validator/client/aggregate_test.go
  validator/client/attest.go
  validator/client/attest_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/grpc-api/grpc_prysm_beacon_chain_client_test.go
  validator/client/grpc-api/grpc_validator_client.go
  validator/client/iface/validator_client.go
  validator/client/key_reload_test.go
  validator/client/validator_test.go
  validator/client/wait_for_activation_test.go
  validator/rpc/handlers_beacon_test.go
Labels: Ready For Review, API, Validator Client, Electra

#14200 State: HasPendingBalanceToWithdraw
  beacon-chain/core/blocks/exit.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/getters_validator.go
  beacon-chain/state/state-native/getters_validator_test.go
Labels: Electra

#14212 adding electra version to payload attribute event
  beacon-chain/rpc/eth/events/events.go
Labels: API, Electra

#14203 EIP-7549: Allow multiple committee bits
  proto/prysm/v1alpha1/attestation/BUILD.bazel
  proto/prysm/v1alpha1/attestation/id.go
  proto/prysm/v1alpha1/attestation/id_test.go
Labels: Ready For Review, Electra

#14180 Electra: Handle AttestationElectra in forkchoice spectest
  testing/spectest/shared/common/forkchoice/builder.go
  testing/spectest/shared/common/forkchoice/runner.go
Labels: Electra

#14181 Electra: EIP-7251 implement process_withdrawal updates
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/core/electra/withdrawals.go
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/state/state-native/getters_withdrawal.go
Labels: Electra

#14215 Fix effective balance updates in Electra
  beacon-chain/core/electra/effective_balance_updates.go
Labels: Electra

#14219 Electra: process_consolidation_requests in state transition
  beacon-chain/core/electra/transition_no_verify_sig.go
Labels: Electra

#14221 Electra: process_registry_updates handle exiting validators
  beacon-chain/core/electra/registry_updates.go
  beacon-chain/core/electra/registry_updates_test.go
Labels: Electra

#14224 Electra: Add minimal spectests for sync_committee_updates
  testing/spectest/minimal/electra/epoch_processing/BUILD.bazel
  testing/spectest/minimal/electra/epoch_processing/sync_committee_updates_test.go
  testing/spectest/shared/electra/epoch_processing/BUILD.bazel
  testing/spectest/shared/electra/epoch_processing/sync_committee_updates.go
Labels: Electra

#14209 Payload attributes misleading value fix
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/eth/events/BUILD.bazel
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/events/events_test.go
  beacon-chain/rpc/eth/events/server.go
Labels: Bug, API, Builder

#14227 Add missing pieces of Electra
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/blockchain/execution_engine_test.go
  beacon-chain/db/kv/encoding.go
  beacon-chain/rpc/core/validator.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
  validator/db/filesystem/attester_protection.go
  validator/db/iface/interface.go
  validator/db/kv/attester_protection.go
  validator/helpers/metadata_test.go
Labels: Ready For Review, Electra

#14105 [PeerDAS] Parallelize data column sampling
  beacon-chain/core/peerdas/helpers.go
  beacon-chain/sync/data_columns_sampling.go
  beacon-chain/sync/data_columns_sampling_test.go
  beacon-chain/sync/service.go
Labels: peerDAS

#14231 Use Proposer Cache to Verify Data Columns
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_data_column.go
  beacon-chain/verification/initializer.go
  beacon-chain/verification/interface.go
Labels: Ready For Review, peerDAS

#14229 adding consolidation requests to json serialization
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/payload_body_test.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
  testing/util/electra.go
Labels: Ready For Review, API, Electra

#14235 electra payload fix for devnet1
  beacon-chain/execution/engine_client_test.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
Labels: Electra

#14241 removing unused naming convention
  config/params/loader_test.go
  testing/spectest/exclusions.txt
Labels: Cleanup

#14198 HTTP endpoint `GetIndividualVotes`
  api/server/structs/endpoints_beacon.go
  beacon-chain/rpc/core/service.go
  beacon-chain/rpc/core/validator.go
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/endpoints_test.go
  beacon-chain/rpc/prysm/beacon/BUILD.bazel
  beacon-chain/rpc/prysm/beacon/handlers.go
  beacon-chain/rpc/prysm/beacon/handlers_test.go
  beacon-chain/rpc/prysm/beacon/server.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/assignments.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/committees_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
Labels: API

#14238 EIP-7549: Attestation packing
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_electra.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_electra_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go
Labels: Ready For Review, Electra

#14239 payload electra cloning
  proto/engine/v1/BUILD.bazel
  proto/engine/v1/execution_engine.go
  proto/engine/v1/execution_engine_fuzz_test.go
  proto/engine/v1/export_test.go
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
Labels: Ready For Review, Cleanup, Electra

#14246 creating execution payload copy and fuzz tests
  beacon-chain/state/state-native/getters_payload_header.go
  beacon-chain/state/state-native/getters_state.go
  beacon-chain/state/state-native/state_trie.go
  proto/engine/v1/execution_engine.go
  proto/engine/v1/execution_engine_fuzz_test.go
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
Labels: Cleanup

#14173 remove eip6110flag for validator index cache
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/state/state-native/getters_validator.go
  beacon-chain/state/state-native/setters_misc.go
  beacon-chain/state/state-native/state_trie.go
  config/features/config.go
  config/features/flags.go
Labels: Ready For Review, Electra

#14225 Proposer: filter attestations for invalid signature
  beacon-chain/blockchain/chain_info.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go
Labels: Ready For Review

#14265 moving cloner functions to beacon_block.go
  beacon-chain/sync/pending_blocks_queue_test.go
  consensus-types/blocks/getters.go
  proto/prysm/v1alpha1/beacon_block.go
  proto/prysm/v1alpha1/beacon_block_fuzz_test.go
  proto/prysm/v1alpha1/cloners.go
  proto/prysm/v1alpha1/cloners_test.go
Labels: Ready For Review, Cleanup

#14155 Push proposer settings every slot
  validator/client/runner.go
  validator/client/runner_test.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Ready For Review, API

#14272 missed adding electra process epoch on state replay - devnet 1
  beacon-chain/core/electra/transition_test.go
  beacon-chain/core/transition/transition.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
Labels: Electra

#14280 adding corrected returns under handle error
  beacon-chain/rpc/eth/beacon/handlers.go
Labels: Bug, API

#14285 removing explicit deadlines on push proposer settings
  validator/accounts/testing/mock.go
  validator/client/iface/validator.go
  validator/client/runner.go
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
Labels: Bug
