Repository OffchainLabs/prysm, pull requests merged in 2024-05, with the labels that each got.

#13938 Add DA Check For Data Columns
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/error.go
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_data_column.go
  beacon-chain/blockchain/receive_sidecar.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/setup_test.go
  beacon-chain/db/filesystem/blob.go
  beacon-chain/p2p/interfaces.go
  config/fieldparams/mainnet.go
  config/fieldparams/minimal.go
Labels: Ready For Review, peerDAS

#13940 Spectests
  WORKSPACE
  beacon-chain/core/peerdas/helpers.go
  config/params/config.go
  config/params/mainnet_config.go
  testing/spectest/mainnet/eip7594/networking/BUILD.bazel
  testing/spectest/mainnet/eip7594/networking/custody_columns_test.go
  testing/spectest/minimal/eip7594/networking/BUILD.bazel
  testing/spectest/minimal/eip7594/networking/custody_columns_test.go
  testing/spectest/shared/eip7594/networking/BUILD.bazel
  testing/spectest/shared/eip7594/networking/custody_columns.go
Labels: Ready For Review, peerDAS

#13943 EIP6110: add validator index cache
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/beacon_state_mainnet.go
  beacon-chain/state/state-native/beacon_state_minimal.go
  beacon-chain/state/state-native/getters_validator.go
  beacon-chain/state/state-native/readonly_validator.go
  beacon-chain/state/state-native/setters_misc.go
  beacon-chain/state/state-native/state_trie.go
  beacon-chain/state/state-native/validator_index_cache.go
  beacon-chain/state/state-native/validator_index_cache_test.go
  config/features/config.go
  config/features/flags.go
Labels: Ready For Review, Electra

#13954 Remove unused validator map copy method
  beacon-chain/state/state-native/state_test.go
  beacon-chain/state/stateutil/validator_map_handler.go
Labels: Ready For Review

#13946 EIP-7549 beacon spec
  beacon-chain/blockchain/process_block.go
  beacon-chain/core/altair/attestation.go
  beacon-chain/core/altair/attestation_test.go
  beacon-chain/core/altair/upgrade.go
  beacon-chain/core/altair/upgrade_test.go
  beacon-chain/core/blocks/attestation.go
  beacon-chain/core/blocks/attestation_test.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/precompute/attestation.go
  beacon-chain/core/epoch/precompute/attestation_test.go
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/core/helpers/beacon_committee_test.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/monitor/process_attestation.go
  beacon-chain/rpc/prysm/v1alpha1/debug/block.go
  beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  proto/prysm/v1alpha1/attestation/BUILD.bazel
  proto/prysm/v1alpha1/attestation/attestation_utils.go
  proto/prysm/v1alpha1/attestation/attestation_utils_test.go
Labels: Ready For Review, Electra

#13960 Update Libp2p Dependencies
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review, dependencies

#13959 Parallelize Broadcasting And Processing Each Blob
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Labels: Ready For Review

#13933 Electra: upgrade
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/upgrade.go
  beacon-chain/core/electra/upgrade_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/core/time/slot_epoch.go
  beacon-chain/core/time/slot_epoch_test.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/rpc/eth/beacon/handlers_validator.go
  beacon-chain/rpc/eth/config/handlers_test.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/getters_exit.go
  beacon-chain/state/state-native/getters_exit_test.go
  beacon-chain/state/state-native/readonly_validator.go
  beacon-chain/state/state-native/readonly_validator_test.go
  beacon-chain/state/stategen/BUILD.bazel
  beacon-chain/state/stategen/replay.go
  beacon-chain/state/stategen/replay_test.go
  config/params/config.go
  config/params/loader.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  consensus-types/interfaces/BUILD.bazel
  consensus-types/interfaces/validator.go
  testing/endtoend/evaluators/operations.go
  testing/spectest/mainnet/electra/fork_helper/BUILD.bazel
  testing/spectest/mainnet/electra/fork_helper/upgrade_to_electra_test.go
  testing/spectest/minimal/electra/fork/BUILD.bazel
  testing/spectest/minimal/electra/fork/upgrade_to_electra_test.go
  testing/spectest/shared/electra/fork/BUILD.bazel
  testing/spectest/shared/electra/fork/upgrade_to_electra.go
  testing/util/BUILD.bazel
  testing/util/electra_state.go
Labels: Electra

#13975 Add electra DB
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/db/kv/key.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/kv/state_test.go
  encoding/ssz/equality/BUILD.bazel
  encoding/ssz/equality/deep_equal.go
  testing/util/electra_state.go
Labels: Ready For Review

#13985 Add p2p support for Electra
  beacon-chain/p2p/fork_watcher.go
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/p2p/gossip_topic_mappings_test.go
  beacon-chain/p2p/pubsub_filter.go
  beacon-chain/p2p/types/object_mapping.go
Labels: Ready For Review

#13945 Enable E2E For PeerDAS
  beacon-chain/blockchain/kzg/BUILD.bazel
  beacon-chain/blockchain/kzg/trusted_setup.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_data_column.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/core/peerdas/BUILD.bazel
  beacon-chain/core/peerdas/helpers.go
  beacon-chain/core/peerdas/helpers_test.go
  beacon-chain/db/filesystem/cache.go
  beacon-chain/db/filesystem/cache_test.go
  beacon-chain/node/node.go
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/gossip_scoring_params.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/validate_data_column.go
  config/features/config.go
  consensus-types/blocks/kzg.go
  testing/endtoend/components/beacon_node.go
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/evaluators/metrics.go
Labels: peerDAS

#13992 Fix `GetPayloadMethodV4` endpoint string
  beacon-chain/execution/engine_client.go
Labels: Ready For Review

#13994 Support version Electra for ForkchoiceUpdated
  beacon-chain/execution/engine_client.go
  consensus-types/payload-attribute/getters.go
Labels: Ready For Review

#13993 Correctly return electra attestations for block getter
  consensus-types/blocks/getters.go
  consensus-types/blocks/getters_test.go
Labels: Ready For Review

#13972 Implement Data Columns By Range Request And Response Methods
  beacon-chain/das/BUILD.bazel
  beacon-chain/das/availability_columns.go
  beacon-chain/das/cache.go
  beacon-chain/db/filesystem/blob.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/rpc_topic_mappings.go
  beacon-chain/p2p/utils.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_data_column_sidecars_by_range.go
  beacon-chain/sync/rpc_send_request.go
  beacon-chain/sync/verify/blob.go
  consensus-types/blocks/roblock.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/generated.ssz.go
  proto/prysm/v1alpha1/p2p_messages.pb.go
  proto/prysm/v1alpha1/p2p_messages.proto
Labels: Ready For Review, peerDAS

#13999 Support Electra for WriteBlockChunk
  beacon-chain/sync/rpc_chunked_response.go
Labels: Ready For Review

#13980 Sample from peers some data columns.
  beacon-chain/p2p/discovery.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/rate_limiter_test.go
  beacon-chain/sync/rpc_data_column_sidecars_by_root.go
  beacon-chain/sync/rpc_send_request.go
  beacon-chain/sync/sampling_data_columns.go
  beacon-chain/sync/service.go
Labels: peerDAS

#13983 eip-7251: process consolidations
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/consolidations.go
  beacon-chain/core/electra/consolidations_test.go
  testing/spectest/mainnet/electra/epoch_processing/BUILD.bazel
  testing/spectest/mainnet/electra/epoch_processing/pending_consolidations_test.go
  testing/spectest/mainnet/electra/operations/BUILD.bazel
  testing/spectest/mainnet/electra/operations/consolidation_test.go
  testing/spectest/minimal/electra/epoch_processing/BUILD.bazel
  testing/spectest/minimal/electra/epoch_processing/pending_consolidations_test.go
  testing/spectest/minimal/electra/operations/BUILD.bazel
  testing/spectest/minimal/electra/operations/consolidation_test.go
  testing/spectest/shared/electra/epoch_processing/BUILD.bazel
  testing/spectest/shared/electra/epoch_processing/pending_consolidations.go
  testing/spectest/shared/electra/operations/BUILD.bazel
  testing/spectest/shared/electra/operations/consolidations.go
Labels: Electra

#14002 eip-7251: process_pending_balance_deposits
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/balance_deposits.go
  beacon-chain/core/electra/balance_deposits_test.go
  beacon-chain/core/electra/consolidations_test.go
  testing/spectest/mainnet/electra/epoch_processing/BUILD.bazel
  testing/spectest/mainnet/electra/epoch_processing/pending_balance_updates_test.go
  testing/spectest/minimal/electra/epoch_processing/BUILD.bazel
  testing/spectest/minimal/electra/epoch_processing/pending_balance_updates_test.go
  testing/spectest/shared/electra/epoch_processing/BUILD.bazel
  testing/spectest/shared/electra/epoch_processing/pending_balance_updates.go
Labels: Electra

#14000 Electra payload body engine methods
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/mock_test.go
  beacon-chain/execution/payload_body.go
  beacon-chain/execution/payload_body_test.go
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/generated.ssz.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
  proto/eth/v1/generated.ssz.go
  proto/eth/v2/generated.ssz.go
  proto/prysm/v1alpha1/generated.ssz.go
  testing/util/deneb.go
  testing/util/electra.go
Labels: Electra

#14014 Remove Beacon API Postman collection
  hack/beacon-node-api/README.md
  hack/beacon-node-api/beacon-node-api.postman-collection.json
Labels: Ready For Review, Cleanup

#14040 WebFix develop
  api/constants.go
  validator/node/node.go
  validator/rpc/intercepter.go
  validator/rpc/server.go
Labels: Bug, API, Web UI, Validator Client

#14001 Electra core transition operations
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/deposits.go
  beacon-chain/core/electra/deposits_test.go
  beacon-chain/core/electra/effective_balance_updates.go
  beacon-chain/core/electra/registry_updates.go
  beacon-chain/core/electra/transition.go
  beacon-chain/core/electra/withdrawals.go
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  testing/spectest/minimal/electra/fork_transition/BUILD.bazel
  testing/spectest/minimal/electra/fork_transition/transition_test.go
Labels: Ready For Review, Electra

#14003 eip-7251: process_effective_balance_updates
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/effective_balance_updates.go
  beacon-chain/core/electra/effective_balance_updates_test.go
  testing/spectest/mainnet/electra/epoch_processing/BUILD.bazel
  testing/spectest/mainnet/electra/epoch_processing/effective_balance_updates_test.go
  testing/spectest/minimal/electra/epoch_processing/BUILD.bazel
  testing/spectest/minimal/electra/epoch_processing/effective_balance_updates_test.go
  testing/spectest/shared/electra/epoch_processing/BUILD.bazel
  testing/spectest/shared/electra/epoch_processing/effective_balance_updates.go
Labels: Electra

#14046 Only log error when aggregator check fails
  validator/client/validator.go
Labels: Ready For Review, Validator Client

#14053 Fix dependent root retrival genesis case
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
Labels: Ready For Review

#14063 api fix for panic on unsynced unfound block
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/rewards/handlers.go
Labels: Bug, API

#14068 Fix mockgen sh
  hack/update-mockgen.sh
  testing/validator-mock/chain_client_mock.go
  testing/validator-mock/prysm_chain_client_mock.go
Labels: Ready For Review

#14031 EIP-7002:Execution layer triggerable withdrawals
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/transition.go
  beacon-chain/core/electra/withdrawals.go
  beacon-chain/core/electra/withdrawals_test.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/state/state-native/getters_withdrawal.go
  testing/spectest/mainnet/electra/operations/BUILD.bazel
  testing/spectest/mainnet/electra/operations/execution_layer_withdrawals_test.go
  testing/spectest/minimal/electra/operations/BUILD.bazel
  testing/spectest/minimal/electra/operations/execution_layer_withdrawals_test.go
  testing/spectest/shared/electra/operations/execution_layer_withdrawal_request.go
Labels: Ready For Review, Electra

#14055 EIP-7549 gRPC (part 1)
  beacon-chain/rpc/prysm/v1alpha1/beacon/attestations.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/slashings.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/slashings_test.go
  proto/prysm/v1alpha1/attestation/attestation_utils.go
  proto/prysm/v1alpha1/beacon_chain.pb.go
  proto/prysm/v1alpha1/beacon_chain.pb.gw.go
  proto/prysm/v1alpha1/beacon_chain.proto
  testing/util/attestation.go
Labels: Ready For Review, API, Electra

#14028 Organize validator flags
  cmd/prysmctl/validator/cmd.go
  cmd/validator/accounts/accounts.go
  cmd/validator/accounts/backup.go
  cmd/validator/accounts/delete.go
  cmd/validator/accounts/delete_test.go
  cmd/validator/accounts/exit.go
  cmd/validator/accounts/import.go
  cmd/validator/accounts/list.go
  cmd/validator/flags/flags.go
  cmd/validator/main.go
  cmd/validator/usage.go
  cmd/validator/usage_test.go
  cmd/validator/wallet/create_test.go
  testing/endtoend/components/validator.go
  validator/accounts/accounts_list_test.go
  validator/node/node.go
Labels: Ready For Review, Cleanup, Validator Client
