Repository OffchainLabs/prysm, pull requests merged in 2024-10, with the labels that each got.

#14494 PeerDAS: Fix initial sync
  beacon-chain/p2p/peers/scorers/BUILD.bazel
  beacon-chain/p2p/peers/scorers/bad_responses.go
  beacon-chain/p2p/peers/scorers/log.go
  beacon-chain/p2p/peers/status.go
  beacon-chain/p2p/peers/status_test.go
  beacon-chain/p2p/utils.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
Labels: peerDAS

#14491 Use wait for ptc duty in submit payload attestation message
  validator/client/payload_attestation.go
  validator/client/payload_attestation_test.go
Labels: ePBS

#14496 PeerDAS: Improve initial sync logs
  beacon-chain/sync/initial-sync/blocks_fetcher.go
Labels: peerDAS

#14488 Update block Beacon APIs to Electra
  CHANGELOG.md
  api/server/structs/conversions_block.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/eth/validator/handlers_block_test.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/electra.ssz.go
Labels: Ready For Review, API, Electra

#14493 Fix Commitments Check
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/service_test.go
  beacon-chain/blockchain/setup_test.go
  beacon-chain/core/peerdas/helpers.go
  beacon-chain/das/BUILD.bazel
  beacon-chain/das/availability.go
  beacon-chain/das/availability_columns.go
  beacon-chain/das/availability_columns_test.go
  beacon-chain/das/availability_test.go
  beacon-chain/das/cache.go
  beacon-chain/das/iface.go
  beacon-chain/das/mock.go
  beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_eth1data.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
  beacon-chain/sync/backfill/BUILD.bazel
  beacon-chain/sync/backfill/status.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/rpc_data_column_sidecars_by_range.go
Labels: Ready For Review, peerDAS

#14503 Register deposit snapshot endpoint
  CHANGELOG.md
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/endpoints_test.go
  beacon-chain/rpc/eth/beacon/handlers.go
Labels: Ready For Review, API

#14507 Flip committee aware packing flag
  CHANGELOG.md
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go
  config/features/config.go
  config/features/deprecated_flags.go
  config/features/flags.go
Labels: Ready For Review

#14478 Add `/eth/v2/beacon/blocks/{block_id}/attestations`
  CHANGELOG.md
  api/server/structs/endpoints_beacon.go
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/endpoints_test.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
Labels: API, Electra

#14514 Replace validator wait for activation stream with polling
  CHANGELOG.md
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.proto
  testing/mock/beacon_validator_client_mock.go
  time/slots/slottime.go
  time/slots/slottime_test.go
  validator/client/BUILD.bazel
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/activation.go
  validator/client/beacon-api/activation_test.go
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/grpc-api/grpc_validator_client.go
  validator/client/iface/validator_client.go
  validator/client/key_reload.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/client/wait_for_activation.go
  validator/client/wait_for_activation_test.go
Labels: Ready For Review, API, Cleanup

#14526 update batch deposit message verification for better readability
  CHANGELOG.md
  beacon-chain/core/altair/deposit.go
  beacon-chain/core/altair/deposit_test.go
  beacon-chain/core/blocks/deposit.go
  beacon-chain/core/blocks/deposit_test.go
  beacon-chain/core/electra/deposits.go
  beacon-chain/core/electra/deposits_test.go
Labels: Cleanup

#14522 Data columns initial sync: Refactor
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go
  beacon-chain/sync/rpc_data_column_sidecars_by_root.go
  beacon-chain/sync/validate_data_column.go
  beacon-chain/sync/verify/blob.go
Labels: peerDAS

#14511 Switch to compounding when consolidating with source==target
  CHANGELOG.md
  beacon-chain/core/electra/consolidations.go
  beacon-chain/core/electra/consolidations_test.go
  beacon-chain/core/electra/validator.go
  beacon-chain/core/helpers/BUILD.bazel
  testing/spectest/mainnet/electra/epoch_processing/pending_consolidations_test.go
  testing/spectest/mainnet/electra/operations/consolidation_test.go
  testing/spectest/mainnet/electra/sanity/blocks_test.go
  testing/spectest/minimal/electra/epoch_processing/pending_consolidations_test.go
  testing/spectest/minimal/electra/operations/consolidation_test.go
  testing/spectest/minimal/electra/sanity/blocks_test.go
Labels: Ready For Review

#14541 Update CHANGELOG.md for v5.1.1
  CHANGELOG.md
Labels: Ready For Review

#14538 Execution API Electra: removing bodies v2 logic
  CHANGELOG.md
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/mock_test.go
  beacon-chain/execution/payload_body.go
  beacon-chain/execution/payload_body_test.go
Labels: API, Electra

#14532 PeerDAS: Fix major bug in `dataColumnSidecarsByRangeRPCHandler` and allow syncing from full nodes.
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc_data_column_sidecars_by_range.go
Labels: peerDAS

#14492 Execution API Electra: requests as a sidecar
  CHANGELOG.md
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  consensus-types/blocks/execution.go
  consensus-types/blocks/get_payload.go
  consensus-types/blocks/setters.go
  consensus-types/interfaces/beacon_block.go
  proto/engine/v1/BUILD.bazel
  proto/engine/v1/electra.go
  proto/engine/v1/electra.pb.go
  proto/engine/v1/electra.proto
  proto/engine/v1/electra_test.go
  proto/engine/v1/export_test.go
  proto/engine/v1/json_marshal_unmarshal.go
  proto/engine/v1/json_marshal_unmarshal_test.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review, API, Electra

#14456 Update correlation penalty for EIP-7251
  CHANGELOG.md
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  testing/spectest/mainnet/electra/epoch_processing/slashings_test.go
  testing/spectest/minimal/electra/epoch_processing/slashings_test.go
Labels: Electra

#14558 Use read only validator for processing
  CHANGELOG.md
  beacon-chain/core/electra/consolidations.go
  beacon-chain/core/electra/deposits.go
  beacon-chain/core/electra/validator.go
  beacon-chain/core/electra/withdrawals.go
  beacon-chain/core/helpers/sync_committee.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/BUILD.bazel
  beacon-chain/state/state-native/getters_validator.go
  beacon-chain/state/state-native/getters_validator_test.go
  beacon-chain/state/state-native/getters_withdrawal.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review

#14562 Update the monitor package to Electra
  CHANGELOG.md
  beacon-chain/monitor/process_attestation.go
Labels: Ready For Review, Electra

#14559 PeerDAS: Batch columns verifications
  beacon-chain/core/peerdas/helpers.go
  beacon-chain/core/peerdas/helpers_test.go
  beacon-chain/das/availability_columns.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/data_columns_sampling.go
  beacon-chain/sync/data_columns_sampling_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_queue.go
  beacon-chain/sync/initial-sync/round_robin.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_send_request.go
  beacon-chain/sync/service.go
  beacon-chain/sync/validate_data_column.go
  beacon-chain/sync/verify/BUILD.bazel
  beacon-chain/sync/verify/blob.go
  beacon-chain/verification/batch.go
  beacon-chain/verification/blob_test.go
  beacon-chain/verification/data_column.go
  beacon-chain/verification/data_column_test.go
  beacon-chain/verification/initializer.go
  beacon-chain/verification/interface.go
Labels: peerDAS

#14573 Set fields of wrapped proto object in light client setters
  CHANGELOG.md
  beacon-chain/core/light-client/lightclient.go
  consensus-types/interfaces/light_client.go
  consensus-types/light-client/update.go
Labels: Ready For Review, Light Client

#14513 Use engine api `get-blobs` for block subscriber
  CHANGELOG.md
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/options.go
  beacon-chain/execution/rpc_connection.go
  beacon-chain/execution/service.go
  beacon-chain/execution/service_test.go
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/node/node.go
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/server.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/metrics.go
  beacon-chain/sync/options.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  beacon-chain/sync/subscriber_blob_sidecar.go
  beacon-chain/verification/batch_test.go
  beacon-chain/verification/blob.go
  beacon-chain/verification/mock.go
  proto/engine/v1/execution_engine.pb.go
  proto/engine/v1/execution_engine.proto
  proto/engine/v1/json_marshal_unmarshal.go
  proto/prysm/v1alpha1/light_client.pb.go
Labels: Ready For Review

#14566 Add missing version headers
  CHANGELOG.md
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
Labels: API

#14560 Add `GET /eth/v2/beacon/pool/attestations` endpoint
  CHANGELOG.md
  api/server/structs/endpoints_beacon.go
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/endpoints_test.go
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  config/params/config.go
Labels: API, Electra

#14554 Rollback Block During Processing
  CHANGELOG.md
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
Labels: Ready For Review

#14586 keymanager API: bug fixes and inconsistencies
  CHANGELOG.md
  validator/rpc/BUILD.bazel
  validator/rpc/handlers_keymanager.go
  validator/rpc/handlers_keymanager_test.go
  validator/rpc/intercepter.go
  validator/rpc/intercepter_test.go
Labels: Bug, API, Keymanager-API

#14405 small improvements to logs
  CHANGELOG.md
  config/proposer/loader/loader.go
  validator/client/validator.go
Labels: Cleanup, UX

#14592 Use Read Only Head State When Computing Active Indices
  CHANGELOG.md
  beacon-chain/blockchain/chain_info.go
Labels: Ready For Review

#14578 eip7251: Bugfix and more withdrawal tests
  CHANGELOG.md
  beacon-chain/core/blocks/withdrawals.go
  beacon-chain/state/state-native/getters_withdrawal.go
  beacon-chain/state/state-native/getters_withdrawal_test.go
Labels: Ready For Review, Electra

#14580 Electra: exclude empty requests in requests list
  CHANGELOG.md
  beacon-chain/execution/engine_client_test.go
  proto/engine/v1/electra.go
  proto/engine/v1/electra_test.go
Labels: Ready For Review, Electra
