Repository OffchainLabs/prysm, pull requests merged in 2024-02, with the labels that each got.

#13568 handle slice out of range
  validator/rpc/intercepter.go
  validator/rpc/intercepter_test.go
Labels: Bug, API

#13571 Revise blob sidecar not found log
  beacon-chain/sync/rpc_blob_sidecars_by_root.go
Labels: Ready For Review

#13575 Return consensus block value in Wei
  beacon-chain/rpc/eth/rewards/service.go
  beacon-chain/rpc/eth/validator/handlers_block.go
  beacon-chain/rpc/eth/validator/handlers_block_test.go
Labels: Bug, Ready For Review, API

#13574 Fix Slashing Gossip Checks
  beacon-chain/sync/validate_attester_slashing.go
  beacon-chain/sync/validate_attester_slashing_test.go
  beacon-chain/sync/validate_proposer_slashing.go
  beacon-chain/sync/validate_proposer_slashing_test.go
Labels: Ready For Review

#13581 Do Not Cache For Non Active Public Keys
  beacon-chain/state/stategen/service.go
Labels: Ready For Review

#13561 Rename block by range request log
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
Labels: Ready For Review

#13582 Enhance EL block height log
  beacon-chain/execution/service.go
Labels: Ready For Review

#13579 Get the right head state when proposing a failed reorg
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Bug

#13580 Add Sync Checker
  beacon-chain/blockchain/chain_info.go
  beacon-chain/blockchain/chain_info_test.go
  beacon-chain/blockchain/options.go
  beacon-chain/blockchain/service.go
  beacon-chain/blockchain/setup_test.go
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/node/node.go
  beacon-chain/node/node_test.go
  beacon-chain/sync/initial-sync/service.go
  testing/spectest/shared/common/forkchoice/service.go
Labels: Ready For Review

#13585 Beacon API: get blob fix retention cases
  beacon-chain/rpc/eth/blob/BUILD.bazel
  beacon-chain/rpc/eth/blob/handlers_test.go
  beacon-chain/rpc/lookup/blocker.go
  beacon-chain/rpc/lookup/blocker_test.go
  beacon-chain/rpc/service.go
Labels: Bug, API, Deneb

#13514 Add `/eth/v1/beacon/deposit_snapshot` endpoint
  api/server/structs/BUILD.bazel
  api/server/structs/conversions.go
  api/server/structs/conversions_test.go
  api/server/structs/endpoints_beacon.go
  beacon-chain/rpc/eth/beacon/BUILD.bazel
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/generated.ssz.go
  proto/prysm/v1alpha1/powchain.pb.go
  proto/prysm/v1alpha1/powchain.proto
Labels: API

#13573 Improve vc logs
  validator/accounts/accounts_delete.go
  validator/accounts/accounts_exit.go
  validator/accounts/testing/mock.go
  validator/client/aggregate.go
  validator/client/attest.go
  validator/client/iface/validator.go
  validator/client/log.go
  validator/client/metrics.go
  validator/client/propose.go
  validator/client/propose_protect.go
  validator/client/propose_test.go
  validator/client/runner.go
  validator/client/service.go
  validator/client/testutil/mock_validator.go
  validator/client/validator.go
  validator/client/validator_test.go
  validator/db/kv/attester_protection.go
  validator/keymanager/local/import.go
  validator/keymanager/remote-web3signer/internal/log.go
  validator/node/node.go
  validator/rpc/server.go
  validator/web/log.go
Labels: v5

#13597 Handle Syncing Executon Client
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
Labels: Ready For Review

#13536 Remove deprecated late reorg flag
  config/features/deprecated_flags.go
Labels: Breaking Changes

#13537 Remove disable vectorized htr flag
  config/features/deprecated_flags.go
Labels: Breaking Changes

#13538 Remove deprecated aggregate parallel flag
  config/features/deprecated_flags.go
Labels: Breaking Changes

#13539 Remove deprecated build block parallel flag
  config/features/deprecated_flags.go
Labels: Breaking Changes

#13587 Validate Range Availibility
  beacon-chain/node/node.go
  beacon-chain/p2p/types/rpc_errors.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/options.go
  beacon-chain/sync/rpc_beacon_blocks_by_range.go
  beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
  beacon-chain/sync/service.go
Labels: Ready For Review, Networking

#13606 Remove deprecated flags: gossip batch registration and registration cache
  config/features/deprecated_flags.go
Labels: Ready For Review, Breaking Changes

#13608 Use Gwei for value in get header log
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
Labels: Ready For Review

#13611 Clean Up Deposit Processing Logs
  beacon-chain/execution/log_processing.go
Labels: Ready For Review, v5

#13615 Rm unused import
  proto/eth/v1/events.proto
  proto/eth/v2/beacon_lightclient.proto
Labels: Ready For Review

#13619 Remove /eth/v1/debug/beacon/states/{state_id}
  beacon-chain/rpc/eth/debug/handlers.go
  beacon-chain/rpc/eth/debug/handlers_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
Labels: Ready For Review, API, Cleanup, v5

#13600 Remove deprecated items
  INTEROP.md
  beacon-chain/rpc/eth/config/handlers_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/beacon/attestations.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/attestations_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_stream.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/validators_stream_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/duties.go
  beacon-chain/rpc/prysm/v1alpha1/validator/duties_test.go
  cmd/prysmctl/BUILD.bazel
  cmd/prysmctl/deprecated/BUILD.bazel
  cmd/prysmctl/deprecated/checkpoint/BUILD.bazel
  cmd/prysmctl/deprecated/checkpoint/checkpoint.go
  cmd/prysmctl/deprecated/checkpoint/latest.go
  cmd/prysmctl/deprecated/checkpoint/save.go
  cmd/prysmctl/deprecated/cmd.go
  cmd/prysmctl/main.go
  config/params/config.go
  config/params/configset_test.go
  config/params/loader_test.go
  config/params/testnet_config_test.go
  hack/update-mockgen.sh
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/beacon_chain.pb.go
  proto/prysm/v1alpha1/beacon_chain.pb.gw.go
  proto/prysm/v1alpha1/beacon_chain.proto
  proto/prysm/v1alpha1/debug.pb.go
  proto/prysm/v1alpha1/debug.pb.gw.go
  proto/prysm/v1alpha1/debug.proto
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.pb.gw.go
  proto/prysm/v1alpha1/validator.proto
  testing/endtoend/evaluators/slashing_helper.go
  testing/mock/BUILD.bazel
  testing/mock/beacon_chain_service_mock.go
  testing/mock/beacon_service_mock.go
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
  validator/client/beacon-api/duties.go
  validator/client/beacon-api/duties_test.go
Labels: Cleanup, v5

#13621 Reorganize Prysm custom endpoints
  beacon-chain/rpc/prysm/beacon/BUILD.bazel
  beacon-chain/rpc/prysm/beacon/server.go
  beacon-chain/rpc/prysm/beacon/validator_count.go
  beacon-chain/rpc/prysm/beacon/validator_count_test.go
  beacon-chain/rpc/prysm/validator/BUILD.bazel
  beacon-chain/rpc/prysm/validator/server.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
Labels: Ready For Review, API, Cleanup, v5

#13607 Update aggregate atts t1 bucket values
  beacon-chain/operations/attestations/metrics.go
Labels: Ready For Review

#13624 Remove safe slots to import flag
  cmd/beacon-chain/flags/base.go
Labels: Ready For Review, Breaking Changes

#13618 removing show deposit data flag
  cmd/validator/accounts/accounts.go
  cmd/validator/accounts/list.go
  cmd/validator/flags/flags.go
  validator/accounts/accounts_list.go
  validator/accounts/accounts_list_test.go
  validator/accounts/cli_manager.go
  validator/accounts/cli_options.go
  validator/keymanager/local/keymanager.go
  validator/keymanager/types.go
Labels: Cleanup

#13616 Blob API - invalid indicies should error instead of ignored
  beacon-chain/rpc/eth/blob/handlers.go
  beacon-chain/rpc/eth/blob/handlers_test.go
Labels: Bug, Priority: Low, UX, Deneb

#13502 add BlockBatchLimit comment: Maximum 128
  cmd/beacon-chain/flags/base.go
Labels: Cleanup

#13626 Check deneb fork transition test folder is empty
  testing/spectest/shared/deneb/fork/transition.go
Labels: Ready For Review

#13627 Remove leftover log
  validator/client/beacon-api/submit_aggregate_selection_proof.go
Labels: v5

#13628 Remove /eth/v1/beacon/blocks/{block_id}
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  beacon-chain/rpc/service.go
  beacon-chain/rpc/service_test.go
Labels: Ready For Review, API, Cleanup, v5

#13636 Some clean ups on the sync package
  beacon-chain/sync/backfill/verify_test.go
  beacon-chain/sync/block_batcher.go
  beacon-chain/sync/initial-sync/verification.go
  beacon-chain/sync/verify/blob_test.go
Labels: Ready For Review

#13644 Normalize filesystem/blob logs
  beacon-chain/db/filesystem/BUILD.bazel
  beacon-chain/db/filesystem/blob.go
  beacon-chain/db/filesystem/log.go
  beacon-chain/db/filesystem/pruner.go
Labels: Ready For Review, Cleanup

#13638 Remove unused bolt buckets
  beacon-chain/db/kv/kv.go
  beacon-chain/db/kv/schema.go
Labels: Ready For Review

#13649 Fix blob batch verifier pointer receiver
  beacon-chain/sync/backfill/blobs.go
Labels: Ready For Review

#13637 Do not Persist Startup State
  beacon-chain/blockchain/service.go
  beacon-chain/execution/service.go
  beacon-chain/node/node.go
Labels: Ready For Review

#13642 Normalize backfill logs/errors
  beacon-chain/sync/backfill/BUILD.bazel
  beacon-chain/sync/backfill/batch.go
  beacon-chain/sync/backfill/log.go
  beacon-chain/sync/backfill/pool.go
  beacon-chain/sync/backfill/service.go
  beacon-chain/sync/backfill/status.go
  beacon-chain/sync/backfill/worker.go
  cmd/beacon-chain/sync/backfill/flags/flags.go
Labels: Ready For Review, Cleanup, backfill

#13654 Unify log fields
  api/client/beacon/checkpoint.go
  api/client/beacon/client.go
  api/client/builder/client.go
  beacon-chain/blockchain/service.go
  beacon-chain/cache/depositcache/deposits_cache.go
  beacon-chain/cache/depositsnapshot/deposit_inserter.go
  beacon-chain/execution/log_processing.go
  beacon-chain/execution/service.go
  beacon-chain/monitor/process_attestation.go
  beacon-chain/monitor/process_attestation_test.go
  beacon-chain/monitor/process_block.go
  beacon-chain/monitor/process_block_test.go
  beacon-chain/monitor/process_exit.go
  beacon-chain/monitor/process_exit_test.go
  beacon-chain/monitor/process_sync_committee.go
  beacon-chain/monitor/process_sync_committee_test.go
  beacon-chain/monitor/service.go
  beacon-chain/monitor/service_test.go
  beacon-chain/node/config.go
  beacon-chain/node/node.go
  beacon-chain/operations/attestations/prepare_forkchoice.go
  beacon-chain/rpc/lookup/blocker.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/prysm/v1alpha1/validator/status.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/pending_blocks_queue.go
  beacon-chain/sync/rate_limiter.go
  beacon-chain/sync/rpc.go
  beacon-chain/sync/rpc_goodbye.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber.go
  beacon-chain/verification/blob.go
  beacon-chain/verification/cache.go
  cmd/prysmctl/validator/withdraw.go
  runtime/logging/blob.go
  testing/endtoend/components/beacon_node.go
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/evaluators/fee_recipient.go
  tools/forkchecker/forkchecker.go
  validator/accounts/accounts_backup.go
  validator/accounts/wallet/wallet.go
  validator/accounts/wallet_create.go
  validator/accounts/wallet_recover.go
  validator/node/node.go
Labels: Ready For Review, Cleanup

#13657 Do Not Compute Block Root Again
  beacon-chain/core/blocks/signature.go
  beacon-chain/core/blocks/signature_test.go
  beacon-chain/sync/validate_beacon_blocks.go
Labels: Ready For Review

#13660 Optimize Adding Dirty Indices
  beacon-chain/state/state-native/setters_misc.go
  beacon-chain/state/state-native/state_test.go
  container/slice/slice.go
Labels: Ready For Review

#13656 Use a Validator Reader When Computing Unrealized Balances
  beacon-chain/state/state-native/getters_participation.go
  beacon-chain/state/stateutil/BUILD.bazel
  beacon-chain/state/stateutil/unrealized_justification.go
  beacon-chain/state/stateutil/unrealized_justification_test.go
  beacon-chain/state/stateutil/validator_reader.go
Labels: Ready For Review

#13662 Do not log zero sync committee messages
  validator/client/log.go
Labels: Ready For Review, Cleanup, Validator Client

#13666 small cleanup on functions: use slots.PrevSlot
  beacon-chain/blockchain/head_test.go
  beacon-chain/core/transition/BUILD.bazel
  beacon-chain/core/transition/altair_transition_no_verify_sig_test.go
  beacon-chain/core/transition/bellatrix_transition_no_verify_sig_test.go
  beacon-chain/rpc/eth/builder/handlers.go
  beacon-chain/rpc/eth/rewards/service.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_altair.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/sync/validate_sync_committee_message_test.go
  testing/util/helpers_test.go
Labels: Cleanup

#13675 bazel: Update aspect-build/bazel-lib to v2.5.0
  WORKSPACE
Labels: CI, Priority: High, dependencies

#13640 Employ Dynamic Cache Sizes
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/cache/committee.go
  beacon-chain/cache/committee_disabled.go
  beacon-chain/core/helpers/beacon_committee.go
Labels: Ready For Review

#13676 move setting route handlers to registration from start
  beacon-chain/gateway/helpers.go
  beacon-chain/node/node.go
  beacon-chain/rpc/service.go
Labels: Bug, API

#13671 Downgrade Level DB to Stable Version
  beacon-chain/blockchain/pow_block_test.go
  deps.bzl
  go.mod
  go.sum
  third_party/com_github_datadog_zstd.patch
Labels: Ready For Review, dependencies

#13679 Fix failed reorg log
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Labels: Bug
