Repository OffchainLabs/prysm, pull requests merged in 2025-02, with the labels that each got.

#14853 Fix monitor service for Electra
  beacon-chain/monitor/process_attestation.go
  changelog/radek_electra-monitor.md
Labels: Electra

#14855 Update Beacon API events to Electra
  api/server/structs/conversions.go
  beacon-chain/core/feed/operation/events.go
  beacon-chain/monitor/service.go
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/events/events.go
  beacon-chain/rpc/eth/events/events_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_beacon_attestation.go
  changelog/radek_electra-events-api.md
  testing/util/attestation.go
Labels: API, Electra

#14868 improving proposer settings loader readability
  changelog/james-prysm_proposer-settings-readability.md
  config/proposer/loader/loader.go
Labels: Cleanup, UX, Validator Client

#14871 Reduce size of api/client import graph
  api/client/beacon/BUILD.bazel
  api/client/beacon/checkpoint.go
  api/client/beacon/client.go
  api/client/beacon/client_test.go
  beacon-chain/sync/checkpoint/BUILD.bazel
  beacon-chain/sync/checkpoint/api.go
  beacon-chain/sync/checkpoint/api_test.go
  beacon-chain/sync/checkpoint/weak-subjectivity.go
  beacon-chain/sync/checkpoint/weak-subjectivity_test.go
  changelog/kasey_refactor-checkpoint-download.md
  cmd/prysmctl/checkpointsync/BUILD.bazel
  cmd/prysmctl/checkpointsync/download.go
  cmd/prysmctl/weaksubjectivity/BUILD.bazel
  cmd/prysmctl/weaksubjectivity/checkpoint.go
  go.mod
  network/forks/ordered.go
Labels: API, Cleanup

#14883 Set New Blob Limits For Electra
  beacon-chain/core/electra/churn_test.go
  beacon-chain/db/kv/blocks_test.go
  beacon-chain/sync/rpc_blob_sidecars_by_range.go
  beacon-chain/sync/sync_test.go
  changelog/nisdas_increase_electra_limits.md
  cmd/beacon-chain/flags/base.go
Labels: Networking, Electra

#14862 Notify about attestations from the pending att queue
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  changelog/radek_pending-att-queue-notification.md
Labels: API, Electra

#14829 Prune pending deposits from the deposit cache post-Electra
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/cache/depositsnapshot/BUILD.bazel
  beacon-chain/cache/depositsnapshot/deposit_cache_test.go
  beacon-chain/cache/depositsnapshot/deposit_fetcher.go
  beacon-chain/cache/depositsnapshot/deposit_fetcher_test.go
  beacon-chain/cache/depositsnapshot/deposit_pruner.go
  beacon-chain/cache/depositsnapshot/deposit_pruner_test.go
  beacon-chain/cache/interfaces.go
  changelog/syjn99_prune-deposit-cache.md
Labels: Electra

#14890 Update Pubsub Dependency to v0.13.0
  changelog/nisdas_update_go_libp2p_pubsub.md
  deps.bzl
  go.mod
  go.sum
Labels: dependencies

#14895 Fix electra state to safe share references on pending fields when append
  beacon-chain/state/state-native/setters_churn.go
  beacon-chain/state/state-native/setters_consolidation.go
  beacon-chain/state/state-native/setters_consolidation_test.go
  beacon-chain/state/state-native/setters_deposit_requests.go
  beacon-chain/state/state-native/setters_deposits.go
  beacon-chain/state/state-native/setters_deposits_test.go
  beacon-chain/state/state-native/setters_withdrawal.go
  beacon-chain/state/state-native/setters_withdrawal_test.go
  beacon-chain/state/state-native/state_trie.go
  changelog/tt_fix_electra_state.md
Labels: Electra

#14903 Add missing config values from the spec
  beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
  beacon-chain/rpc/eth/config/handlers_test.go
  changelog/radek_add-missing-config-values.md
  config/params/config.go
  config/params/loader_test.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
Labels: API

#14897 fix: /eth/v2/beacon/blocks post api to handle electra and fulu blocks correctly
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  changelog/james-prysm_fix-block-api-electra.md
Labels: Bug, API, Electra

#14911 Dynamic max blobs config
  changelog/james-prysm_dynamic-max-blobs.md
  config/params/config.go
Labels: Electra

#14904 Rename files in `beacon-chain/operations/slashings`
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/pool.go
  beacon-chain/operations/slashings/service.go
  beacon-chain/operations/slashings/service_new.go
  changelog/radek_rename-slashing-files.md
Labels: Cleanup

#14913 fix: gocognit on publish block and fixing publish blinded block header check
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  changelog/james-prysm_blockv2-cognit.md
Labels: Bug, API, Cleanup, Builder, Electra

#14924 Fix Engine Capabilites Check
  beacon-chain/execution/engine_client.go
  changelog/nisdas_fix_capabilites.md
  config/params/config.go
Labels: Electra

#14921 Update Blst to v3.14.0
  changelog/nisdas_update_blst.md
  deps.bzl
  go.mod
  go.sum
Labels: dependencies

#14933 Fix Deposit Evaluator in E2E
  changelog/nisdas_fix_process_deposit_evaluator.md
  testing/endtoend/evaluators/operations.go
Labels: E2E Tests, Electra

#14938 Fix Deposit Activation Evaluator
  changelog/nisdas_fix_deposit_active_evaluator.md
  testing/endtoend/evaluators/operations.go
Labels: E2E Tests

#14936 web3signer electra for e2e
  changelog/james-prysm_web3signer-electra-e2e.md
  config/params/loader.go
  testing/endtoend/deps.bzl
  testing/endtoend/minimal_builder_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
Labels: E2E Tests, Web3Signer, Electra

#14946 Add in Multiclient E2E For Electra
  changelog/nisdas_enable_multiclient_e2e_electra.md
  testing/endtoend/components/lighthouse_beacon.go
  testing/endtoend/deps.bzl
  testing/endtoend/endtoend_test.go
  testing/endtoend/evaluators/beaconapi/requests.go
  testing/endtoend/evaluators/beaconapi/verify.go
  testing/endtoend/evaluators/execution_engine.go
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
Labels: E2E Tests, Electra

#14925 Don't use MaxCover for Electra on-chain aggregates
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go
  changelog/radek_no-maxcover-for-electra.md
Labels: Bug, Electra

#14941 Add get pending deposits endpoint
  api/server/structs/endpoints_beacon.go
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/endpoints_test.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  changelog/saolyn_add-GetPendingDeposits.md
Labels: API

#14956 Log Execution Requests In a Block
  beacon-chain/blockchain/log.go
  changelog/nisdas_log_execution_requests.md
Labels: Electra

#14949 Add get pending partial withdrawals
  api/server/structs/endpoints_beacon.go
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/endpoints_test.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  changelog/saolyn_add-GetPendingPartialWithdrawals.md
Labels: API

#14961 builder: api calls should have appropriate headers
  api/client/builder/BUILD.bazel
  api/client/builder/client.go
  api/client/builder/client_test.go
  changelog/james-prysm_fix-builder-post-header.md
Labels: Bug, API, Builder

#14962 improving the error messages for execution request deserialization
  changelog/james-prysm_improve-execution-request-errors.md
  proto/engine/v1/electra.go
  proto/engine/v1/electra_test.go
Labels: UX, Electra

#14964 Test Execution Deposit Requests in E2E
  changelog/nisdas_add_deposit_request_testing.md
  runtime/interop/genesis.go
  testing/endtoend/component_handler_test.go
  testing/endtoend/components/eth1/depositor.go
  testing/endtoend/components/eth1/transactions.go
  testing/endtoend/endtoend_test.go
  testing/endtoend/params/params.go
  testing/endtoend/types/types.go
Labels: E2E Tests, Electra

#14985 Fix Gossip Validation of Electra Attester Slashings
  beacon-chain/p2p/types/object_mapping.go
  beacon-chain/p2p/types/object_mapping_test.go
  beacon-chain/sync/decode_pubsub.go
  beacon-chain/sync/decode_pubsub_test.go
  changelog/nisdas_fix_attester_slashing_validation.md
Labels: Priority: Critical, Electra

#14993 add log for committee index on electra attesation
  changelog/james-prysm_committee-index-log.md
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/attestation.go
  proto/prysm/v1alpha1/log.go
Labels: Electra
