Repository OffchainLabs/prysm, pull requests merged in 2025-08, with the labels that each got.

#15558 Optimize validator assignment lookups with hybrid O(1) approach for large requests
  beacon-chain/rpc/prysm/v1alpha1/validator/duties_v2.go
  beacon-chain/rpc/prysm/v1alpha1/validator/duties_v2_test.go
  changelog/tt_opt-val-lookup.md
Labels: api, optimization

#15553 Add Fulu case for saveStatesEfficientInternal
  beacon-chain/db/kv/state.go
  changelog/syjn99_save-state-efficient-fulu.md
Labels: fulu

#15554 Persist metadata sequence number using Beacon DB
  beacon-chain/db/alias.go
  beacon-chain/db/iface/interface.go
  beacon-chain/db/kv/BUILD.bazel
  beacon-chain/db/kv/error.go
  beacon-chain/db/kv/p2p.go
  beacon-chain/db/kv/p2p_test.go
  beacon-chain/db/kv/schema.go
  beacon-chain/node/node.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/pubsub_filter_test.go
  beacon-chain/p2p/pubsub_test.go
  beacon-chain/p2p/service.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/p2p/utils.go
  beacon-chain/p2p/utils_test.go
  changelog/syjn99_persist-p2p-seqnum.md
  cmd/beacon-chain/main.go
  cmd/beacon-chain/usage.go
  cmd/flags.go
  config/features/deprecated_flags.go
Labels: networking, fulu, bug-fix

#15548 Fix validateConsensus
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_test.go
  changelog/potuz_fix_stater.md
Labels: api, bug-fix

#15568 fixing builder version check
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  changelog/james-prysm_fix-builder-version-check.md
Labels: api, builder, bug-fix

#15571 Don't submit duplicate `SignedContributionAndProof` messages
  changelog/radek_duplicate-sync-aggregate.md
  validator/client/sync_committee.go
  validator/client/sync_committee_test.go
Labels: api, bug-fix

#15559 Update endpoint to return 404 after isOptimistic check
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/eth/beacon/handlers_state.go
  beacon-chain/rpc/eth/beacon/handlers_validator.go
  beacon-chain/rpc/eth/debug/handlers.go
  beacon-chain/rpc/eth/helpers/BUILD.bazel
  beacon-chain/rpc/eth/helpers/error_handling.go
  beacon-chain/rpc/eth/helpers/sync.go
  beacon-chain/rpc/eth/helpers/sync_test.go
  beacon-chain/rpc/lookup/blocker.go
  beacon-chain/rpc/lookup/stater.go
  beacon-chain/rpc/prysm/beacon/validator_count.go
  beacon-chain/rpc/testutil/mock_stater.go
  changelog/muzry_update_not_found_status.md
Labels: api, bug-fix

#15557 Omit non blob fields
  changelog/kasey_omit-non-blob-fields.md
  config/params/config.go
Labels: peer-das, fulu, bug-fix

#15606 FIx initialization issue in rpc handlers
  beacon-chain/node/node.go
  beacon-chain/rpc/service.go
  changelog/kasey_fix-cache-panic.md
Labels: bug-fix

#15629 PeerDAS: Add various missing items
  beacon-chain/node/node.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
  beacon-chain/rpc/prysm/v1alpha1/validator/construct_generic_block_test.go
  changelog/manu-peerdas-various.md
  cmd/beacon-chain/main.go
  cmd/beacon-chain/storage/options_test.go
  cmd/beacon-chain/usage.go
Labels: peer-das

#15593 `FetchDataColumnSidecars`: If possible, try to reconstruct after retrieving sidecars from peers if not some are still missing.
  beacon-chain/sync/data_column_sidecars.go
  beacon-chain/sync/data_column_sidecars_test.go
  changelog/manu-peerdas-reconstruct.md
Labels: peer-das

#15634 Retry fetch origin data column sidecars.
  beacon-chain/p2p/custody.go
  beacon-chain/p2p/custody_test.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/data_column_sidecars.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/rpc_send_request.go
  changelog/manu-retry-fetch-origin-columns.md
Labels: peer-das

#15642 Fix next epoch proposer duties
  beacon-chain/core/helpers/beacon_committee.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/helpers/validators_test.go
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/eth/validator/handlers_test.go
  changelog/potuz_next_epoch_proposer_duties.md
  testing/spectest/shared/fulu/sanity/block_processing.go
Labels: api, fulu, bug-fix
