Repository OffchainLabs/prysm, pull requests merged in 2025-01, with the labels that each got.

#14762 Remove slashingMultiplier argument from ProcessSlashings
  CHANGELOG.md
  beacon-chain/core/altair/epoch_spec_test.go
  beacon-chain/core/altair/transition.go
  beacon-chain/core/electra/transition.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/epoch/epoch_processing_test.go
  testing/spectest/shared/altair/epoch_processing/BUILD.bazel
  testing/spectest/shared/altair/epoch_processing/slashings.go
  testing/spectest/shared/bellatrix/epoch_processing/BUILD.bazel
  testing/spectest/shared/bellatrix/epoch_processing/slashings.go
  testing/spectest/shared/capella/epoch_processing/BUILD.bazel
  testing/spectest/shared/capella/epoch_processing/slashings.go
  testing/spectest/shared/deneb/epoch_processing/BUILD.bazel
  testing/spectest/shared/deneb/epoch_processing/slashings.go
  testing/spectest/shared/electra/epoch_processing/BUILD.bazel
  testing/spectest/shared/electra/epoch_processing/slashings.go
  testing/spectest/shared/phase0/epoch_processing/BUILD.bazel
  testing/spectest/shared/phase0/epoch_processing/slashings.go
Labels: Cleanup

#14765 Remove v2 protos
  CHANGELOG.md
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  proto/eth/v2/BUILD.bazel
  proto/eth/v2/beacon_block.pb.go
  proto/eth/v2/beacon_block.proto
  proto/eth/v2/beacon_lightclient.pb.go
  proto/eth/v2/beacon_lightclient.proto
  proto/eth/v2/custom.go
  proto/eth/v2/grpc.ssz.go
  proto/eth/v2/ssz.pb.go
  proto/eth/v2/ssz.proto
  proto/eth/v2/sync_committee.pb.go
  proto/eth/v2/sync_committee.proto
  proto/eth/v2/validator.pb.go
  proto/eth/v2/validator.proto
  proto/eth/v2/version.pb.go
  proto/eth/v2/version.proto
  proto/eth/v2/withdrawals.pb.go
  proto/eth/v2/withdrawals.proto
  proto/migration/BUILD.bazel
  proto/migration/v1alpha1_to_v2.go
  testing/util/BUILD.bazel
  testing/util/block.go
  testing/util/block_test.go
  testing/util/merge.go
Labels: Ready For Review, Cleanup

#14770 Update Go-Libp2p-Pubsub
  CHANGELOG.md
  deps.bzl
  go.mod
  go.sum
Labels: Ready For Review

#14772 Remove duplicate imports
  api/client/builder/client_test.go
  beacon-chain/core/electra/deposits.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder_test.go
  beacon-chain/state/state-native/setters_eth1_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
  testing/util/lightclient.go
  validator/rpc/handlers_health_test.go
Labels: Cleanup

#14761 Simplify next Fork boilerplate creation.
  CHANGELOG.md
  api/server/structs/block.go
  api/server/structs/conversions_block.go
  api/server/structs/conversions_lightclient.go
  api/server/structs/conversions_state.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/core/blocks/genesis.go
  beacon-chain/core/blocks/withdrawals_test.go
  beacon-chain/core/electra/upgrade.go
  beacon-chain/core/electra/upgrade_test.go
  beacon-chain/core/light-client/lightclient_test.go
  beacon-chain/core/time/slot_epoch_test.go
  beacon-chain/core/transition/transition.go
  beacon-chain/core/validators/slashing.go
  beacon-chain/db/kv/lightclient_test.go
  beacon-chain/db/kv/state_test.go
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/payload_body_test.go
  beacon-chain/operations/attestations/kv/aggregated.go
  beacon-chain/operations/attestations/kv/unaggregated.go
  beacon-chain/p2p/types/object_mapping.go
  beacon-chain/rpc/eth/light-client/handlers_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/construct_generic_block.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  beacon-chain/state/state-native/getters_payload_header.go
  beacon-chain/state/state-native/setters_payload_header_test.go
  beacon-chain/state/state-native/spec_parameters.go
  beacon-chain/state/state-native/state_trie.go
  beacon-chain/sync/rpc.go
  consensus-types/blocks/execution.go
  consensus-types/blocks/factory.go
  consensus-types/blocks/getters.go
  consensus-types/blocks/getters_test.go
  consensus-types/blocks/proto.go
  encoding/ssz/detect/configfork_test.go
  proto/engine/v1/electra.go
  proto/prysm/v1alpha1/beacon_block.go
  proto/prysm/v1alpha1/beacon_state.proto
  runtime/interop/BUILD.bazel
  runtime/interop/premine-state.go
  testing/spectest/shared/common/forkchoice/runner.go
  testing/spectest/shared/electra/operations/withdrawals.go
  testing/spectest/shared/electra/ssz_static/ssz_static.go
  testing/util/block.go
  testing/util/electra.go
  testing/util/electra_block.go
  testing/util/electra_state.go
  testing/util/merge.go
  testing/util/state.go
Labels: Cleanup

#14777 Security Update For Dependencies
  CHANGELOG.md
  deps.bzl
  go.mod
  go.sum
Labels: Security, dependencies

#14778 Add Ability to Trace IDONTWANT Control Messages
  CHANGELOG.md
  beacon-chain/p2p/pubsub_tracer.go
Labels: Networking

#14776 Close Streams For Metadata Requests Better
  CHANGELOG.md
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/rpc_metadata.go
  beacon-chain/sync/rpc_metadata_test.go
Labels: Networking

#14780 Update x/net to v0.33.0
  CHANGELOG.md
  deps.bzl
  go.mod
  go.sum
Labels: Security, dependencies

#14659 Separate type for unaggregated network attestations
  CHANGELOG.md
  api/server/structs/conversions.go
  api/server/structs/other.go
  beacon-chain/core/helpers/attestation.go
  beacon-chain/core/helpers/attestation_test.go
  beacon-chain/core/helpers/beacon_committee_test.go
  beacon-chain/p2p/gossip_topic_mappings.go
  beacon-chain/p2p/gossip_topic_mappings_test.go
  beacon-chain/p2p/types/object_mapping.go
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/eth/beacon/handlers_pool.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  beacon-chain/rpc/eth/beacon/server.go
  beacon-chain/rpc/eth/validator/handlers.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/server.go
  beacon-chain/rpc/service.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/decode_pubsub_test.go
  beacon-chain/sync/pending_attestations_queue.go
  beacon-chain/sync/pending_attestations_queue_test.go
  beacon-chain/sync/subscriber_beacon_attestation.go
  beacon-chain/sync/validate_aggregate_proof.go
  beacon-chain/sync/validate_aggregate_proof_test.go
  beacon-chain/sync/validate_beacon_attestation.go
  beacon-chain/sync/validate_beacon_attestation_electra.go
  beacon-chain/sync/validate_beacon_attestation_electra_test.go
  beacon-chain/sync/validate_beacon_attestation_test.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/attestation.go
  proto/prysm/v1alpha1/attestation.pb.go
  proto/prysm/v1alpha1/attestation.proto
  proto/prysm/v1alpha1/electra.ssz.go
  proto/prysm/v1alpha1/validator.pb.go
  proto/prysm/v1alpha1/validator.proto
  testing/mock/beacon_service_mock.go
  testing/mock/beacon_validator_client_mock.go
  testing/mock/beacon_validator_server_mock.go
  testing/validator-mock/validator_client_mock.go
  validator/client/attest.go
  validator/client/attest_test.go
  validator/client/beacon-api/BUILD.bazel
  validator/client/beacon-api/beacon_api_validator_client.go
  validator/client/beacon-api/beacon_block_json_helpers.go
  validator/client/beacon-api/mock/json_rest_handler_mock.go
  validator/client/beacon-api/propose_attestation.go
  validator/client/beacon-api/propose_attestation_test.go
  validator/client/grpc-api/grpc_validator_client.go
  validator/client/iface/validator_client.go
Labels: >1 Approves Required, Electra

#14351 goethereum dependency to v1.14~
  CHANGELOG.md
  beacon-chain/blockchain/kzg/validation.go
  beacon-chain/blockchain/kzg/validation_test.go
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/block_reader_test.go
  beacon-chain/execution/log_processing_test.go
  beacon-chain/execution/service_test.go
  beacon-chain/execution/testing/BUILD.bazel
  beacon-chain/execution/testing/mock_execution_chain.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/config.go
  beacon-chain/p2p/discovery.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/fork_test.go
  beacon-chain/p2p/service_test.go
  beacon-chain/p2p/subnets_test.go
  beacon-chain/rpc/eth/beacon/handlers.go
  beacon-chain/rpc/prysm/v1alpha1/debug/server.go
  cmd/beacon-chain/main.go
  cmd/prysmctl/testnet/generate_genesis.go
  contracts/deposit/contract_test.go
  contracts/deposit/mock/BUILD.bazel
  contracts/deposit/mock/mock.go
  deps.bzl
  go.mod
  go.sum
  nogo_config.json
  runtime/debug/BUILD.bazel
  runtime/debug/debug.go
  runtime/interop/genesis.go
  runtime/interop/premine-state.go
  testing/endtoend/components/eth1/BUILD.bazel
  testing/endtoend/components/eth1/miner.go
  testing/endtoend/components/eth1/node.go
  testing/endtoend/components/eth1/transactions.go
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/evaluators/builder.go
  testing/endtoend/geth_deps.go
  testing/endtoend/mainnet_e2e_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/minimal_builder_e2e_test.go
  testing/endtoend/minimal_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
  testing/middleware/builder/builder.go
  third_party/com_github_karalabe_hid.patch
  third_party/hid/AUTHORS
  third_party/hid/BUILD.bazel
  third_party/hid/LICENSE
  third_party/hid/README.md
  third_party/hid/hid_disabled.go
  third_party/hid/raw_disabled.go
  third_party/hid/usb.go
  third_party/hid/usb_disabled.go
  third_party/hid/usb_test.go
  time/slots/slottime.go
  tools/bootnode/bootnode.go
  tools/bootnode/bootnode_test.go
Labels: Breaking Changes

#14798 fix e2e scenario evaluators
  changelog/james-prysm_e2e-scenario-fork-fix.md
  testing/endtoend/endtoend_setup_test.go
  testing/endtoend/mainnet_scenario_e2e_test.go
  testing/endtoend/minimal_scenario_e2e_test.go
Labels: Bug, E2E Tests

#14477 Remote Signer: Electra
  changelog/james-prysm_remote-signer-electra.md
  testing/endtoend/deps.bzl
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/keymanager_test.go
  validator/keymanager/remote-web3signer/metrics.go
  validator/keymanager/remote-web3signer/types/BUILD.bazel
  validator/keymanager/remote-web3signer/types/custom_mappers.go
  validator/keymanager/remote-web3signer/types/custom_mappers_test.go
  validator/keymanager/remote-web3signer/types/mock/BUILD.bazel
  validator/keymanager/remote-web3signer/types/mock/mocks.go
  validator/keymanager/remote-web3signer/types/requests.go
  validator/keymanager/remote-web3signer/types/requests_test.go
  validator/keymanager/remote-web3signer/types/web3signer_types.go
Labels: Web3Signer, Electra

#14816 Add Electra test case to rewards API
  beacon-chain/rpc/eth/rewards/BUILD.bazel
  beacon-chain/rpc/eth/rewards/handlers_test.go
  changelog/radek_rewards-electra.md
Labels: API, Electra

#14817 Update `proto_test.go` to Electra
  changelog/radek_proto_test-electra.md
  consensus-types/blocks/BUILD.bazel
  consensus-types/blocks/proto_test.go
Labels: Electra

#14821 `UpgradeToFulu`: Respect the specification.
  beacon-chain/core/fulu/BUILD.bazel
  beacon-chain/core/fulu/upgrade.go
  beacon-chain/core/fulu/upgrade_test.go
  changelog/manu_fulu_fork.md
Labels: Fulu

#14822 `nodeFilter`: Add `GossipBlobSidecarMessage` case.
  beacon-chain/p2p/subnets.go
  changelog/manu_blob_subnets_node_filter.md
Labels: Blobspace

#14344 Builder: Electra
  api/client/builder/BUILD.bazel
  api/client/builder/bid.go
  api/client/builder/client.go
  api/client/builder/client_test.go
  api/client/builder/types.go
  api/client/builder/types_test.go
  beacon-chain/blockchain/execution_engine.go
  beacon-chain/builder/testing/mock.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  changelog/james-prysm_builder-electra.md
  config/params/BUILD.bazel
  config/params/config.go
  config/params/config_test.go
  proto/prysm/v1alpha1/BUILD.bazel
  proto/prysm/v1alpha1/beacon_block.pb.go
  proto/prysm/v1alpha1/beacon_block.proto
  proto/prysm/v1alpha1/electra.ssz.go
  testing/middleware/builder/BUILD.bazel
  testing/middleware/builder/builder.go
Labels: Builder, Electra

#14818 Update to Go 1.23
  .bazelversion
  .github/actions/gomodtidy/Dockerfile
  .github/workflows/fuzz.yml
  .github/workflows/go.yml
  .golangci.yml
  MODULE.bazel.lock
  WORKSPACE
  api/grpc/grpcutils.go
  beacon-chain/blockchain/blockchain_test.go
  beacon-chain/cache/cache_test.go
  beacon-chain/db/slasherkv/slasherkv_test.go
  beacon-chain/execution/execution_chain_test.go
  beacon-chain/p2p/discovery_test.go
  beacon-chain/p2p/peers/peers_test.go
  beacon-chain/p2p/peers/scorers/scorers_test.go
  beacon-chain/rpc/BUILD.bazel
  beacon-chain/rpc/endpoints_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/beacon_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/attester.go
  beacon-chain/rpc/prysm/v1alpha1/validator/validator_test.go
  beacon-chain/slasher/BUILD.bazel
  beacon-chain/slasher/detect_attestations.go
  beacon-chain/slasher/service_test.go
  beacon-chain/sync/initial-sync/initial_sync_test.go
  beacon-chain/sync/sync_test.go
  changelog/nisdas_update_go_v1-23.md
  config/proposer/settings.go
  container/slice/slice.go
  deps.bzl
  go.mod
  go.sum
  proto/prysm/v1alpha1/attestation/aggregation/attestations/attestations_test.go
  runtime/logging/logrus-prefixed-formatter/BUILD.bazel
  runtime/logging/logrus-prefixed-formatter/formatter_test.go
  runtime/logging/logrus-prefixed-formatter/logrus_prefixed_formatter_suite_test.go
  testing/endtoend/components/web3remotesigner.go
  testing/endtoend/helpers/helpers.go
  testing/spectest/mainnet/phase0/epoch_processing/epoch_processing_test.go
  testing/spectest/minimal/phase0/epoch_processing/epoch_processing_test.go
  time/slots/slotutil_test.go
  tools/analyzers/errcheck/BUILD.bazel
  tools/analyzers/errcheck/analyzer.go
  tools/analyzers/errcheck/embedded_walker_test.go
  tools/bootnode/bootnode_test.go
  validator/db/kv/kv_test.go
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/keymanager.go
Labels: dependencies

#14823 Handle `AttesterSlashingElectra` everywhere in the codebase
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/transition/transition.go
  beacon-chain/core/transition/transition_test.go
  beacon-chain/db/kv/blocks.go
  beacon-chain/db/kv/key.go
  beacon-chain/db/kv/lightclient.go
  beacon-chain/db/kv/schema.go
  beacon-chain/db/kv/state.go
  beacon-chain/db/slasherkv/BUILD.bazel
  beacon-chain/db/slasherkv/pruning_test.go
  beacon-chain/db/slasherkv/slasher.go
  beacon-chain/db/slasherkv/slasher_test.go
  beacon-chain/rpc/eth/events/events_test.go
  changelog/radek_eip-7549-slasher-pt1.md
  changelog/radek_eip-7549-slasher-pt2.md
  config/params/configset_test.go
  config/params/loader_test.go
  config/params/testnet_config_test.go
  testing/util/attestation.go
  validator/client/attest.go
Labels: Electra

#14841 Update electra spec tests to beta.1
  WORKSPACE
  changelog/tt_new_spec_test.md
Labels: Electra

#14843 Sync: Integrate batch directly in `buildBwbSlices`.
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
  beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go
  beacon-chain/sync/validate_data_column.go
Labels: peerDAS

#14852 Electra blob sidecar API update
  beacon-chain/rpc/eth/blob/BUILD.bazel
  beacon-chain/rpc/eth/blob/handlers.go
  beacon-chain/rpc/eth/blob/handlers_test.go
  changelog/james-prysm_electra-blobs-api.md
Labels: Electra

#14844 Convert Phase0 slashing to Electra slashings at the fork
  beacon-chain/node/node.go
  beacon-chain/operations/slashings/BUILD.bazel
  beacon-chain/operations/slashings/mock/mock.go
  beacon-chain/operations/slashings/service.go
  beacon-chain/operations/slashings/service_attester_test.go
  beacon-chain/operations/slashings/service_new.go
  beacon-chain/operations/slashings/service_new_test.go
  beacon-chain/operations/slashings/types.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  changelog/radek_eip-7549-slasher-pt3.md
Labels: Electra

#14835 skip eth1data voting after electra
  beacon-chain/core/helpers/BUILD.bazel
  beacon-chain/core/helpers/legacy.go
  beacon-chain/core/helpers/legacy_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_eth1data.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
  changelog/james-prysm_electra-eth1voting.md
  testing/util/electra_state.go
Labels: Electra

#14833 Address @jtraglia's comments regarding Electra code
  api/server/structs/BUILD.bazel
  api/server/structs/conversions.go
  api/server/structs/conversions_block.go
  beacon-chain/core/electra/consolidations.go
  beacon-chain/core/helpers/validator_churn.go
  beacon-chain/core/helpers/validators.go
  beacon-chain/core/validators/validator.go
  beacon-chain/rpc/eth/beacon/handlers_pool_test.go
  beacon-chain/rpc/eth/config/handlers_test.go
  beacon-chain/state/state-native/getters_withdrawal.go
  changelog/radek_electra-nits.md
  config/params/config.go
  config/params/mainnet_config.go
  config/params/minimal_config.go
  consensus-types/blocks/factory.go
  container/slice/slice.go
  encoding/bytesutil/hex.go
  proto/engine/v1/electra.go
  proto/prysm/v1alpha1/attestation.pb.go
  proto/prysm/v1alpha1/attestation.proto
  proto/prysm/v1alpha1/beacon_state.proto
  proto/prysm/v1alpha1/validator.proto
  proto/ssz_proto_library.bzl
  validator/client/beacon-api/test-helpers/electra_beacon_block_test_helpers.go
Labels: >1 Approves Required, Electra

#14826 Handle errors as no-op for execution requests
  beacon-chain/blockchain/BUILD.bazel
  beacon-chain/blockchain/receive_block.go
  beacon-chain/core/electra/BUILD.bazel
  beacon-chain/core/electra/error.go
  beacon-chain/core/electra/error_test.go
  beacon-chain/core/electra/transition_no_verify_sig.go
  beacon-chain/core/electra/transition_no_verify_sig_test.go
  changelog/tt_fix_electra_core_processing.md
Labels: >1 Approves Required, Electra
