Repository OffchainLabs/prysm, pull requests merged in 2025-09, with the labels that each got.

#15658 update to v1.6.0-alpha.6
  WORKSPACE
  changelog/james-prysm_alpaha6-spec-tests.md
  config/params/loader_test.go
  specrefs/.ethspecify.yml
  specrefs/configs.yml
  specrefs/functions.yml
Labels: spec-tests

#15659 Remove BLS change broadcasting at the fork
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/broadcast_bls_changes.go
  beacon-chain/sync/broadcast_bls_changes_test.go
  beacon-chain/sync/fork_watcher.go
  changelog/potuz_remove_bls_broadcast.md
Labels: cleanup

#15660 refactor subscription code to enable peer discovery asap
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/startup/clock.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/custody.go
  beacon-chain/sync/fork_watcher.go
  beacon-chain/sync/fork_watcher_test.go
  beacon-chain/sync/rpc_status_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/service_test.go
  beacon-chain/sync/subscriber.go
  beacon-chain/sync/subscriber_test.go
  beacon-chain/sync/validate_bls_to_execution_change_test.go
  beacon-chain/sync/validate_sync_committee_message_test.go
  beacon-chain/sync/validate_sync_contribution_proof_test.go
  changelog/kasey_start-discovery-immediately.md
  config/params/config.go
  config/params/fork.go
Labels: networking, peer-das

#15498 adding remote singer changes for fulu
  changelog/james-prysm_fulu-web3signer.md
  testing/endtoend/deps.bzl
  validator/keymanager/remote-web3signer/BUILD.bazel
  validator/keymanager/remote-web3signer/keymanager.go
  validator/keymanager/remote-web3signer/keymanager_test.go
  validator/keymanager/remote-web3signer/types/BUILD.bazel
  validator/keymanager/remote-web3signer/types/mock/BUILD.bazel
  validator/keymanager/remote-web3signer/types/mock/mocks.go
  validator/keymanager/remote-web3signer/types/requests.go
  validator/keymanager/remote-web3signer/types/requests_test.go
Labels: web3signer, fulu

#14990 Optimize processing of slashings
  api/server/httprest/options.go
  beacon-chain/core/blocks/attester_slashing.go
  beacon-chain/core/blocks/attester_slashing_test.go
  beacon-chain/core/blocks/block_operations_fuzz_test.go
  beacon-chain/core/blocks/block_regression_test.go
  beacon-chain/core/blocks/exit.go
  beacon-chain/core/blocks/exit_test.go
  beacon-chain/core/blocks/proposer_slashing.go
  beacon-chain/core/blocks/proposer_slashing_test.go
  beacon-chain/core/electra/registry_updates.go
  beacon-chain/core/electra/transition_no_verify_sig.go
  beacon-chain/core/electra/withdrawals.go
  beacon-chain/core/epoch/epoch_processing.go
  beacon-chain/core/helpers/rewards_penalties.go
  beacon-chain/core/helpers/rewards_penalties_test.go
  beacon-chain/core/transition/transition_no_verify_sig.go
  beacon-chain/core/validators/validator.go
  beacon-chain/core/validators/validator_test.go
  beacon-chain/rpc/eth/rewards/service.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_slashings.go
  beacon-chain/state/interfaces.go
  beacon-chain/state/state-native/setters_churn.go
  changelog/radek_fix-max-epoch-calculation-once.md
  runtime/logging/logrus-prefixed-formatter/README.md
  testing/spectest/shared/common/operations/attester_slashing.go
  testing/spectest/shared/common/operations/proposer_slashing.go
  testing/spectest/shared/common/operations/voluntary_exit.go
Labels: optimization

#15666 spectests: add fulu fork transition tests for mainnet and minimal
  beacon-chain/blockchain/kzg/validation_test.go
  beacon-chain/rpc/eth/beacon/handlers_equivocation_test.go
  beacon-chain/rpc/prysm/v1alpha1/beacon/config_test.go
  changelog/ttsao_add-fulu-fork-transition-tests.md
  testing/spectest/mainnet/BUILD.bazel
  testing/spectest/mainnet/fulu__fork_transition__transition_test.go
  testing/spectest/minimal/BUILD.bazel
  testing/spectest/minimal/fulu__fork_transition__transition_test.go
  testing/spectest/shared/fulu/fork/BUILD.bazel
  testing/spectest/shared/fulu/fork/transition.go
Labels: spec-tests, fulu

#15643 deprecate /prysm/v1/beacon/blobs
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/prysm/beacon/handlers.go
  beacon-chain/rpc/prysm/beacon/handlers_test.go
  changelog/james-prysm_deprecate-publish-blos.md
Labels: api, deprecation

#15681 prevent ConnManager from pruning peers excessively
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/config.go
  beacon-chain/p2p/options.go
  beacon-chain/p2p/options_test.go
  changelog/kasey_fix-15607.md
Labels: networking, bug-fix

#15644 PeerDAS: Implement syncing in a disjoint network (Also know as "perfect PeerDAS" network).
  beacon-chain/core/peerdas/reconstruction.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/sync/data_column_sidecars.go
  beacon-chain/sync/data_column_sidecars_test.go
  beacon-chain/sync/initial-sync/BUILD.bazel
  beacon-chain/sync/initial-sync/blocks_fetcher.go
  beacon-chain/sync/initial-sync/blocks_fetcher_test.go
  beacon-chain/sync/initial-sync/service.go
  beacon-chain/sync/initial-sync/service_test.go
  beacon-chain/sync/rpc_beacon_blocks_by_root.go
  changelog/manu-peerdas-syncing-disjoint-network.md
Labels: peer-das

#15520 Retry logic for getBlobsV2 in peerDAS
  beacon-chain/blockchain/kzg/kzg.go
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_test.go
  beacon-chain/blockchain/receive_block.go
  beacon-chain/blockchain/receive_block_test.go
  beacon-chain/blockchain/setup_test.go
  beacon-chain/core/peerdas/BUILD.bazel
  beacon-chain/core/peerdas/das_core.go
  beacon-chain/core/peerdas/das_core_test.go
  beacon-chain/core/peerdas/p2p_interface_test.go
  beacon-chain/core/peerdas/reconstruction.go
  beacon-chain/core/peerdas/reconstruction_test.go
  beacon-chain/core/peerdas/validator.go
  beacon-chain/core/peerdas/validator_test.go
  beacon-chain/execution/BUILD.bazel
  beacon-chain/execution/engine_client.go
  beacon-chain/execution/engine_client_test.go
  beacon-chain/execution/testing/BUILD.bazel
  beacon-chain/execution/testing/mock_engine_client.go
  beacon-chain/p2p/BUILD.bazel
  beacon-chain/p2p/broadcaster.go
  beacon-chain/p2p/broadcaster_test.go
  beacon-chain/p2p/interfaces.go
  beacon-chain/p2p/testing/BUILD.bazel
  beacon-chain/p2p/testing/fuzz_p2p.go
  beacon-chain/p2p/testing/mock_broadcaster.go
  beacon-chain/p2p/testing/p2p.go
  beacon-chain/rpc/lookup/blocker_test.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
  beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/data_columns_reconstruct.go
  beacon-chain/sync/data_columns_reconstruct_test.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_beacon_blocks_test.go
  beacon-chain/sync/subscriber_data_column_sidecar.go
  beacon-chain/verification/data_column_test.go
  changelog/satushh-getblobsv2-retry.md
  specrefs/.ethspecify.yml
  specrefs/functions.yml
  testing/util/fulu.go
Labels: peer-das

#15688 Change insertchain
  beacon-chain/blockchain/process_block.go
  beacon-chain/blockchain/process_block_helpers.go
  beacon-chain/blockchain/setup_forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
  beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
  changelog/potuz_change_insertchain.md
Labels: cleanup

#15610 Get blob fulu
  api/server/structs/endpoints_beacon.go
  beacon-chain/rpc/endpoints.go
  beacon-chain/rpc/endpoints_test.go
  beacon-chain/rpc/eth/blob/BUILD.bazel
  beacon-chain/rpc/eth/blob/handlers.go
  beacon-chain/rpc/eth/blob/handlers_test.go
  beacon-chain/rpc/lookup/BUILD.bazel
  beacon-chain/rpc/lookup/blocker.go
  beacon-chain/rpc/lookup/blocker_test.go
  beacon-chain/rpc/options/BUILD.bazel
  beacon-chain/rpc/options/options.go
  beacon-chain/rpc/testutil/BUILD.bazel
  beacon-chain/rpc/testutil/mock_blocker.go
  changelog/james-prysm_get-blob-fulu.md
Labels: api, fulu

#15705 PeerDAS: Modify the reconstruction and reseed process.
  beacon-chain/blockchain/testing/mock.go
  beacon-chain/db/filesystem/data_column.go
  beacon-chain/sync/BUILD.bazel
  beacon-chain/sync/data_columns_reconstruct.go
  beacon-chain/sync/data_columns_reconstruct_test.go
  beacon-chain/sync/options.go
  beacon-chain/sync/service.go
  beacon-chain/sync/subscriber_beacon_blocks.go
  beacon-chain/sync/subscriber_data_column_sidecar.go
  changelog/manu-peerdas-reconstruction-delay.md
Labels: peer-das, fulu, bug-fix

#15687 Fix prysmctl panic when baseFee is not set in genesis.json
  changelog/muzry_fix_prysmctl_panics.md
  cmd/prysmctl/testnet/BUILD.bazel
  cmd/prysmctl/testnet/generate_genesis.go
  cmd/prysmctl/testnet/generate_genesis_test.go
Labels: bug-fix

#15743 flipping if statement check to fix da metric
  beacon-chain/blockchain/receive_block.go
  changelog/james-prysm_fix-da-metric.md
Labels: tools, bug-fix
